### ISSUE TITLE
healpy imports in gammapy.maps

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1000]
@woodmd - The Gammapy CI is failing because of the top-level `healpy` import in `gammapy.maps`:
https://travis-ci.org/gammapy/gammapy/jobs/226312428#L1790

Is it OK if I fix this now? Or do you have uncommitted changes in `gammapy.maps`?

cc @joleroi

**Comment by cdeil** [comment]
💯  + 💯  + 💯  + 💯  + 💯  + 💯  + 💯  + 💯  + 💯  + 💯  
We have issues!

**Comment by cdeil** [comment]
Fixed in #1003. I'm not a huge fan any more of the delayed imports in many methods.

For `gammapy/maps/tests/test_hpx.py` I've put `pytest.importorskip('healpy')` at the top, instead of `@requires_dependency('healpy')` on each test.

We could investigate using something like that at the top of files like `gammapy/maps/hpx.py` as well.

**Comment by woodmd** [comment]
Have you given any thought to making healpy a core dependency?  For now the delayed import approach seems fine but once you have other gammapy modules that depend on HPX functionality from `gammapy.maps` it might get cumbersome to isolate imports like this.

**Comment by cdeil** [comment]
> Have you given any thought to making healpy a core dependency? 

Yes.

I'd like to avoid making `healpy` a core dependency, and have Gammapy install and import always work if only Numpy Astropy are there.

We can implement a nicer solution if the delayed imports in the methods become too annoying (e.g. `from gammapy.utils.dependency import healpy as hp` at the top, which does a few lines of magic to import healpy or to give a shim that will raise an ImportError or other good error on any attribute access.
