### ISSUE TITLE
Fix observation grouping functionality in gammapy.spectrum

### ISSUE THREAD

**Issue by joleroi** [gammapy/gammapy#1005]
In https://github.com/gammapy/gammapy/commit/926855652eba59a1d2e3188987b329c6dd9daea1 I remove ``gammapy/spectrum/obs_group.py`` from the high level docs because it is untested and completely broken. The test is xfailed since [more than 1 year](https://github.com/gammapy/gammapy/blame/master/gammapy/spectrum/tests/test_obs_group.py#L11). After discussing with @JouvinLea we decided to keep this files as starting point for reimplementing the functionality at some point in the future.

**Comment by cdeil** [comment]
Fixed by removing this code. See #1575 .
