### ISSUE TITLE
testCombinedModel3DIntConvolveEdisp fail with Numpy 1.10

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1012]
In #1011 I noticed this issue in the build that uses Numpy 1.10: https://travis-ci.org/gammapy/gammapy/jobs/228110585#L2003

`testCombinedModel3DIntConvolveEdisp` fails because at https://github.com/gammapy/gammapy/blob/24db8c055d249494d66067ef58cf3feb15bf8f79/gammapy/cube/sherpa_.py#L425 `numpy.moveaxis` is called.

The moveaxis function was added in Numpy 1.11 (see https://github.com/numpy/numpy/pull/6630/files#diff-3ea1c0941c98bf78c98f835bc8a4aff1R106) which was released only a year ago (see https://pypi.python.org/pypi/numpy/1.11.0).

In https://github.com/numpy/numpy/pull/6630 they mention that `np.moveaxis` is just a more intuitive API than `np.rollaxis`, so since it's just one case I'd suggest we switch to `np.rollaxis` to keep compabibility with Numpy 1.10 for Gammapy

@adonath - Can you do it? (If no, assign to me and I'll do this tomorrow evening.)

**Comment by adonath** [comment]
Closed via #1017.
