### ISSUE TITLE
conda install gammapy.v0.6

### ISSUE THREAD

**Issue by robertazanin** [gammapy/gammapy#1019]
When I try to install the last stable version 
conda install -c openastronomy gammapy
it installs version 0.6.dev3938

**Comment by cdeil** [comment]
@robertazanin - try `conda install -c astropy gammapy`. Does it work?

The Gammapy 0.6 conda package is in the "astropy" channel, not the "openastronomy" channel.
I've fixed the docs that were mentioning the "openastronomy" channel just now in  7e58d4ff089dd68b67b25f0de74eb15e9a7bde98 .

**Comment by cdeil** [comment]
I'm closing this issue now.

@robertazanin - If `conda install -c astropy gammapy` doesn't install gammapy 0.6 for you, please re-open the issue and copy & paste the full  output from that command here.
