### ISSUE TITLE
KeyError: u'spec_index' when gammapy.test('catalog')  

### ISSUE THREAD

**Issue by Bultako** [gammapy/gammapy#1024]
Hi there
I've been installing last release v0.6
When doing the battery tests I find KeyError: u'spec_index' in tests_gammacat.py

--

**Comment by adonath** [comment]
@Bultako Thanks for reporting this issue! Can you update your `gammapy-extra` repository and see if it resolves the issue? I think this test fails is because of a recent update of https://github.com/gammapy/gammapy-extra/blob/master/datasets/catalogs/gammacat.fits.gz (see [here](https://github.com/gammapy/gammapy-extra/blob/master/datasets/catalogs/gammacat.fits.gz)).

**Comment by adonath** [comment]
I just noticed: you probably updated `gammapy-extra` already and that's why the error occurs. So to resolve that have to update to the latest (development) gammapy version.

@cdeil Can those issues avoided in future, if we introduce `gammapy-extra` as a git submodule?

**Comment by Bultako** [comment]
Yes
installing last gammapy devel version 0.7.dev4612 with an updated gammapy-extra repo solved the issue. All battery tests passed. I think the point is, as you say, how to link gammapy-extra repo with gammapy (at least with a a tagged release). Or maybe removing/modifying the tests that need gammapy-extra repo.

**Comment by cdeil** [comment]
Yes, we need to change our test setup to version-couple any files we access with the Gammapy version. It's non trivial to set this up in a good way, most files are from gammapy-extra, but we have other files as well that need to be dealt with. @adonath - let's discuss offline or in #288.

For now, users shouldn't run tests. Keeping this issue open as a reminder until it's resolved.
@Bultako - Thanks for the issue report and apologies for the inconvenience.

**Comment by cdeil** [comment]
I'm closing this issue as duplicate.

We still don't have version coupling of the Gammapy code with the example files used in tests / docs, but there's  #1131 and other issues open that cover that, and it doesn't help to distribute the discussion across many issues and to keep those open.
