### ISSUE TITLE
CTA spectrum forward-folding fit

### ISSUE THREAD

**Issue by emmaow** [gammapy/gammapy#1030]
Hi,

we are trying to simulate some spectrum using the CTA response. We followed the nice tutorial under: https://nbviewer.jupyter.org/github/gammapy/gammapy-extra/blob/master/notebooks/cta_simulation.ipynb
Once we have the number of excess, on, off etc, and read the performance file, can we do a forward folding to the data to recover the initial spectrum? is there any example I can follow to learn how to do this? 
Thanks!!
Emma

**Comment by joleroi** [comment]
Hi @emmaow 

I think the easiest way is to follow the instructions in [this notebook](https://nbviewer.jupyter.org/github/gammapy/gammapy-extra/blob/master/notebooks/spectrum_analysis.ipynb). I talks about how to extract spectra from IACT data first - you can skip all that. But there's a section called 'Fit Spectrum' that explains how to fit a given spectral model to a ``SpectrumObservation`` (what you've produced in the ``cta_simulation.ipynb``.

I would suggest to leave this issue open, in case you have further questions.

**Comment by emmaow** [comment]
Hi Johannes,

thanks!! that works beautifully. 

Maybe, for some tontos like me, it would be useful to include just a couple of lines more in the CTA notebook:

http://nbviewer.jupyter.org/github/gammapy/gammapy-extra/blob/master/notebooks/cta_simulation.ipynb <http://nbviewer.jupyter.org/github/gammapy/gammapy-extra/blob/master/notebooks/cta_simulation.ipynb>

model2fit = models.PowerLaw(index = 2.1 * u.Unit(''),
                 amplitude = 2e-11 * u.Unit('cm-2 s-1 TeV-1'),
                 reference = 1. * u.TeV)



ReconstructedFit = SpectrumFit(obs_list = simu, model=model2fit)
ReconstructedFit.fit()
Reconstructed.est_errors()
Results = fit_crab.result
ax0, ax1 = Results[0].plot(figsize=(8,8))
print(Results[0])

So you have the complete thread
Cheers

**Comment by joleroi** [comment]
I'm happy to hear that the fitting worked for you. We're currently trying to restructure/improve the documentation in gammapy, so for now I just added a link to to ``spectrum_analysis`` notebook at the end of the ``cta_simulation`` notebook until we have figured out how to structure the docs in a clearer fashion.

**Comment by joleroi** [comment]
Done in https://github.com/gammapy/gammapy-extra/commit/c4a7cd3c00e94709751e0502673725903ce0e057
