### ISSUE TITLE
Remove SkyImage unit attribute?

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1044]
Currently `SkyImage` has a unit attribute separate from the data attribute, whereas `SkyCube` doesn't. As far as I know, in both cases one can store a `Quantity` in `data`.

This leaves the two classes inconsistent and confusing for the user, and I'd like to make them work the same by either removing `unit` from `SkyImage` or adding a separate `unit` attribute to `SkyCube`.

Naively (without having reviewed the SkyImage code and callers and tests) I would think that removing the separate `unit` attribute and supporting a `Quantity` data member in `SkyImage` would be the better direction to resolve this.
A somewhat related question is whether we should enforce `data` to be a `Quantity`, or whether we should allow the plain `numpy.ndarray` case also.

@adonath @joleroi - Thoughts?

**Comment by adonath** [comment]
The actual (bigger) question to answer here is whether the `.data` attributes should be plain `numpy.ndarray` or `Quantity` objects. I think the answer depends on what we need more often. For sky images there are a lot of numerical algorithms and calls to scipy functions (convolution, smoothing, ts images, etc), that do not change the units or where the units have to be stripped of anyway. But on the other hand it's nice e.g. when you can convert a surface brightness image to a flux image by multiplying with the solid angle image etc. I think my 51:49 preference would be to leave the `.data` attribute as a plain `numpy.ndarray` and introduce a `.unit` and `.quantity` attribute with a setter, as we did for the [gammapy.utils.modeling.Parameter](https://github.com/gammapy/gammapy/blob/master/gammapy/utils/modeling.py#L104) class.

**Comment by cdeil** [comment]
@adonath - Agree, I feel exactly like you said, and would also propose the solution of having `.unit` be separate. This was also what I discussed with @woodmd when we talked about `gammapy.maps` a few weeks ago (where so for `unit` isn't added at all yet).

I can try to make the change in the coming days, but I might postpone it to v0.8.
Help welcome of course.

**Comment by cdeil** [comment]
I'm closing this old issue about SkyImage units. (which is similar to https://github.com/gammapy/gammapy/issues/1050#issuecomment-386324524)  Let's all transition to gammapy.maps and put our efforts there. Units are implemented there and should work flawlessly; if something is buggy or missing in gammapy.maps, please open a new issue.
