### ISSUE TITLE
Fix absorbed spectral model evaluate_error

### ISSUE THREAD

**Issue by jjlk** [gammapy/gammapy#1046]
Hi @cdeil, @joleroi  and @adonath , 

I'd like to know you if get any ideas how to deal with the problem related to the error propagation of the `AbsorbedSpectralModel` model. For now I can fit the model but I can't get the flux points and the butterfly associated to the minimisation.

As a reminder, the `AbsorbedSpectralModel.evaluate` function returns the product: 
```
        flux = self.spectral_model.evaluate(energy=energy, **kwargs)
        absorption = self.absorption.evaluate(energy=energy,
                                              parameter=parameter)
        return flux * absorption
```

The `Absorption.evaluate` function calls the `NDDataArray.evaluate`function:
```
    def evaluate(self, energy, parameter):
        """Evaluate model for energy and parameter value."""
        return self.data.evaluate(energy=energy, parameter=parameter)
```

When I try to compute the butterfly by calling the `SpectrumFitResult.butterfly` function I get the following errors related to the fact that the `NDDataArray` can not handle the `uncertainties` package: 
```
/Users/julien/Documents/WorkingDir/Tools/python/anagammapy/develop/spectral_reco/spectral_model.py in <module>()
    183 model.plot(energy_range=energy_range)
    184 result.model.plot(energy_range=energy_range)
--> 185 result.butterfly().plot(energy_range=energy_range)
    186 
    187 seg = SpectrumEnergyGroupMaker(obs=simu)

/Users/julien/Documents/WorkingDir/Tools/python/gammapy/gammapy/spectrum/results.pyc in butterfly(self, energy, flux_unit)
    223                                                     self.fit_range[1], 100)
    224 
--> 225         flux, flux_err = self.model.evaluate_error(energy)
    226 
    227         butterfly = SpectrumButterfly()

/Users/julien/Documents/WorkingDir/Tools/python/gammapy/gammapy/spectrum/models.pyc in evaluate_error(self, energy)
     95         unit = self(energy).unit
     96         upars = self.parameters._ufloats
---> 97         uarray = self.evaluate(energy.value, **upars)
     98         return self._parse_uarray(uarray) * unit
     99 

/Users/julien/Documents/WorkingDir/Tools/python/gammapy/gammapy/spectrum/models.pyc in evaluate(self, energy, **kwargs)
   1276         flux = self.spectral_model.evaluate(energy=energy, **kwargs)
   1277         absorption = self.absorption.evaluate(energy=energy,
-> 1278                                               parameter=parameter)
   1279         return flux * absorption

/Users/julien/Documents/WorkingDir/Tools/python/gammapy/gammapy/spectrum/models.pyc in evaluate(self, energy, parameter)
   1228     def evaluate(self, energy, parameter):
   1229         """Evaluate model for energy and parameter value."""
-> 1230         return self.data.evaluate(energy=energy, parameter=parameter)
   1231 
   1232 

/Users/julien/Documents/WorkingDir/Tools/python/gammapy/gammapy/utils/nddata.pyc in evaluate(self, method, **kwargs)
    150         for axis in self.axes:
    151             # Extract values for each axis, default: nodes
--> 152             temp = Quantity(kwargs.pop(axis.name, axis.nodes))
    153             # Transform to correct unit
    154             temp = temp.to(axis.unit).value

/Users/julien/anaconda2/lib/python2.7/site-packages/astropy/units/quantity.pyc in __new__(cls, value, unit, dtype, copy, order, subok, ndmin)
    321                  isinstance(value.item(() if value.ndim == 0 else 0),
    322                             numbers.Number))):
--> 323             raise TypeError("The value must be a valid Python or "
    324                             "Numpy numeric type.")
    325 

TypeError: The value must be a valid Python or Numpy numeric type.
```

Do you have any idea how to solve this problem? To be honest I know nothing about the `uncertainties` package and I do not have a clear vision of the limitation of the `NDDataArray` class. You can find an example on the following link: https://gist.github.com/jjlk/654f3359af0aa0abd10b4281d80ce69b.

Thanks in advance!

PS: the scientific interest is to estimate the redshift of a blazar observed with CTA!

**Comment by adonath** [comment]
The problem here is that `NDData.evaluate()` is called with a `uncertainties.ufloat` object as parameter, which doesn't cast into  a `Quantity` object. 

One could try to specifically handle the case where the parameter are `uncertainties.uarray` objects, e.g. as done in [ExponentialCutoffPowerLaw.evaluate()](https://github.com/gammapy/gammapy/blob/master/gammapy/spectrum/models.py#L714), but I have to think about it a bit more. Does the solution need to include the uncertainty of the absorption model itself? Or is it only about propagating the spectral model error through the absorption model and neglecting the uncertainty of the latter?

**Comment by jjlk** [comment]
Hi @adonath , thanks for your reply and sorry for the delay.

> Does the solution need to include the uncertainty of the absorption model itself? Or is it only about propagating the spectral model error through the absorption model and neglecting the uncertainty of the latter?

For now it's level 1, so I do not consider that the absorption model as uncertainties. I'm only interested to propagate the errors of the parameters (e.g., phi0, gamma, z) through the spectral model (e.g., abs(z) * pwl(phi0,gamma)). Do you think there is an easy/quick patch I could try to obtain a butterfly and spectral points?

Thanks!

**Comment by cdeil** [comment]
This issue of uncertainty handling and error propagation is a general one for Gammapy, let's try to find a good solution: #2255

**Comment by cdeil** [comment]
This should be fixed by #2585 .

@luca-giunti - could you please change this to a small test case for absorbed model?
https://github.com/gammapy/gammapy/pull/2585/files#diff-35228bd33202259fb76a617dde437cb8R588-R592
(similar to how you did it for Naima yesterday, just add a `evaluate_error` call and one assert at the end of an existing test)

**Comment by luca-giunti** [comment]
Sure!

**Comment by cdeil** [comment]
@luca-giunti added a regression test in #2603 showing that it now works.
