### ISSUE TITLE
SkyCube.read: units lost

### ISSUE THREAD

**Issue by robertazanin** [gammapy/gammapy#1049]
I write my SkyCube obj in a file
 exposure_cube.write('exposure_cube.fits', overwrite=True)

Sky cube None with shape=(10, 300, 500) and unit=m2 s:
 n_lon:      500  type_lon:    RA---TAN         unit_lon:    deg
 n_lat:      300  type_lat:    DEC--TAN         unit_lat:    deg
 n_energy:    10  unit_energy: TeV

when I read it out 
exposure_cube = SkyCube.read('exposure_cube.fits')

I lost info about the exposure units

Sky cube counts with shape=(10, 300, 500) and unit=ct:
 n_lon:      500  type_lon:    RA---TAN         unit_lon:    deg
 n_lat:      300  type_lat:    DEC--TAN         unit_lat:    deg
 n_energy:    10  unit_energy: TeV

**Comment by adonath** [comment]
Currently the `I/O` format has to be specified by hand and the default is `'fermi-counts'` (see [SkyCube.write()](http://docs.gammapy.org/en/latest/api/gammapy.cube.SkyCube.html#gammapy.cube.SkyCube.write)). Could you try:
```
exposure_cube.write('exposure_cube.fits', overwrite=True, format='fermi-exposure')
exposure_cube = SkyCube.read('exposure_cube.fits', format='fermi-exposure')
```
And see if that works?

**Comment by robertazanin** [comment]
Yep! Thanks! 
Even though it sets the Energy to MeV :)
