### ISSUE TITLE
FluxPointEstimator.compute_points(): missing uncertainties module

### ISSUE THREAD

**Issue by cosimoNigro** [gammapy/gammapy#1052]
Hi all,

I am trying to reproduce the steps in
https://nbviewer.jupyter.org/github/gammapy/gammapy-extra/blob/master/notebooks/spectrum_analysis.ipynb
with my own FITS files that contains IACT observations.
I got stuck at the point of creating spectral points, when I try to execute the ```compute_points()``` from FluxPointEstimator
```python
fpe = FluxPointEstimator(
    obs=stacked_obs,
    groups=seg.groups,
    model=fit_result[0].model,
)
fpe.compute_points()
```
I have the following error
```python
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-27-6c3695bead7f> in <module>()
      4     model=fit_result[0].model,
      5 )
----> 6 fpe.compute_points()

/afs/ifh.de/group/amanda/scratch/cosimo/miniconda2/lib/python2.7/site-packages/gammapy/spectrum/flux_point.pyc in compute_points(self)
    589                 continue
    590 
--> 591             row = self.compute_flux_point(group)
    592             rows.append(row)
    593 

/afs/ifh.de/group/amanda/scratch/cosimo/miniconda2/lib/python2.7/site-packages/gammapy/spectrum/flux_point.pyc in compute_flux_point(self, energy_group)
    605 
    606         return self.fit_point(
--> 607             model=model, energy_group=energy_group, energy_ref=energy_ref,
    608         )
    609 

/afs/ifh.de/group/amanda/scratch/cosimo/miniconda2/lib/python2.7/site-packages/gammapy/spectrum/flux_point.pyc in fit_point(self, model, energy_group, energy_ref)
    681         e_max = energy_group.energy_range.max
    682         e_min = energy_group.energy_range.min
--> 683         diff_flux, diff_flux_err = res.model.evaluate_error(energy_ref)
    684         return OrderedDict(
    685             e_ref=energy_ref,

/afs/ifh.de/group/amanda/scratch/cosimo/miniconda2/lib/python2.7/site-packages/gammapy/spectrum/models.pyc in evaluate_error(self, energy)
     94 
     95         unit = self(energy).unit
---> 96         upars = self.parameters._ufloats
     97         uarray = self.evaluate(energy.value, **upars)
     98         return self._parse_uarray(uarray) * unit

/afs/ifh.de/group/amanda/scratch/cosimo/miniconda2/lib/python2.7/site-packages/gammapy/utils/modeling.pyc in _ufloats(self)
    278         Return dict of ufloats with covariance
    279         """
--> 280         from uncertainties import correlated_values
    281         values = [_.value for _ in self.parameters]
    282 

ImportError: No module named uncertainties
```
I am using the 0.6 release of gammapy, installed through miniconda. Am I missing some module?

Unluckily the documentations looks a bit outdated, referring to 
http://docs.gammapy.org/en/latest/spectrum/flux_points.html
I don't see alternative methods for spectral points computation: indeed
```DifferentialFluxPoints``` it is not anymore in gammapy.spectrum
and the ```SpectrumFit``` object does not have anymore the ```compute_fluxpoints``` method as shown in the documentation.

Thanks a lot for your help!

Cosimo

**Comment by cdeil** [comment]
@cosimoNigro - Indeed `uncertainties` is  separate Python package that you should install:
https://pypi.python.org/pypi/uncertainties

It is available at https://anaconda.org/conda-forge/uncertainties , so you should be able to get it like so:
```
conda install -c conda-forge uncertainties
```
If that doesn't work, you can always try:
```
pip install uncertainties
```

It's an optional dependency for Gammapy, that we use for parameter uncertainty propagation to derived quantities like integral fluxes.

Yes, our docs are outdated. I'll keep this issue open as a reminder to make it better (and for you to ask further questions if you like).

**Comment by cosimoNigro** [comment]
**Thanks a lot** @cdeil! I didn't think it could be an external package, my bad.

**Comment by cdeil** [comment]
I'm closing this old issue.

Of course, generally our docs can / should be improved, but there's no concrete action item described here, so the old issue isn't very helpful in getting towards better docs.

This is what we have now for install docs:
http://docs.gammapy.org/en/latest/install/index.html
Pull requests to improve welcome any time.
