### ISSUE TITLE
Test fails with pytest 3.1

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1056]
Since today we have two builds that fail on travis-ci in Gammapy:
https://travis-ci.org/gammapy/gammapy/jobs/238624107

As far as I can see, the cause is that those builds since today use the recently release pytest 3.1, which accidentally changed something about the warnings filter, and now 1000s of warnings appear and the builds on travis-ci fail because the log is too long.

Maybe this was fixed in the pytest 3.1.1 release two days ago?
https://docs.pytest.org/en/latest/changelog.html#pytest-3-1-1-2017-05-30

@bsipocz @astrofrog - Do you know anything about this? Is this seen for other Astropy packages too? Should we change something in Gammapy or `ci-helpers` or will simply waiting a few days resolve the issue, because  `pytest 3.1.1` makes it to the appropriate conda channel?

**Comment by bsipocz** [comment]
@cdeil - Brilliant. I haven't seen these error yet, so as a first approach would suggest to try to deal with it in gammapy, but any workaround for ``ci-helpers`` is also welcome.

Could you test how it behaves with pytest 3.1.1? As I see it's already available both on conda-forge and the defaults channels. You can use ``PYTEST_VERSION=1.3.1`` in travis.yml to make sure that version is picked up.

**Comment by bsipocz** [comment]
@cdeil - Looking at your logs again, I'm afraid pytest 1.3.1 isn't a solution, as that is the version already been used.

**Comment by bsipocz** [comment]
@cdeil - here is a workaround: https://docs.pytest.org/en/latest/warnings.html#disabling-warning-capture

Add  ``addopts = -p no:warnings`` in ``setup.cfg`` under ``[pytest]``

Also I wonder whether you're planning to drop the astropy bundled pytest? I have a wip branch (generated by a script some time back) for that cleanup, so can easily open a PR.

**Comment by cdeil** [comment]
I think this old issue has been resolved a few months ago. Closing now.
