### ISSUE TITLE
Compute likelihood without fit

### ISSUE THREAD

**Issue by ctrichard** [gammapy/gammapy#1059]
Hi everyone,

Is there a way to compute the likelihood of a model on a given dataset without running the fit using SpectrumFit ? 

Up to now, I freeze all parameters except one with a short fit range and run the fit. It works but it's pretty ugly...

Cheers,
Cyril

**Comment by joleroi** [comment]
Hi @ctrichard 

Do you know about the [likelihood_1d](http://docs.gammapy.org/en/latest/api/gammapy.spectrum.SpectrumFit.html?highlight=SpectrumFit#gammapy.spectrum.SpectrumFit.likelihood_1d) function? It's not specifically meant for your problem, but you can achieve what you want.

```
In [1]: from gammapy.spectrum.models import PowerLaw

In [2]: import astropy.units as u

In [4]: from gammapy.spectrum import SpectrumFit, SpectrumObservation

In [5]: obs = SpectrumObservation.read('$GAMMAPY_EXTRA/datasets/hess-crab4_pha/pha_obs23523.fit
   ...: s')

In [6]: fit = SpectrumFit(obs_list=obs, model=None)

In [7]: model = PowerLaw(index = 2 * u.Unit(''),
   ...: amplitude=2e-11 * u.Unit('cm-2 s-1 TeV-1'),
   ...: reference = 1 * u.TeV)

In [8]: fit.likelihood_1d(model=model, parname='index', parvals=[2,3])

Out[8]: array([ 45.81979616,  84.96187135])
```  

I guess it would be nice to have a method like ``compute_likelihood`` on ``SpectrumObservation``?

**Comment by ctrichard** [comment]
Hi Johannes,
Thank you, That's exactly what I needed !
Cheers,
Cyril

**Comment by joleroi** [comment]
Alright, so I'm closing this.
