### ISSUE TITLE
Fitting with a combined spectral model

### ISSUE THREAD

**Issue by Ozi1Kenobi** [gammapy/gammapy#1060]
Dear all,

I'm quite new in gammapy and trying to perform a fit to FITS data by using combined spectral models. I wondered if there is a way to provide a combined spectral model (like PowerLaw + PowerLaw or PowerLaw + ExponentialCutoffPowerLaw) as an input argument to SpectrumFit in gammapy by using gammapy.spectrum.models.

For example 
combinedModel = PowerLaw1 (pars ....) + PowerLaw2 (pars ...)
joint_fit = SpectrumFit(obs_list = stacked_obs, 
                                    model=combinedModel,
                                    forward_folded=True,
                                    stat='wstat')

Or alternatively, is it possible to provide sherpa models as an input argument to SpectrumFit, since in sherpa one can define a combined spectral model as

combinedSherpaModel = powlaw1d.sr1 + powlaw1d.sr2

A simple code example would be very helpful. Thanks in advance.

Cheers,
Ozi

**Comment by joleroi** [comment]
Hi,

fitting combined spectral models with gammapy is possible. There is, however, no high-level language to define a user model with operators like in sherpa. Instead, you have to define a new spectral model. There is an example how to to this in [this notebook](https://github.com/gammapy/gammapy-extra/blob/master/notebooks/spectrum_simulation.ipynb), section 'User defined model'. Then you can use this model in the ``SpectrumFit``.

You can also use sherpa directly to do the fits. This is explained in [this notebook](https://github.com/gammapy/gammapy-extra/blob/master/notebooks/spectrum_fitting_with_sherpa.ipynb).

In case you choose to follow the first option, it would be very valuable to us if you could provide feedback, if you had problems defining your model and how you think the way defining user models could be improved. I will leave this issue open for that purpose.

**Comment by Ozi1Kenobi** [comment]
Hi,

Thank you very much for the quick response and documentation. I will try both and provide you feedback.

**Comment by joleroi** [comment]
Note that I added a [new notebook](https://github.com/gammapy/gammapy-extra/blob/master/notebooks/spectrum_models.ipynb) to our documentation that explains a little bit how spectral models work in gammapy. This also contains the example how to define a custom model, now.

**Comment by Ozi1Kenobi** [comment]
Hi Johannes, 

I implemented the following code to models.py :

class CombinedPLFixERange(SpectralModel):
    def __init__(self, index1, amplitude1, index2, amplitude2, reference):
        self.parameters = ParameterList([
                Parameter('index1', index1, parmin=0, parmax=10.),
                Parameter('amplitude1', amplitude1, parmin=0),
                Parameter('index2', index2, parmin=0, parmax=10.),
                Parameter('amplitude2', amplitude2, parmin=0),
                Parameter('reference', reference, frozen=True)
        ])

    def evaluate(self, energy, index1, amplitude1, index2, amplitude2, reference):
        pl1 = PowerLaw.evaluate(energy=energy, index=index1, amplitude=amplitude1, reference=reference)
        pl2 = PowerLaw.evaluate(energy=energy, index=index2, amplitude=amplitude2, reference=reference)
        return pl1 + pl2

I also added 'CombinedPLFixERange' string to __all__ = []

You can find some basic test results on HESS Crab data (prod3) in attachments (
[crabTestResultsForCombinedPL.txt](https://github.com/gammapy/gammapy/files/1059060/crabTestResultsForCombinedPL.txt)
) for comparison. This approach has one problem that both power-laws are fitted in the same energy interval. This can be useful only if the 2nd power-law (lets call it contamination for ex) index is not so hard, otherwise, for ex. if its harder than the 1st power-law (say the source spectrum itself), there's a danger that at high energies, 2nd power-law may contribute more that 1st power-law. 

For this reason, I think using PowerLaw2 model, which is basically the same as PowerLaw but uses intergral flux as a norm parameter, allowing determination of energy range. So a better approach would be PowerLaw2 + PowerLaw2 (the first one can still be a PL), so one can set the energy range (emin2, emax2) for the contamination part and we would be safer at high energies. This is also valid if one wants to use PowerLawExponentialCutoff + PowerLaw, so if we have a hard power-law contamination model and fit in the same range, then the contamination part will go on while the source component cuts off above certain energy (Ecut). I think that in the case of PowerLaw2 + PowerLaw2, emin1 and emin2 parameters can be same, while the fit range is [emin1, emax1].

In most cases, contaminating spectral components would not be significant above few TeVs (at high energies in general). So I gave a try to PowerLaw2 version. 

-- When fitting by using simple PowerLaw2 model, I could not make the fit work. The first problem comes from definition of integral() function for PowerLaw2 class in models.py. One can overcome this problem by modifying the definition as below, 

   def integral(self, emin, emax): --> def integral(self, emin, emax, **kwargs):

like it was done for the other models. Otherwise one would get "TypeError: integral() got an unexpected keyword argument 'intervals'". 

After modifying it, and trying to perform a fit by using PowerLaw2 function, I got the following error when I use u.Unit('cm-2 s-1') for the amplitude parameter :

File "/usr/local/lib/python3.5/site-packages/astropy/units/core.py", line 1855, in __call__
    raise TypeError("None is not a valid Unit")
TypeError: None is not a valid Unit 

and when I use u.Unit('cm-2 s-1 TeV-1') :

File "/usr/local/lib/python3.5/site-packages/astropy/units/core.py", line 881, in _apply_equivalencies
    unit_str, other_str))
astropy.units.core.UnitConversionError: 'cm2 / TeV' and '' (dimensionless) are not convertible

It would be quite helpful to make PowerLaw2 work before going further. Or am I missing something somewhere ? What do you think ? 

Cheers,
Ozi

**Comment by joleroi** [comment]
Hi @Ozi1Kenobi 

thanks for your detailed feedback. Do I understand you correctly that you want to set the energy range where each power law contributes separately for each component? In this case I have some comments
* The parameters ``e_min`` and ``e_max`` in ``PowerLaw2`` are **not** the energy range where the power law is fitted. The energy range is only controlled by the ``fit_range`` parameter of ``SpectrumFit``. The ``emin`` and ``emax`` parameters of ``PowerLaw2`` control the energy range in which the integral flux ``F_0`` of the data is compared to the model prediction.
* The integral method of ``PowerLaw2`` seems to be broken, indeed. In case you would like to make a pull request to gammapy in order to fix it, I can explain you how to do that (if you dont't know it already). I think this is a very good use case to learn how to contribute to an open source package. Otherwise, I fill fix it myself.
* How did you set the unit for the ``amplitude`` parameter of ``PowerLaw2``?
* Coming back to the original problem: What you are looking for is basically a power law with 2 breaks, where in the intermediate energy range the model is the sum of both power laws, right? The easiest way to achieve this is, is modifying the model definition.
```
class CombinedPLFixERange(SpectralModel):
    def __init__(self, index1, amplitude1, index2, amplitude2, reference):
        self.parameters = ParameterList([
                Parameter('index1', index1, parmin=0, parmax=10.),
                Parameter('amplitude1', amplitude1, parmin=0),
                Parameter('index2', index2, parmin=0, parmax=10.),
                Parameter('amplitude2', amplitude2, parmin=0),
                Parameter('reference', reference, frozen=True)
        ])

    def evaluate(self, energy, index1, amplitude1, index2, amplitude2, reference):
        pl1 = PowerLaw.evaluate(energy=energy, index=index1, amplitude=amplitude1, reference=reference)
        pl2 = PowerLaw.evaluate(energy=energy, index=index2, amplitude=amplitude2, reference=reference)

        e_break1 = X * u.TeV
        e_break2  = Y * u.TeV
        if energy < e_break1:
            retval = pl1
        else:
             if energy < e_break2:
                  retval = pl1 + pl2
              else:
                   retval = pl2     
     
        return retval
```
You could even add the break energies as fit parameters, depending on your specific application.

Did this help you to solve your problem?

**Comment by Ozi1Kenobi** [comment]
Hi,

Sorry if I expressed myself wrong. Sure, the fit range is always controlled by the fit_range parameter of SpectrumFit, while emin and emax basically defines the energy range of the PowerLaw2 model.

So basically, I want to fit a powerlaw model to the data within energy range [Emin, Emax], in which below a defined energy value (say E_break from your example), there's a fixed contribution which can again be defined as a powerlaw function. Note that I can actually measure this contribution from measurements. So I know the index and norm (most cases) of this contribution between [Emin, E_break]. That's why I would like to use PowerLaw2 for the 2nd power-law. But sure, it can be achieved with your generalized code (in an easier way maybe). I'll give it a try. 

Sure it would be nice to learn it, but currently I have many other stuff to do, so won't be able to spend too much time on it and therefore fixing it might take time. I used both differential and integral flux units for the amplitude. 

I'll come back with some feedback. 

Cheers

**Comment by joleroi** [comment]
> So I know the index and norm (most cases) of this contribution between [Emin, E_break]. That's why I would like to use PowerLaw2 for the 2nd power-law.

If you know the norm and in the index, it's more straightforward to use ``PowerLaw``, isnt't it? For ``PowerLaw2`` you'd need to know the integrated flux, or is that what  you mean by 'norm'. In any case, you can of course use ``PowerLaw2``, with my example I just wanted to demonstrate how to make a certain model component only contribute in a fixed energy range.

**Comment by Ozi1Kenobi** [comment]
Hi,

In the end, PowerLaw and PowerLaw2 are the different representation of the same function. Thus, regardless of which one we use, the fit results should be exactly identical. I just had an impression that in the case we have a known (constant) contribution, using PowerLaw2 could be easier, but sure, it may not always be the case. Nevertheless, I think making PowerLaw2 work fine first would be quite useful (I'm trying to make it work, but may take some time). Afterwards, trying both approaches and see which one is more efficient might teach us something (not only for PL + PL but also for the other combined spectral shapes like ECPL + PL or Log Parabola + PL). In the end, source confusion would be one of the challenging issues for the future CTA data analysis, thus such a kind of study on real data would be quite useful. 

Thank you very much for your example, I gave it several tries but encountered with some problems to get the fit results (ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()). When I use np.all() & np.any() functions, then the fit does not work in the way I want (basically tries to compare "energy" array with a "e_break" energy value) and changing e_break has no effect on the results. I'll work on it more and try to make it work so I can come back with some feedback.

**Comment by joleroi** [comment]
> I gave it several tries but encountered with some problems to get the fit results

As you've already noticed, the problem is that an array of ``energies`` is compared to a singe ``e_break`` value, so the ``if`` statement does not make much sense. I guess, you could use (np.where)[ https://docs.scipy.org/doc/numpy/reference/generated/numpy.where.html] in order to avoid the ``if`` statement.

**Comment by Ozi1Kenobi** [comment]
Hi,

I could make the fit work in the following way.

    def evaluate(self, energy, index1, amplitude1, index2, amplitude2, reference, e_break):

        pl2_test = PowerLaw.evaluate(energy=e_break, index=index2, amplitude=amplitude2, reference=reference)
             
        pl1 = PowerLaw.evaluate(energy=energy, index=index1, amplitude=amplitude1, reference=reference)
        pl2 = PowerLaw.evaluate(energy=energy, index=index2, amplitude=amplitude2, reference=reference)

        pl2[pl2<pl2_test] = 0 * u.Unit('TeV-1 cm-2 s-1')

        return pl1 + pl2

which basically set the corresponding pl2 return values to '0' if they are above a chosen energy value. It's surely not the best way and looks ugly, but currently makes the fit work. I'll also try the way you've suggested (np.where) to make it better.

When I try to plot the model with the flux points together, I have a problem while computing the flux points.

fpe = FluxPointEstimator(
    obs=stacked_obs,
    groups=seg.groups,
    model=joint_result[0].model,
)
fpe.compute_points()

  File "/usr/local/lib/python2.7/dist-packages/astropy-1.3.2-py2.7-linux-x86_64.egg/astropy/table/table.py", line 728, in _init_from_cols
    .format(lengths))
ValueError: Inconsistent data column lengths: set([0, 6])

Do you have a suggestion for that ?

Cheers

**Comment by joleroi** [comment]
> Do you have a suggestion for that ?

It's hard for me to understand the problem from just looking at the error message. If you could provide a script that produces this error, I will have a look.

**Comment by Ozi1Kenobi** [comment]
Hi, 

Thank you very much. 
[hessCrabTest_python.txt](https://github.com/gammapy/gammapy/files/1068037/hessCrabTest_python.txt)

**Comment by joleroi** [comment]
When I run your script I get the following error
```
ImportError: cannot import name 'CombinedPLFixERange'
```
The reason is the following
> I implemented the following code to models.py : [...]
> I also added 'CombinedPLFixERange' string to all = []

by doing this you have created your own version of gammapy. Nobody (which includes me :wink: ) is going to be able to run your analysis scripts. Also, you will run into trouble when trying to update gammapy, because you will have local changes to the source code. Therefore, you should never edit the gammapy source code, unless you're planning to contribute your changes to the package (obviously, this holds not only for gammapy but any package). I suggest you move the model definition to the top of your analysis script.

**Comment by Ozi1Kenobi** [comment]
Oh sure, you are right. It was just for some test purposes, and forgot to modify the script. Sorry for the spam. Hope this version works for you, please let me know if something is still missing. 
[hessCrabTest_python_corrected.txt](https://github.com/gammapy/gammapy/files/1068827/hessCrabTest_python_corrected.txt)

**Comment by joleroi** [comment]
Hi @Ozi1Kenobi , I came across this older issue. What's the status here? Is there still a problem?

**Comment by cdeil** [comment]
I'm closing this old issue.

As far as I know, combined spectral models should work either by doing `+` for two spectral models, or defining a new model like in this tutorial:
http://docs.gammapy.org/dev/notebooks/spectrum_models.html#User-defined-model

@Ozi1Kenobi - If there's a remaining issue or missing feature or if you have any question, just comment here or in a new issue or on the Gammapy mailing list.
