### ISSUE TITLE
Travis-CI test fails because of reproject version 0.1 

### ISSUE THREAD

**Issue by adonath** [gammapy/gammapy#1066]
Since a few days the following test fails in gammapy master on Travis-CI:

https://travis-ci.org/gammapy/gammapy/jobs/242743196#L2321

This is because currently  `reproject` version 0.1 is installed, instead of something newer such as 0.3 or 0.3.1.

@cdeil, @bsipocz Any idea why the `reproject` version has been downgraded?

**Comment by bsipocz** [comment]
Numpy 1.13 got released recently and now it's the "stable" version. However new reproject builds are not yet available for it, so the only version that the conda resolver finds is 0.1 (that doesn't required the numpy builds yet). 

So as a workaround you can use ``REPROJECT_VERSION=0.3.1`` making the install script falling back to pip install. Or of course you can open a PR for the conda-forge reproject repo to rerender the recipe to trigger the new builds.
Same applies to healpy, now you're pip installing it, but ideally there should be conda builds for the latest version, too.

**Comment by adonath** [comment]
@bsipocz Thanks for clarifying! 
@cdeil Any preference how to handle this now and for the future?

**Comment by cdeil** [comment]
I've left a comment here: https://github.com/conda-forge/reproject-feedstock/issues/3#issuecomment-308550164 and assigned this issue to myself.

Plan is to just wait for a week or two, and if the issue doesn't get resolved by Tom or someone building the missing package, then I'll learn conda-forge and start helping out there.

Generally I think for Gammapy continuous integration we should consider travis-ci as something that maintainers look at, not contributors. There's just too many unrelated fails and frequent breakage that it makes sense for contributors to look at build logs / fails and try to figure it out.
I'm -1 on spending time to tweak travis.yml for workaround often, and would suggest to instead just leave it read for a few days or even week or two and try to let "upstream" sort out the issue whenever possible.

**Comment by cdeil** [comment]
The missing conda packages were built by Tom today:
* https://anaconda.org/conda-forge/reproject/files
* https://github.com/conda-forge/reproject-feedstock/pull/4

This issue should be resolved and travis-ci passing in this build that I started just now:
https://travis-ci.org/gammapy/gammapy/builds/243454178

Closing this now.

If there's still an issue tomorrow, please re-open.
