### ISSUE TITLE
Stricter warnings with sphinx 1.6.1

### ISSUE THREAD

**Issue by bsipocz** [gammapy/gammapy#1068]
While testing the the new helpers with new sphinx, I run into new warnings in the gammapy docs builds. It appears that things became a bit more strict about references, etc.

https://travis-ci.org/bsipocz/gammapy/jobs/244606732#L1731
```
checking consistency... /home/travis/build/bsipocz/gammapy/docs/references.rst:63: WARNING: Citation [Knoedlseder2012] is not referenced.
/home/travis/build/bsipocz/gammapy/docs/references.rst:57: WARNING: Citation [Raue2012] is not referenced.
/home/travis/build/bsipocz/gammapy/docs/references.rst:40: WARNING: Citation [Meyer2010] is not referenced.
/home/travis/build/bsipocz/gammapy/docs/references.rst:78: WARNING: Citation [CSV] is not referenced.
/home/travis/build/bsipocz/gammapy/docs/references.rst:60: WARNING: Citation [Robitaille2013] is not referenced.
/home/travis/build/bsipocz/gammapy/docs/about.rst:161: WARNING: Citation [Puelhofer2015] is not referenced.
/home/travis/build/bsipocz/gammapy/docs/about.rst:158: WARNING: Citation [Owen2015] is not referenced.
```

**Comment by bsipocz** [comment]
@cdeil - the new helpers RC is out now. Maybe you want to give it a go and see how badly sphinx 1.6+ fails, or would rather wait for the final release next week? I don't plan to lift the sphinx version limitation from ci-helpers for a while, so no sudden failures are expected in the near future.

**Comment by cdeil** [comment]
@bsipocz - I'm not sure how I'd locally update and test to the astropy-helpers RC. It involves updating with the git submodule, no?
I don't have time this week (sorry!), but if you do have time to update astropy-helpers in Gammapy to the RC version via a PR and travis-ci passes, we can merge and then me and some devs will use it for the coming days.
Not sure if that helps you get some testing, from my side also updating after the new stable astropy-helpers release is out would be OK.

**Comment by cdeil** [comment]
This was resolved, closing this issue. See https://github.com/gammapy/gammapy/pull/1077#issuecomment-327418835 .
