### ISSUE TITLE
Docs build without gammapy-extra

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1071]
Currently building the Gammapy docs fails with a not very clear error message (a different one for @wegenmat and me) if `GAMMAPY_EXTRA` isn't set or doesn't point to a checkout of `gammapy-extra`. @woodmd also mentioned this on Slack.

This is a reminder issue for me to:
- [ ] check if we can make the docs build work without `GAMMAPY_EXTRA` with limited effort
- [ ] if yes, do it
- [ ] if no, improve the error message
- [ ] in any case, improve the Gammapy dev docs explaining this.

**Comment by cdeil** [comment]
Currently `python setup.py build_docs` actually gives errors that are pretty loud and clear that `gammapy-extra` is missing:
https://gist.github.com/cdeil/3172b6f9ae59ad13d81a0f481c634747

And actually it runs through and makes a docs version, just with notebooks and examples that use data files from gammapy-extra missing.

So IMO it's as good as it can be. Closing this old issue.

Notice that we plan to do significant changes to the notebook / docs setup in the coming months (see #1419). So there will be room for more discussions / improvements.

**Comment by joleroi** [comment]
As of now the situation has changed a little bit. The docs built noticed me that ``GAMMAPY_DATA`` was not set but gave me the impression that the build would work anyways

```
*** gammapy-data *not* found.
*** Set the GAMMAPY_DATA environment variable!
*** Docs build will be incomplete.
```

Later it crashes quite heavily

```
Exception occurred:
  File "/Users/kingj/Software/gammapy/build/lib.macosx-10.9-x86_64-3.7/gammapy/utils/docs.py", line 63, in run
    self.options["alt"] = self.arguments[1]
IndexError: list index out of range
```
[Full traceback](https://gist.github.com/joleroi/158eb74134e1296f77810a473e75e2b3)

I just want to work on the docs and not care about gammapy-data ...

**Comment by adonath** [comment]
Thanks @joleroi for the report. I'll include @Bultako in the discussion, maybe he has an idea...

**Comment by Bultako** [comment]
@joleroi 
I've fixed this in https://github.com/gammapy/gammapy/commit/8113b88e04e885faccb09bd486964d6a1b316ce0 so you can build **incomplete docs** with GAMMAPY_DATA env var not set.

Note that a big part of the docs are built from empty notebooks that are run and filled during the doc building process, and for this they need datasets accessed through the GAMMAPY_DATA env var. Moreover, many RST files link to these notebooks, some images in the docs are generated executing code with dataset, and maybe other things that I'm missing now..

**Comment by joleroi** [comment]
Thanks @Bultako ! The docs build works fine now
