### ISSUE TITLE
SED : upper limits points

### ISSUE THREAD

**Issue by bkhelifi** [gammapy/gammapy#1080]
Dear all,

I did a 1D spectrum fit using the class SpectrumAnalysisIACT in scripts/spectrum_pipe.py. When I make the SED plots, One can see the 'residual points', even for non-significant bins for which an upper-limit should be calculated instead.
Does this function exist? If not, can we make it (and how)?
Cheers,
B.
To: @cdeil, @adonath 
Cc: @jjlk

**Comment by adonath** [comment]
@bkhelifi The functionality to compute upper limits has been recently introduced in https://github.com/gammapy/gammapy/pull/1084. But the residual plotting code must probably be adapted for this...@joleroi

**Comment by adonath** [comment]
The issue with plotting upper limits in the residual plot has already been resolved in 946b1156938e3b4094ad08ee9e4d45b2af4b7e7e.
