### ISSUE TITLE
Problem with flux points computation

### ISSUE THREAD

**Issue by jjlk** [gammapy/gammapy#1091]
Hi @cdeil , @adonath , @joleroi ,

I've got an issue when I try to compute the flux points. When I set the energy bounds for the computation, the lower energy interval flux is systematically missing. I can recover it by lowering the threshold for the energy bounds but it's not clear what really happens.

You will find attach a small script to reproduce the issue.

I'm simulating data for the ~80 GeV / 10 TeV energy range, do a fit and then compute flux points. When I ask to compute flux points from the simulation threshold I got this: 
![good_threshold](https://user-images.githubusercontent.com/15717586/28669270-e60f7b1e-72d3-11e7-91f6-9ced676e8a96.png)
I tried to lower the treshold as 0.99 * lower threshold but it does not work. When I lower the energy threshold to 30 GeV I got what I want: 
![very_lower_threshold](https://user-images.githubusercontent.com/15717586/28669306-0f1e4cec-72d4-11e7-8efb-4804e06e17eb.png)

Do you have any idea of what is going wrong?

Thanks

The example script: 
```
"""
Example script showing how to simulate expected counts
in the CTA energy range
"""
from gammapy.spectrum.models import LogParabola
from gammapy.scripts import CTAPerf
from gammapy.scripts.cta_utils import CTAObservationSimulation, Target, ObservationParameters

import astropy.units as u
import matplotlib.pyplot as plt
from gammapy.spectrum import SpectrumFit, SpectrumResult
from gammapy.spectrum import FluxPoints, FluxPointEstimator, SpectrumEnergyGroupMaker, SpectrumObservationList

# Observation parameters
alpha = 0.2 * u.Unit('')
livetime = 100 * u.h
emin = 0.08 * u.TeV
emax = 10. * u.TeV
obs_param = ObservationParameters(alpha=alpha,
                                  livetime=livetime,
                                  emin=emin,
                                  emax=emax)

# Target
name = 'Test AGN'
input_model = LogParabola(amplitude=5.e-13 * u.Unit('1 / (cm2 s TeV)'),
                       reference=1. * u.TeV,
                       alpha=2.5,
                       beta=0.3)
target = Target(name=name, model=input_model)

# Performance
filename = '$GAMMAPY_EXTRA/datasets/cta/perf_prod2/point_like_non_smoothed/South_5h.fits.gz'
cta_perf = CTAPerf.read(filename)

# Simulation
simu = CTAObservationSimulation.simulate_obs(perf=cta_perf,
                                             target=target,
                                             obs_param=obs_param)
print(simu)
stats = simu.stats_table()
stats = stats[stats['energy_min']>=0.03 * u.TeV]
stats = stats[stats['energy_max']<=15 * u.TeV]

print(stats[['energy_min', 'energy_max', 'background', 'excess', 'sigma']])

model = LogParabola(amplitude=5.e-13 * u.Unit('1 / (cm2 s TeV)'),
                       reference=1. * u.TeV,
                       alpha=2.5,
                       beta=0.3)

joint_fit = SpectrumFit(obs_list=SpectrumObservationList([simu]), model=model)

joint_fit.fit()
joint_fit.est_errors()
joint_result = joint_fit.result
print(joint_result[0])

ebounds = simu.e_reco
print('emin,emax for flux points: {}, {}'.format(simu.lo_threshold,
                                                 simu.hi_threshold))
ebounds = ebounds[ebounds>=simu.lo_threshold]
#ebounds = ebounds[ebounds>=simu.lo_threshold * 0.99]
#ebounds = ebounds[ebounds>=0.035 * u.TeV]
ebounds = ebounds[ebounds<=simu.hi_threshold]
seg = SpectrumEnergyGroupMaker(obs=simu)
seg.compute_range_safe()
seg.compute_groups_fixed(ebounds=ebounds)
print(seg.groups)

fpe = FluxPointEstimator(
    obs=simu,
    groups=seg.groups,
    model=joint_result[0].model,
)
fpe.compute_points()

spectrum_result = SpectrumResult(
    points=fpe.flux_points,
    model=joint_result[0].model,
)

ax0, ax1 = spectrum_result.plot(
    energy_range=joint_fit.result[0].fit_range, flux_unit='TeV-1 cm-2 s-1',
    point_kwargs=dict(color='navy'),
    fit_kwargs=dict(label='fit', c='b')
)

input_model.plot(ax=ax0,
                 energy_range=joint_fit.result[0].fit_range,
                 label="input model", c='g')

ax0.set_xlim(emin.value, emax.value)
ax0.set_ylim((joint_result[0].model(emax) * 0.9).value, (joint_result[0].model(emin) * 1.1).value)
ax0.legend(loc='best')
plt.show()

```

**Comment by cdeil** [comment]
I probably won't have time to have a look soon. @jjlk - Maybe you could do it, or @joleroi if he has time.

From your description it sounds like you think there's a bug with the energy group computation. 
That is very well possible, it hasn't been tested much and the API / implementation probably isn't great.

If so, then it would be good if you could make a minimal example (~ 10 lines of code), focusing on this part and printing out / looking in more detail at the inputs / outputs of these methods:
```
seg = SpectrumEnergyGroupMaker(obs=simu)
seg.compute_range_safe()
seg.compute_groups_fixed(ebounds=ebounds)
print(seg.groups)
```
An example is here: https://github.com/gammapy/gammapy/blob/b305e8fcf822da65a66f4e3f8a4a2dc4f49ea06b/gammapy/spectrum/tests/test_energy_group.py

@jjlk - Is that correct? Or did I misunderstand and there is an issue with the later step of flux point estimation? Can you move your example to a Jupyter notebook in a https://gist.github.com/ where at the end you print out the energy grouping that comes out, and exactly say what you'd expect instead (one more bin from ??? to ???).

**Comment by cdeil** [comment]
Should be fixed in gammapy master now, since last week (see #1493).
Please try again!
If there's still any issue with energy grouping, please re-open or file a new issue!
