### ISSUE TITLE
SkyImage.from_image_hdu does not test HDU nature

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#1113]
One can open a table extension with SkyImage.from_image_hdu or have elements in a SkyImageList that are created as SkyImage when they are not.

A test should be added to check that image_HDU is a real `astropy.io.fits.ImageHDU` and sent an exception if not. 
SkyImageList.from_hdu_list() should skip non image extensions.

**Comment by registerrier** [comment]
A nice solution could be to define a setter property in SkyImage to force data to be homogeneous to a 2 dimension array. This would also prevent stupid data allocations:
`    def __init__(self, name=None, data=None, wcs=None, unit='', meta=None):
        # TODO: validate inputs
        self.name = name
        self.data = data
        self.wcs = wcs

        if meta is None:
            self.meta = OrderedDict()
        else:
            self.meta = OrderedDict(meta)

        self.unit = u.Unit(unit)

    @property
    def data(self):
        return self._data

    @data.setter
    def data(self,dat):
        """ Set data member and check it is a 2D `~numpy.array` """

        ndim = len(np.squeeze(dat).shape)
        if ndim == 2:
            self._data = dat
        else:
            raise ValueError("Incorrect number of dimension for SkyImage data")
`

But in this case this breaks the default constructor (with data=None). But is a default constructor useful here?

Another solution could be to put a similar test in ~SkyImage.from_image_hdu.

Maybe  a method get_image_hdus to get all ImageHDUs in SmartHDUList would be helpful.

Opinions @cdeil @adonath ?

**Comment by cdeil** [comment]
The `data=None` case is used quite often for "reference" sky images that represent just a WCS. I don't think you can easily get rid of that without breaking stuff.

I'm fine with whatever you do here. Just note that this is the future, so please don't spend too much time on the existing SkyImage (but do fix / add what you need of course):
http://docs.gammapy.org/en/latest/maps/index.html

**Comment by cdeil** [comment]
I'm moving this issue to v0.8. @registerrier - pull requests to add tests or fixes or improvements to SkyImage are welcome any time, this issue is assigned to you. Personally I will start to use `gammapy.maps`, so don't plan to do something here or for the other open issues on `SkyImage` and `SkyCube`.

**Comment by cdeil** [comment]
I'm closing this old issue. Please start using `gammapy.maps` and if there are any issues or missing features there, please let us know.

I'm -1 on adding a `SkyImageList` equivalent, it's not very useful and hard to decide when to use it. Suggest to use just explicitly take the inputs that are needed or use dicts if grouping is useful. If someone wants to add a `MapList` or some such convenience container, please open an issue for discussion before coding.
