### ISSUE TITLE
Reuse EnergyDispersion2D.from_gauss in EnergyDispersion.from_gauss

### ISSUE THREAD

**Issue by joleroi** [gammapy/gammapy#1122]
To get better tests in ``gammapy.irf.energy_dispersion`` we should have reliable methods to create gaussian energy dispersion matrixes.

At the moment there are 

* [EnergyDispersion2D.from_gauss](http://docs.gammapy.org/en/latest/api/gammapy.irf.EnergyDispersion2D.html?highlight=EnergyDispersion2D#gammapy.irf.EnergyDispersion2D.from_gauss) implemented by @registerrier 
* [EnergyDispersion.from_gauss](http://docs.gammapy.org/en/latest/api/gammapy.irf.EnergyDispersion.html#gammapy.irf.EnergyDispersion.from_gauss) implemented by @joleroi

The 2D method is more complete (allows for energy dependent bias and RMS) so we should use this everywhere, and call from ``EnergyDispersion.from_gauss``

See also 
* https://github.com/gammapy/gammapy/pull/1115#issuecomment-327171581
* https://github.com/gammapy/gammapy/pull/1120

**Comment by joleroi** [comment]
I started working on this because I think it is the best way to tackle the issues that @cosimoNigro has found in the energy dispersion code (see #1132 ). This whole project relies on ``EnergyDispersion2D.from_gauss`` so there better be no :beetle: in there.

If you run the following code, however
```
import astropy.units as u
import matplotlib.pyplot as plt
from gammapy.irf import EnergyDispersion2D
from gammapy.utils.energy import EnergyBounds
import numpy as np

e_true = EnergyBounds.equal_log_spacing(1, 10, 5, 'TeV')
migra = np.linspace(0.5, 2, 30)
sigma = 0.2
bias = 0
offset = [0,1,2] * u.deg
edisp = EnergyDispersion2D.from_gauss(e_true=e_true, migra=migra, sigma=sigma,
                                      bias=bias, offset=offset)

edisp.plot_bias()
plt.show()
```
you get this plot
![edisp1](https://user-images.githubusercontent.com/11678435/30431677-a8e41e2c-995f-11e7-97cd-721f44f16b64.png)

which does not seem right to me (it should be centered at 1 on the y-axis).

@registerrier Can you please comment, am I missunderstanding something?

**Comment by registerrier** [comment]
I think the issue is that here you would rather use bias=1 which is probably an improper definition of bias but what is meant here is the mean value of Erec/Etrue.

**Comment by joleroi** [comment]
This was done in https://github.com/gammapy/gammapy/commit/fe019ffc01ecb0a6a8871b594afe64bb1fc40801#diff-8b56cb9409f551e1a8ec1c96689236bf
