### ISSUE TITLE
Test fail in gammapy.maps

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1160]
@woodmd - There's a test fail in `gammapy.maps`:
https://travis-ci.org/gammapy/gammapy/jobs/281217589#L1084

It's a weird one I don't understand and can't reproduce locally.
In `test_wcsmapnd_interp_by_coords[10-binsz9-GAL-AIT-skydir9-axes9]` on line `gammapy/maps/tests/test_wcsnd.py:93` there's an `x and y nan location mismatch` error.

Could it be that those arrays contain `nan` values that are susceptible to rounding errors and thus a difference can happen if the computation isn't 100% identical or has the same dtype precision?

Opening up that test file with PyCharm also points out a few minor issues, e.g. `tmpdir` isn't used / needed in `test_wcsmapnd_iter` and `test_wcsmapnd_fill_by_coords`. And in other files in gammapy.maps too, e.g. at https://github.com/gammapy/gammapy/blob/58e8367f482970982a3da25cd7a1386914596777/gammapy/maps/geom.py#L627 you're passing `**kwargs` to a function that only takes `*args`, so I think that code line will always fail (didn't try, not 100% sure). And there's still this fermipy import at https://github.com/gammapy/gammapy/blob/ae9067dad064aef16eb72e41cee425bf182b7229/gammapy/maps/hpx.py#L1458 .

@woodmd - Do you have time to make a pull request or should I start one for `gammapy.maps` with some cleanup? (for the test fail mentioned above I have no idea what's going on though)

**Comment by woodmd** [comment]
I can look into this and make a PR in the next few days.

**Comment by woodmd** [comment]
Ok this should now be fixed in #1161.  Your intuition was correct that the issue was connected to a rounding error.   For points along the edge of the map `griddata` was sometimes returning NaN.  I'm now filing these by rerunning interpolation for those points with `method='nearest'`.

**Comment by cdeil** [comment]
Fixed by @woodmd in #1161 .
