### ISSUE TITLE
peek() method does not work for Fermi file lists

### ISSUE THREAD

**Issue by cosimoNigro** [gammapy/gammapy#1175]
Hi all,
running this snippet
```python
from gammapy.data import EventList
filename_fermi = '$GAMMAPY_EXTRA/datasets/vela_region/events_vela.fits'
events = EventList.read(filename_fermi)
events.peek()
```
will trigger the error
```python
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-15-b734019b0889> in <module>()
      2 filename_fermi = '$GAMMAPY_EXTRA/datasets/vela_region/events_vela.fits'
      3 events = EventList.read(filename_fermi)
----> 4 events.peek()

/afs/ifh.de/group/amanda/scratch/cosimo/miniconda2/lib/python2.7/site-packages/gammapy/data/event_list.pyc in peek(self)
    440         import matplotlib.pyplot as plt
    441         fig, axes = plt.subplots(nrows=1, ncols=2, figsize=(20, 8))
--> 442         self.plot_image_radec(ax=axes[0])
    443         #        self.plot_time_map(ax=axes[1])
    444         self.plot_time(ax=axes[1])

/afs/ifh.de/group/amanda/scratch/cosimo/miniconda2/lib/python2.7/site-packages/gammapy/data/event_list.pyc in plot_image_radec(self, ax, number_bins)
    484         ax.set_ylabel('DEC')
    485 
--> 486         ax.plot(self.pointing_radec.ra.value, self.pointing_radec.dec.value, '+', ms=20, mew=3, color='white')
    487 
    488         im = ax.imshow(count_image, interpolation='nearest', origin='low',

/afs/ifh.de/group/amanda/scratch/cosimo/miniconda2/lib/python2.7/site-packages/gammapy/data/event_list.pyc in pointing_radec(self)
    245         """Pointing RA / DEC sky coordinates (`~astropy.coordinates.SkyCoord`)."""
    246         info = self.table.meta
--> 247         lon, lat = info['RA_PNT'], info['DEC_PNT']
    248         return SkyCoord(lon, lat, unit='deg', frame='icrs')
    249 

KeyError: u'RA_PNT'
```
should `plot_image_radec` be modified to handle this exception, my understanding is that Fermi event lists don't have these keywords. Am I wrong?

Thank you

**Comment by cdeil** [comment]
@cosimoNigro - See #1177 .

In addition, concretely for `EventList.peek` - it doesn't really work well at the moment even for IACT images. My suggestion for IACT would be to make a SkyImage centered on the pointing position, call `image.fill(self)`, and plot that counts image. For Fermi-LAT: I would suggest to make an all-sky counts image (maybe in Galactic frame, centered on Galactic center) and again fill the events and show the counts image. This is just a quick look to be able to see the event spatial distribution quickly.

**Comment by cdeil** [comment]
We now have this: http://docs.gammapy.org/dev/api/gammapy.data.EventListLAT.html

I'm keeping this issue open for now (moving to v0.9 milestone) - remaining task is to improve the docs or add a factory method for event list read - it's still possible / too easy read an event list with the class that only works properly for IACT data:
```
from gammapy.data import EventList
filename_fermi = '$GAMMAPY_EXTRA/datasets/vela_region/events_vela.fits'
events = EventList.read(filename_fermi)
events.peek()
```
gives
```
KeyError: 'RA_PNT'
```

**Comment by cdeil** [comment]
I'm not sure sure anymore if introducing a separate EventListLAT class was a good idea.
There could also be a single class with a flag whether it's from a pointed observation (IACT) or a slewing one (Fermi-LAT and HAWC).
It's related to the question whether we introduce an `ObservationLAT` class, and whether that would smooth over the differences in the events via a uniform interface.

@registerrier @dcfidalgo @adonath - Let's discuss this tomorrow and make a plan for changes before v0.8 or v0.9.

**Comment by cosimoNigro** [comment]
Hi @cdeil, I think also this old issue can be closed since it is related to the implementation of the eventual Fermi Event List class.

**Comment by cdeil** [comment]
I'll take care of this next week. Probably I'll do some changes to the event list classes, but at the very least the docs example needs to be udpated with one Fermi-LAT example here:
http://docs.gammapy.org/dev/data/index.html

So this is a reminder issue for myself now.
