### ISSUE TITLE
Unnecessary loop over energy bins in LightCurveEstimator.compute_flux_point

### ISSUE THREAD

**Issue by lmohrmann** [gammapy/gammapy#1178]
In the computation of a lightcurve fluxpoint there's a loop over energy bins [here](https://github.com/gammapy/gammapy/blob/bc822b86707cb81fcf8b268e611f488275475a0d/gammapy/time/lightcurve.py#L275) that I don't understand. Why not just compute the number of events in the specified `energy_range` without performing this loop?

I'm happy to make a PR for this, but I wanted to know whether there maybe is a specific reason for this loop or not.

**Comment by cdeil** [comment]
@jjlk added the LC estimator in #950 - Julien - please comment.

I also looked at this today and to the user it's not explained why one has to do a spectral extraction and pass it in:
https://nbviewer.jupyter.org/github/gammapy/gammapy-extra/blob/master/notebooks/light_curve.ipynb#Extract-spectral-data

There's also #982 by Johannes suggesting changes.

I don't have time to look or get involved. @lmohrmann and @jjlk - if one of you can make a PR to make it better, and the other do the review, that would be perfect.

**Comment by lmohrmann** [comment]
OK, I think I understand why the binning is used: it's also used in the calculation of the predicted excess, so to keep things consistent it should be used for the observed excess as well. Nevertheless, the loop is unnecessary and can be replaced.

I think I also found two (rather serious) bugs in the code, so I opened a PR: #1179.

**Comment by adonath** [comment]
There is no action item left in this issue, closing now.
