### ISSUE TITLE
gammapy.maps test fails with Numpy 1.10

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1193]
I'm seeing  a bunch of errors
```
E           ValueError: assignment destination is read-only
```
in this build with Numpy 1.10.4, astropy 2.0.2 and healpy 1.11.0
https://travis-ci.org/gammapy/gammapy/jobs/297629990#L2767

I saw some  similar issues in other parts of Gammapy where I thought the problem was changed behaviour of FITS open: https://github.com/gammapy/gammapy/pull/1192#issuecomment-341991511

But the Astropy changelog has no change listed, and `ValueError: assignment destination is read-only` gives a few issues in Numpy and other packages using Numpy, and the tests failing here don't do any FITS I/O, so I'm pretty sure this is just a Numpy issue.

It doesn't show up for me locally or in other builds with other Numpy versions. We could consider dropping Numpy 1.10 support and bumping to 1.11 if that is a bug in Numpy 1.10. But first we should reproduce the issue locally and understand what is going on.

@woodmd - Do you have time to look at this in the coming days, or should I do it?

**Comment by woodmd** [comment]
This is a bug in the `np.unravel_index` method which was fixed in numpy 1.12 (see numpy/numpy#7269).  For reasons I don't understand the method was returning a read-only output array.  I guess the solution would be to mark this with xfail for earlier numpy versions?
