### ISSUE TITLE
Missing astropy-pytest fail in astropy-dev build

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1200]
Since today, we have the one build for Gammapy against the `astropy-dev` version fail with:
```
RuntimeError: Test dependencies are missing. You should install the 'pytest-astropy' package.
```
https://travis-ci.org/gammapy/gammapy/jobs/298806381#L1407

I see that https://github.com/astropy/pytest-astropy is something introduced by @drdavella (cc @astrofrog, @bsipocz )

Is there something we should change in our travis config and setup instructions for Gammapy developers? Or is this something you will change e.g. in CI helpers?

**Comment by astrofrog** [comment]
@bsipocz - I think we should change this in ci-helpers if astropy is listed as a dependency. Do you agree?

**Comment by bsipocz** [comment]
@astrofrog - you mean to install pytest-astropy if ``ASTROPY_VERSION`` is present? I agree that this is a good idea and can open a PR for it later today.

**Comment by astrofrog** [comment]
@bsipocz - yes, that sounds reasonable. Basically if we install astropy we should install pytest-astropy

**Comment by drdavella** [comment]
Just a note of caution: the `pytest-astropy` package should only be installed in environments that make use of the latest development version of astropy. Installing it with stable version of astropy will cause issues with `pytest` since the plugins provided by the `pytest-astropy` package will conflict with the old versions of the plugins provided by the astropy core package.

**Comment by bsipocz** [comment]
@drdavella - OK, that's sounds reasonable. I'll add it for dev for now and a reminder issue to do it for stable once 3.0 is out.

**Comment by bsipocz** [comment]
@cdeil - this supposed to have been fixed, could you please close if it indeed the case?

**Comment by cdeil** [comment]
I think this is fixed, e.g. here's a successful build with astropy-dev:
https://travis-ci.org/gammapy/gammapy/jobs/299739178

I'm closing this issue now.

As far as I can see, there's no documentation for `pytest-astropy` yet:
http://docs.astropy.org/en/latest/search.html?q=pytest-astropy&check_keywords=yes&area=default
but probably the error message
```
RuntimeError: Test dependencies are missing. You should install the 'pytest-astropy' package.
```
is sufficient for developers to just `pip install pytest-astropy` and be on their way.

**Comment by bsipocz** [comment]
It's documented in the testing guide: http://docs.astropy.org/en/latest/development/testguide.html?highlight=pytest-astropy#testing-dependencies and will also be featured in "what's new" for the new release.

**Comment by cdeil** [comment]
@bsipocz - That's perfect. I just missed it. Thank you!

**Comment by drdavella** [comment]
@cdeil I also hope to provide better documentation for the `pytest-astropy` package itself in the near future. It probably will just consist of a list of dependencies and links to documentation for those dependencies, though.

**Comment by cdeil** [comment]
@drdavella - That sounds good, thanks!
