### ISSUE TITLE
Finish SkyCube implementation

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#121]
The `GammaSpectralCube` implementation is currently unfinished ... the following things should be done:
- [x] See if it's possible to re-use the `NDData` or radio `SpectralCube` class.
- [ ] Nice slicing methods should be implemented (see e.g. [nddata](http://astropy.readthedocs.org/en/latest/nddata/index.html#mixins-for-additional-functionality) and [xray](https://github.com/xray/xray)).
- [x] The `integral_flux_image` class currently gives incorrect results if the `energy_band` unit is not `MeV` ... fix and check:

```
energy_band = Quantity([10, 500], 'GeV').to('MeV')
flux = cube.integral_flux_image(energy_band, energy_bins=10)
```
- [x] Implement the `spectral_index` method.
- [x] Implement `integral_energy_flux_image`
- [x] Implement an extrapolation method so that Fermi models can be extrapolated to `TeV` (using power-law extrapolation from the last two bins and by introducing a fake extra energy slice at very large energy)
- [x] Implement a method to generate coordinate grids.
- [ ] Implement methods to cut out parts of the image or an energy range to get a sub-cube.

**Comment by adonath** [comment]
Partly addressed in #753, #759 and #766.

`SkyCube.sky_image_integral()` works now with any energy unit and does a log-linear extrapolation to higher energies.

**Comment by cdeil** [comment]
Moving milestone to 0.7 (I'll make the 0.6 release tomorrow)

**Comment by cdeil** [comment]
Closing this old issue. SkyCube is deprecated. New issues or feature requests for `gammapy.maps` welcome any time.
