### ISSUE TITLE
Time-properties should be added to ObservationTable

### ISSUE THREAD

**Issue by labsaha** [gammapy/gammapy#1218]
At present ```ObservationTable``` doesn't provide information for ```tstart``` and ```tstop``` in ```mjd``` format. It needs to be modified to get the time properties from the ```ObservationTable```. From ```gammapy.data.EventList``` we get ```time``` for each event in ```mjd```. Similarly, it would be good to have ```start``` and ```stop``` times for all observations stored in ```ObservationTable``` in ```mjd``` format efficiently. This is required for selection of observations on a specific time window given in ```mjd```

**Comment by joleroi** [comment]
Related to #1172 - could be added if ``ObservationTable`` is rewritten.

**Comment by adonath** [comment]
The `ObservationTable` now has `time_start` and `time_stop` properties. I think there is nothing else to be done here. Will close the issue...
