### ISSUE TITLE
Quo vadis gammapy.datasets sub package?

### ISSUE THREAD

**Issue by adonath** [gammapy/gammapy#1237]
Browsing the current gammapy code base I noticed that the `gammapy.datasets` sub package is in very bad shape and a lot of its former functionality has actually been replaced by new data classes and methods.

I suggest to remove the `fetch_`, `load_` and `make_` functions in `gammapy.datasets` and rather add functionality as additional constructors directly to our data and IRF classes (such as `EventList`, `FluxPoints`, `DataStore`, etc). Taking `EventList` as an example: 

- The first method would be something like `EventList.load_example('example-1')`, which creates an instance from a simple prepared dataset that is contained in gammapy-extra. This is very handy for docs examples or interactive use and demonstration. It's basically the same as `EventList.read('$GAMMAPY_EXTRA/path/to/file')`, but offers the convenience with a simple string alias and documentation of the example datasets in a central place.
- The second method is something along the lines of  `EventList.make_example('test-event-list-1')`, which creates an instance from a simple simulated toy dataset, that can be mainly used for testing.
This has already been partly done e.g. in the case of `EnergyDispersion.from_gauss()`.

This way we could get rid of 90% of the functionality in `gammapy.datasets` and add it directly to our data classes. The only remaining functionality is the `_GammapyExtra` class and the `load_electron_spectrum` function, where we don't have an appropriate data class to represent it (maybe `SpectralTableModel`?).

**Comment by adonath** [comment]
One further addition: the `FermiLATDataset` class is conceptionally very similar to the `DataStore` and should probably go to `gammapy.data`. It could also be renamed to `DataStoreLAT` or whatever naming scheme we adopt...

**Comment by adonath** [comment]
Is this worth a PIG? @cdeil, @registerrier, @bkhelifi, @robertazanin?

**Comment by cdeil** [comment]
@adonath - I didn't have time to look at this yet, sorry.

We either need a PIG for this and other parts, or a larger one outlining code organisation in general and versioning / coupling of the two repos.

Yesterday we discussed that modeling and 2D / 3D map based analysis is high priority for January, so I would say this is something we discuss at the F2F in Paris and then tackle in February / March. I'm putting this on the v0.8 milestone for now and we discuss next year. OK?

**Comment by cdeil** [comment]
@adonath - Please review and comment on #1419.

It doesn't mention `gammapy.datasets`, but my thinking is that it will become mostly superfluous. Maybe we'll use it as the place where the `gammapy download` code and some code to make example simulated test datasets lives. That discussion is a next step that we could have e.g. at the coding sprint.

I'm -1 on attaching move code like `EventList.load_example('example-1')` as you mention above. One argument is that it's a bit dirty to mix our data structures with tutorial / example / docs things. For me the more important argument why I don't like it is that it teaches users one thing, and the when they want to move from tutorials to their own analyses, they have to learn something new. This is bad, the tutorials should access data as you would in real analyses, and only contain a few lines at the top how to download the example dataset for the tutorial.

@adonath - What do you think?

**Comment by cdeil** [comment]
A lot of old stuff in `gammapy.datasets` was removed recently.
Status: http://docs.gammapy.org/dev/datasets/index.html

Concerning the Fermi observation list class, indeed it should be added to `gammapy.data`.
See https://github.com/gammapy/gammapy/pull/1546#issuecomment-408152794
Let's discuss tomorrow whether to make this a priority (since we need to translate to `Map` anyways), or leave this to v0.9.

**Comment by adonath** [comment]
I decided to remove the `gammapy.datasets` submodule in #2098.
