### ISSUE TITLE
Move docs from ReadTheDocs to Github pages

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1241]
We've discussed this before and I think there is agreement on the change, but I didn't find an issue and wanted to take notes.

I'm moving the docs from ReadTheDocs (RTD) to Github Pages (GHP).

The problems with RTD are:
* Currently build times out -> no easy way to get it to work
* The RTD build has been hard to maintain - every few months there's build failures and they are often hard to debug

This isn't trivial to set up in a good way, and I'm not sure yet about the best way. I'll document it after I have something that works.

For now, I'll try doing everything in a separate repo `gammapy/gammapy-docs`, probably via a `make.py` script there that has sub-commands to `build` and `deploy` the current as well as older versions of the docs. I don't know yet if I'll also have time to add a scripted `env` way to set up execution environments for different versions of the docs, or if I do this manually for now for v0.6 and see if I can get it built.

For now, docs are built and deployed manually, and then if we want we can add a docs build and deploy in addition on travis-ci or Jenkins. Probably that's only needed for the `master` branch and there it's easy to do using e.g. https://github.com/Syntaf/travis-sphinx and maybe https://github.com/davisp/ghp-import .

Later we can try adding the multi-version selection on the docs. For now the only thing I could find was https://robpol86.github.io/sphinxcontrib-versioning/ and it seems unmaintained. But probably the RTD version chooser is also open source or maybe there is something else or it's not too hard to roll our own.

**Comment by cdeil** [comment]
I have started here: https://github.com/gammapy/gammapy-docs

See https://gammapy.github.io/gammapy-docs/dev/ and https://gammapy.github.io/gammapy-docs/0.6/ and https://github.com/gammapy/gammapy-docs/blob/master/README.md for some notes.

I think the main things to figure out are:

1. How to build older stable versions of the docs, by creating a conda env with the appropriate execution environment (e.g. older Sphinx version) and gammapy-extra version. The current dev environment can't be used to build the old Gammapy v0.6 docs: https://github.com/gammapy/gammapy-docs/tree/master/build/0.6 . The current https://gammapy.github.io/gammapy-docs/0.6/ is just something I downloaded from RTD, that's why it has RTD stuff in there.

2. How to add links between the multiple versions. E.g. https://robpol86.github.io/sphinxcontrib-versioning/ or a version selector somewhere (e.g. in the sidebar, see http://click.pocoo.org/5/).

This can easily take a day or two to figure out and isn't super high priority, and I think up-to-date docs are most important, so I would suggest we do the switch over docs.gammapy.org to point to GH pages now.

One change is that the URLs don't contain the `en` any more for "english", like we had on RTD. This is also the case e.g. for Python itself and many other projects. We are never going to translate the Gammapy docs to multiple languages, so the `en` in the URL doesn't help. And since we're breaking URLs here anyways, I also removed the "v" in "v0.6", just putting "0.6". Again, to have a bit shorter / simpler URLs, following again how docs.python.org works.

@adonath @joleroi or @Bultako - Any thoughts on this? OK to switch to this new Gammapy docs build / deploy / hosting now?

How about keeping RTD in place for a month or even directly removing it now? I think it doesn't help much to keep it in place for a long time? We actually don't want anyone to work with old Gammapy at the moment anyways.

**Comment by Bultako** [comment]
@cdeil 

> How to build older stable versions of the docs

I understand you are talking of a process to rebuild also versions that will be considered as older in a future time, but they are not born right now.

In this sense, I think playing with conda envs is not enough. We will also have to rollback to a previous specific commit of `GAMMAPY_EXTRA` local repo (at least for the building notebooks/tutorials). This reminds that `GAMMAPY_EXTRA` and `gammapy`are not version-coupled. https://gammapy.github.io/gammapy-docs/dev/development/setup.html#versioning I don't know exactly how the `astropy_helpers` are coupled to gammapy, but I guess we could do something similar with the gammapy_extra?

> How to add links between the multiple versions.

I'm thinking of common JS file called by the Sphinx templates of all versions, that modifies the DOM of the HTML pages and adds a version-switcher at the footer like in RTD. This JS file will provide new links to versions as they appear. It could also add links to PDF versions of the docs. I have to examine carefully the Sphinx layouts provided by `astropy_helpers`, and find a way of how to do it without modifying them, because gammapy is tightly coupled to these helpers.. I don't even know if this is possible :(

---
I'm ok with moving to GHP as soon as possible, but before that, I'm going to update the green box messages that are in all the tutorials/fixed-notebooks. If I find any other mentions to RTD in the docs I will modify accordingly.

**Comment by cdeil** [comment]
Just to say: I'm not a fan of the Astropy Sphinx theme in `astropy_helpers` that we're currently using. I'd prefer we use a responsive layout like https://github.com/rtfd/sphinx_rtd_theme . It's probably not trivial to switch though, because other things are different (most notably the sidebar navigation), so a switch would require some work to identify the differences and discussion what we want.

Overall I'm inclined to do nothing here for now and leave all of these docs improvements to later (and for now just loose the multi-version docs x-link feature).

**Comment by cdeil** [comment]
I've closed the open issues we hat in the RTD tracker: https://github.com/rtfd/readthedocs.org/issues/2827 and https://github.com/rtfd/readthedocs.org/issues/3360
and I've deactivated the build of all versions for Gammapy on RTD over at https://readthedocs.org/dashboard/gammapy/versions/ and deleted the RTD service hook at https://github.com/gammapy/gammapy/settings/installations .

I think I'll just leave RTD like that for now, move to GH pages now, and then we can delete the project completely from RTD in a month. In the meantime, RTD will not do any new docs build, but the existing one will still be at https://gammapy.readthedocs.io (with the last one for the "latest" version from 13 Nov 2017, when it last worked).

**Comment by cdeil** [comment]
This is working now, the switch is done:

* http://docs.gammapy.org/dev/
* http://docs.gammapy.org/0.6/
* http://docs.gammapy.org -> http://docs.gammapy.org/dev/ 
* http://docs.gammapy.org/stable/ -> http://docs.gammapy.org/0.6/

I've also updated the links to docs.gammapy.org from gammapy.org just now:
https://github.com/gammapy/gammapy-webpage/commit/bbe0c87619cf4759867a75550a284f367ed141ea

I'm keep this issue open as a reminder for me to improve this later, and for further discussion.

At the very least:
- [ ] Automate the build and deploy for the dev branch, triggered by commits to gammapy master
- [ ] Automate a few things in https://github.com/gammapy/gammapy-docs/blob/master/make.py, e.g. introduce an `info.json` that contains the latest stable version, and propagate that to [here](https://github.com/gammapy/gammapy-docs/blob/69b9a49a90abaaf31f4629c4e6fc7bce4c507dfd/docs/stable/index.html#L5).
- [ ] Document how things work at http://docs.gammapy.org/dev/development/setup.html#docs-gammapy-org and what steps are necessary concerning a new docs version on http://docs.gammapy.org/dev/development/release.html

There's also other possible improvements, like the docs version chooser feature as discussed with @Bultako above.

**Comment by Bultako** [comment]
@cdeil nice !
as a final touch it would be good to have the very last version published, there are still many places with references to RTDs.

i.e.
http://docs.gammapy.org/dev/notebooks/first_steps.html
http://docs.gammapy.org/dev/development/setup.html#docs-gammapy-org

**Comment by cdeil** [comment]
I'll completely delete the Gammapy RTD account now.
An archive of the HTML docs from old Gammapy versions from RTD is here: https://github.com/cdeil/gammapy-docs-rtd-archive

**Comment by Bultako** [comment]
> I'll completely delete the Gammapy RTD account now.
> An archive of the HTML docs from old Gammapy versions from RTD is here: https://github.com/cdeil/gammapy-docs-rtd-archive

@cdeil 
Note that the links to the different versions of the docs in that page are broken, since Rawgit does not provides its service to new repos.

See also https://github.com/gammapy/gammapy/issues/2004

**Comment by cdeil** [comment]
We have used https://github.com/gammapy/gammapy-docs for ~ 1 year and it's working.

It's not a great solution, because it's not automated, and the git repo grows and grows with every docs version.

A better solution would likely be to either go back to RTD, or to automate and improve the solution using Gihtub actions ( https://github.com/features/actions ) and Github pages ( https://pages.github.com/ ).
RTD has improved since we left, and Github has massively improved recently with actions.

But I don't have time to prototype implementing these options, so closing this issue.
Try to find an engineer or contributor that like Github automation and CI work next year!
This has a steep learning curve to be set up, and then very small level of time investment to maintain (that could be done by the release manager as now).
