### ISSUE TITLE
Required packages not mentioned.

### ISSUE THREAD

**Issue by mackaiver** [gammapy/gammapy#1245]
For executing the example notebooks (e.g. http://docs.gammapy.org/dev/notebooks/first_steps.html) both scipy and matplotlib need to be installed. This is not mentioned in either the notebooks nor the installation instructions for gammapy.

Should we simply add both dependencies to the setup.py maybe?

**Comment by mackaiver** [comment]
Reproject seems to be another requried dependency.
https://reproject.readthedocs.io/en/stable/

**Comment by cdeil** [comment]
@mackaiver - we are working on making Gammapy install and docs better, but it's still work in progress.

Here's what we have:
* For Gammapy devs using conda: https://github.com/gammapy/gammapy/blob/master/environment-dev.yml
* For Gammapy users using conda: https://github.com/gammapy/gammapy-extra/blob/master/environment.yml
* For pip users, we have this: https://github.com/gammapy/gammapy/blob/904e9abd3809171d8ef46839a5e2259188413065/setup.py#L106

I think the conda files for users and devs are OK? The remaining TODO there is to improve http://docs.gammapy.org/dev/ to advertise them.

For pip, I would prefer to keep the default `install_requires` minimal, i.e. what we have now.
But then we can define `extras_require`, and there the ones we have now (`analysis` and `plotting`) need to be changed. There a proposal is needed what to put, and then also documenting this in the Gammapy install docs. I think one can use the `extras_requires` either as env specs, like `recommended`, `all` or `test`. Or one can use them as mix-ins, e.g. have `plotting` and `analysis`, and then recommend `pip install gammapy[analysis,plotting]` to get both. I think I prefer the "env spec" way to use `extras_requires`. I don't think `pip install` works well for all our dependencies, some don't distribute binary wheels, so probably the goal shouldn't be to put as much as in the conda envs, although maybe `gammapy[all]` should match the default recommended "all" conda env.

@mackaiver @adonath or anyone - Thoughts?

Anyone has time to send a PR to change `setup.py` and / or improve the Gammapy install docs?

Putting this on the upcoming v0.7 release; this is important; I could also make a PR next week.

**Comment by mackaiver** [comment]
> I don't think pip install works well for all our dependencies, some don't distribute binary wheels

Both matplotlib and scipy have binary wheels. So does astropy and reproject. I think these are required for almost all the example notebooks. So for somebody doing the `first_steps` notebook these are hard dependencies. The name suggests that the notebook contains some core functionalities. If not, the notebook should be removed.

**Comment by cdeil** [comment]
But it's still reasonable to ask users to type
```
pip install gammapy[analysis]
```
to install these things and to reserve
```
pip install gammapy
```
for only the core required dependencies, i.e. not things like `matplotlib` or `reproject` that are only used in a few method calls.

I can see the appeal of having `pip install gammapy` install those, but the problem is where to stop, and if we put all 10-20 dependencies that are maybe used in one or two methods or tutorials, then install will be slow or even fail for some users.

@mackaiver - Note that since a week ago, we now have
```
gammapy info
```
as described [here](http://docs.gammapy.org/dev/scripts/index.html). Another thing we could do is to extend this a bit to list dependencies for each notebook in https://github.com/gammapy/gammapy-extra/blob/master/notebooks/notebooks.yaml and then to implement a helper function and execute it at the top of each notebook that prints to the user which python they use and if they have the dependencies needed for that notebook and at what versions. I.e. the first cell of each tutorial would be something like this:
```
from gammapy.scripts import info
info.tutorial_env()
```
or if it's not easy to figure out which notebook one is running, then repeat it's name:
```
from gammapy.scripts import info
info.tutorial_env('first_steps')
```

@adonath @joleroi @Bultako   - Thoughts?

**Comment by mackaiver** [comment]
> for only the core required dependencies

yes. But the packages we are talking about seem to provide core functionalities. As a user coming to gammapy I expected the "first_steps" notebook to show me the core functionalities. 
If that is not the case then maybe we should change the documentation and clearly state the core functionalities and create another "first_steps" or quick start guide.

> Another thing we could do is to extend this a bit to list dependencies for each notebook

I feel like this would be a step in the wrong direction. Dependency resolution has  already been solved by pip and the likes. I would refrain from adding another complication ontop of that.

**Comment by cdeil** [comment]
@mackaiver - For now, I put this as recommendation for users to get set up:
http://docs.gammapy.org/dev/tutorials.html#set-up

I'll do the Gammapy 0.7 release now, but I admit that the Gammapy install instructions still need a lot of work and polishing, so keeping this issue open for now.

Like I said before, my preference would be to keep `pip install gammapy` and `conda install gammapy` minimal, and to additionally implement and advertise something like `pip install gammapy[recommended]` and `conda install gammapy-recommeded` (or call it `gammapy-all`).
This is not uncommon, e.g. there is an `apt-get install git-all`.

The question about the exact content of the `gammapy` and `gammapy-all` is another task, e.g. `sherpa` is not available on windows, so we'll have to see how to handle that in `gammapy-all`.

**Comment by cdeil** [comment]
The recommended way for users is now to use conda and a stable env with all dependencies:
http://docs.gammapy.org/dev/getting-started.html#install

This is super new and will be first tested for v0.8 in the next days.

I'm closing this old issue now, not sure if there's any action items left.
@mackaiver - If yes, please re-open or file a new issue or PR suggesting what exactly to do.
