### ISSUE TITLE
Delete unimplmented methods in datastore

### ISSUE THREAD

**Issue by mackaiver** [gammapy/gammapy#1253]
And elsewhere to. Heres an example:

```
In [142]: data_store.check_integrity()
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
~/Development/galactic_plane_cta/skymap.py in <module>()
----> 1 data_store.check_integrity()

~/Development/gammapy/gammapy/data/data_store.py in check_integrity(self, logger)
    314 
    315         logger.info('Checking event list files')
--> 316         available = self.check_available_event_lists(logger)
    317         if np.any(~available):
    318             logger.warning('Number of missing event list files: {}'.format(np.invert(available).sum()))

~/Development/gammapy/gammapy/data/data_store.py in check_available_event_lists(self, logger)
    365         """
    366         # TODO: This is broken. Remove (covered by HDUlocation class)?
--> 367         raise NotImplementedError
    368 
    369         observation_table = self.obs_table

NotImplementedError: 

```

**Comment by cdeil** [comment]
@mackaiver - I disagree on the suggestion to remove all unimplemented methods in Gammapy.
When writing a class like the DataStore, IMO it's normal to not do everything at once, and to put stubs for methods we want and need. This helps the developer, as well as others to continue in the future, if the design / API is more fleshed out.

In this case, I now really need to have such a method to check the integrity of a DataStore. I screwed up creating the index files for CTA 1DC, and I regularly see others also screw up with data releases and having some automated checks for DL3 FITS data will be immensely helpful for HESS, MAGIC, CTA, ...
Checking release data would almost alway go by building an index of what data is present and then checking the data, creating results tables, so for now this kind of work in Gammapy happens with the DataStore.

I'm closing this issue in favour of #1321 .
