### ISSUE TITLE
Delete from_all method from datastore

### ISSUE THREAD

**Issue by mackaiver** [gammapy/gammapy#1254]
I think you know whether you have a directory or a name to pass along.

**Comment by cdeil** [comment]
👍  to remove it. Looks like there's no callers, i.e. easy to remove. @mackaiver - You or me?

**Comment by mackaiver** [comment]
I can do it later today.

**Comment by joleroi** [comment]
Note that in a config file driven analysis you do not know what is passed along. But it's ok for me to force one of the two in a config file driven analysis.

**Comment by cdeil** [comment]
@joleroi - Please see #1265 . I know this will need more discussion / thought, but I think we should probably introduce an intermediate class / file that specifies which IACT data to use for an analysis, probably the `ObservationList` should be re-written and grow a serialisation format.
Then config file driven analysis in Gammapy would never need the master index file and the `DataStore.from_name` method would be removed as well, and we wouldn't have to support the use case of master index files in the science tool config API. @joleroi - Please share your thoughts on this larger question in #1265 .

**Comment by cdeil** [comment]
Done in #1265 .
