### ISSUE TITLE
allow datastore.obs to return all observations

### ISSUE THREAD

**Issue by mackaiver** [gammapy/gammapy#1255]
currently one needs to supply a list of observations ids. What if I want all of them? Is that a valid use case?

**Comment by cdeil** [comment]
To get get all observations, currently you'd first get a list of all obs_id via:
```
obs_id = data_store.obs_table['OBS_ID'].data
```
(in this case a Numpy array, can also call `list()` on it if you like that)
And then you could use either
```
obs_list = data_store.obs_list(obs_id)
```
and then access the `obs` you like from that list, e.g. via
```
obs = obs_list[42]
```
or you could loop over the `obs_id` in the calling code and access `obs` like this:
```
for oid in obs_id:
    obs = data_store.obs(oid)
    # do something
```

Given that we said that we want to introduce an "observations" container (see #1303) and have the data store as just one way to get that, the pattern using `obs_list` is preferable for now IMO.

I'm not sure if the use case to want all obs is very common.

My suggestion would be to improve the docs instead and show an example:
See http://docs.gammapy.org/dev/api/gammapy.data.DataStore.html

If we think it is common to access all available obs, we could add a default `obs_id=None` in [DataStore.obs_list](http://docs.gammapy.org/dev/api/gammapy.data.DataStore.html#gammapy.data.DataStore.obs_list) and in that case put:
```
if obs_id is None:
    obs_id = self.obs_table['OBS_ID'].data
```
In that case adding a docs example would still be needed.

@mackaiver - What do you think we should put? You or me?

**Comment by joleroi** [comment]
I think it's okay to ask people to put this one line

```
obs_id = data_store.obs_table['OBS_ID'].data
```

if they want all observations

**Comment by cdeil** [comment]
Closing this old issue. We're discussing a one-line convenience addition, and opinions are split whether it's useful. If someone send a PR to improve gammapy.data (or anything really), I'll hit the merge button.
