### ISSUE TITLE
artifacts in image at edges of exposure maps

### ISSUE THREAD

**Issue by mackaiver** [gammapy/gammapy#1260]
When creating an image from multiple observations with the RingBackgroundEstimator I get the following exposure map. which looks fine.
![exposure_2](https://user-images.githubusercontent.com/4076745/34995449-d8ae4744-fad6-11e7-9e6c-3b41c88885bf.png)

in the excess picture I see some artifacts along the edges of the exposure map (look closely at the overlapping region above the center. less excess at the edges of the exposure regions.)

![exposure](https://user-images.githubusercontent.com/4076745/34995450-d8ca04a2-fad6-11e7-866e-e2aa7ec1fc2f.png)

Is this expected behaviour?

**Comment by mackaiver** [comment]
I scaled the image to make it more visible

![exposure_3](https://user-images.githubusercontent.com/4076745/34995638-61934db6-fad7-11e7-9428-c95a526b4c1f.png)

**Comment by cdeil** [comment]
@registerrier has started to work on new code to compute sky images. I think the effect described here is the result of the `IACTBasicImageEstimator` taking the AEFF response shape to make a background image in the FOV, and the AEFF radial acceptance curve shape isn't correct, i.e. doesn't match BKG.

A very similar report is in #1198 with extensive discussion. @registerrier - Up to you if you want to close this issue as a duplicate and just have discussion in #1198, or to keep both issues open until the new code to compute a correct background image is in place.

**Comment by registerrier** [comment]
This should be now solved by PR #1331 which introduces acceptance correction for background estimates in `IACTBasicImageEstimator`.
Closing issue.
