### ISSUE TITLE
Notebooks containing TODOs

### ISSUE THREAD

**Issue by mackaiver** [gammapy/gammapy#1261]
Heres a list of notebooks containing todos. I propose to either fix them during the coding sprint or delete the notebooks:
```

→ grep -rwn . -e 'TODO'
./spectrum_simulation.ipynb:79:    "For the sake of self consistency of this tutorial, we will simulate a simple detector. For a real application you would want to replace this part of the code with loading the IRFs or your detector (TODO: Link to IRFs tutorial)"
./detect_ts.ipynb:229:    "TODO: run a peak finder to make a source catalog\n",
./detect_ts.ipynb:256:    "* TODO: show cutout for a few sources and some aperture photometry measurements (e.g. energy distribution, significance, flux)"
./detect_ts.ipynb:269:    "# TODO"
./detect_ts.ipynb:281:    "TODO"
./detect_ts.ipynb:340:    "TODO: put one or more exercises"
./detect_ts.ipynb:369:    "- TODO: point to background estimation examples\n",
./detect_ts.ipynb:370:    "- TODO: point to other docs ..."
./image_analysis.ipynb:23:    "TODO: Refactor [gammapy.scripts.image_fit](http://docs.gammapy.org/en/latest/api/gammapy.scripts.image_fit.html) into a class (simiar to `gammapy.spectrum.SpectrumFit`) and run it here to fit a Gauss and get the position / extension."
./image_analysis.ipynb:447:    "TODO"
./image_analysis.ipynb:484:    "TODO: summarise\n",
./image_analysis.ipynb:486:    "TODO: give links what to do next."
./source_diffuse_estimation.ipynb:19:    "* TODO: code to simulate images from a source catalog is where?!?\n",
./source_diffuse_estimation.ipynb:62:    "TODO"
./source_diffuse_estimation.ipynb:124:    "TODO"
./source_diffuse_estimation.ipynb:184:    "TODO"
./source_diffuse_estimation.ipynb:240:    "TODO: summarise\n",
./source_diffuse_estimation.ipynb:242:    "TODO: pointers to other docs"
./time_analysis.ipynb:12:    "TODO: use which example dataset? 2FHL / 3FGL and/or HESS DL3 DR1?\n",
./time_analysis.ipynb:64:    "TODO: maybe use 3FGL and compute `variability_index`? (needs to be implemented!)"
./time_analysis.ipynb:82:    "TODO"
./time_analysis.ipynb:100:    "TODO"
./time_analysis.ipynb:120:    "In this tutorial we ... (TODO: summarise.\n",
./time_analysis.ipynb:123:    "- TODO"
./spectrum_pipe.ipynb:93:    "# TODO: Replace with public data release\n",
./spectrum_pipe.ipynb:173:    "TODO: Clean up the log (partly done, get rid of remaining useless warnings)"
./spectrum_pipe.ipynb:347:    "TODO: Nice summary page with all results"
./diffuse_model_computation.ipynb:150:    "# TODO: Counts should roughly match Fermi counts, which is 1 count / pixel in the Galactic plane.\n"
./fermi_vela_model.ipynb:109:    "# TODO: images below should be flipped left-right!!!\n",
./cube_analysis_part2.ipynb:713:    "# TODO: there should be some visualisation of results.\n",
./cta_1dc_introduction.ipynb:582:    "TODO: write the rest of this notebook."
./spectrum_analysis.ipynb:208:    "TODO: Change to [gamma-cat](https://gammapy.github.io/gamma-cat/)"
./spectrum_analysis.ipynb:891:    "TODO: give pointers how to do this (and maybe write a notebook with solutions)"
./source_population_model.ipynb:331:    "# TODO: plot GLON, GLAT, FLUX distribution\n"
./source_population_model.ipynb:340:    "TODO"
./source_population_model.ipynb:360:    "TODO: summarise what was done here briefly.\n",
./source_population_model.ipynb:362:    "TODO: add some pointers to other documentation."
./source_catalogs.ipynb:201:    "TODO: move content from this section and http://docs.gammapy.org/en/latest/spectrum/plotting_fermi_spectra.html to a separate notebook about SED access and plotting"
./data_iact.ipynb:601:    "TODO: examples for point spread function (PSF)"
./data_iact.ipynb:663:    "TODO: example how to load and plot `gammapy.background.FOVBackgroundModel`"
./data_iact.ipynb:676:    "# TODO: doesn't work yet\n",
./data_iact.ipynb:691:    "- TODO"
```

**Comment by MaxNoe** [comment]
Also: TODOs like "Add one or mor exercises" are a nice entry point for new contributors and could be made visible as Issues with a label "entry-friendly" or "small-task"

**Comment by cdeil** [comment]
Yes, we should go through and remove some notebooks and restructure / improve / clean up the ones we keep. An overview of what we have or at least show to users is here: http://docs.gammapy.org/dev/tutorials.html#notebooks

We can discuss on Monday at the coding sprint how much time to spend on this task during the coding sprint.

My 2 cents: There's two reasons we might want to not spend too much time on notebooks at the meeting, even though of course in general good tutorials are very important. 1. new code to make maps and cubes and for modeling is coming, i.e. the API for many things will change, so many tutorials will need another update anyways soon. 2. most people already know how to edit and update a notebook, they can do that by themselves; but most don't know how to efficiently contribute to the Gammapy codebase, i.e. write good code and tests, and go through a code review process. So I'd like people to also spend time on pair-coding and practicing that during the workshop.

@robertazanin - Assigning this issue to you, to organise work on Gammapy docs at the coding sprint. At the very least there should be 2 persons that go through what we have and make a proposal which notebooks they think should be removed, or re-organised or added. And then they either distribute the work to do after the wokshop, or spend some time to do it directly there.

**Comment by cdeil** [comment]
Along the lines of https://github.com/gammapy/gammapy/issues/1262#issuecomment-364461333 : I don't think this issue listing all TODOs in notebooks is helpful. Closing it now.

We will make a real effort to clean up and improve, and also to split the work among more contributors. But for that, I think we have to either do pair coding or make issues describing one specific task (e.g. how to improve one notebook) that someone can sign up for.
Let's talk on Monday: https://github.com/gammapy/gammapy-meetings/blob/master/2018-07-09/README.md#monday
