### ISSUE TITLE
Stacking observations with different energy thresholds

### ISSUE THREAD

**Issue by lmohrmann** [gammapy/gammapy#1263]
This issue is mostly to start a discussion about a problem I encountered.

I'd like to perform a spectral fit on multiple observations that have different energy thresholds. In principle, there's two was of doing this, namely to fit all observations simultaneously, or to first stack them and then fit the stacked observation. Both of these approaches have their advantages and disadvantages. I'd like to focus on the second one, i.e. the one where the observations are stacked first.

If one wants to obtain correct results in the energy range where only some of the observations (those with a low energy threshold) contribute, one has to compute the effective area of only those observations, and one has to account for the reduced livetime. Both of these things are currently not done in Gammapy.

While it would be easy to correctly compute the "stacked" effective area by considering only those observations that contribute, accounting for the reduced livetime is harder. In HESS, we do this by storing an energy-dependent livetime. This could be an option for Gammapy as well, however, this would probably mean that the PHACountsSpectrum class is no longer compliant to the [OGIP standard](https://heasarc.gsfc.nasa.gov/docs/heasarc/ofwg/docs/spectra/ogip_92_007/node8.html) (which, as far as I understand, specifies the livetime as a single value per observation, see the "EXPOSURE" keyword).

I'd be interested to hear other people's opinions on this. Can someone think of a way to do this without changing the way livetimes are handled currently?

Thanks!

**Comment by cdeil** [comment]
https://github.com/gammapy/gammapy/pull/1236#issuecomment-352675535 might be related, or maybe that only concerns "joint fit", not "stacked" analysis?

@joleroi or @registerrier - Is what @lmohrmann says above correct? Gammapy can't do what we do by default in HAP FitSpectrum, i.e. a stacked analysis where `A * T` is computed for each run, then energy thresholds applied, then vectors added?

**Comment by lmohrmann** [comment]
I've given this some more thoughts. Here's a couple of ways I can think of to implement this:

1) Change the PHACountsSpectrum class to store the livetime as a function of energy.

2) Add a flag to the SpectrumObservation class that determines whether it is a stacked observation or not. If it's stacked, do not read the livetime and energy thresholds from the on_vector attribute but store/compute them in the class itself.

3) Add a new class "StackedSpectrumObservation" (to be returned by the SpectrumObservationStacker, or as a replacement for that class). This class would probably inherit from SpectrumObservation, but handle energy thresholds and livetimes on a per-observation basis.

I think I like option 3) the best, but again, I'd be interested to hear other people's opinions.

**Comment by lmohrmann** [comment]
@cdeil The problem is that if the SpectrumFit class is working on a single, stacked observation, the CountsPredictor is fed with the livetime of that observation. If the livetime is a single number, it's not really possible to account for different energy thresholds correctly, I think.

**Comment by registerrier** [comment]
No you can (should) do it without introducing an energy dependent exposure.
When computing the average response functions, here are and rmf, you have to take into account the QUALITY flag telling whether a bin is to used or not.
The average rmf (EnergyDispersion) then properly takes into account the lower probability of a given energy bin since it has less exposure than the others

**Comment by lmohrmann** [comment]
@registerrier Yes, it's possible to compute the average IRFs correctly (although this is not done currently, as far as I can tell). The bigger problem occurs when the stacked observation is fit in the SpectrumFit class (as described in my previous comment).

**Comment by registerrier** [comment]
OK, I suppose it means the stacked IRF is not correct so the problem rather lies in the `~gammapy.irf.IRFStacker`

**Comment by lmohrmann** [comment]
Yes and no - the stacked IRF is not correct, but this is easy to fix.

However, if we do stack the IRFs correctly, we still need to account for the reduced livetime (or exposure) in the energy range where only some observations contribute, and this is the harder-to-solve problem.

It requires to keep track of the energy thresholds of the individual observations, or their combined, energy-dependent livetime, or both. Since the SpectrumObservationStacker currently returns a single SpectrumObservation (with a single energy threshold and a single livetime), this is  currently not possible.

**Comment by registerrier** [comment]
With the correct stacked IRF, you don't need to have energy dependent livetimes since the average edisp already contains the energy varying exposure. See the doc here:
http://docs.gammapy.org/dev/api/gammapy.irf.IRFStacker.html#gammapy.irf.IRFStacker

**Comment by joleroi** [comment]
I completely agree with @registerrier  and  I am pretty sure that different energy thresholds are handled correctly in the IRF stacking process.

@lmohrmann if you insist that the stacking is wrong it would be most intructive to show an example where some simulated obeservations are stacked with gammapy and also (manually) the HAP way and the results in the first case are wrong compared to the second one.

**Comment by cdeil** [comment]
> @lmohrmann if you insist that the stacking is wrong it would be most intructive to show an example where some simulated obeservations are stacked with gammapy and also (manually) the HAP way and the results in the first case are wrong compared to the second one.

Agree that we need this, the on counts and stacked `A * T` histograms are very important debug plots. I've also never seen PSF containment fraction curves or any plot that shows if this is or isn't applied correctly.

I don't know if the onus here is on @lmohrmann , @joleroi I was hoping to see such plots in your thesis. But it doesn't really matter, I didn't have any time to work on 1D spectral analysis and would prefer not to get involved at all. So if anyone has time to demonstrate what's what with a simple test case of two runs for stacked analysis, please go ahead. My understanding is that @joleroi already did this for "joint fit" and picked two runs in https://github.com/gammapy/gammapy/pull/1236#issuecomment-352675535, so the equivalent check should now be done for stacked?

**Comment by lmohrmann** [comment]
@registerrier I hadn't seen that the stacked edisp somehow takes into account the different energy thresholds, thanks for pointing this out. I looked a bit further into this using the test script below. It turns out my naive calculations differ from the Gammapy results in the way the energy thresholds are applied: Gammapy applies them in reconstructed energy space, whereas I apply them in true energy space (this, I believe, is also what HAP effectively does).

Since we usually determine the energy thresholds based on the energy bias or the effective area itself, both as a function of true energy, I'd tend to think that they should also be applied in true energy space. Anyone having thoughts on this?

This is the test script:

```python
import numpy as np
from gammapy.spectrum import SpectrumObservation, SpectrumObservationList, PHACountsSpectrum
from gammapy.spectrum.models import PowerLaw
from gammapy.irf import EffectiveAreaTable, EnergyDispersion
from astropy import units

np.random.seed(137)

nbins = 10
nobs = 6

livetime = 100

ereco = np.logspace(-1, 1, nbins+1) * units.TeV
etrue = np.logspace(-1, 1, nbins+1) * units.TeV

# Create dummy effective areas
aeff = [EffectiveAreaTable(etrue[:-1], etrue[1:],
                           np.random.random() * np.linspace(1, nbins+1, nbins) * units.m**2)
        for i in range(nobs)]

# Create dummy energy dispersions (equal for all observations!)
edisp = EnergyDispersion.from_gauss(etrue, ereco, 1, 0)

# Create dummy counts
dummy_counts = PHACountsSpectrum(etrue[:-1], etrue[1:], np.zeros(nbins),
                                 meta=dict(EXPOSURE=livetime))

# Produce observations
obs_list = SpectrumObservationList([SpectrumObservation(dummy_counts.copy(),
                                                        off_vector=dummy_counts.copy(),
                                                        aeff=aeff[i], edisp=edisp)
                                    for i in range(nobs)])

# Define and set thresholds, different for each observation
thresholds = ereco[:nobs]
for obs,thr in zip(obs_list, thresholds):
    obs.lo_threshold = thr

# Stack observations
stacked_obs = obs_list.stack()

def get_e_mask(obs):
    mask = obs.aeff.energy.log_center() > obs.lo_threshold
    mask &= obs.aeff.energy.log_center() < obs.hi_threshold
    return mask

def stack_aeff(obs_list):
    aefft = np.zeros(nbins) * units.m**2 * units.s
    t = np.zeros(nbins) * units.s
    for obs in obs_list:
        mask = get_e_mask(obs)
        aefft[mask] += obs.aeff.data.data[mask] * obs.livetime
        t[mask] += obs.livetime
    aeff = aefft[aefft>0] / t[aefft>0]
    return aeff

def stack_livetime(obs_list):
    t = np.zeros(nbins) * units.s
    for obs in obs_list:
        mask = get_e_mask(obs)
        t[mask] += obs.livetime
    return t

# Compute stacked aeff, edisp, livetime
aeff_stacked = stack_aeff(obs_list)
edisp_stacked = edisp  # no stacking here: all observations have the same edisp
livetime_stacked = stack_livetime(obs_list)

print('Aeff Gammapy:')
print(stacked_obs.aeff.data.data.to('m2'))
print('Aeff LM:')
print(aeff_stacked)

# Define dummy model and compute flux
model = PowerLaw(index=2, amplitude=0.1*units.Unit('m-2 s-1 TeV-1'), reference=1*units.TeV)
flux = model.integral(etrue[:-1], etrue[1:])

# Compute expected counts for this flux
# Gammapy
npred1 = stacked_obs.edisp.apply(stacked_obs.aeff.data.data.to('m2') * flux * stacked_obs.livetime)
# My version
npred2 = edisp.apply(aeff_stacked * flux * livetime_stacked)
# Single observations
npred3 = np.zeros(nbins)
npred4 = np.zeros(nbins)
for obs in obs_list:
    mask = get_e_mask(obs)
    # apply energy threshold in reco energy space
    npred3[mask] += edisp.apply(obs.aeff.data.data * flux * obs.livetime)[mask]
    # apply energy threshold in true energy space
    counts_true = np.zeros(nbins)
    counts_true[mask] += obs.aeff.data.data[mask] * flux[mask] * obs.livetime
    npred4 += edisp.apply(counts_true)

print('')
print('Npred Gammapy:')
print(npred1)
print('Npred LM:')
print(npred2)
print('Npred single, reco energy thresholds:')
print(npred3)
print('Npred single, true energy thresholds:')
print(npred4)
```

And this is the output:

```
Aeff Gammapy:
[ 0.57167649  1.20687258  1.84206868  2.47726478  3.11246087  3.74765697
  4.38285307  5.01804917  5.65324526  6.28844136] m2
Aeff LM:
[ 0.94385021  1.08974947  1.85574781  2.63006852  3.18756531  3.74765697
  4.38285307  5.01804917  5.65324526  6.28844136] m2

Npred Gammapy:
[  19.29375334   35.92360625   75.30441475  101.08215164  103.01276245
   95.46122715   72.41130299   53.37308785   37.35138107   24.22849239]
Npred LM:
[ 22.79581729  44.14776708  65.85523736  81.5647144   88.26125319
  82.6228321   69.38959695  53.37308785  37.35138107  24.22849239]
Npred single, reco energy thresholds:
[  19.29375334   35.92360625   75.30441475  101.08215164  103.01276245
   95.46122715   72.41130299   53.37308785   37.35138107   24.22849239]
Npred single, true energy thresholds:
[ 22.79581729  44.14776708  65.85523736  81.5647144   88.26125319
  82.6228321   69.38959695  53.37308785  37.35138107  24.22849239]
```

As explanation: I create some dummy observations with different Aeffs, different energy thresholds, but equal energy dispersion.

Then I compute the averaged effective area first with Gammapy, then using my function that takes into account the different thresholds. As expected, the results differ.

I then compute the number of predicted counts for some dummy energy spectrum. For Gammapy I use the stacked edisp that Gammapy computes, in my own, naive calculation I simply use the edisp matrix that is common to all observations (which should be valid for the stacked observation as well, given that it's the same for all). Finally, I compute the predicted counts for each single observation, once applying the thresholds in reconstructed and once in true energy space, and then adding them up.

You can see that the Gammapy results are identical to the ones where I apply the thresholds in reconstructed energy space for each observation, and my results are identical to those where I apply the thresholds in true energy space.

**Comment by registerrier** [comment]
Thanks for the example and explanation of the difference @lmohrmann. It is very helpful.

 I must say I don't know precisely how thresholds are handled in HAP.  But I now better understand where the discrepancy arises. 

If you want to do forward-folding, it is necessary to define thresholds in reco energy, because your data points are in reco energy. The rejected bins are then excluded from the spectrum stacking. The IRF stacking must then reflect this. The stacking used in `IRFStacker` ensures that the number of predicted counts of the stacked spectrum is equal to the stacked predicted counts of individual spectra. This stacking scheme is the same as that used in START.

There might be other ways to stack IRF that can introduce reco energy dependent exposure, but I think they also implies reco energy dependent effective areas.

 The approach we have now is correct I think. Maybe, we could improve testing and documentation in the line suggested by Christoph.

**Comment by JouvinLea** [comment]
Thanks a lot @lmohrmann !!
At least now we have a dobble check that the implementation with the threshold in reco energy is right!

**Comment by lmohrmann** [comment]
@registerrier - I'm note sure I'm following.

> If you want to do forward-folding, it is necessary to define thresholds in reco energy, because your data points are in reco energy

If I do forward folding, I'd expect to obtain data points (or, rather, flux points) in true energy, not reconstructed energy. Or what do you mean by "data points"?

I agree that the stacking process should make sure that the stacked spectrum yields the same predicted counts as the summed predicted counts of the individual spectra. But that is independent of the question whether the thresholds are applied before or after applying the energy dispersion matrix (i.e. in true or reconstructed energy space).

The approach implemented in Gammapy now is correct in case one wants to apply the thresholds in reconstructed energy space, I think. However, I can also think of good arguments to apply the thresholds in true energy space (which we do in HAP, as I just checked again). Neither approach is correct I'd say - this is a matter of definition.

@cdeil, @joleroi: do you have thoughts on this?

I'll try to think of a way to implement an option to apply the thresholds in true energy space and open a PR if I find one.

**Comment by lmohrmann** [comment]
It turns out implementing such an option is fairly straightforward. PR is here: #1267.

**Comment by joleroi** [comment]
> However, I can also think of good arguments to apply the thresholds in true energy space

I cannot see an argument to do this. My understanding of the threshold is that you assume that you cannot reconstruct events properly below the threshold, therefore you throw away the data below it (I guess that's what @registerrier meant by data points). Since the data is always in reco energy the threshold should also be applied there. Applying a threshold in true energy is like saying that the source somehow stops working below a certain energy. 

@lmohrmann  Can you explain in what situation a threshold in true energy would make more sense (and thus justify the extra complexity of giving both options)

**Comment by cdeil** [comment]
We have had several important discussions about 1D spectral analysis in a few Github issues.

@registerrier has kindly agreed to summarise what we have and what changes / additions should be made on slides on Monday, Feb 5 afternoon at the Gammapy coding sprint: https://github.com/gammapy/gammapy-meetings/tree/master/2018-02-05#preliminary-agenda
@lmohrmann @joleroi - if you cannot come, maybe you can join remotely via eZuce for that topic? If not, I would suggest a call with the three of you and probably Cosimo and me in February. It'll be more fun / efficient to get 1D spectral analysis sorted out by talking to each other than over Github.
This is just a suggestion, of course it shouldn't stop anyone from doing pull requests and improve things now via Github if you have time!

**Comment by lmohrmann** [comment]
@joleroi 
We assume that we cannot reconstruct events below a given threshold, yes. But why does that threshold need to be defined in reconstructed energy units? In fact, we usually determine the threshold by plotting the energy bias as a function of **true** energy (and then choosing an energy above which the bias is small enough). Thus, it would be only natural to then apply that threshold in true energy space. I can also see arguments for applying it in reconstructed energy space, which is why I didn't suggest to change the default behavior.

As a side note: I think in HAP we actually do both, i.e. apply the same threshold first in true energy space, and then again in reconstructed energy space. This would also be possible in Gammapy with the PR I made.

@cdeil 
I should have time on the afternoon of Feb 5. Let me know when exactly you plan to discuss this and I will try to join.

**Comment by cdeil** [comment]
My 2 cents: I think applying a cut always has to be done in reco parameter, in this case the safe energy cut in reco energy. For the data you can only apply it to reco energy, so to get matching  `n_pred` for the given `n_obs` as a function of reco energy, the only way to get that for any spectrum / AEFF / EDISP is to apply the same cut at the very end of the `n_pred` computation, where you have the `n_pred` vector as a function of reco energy.

There's probably cases where applying the cut for true energy or applying it to both true and reco yields correct or almost correct results. But given that it's incorrect for the general case, it's probably best to never do this?

I have to say: I'm not 100% sure here, and I haven't throught this through or done a notebook with some simple example to fully convince myself (e.g. one or two spectral lines, some simple AEFF and very high, constant bias EDISP, e.g. e_reco = 3 x e_true, and different locations for the energy threshold to apply).

---

@lmohrmann - As far as I know the EDISP handling in HAP was never used for a publication. Is that true or are people using that? I added it 5 years ago, but got weird results and wasn't sure about these questions that come up now with the threshold and gave up. Then Christopher finished it, but I've never seen any review or study showing that something correct comes out.

**Comment by cdeil** [comment]
@lmohrmann or @registerrier  - This discussion ended in January. Is there a conclusion or is more discussion needed? Ideally we'd close out old issues or find action items (i.e. summarise proposed code changes or docs improvements) and move forward.

**Comment by registerrier** [comment]
Hi @lmohrmann, can we close this issue or is there something left to be done?

**Comment by lmohrmann** [comment]
No, I think it can actually be closed. I'm with @cdeil and @joleroi by now, i.e. I think the threshold should be applied to `npred` in reco energy space.

I'll just go ahead and close it now.

**Comment by cdeil** [comment]
> I think the threshold should be applied to npred in reco energy space. I'll just go ahead and close it now.

Agreed, good.

Although I'm not sure our filtering code is fully correct or structured as good as can be, especially for spectra (for maps it's much simpler and we don't have the case of multiple maps yet).

This is what we do at the moment in SpectrumFit and FluxPointEstimator:

https://github.com/gammapy/gammapy/blob/a8ea355a611b6d440f6ecaa04f1461fafba80abf/gammapy/spectrum/fit.py#L131

https://github.com/gammapy/gammapy/blob/a8ea355a611b6d440f6ecaa04f1461fafba80abf/gammapy/spectrum/flux_point.py#L731

@adonath wants to rewrite the FluxPointEstimator in the next ~ 2 weeks for v0.9, but also probably the SpectrumFit should be improved a little bit. So this PR is closed, but @lmohrmann @registerrier or @adonath  - if there is an issue or suggestion to improve something, please open a new issue or put it on the agenda for a weekly Gammapy (Fridays 10 am, next one Nov 9).
