### ISSUE TITLE
Two notebook copies in docs

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1270]
I saw that there's two copies of the notebooks in `docs/notebooks` and also in `docs/_static/notebooks`. The `docs/notebooks` is in `.gitignore`, the `docs/_static/notebooks` is not. In both cases `.ipynb_checkpoints` is present, probably copied over from gammapy-extra.

@Bultako - Are the two copies in `docs` needed? Or can we avoid one copy?

**Comment by Bultako** [comment]
@cdeil 

These two folders are copied from `$GAMMAPY_EXTRA` in the process of documentation building. They are removed anytime a `make clean` command is executed and like the `docs/_build` folder I think they do not take part of the delivered sources of Gammapy.

The `docs/notebooks` folder contains the modified notebooks (with the green box on top) used to generate the static-notebooks of the HTML docs. The `docs/_static/notebooks` folder contains the raw notebooks (without the green box on top) and the *converted* **.py* scripts that may be downloaded from the  static-notebooks of the HTML docs, as well as some *.fits files needed to execute the notebooks that are at the root of the `notebooks` folder in `$GAMMAPY_EXTRA`.

If we have to remove one of the folder I would prefer to remove the `docs/notebooks` folder once the doc building process is completed and keep the `docs/_static/notebooks` folder. I guess we could also remove the *.fits files from  `docs/_static/notebooks` and adapt the notebooks to fetch them from `$GAMMAPY_EXTRA` datasets folder.

**Comment by cdeil** [comment]
I see. I'm not sure how to best arrange the different folders. Maybe doing everything in `docs/_static/notebooks` could be simpler, i.e. have sub-folders `raw`, `py` and `processed` or something like that there? Or we can leave as-is.

So for sure we should amend `.gitignore` to ignore all those folders, since they are all auto-generated files that we don't want to track, right?

And a few extra sentences at http://docs.gammapy.org/dev/development/setup.html describing this most difficult part of the docs build would be good, no?

**Comment by Bultako** [comment]
Well, the point is that Sphinx and `nbsphinx` need the **.ipynb* files in the same folder structure of the RST docs. 

There is only one line to add to `.gitignore`: docs/_static/notebooks
I could make a PR for this with the modified gitignore, removing `docs/notebooks` at the end of the building process, copying only **.ipynb* files from `$GAMMAPY_EXTRA` and adding some sentences in the docs related to this as you suggest.

FYI 
Other related docs:
http://docs.gammapy.org/dev/development/howto.html#sphinx-docs-build
http://docs.gammapy.org/dev/development/howto.html#link-to-a-notebook-in-gammapy-extra-from-the-docs

**Comment by cdeil** [comment]
I'm closing this old issue. I think there was no action item left here.
If yes, we can always reopen.
