### ISSUE TITLE
Improve FITS serialisation for stacked spectra

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1275]
While preparing the HESS data release, I ran into two issues with stacked spectra.

When stacking, a Python list is stored in the meta dict of the on and off counts. Then write fails because that can't be handled by a FITS header. For now I've implemented a workaround where I just put "stacked" under OBS_ID:
https://github.com/gammasky/HESS-DL3-DR1/blob/17390fe1a752af1eb11e7195348f6d2e9f98d5d0/hess_dl3_dr1/analysis_spec.py#L64
I'm not sure what the proper fix is here. Presumably Gammapy should either not write an OBS_ID at all, or if it does, store it in some way that FITS can handle?

A second issue is that I wrote a stacked spectrum to file and read it back, and then wanted to analyse it by computing spectral points. But that failed like this:
```
  File "/Users/deil/code/HESS-DL3-DR1/hess_dl3_dr1/analysis_spec.py", line 134, in make_spectrum_points
    seg = SpectrumEnergyGroupMaker(obs=obs_list_stacked)
  File "/Users/deil/code/gammapy/gammapy/spectrum/energy_group.py", line 376, in __init__
    self.groups = self._groups_from_obs(obs)
  File "/Users/deil/code/gammapy/gammapy/spectrum/energy_group.py", line 393, in _groups_from_obs
    table = obs.stats_table()
AttributeError: 'SpectrumObservationList' object has no attribute 'stats_table'
```
For now, I recompute the stacked spectrum multiple times in my scripts, instead of reading the version from file back: https://github.com/gammasky/HESS-DL3-DR1/blob/17390fe1a752af1eb11e7195348f6d2e9f98d5d0/hess_dl3_dr1/analysis_spec.py#L117

Finally a feature request: I would prefer to have the option to write a single FITS files with many HDUs, instead of having to write all these tiny separate FITS files.

@registerrier @lmohrmann @joleroi - thoughts?

**Comment by registerrier** [comment]
Regarding the last point (multiple files instead of ones), as far as I remember @joleroi had tested the export to OGIP type II format. 
https://heasarc.gsfc.nasa.gov/docs/heasarc/ofwg/docs/spectra/ogip_92_007/node8.html
I don't know what came out of it.

**Comment by cdeil** [comment]
I'm just closing this old issue now. I have no idea if it's still there or not, I'm not using that any more.
If someone is using this functionality and finds an issue with it in the future, please comment here, or better yet open a new issue. Please try to post a minimal example to reproduce the error.
