### ISSUE TITLE
Flux point estimator API

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1276]
I'm having some trouble with the [gammapy.spectrum.FluxPointEstimator](http://docs.gammapy.org/dev/api/gammapy.spectrum.FluxPointEstimator.html)

For the HESS test data release I noticed that by default when one makes a `FluxPointEstimator` and runs `compute_points` it gives results where the energies are in keV (should be TeV) and column `dnde_errp` and `dnde_errn` are added but not computed, which means that when plotting the flux points, the errors from `dnde_err` don't show up. Also the `__init__` or `compute_points` don't expose options what to do, e.g. whether to compute upper limits or asymmetric errors or not. As a workaround, here is what I did in the [HESS data release check script](https://github.com/gammasky/HESS-DL3-DR1/blob/17390fe1a752af1eb11e7195348f6d2e9f98d5d0/hess_dl3_dr1/analysis_spec.py#L150
):
```
    # We do some clean-up of the results table
    table = fpe.flux_points.table
    table['e_ref'] = table['e_ref'].quantity.to('TeV')
    table['e_min'] = table['e_min'].quantity.to('TeV')
    table['e_max'] = table['e_max'].quantity.to('TeV')
    table.remove_columns(['dnde_errp', 'dnde_errn'])
    for name in ['e_ref', 'e_min', 'e_max', 'dnde', 'dnde_err', 'dnde_ul', 'sqrt_ts']:
        table[name].format = '.5e'
```

I would suggest to either add more options to `__init__` or `compute_points`, or alternatively to advertise how to use the lower-level API of doing separate computations for each point.

#1140 by @bkhelifi is related. CC @registerrier @adonath @joleroi @lmohrmann

**Comment by adonath** [comment]
Addressed by #1929, #1933 and #1934.
