### ISSUE TITLE
Links to notebooks

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1283]
I noticed that we still link to nbviewer for the Gammapy notebooks.
E.g. from
http://docs.gammapy.org/dev/spectrum/index.html#using-gammapy-spectrum
we link to 
https://nbviewer.jupyter.org/github/gammapy/gammapy-extra/blob/master/notebooks/spectrum_analysis.ipynb

I think this should link here instead, no?
http://docs.gammapy.org/dev/notebooks/spectrum_analysis.html

I'm not sure what the best way to implement that is. But the current link is generated here:
https://github.com/gammapy/gammapy/blob/c7e8f47b18927e3e5a1f928c7493ff8174c89c79/gammapy/utils/docs.py#L89

**Comment by Bultako** [comment]
Just for contextual info.
At this moment there are two ways of linking to static notebooks:
* with the `:gp-extra-notebook:` Sphinx directive
* using relative links to `docs/notebooks` folder

http://docs.gammapy.org/dev/development/howto.html#link-to-a-notebook-in-gammapy-extra-from-the-docs 

I could modify the function for the `:gp-extra-notebook:` directive to point the links to relative paths in the `docs/notebooks` folder so we can keep both methods.

**Comment by cdeil** [comment]
How about always using a `:gp-notebook:` directive, and have that point to the local version?

Now that we have HTML versions of the notebooks in our docs, I don't think we need to link to nbviewer? If it's useful for some reason, it could be via `:gp-notebook-nbviewer:` to be as simple / similar as possible?

I don't have a preference for how the links are generated, my suggestion here is just to link to the local HTML version instead of to nbviewer.
