### ISSUE TITLE
Delete PRs

### ISSUE THREAD

**Issue by mackaiver** [gammapy/gammapy#1297]
I propose to simply remove all pull requests older than two months or so. :see_no_evil:

**Comment by cdeil** [comment]
@mackaiver - Most open PRs are from me. I will work on finishing them up or closing them in the coming weeks. E.g. I just now closed #175 .

I'm also closing out some issues, e.g. this one. :-)

Generally in Gammapy looking through the issues / PRs is a terrible way to get involved. The only thing that really makes sense is to pick one thing that's bad or missing, and make it better or add it.
