### ISSUE TITLE
Fix docs PDF build

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#13]
The docs PDF build gives errors:
https://readthedocs.org/builds/gammapy/

and doesn't look good:
https://media.readthedocs.org/pdf/gammapy/latest/gammapy.pdf

First check package-template if the problem is there already.

**Comment by cdeil** [comment]
I looked at this again for the upcoming Gammapy 0.3 release.

Well, at some point (no idea when) the Gammapy PDF build on readthedocs started working again:
https://readthedocs.org/builds/gammapy/3176162/
The PDF looks OK.

I tried to build the PDF on my Macbook.

As described [here in the Astropy docs](http://astropy.readthedocs.org/en/latest/install.html#building-documentation), the proper commands to build the PDF are:
```
python setup.py build_docs -b latex
cd docs/_build/latex
pdflatex gammapy
```

At first I got an error from `pdflatex` that `inconsolata.sty` is missing, but as noted in the Astropy-docs, installing `texlive-fonts-extra` fixed it:
```
sudo port install texlive-fonts-extra
```

Then the PDF build fails with this error:
https://gist.github.com/cdeil/d10c858692aa902ffa4c#file-gistfile1-txt-L1250

It's pointing to this line in the Sphinx-generated `gammapy.tex`:
https://gist.github.com/cdeil/470f03224b4df3f53c08#file-gistfile1-txt-L3057

So it looks like there's a formatting issue with this table (which looks OK in the html output)
http://gammapy.readthedocs.org/en/latest/dataformats/file_formats.html#overview

The readthedocs log doesn't show what commands they run, so I don't know why it works there.
So for now I'll keep this issue open, but move the milestone to the 0.4 release.

**Comment by cdeil** [comment]
The PDF build is currently working locally for me and on RTD.

The PDF looks mostly OK:
https://media.readthedocs.org/pdf/gammapy/latest/gammapy.pdf

500 pages, and I didn't even know we had so many pretty Figures.

I've added the commands that work for me locally to build the PDF in #714 (commit: 0274c03)

Closing this issue now.

**Comment by cdeil** [comment]
Gammapy PDF build is broken again on RTD:
http://readthedocs.org/projects/gammapy/builds/4649893/

Re-opening this issue.

- [ ] Fix PDF build
- [ ] Add PDF docs build on travis-ci so that this doesn't keep breaking

**Comment by cdeil** [comment]
@bsipocz - Thanks for making the PR #779.

The Gammapy PDF docs build has been braking many times over the past years.

Would it be possible to add a travis-ci build that runs it?
I think the commands that should be run are these and then the exit status needs to be checked:
http://docs.gammapy.org/en/latest/development/howto.html#sphinx-docs-build
```
python setup.py build_docs -b latex
cd docs/_build/latex
makeindex -s python.ist gammapy.idx
pdflatex -interaction=nonstopmode gammapy.tex
```

**Comment by cdeil** [comment]
PDF is currently working: https://media.readthedocs.org/pdf/gammapy/latest/gammapy.pdf
Remaining task is stated in my last comment: add CI build for PDF to make sure it doesn't break again.
Moving this issue to v0.7.

**Comment by cdeil** [comment]
I'm closing this old issue now. At the moment, we don't offer a PDF or EPUB version of the Gammapy docs any more. It would only be of interest to a small fraction of users, most use HTML. Maybe it still works, I didn't try. I'd suggest to just do nothing here. There are other features for docs that IMO would be more important, e.g. a version chooser for the HTML docs.

**Comment by bsipocz** [comment]
@cdeil - with RTD there should be an option to choose the version (though with quick look it seems that you don't use that on http://docs.gammapy.org/?)

**Comment by cdeil** [comment]
@Bultako - I realise multi-version selector isn't easy to implement.

We already discussed a bit in https://github.com/gammapy/gammapy/issues/1241 .

Let's not continue here, but over there, but with low priority, only if someone has time to work on this.
