### ISSUE TITLE
Coding pattern to handle scalars in functions

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1301]
Numpy behaves nicely wrt. scalars and arrays, i.e. when given a scalar it returns a scalar:
```python
>>> import numpy as np
>>> np.sin(42)
-0.9165215479156338
>>> np.sin([42])
array([-0.91652155])
>>> np.sin([[42]])
array([[-0.91652155]])
```

We currently have this, i.e. we don't return scalars for scalar input:
```
>>> from gammapy.stats import significance
>>> significance(n_on=10, mu_bkg=3)
array([3.17481591])
>>> significance(n_on=[10], mu_bkg=3)
array([3.17481591])
```
Unrelated to this discussion, just as a note to myself, I think there's also a bug:
```
>>> significance(n_on=[[10]], mu_bkg=3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/deil/code/gammapy/gammapy/stats/poisson.py", line 239, in significance
    s[mask] = func(n_on[mask], mu_bkg[mask])
IndexError: too many indices for array
```

There was a discussion at https://mail.python.org/pipermail/numpy-discussion/2017-December/077512.html about good patterns for functions that handle scalars and arrays.
and as far as I can tell the best suggestion / conclusion was that this is the best pattern:
```
def func_for_scalars_or_vectors(x):
     x = np.asanyarray(x) # convert scalars to 0d arrays

     # The magic happens here

     return ret[()]  # convert 0d arrays to scalars
```
I'd like to start using it in a few places, e.g. in [gammapy.stats.significance](http://docs.gammapy.org/dev/api/gammapy.stats.significance.html) that I used in the example above.

@woodmd @kosack @adonath  or anyone that knows Numpy well - Is that a good idea or is there a better way? (e.g. just accept the current behaviour or adapt some other coding pattern)

**Comment by adonath** [comment]
The `CountsStatistics` consistently convert to `np.asanyarray()` they don't preserve scalar values. This is maybe not the perfect behavior but it is consistent with in `gammapy.stats`.

**Comment by registerrier** [comment]
The pattern has changed with numpy v2.0 as floats can not be treated as arrays. Closing now.
