### ISSUE TITLE
Change Map write from extname to hdu?

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1320]
@woodmd - I noticed that in `gammapy.map` you use `extname` in a few places:
https://gist.github.com/cdeil/750e97c24864dfdb2d5ed1a22fb4d277

We don't use it anywhere else in Gammapy, so especially in `map.write` I would suggest to rename from `extname` to `hdu`, to be consistent with the rest of Gammapy (and also e.g. `Table.read` and `Table.write` in Astropy) and could make a PR for this change.

I realise that `extname` is partly used in the `astropy.io.fits` interface, and it is a FITS header key, so I'm not saying we can / should remove all mentions of `extname` in `gammapy.maps`.

@woodmd - How would you feel about mostly using `hdu` for better consistency, and to only use `extname` internally where needed, i.e. when interacting with the FITS header keyword of that name, or possibly some `astropy.io.fits` method that uses that term (if we use any of those).

**Comment by woodmd** [comment]
This is fine by me.  I'll go ahead and add this change to #1318.

**Comment by cdeil** [comment]
Closing this issue now. I checks in the branch in #1318 that `extname` no more appears in Gammapy.

There's a mix of "hdu" and "hduname", but I think that makes sense, i.e. just using "hdu" everywhere would be confusing. Of course, follow-up suggestions in the future still welcome.
