### ISSUE TITLE
SpectrumFit and SpectrumAnalysisIACT suggestions

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1333]
@cosimoNigro  and I have some suggestions to improve [SpectrumFit](http://docs.gammapy.org/dev/api/gammapy.spectrum.SpectrumFit.html) and [SpectrumAnalysisIACT](http://docs.gammapy.org/dev/api/gammapy.scripts.SpectrumAnalysisIACT.html).

One mistake I made was to access `spectrum_fit.model` after the fit and thought it would be the fit result. But it's not, and it's also not the input model. I think the modification of the input model occurs [here](http://docs.gammapy.org/dev/_modules/gammapy/spectrum/fit.html#SpectrumFit.likelihood_1d).
This should be improved / clarified. Probably best to leave it as the input model and untouched, no?

For `SpectrumAnalysisIACT`, could you please split out the flux point computation into a separate method? At the moment we are debugging spectral fit, and don't want to run or have to give parameters for spectral points.

@joleroi - you can see the example we are working with here:
https://github.com/gammasky/joint-crab/commit/c0318102d3955f22ab3350f5897b00d70c4a0da1

**Comment by joleroi** [comment]
Done in #1345
