### ISSUE TITLE
PSF containment correction is applied in reco energy bins rather than true energy bins 

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#1338]
The PSF containment correction computed in `SpectrumExtraction.apply_containement_correction` is performed for each bin in e_reco and stored in the `PHACountSpectrum.areascal` vector of the ON and OFF vectors.
This logic seems incorrect and might lead to incorrect results especially close to the threshold. 
Normally the PSF should be computed in each true energy bin and should be applied to the 1D effective area not stored in the areascal array. No? @joleroi

**Comment by joleroi** [comment]
I commented on this in  https://github.com/gammapy/gammapy/issues/684

I agree that the PSF correction should be applied in true energy. I don't see your second point, however. Why don't you like the ``AREASCAL`` column. It's like applying it to the effective area with the benefit that you keep the information how much the correction was.

**Comment by registerrier** [comment]
The issue with `AREASCAL` is precisely that it is applied to the reco energy bins. 
One could estimate the scaling factor by computing the average correction to apply in a e_reco bin integrating over all true energies i.e. int dE_t rmf(E_r,E_t) \Phi(E_T) arf(E_t).
But this supposes to assume a spectral index. It seems simpler to simply modify the arf accordingly, no? 
Most likely the difference with computing the `AREASCAL` in the center of the reco energy bin is tiny in most situations, but it might not be the case if the spectrum or the responses vary rapidly.

**Comment by joleroi** [comment]
> The issue with AREASCAL is precisely that it is applied to the reco energy bins.

Of course :man_facepalming: 

I think it'd be nice to keep the information of how much the effective area correction was, but I guess it will be hard to do this in a OGIP compliant way. [Here](https://heasarc.gsfc.nasa.gov/docs/heasarc/caldb/docs/memos/cal_gen_92_002/cal_gen_92_002.html#tth_sEc4) in Section 4.1.2. point 3 it is stated explicitly that the ARF file should contain the _product of all the components (effective area, filter transmission, correction factors etc)_ if I read the memo correctly.

@registerrier You suggest to remove the ``AREASCAL`` column completely right? Would you be willing to do this change or should I?

**Comment by registerrier** [comment]
OK. I am not completely clear about it. Since it is there already, one can keep it. We might use it in some situations.

I can do the change if you want.

**Comment by cdeil** [comment]
Just a general thought: don't let OGIP formats dictate the Gammapy data model. Generally we should aim to have a simple and nice internal data model / data structures, and then if like in this case where legacy formats exist translate at the I/O boundary.

I haven't followed the discussion in detail or if this helps make a decision here.
@registerrier @joleroi - do you have an opinion what to do here? Or would talking about it help (e.g. at the Gammapy call tomorrow 11 am or right after)?

**Comment by cdeil** [comment]
@joleroi - Here's the example I mentioned in the call, where we had to apply containment correction a second time to the flux points, for unknown reasons:
https://github.com/gammasky/cta-analyses/blob/master/dc-1-checks/hess_j1702/spectrum.ipynb

**Comment by joleroi** [comment]
Fixed by #1343
