### ISSUE TITLE
Implement spectral table model

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#134]
@ellisowen We should implement a spectral table model.

The simplest thing would be to have a piecewise power-law at a few given points (with linear extrapolation beyond the edge points):
http://gammalib.sourceforge.net/user_manual/modules/model.html?highlight=nodes#node-function
http://gammalib.sourceforge.net/doxygen/classGModelSpectralNodes.html
(this is what you implemented as `my_model` in the spectral point example).

But we could also have a polynomial in log or use the `UniVariateSpline` to get something that is optionally more smooth when evaluating it.

**Comment by jjlk** [comment]
Hi @cdeil @joleroi ,
Now that the spectrum.models module looks fine, do you think we could add a spectral table model class ? I'd like to use that with the gammapy.spectrum.utils.calculate_predicted_counts function.

I guess we could start with something similar to what they did in [naima.models.TableModel](http://naima.readthedocs.io/en/latest/api-models.html#naima.models.TableModel) and adapt it to your new SpectralModel class, right ?

I can work on that if you'd like.

**Comment by cdeil** [comment]
@jjlk - Yes, sure, that would be great.
You can also copy it over from Naima and leave a comment to give attribution.

**Comment by adonath** [comment]
Resolved by #733?

**Comment by cdeil** [comment]
Yes, like for the other issues: I would have suggestions for better tests / docs and in some cases also implementation. But no concrete high-level action items here, a basic version is implemented.

Closing issue now.
