### ISSUE TITLE
Bug with LIVETIME / EXPOSURE unit in spectrum extraction

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1348]
This is a bug that @mackaiver encountered here:
https://github.com/gammasky/joint-crab/issues/57#issuecomment-375651023

He has an observation index table where `datastore.obs_table['LIVETIME'].unit` is `s` (second),
and then when running `SpectrumExtraction` he finds that `extraction.observations[0].livetime` has unit `second ^ 2`.

This occurs because `PHACountsSpectrum.livetime` is taken from `PHACountsSpectrum.meta['EXPOSURE']` which is supposed to be a number in seconds without the unit attached:
https://github.com/gammapy/gammapy/blob/3b148304e65266da9728bae420aad58e7390886b/gammapy/spectrum/core.py#L334-L340

Tracing this back one can see how `PHACountsSpectrum.meta['EXPOSURE']` is filled here in `SpectrumExtraction` from `obs.obs_info`:
https://github.com/gammapy/gammapy/blob/3b148304e65266da9728bae420aad58e7390886b/gammapy/spectrum/extract.py#L159

and `obs.obs_info` is filled from the observation index table like this, which fills a Quantity object if the observation index table column (like `LIVETIME` in this case) has a unit:
https://github.com/gammapy/gammapy/blob/f7088819004aac3eb8c039e996229a4f7409e310/gammapy/data/data_store.py#L572-L575

There's probably two action items here:
1. `SpectrumExtraction` or `PHACountsSpectrum` can be changed to make sure unit handling is done correction or an error is raised (a small change)
2. The code should be changed so that values for the analysis are never taken from the observation index table, only from the GTI table and / or EVENTS header (a large change)

@joleroi - thoughts?

**Comment by joleroi** [comment]
> @joleroi - thoughts?

Let's abandon ``astropy.units``, it makes everything too complicated.  I'm kidding. I think your second option is the way to go, and I think it's not such a huge amount of work

**Comment by cdeil** [comment]
@joleroi - I'm not sure if your proposed change in #1349 is the best course of action here. It will trigger an extra events FITS table read from disk just to get one number from the header. And it will not solve the issue in other callers, e.g. when we compute exposure for 3D (cc @registerrier). I think we do want the `obs_info` abstraction and access livetime from analysis code via that. So maybe we just change something about the unit handling either in spectrum extract or obs info?
Also: The pop of `extname` will fail for some people if their events table doesn't have that header key. That's a FITS I/O issue, if this header key remove needed at all should be done in the FITS I/O routines.

I actually think this is pretty tricky what we should change now here (avoiding a large rewrite, making a few small changes to improve what we have). Maybe we do this as pair-coding tomorrow?

**Comment by joleroi** [comment]
> It will trigger an extra events FITS table read from disk just to get one number from the header

Right, I didn't consider that

> So maybe we just change something about the unit handling either in spectrum extract or obs info?

This would be most robust at least short term I guess

> Maybe we do this as pair-coding tomorrow?

We can talk about file handling etc. in gammapy but I'm afraid we won't come to any conclusion :wink:

**Comment by mackaiver** [comment]
A new wild issue appeared.

https://github.com/gammasky/joint-crab/pull/63#issuecomment-381057785

**Comment by cdeil** [comment]
The issues mentioned here should all be resolved in gammapy.master. Closing.
