### ISSUE TITLE
Sphinx warning from CTA notebooks

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1361]
@Bultako - I mentioned it and we discussed / investigated a bit in #1176 and #1215 , but never figured it out. I still see these warnings locally:
```
/Users/deil/code/gammapy/docs/notebooks/cta_1dc_introduction.ipynb:45: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/Users/deil/code/gammapy/docs/notebooks/cta_1dc_introduction.ipynb:1797: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/Users/deil/code/gammapy/docs/notebooks/cta_data_analysis.ipynb:45: WARNING: Explicit markup ends without a blank line; unexpected unindent.
```

I'd like to finally figure those out and resolve them. @Bultako - You don't see those locally, right?
Then I'd have a closer look at versions and where / when those appear in the next days ...

**Comment by Bultako** [comment]
@cdeil 
I do not see those warnings locally :(
In case it helps this is my sphinx-related local config

<pre>
$ conda list sphinx
# packages in environment at /Users/jer/anaconda/envs/gammapy-dev:
#
# Name                    Version                   Build  Channel
astropy-sphinx-theme      1.0.0                     <pip>
nbsphinx                  0.2.17                    <pip>
sphinx                    1.7.2                    py36_0    conda-forge
sphinx-autobuild          0.7.1                     <pip>
sphinx-click              1.0.4                     <pip>
sphinx_rtd_theme          0.2.4                    py36_0  
sphinxcontrib             1.0              py36h9364dc8_1  
sphinxcontrib-websupport  1.0.1            py36h92f4a7a_1 
</pre>

**Comment by cdeil** [comment]
I never took the time to track down this issue.
But good news, I don't see it locally any more.
Closing issue.

@Bultako - Thanks for your patience with me bringing this up several times and never resolving it.
