### ISSUE TITLE
Implement template background spectrum (TBS)

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#137]
As a continuation of #42, we should implement template background estimation for spectra as in [Fernandes 2014](http://adsabs.harvard.edu/abs/2014arXiv1407.0925F).

**Comment by cdeil** [comment]
Milton shared his TBS Python code with us and gave us permission to use / integrate it into Gammapy. For now it's here: https://github.com/gammasky/hess-host-analyses/tree/master/tbs

I think at the moment no-one has time to do this, but it would be a very welcome addition ...

**Comment by adonath** [comment]
As we rely on DL3 data input in Gammapy this method is not really in scope for Gammapy.
