### ISSUE TITLE
Support Map in 1D analysis

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1391]
One more task to be able to transition from SkyImage to Map is to adjust the 1D spectrum code to work with Map. This should be a relatively minor change in the part that deals with exclusion regions and reflected regions.

Since SkyImage is the deprecated one, I think the best way is to change the API to Map and internally work with Map, but for now if a SkyImage is passed, then it's immediately converted to a Map object via http://docs.gammapy.org/dev/api/gammapy.image.SkyImage.html#gammapy.image.SkyImage.to_wcs_nd_map

I'm not sure if this task requires first to add the method to make masks from regions to Map or if that is separate. If so, the code and tests should be copied and adapted from the old version here:
http://docs.gammapy.org/dev/api/gammapy.image.SkyImage.html#gammapy.image.SkyImage.region_mask
Best to do that first, in a separate small PR.

**Comment by registerrier** [comment]
I'll take care of this.

Some question though: is it safe to have a default mask at all? Since it is defined in galactic coordinates it will give weird results in many situations, in particular when the Plate-Carrée projection is inadapted.

**Comment by cdeil** [comment]
> I'll take care of this.

Thanks for taking this on!
I didn't start this one because it's complex and I wasn't sure what we want.

> Some question though: is it safe to have a default mask at all? 

Looking at  https://github.com/gammapy/gammapy/blob/master/gammapy/background/reflected.py again, I would suggest to change the algorithm to be SkyCoord based, not PixCoord.

Note that since 2016 this is available, so reflected region computation in sky coords should now be just a few lines:
http://docs.astropy.org/en/stable/api/astropy.coordinates.SkyCoord.html#astropy.coordinates.SkyCoord.skyoffset_frame
I admit this is more complex than reflecting regions in the plane, but we have to learn skyoffset_frame anyways, we'll also use it for FOV coordinates and to replace this code:
https://github.com/gammapy/gammapy/blob/master/gammapy/utils/coordinates/fov.py

So then if no exclusion mask is given, we don't need to invent one. (If we did, I would have suggested TAN projection on the obs pointing position).

If there is an exclusion, the same algorithm can be used, just discarding reflected regions based on a similar method to what we have now: use the "pixel distance to exclusion region" image, and then transform reflected region center to pixel position, look up value in that map, and compare to some pixel-scale equivalent of region center. That should work OK for almost everyone. Most people have small maps, for GPS work the distortions are really small and I think it's super rare to want all-sky e.g. AIT map exclusion masks and use those for reflected regions.

Note that for the docs we still have such an alls-ky map from tevcat. There's another issue to remove that completely. I'll take care of this.

@registerrier - What do you think? How should this stuff work?

**Comment by cdeil** [comment]
Transition to Map done by @registerrier done in #1589 .

Keeping this open for now, as reminder concerning the question whether to change to a SkyCoord based algorithm and making the exclusion mask optional.

**Comment by cdeil** [comment]
Decided to keep reflected region computation as-is for now.
I still think it could / should be done with SkyCoord, but we have many other high-priority issues.
Closing this one now, the transition to gammapy.maps is done.
