### ISSUE TITLE
Default for overwrite in write methods

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1396]
What default should we use for `overwrite` in `write` methods? `True` or `False`?

This question came up in  https://github.com/gammapy/gammapy/issues/1392#issuecomment-384146524 because currently in `gammapy.maps` we have default `overwrite=True`, whereas everywhere else in Gammapy we have default `overwrite=False`.

I find this decision is a close call, just to point out some relevant concerns:

* The Python `open('file.txt', 'w')` has `overwrite=True` behaviour. In Astropy `overwrite=False` default is used, probably inherited from `astropy.io.fits` and then used also for `Table.write`.
* Really many time one wants `overwrite=True`, almost all scripts / notebooks will put this so that they can re-execute. But for the very rare case that one overwrites something unintentionally that is expensive to recompute, of course one wishes the default had been `overwrite=False`.
* I think we should be consistent within Gammapy, but the decision could go either way, i.e. be consistent with Python write default or Astropy write default.

I haven't looked around much what other packages do. From the first two entries at
https://github.com/cta-observatory/ctapipe/search?p=1&q=overwrite&type=&utf8=%E2%9C%93
I think ctapipe also has a mix currently.

@woodmd @registerrier @joleroi @kosack - Could you please comment or just vote on this point what default to use?

**Comment by cdeil** [comment]
I'm +1 to use `overwrite=True` default everywhere in Gammapy because it's what one wants most of the time (consistent with Python itself for `open`,  opposite to Astropy default). 🔪 ✂️ 🔥 

@registerrier @joleroi  and all - please vote here.

**Comment by joleroi** [comment]
+1 for ``overwrite=False``, better safe than sorry

**Comment by registerrier** [comment]
I would also support `overwrite=False` as the default and have write(overwrite=True) in notebooks and example.

**Comment by cdeil** [comment]
Ha ha, then we have a tie: @woodmd and I like `overwrite=True` as default and @registerrier / @joleroi like `overwrite=False`. @leajouvin or @adonath - please vote.

**Comment by leajouvin** [comment]
I support the "better safe than sorry" of Johannes (-; so overwrite=False

**Comment by cdeil** [comment]
OK, then I'd suggest we change to `overwrite=False` consistently in Gammapy.
#1412 does the change for gammapy.maps, and #1413 for SpectrumExtract.

**Comment by cdeil** [comment]
Resolved via #1412 and #1413. Closing.
