### ISSUE TITLE
API to create models and interact with parameter errors

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1398]
Currently the Gammapy API to create models uses quantity objects (or numbers / strings that pass through the Quantity init) which are then passed to the Parameter init:
```
>>> from gammapy.spectrum.models import PowerLaw
>>> m = PowerLaw(index=2.3, amplitude='1e-12 cm-2 s-1 TeV-1')
>>> print(m)
PowerLaw

Parameters: 

	   name     value   error       unit      min max frozen
	--------- --------- ----- --------------- --- --- ------
	    index 2.300e+00   nan                 nan nan  False
	amplitude 1.000e-12   nan 1 / (cm2 s TeV) nan nan  False
	reference 1.000e+00   nan             TeV nan nan   True
```
This doesn't support setting parameter errors on init, one has to do it after init:
```
>>> m.parameters.set_parameter_errors(dict(index=0.1))
>>> print(m)
PowerLaw

Parameters: 

	   name     value     error         unit      min max frozen
	--------- --------- --------- --------------- --- --- ------
	    index 2.300e+00 1.000e-01                 nan nan  False
	amplitude 1.000e-12 0.000e+00 1 / (cm2 s TeV) nan nan  False
	reference 1.000e+00 0.000e+00             TeV nan nan   True

Covariance: 

	name/name index amplitude
	--------- ----- ---------
	    index  0.01       0.0
	amplitude   0.0       0.0
```

As far as I can tell, there's no API to interact with parameter errors in a more natural way like e.g.
```
m.parameters['index'].error = 0.1
```
(this creates a new attribute error on the Parameter object, but it isn't used, so kind of a "silent fail", which Sherpa avoids via 'NoNewParametersAfterInit' mixin).

I think this is non ideal, we should either change init or add a second create method with a more powerful / direct way to init, including parameter errors. It's not a very common use case, but also not very rare, e.g. we will probably use parameter errors to pass on to the optimiser like we do for iminuit to control the fit a bit, and at the moment in #1387 I'm working on the code that creates models from catalogs and there we have parameter errors to fill everywhere.

@joleroi @woodmd @registerrier  or anyone else interested - any thoughts on what API we should expose for this?

**Comment by joleroi** [comment]
I wanted to start exactly the same issue yesterday. The model initialization with ``Quantities`` is very bad. For example if you want to do any kind of [serialization](https://github.com/gammapy/gammapy/pull/1397) you cannot transform let's say XML to a ``ParameterList`` and instantiate the model with it. You have to transform the XML to ``Quantities`` that then on init are transformed back to a **incomplete** ``ParameterList`` so you have to set some info manually later by hand (errors, frozen params, mins, maxes). 

IMO the Model ``init`` should only accept ``ParameterList``

```
class FunnyModel(ModelBase):
    def __init__(self, parameters):
        self.parameters = parameters
```

and maybe have a utility

```
@classmethod
def from_quantities(self, **kwargs)
    ...
```
which could/should even live on ``ParameterList``. I don't know which moron came up with the old API - oh, right that was me :see_no_evil: .

This change will break all callers, but it's definitely worth it.

**Comment by cdeil** [comment]
@joleroi - I think you are already proposing the best solution, but let's discuss a bit tomorrow to be sure before making the change.

If you are blocked by this today, you can always add a from_parameters class method (if it doesn't exist already) to allow your coding, and then next week we just have to exchange function names.

For gammapy.catalog, I will finish up the PR today mostly as-is, and then this will need another adapt next week (but we have lots of tests there, should be pretty mechanical and quick changes).

**Comment by cdeil** [comment]
Just to note: we could also allow multiple types of inputs in init, and use a little if / else and type checking to dispatch to create from quantity etc. Many users find that convenient, and e.g. SkyCoord does this. It's a matter of preference how much to do in init, and we need to discuss a bit what the best solution is, because every Gammapy user will interact with that API a lot.

**Comment by cdeil** [comment]
After discussing with @adonath  just now, I'm moving this issue to v0.14 and assigning myself.

Concerning models, I think we should and plan to work on next week:

- Introduce a `Parameter.create` and maybe `Parameters.create` method that allows init from multiple objects (string, Quantity, existing Parameter object)
- Introduce Parameter descriptor and move the parameters from `__init__` to class level, so that the `__init__` for individual models can be deleted (very similar to how Astropy works, but with a simple implementation), calling `Parameter.create` so that one can pass str, Quantity or Parameter objects to model init.
- For parametere error or covariance init, I'm not sure yet how to do it, if nothing better comes up would stay as-is for now.

Then together with #2353 we'll have a big improvement and the vast majority of API breakage that we can ship in v0.14 in one go.

The next step would be to re-consider whether we can / should use `astropy.modeling`, there a detailed look at parameter linking is needed, I think that's the only thing why it might not work for us. Another topic will be to clean up the design and interfaces with the optimisation backends, but that's a different discussion.

**Comment by adonath** [comment]
By now a `Parameter` object can be passed on init of a model to carry the additional information such as boundaries and error information. There is now a setter for `Parameter.error` as well. I'll close the issue, there is nothing really left to be done.
