### ISSUE TITLE
Implement sensitivity function in Cython

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#14]
The looping over array entries and the iterative optimisation for each entry in [gammapy.stats.sensitivity_on_off](https://gammapy.readthedocs.org/en/latest/api/gammapy.stats.sensitivity_on_off.html) should be implemented in Cython to get good speed.

Before doing that unit tests and a benchmark should be added.

**Comment by adonath** [comment]
From my experience with TS maps, I think it's a good choice to use [brentq](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.optimize.brentq.html) in combination with multiprocessing. Sensitivity computation for TS maps is missing as well, I'll open a separate issue for that.

**Comment by adonath** [comment]
The `sensitivity_on_off` method does not exist anymore, I think it's functionality was mostly replaced by the `SensitivityEstimator` class. Closing this issue.

**Comment by cdeil** [comment]
@adonath - The issue / task really is still the there, only `sensitivity_on_off` was renamed `excess_matching_significance` in the meantime.

Currently we use `numpy.vectorize` at
https://github.com/gammapy/gammapy/blob/55ea4c816eb96b483637e4bfaf4be6f44b886362/gammapy/stats/poisson.py#L600-L603
and execute all the code for this computation using Python scalar numbers.
I.e. there's a ton of Python overhead - moving to Cython should speed up by ~ 100x
It's the same thing as you have for the TS map computation - there you wrote it in Cython.

It's not a trivial task because currently the implementation is based on `scipy.optimize.fsolve` - I think that is callable from Cython, but only from the latest Scipy version, i.e. not available for us yet.

@adonath - Up to you if you want to re-open or keep this issue closed. It's certainly not urgent - but some day (can be next year) - this should be implemented in a fast way, and probably code duplication with the TS map code removed (by moving the stats part of that code to `gammapy.stats` and sharing as much as possible for these 1-dim amplitude fit tasks.

**Comment by adonath** [comment]
Thanks @cdeil, you are right, I didn't notice the re-name of the function. 

I just checked what the `SensitivityEstimator` does and I doubt a highly optimised version of this code is needed. Computing the minimal excess needed for a given significance for O(~30) energy bins should always be less than one second. The TS map computation does this for O(~1e4-1e6) pixels, which is a completely different magnitude. In the case of the `SensitivityEstimator` even a "brute-force" grid minimisation (30 energy bins and ~100 bins in flux / excess) with Numpy should be efficient and precise enough.

For me it's rather the question, whether the code should be shared e.g. with the `FluxPointsEstimator` or be re-written based on SED likelihood profiles, such that we can compute sensitivity curves for 1D and 3D datasets as well. I can make a reminder issue for this.

**Comment by cdeil** [comment]
Yes, a faster version would only be needed for sensitivity maps with ~ 1e6 pixels, not sensitivity spectra with @ 10 pixels. I'm not sure how to best avoid code (and test effort) duplication among the various use cases for 1D optimisation within Gammapy. Not high priority, thus the label here was "wishlist".
