### ISSUE TITLE
Add back spatial model bounding boxes and catalog evaluate tests

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1400]
I will send a PR shortly to remove the old spatial models as well as the old `gammapy/image/catalog.py`. This is superseded by gammapy.maps, the new model classes and the SkyModelEvaluator.

This is a reminder issue to add back two things:

Spatial model bounding boxes:
https://github.com/gammapy/gammapy/blob/ab6b17aa005bba21c13e433649757ab144ee375f/gammapy/image/catalog.py#L122

This might be very tricky because we now have spatial models on the sphere, and there are no simple bounding boxes. @woodmd or @registerrier  - do you have any thought on this? I guess we need to introduce pixel arrays for each source, that are the subset of the map pixels on which the model needs to be evaluated?

And we should also add back the tests from @adonath for the HESS, gamma-cat and Fermi-LAT model evaluator:
https://github.com/gammapy/gammapy/blob/ab6b17aa005bba21c13e433649757ab144ee375f/gammapy/image/tests/test_catalog.py
Probably some bugs were introduced in the rewrite to new spatial models and the filling of those in gammapy.catalog, or the evaluate of some of our spatial models doesn't work properly yet.

**Comment by adonath** [comment]
This is mostly addressed by #2071.
