### ISSUE TITLE
Add Gaussian spectral model

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1411]
One of the spectral models we are still missing in [gammapy.spectrum.models](http://docs.gammapy.org/dev/spectrum/index.html#module-gammapy.spectrum.models) is the Gaussian model:

* https://fermi.gsfc.nasa.gov/ssc/data/analysis/scitools/source_models.html#Gaussian
* http://cta.irap.omp.eu/ctools/users/user_manual/getting_started/models.html#gaussian

It is nice to have to test energy dispersion effects, and is also used for science e.g. to analyse spectral lines.

Implementing the class and tests for this spectral model following the other spectral models should be relatively straight forward, so I'm labeling this issue "package-novice".

The one complication is that for this spectral model the `integral` method should be implemented analytically by calling [scipy.special.erf](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.special.erf.html) and a test added to show that it integrates to the `Normalization` model parameter (which is in `cm-2 s-1`).

**Comment by joleroi** [comment]
Unassigning myself to leave this to a ``package-novice``

**Comment by cdeil** [comment]
See PR #2244 by @JouvinLea . I'm closing this issue now, then we'll have discussion in one place.
