### ISSUE TITLE
SpectrumFit run and write

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1418]
While doing the edit for #1413 I noticed that in `SpectrumFit.run` we currently do `if outdir: self._write` at the end:

https://github.com/gammapy/gammapy/blob/346fc531d5c4093a527324134cb15be21fa0d817/gammapy/spectrum/fit.py#L529-L543

IMO it would be better to remove that from run and let users that want to write call `write` (because more modular and explicit), i.e. make that public and mention write / read back in a high-level docs example.

@joleroi - Do you agree?

**Comment by joleroi** [comment]
Agreed :+1:

**Comment by joleroi** [comment]
Actually when I think about it now I disagree, if one does not want the results to be written to disk automatically they can just call ``fit`` and ``est_errors`` (and then maybe ``write``). That's 3 lines. The ``run`` method is meant as convenience so where's the point if one has to run some of the analysis steps manually afterwards?

**Comment by cdeil** [comment]
But there's also the aspect of uniformity within Gammapy. It's confusing to users if e.g. SpectrumFit does write stuff, but MapFit doesn't. But let's discuss this without haste some day and try to make a good decision. Moving to v0.9.

**Comment by cdeil** [comment]
Done by @adonath in #1785 .
