### ISSUE TITLE
Auto-format Gammapy code?

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1423]
There's a new Python auto code formatter called [black](https://github.com/ambv/black). It can paint your code any color you want, as long as it's black. :-)

It's very easy to use, just give a file or folder and it will re-format all Python code in-place.
```
pip install black
black gammapy/maps
git diff
```

The idea of `black` is that they give no options to customise it. There's others like [yapf](https://github.com/google/yapf) that allow more control.

I think we should adopt an auto code formatter for Gammapy. It means we don't ever have to talk about formatting in pull requests or teach others, we just accept what we get and then auto-format in a follow-up commit when we merge, either in the PR branch or on master.

There would be a one-time rather large diff on our code, but not too bad, and then it would be stable and consistent from now on.

@registerrier @joleroi @adonath or anyone - thoughts?

**Comment by adonath** [comment]
In general I support this idea. I think it is very helpful for developers, when the coding style is consistent. What I do not like is that with the auto-format after every commit, we artificially double the numbers of commits, which blows up our history. Can this process be automatized or shall we ask contributors to run the formatting tool themselves? How do other projects handle this?

I quickly tried `black` and it seems to give nice results and runs very fast.

**Comment by cdeil** [comment]
Devs that know are experienced would just configure their editor to auto-format on save. Black is very new, but e.g. PyCharm and VSCode already support it and others are adding it, and there's also the CLI one can run. This would be described in the dev docs.

But if someone doesn't do this, as a reviewer I wouldn't argue but just do a follow-up commit, either directly when merging, or any time later. E.g. auto-format all of the code (if needed) could be one of the pre-release steps.

There's also git pre-commit hooks, but I would not use those. Most people already struggle with git.

Also: now there's something to run this on docs examples as well:
https://github.com/asottile/blacken-docs
Probably soon there will be something to auto-format notebook code input as well.

**Comment by cdeil** [comment]
I'll paint Gammapy black now.

**Comment by cdeil** [comment]
Done in #1764 and #1756 and https://github.com/gammapy/gammapy-extra/pull/118
