### ISSUE TITLE
gamma_rate wrongly computed in data.ObservationStats

### ISSUE THREAD

**Issue by jlenain** [gammapy/gammapy#1428]
Hi,

We (@santiagopita and I) just noticed that `gamma_rate` is wrongly computed in `data.ObservationStats`. For instance, the final result in https://github.com/gammapy/gammapy-extra/blob/master/notebooks/cta_simulation.ipynb reports (entry 13) a `gamma_rate` of 2.51/min, while it should be `excess/livetime`~30/min.

I am not sure where the problem exactly lies, but to start with, I noticed that in `data.obs_stats.ObservationStats.__init__`, the statement:

`self.gamma_rate = gamma_rate or n_on / livetime`

should be

`self.gamma_rate = gamma_rate or (n_on - self.alpha_obs * n_off) / livetime`

however that does not solve the issue reported here.

Thanks a lot.
Cheers

**Comment by joleroi** [comment]
Hi @jlenain 

thanks for reporting this and sorry for the late reply. With the modification in #1434 I get

```
*** Observation summary report ***
Observation Id: 0
Livetime: 5.000 h
On events: 9617
Off events: 10334
Alpha: 0.200
Bkg events in On region: 2066.80
Excess: 7550.20
Excess / Background: 3.65
Gamma rate: 1510.04 1 / h
Bkg rate: 0.69 1 / min
Sigma: 102.95
energy range: 0.05 TeV - 5.01 TeV
```

Please confirm that this is what you expect

**Comment by jlenain** [comment]
Hi @joleroi ,

Thanks a lot for digging into it. This is exactly what is expected. I'll have a look at #1434 asap.
