### ISSUE TITLE
Add theta2 plots in gammapy?

### ISSUE THREAD

**Issue by cosimoNigro** [gammapy/gammapy#1450]
Hi,

In MAGIC to have a quick look of the excesses in an observation and to assess their significance we use theta2 plots.
These are basically histograms of the ON and OFF counts in theta2 (angular distance from the centre of the on/off regions) 
![theta2flare](https://user-images.githubusercontent.com/26409711/42173223-a22486d6-7e1e-11e8-92f6-13e438c0d0c1.png)
We count (integrate) the ON and OFF counts within a certain theta2 cut (i.e. the on region size) to get the excess and then compute their significance.
I have to produce theta2 plots for a `MARS` / `gammapy` comparison analysis I am doing, if you think they could be useful for `gammapy` I am willing to add them to `gammapy`.
For point like sources it is a straightforward way of estimating the significance without using a skymap, or it can also be the first step to see if a source has an extension.
It can also reveal features in the background (like non-homogenities in the off regions).

Let me know what do you think.

Thank you

**Comment by cdeil** [comment]
Short answer: I'm not sure if / what kind of code we should add.

##### What we have already

- One method we already have is [EventList.plot_offset2_distribution](http://docs.gammapy.org/dev/api/gammapy.data.EventList.html#gammapy.data.EventList.plot_offset2_distribution) that makes the theta2 histogram from events. It doesn't do theta2 background estimation or handle multiple event lists, it's just a few lines.
- In [gammapy.image](http://docs.gammapy.org/dev/image/index.html#reference-api) there are a few functions and classes for region-based and profile measurements. Those are based on pixels / images, not events, and the code there isn't of good quality yet, it needs to be improved (and moved to use `gammapy.maps`).
- There is also [ObservationStats](http://docs.gammapy.org/dev/api/gammapy.data.ObservationStats.html), [ObservationSummary](http://docs.gammapy.org/dev/api/gammapy.data.ObservationSummary.html) and [ObservationTableSummary](http://docs.gammapy.org/dev/api/gammapy.data.ObservationTableSummary.html) to get stats / significance for each observation.

##### What to add?

@cosimoNigro - What exactly would you propose to add? I.e. which functions / methods / classes? Are they separate from the existing spectral or other analysis code, or integrated somehow? Is the background estimate pixel-based or event-based?

Clearly we should provide something that makes it relatively straightforward to make this plot, it's commonly used, we have it in HESS as well.

But IMO we should avoid adding a lot of code for this, like we did with the `ObservationStats`, `ObservationSummary`, `ObservationTableSummary` and the too many pixel-based `*_profile` functions we have in `gammapy.image`.

Maybe start with a Jupyter notebook in `gammapy_extra/notebooks` showing an example how to compute the theta2 histograms (especially the background estimation) and how to make the plot, and then we discuss if / what parts to move into the Gammapy package?

**Comment by cdeil** [comment]
Discussed with @cosimoNigro in the Gammapy call just now. Decided to close this feature request for now. We could still add something in the future, if someone is willing to send a pull request and it's not too much or to complex code. Plotting should always be separate from documentation.

@cosimoNigro - If you have working code for this, you could add add it as a docs example either in Gammapy, or link to it from Gammapy for now. That way, we show how to do it, but don't offer code / promise to maintain to users.

**Comment by Bultako** [comment]
FYI
In case it helps, here's a notebook on how to do theta2 plots with `ctapipe`

https://github.com/cta-observatory/ctapipe/blob/master/examples/notebooks/Theta%20square%20plot.ipynb
