### ISSUE TITLE
different `method` and `err_method`

### ISSUE THREAD

**Issue by dcfidalgo** [gammapy/gammapy#1481]
In `gammapy.spectrum.SpectrumFit` it gives an error when choosing different methods for `method` and `err_method`. I think we simply could get rid of the `err_method` and only use `method` ...
Would you ever need a different backend for the parameter and error estimation?
@cdeil @joleroi Objections? 

As an reminder for me, i want to update the tests for SpectrumFit.

**Comment by cdeil** [comment]
I'm not sure, let's discuss tomorrow.

E.g. with Minuit there's the HESSE and MINOS to get errors. Sherpa also has the equivalent of a method that estimates errors based on second derivatives (like HESSE) or likelihood profile analysis (like MINOS). In principle I guess other might be added. So it might make sense to keep the `err_method` option, even if not used at the moment.

**Comment by mackaiver** [comment]
Or we add it back once we actually use it. --> less clutter.

**Comment by dcfidalgo** [comment]
>  E.g. with Minuit there's the HESSE and MINOS to get errors. Sherpa also has the equivalent of a method that estimates errors based on second derivatives (like HESSE) or likelihood profile analysis (like MINOS). In principle I guess other might be added. So it might make sense to keep the err_method option, even if not used at the moment.

Then i think we should rewrite a bit the code, since now `err_method` is used to rather define the backend for the error estimation (iminuit, sherpa) than the actual method (HESSE, MINOS, ...).

**Comment by adonath** [comment]
For the `TSImageEstimator` there is an [error_method](https://github.com/gammapy/gammapy/blob/master/gammapy/detect/test_statistics.py#L94) argument, where I offered `covar` and `conf` as options, named after the corresponding sherpa methods (even though it does not use sherpa under the hood...). It be nice to make it consistent.

**Comment by cdeil** [comment]
This was improved a bit in #1512 . I think a proper resolution will need quite a bit of work, to create a uniform interface to optimisers and error estimators in gammapy.utils.fitting. Moving this to the v0.9 milestone.

**Comment by cdeil** [comment]
I'm closing this now. For now, the err_method is removed.

In the coming weeks / months, we should develop our optimiser and error estimator interface, and then use that and expose options in a uniform way from the higher-level "Fit" classes.

This can go step by step, refactoring as we learn what's good and bad, or if someone wants to write up a design on a page or two, please make a PR for a pig.
