### ISSUE TITLE
Plot in SpectrumFit changes model

### ISSUE THREAD

**Issue by mackaiver** [gammapy/gammapy#1483]
It's not an idempotent operation. It changes the parameters of the fitted model. This is dangerous since the plot output changes as well as the model parameters.

I found no wasy fix. I guess we could remove the method.

**Comment by cdeil** [comment]
@mackaiver - Do you have an example that shows that bug?

@joleroi - I think we previously had some issues where computing npred changed one of the model objects. Maybe @mackaiver is just accessing the wrong model object?
