### ISSUE TITLE
Local test failure on python 3.6

### ISSUE THREAD

**Issue by joleroi** [gammapy/gammapy#1487]
Since a few days I have several local test failures, when running on python 3.6. For example 

```
python setup.py test -t gammapy/catalog/tests/test_hess.py -a '-k test_source_table'
```
On Python 3.6.2 the test [fails](https://gist.github.com/joleroi/1f91cd663bdf67e7b4b5926e6844dc3f)
On Python 3.5.3 if passes

Can anyone reproduce this and/or has any idea how to tackle this?

**Comment by adonath** [comment]
The test passes just fine for me using Python 3.6 and pytest 3.5 / 3.6.2. Have you tried updating pytest?

**Comment by joleroi** [comment]
I was on the wrong conda channel ... so I indeed had an old version of pytest. Thanks @adonath
