### ISSUE TITLE
Implement fast, accurate integrator for power-law type functions

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#15]
I've had problems getting accurate results when numerically integrating power-law type functions (spectral models like curved or exponential cutoff power law) using [scipy.quad](http://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.quad.html) or other integrators.

I think using a `log(x)` spacing instead of `x` and using a simple integration method that takes vectors of `x` and `y` as input like [cumtrapz](http://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.cumtrapz.html) or [scipy.simps](http://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.simps.html)
should give good results.

Also check all GammaLib results for `flux` and `eflux` and compare speed / accuracy. Usage example:

```
from gammalib import GModelSpectralPlaw, GModelSpectralPlaw2, GModelSpectralExpPlaw, GModelSpectralLogParabola
from gammalib import GEnergy, GTime
model = GModelSpectralPlaw(1, 2, GEnergy(1, 'TeV'))
print model.eval(gammalib.GEnergy(10, 'TeV'), gammalib.GTime(1, 's'))
print model.flux(GEnergy(1, 'TeV'), GEnergy(10, 'TeV'))
print model.eflux(GEnergy(1, 'TeV'), GEnergy(10, 'TeV'))
```

Links:
- https://cta-redmine.irap.omp.eu/projects/gammalib/wiki/How_to_integrate_a_function

**Comment by cdeil** [comment]
Update: we now have [gammapy.spectrum.integrate_spectrum](https://gammapy.readthedocs.io/en/latest/api/gammapy.spectrum.integrate_spectrum.html).

- [ ] move to a method on the [gammapy.spectrum.models.SpectralModel](https://gammapy.readthedocs.io/en/latest/api/gammapy.spectrum.models.SpectralModel.html) class.
- [ ] find good settings to get results with reasonable accuracy and speed for most models.

**Comment by joleroi** [comment]
Note: http://docs.gammapy.org/en/latest/api/gammapy.spectrum.models.SpectralModel.html#gammapy.spectrum.models.SpectralModel.integral

**Comment by cdeil** [comment]
@joleroi - I know. I'll close these spectrum integral issues in the next days. I just want to do some more testing and clean-up of old code, and keep them as a reminder.

**Comment by adonath** [comment]
Is there anything left to be done for this issue? Compare against gammalib?

**Comment by cdeil** [comment]
This is a key piece of spectral analysis, and probably there will still be a lot of work on getting the precision / speed trade off right in Gammapy, and https://github.com/joleroi/wstat/issues/12 might be related, i.e. things can improve a lot by changing to integrating over bins use power-law approximation over bins by default instead of a simple diff flux times bin width method (cc @joleroi).

But the main thing suggested above was implemented by you a few months ago, and there is no concrete action item here, so I'm closing this issue. We can re-open or file new issues in the future when we encounter precision or speed problems from Gammapy spectral analyses.
