### ISSUE TITLE
test_spectrum_analysis_iact fail

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1510]
This test:
https://github.com/gammapy/gammapy/blob/8010f910e458d464002aae8646c46ec26069f0f5/gammapy/scripts/tests/test_spectrum_pipe.py#L32

is failing in this build because the `dnde` changed a little bit:
https://travis-ci.org/gammapy/gammapy/jobs/404319697#L3770

Locally I don't see the fail, I get the same expected values that are currently in the test file.
This is not failing in all builds, I don't know whats going on.

@joleroi - Any idea?

**Comment by joleroi** [comment]
I see the failure locally, my guess is that the tests for spectrum pipe were not updated during the work on the flux points functionality during last weeks coding sprint. In [this](https://github.com/gammapy/gammapy/commit/31ea0ff23b8d7b0f82a29442bc023b40251cc0d7) commit ``dnde`` was changed for quite some other tests, so my suggestion would be to adapt the test value here as well

**Comment by cdeil** [comment]
But for me, locally with `master`, I get exactly the values as written in the test file.

Adding this line in the test:
```
print(dnde); flux_points.table.pprint(max_width=-1); 1/0
```
I get these numbers: https://gist.github.com/cdeil/b1ccf760fcfc03711c6d0d2d2338fd88

@joleroi - Could you please try that also and past the result?
Maybe it's a float rounding issue where the energy bins are slightly different for you and me?

**Comment by cdeil** [comment]
My guess is that this issue is due to floating point noise, possibly leading to a difference in fine bin energy grouping by one bin, or in the flux point computation.

The flux points agree at the 0.5% level, which I consider acceptable, so I've reduced the tolerance to 1% for these dnde asserts in 06ffe6af049d1a41ee7c18bc6d52247806e4376b .

Closing this issue now.

**Comment by mealworm** [comment]
Oh, I also got rid of obs.copy().
