### ISSUE TITLE
Add code to make background models

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1516]
I deleted the old code we had in Gammapy to make background models (see #1513, #1515).
This was added when we and Astropy were very young, and before `gammapy.irf` and `gammapy.maps` existed.

In principle we want this code back, rewritten in a clean and simple way, using e.g. the `gammapy.irf.Background3D` class instead of the old `gammapy.background.FOVCube` class.

Probably this will take some time and discussion. IMO a good step that we should take now is to update https://github.com/gammapy/gammapy-extra/blob/master/notebooks/background_model.ipynb with a simple method (e.g. two or three groups in zenith angle and Gaussian smoothing) to make background models using the off runs from https://github.com/cdeil/HESS-DL3-DR1-preview as an example. This should be doable with limited effort, and it'll drive the FOV to sky coordinate transform and work on the background IRF classes that we started last week.

@JouvinLea - You're back to work on the CTA camera, right?
@lmohrmann - Do you have time / interest?

Alternatively, this is also something that I would be interested to hack on a bit.

**Comment by cdeil** [comment]
I've written a simple example to estimate a background model from the HESS data in
https://github.com/gammapy/gammapy-extra/commit/9f9f4e3ff92075996afba69a9bd3a2fe63f7d6d0

You can see it here: https://github.com/gammapy/gammapy-extra/blob/master/notebooks/background_model.ipynb

The minimal next step is to update the code to make the debug plots and remove the rest of the notebook about index files.

Better would be to extend the tutorial to process two zenith angle bins and create a new index file at the end of the notebook, and then (probably in a separate notebook) do a first 3D analysis for the four Crab runs from the test data release. Now that it's working and using the new IRF class, we could also move the background estimator class back into Gammapy; IMO it doesn't matter that the algorithm is primitive and incomplete, we can make it better step by step in the coming months.

The HESS release will be announced this Friday, and I think it's important to (a) know that 3D analysis works with Gammapy and (b) we have a tutorial for this.

@JouvinLea @lmohrmann - do you have time to work on this this week? If no, please still leave a comment what you think of this, and I'll try to finish up this tutorial and add a second one specifically for the HESS release (probably 3D analysis for the 4 Crab runs with background model estimated this way) tomorrow evening.

**Comment by lmohrmann** [comment]
@cdeil I'll try to start applying the 3D analysis to the HESS data this week, but it's likely that I won't be able to finish this. If I find any issues, I'll let you know. I'd work with our background model directly, so I cannot really contribute to (b), at least not on a short timescale.

**Comment by cdeil** [comment]
OK, so I'll make a draft tutorial for HESS DL3 DR1 analysis tonight.

@lmohrmann - If you have a little time tomorrow let us know if you find any issues or missing features for the HESS analysis, that would be very useful.

We have a weekly Gammapy call always Friday morning.
https://github.com/gammapy/gammapy-meetings/tree/master/2018-09-14

**Comment by cdeil** [comment]
There's now a first version of the notebook that makes the background model:
https://github.com/gammapy/gammapy/blob/master/tutorials/background_model.ipynb

and a placehoder for the HESS tutorial notebook:
https://github.com/gammapy/gammapy/blob/master/tutorials/hess.ipynb

I haven't tried the background model yet. Will try to continue and finish this up tonight.

**Comment by cdeil** [comment]
See http://docs.gammapy.org/dev/notebooks/background_model.html

@lmohrmann - Do you know why the `DataStore.from_dir` gives this warning at the end? Do you see that as well? Can this be fixed in your PR for that method?
```
WARNING: hdu= was not specified but multiple tables are present, reading in first available table (hdu=1) [astropy.io.fits.connect]
```

**Comment by lmohrmann** [comment]
Nope, haven't seen it, and no time to look into this.

**Comment by cdeil** [comment]
A first version of the HESS Crab analysis is in the tutorial notebook. In the 3D analysis, the background model isn't good and probably the morphology / spectral model too. For the 1D analysis, it might be OK, but I first had an 0.3 deg on region size, and there the flux was much too high for unknown reasons.

I don't plan to work on this further in the near future, anyone is welcome to send a PR or make an issue to suggest improvements to the tutorials.
