### ISSUE TITLE
What's the correct value for errordef in iminuit?

### ISSUE THREAD

**Issue by joleroi** [gammapy/gammapy#1532]
see https://github.com/gammapy/gammapy/blob/master/gammapy/utils/fitting/iminuit.py#L88

Reminder:
out fit statistic is -2 log (likelihood)
https://github.com/gammapy/gammapy/blob/master/gammapy/stats/fit_statistics.py#L58

**Comment by AtreyeeS** [comment]
I can try this check... maybe later today or early tomorrow

**Comment by cdeil** [comment]
@AtreyeeS - Thanks!
I assigned the issue to you.

Maybe you could also send a PR that removes the TODO comment @joleroi linked to above,
and adds a few asserts on the parameter errors in this test? (low precision, with `rtol=1e-2` like we have for the parameter values)? Then we'll have a regression test.

https://github.com/gammapy/gammapy/blob/c886a411f24a011459ca4a3a8d701180ea8e1f19/gammapy/cube/tests/test_fit.py#L108

**Comment by cdeil** [comment]
@AtreyeeS - I now start editing the `make_minuit_par_kwargs` and also moving this `kwargs['errordef'] = 1` line. Hope I'm not interfering with edits you've made in the past days...

**Comment by cdeil** [comment]
This issue should be resolved via #1563 and #1567 .

@AtreyeeS - Could you please try running your script for a pull distribution again with `master` for a simple test case? Do you now find a unit normal distribution for the pull?

If no, there's an important bug please let me know and I'll have a look.

**Comment by AtreyeeS** [comment]
The width of the pull distribution is `1` now (major improvement), but there is still a bias in the fitting. The gaussians are not centred on `0`.

**Comment by cdeil** [comment]
@AtreyeeS - OK, but then that could be pixelisation or other effects.
Please open a new issue and share your script or notebook if you want me to have a look.

**Comment by AtreyeeS** [comment]
Yes, I will just clean up my notebook and file an issue.
But this issue looks solved.
