### ISSUE TITLE
PSF issues when fitting Gaussians ?

### ISSUE THREAD

**Issue by facero** [gammapy/gammapy#1533]
When trying to fit a Gaussian in CTA DC1, I get some residuals even when fixing the truth sigma read from the model.

When the sigma is fixed to truth model (0.06°) there are some positive residual in the core
![gaussian-fixed-truth](https://user-images.githubusercontent.com/8652898/42827309-5b17aa9c-89e6-11e8-99be-c39e5b568777.png)

When the sigma is let free the best fit is 0.048° and there are some negative residuals in the core. Like if the model was too peaked in the center.
![gaussian-bestfit](https://user-images.githubusercontent.com/8652898/42827494-d0d27dde-89e6-11e8-83aa-3d83d3c79abe.png)

So a Gaussian Model can not explain both the wing and the core of this Gaussian source. 
A possible explanation could be that something is wrong with the PSF or maybe the energy/pixel binning is too coarse (but I'm already using 10bins/decade and 0.02°/pixel).
I will try to find a point source to model and see if the issue is still there.
@registerrier @cdeil  any idea ?
The full example can be found [here](https://github.com/gammasky/cta-analyses/blob/master/dc-1-checks/rx_j1713/RXJ_gammapy_data_analysis3D.ipynb)

**Comment by facero** [comment]
So I tried with smaller energy bins (20bins/decade) to see if the sampling of the IRF was enough and also smaller pixels and the result is the same. Below is the best-fit Gaussian model
![gaussian-bestfit-smallbins](https://user-images.githubusercontent.com/8652898/42830107-f2bac0f6-89ea-11e8-944a-f4bb8337e607.png)

**Comment by cdeil** [comment]
@facero - Thanks for this!

This can come from different effects:
- PSF interpolation in FOV offset done differently in the ctools simulation and Gammapy evaluation?
- Mean PSF computation and PSF kernel computation in Gammapy OK?
- Still need to apply npred-weighting of PSF with an assumed spectrum for better precision?
- Still need to apply EDISP?
- Bug in Gammapy?

They need to be checked one by one, starting with an isolated bright point source, and looking at `psf_theta` distributions of the counts and prediction from the mean PSF in Gammapy first, without extra complications from Gaussian model evaluation and PSF folding.

I would suggest to discuss this on Friday (@facero - feel free to add links to issues [here](https://github.com/gammapy/gammapy-meetings/tree/master/2018-07-20)) any time) and then to tackle this next week.

Note that none of the DC1 check analyses have small source extension as a measurement we need to deliver, so even resolving this only later is an option, first we have to get good spectra from the new code.

**Comment by facero** [comment]
So I tried to simulate sources using the [simulate_3D notebook](https://github.com/gammapy/gammapy-extra/blob/master/notebooks/simulate_3d.ipynb). The **pixel size for this study is 0.005°** and E=0.1-10 TeV with 20 bins and the source is the center of the FoV.

When simulating a point source and comparing it to the PSF, the residuals come out almost perfect (residuals are ~1e-8):

![ptsource-psf](https://user-images.githubusercontent.com/8652898/43000427-a77e4d04-8c21-11e8-82b6-8e19f30e72c5.png)

The spectral results are ok for the Point source (except this normalization issue for SkyPtSource model).

When fitting a Gaussian of 0.1°, the residuals are not looking good  
![fitting-gaussian-0 1deg](https://user-images.githubusercontent.com/8652898/43000464-daf6eefc-8c21-11e8-9755-21117699ee8b.png)

The problem is not visible when sigma > 0.2° and becomes worth for sigma<0.1° as shown in the plot below where I varied the sigma in the simulation:
![fitting-gaussian-gammapy](https://user-images.githubusercontent.com/8652898/43000571-4501620a-8c22-11e8-8abc-ba8e0d30fc22.png)

So maybe it's related to the convolution of the Gaussian model with the PSF ?
At large sigma the PSF has a small impact and therefore we don't see it but when sigma ~ PSF, the effect of the PSF convolution is dominating ?
But in this simulation we create the source and then fit it with the same code so I'm not sure why we are seeing this effect.
It is not a minuit issue as when fixing the sigma to the true value we still see bad residuals :
![fixed-gaussian-0 1deg](https://user-images.githubusercontent.com/8652898/43000851-5d9debc0-8c23-11e8-8ed2-b0dd46d2548d.png)

So it is:
-Not a DC1 related issue
-Not a PSF reading/offset/evaluation stuff (as PointSrc residual are ok)
-Probably not a Edisp effect as this would affect both PtSrc and Gaussian

Any suggestions ?
I'm narrowing down the problem and will keep you posted.

**Comment by cdeil** [comment]
Is it still possible to run without a PSF by passing no PSF kernel to the evaluator of fitter?
Does that give correct results for Gaussians?

Or prepare a kernel which has a single pixel with 1 at the center, i.e. should be a no-op in the PSF apply?

What is your PSF containment in the kernel. If it's truncated I guess you would find this residual, no?
Can you make the PSF kernel larger to be full containment (or 99%)?

**Comment by facero** [comment]
So turns out that I used the `simulate_3D notebook` for my analysis without adding the psf_kernel in my fit: 
```
fit = MapFit(
    model=model.copy(),
    counts=counts_map,
    exposure=exposure_map,
    background=bkg
)

fit.fit()
```
when adding the `psf=psf_kernel` we can recover the good sigma values, so nothing is wrong in this auto-consitent test (simulate, fit).

I managed to recover the good sigma value of the Gaussian for values down to 0.01° (almost the pixel size). I also tested different offset angle in the source simulation and the fitted results came out correct.

Unlike what I stated in a previous post, it seems that it could be something related to DC1 (reading the irf and interpolating IRFs ?)  Sorry for the confusion

**Comment by cdeil** [comment]
The next thing I would investigate here is the FOV offset interpolation of PSF parameters. 

I think what's happening is that we load the CTA DC1 PSF via [EnergyDependentMultiGaussPSF](http://docs.gammapy.org/dev/api/gammapy.irf.EnergyDependentMultiGaussPSF.html) (it's really a single Gaussian), and then via [ObservationList.make_mean_psf](http://docs.gammapy.org/dev/_modules/gammapy/data/data_store.html#ObservationList.make_mean_psf) and [DataStoreObservation.make_psf](http://docs.gammapy.org/dev/api/gammapy.data.DataStoreObservation.html#gammapy.data.DataStoreObservation.make_psf) the mean PSF as an [EnergyDependentTablePSF](http://docs.gammapy.org/dev/api/gammapy.irf.EnergyDependentTablePSF.html) at a given sky position is computed. This calls into [EnergyDependentMultiGaussPSF.to_energy_dependent_table_psf](http://docs.gammapy.org/dev/_modules/gammapy/irf/psf_analytical.html#EnergyDependentMultiGaussPSF.to_energy_dependent_table_psf) which calls [EnergyDependentMultiGaussPSF.psf_at_energy_and_theta](http://docs.gammapy.org/dev/_modules/gammapy/irf/psf_analytical.html#EnergyDependentMultiGaussPSF.psf_at_energy_and_theta) which does nearest interpolation on the Gauss parameters and goes via the `HESSMultiGaussPSF` class.

At the very least this need some cleanup / simplification, removing extra IRF classes with HESS in the name.

Most likely this also needs improved tests.

Finally, we have to make a decision on how interpolation (especially in FOV offset) should work for the two analytical PSFs and resolve the TODO here:
https://github.com/gammapy/gammapy/blob/ac1b07e7e397ce9c97cfb2722d856f6fe047d774/gammapy/irf/psf_king.py#L201
https://github.com/gammapy/gammapy/blob/2f9afdf2446cd375e182b88c4344300c4c1983bc/gammapy/irf/psf_analytical.py#L206

We could consider using [PSFMap.containment_radius_map](http://docs.gammapy.org/dev/api/gammapy.cube.PSFMap.html#gammapy.cube.PSFMap.containment_radius_map) to debug this and see how big the jumps are for the CTA DC1 PSF (the offset nodes should be at 0.5, 1.5, 2.5, 3.5, ... deg)

This cleanup and investigation is at least a day of work, if done thoroughly with tests probably rather 2-3 days.

@registerrier - I'd suggest we hold off on this for now, and first see if CTA 1DC results come out OK for the point and small sources, and only if that's not the case, tackle this issue in the second half of next week.

**Comment by cdeil** [comment]
Info from Jürgen via email:

> The ctools currently use a bi-linear interpolation of the Gaussian sigmas and relative amplitudes.

We'll have to discuss what to do in Gammapy ...

**Comment by adonath** [comment]
I implemented the bi-linear interpolation of the multi-gauss PSF in #2022. The changes in the test values of the containment radii  were in order of a few percent.
