### ISSUE TITLE
notebook links in documentation are broken

### ISSUE THREAD

**Issue by joleroi** [gammapy/gammapy#1541]
The ``gp-extra-notebook`` sphinx directive has [recently been modified](https://github.com/gammapy/gammapy/pull/1286). I'm not sure what the intended behaviour is, but the online documentation does not work for me anymore.

For example the link on [this page](http://docs.gammapy.org/dev/api/gammapy.spectrum.SpectrumSimulation.html) links to ``http://docs.gammapy.org/notebooks/spectrum_simulation.html`` which does not exist.

cc @Bultako @cdeil

**Comment by cdeil** [comment]
Current we generate a link to http://docs.gammapy.org/notebooks/spectrum_simulation.html which doesn't exist. The "version" part in the URL is missing, e.g. for the dev version this exists: http://docs.gammapy.org/dev/notebooks/spectrum_simulation.html

Previously I think we didn't have the version coupling, so the problem with linking between Sphinx notebooks and RST docs in different versions was always there. So we could just re-establish the old behaviour and add "dev/" to the URL and have this work fo the dev version of the docs.

I'm not sure how difficult it would be to put a real solution with the version in the URL route also for stable releases? Maybe as simple as accessing the Gammapy version in the implementation of the `gp-extra-notebook` directive?

@Bultako - Thoughts?

Do you have time to try to fix this next week? If no, I can give it a shot.

**Comment by Bultako** [comment]
@cdeil 
@joleroi

I'll rebuild locally and hope to get the same broken links for the notebooks. If this happen I think it could be just a silly problem of definition of relative paths, not related with version coupling (which is a bigger issue...)

**Comment by Bultako** [comment]
Fixed
