### ISSUE TITLE
Update FermiLATBasicImageEstimator to gammapy.maps

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1545]
I plan to update the FermiLATBasicImageEstimator to gammapy.maps in the following way:

- Update [data_fermi_lat.ipynb](http://docs.gammapy.org/dev/notebooks/data_fermi_lat.html) to give very similar output (maybe the images will be slightly different because of energy binning or spectral weighting isn't done the same)
- Update this to give the same result (or again - almost the same):
https://github.com/gammapy/gammapy/blob/f469da82239920ad7c4398b8c08d3bd6209393b7/gammapy/image/tests/test_basic.py#L22
- Remove the FermiLATBasicImageEstimator:
https://github.com/gammapy/gammapy/blob/f469da82239920ad7c4398b8c08d3bd6209393b7/gammapy/image/basic.py#L501

Doing this might require changing the map functions and `MapMaker` first to handle the max offset cut in a different way, either optional, do nothing for Fermi, or replace with a mask (cc @registerrier).
If this causes problems, then I might add a second `MapMakerLAT`.

Currently there is this very weird fail in master for `TestFermiLATBasicImageEstimator.test_run`, but only in the case where you don't have the Fermi-LAT diffuse model:
https://gist.github.com/cdeil/b7c5f488c809cc7391529dd4e88ee029
I'll mark that as xfail in master now, and this issue should just go away in a clean now re-implementation.

**Comment by registerrier** [comment]
Isn't it better avoiding using `MapMaker` for non IACT datasets?

Passing a mask rather than an offset cut to the various functions such as `make_map_exposure` is obviously something we have to do, since offset might not be the unique way to determine the validity region (e.g. non isotropic FoV) and since the selection might be energy dependent. Yet we need to find a way to allow `MapMaker` to know how to deal with this. A possibility could to pass a `Map` in FoV coordinates and retroject it on the correct geometry for each observation. But we need to be have a support for something like `SkyOffsetFrame` in `Map` and `MapCoord`.

**Comment by cdeil** [comment]
> Isn't it better avoiding using MapMaker for non IACT datasets?

I think you're right. @adonath made the same comment.

We can't compute exposure for Fermi-LAT, and background is different. No point in using MapMaker just to make a counts image, that's trivial for Fermi-LAT.

Not sure yet if we want to add a class for Fermi-LAT. Probably not needed, except if we want to pre-script again the diffuse model npred computation, because we think MapEvaluator is too low level to use directly, we could introduce a convenience class for this.

---

Concerning MapMaker for IACT, how about this?

(re-)Introduce a second class that processes one obs, e.g. ObsMapMaker
On init it makes a mask from the pointing position and max FOV cut.
Either that mask is passed down to `make_map_exposure_true_energy` et al, or (my preference) those functions don't need that at all, just process all pixels, and the mask is applied by the ObsMapMaker after the call, ensuring consistent mask application for counts, bkg and exposure.

The current MapMaker would just orchestrate the looping over obs and stacking, for each map doing the cutout and paste back of sub-maps for each obs, like it does now.

The structure of both classes is changed so that it's possible to do only counts or only background or only exposure. Either that, or we get more functions / classes for each.

Do we have an issue for those mapmaker suggestions already? If no, @registerrier - could you please open one stating your preferred changes to MapMaker and concerning max FOV handling?

**Comment by cdeil** [comment]
Another related thing that I removed just now in #1593 is the `FermiLATDataset` and `FermiGalacticCenter` from `gammapy.datasets`.

@adonath @registerrier - let's discuss later this week what to bring back.

Those were two convenience classes that computed counts maps from events, and also that loaded and reprojected the images commonly used, and for the diffuse background models also did evaluate.

I think we want e.g. a helper class or function for the Fermi-LAT diffuse isotropic spectral model read. But the main thing that we should introduce is a "DatasetLAT" that can be used in model fitting, ideally together with a "DatasetCTA" in a joint fit.

Probably the new implementation will be pretty different from the old one, and like or MapMaker and MapEvaluator and MapFit pretty simple. Or maybe we can just use the same, at that level "DatasetLAT" and "DatasetCTA" are the same.

**Comment by cdeil** [comment]
I've updated the first part of https://github.com/gammapy/gammapy-extra/blob/master/notebooks/data_fermi_lat.ipynb

I still need to update the part from "Isotropic diffuse background" and the rest. The idea would be to prepare everything for a 3D analysis using MapFit, and to fit the Galactic center source at the end of the notebook, in addition to computing a flux map.

Indeed, using MapMaker for Fermi-LAT is pointless.

I also don't think any more adding these tests back in Gammapy has much value:
https://github.com/gammapy/gammapy/blob/f469da82239920ad7c4398b8c08d3bd6209393b7/gammapy/image/tests/test_basic.py#L22

Long-term I think we should probably add a "science validation test" that reproduces one or two 3FHL catalog results, like e.g. for the GC source and for an AGN, checking position and spectral parameters from a 3D analysis. But I would prefer to postpone this to post v0.8 and just work on maps and modeling basics and unit tests this week.

@adonath - Thoughts?

**Comment by cdeil** [comment]
> I also don't think any more adding these tests back in Gammapy has much value

Note that these tests were using the few 100 MB diffuse model cube that comes with the Fermi ST. I don't even have that on my machine, and we don't have it on travis-ci. It's not a good test case for an automated test to start with.

**Comment by cdeil** [comment]
Check this out: https://github.com/gammapy/gammapy-extra/blob/master/notebooks/data_fermi_lat.ipynb

Diffuse models and 3D analysis for Fermi-LAT!

@registerrier @adonath - Some things we have to talk about:
- Sane strategy for energy axis handling concerning where to take node_type "edge" or "center"
- Unit handling in gammapy.maps wrt. coords and axes needs to be improved further, I already opened an issue for that.
- PSF convolution image boundary mode

The big next step for v0.9 would be to have a fit class that takes a list of "datasets" or "observations" where this Fermi-LAT would be only one dataset, and you could add an IACT one or whatever you like.

@adonath - OK to close this issue?

**Comment by adonath** [comment]
@cdeil Nice! It would be great to check at least once, whether the predicted number of counts is at least close to what it was before, or close to what is obtained from the Fermi ST. Any idea for that? Maybe add a small test in Gammapy?

**Comment by registerrier** [comment]
Nice indeed. 
We should also add data in `Map.from_geom` to avoid as much as possible calling `WcsNDMap.create` where a single reference to `Map` and `WcsGeom` would be sufficient.

**Comment by cdeil** [comment]
This validation would take me at least a day, I haven't run the Fermi ST since, not sure, maybe two years. The quickest would probably be to analyse the Crab or some other source and compare against 3FHL results. Adding a test to Gammapy is possible, but then the question is whether we access the large prepared maps, or copy cutouts already to gammapy-extra to have a small and quick example that runs in at most a few seconds.

My preferred solution would be of course if you update the Fermi-HGPS paper to use gammapy.maps, and then this will give a thorough validation of Gammapy for Fermi-LAT high-energy analysis via a publication. I know it's effort, and of course it's up to you.

OK to postpone all of this post v0.8 and close this issue now?

**Comment by cdeil** [comment]
> We should also add data in Map.from_geom to avoid as much as possible calling WcsNDMap.create where a single reference to Map and WcsGeom would be sufficient.

Yes, we should make some change or addition. Please open a separate issue with a proposal, or if you're unsure what exactly, this question.

**Comment by registerrier** [comment]
OK for me.

**Comment by cdeil** [comment]
I'm closing this now. It's mostly done and I want to focus on other stuff this week. @adonath - If you think a reminder issue is helpful about validation or other improvements here, please open it.
