### ISSUE TITLE
Cloning / copy pattern for Gammapy maps

### ISSUE THREAD

**Issue by adonath** [gammapy/gammapy#1547]
In the Gammapy code we have many use cases, especially with `Map` objects, where we want to basically clone an object and modify a selection of its attributes. E.g. cloning a `Map` object and then set its data, meta or unit attribute. Currently this is typically done as follows:

```python
# Current pattern
flux = copy.deepcopy(counts)  
flux.data = data
flux.unit = unit
flux.meta = meta
```
This patter is inefficient, because data is copied and thrown away again. It is also error-prone because, people might forget to set attributes and it is also a lot of code lines.  I've discussed with @cdeil in the past that we should introduce a coding pattern that makes this simpler to achieve, ideally with only one line of code. And we suggest to introduce a `.copy()` method, that works as following:

```python
# pattern using a copy function
flux = counts.copy(data=data, meta=meta, unit=unit)

# or more explicit function name
flux = counts.copy_and_setattr(data=data, meta=meta, unit=unit)

# alternative pattern with factory function, which might need an additional import
flux = Map.from_map(counts, data=data, meta=meta, unit=unit)
```
While the structure of the `.copy()` function is clear, I do not like the name, because it does more. It copies the map object and overwrites given attributes. So I suggested the altenative name `.copy_and_setattr()`. Another alternative name could be `.clone()`.

What do you think @cdeil. @registerrier @woodmd?

**Comment by cdeil** [comment]
I like `clone`. A clone is by default an exact copy, but then can have attributes that are different if the caller requests it in the call.

**Comment by registerrier** [comment]
I am +1 for clone.

**Comment by cdeil** [comment]
Decision in Gammapy dev call today: `clone`.
Axel will add this very soon.

**Comment by registerrier** [comment]
Can we close the issue now?
