### ISSUE TITLE
Incorrect results for SkyPointSource

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#1550]
The SkyPointSource spatial model gives a wrong npred.

eg:

`spatial_model = SkyGaussian(
    lon_0='0.2 deg',
    lat_0='0.1 deg',
    sigma='0.01 deg',
)
spectral_model = PowerLaw(
    index=3,
    amplitude='1e-11 cm-2 s-1 TeV-1',
    reference='1 TeV',
)
sky_model = SkyModel(
    spatial_model=spatial_model,
    spectral_model=spectral_model,
)'
'evaluator = MapEvaluator(sky_model, exposure=exposure_map)'
'npred = evaluator.compute_npred()'
'print(npred.sum())`

gives  `3846` predicted events in total.

`spatial_model1 = SkyPointSource(
    lon_0='0.2 deg',
    lat_0='0.1 deg',
)
spectral_model = PowerLaw(
    index=3,
    amplitude='1e-11 cm-2 s-1 TeV-1',
    reference='1 TeV',
)
sky_model1 = SkyModel(
    spatial_model=spatial_model1,
    spectral_model=spectral_model,
)'
`evaluator = MapEvaluator(sky_model1, exposure=exposure_map)`
`npred = evaluator.compute_npred()`
`print(npred.sum())`

gives `0.0004824` predicted events in total

(for the detailed code, see https://gist.github.com/AtreyeeS/d5161ebe30f29c1a19b34757a1916301)

**Comment by adonath** [comment]
I'm pretty sure that this is an issue of flux vs. surface density, so a missing division by the solid angle of the pixel. I'll look into it...

**Comment by cdeil** [comment]
@AtreyeeS - If you do the checks in a bit more systematic way, it could either be Python scripts or notebooks in gammapy-extra, and/or it could by one test per sky model with an assert on an npred when passing it to a SkyModelEvaluator. Then we know where we stand, and can refactor evaluation between the sky model evaluate and the evaluator.

**Comment by AtreyeeS** [comment]
I see that just the test for the SkyPointSource` woks well, but the  MapEvaluator has tests only for the `SkyGaussian` spectral model. I am guessing that the error lies there. 
Cleaning up my pull distribution code now.
