### ISSUE TITLE
Add make_images method on MapMaker

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1571]
I would propose to add a small convenience method on MapMaker (or standalone) which makes 2D images from 3D cubes by summing or integrating over the energy axis.

This is what some people want that do 2D image-based analysis.

As test case we could use the old
https://github.com/gammapy/gammapy/pull/1568/files#diff-f2e451b070025cd2253c3025e08fce92L55
but for that test case the ring background estimator has to be migrated first (#1570).

@AtreyeeS or @registerrier - Do you have time for this tomorrow?
If no, I could do this.
(I'd like to finish the SkyImage / SkyCube -> Maps transition by Friday this week)

**Comment by AtreyeeS** [comment]
Isn't this what is done by the `sum_over_axes` method, making 2D images from 3D cubes by summing over the energy axis?
http://docs.gammapy.org/dev/api/gammapy.maps.WcsNDMap.html?highlight=sum_over_axes#gammapy.maps.WcsNDMap.sum_over_axes

**Comment by cdeil** [comment]
For counts and background, yes, I think it's just a `sum_over_axes` call.

For exposure, probably we would want to do weighting by a spectral model as here:
https://github.com/gammapy/gammapy/pull/1568/files#diff-f92b7b183b45d4bc8b841ffa28f26b77L690

The idea is to make an image such that if you do `counts - background) / exposure` and have the exposure weighting with the right spectral model, the integral flux of a given source comes out correct again.
It's a bit weird, but it is what we had previously, and also what was done in HESS (e.g. see https://www.mpi-hd.mpg.de/hfm/HESS/hgps/), so I'd suggest to add it back.
It's 5-10 lines of code if you take a `SpectralModel` as input for the method that makes the images, but it's nontrivial, so I'd suggest to offer it as a little helper method `MapMaker.make_images(spectral_model=None)` and for no spectral model take a Powerlaw with index 2.

**Comment by adonath** [comment]
What about if we just provide an additional `weights` argument to the `sum_over_axes()` method and show an example how to compute the weights from a spectral model?

**Comment by registerrier** [comment]
Yes weights are really the best way to go.

**Comment by cdeil** [comment]
OK, but weights can be passed in as a vector or a spectral model is passed and the integral / weights are computed there. I would do it "from the outside" for now, and only when we have 2 callers at least move that to a method on maps. But any solution is fine with me. Anyone has time to type this up?

**Comment by registerrier** [comment]
Initially I had planned a specific function for this `make_map_exposure_reco_energy` with the idea of being able to compute a (most likely 2D) map with spectral weighting and possibly edisp usage. It was not implemented and the caller and docstring was removed.

So we probably should put it back in if we want to have exposure maps made this way. I don't think we should handle this specific issue by twisting `Map.sum_over_axes()`.

**Comment by cdeil** [comment]
Like I said above, I would also prefer to have some code outside gammapy.maps that computes this, probably multiplies the exposure cube data with a spectral weights vector and then calls sum_over_axes on that, no?

**Comment by cdeil** [comment]
I will make a PR for this today.

**Comment by cdeil** [comment]
Done in #1681 by @registerrier
