### ISSUE TITLE
Bias in MapFit

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#1574]
I have been testing MapFit and it seems there is a slight bias in the fitting at high statistics. The pull distributions are shifted at high statistics. I am looking into this, but since I will be on vacations for a month, I doubt I will get time.
The notebook is here:
https://github.com/AtreyeeS/gammapy-extra/blob/map-ex/notebooks/test_pd.ipynb

**Comment by cdeil** [comment]
Note that `pull = (reco - true) / error`, so even for small differences `reco-true` the `pull` can be large if `error` is large. So for very high statistics, the error gets small and it's not super surprising that the pull can be biased.

It'll still be interesting to look at this in detail and understand why it doesn't come out perfect, but if e.g. a flux is off by < 1% or a spectral index by < 0.01, it's not really important.

So maybe you could change your notebook slightly to clarify what level of `npred` you have, or show value and error separately, not just pull, and then we leave this for later, focus on
https://github.com/gammapy/gammapy/milestone/11 for now.

Another very common debug plot is `flux / flux_err` versus `sqrt(npred)` on a log-log plot:
http://enrico.readthedocs.io/en/latest/tutorial.html#check-results

**Comment by registerrier** [comment]
@AtreyeeS . Can we close?

**Comment by AtreyeeS** [comment]
Yes. Pull distributions are OK now
