### ISSUE TITLE
Implement and test edge mode for WcsGeom.get_coord

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1578]
In #1573 apparently @adonath tried to implement `mode="edge"` for `WcsGeom.get_coord`, see his edits here: https://github.com/gammapy/gammapy/pull/1573/files#diff-3cf936d0601fe08b95aa7b11fb9cf614

This doesn't work yet, it causes test fails in gammapy.maps:
https://ci.appveyor.com/project/cdeil/gammapy/build/1.0.3897/job/04tkynv5dibs2jbq#L2313

The missing `mode="edge"` for `WcsGeom.get_coord` was already noticed here:
https://github.com/gammapy/gammapy/blob/a4dad70c8c2f54da57522c7599673ebe5dda24f6/gammapy/maps/wcs.py#L698

I tried to do this in the past 10 min, but the code there is a bit complex.
So this is a reminder issue for myself to first implement `mode="edge"` for `WcsGeom.get_coord` with tests, and to adapt the `solid_angle` caller, and only then to finish up #1573 .

**Comment by adonath** [comment]
As I'd like to finish up #1573, I'll take this over. Re-assigning to me...

**Comment by adonath** [comment]
Resolved in #1592
