### ISSUE TITLE
Improve Sherpa fitting backend code

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1588]
I think we should move  [gammapy/utils/sherpa.py](https://github.com/gammapy/gammapy/blob/master/gammapy/utils/sherpa.py)
to [gammapy/utils/fitting](https://github.com/gammapy/gammapy/tree/master/gammapy/utils/fitting) and add a minimal unit test case that gives one working example.  That should not be much work. This is currently used only by the `FluxPointFitter`.

I guess then we could try to use this generic Sherpa interface from other part, specifically:
- MapFit (currently only iminuit)
- SpectrumFit (currently iminuit or Sherpa with custom Sherpa interface)
- FluxPointEstimator (currently only using scipy.optimize.brentq I think for 1D parameter estimation)

@adonath and / or @joleroi - Maybe one or two of us could work on this for ~ 1 day this week to make it a bit better?

I think this mess / technical debt is holding us back from making progress on modeling in Gammapy, so I would consider it high priority. But of course, time is limited before the v0.8 release, so we might defer this.

**Comment by adonath** [comment]
I will work on this this week.

**Comment by cdeil** [comment]
@adonath - FYI: I've deleted the old `examples/example_sherpa_mwl.py` in 4179ec26 , since as we discussed this is not the way we want to interface with Sherpa. (and even if it were, I wouldn't want to maintain such a complex example there, without having it tested as part of continuous integration)

**Comment by adonath** [comment]
Discussing offline with @cdeil, we decided the existing backend should be discarded in favour of a solution that directly uses the sherpa optimizers instead of the `Fit` API. I'll rewrite the `FluxPointFitter` to use the existing minuit backend and remove the old sherpa one.

**Comment by adonath** [comment]
Addressed in #1605, #1606 and #1614.
