### ISSUE TITLE
Add tutorial how to make IACT DL3 index tables

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1597]
I'll work on the docs today, and removed  0008b859ecb60b4a5466a4c238eaf1b3ad79dae5 just now.

This is a reminder issue to add a short tutorial notebook how to access DL3 data if you don't have index files, showing how to make index tables and a datastore from scratch.

In the coming months this will then be replaced by new code to make observation lists and access IACT data without index tables and the DataStore, but for now (and the past years) this is what one has to do, so it's good to have a working example.

I could use one or both of those example datasets:
- https://github.com/cdeil/HESS-DL3-DR1-preview
- https://github.com/gammapy/gammapy-extra/tree/master/datasets/cta-1dc

Now those have index files, but we can pretend that those index files aren't there, and show how it's possible to make those with ~ 20 lines of Python code that makes an `astropy.table.Table`.

**Comment by adonath** [comment]
There is now the `DatasStore.from_events_files()`, which is probably all a standard users would need. Advanced users will be able to create such a file, based on the documentation here https://gamma-astro-data-formats.readthedocs.io/en/latest/data_storage/index.html. I'll close the issue as the priority is super low...
