### ISSUE TITLE
Improve exclusion mask code / docs

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1612]
@robertazanin asked how to make an exclusion masks for a list of regions.

Here's an example:
```python
"""Example how to make an exclusion mask for multiple regions"""
from astropy.coordinates import SkyCoord, Angle
from regions import CircleSkyRegion
from gammapy.maps import Map

regions = [
    CircleSkyRegion(center=SkyCoord(0, 0, unit='deg'), radius=Angle('0.2 deg')),
    CircleSkyRegion(center=SkyCoord(0, 0.5, unit='deg'), radius=Angle('0.3 deg')),
    CircleSkyRegion(center=SkyCoord(1.0, 0, unit='deg'), radius=Angle('0.4 deg')),
]

# Make an exclusion map, initially an empty map (zero filled)
m = Map.create(npix=(300, 200), binsz=0.01, dtype=bool)

# For each region, make a mask, then OR it with the total mask
for region in regions:
    m.data += m.geom.get_region_mask_array(region)

import matplotlib.pyplot as plt
m.plot(add_cbar=True);
plt.savefig('exclusion.png')
```

![exclusion](https://user-images.githubusercontent.com/852409/43521062-386d0518-9595-11e8-88c7-83528bdea3b2.png)

We should add this and maybe a bit more info how to work with regions to the Gammapy docs.

Also: the make mask code blows up when passing in a CompoundRegion: http://astropy-regions.readthedocs.io/en/latest/compound.html
```
AttributeError                            Traceback (most recent call last)
<ipython-input-149-b1b1afd1779e> in <module>()
----> 1 exclusion_mask=ref_image.make_region_mask(off_regions, inside=False)
     2 #exclusion_mask.make_region_mask
     3 exclusion_mask.plot(add_cbar=True)
     4
     5 #exclusion_mask = ref_image.region_mask(on_region)

~/.local/lib/python3.6/site-packages/gammapy/maps/wcsnd.py in make_region_mask(self, region, inside)
   614             the mask map
   615         """
--> 616         mask = self.geom.get_region_mask_array(region)
   617         if inside is False:
   618             np.logical_not(mask, out=mask)

~/.local/lib/python3.6/site-packages/gammapy/maps/wcs.py in get_region_mask_array(self, region)
   766         idx = self.get_idx()
   767         pixcoord = PixCoord(idx[0], idx[1])
--> 768         return region.contains(pixcoord)
   769
   770     def __repr__(self):

AttributeError: 'list' object has no attribute 'contains'
```
We can look into either making it work (changing the implementation), or alternatively trying to give a better error message.

**Comment by cdeil** [comment]
Actually there's already a TODO in the code:

https://github.com/gammapy/gammapy/blob/98982e40d71a381cac82a849c5e7d0025f5074b8/gammapy/maps/wcs.py#L762

So the task here is:
1. Resolve that (ideally by making it work for compound, alternatively better error)
2. Add docs example (not sure where)

Let's discuss tomorrow morning who does this, after the more high-priority work is done.

**Comment by registerrier** [comment]
A solution for me is to use `WcsNDMap.make_region_mask()` accept a list of regions rather than a single one. This way you can relieve the user with either the creation of the `CompoundRegion` or with the loop on the list of regions.

**Comment by cdeil** [comment]
+1 to change http://docs.gammapy.org/dev/api/gammapy.maps.WcsNDMap.html#gammapy.maps.WcsNDMap.make_region_mask to accept list of region. (And only list of region, a caller can do `[region]` if they just have one, and trying to support both single and list like we do in other places is unnecessary complication IMO in the documentation and testing)

(and if it's easy, we could still make this work for CompoundRegion)

**Comment by cdeil** [comment]
Done by @registerrier in #1628 .
Closing issue.
