### ISSUE TITLE
Improve code and tests to fill counts maps

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1620]
In #1619 I did a little bit of cleanup for [gammapy/cube/counts.py](https://github.com/gammapy/gammapy/blob/master/gammapy/cube/counts.py) and [gammapy/cube/tests/test_counts.py](https://github.com/gammapy/gammapy/blob/master/gammapy/cube/tests/test_counts.py).

The following things should be done IMO:

I'd again like to make the suggestion to remove `make_map_counts`. It can now be written as one line:
```
def make_map_counts(events, geom):
    return fill_map_counts(Map.from_geom(geom), events)
```
@registerrier - If you insist on keeping it, we should add a test.

`fill_map_counts` does not work for a column / axis without unit. E.g. I tried to use `EVENT_ID` here:
https://github.com/gammapy/gammapy/blob/59f04eaa71c7d1616fe1b61807fa85142fa601fb/gammapy/cube/tests/test_counts.py#L65
and it failed. The reason is this, which to be honest I find a bit surprising:
```
>>> from gammapy.data import EventList
>>> events = EventList.read('$GAMMAPY_EXTRA/datasets/cta-1dc/data/baseline/gps/gps_baseline_110380.fits')
>>> events.table['EVENT_ID'].quantity.to('')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.6/site-packages/astropy/units/quantity.py", line 847, in to
    return self._new_view(self._to_value(unit, equivalencies), unit)
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.6/site-packages/astropy/units/quantity.py", line 819, in _to_value
    equivalencies=equivalencies)
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.6/site-packages/astropy/units/core.py", line 965, in to
    return self._get_converter(other, equivalencies=equivalencies)(value)
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.6/site-packages/astropy/units/core.py", line 880, in <lambda>
    return lambda val: scale * _condition_arg(val)
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.6/site-packages/astropy/units/core.py", line 2293, in _condition_arg
    raise ValueError("Value not scalar compatible or convertible to "
ValueError: Value not scalar compatible or convertible to an int, float, or complex array
```

Anyways, we should have improved tests, also for combinations of columns and axes with and without units.

I think this TODO should be addressed: make one test function that just tests the axis name matching with different cases:
https://github.com/gammapy/gammapy/blob/59f04eaa71c7d1616fe1b61807fa85142fa601fb/gammapy/cube/tests/test_counts.py#L14
That will make the test file overall more readable.

I think the implementation of `fill_map_counts` can now be improved? I think we added a get by name, so there's two lines that can go? I would also suggest to remove the axis type and just do matching by name. I guess that last suggestion might be controversial.

@registerrier - Interested in this task for tomorrow?
Otherwise I could also work on this ...

**Comment by cdeil** [comment]
@registerrier - I will remove `make_map_counts` now, and then leave the bug and improvement of `fill_counts_map` to you.

**Comment by cdeil** [comment]
The `make_map_counts` was removed in #1625 .
I'll now touch counts.py or test_counts.py now.

**Comment by cdeil** [comment]
@registerrier - Thanks for fixing / improving `fill_map_counts` in #1631

I still think we should remove `axis.type`. There's one user and that can be done by name: find first axis with "energy" in the name.
```
$ ack axis.type gammapy
gammapy/maps/geom.py
366:        # Set axis type from its unit
438:        """Return coordinate axis type."""
1414:            raise ValueError("Invalid axis type {}. Should be {}.".format(type, valid_types))
1417:            if axis.type == type:

gammapy/cube/counts.py
58:        if axis.type == 'energy':
```

Now we have this: http://docs.gammapy.org/dev/development/howto.html#coordinate-and-axis-names

That should be enough and simple. If we do things by axis name in some places, and by axis type in others, I think it'll be a mess.

@registerrier - OK to remove axis type, and try to do things by http://docs.gammapy.org/dev/development/howto.html#coordinate-and-axis-names in Gammapy?

**Comment by registerrier** [comment]
I was doing the update

**Comment by cdeil** [comment]
This is done. Closing.

The code in https://github.com/gammapy/gammapy/blob/master/gammapy/cube/counts.py and https://github.com/gammapy/gammapy/blob/master/gammapy/cube/tests/test_counts.py is now very simple.
