### ISSUE TITLE
Add MapFit test with only one energy bin

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1623]
Yesterday I added a test for `MapMaker` for a cube with only one energy bin:
https://github.com/gammapy/gammapy/blob/ddfd325f1510e2999199c02b75f7ca680cff4d16/gammapy/cube/tests/test_make.py#L40

We should do the same for MapFit, a test for that should be added.
I think it should even be possible with a PSF kernel, that has an energy axis with a single energy bin?

During code review in the past months, we had many cases where people `np.sqeeze` axes of length 1, and tried to get rid of them all, but some might still be there. Or there might be other issues just in `gammapy.maps` with axes with a single bin. This is a great test to find those issues and fix them.

@robertazanin mentioned via email that it's currently not working, without specifics.

The best way to proceed is probably to make a single energy bin here to try:
https://github.com/gammapy/gammapy/blob/ddfd325f1510e2999199c02b75f7ca680cff4d16/gammapy/cube/tests/test_fit.py#L25
and then to add a second MapFit test for that; I'm not sure how to do it best without too much code repetition, it might be best if someone makes a proposal and we discuss a bit here before writing it all.

**Comment by registerrier** [comment]
@AtreyeeS can you have a look?

**Comment by AtreyeeS** [comment]
Done in #1925
