### ISSUE TITLE
Draw initial directions of pulsars correctly

### ISSUE THREAD

**Issue by adonath** [gammapy/gammapy#164]
Currently both angles for the initial direction of the proper motion of pulsars are drawn from a uniform distribution. This is incorrect. To obtain a uniform distribution of directions on the sphere the same approach as in [sample_sphere](https://gammapy.readthedocs.org/en/latest/api/gammapy.utils.random.sample_sphere.html?highlight=sphere#gammapy.utils.random.sample_sphere) has to be used.

**Comment by cdeil** [comment]
Closing this old issue. We have 100 bigger fish to fry and should focus on those for the next year. IMO it also helps to have the Gammapy issue tracker cleaned out and only important issues left, so that people know what to focus on.
