### ISSUE TITLE
SpectrumFitResult.plot() fails

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#1642]
During the commit to remove the sherpa fitting backend, the background has been removed from SpectrumFit. The plot therefore fails. 
The test in spectrum/test/test_result.py as written masks the failure by passing a fake predicted background.
Any idea @joleroi , @cdeil?

**Comment by cdeil** [comment]
Should be fixed in Gammapy master now, in #1672 by @joleroi .
@registerrier - Please try again and shout if not.
