### ISSUE TITLE
Quantity support in map get_by_coord

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1646]
Currently `get_image_by_coord` does support Quantity, i.e. you can use it like this:

```
            image = m_wcs.get_image_by_coord({'energy': '500 GeV', 'time': '1 h'})
            # Get image by coord dict with quantities
            image = m_wcs.get_image_by_coord({'energy': 0.5 * u.TeV, 'time': 1 * u.h})
```

See examples and implementation here:

https://github.com/gammapy/gammapy/blob/418260e781a2212728e4b793e1eeeb5ce8725e07/gammapy/maps/base.py#L547

However, `get_by_coord` and `interp_by_coord` does not support Quantity. When passing a Quantity, it "works", but just uses the value and assumes it's given in the map axis unit. I was baffled by this just now, where I was interpolating or getting from a map with energy axis in MeV, and was passing energy coordinates in GeV.

I think this will bite many users and silently give them incorrect analysis results, and thus we should fix this now, before the v0.8 release. To improve this, I think we have to add support for quantity coordinates to MapCoord, and then change functions like `get_by_coord` and `interp_by_coord` and `get_image_by_coord` to consistently go through `MapCoord` on the first line, to get good and consistent behaviour. It can be done as one larger PR, or a series of small PRs, but overall someone has to spend a day to work on this. I'm interested in this task, but of course if someone else wants to do it and has time today or tomorrow for this: go for it!

**Comment by adonath** [comment]
Resolved by #1685
