### ISSUE TITLE
FluxPointEstimator residuals

### ISSUE THREAD

**Issue by bkhelifi** [gammapy/gammapy#1647]
Hi all,
As mentioned to @joleroi during the last coding sprint, residuals are plotted even when the Point is an upper limit! One could add a mask in the plot_residual fonction to remove UL points...
Thanks in advance

**Comment by cdeil** [comment]
@joleroi - Was this addressed in #1672 ?
Is there action item left or should this issue be closed?

**Comment by cdeil** [comment]
Closing. @bkhelifi - Please re-open or file a new issue if something is still not working.
