### ISSUE TITLE
Update source_population_model notebook

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#165]
@adonath Could you please update the [gp-gsim-cat-gal](https://github.com/gammapy/gammapy/blob/master/scripts/gp-gsim-cat-gal) script to work after your improvements in #157?

It's up to you how many  / which options you want to make available in this command line script.
It should be a quick way to create useful model galaxy catalogs, but we shouldn't try to make every option available because many users will be comfortable with writing a few line Python script to do what they want.

**Comment by cdeil** [comment]
The script is here now:
https://github.com/gammapy/gammapy/blob/master/gammapy/scripts/simulate_source_catalog.py

Looks like it's broken at the moment:
```
$ gammapy-simulate-source-catalog a.fits 100
Traceback (most recent call last):
  File "/Users/deil/Library/Python/3.4/bin/gammapy-simulate-source-catalog", line 9, in <module>
    load_entry_point('gammapy==0.3.dev1242', 'console_scripts', 'gammapy-simulate-source-catalog')()
  File "/Users/deil/code/gammapy/gammapy/scripts/simulate_source_catalog.py", line 31, in main
    simulate_source_catalog(**vars(args))
  File "/Users/deil/code/gammapy/gammapy/scripts/simulate_source_catalog.py", line 55, in simulate_source_catalog
    table = simulate.make_cat_gal(int(nsources),
AttributeError: 'module' object has no attribute 'make_cat_gal'
```
Changing the milestone to 0.4 because I want to cut the 0.3 release tomorrow and now fix this now.

**Comment by cdeil** [comment]
@adonath – Can you fix this script quickly? If no time, please move to 0.4 milestone.

**Comment by cdeil** [comment]
Here's the current version of the command line script we have:
https://github.com/gammapy/gammapy/blob/master/gammapy/scripts/catalog_simulate.py

By now I think this is functionality we don't have to expose via a command line tool.
If someone wants to simulate a source population, it's better (for readability and reproducability) if they write a script that sets the parameters and runs the code.

So my suggestion would be to remove `gammapy/scripts/catalog_simulate.py` and instead add a documentation page or IPython notebook that shows how to simulate a source catalog.
(we have http://nbviewer.jupyter.org/github/gammapy/gammapy-extra/blob/master/notebooks/source_catalogs.ipynb which is focused on real catalogs, that could be extended or a new notebook could be started)

@adonath - Thoughts? Are you interested to do this in the coming weeks? If no, my suggestion would be that we just remove the command line tool now and keep this issue open as a request for documentation.

**Comment by adonath** [comment]
What about this notebook:
http://nbviewer.jupyter.org/github/gammapy/gammapy-extra/blob/master/notebooks/source_population_model.ipynb

I think that already shows what can be done. I'm fine with removing the script

**Comment by cdeil** [comment]
I'll remove the command line script now.

Let's keep this issue open though ... the `source_population_model.ipynb` has several TODOs and is listed in the notebook [work in progress](http://nbviewer.jupyter.org/github/gammapy/gammapy-extra/blob/master/notebooks/Index.ipynb#Work-in-progress) section. Also it doesn't use quantities in some places where units are listed in code comments. So maybe even the implementation should be changed.

**Comment by adonath** [comment]
You're right, maybe I find some time this week to polish the notebook a bit.

**Comment by adonath** [comment]
As the notebook has been removed meanwhile I'm closing the issue.
