### ISSUE TITLE
Merge SourceLibrary and SumSkyModel

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1652]
Should we merge [SourceLibrary](https://github.com/gammapy/gammapy/blob/df3330a400f9f0f5f6d8be099608aae4fa0e3f9f/gammapy/cube/models.py#L22) and [SumSkyModel](https://github.com/gammapy/gammapy/blob/df3330a400f9f0f5f6d8be099608aae4fa0e3f9f/gammapy/cube/models.py#L244) into one class? They both represent a Python list of sky model objects. SourceLibrary currently contains a few methods to serialise the model (at the moment only to XML). SumSkyModel contains the parameter handling and evaluate.

I don't see any advantages to keeping those separate, so I'm +1 to merge.
As name, suggest to just call this `SkyModels` with an "s".

**Comment by adonath** [comment]
Sounds like a good suggestion to me, there is no good reason why we should keep both...

**Comment by cdeil** [comment]
Done by @adonath in #1703 .
