### ISSUE TITLE
Warning in data_fermi_lat.ipynb conversion

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1654]
I edited `gammapy-extra/notebooks/data_fermi_lat.ipynb` in the last days, and now when running `python setup.py build_docs` there's this warning:
```
/home/travis/build/gammapy/gammapy/docs/notebooks/data_fermi_lat.ipynb.rst: WARNING: file not found: 'maps'
```
It makes our docs build fail in CI:
https://travis-ci.org/gammapy/gammapy/jobs/412973457#L2004

I grepped the notebook for "maps" and couldn't spot the problem.

@Bultako - Could you please have a look?

**Comment by Bultako** [comment]
Ok
Fixed in https://github.com/gammapy/gammapy-extra/commit/b48336414e686b79516fd3db5f0ed168799a0fee

You need the filename in the URL when declaring a link, not just the folder.
In this case I have replaced http://docs.gammapy.org/dev/maps/ by  http://docs.gammapy.org/dev/maps/index.html

**Comment by cdeil** [comment]
@Bultako - Thank you!
