### ISSUE TITLE
WcsNDMap.cutout() and width

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#1673]
At the moment, `WcsNDMap.cutout()` does not return the expected cutout. `lon` and `lat` dimensions are inverted. This is because of `astropy.cutout2D` which expects the `width` to be `ny,nx`.
We can either change the docstring of `WcsNDMap.cutout()` or adapt it so that it passes `width`in the correct order if it is a `list` of `Angle`.

The easy solution is to stick to the satrapy convention for cutouts, even if it is not very intuitive.
Agree @adonath @cdeil?

**Comment by cdeil** [comment]
This was discussed at length in https://github.com/gammapy/gammapy/issues/1608 .
I thought this was already done.
Let's close this one, and re-open that other one, to keep discussion on one place.
