### ISSUE TITLE
Add better test for SkyDiffuseCube

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1689]
In #1629 we added the [gammapy.cube.models.SkyDiffuseCube](http://docs.gammapy.org/dev/api/gammapy.cube.models.SkyDiffuseCube.html). Already in that issue I noted that it doesn't seem to give correct results for DC1 . For unknown reasons.

Now @robertazanin and @registerrier also found incorrect results when fitting it's norm on CTA DC1, e.g. Roberta gets norm=0.05 for J1702 even though there is a visible positive excess along the Galactic plane.

There could be a bug related to how this model is used in the `MapEvaluator` to compute npred, i.e. the combination of model eval and how this is processed in MapEvaluator is incorrect. As a first step to debug this, I'll add a test that runs this model through MapEvaluator for some exposure cube and asserts the current result. We don't do that yet for this or actually most models, we just check evaluate, see [here](https://github.com/gammapy/gammapy/blob/0baba866d22dd06f7d394e7db7d099e134e13ce7/gammapy/cube/tests/test_models.py#L198).

Of course there could also be a bug in ctobssim for this model, or just a mismatch in understanding how this model is to be used.

I don't think the problem is related to integration over energy, because e.g. @robertazanin uses very fine energy bins.

One issue I already notice in http://docs.gammapy.org/dev/notebooks/data_fermi_lat.html#Background is that our current PSF apply seems to use a "zero padded" mode, leading to incorrect results at the edge of the image. I don't think these effects are large enough to explain the incorrect norm people are seeing, but still: @registerrier @adonath - is it possible to change to a "reflect"-like behaviour boundary mode in the PSF convove, so that a constant image comes out constant again after PSF apply and we don't loose flux / counts at the edge?

**Comment by cdeil** [comment]
For the spatial convolve, as I said above, we are "loosing npred counts" at the edge because we use [astropy.convolution.convolve_fft](http://astropy.readthedocs.io/en/stable/api/astropy.convolution.convolve_fft.html#astropy.convolution.convolve_fft) with zero padded boundary handing. I'd like to change this to [scipy.ndimage.convolve](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.convolve.html) with the default model='reflect' because that mostly avoids the issue. Of course there are performance implications, but we've looked at this before and I already know that for small kernels `scipy.ndimage.convolve` is fater, and for large kernels slower than FFT convolve. IMO `astropy.convolution` makes no sense for us in Gammapy. It's main difference wrt the scipy convolve functions is that it does some NaN handling which they claim to be better for some astrophysical applications, but we don't have NaN in our images, and so it's just slower, we should only use scipy convolve functions. @registerrier @adonath - OK if I change this now?

Another similar issue is that we get too low npred at the lower energy edge, again becuase we're not computing the npred that comes from the true energies just below the energy threshold. For this, we could try to introduce `e_true` with a larger range, or for now, we could also modify EDISP to be at least counts preserving if that's not the case. This is something that I'd like to defer to v0.9, not attempt to quick-fix today. @registerrier @adonath - OK?

**Comment by registerrier** [comment]
OK for me to rely only on scipy.
regular convolution can be an issue if the kernel size is not optimized. This means we have to work soon on a energy dependent PSF kernel size.

**Comment by cdeil** [comment]
@adonath - I think this issue was done by you in #1749 ? Close? (or mention remaining action item and move to v0.9, please)

**Comment by adonath** [comment]
Resolved in #1749.
