### ISSUE TITLE
Improve repr of gammapy.maps classes

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1699]
@adonath - could you please improve the repr for the classes in gammapy.maps a bit?
I.e. Map, Geom, MapAxis and MapCoord.

At least for me, it's often not clear yet where nx and ny is printed.
Another thing I found confusing was to have a diffuse cube with first energy at 1 TeV in center mode and then the repr show an edge min that is lower.
See https://gist.github.com/cdeil/3b2e1191a15ea49a1dbc4a31581d6007

After improving this a bit we should update
http://docs.gammapy.org/dev/notebooks/intro_maps.html
and IMO put a special emphasis on the energy axis, and to explain what center and edges mode is, and how the interp mode affects coords. I think even within Gammapy we might have small bugs because that is not handled properly in MapMaker or MapFit, so explaining how it works would be important.

As usual, IMO http://xarray.pydata.org/ or https://spectral-cube.readthedocs.io/ are good examples to look at, what repr they give.

**Comment by adonath** [comment]
Addressed in #1700.
