### ISSUE TITLE
Bad covar with iminuit 1.2

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1718]
I'm getting a bad covariance matrix and thus spectral error band in this example with Gammapy master and iminuit 1.2:

https://nbviewer.jupyter.org/github/gammapy/gammapy-extra/blob/66ee6554e0636fc6fddfa176272d79d713c27a14/notebooks/sed_fitting_gammacat_fermi.ipynb#Exponential-Cut-Off-Powerlaw-Fit

After updating to iminuit 1.3.2 the issue is resolved.

I don't understand why yet.

---

This is a reminder issue for me to look at this tomorrow, probably:

- Add a CI build for iminuit 1.2 and some more unit tests for that backend. Especially on the covar that we compute [here](https://github.com/gammapy/gammapy/blob/c118a2bb94a13f68546c82d8e2c02b5d88a710cf/gammapy/utils/fitting/iminuit.py#L116
)
- Add test for [FluxPointFitter](https://github.com/gammapy/gammapy/blob/7bb339cb9d35a164a252ca1587884ef936f08a05/gammapy/spectrum/flux_point.py#L882) that runs this example and asserts on the covariance to have a regression test.
- Refactor FluxPointFitter a bit to remove the input model copy, and to put the likelihood into a separate function instead of having it as a closure like we have in other places.

cc @adonath

**Comment by cdeil** [comment]
I'm wondering if we should bump the iminuit version requirement from 1.2 to 1.3.2.

the 1.3.2 is very new, just released a month ago: https://pypi.org/project/iminuit/#history
But there are conda packages on conda-forge, and pip install should also work well if you have a C++ compiler.

- There was a but in exception handling, an exception in the likelihood function made iminuit crash
- There was a bug in the covar, it was sometimes incorrect
- With 1.3 there is a Numpy interface to iminuit, we would no longer have to use the "parN_" prefix

**Comment by facero** [comment]
Just for the record, the new Numpy interface (removing "ParN_") will break the call fit.minuit.draw_contour('par_002_amplitude','par_001_index',bound=3,show_sigma=True) and might cause issues in Sky Compound model when having multiple sources with same parameter name.

**Comment by cdeil** [comment]
@facero - You are right. Keeping the parnames as-is for now. I did #1771 to require iminuit >= 1.3.2.
closing this issue now.
