### ISSUE TITLE
Spectrum result counts plot excess or counts?

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1720]
@joleroi - Could you please have a look at this?

https://github.com/gammapy/gammapy/blob/c118a2bb94a13f68546c82d8e2c02b5d88a710cf/gammapy/spectrum/results.py#L229-L235

I saw this in  #139 as one of the few last remaining lines that raise a warning in Gammapy, in this example:

https://nbviewer.jupyter.org/github/gammapy/gammapy-extra/blob/080627bbb409803aa0ba1fa82931237699d3a157/notebooks/spectrum_analysis.ipynb#Fit-spectrum

The problem is that you're calling `np.sqrt` on excess, and that is sometimes negative.

I looked at the code a bit, and I think actually what you're plotting is excess and also the `mu_source` shown is without background? But the plot label says `n_on`, not `excess`.

How about changing to plot `n_on`?

Or if you prefer to plot excess, then completely remove the error bars, because `np.sqrt(excess)` is not a good excess error measure, it completely neglegts background.

**Comment by cdeil** [comment]
So if you plot excess this will still emit the Numpy warnings then, because you're taking sqrt of a negagive number, no?

I think you have to change this:

https://github.com/gammapy/gammapy/blob/8a8c3c4da054d8d6fbe399248db4bbbf86e7a66a/gammapy/spectrum/core.py#L166

to
```
if show_poisson_errors:
     yerr = np.sqrt(counts)
else:
    yerr = 0
```
and then call with `show_poisson_errors=False` for excess, no?

(or put the np.sqrt in a with `with np.errstate(invalid='ignore'):` to suppress the warning, but showing sqrt excess as error is incorrect if there is background).

**Comment by joleroi** [comment]
Mmh, what the difference between
```
val = 1 if condition else 0
```
and
```
if condition:
    val = 1
else:
    val =0
```
I always though they were the same

**Comment by cdeil** [comment]
You're right, ignore what I said. But the Numpy warning for negative excess bins still needs to be dealt with, no?

**Comment by joleroi** [comment]
> Or if you prefer to plot excess, then completely remove the error bars, because np.sqrt(excess) is not a good excess error measure, it completely neglegts background.

The excess is now shown [without poisson errors](https://github.com/gammapy/gammapy/commit/8a8c3c4da054d8d6fbe399248db4bbbf86e7a66a#diff-f62764eadcaaa3f0de5e7a538e709650L234), so the warning should have disappeared ...

**Comment by cdeil** [comment]
Ah, OK. Then all is good. Thanks!
