### ISSUE TITLE
4D Map reproject IndexError

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1728]
@adonath - 4D map reproject is broken, it gives an IndexError. Probably this is a regression that got introduced in #1711 . Could you please fix?

https://travis-ci.org/gammapy/gammapy/jobs/418894507#L4649

```
IndexError                                Traceback (most recent call last)
<ipython-input-23-f837fa8ef7e5> in <module>()
      1 geom_rep = WcsGeom.create(binsz=binsz, skydir=source_pos,coordsys="GAL", width=15.0,axes=[energy_axis, mc_axis])
----> 2 map_rep = map4d.reproject(geom_rep)

~/work/code/gammapy/gammapy/maps/base.py in reproject(self, geom, order, mode)
    439             return self._reproject_to_hpx(geom, mode=mode, order=order)
    440         else:
--> 441             return self._reproject_to_wcs(geom, mode=mode, order=order)
    442 
    443     @abc.abstractmethod

~/work/code/gammapy/gammapy/maps/wcsnd.py in _reproject_to_wcs(self, geom, mode, order)
    272                     "Invalid reprojection mode, either choose 'interp' or 'exact'")
    273 
--> 274             data[idx] = vals
    275 
    276         return self._init_copy(geom=geom, data=data)

IndexError: index 3 is out of bounds for axis 0 with size 3
```

**Comment by adonath** [comment]
I think that's actually the same issue as we've noticed with the `RingBackroundEstimator`, that the `idx` returned by `.iter_by_image()` is in reversed order. I'll review all the places where we do the iteration over images now...and try to fix it for all.

**Comment by cdeil** [comment]
@adonath - Thanks!

For now we don't share fixtures across Gammapy tests, and it's not easy to organise this well. So for now, you could just change the existing tests we have for the functions that are supposed to handle extra axes, and insert one or two dummy axes with one or two bins, to have a regression test before changing the idx handling in the implementations.
