### ISSUE TITLE
Check map geom FITS axcols numbers

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1734]
In 51bee796352cc044e60df92abe70ea8345f6801c I did a little code cleanup for the geom _fill_header_from_axes method and noticed that tests still pass if I change from `start=1` to `start=2`.

This means we don't have good tests for this.

I also noticed that there's several enumerate calls where we loop over axes and start counting at zero:

https://github.com/gammapy/gammapy/blob/96368658ee771573edd54c75c6fc2a6caabc4e20/gammapy/maps/geom.py#L30

https://github.com/gammapy/gammapy/blob/96368658ee771573edd54c75c6fc2a6caabc4e20/gammapy/maps/geom.py#L69

https://github.com/gammapy/gammapy/blob/96368658ee771573edd54c75c6fc2a6caabc4e20/gammapy/maps/geom.py#L116

https://github.com/gammapy/gammapy/blob/96368658ee771573edd54c75c6fc2a6caabc4e20/gammapy/maps/geom.py#L727

Looking here very briefly it seems that counting sometimes starts from 0 and sometimes from 1!?

https://gamma-astro-data-formats.readthedocs.io/en/latest/skymaps/index.html#bands-hdu

@woodmd - If you can comment here, that would be great.

Otherwise, @adonath - I think one of us should have a closer look at this before we cut the v0.8 release. If there's a bug and we start writing files, those files will be corrupt and not readable with later versions of Gammapy.

**Comment by cdeil** [comment]
A related issue is that `HpxGeom.make_energies_hdu` is completely broken:

https://github.com/gammapy/gammapy/blob/96368658ee771573edd54c75c6fc2a6caabc4e20/gammapy/maps/hpx.py#L1419-L1431

```
>>> from gammapy.maps import Map, MapAxis
>>> energy_axis = MapAxis.from_bounds(100., 1E5, 12, interp='log')
>>> m_hpx = Map.create(binsz=0.1, map_type='hpx', width=10.0, axes=[energy_axis])
>>> m_hpx.geom.make_energies_hdu()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/deil/work/code/gammapy/gammapy/maps/hpx.py", line 1499, in make_energies_hdu
    ectr = np.sqrt(self._axes[0][1:] * self._axes[0][:-1])
TypeError: 'MapAxis' object is not subscriptable
```

The `make_ebound_hdu` doesn't take axis units into account and is thus also broken for an energy axis with TeV.

Probably we didn't notice so far because that convention to serialise energy axis isn't used by default?

See the only caller of those methods in write here:
https://github.com/gammapy/gammapy/blob/96368658ee771573edd54c75c6fc2a6caabc4e20/gammapy/maps/hpx.py#L1450-L1453

**Comment by adonath** [comment]
So I've looked into this a bit and seems like all the three methods `HpXGeom.write()`, `HpxGeom.make_energies_hdu()` as well as `HpxGeom.make_energies_hdu()` are unused and untested. The `.write()` method on the `HpxGeom` does not make sense to me either. The I/O for `HpxNDMap` goes completely through `.make_bands_hdu()` of the `MapGeom` base class. So I guess there is no reason to keep those extra methods on the `HpxGeom` object, except maybe compatibility with fermpy? @cdeil Any idea how to check this?

**Comment by cdeil** [comment]
> So I've looked into this a bit and seems like all the three methods HpXGeom.write(), HpxGeom.make_energies_hdu() as well as HpxGeom.make_energies_hdu() are unused and untested. The .write() method on the HpxGeom does not make sense to me either. The I/O for HpxNDMap goes completely through .make_bands_hdu() of the MapGeom base class. So I guess there is no reason to keep those extra methods on the HpxGeom object, except maybe compatibility with fermpy? @cdeil Any idea how to check this?

@dimauromattia or @woodmd - Can you comment, please?

We want to release Gammapy v0.8 in the coming days, and of course don't want to break Fermipy.

---

@woodmd set up on CI build for Fermipy to test against Gammapy master:

https://github.com/fermiPy/fermipy/blob/6cbbc0293315caeda3a9bb46e72d2340e696707e/.travis.yml#L91-L102

It passed a week ago:

https://travis-ci.org/fermiPy/fermipy/jobs/417147857

That doesn't mean it's passing now, it's non-ideal that we don't see in Gammapy PRs if we're breaking Fermipy tests or not before merging them.

I think that Fermipy can be installed and a subset of tests run without needing to install Fermi ST. We should add that to the Gammapy CI, I'll try to do that today. And @dimauromattia  - Fermipy should improve the test coverage in that mode to assert on gammapy.maps behaviour they rely on.

**Comment by cdeil** [comment]
@adonath - What you can do locally is to remove or change things in gammapy.maps, and then to also run tests in Fermipy via `cd ../fermipy; pytest -v` before making a PR. This also works on Python 3.

For me this currently gives
```
49 passed, 31 skipped, 22 warnings in 14.29 seconds 
```
See https://gist.github.com/cdeil/4ebc25a94eb8c1ad0bb6ecb75ad49197

@dimauromattia - I think you're also using pytest? Can you fix this?
```
fermipy/tests/test_config.py::TestClass
  cannot collect test class 'TestClass' because it has a __init__ constructor
```

**Comment by cdeil** [comment]
@dimauromattia - We now have a CI build in Gammapy that checks that Fermipy master tests pass with Gammapy master. It doesn't have the Fermi ST installed, so only the tests that don't need those are run. See #1741 .

If you can improve and extend the test coverage of `gammapy.maps` in those tests, that would help us work on `gammapy.maps` more confidently in the coming months, and to notice if we break anything used in Fermipy right away and don't merge such changes in Gammapy.

**Comment by woodmd** [comment]
I think the `make_ebound_hdu` and `make_energies_hdu` methods could safely be dropped at this point.  These are left over from earlier iterations of the `maps` code before we generalized to arbitrary non-spatial axes.  I'm pretty sure that we're not using them anywhere in fermipy.  Regarding `HpxGeom.write` it might be nice to try to rework this into a `MapGeom.write` method in order to provide some way of serializing a geometry without a map instance but I'll leave that up to you.

**Comment by cdeil** [comment]
@adonath - I think this issue is resolved? Close?

Did you add a test that has an assert on the AXCOL header keys and checks that we start numbering at 1 on write? (calling `map.to_hdu_list()[?].header), not hitting the disk)?

**Comment by adonath** [comment]
Regression test added in https://github.com/gammapy/gammapy/commit/c2a06b0b0b99b7ed7504de5d946f4e4f3a6b3d93
