### ISSUE TITLE
Update test_observation.py to new HESS dataset

### ISSUE THREAD

**Issue by adonath** [gammapy/gammapy#1744]
The edisp matrix of the `'$GAMMAPY_EXTRA/datasets/hess-crab4_pha/pha_obs23523.fits'` dataset, which is used in the `test_observation.py` test, contains negative values, which leads to a `UserWarning`, when the matrix is plotted using a `PowerNorm` scale. The test should be changed to an updated dataset.

**Comment by cdeil** [comment]
I'll work today a bit on changing this and a few other tests and notebooks that were using HESS files over to https://github.com/gammapy/gammapy-extra/tree/master/datasets/hess-dl3-dr1 .
