### ISSUE TITLE
Travis CI broken in test_iminuit

### ISSUE THREAD

**Issue by Bultako** [gammapy/gammapy#1768]
pytest script:
https://github.com/gammapy/gammapy/blob/f6fe37db6aab7969e10c029b29da158bb97b077f/gammapy/utils/fitting/tests/test_iminuit.py#L46

![captura de pantalla 2018-09-07 a las 13 45 42](https://user-images.githubusercontent.com/328261/45217441-57125500-b2a4-11e8-8cd6-fe0014b35f55.png)

**Comment by cdeil** [comment]
I'll fix that today.

**Comment by cdeil** [comment]
Fixed in #1771
