### ISSUE TITLE
Problems with the maps intro notebook

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1770]
@adonath @Bultako - looking at http://docs.gammapy.org/dev/notebooks/intro_maps.html I see some issues.

The links at the start with the manual TOC that you added don't work:

![screen shot 2018-09-07 at 17 48 32](https://user-images.githubusercontent.com/852409/45229515-4672d680-b2c6-11e8-9555-ddbe208fc9fc.png)

The bullet list in this section doesn't render propertly:

http://docs.gammapy.org/dev/notebooks/intro_maps.html###-3.-Reading-and-Writing

The `#` and manual numbers in the heading lead to formatting issues in the headings and navbar on the side:

![screen shot 2018-09-07 at 17 49 24](https://user-images.githubusercontent.com/852409/45229548-63a7a500-b2c6-11e8-8d59-dbdbed804621.png)

I'm not sure if some of those things are issues or could be fixed in our jupyter HTML conversion. Even if yes, I would suggest to edit the notebook for now and remove the manual numbers from the headings, and also to add empty lines as needed to make the bullet list work, and to remove the manual TOC at the start.

@adonath - Thoughts? You or me?

**Comment by adonath** [comment]
@cdeil As quick try I added inline html to link to the individual sections. In the notebook this works totally fine. It was rather a convenience for me when working on the notebook, because I became tired of scrolling to the last sections. While I think this is still useful in general when working with the notebook, it is not really important, so I'll just remove it...

**Comment by Bultako** [comment]
@adonath 
You will just have to remove the trailing dashes that you use to underline the section titles, and TOC links and titles format will behave properly.

**Comment by cdeil** [comment]
I now have nbsphinx 2.1.3 and pandoc 2.1.3 .

@adonath - let me know when the maps intro notebook is updated and I'll try the docs build again.

**Comment by cdeil** [comment]
@adonath - Please also fix the typo in the link to the other notebook:
```
/Users/deil/work/code/gammapy/docs/notebooks/intro_maps.ipynb.rst: WARNING: file not found: 'notebooks/fits_steps.ipynb'
```

**Comment by cdeil** [comment]
@adonath - One more issue in the maps intro notebook:
https://travis-ci.org/gammapy/gammapy/jobs/426431157#L2836

What's going on here? Did I introduce a bug today or was this bug there already and it somehow doesn't always show up (e.g. because of using dict isntead of OrderedDict)?

**Comment by adonath** [comment]
@cdeil @Bultako Thanks for the suggestions, I'll try to fix the notebook now...

**Comment by adonath** [comment]
@cdeil No, this was an actual bug that has always been there. I fixed it directly in master in https://github.com/gammapy/gammapy/commit/34c3de735ac3383aafa5328cf6f2507b4eda3d8a.

**Comment by adonath** [comment]
All remaining issues were fixed in https://github.com/gammapy/gammapy-extra/commit/056d644b4bec56ac261f04bef3cf8f33c6cf1a73.
