### ISSUE TITLE
Notebook cta_data_analysis broken

### ISSUE THREAD

**Issue by Bultako** [gammapy/gammapy#1773]
<pre>
INFO:gammapy.scripts.jupyter:   ... TESTING cta_data_analysis.ipynb
INFO:gammapy.scripts.jupyter:   ... Executing duration: 0.56 mn
INFO:gammapy.scripts.jupyter:   ... FAILED cta_data_analysis.ipynb
INFO:gammapy.scripts.jupyter:

AttributeError in cell [22]

--SOURCE CODE: 
%%time
bkg_estimator = ReflectedRegionsBackgroundEstimator(
    obs_list=obs_list, on_region=on_region, exclusion_mask=exclusion_mask
)
bkg_estimator.run()
bkg_estimate = bkg_estimator.result
bkg_estimator.plot();

--TRACEBACK: 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<timed exec> in <module>()

~/git/gammapy/gammapy/background/reflected.py in plot(self, fig, ax, cmap, idx)
    346 
    347         wcs = self.finder.exclusion_mask.geom.wcs
--> 348         on_patch = self.on_region.to_pixel(wcs=wcs).as_artist(color="red")
    349         ax.add_patch(on_patch)
    350 

AttributeError: 'CirclePixelRegion' object has no attribute 'as_artist'
</pre>

**Comment by cdeil** [comment]
There was an API change in regions. Please update to regions v0.3. See #1758 .
