### ISSUE TITLE
Bullet list in HTML version of notebook formatting 

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1779]
At http://docs.gammapy.org/dev/notebooks/intro_maps.html#3.-Reading-and-Writing I see that the bullet list isn't properly formatted:

![screen shot 2018-09-11 at 09 10 36](https://user-images.githubusercontent.com/852409/45343922-98f01380-b5a2-11e8-8f2b-9db88b524780.png)

It appears OK on the version on nbviewer:

https://nbviewer.jupyter.org/github/gammapy/gammapy-extra/blob/master/notebooks/intro_maps.ipynb#3.-Reading-and-Writing

@Bultako - Could you please check if this is a bug in nbsphinx or with the markdown formatting in this cell?

I guess this means we should manually review the HTML version on docs.gammapy.org for all notebooks to check for similar issue?

I posted a new version last night.

**Comment by Bultako** [comment]
Fixed in https://github.com/gammapy/gammapy-extra/commit/959db18bccf968a2bdcf405b5be34774b85c349f

**Comment by cdeil** [comment]
Thanks!
