### ISSUE TITLE
Finish TS map implementation and add matching filter TS computation

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#18]
Currently there's the [ts_image](https://gammapy.readthedocs.org/en/latest/api/gammapy.detect.ts_image.html) function and [TSMapCalculator](https://gammapy.readthedocs.org/en/latest/api/gammapy.detect.TSMapCalculator.html) in `gammapy.detect`.

We should probably also add a command line tool to make TS maps ... here's a very old script as an example: https://gist.github.com/cdeil/58ced17e44d9e8946ea8

**Comment by adonath** [comment]
Mostly adressed in #215 and #234. Matched filters are still missing...

**Comment by cdeil** [comment]
I'm closing this old issue ... let's use #223 to keep track of what should still be done ...
