### ISSUE TITLE
Introduce RegionGeom and RegionNDMap?

### ISSUE THREAD

**Issue by adonath** [gammapy/gammapy#1805]
For image based analyses we now have `gammapy.maps` as the main data structure, which handles image data with arbitrary extra dimensions. For region based analyses we have the `Lightcurve` and `CountsSpectrum` classes, but nothing that combines it. The natural extension of the `gammapy.maps` data structures seems to introduce a `RegionGeom` and `RegionNDMap` to handle region based data. This way we can further unify the API and share the handling of extra axes between all our data structures. We also get the handling of extra axes such as event class for region based spectral and time analyses. This is no priority right now, but I think it should be kept in mind for Gammapy 1.0.

**Comment by AtreyeeS** [comment]
I was thinking exactly along these lines. This will also let us implement observation groupings very naturally. It would be nice to discuss this at the upcoming coding sprint.

**Comment by cdeil** [comment]
I'm +1 to unify the coordinates and axes and use that for IRFs and spectra also.

If the suggestion is to make a 1D spectrum a Map subclass, I'm naively -1.
Currently a Map has a `geom` and a `geom` has a `wcs`.

Maybe relaxing this and generalising the container class is possible, but it certainly would require an expert with several months of full-time development.

So I'm not sure if this is possible or the way to go.

@adonath - If you have a concrete proposal here, please write it up on on a slide or two or a page and present it in Madrid or later this year at a weekly Gammapy call.

**Comment by adonath** [comment]
In #2778 we introduced a `RegionGeom` and `RegionNDMap` class. While there is still a lot to be done in terms of I/O and documentation, we can use it now already to unify the API between 1D and 3D analyses.

Remaining ToDos are:
- Remove `CountsSpectrum` class
- Add documentation to `map.ipynb`
- Adapt `SpectrumDataset` API

**Comment by adonath** [comment]
`CountsSpectrum` was removed in #2815, we decided to not adapt the `SpectrumDataset` API for now.
