### ISSUE TITLE
Update tutorials/image_fitting_with_sherpa.ipynb

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1811]
Thanks to @Bultako we are very close to having `gammapy download` and clean and better datasets and data access.

One notebook that should be updated is `tutorials/image_fitting_with_sherpa.ipynb`, it currently accessess these files:
```
$ ack G300 tutorials/
tutorials/image_fitting_with_sherpa.ipynb
34:    "images['counts']    .write(\"G300-0_test_counts.fits\", clobber=True)\n",
35:    "images['exposure']  .write(\"G300-0_test_exposure.fits\", clobber=True)\n",
36:    "images['background'].write(\"G300-0_test_background.fits\", clobber=True)\n",
40:    "fits.writeto(\"G300-0_test_psf.fits\",images['psf'].data.value,overwrite=True)\n",
71:    "filecounts = os.environ[\"GAMMAPY_EXTRA\"] + \"/datasets/G300-0_test_counts.fits\"\n",
80:    "fileexp = os.environ[\"GAMMAPY_EXTRA\"] + \"/datasets/G300-0_test_exposure.fits\"\n",
81:    "filebkg = os.environ[\"GAMMAPY_EXTRA\"] + \"/datasets/G300-0_test_background.fits\"\n",
82:    "filepsf = os.environ[\"GAMMAPY_EXTRA\"] + \"/datasets/G300-0_test_psf.fits\"\n",

tutorials/notebooks.yaml
47:      - G300-0_test_background.fits
48:      - G300-0_test_counts.fits
49:      - G300-0_test_exposure.fits
50:      - G300-0_test_psf.fits
```

I think it would make sense to use the same example dataset that we use in `analysis3d.ipynb`, i.e. the 3 runs on the GC from CTA DC-1.

So the action items here are:
- [x] Write a Python script and generate FITS images for the DC-1 GC in gammapy-extra 
- [x] Change the tutorial notebook to use those.

One question is where to put the "derived" files.
- Subfolder `images` in https://github.com/gammapy/gammapy-extra/tree/master/datasets/cta-1dc
- Or at https://github.com/gammapy/gammapy-extra/tree/master/datasets/images
- Or in a new folder `cta-1dc-maps` with nice and derived 3D and 2D maps (using the ones produced as in `analysis3d.ipynb`?

@AtreyeeS or @registerrier - Do you have time for this this week?

It's not essential, but would be nice to have clean data and tutorials before the v0.8 release.

**Comment by Bultako** [comment]
I have made a temporal fix for this issue, moving the 4 files to a new folder `sherpaCTA`, so we can have this notebook not broken when we download it  with `gammapy download`

**Comment by cdeil** [comment]
@AtreyeeS - Do you have time for this tomorrow? Or should we postpone to v0.9? (this is not a blocker, and we have to ship v0.8 for the tutorial at the CTA meeting on Monday this weekend)

**Comment by cdeil** [comment]
Done by @AtreyeeS  in #1857 .
