### ISSUE TITLE
DataStore from file

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1819]
@lmohrmann @adonath - I have now produced an example for the case where the index files are in one FITS file: https://github.com/gammapy/gammapy-extra/tree/master/datasets/hess-dl3-dr1

There was discussion in  #1793 already, but the `from_dir` doesn't work well for that case, and also it has a bug - `Path.exists` is called as a static method, passing a string as `self`. The `make_path` utils function in Gammapy should be used to resolve env vars and create path objects instead. Also since no default HDU names are tried, I don't even think it's possible to load the `$GAMMAPY_DATA/hess-dl3-dr1/hess-dl3-dr3-with-background.fits.gz` via a DataStore method in a simple way?

Overall my recommendation would be (which I think is also what I suggested in #1793):

- Simplify `from_dir` again. The dir passed should be the dir to look for index files. The base_dir is something that's usually set in the HDU index file header (see spec) and can be completely different. Only in the case where it's not set we could default to the dir given for the index file location. I think that's the previous behaviour.

- Add a separate `DataStore.from_file` for the use case of having both index files in one FITS file, don't try to shoehorn that into `from_dir`. A `read` method could be used that checks if it's a file or a dir and then either calls `from_dir` or `from_file`. By looking for the default HDU names, the warnings from Table.read would not appear for users when everything is OK.

Of course, @lmohrmann and @adonath - If you don't want that, there are other ways to do it. But at the very least the `Path.exists(some string)` issue should be fixed and covered by a test.

It's a bit time-critical since @adonath  will do a tutorial at the CTA meeting on Monday and this needs to be ready. So either one of you does this today or tomorrow latest, or I could do it tonight. Let me know.

```
In [3]: from gammapy.data import DataStore
   ...: data_store = DataStore.from_dir(
   ...:     base_dir="",
   ...:     hdu_table_filename="$GAMMAPY_DATA/hess-dl3-dr1/hess-dl3-dr3-with-background.fits.gz",
   ...:     obs_table_filename="$GAMMAPY_DATA/hess-dl3-dr1/hess-dl3-dr3-with-background.fits.gz",
   ...: )
   ...: 
   ...: 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-efedae7e2a01> in <module>()
      3     base_dir="",
      4     hdu_table_filename="$GAMMAPY_DATA/hess-dl3-dr1/hess-dl3-dr3-with-background.fits.gz",
----> 5     obs_table_filename="$GAMMAPY_DATA/hess-dl3-dr1/hess-dl3-dr3-with-background.fits.gz",
      6 )

~/work/code/gammapy-docs/build/dev/gammapy/gammapy/data/data_store.py in from_dir(cls, base_dir, hdu_table_filename, obs_table_filename)
     83             obs_table_filename = base_dir / cls.DEFAULT_OBS_TABLE
     84 
---> 85         if not Path.exists(hdu_table_filename):
     86             raise IOError("File not found: {}".format(hdu_table_filename))
     87         log.debug("Reading {}".format(hdu_table_filename))

~/work/code/gammapy-docs/build/dev/gammapy/gammapy/extern/pathlib.py in exists(self)
   1445         """
   1446         try:
-> 1447             self.stat()
   1448         except OSError as e:
   1449             if e.errno not in (ENOENT, ENOTDIR):

AttributeError: 'str' object has no attribute 'stat'
```

**Comment by lmohrmann** [comment]
> Also since no default HDU names are tried, I don't even think it's possible to load the $GAMMAPY_DATA/hess-dl3-dr1/hess-dl3-dr3-with-background.fits.gz via a DataStore method in a simple way?

The default file names _are_ being tried, so that should work.

> The dir passed should be the dir to look for index files.

Agreed!

> I think that's the previous behaviour.

No, it's not, which was the main reason for #1793.

> it has a bug - `Path.exists` is called as a static method, passing a string as `self`.

Ups, sorry, I didn't know this must be called with a `Path` as argument. I can fix this but don't have time to implement anything else.

Let me know whether I should make a PR to fix the bug or whether you want to do something more fancy. In any case, I'd appreciate if the option to specify non-standard filenames for the obs and hdu files in the `base_dir` remains.

**Comment by cdeil** [comment]
@lmohrmann - Please send a PR to fix the `Path.exists` issue and then @adonath and I will see how to finalise this and v0.8 tomorrow.

@adonath and @lmohrmann - What do you think about adding `DataStore.from_file` as a convenience for the case of both index tables (and potentially, but not necessarily all data) bundled up in a single file? I don't think it would need any options, we would just require the default HDU names, although those could of course be exposed as well. That new file in gamampy-extra could be used for a test. This is what I'd then use from the HESS analysis tutorial (coming tonight).

**Comment by lmohrmann** [comment]
Here: #1820.

**Comment by cdeil** [comment]
The `from_dir` doesn't work properly; it reads the first BINTABLE for both index tables, there's no way for the caller to control this:
```
In [1]: from gammapy.data import DataStore
   ...: data_store = DataStore.from_dir(
   ...:     base_dir="",
   ...:     hdu_table_filename="$GAMMAPY_DATA/hess-dl3-dr1/hess-dl3-dr3-with-background.fits.gz",
   ...:     obs_table_filename="$GAMMAPY_DATA/hess-dl3-dr1/hess-dl3-dr3-with-background.fits.gz",
   ...: )
   ...: data_store.info()
   ...: 
   ...: 
WARNING: hdu= was not specified but multiple tables are present, reading in first available table (hdu=1) [astropy.io.fits.connect]
Data store:
HDU index table:
BASE_DIR: .
Rows: 630
OBS_ID: 20136 -- 47829
HDU_TYPE: ['aeff', 'bkg', 'edisp', 'events', 'gti', 'psf']
HDU_CLASS: ['aeff_2d', 'bkg_2d', 'edisp_2d', 'events', 'gti', 'psf_table']

Observation table:
Observatory name: 'N/A'
Number of observations: 630
```
There are other issues, the `base_dir` is never taken from the HDU index header.

I'll add a `from_file` now so that I can work with `hess-dl3-dr3-with-background.fits.gz`, and leave this issue open as a reminder to improve this some more for v0.9.

**Comment by cdeil** [comment]
I added a `DataStore.from_file` in ee44e971 .

I noticed that the question how to handle `base_dir` in the read methods might be complex than I thought. But this can be discussed later.

**Comment by cdeil** [comment]
I don't plan to work on this any more, so I'm closing this old issue. I'm not saying `DataStore` is great and final. New issues or PRs to improve the DataStore or any other part of `gammapy.data` in the future are of course welcome.
