### ISSUE TITLE
Update cta_sensitivity notebook to prod3 IRF files

### ISSUE THREAD

**Issue by Bultako** [gammapy/gammapy#1824]
This notebook is not part of the tutorials, but it is part of the documentation (it is referenced in other parts of the doc) 

<pre>
FileNotFoundError: [Errno 2] No such file or directory: 
'/Users/jer/DATA/GAMMAPY/cta/perf_prod2/point_like_non_smoothed/South_5h.fits.gz'
</pre>
Should we add a `cta/perf_prod2` to the datasets index file?
It is about 8MB in size.

**Comment by cdeil** [comment]
@Bultako - Please leave that notebook as-is for now (using GAMMAPY_EXTRA) and if needed mark it somehow to skip tests if that would cause problems in CI.

Putting this issue on v0.9.

> Should we add a cta/perf_prod2 to the datasets index file?

No.

I think that is something that @jjlk created with custom scripts while we were in the FITS IRF prototyping phase. We shouldn't ship those old files to users.

I'm not sure what to do here.

We could change the [SensitivityEstimator](http://docs.gammapy.org/dev/api/gammapy.spectrum.SensitivityEstimator.html) to work with full-enclosure IRFs and use this existing file: https://github.com/gammapy/gammapy-extra/blob/master/datasets/cta-1dc/caldb/data/cta/1dc/bcf/South_z20_50h/irf_file.fits

Or maybe there's an official IRF file in  http://www.cta-observatory.org/wp-content/uploads/2017/12/CTA-Performance-prod3b-v1-FITS1.tar.gz that works with the current SensitivityEstimator as it's written at the moment?

@jjlk - Thoughts?

**Comment by registerrier** [comment]
This issue is now solved with PR #2000 .
