### ISSUE TITLE
notebook light_curve broken

### ISSUE THREAD

**Issue by Bultako** [gammapy/gammapy#1826]
<pre>
KeyError in cell [3]

--SOURCE CODE: 
mask = data_store.obs_table["OBS_SUBSET_TAG"] == "crab"
obs_ids = data_store.obs_table["OBS_ID"][mask].data
observations = data_store.obs_list(obs_ids)
print(observations)

--TRACEBACK: 
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-3-666d9fa72671> in <module>()
----> 1 mask = data_store.obs_table["OBS_SUBSET_TAG"] == "crab"
      2 obs_ids = data_store.obs_table["OBS_ID"][mask].data
      3 observations = data_store.obs_list(obs_ids)
      4 print(observations)

~/anaconda/envs/gammapy-dev/lib/python3.6/site-packages/astropy/table/table.py in __getitem__(self, item)
   1220     def __getitem__(self, item):
   1221         if isinstance(item, str):
-> 1222             return self.columns[item]
   1223         elif isinstance(item, (int, np.integer)):
   1224             return self.Row(self, item)

~/anaconda/envs/gammapy-dev/lib/python3.6/site-packages/astropy/table/table.py in __getitem__(self, item)
    104         """
    105         if isinstance(item, str):
--> 106             return OrderedDict.__getitem__(self, item)
    107         elif isinstance(item, (int, np.integer)):
    108             return self.values()[item]

KeyError: 'OBS_SUBSET_TAG'
</pre>

**Comment by cdeil** [comment]
Fixed in 3219816c3cda80e0e21dbbfab9a6f87df3f3f78c .

**Comment by Bultako** [comment]
The same problem with spectrum_pipe..

<pre>
KeyError in cell [2]

--SOURCE CODE: 
data_store = DataStore.from_dir("$GAMMAPY_DATA/hess-dl3-dr1/")
mask = data_store.obs_table["OBS_SUBSET_TAG"] == "crab"
obs_ids = data_store.obs_table["OBS_ID"][mask].data
observations = data_store.obs_list(obs_ids)
print(obs_ids)

--TRACEBACK: 
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-2-bd251f91f378> in <module>()
      1 data_store = DataStore.from_dir("$GAMMAPY_DATA/hess-dl3-dr1/")
----> 2 mask = data_store.obs_table["OBS_SUBSET_TAG"] == "crab"
      3 obs_ids = data_store.obs_table["OBS_ID"][mask].data
      4 observations = data_store.obs_list(obs_ids)
      5 print(obs_ids)

~/anaconda/envs/gammapy-dev/lib/python3.6/site-packages/astropy/table/table.py in __getitem__(self, item)
   1220     def __getitem__(self, item):
   1221         if isinstance(item, str):
-> 1222             return self.columns[item]
   1223         elif isinstance(item, (int, np.integer)):
   1224             return self.Row(self, item)

~/anaconda/envs/gammapy-dev/lib/python3.6/site-packages/astropy/table/table.py in __getitem__(self, item)
    104         """
    105         if isinstance(item, str):
--> 106             return OrderedDict.__getitem__(self, item)
    107         elif isinstance(item, (int, np.integer)):
    108             return self.values()[item]

KeyError: 'OBS_SUBSET_TAG'
</pre>

**Comment by cdeil** [comment]
I'm running docs build and fixing that one also now.

**Comment by cdeil** [comment]
Fix tutorials/spectrum_pipe.ipynb in 80237083

**Comment by cdeil** [comment]
Added mention of  light_curve tutorial in docs/tutorials.rst overview page in  e43ec035
