### ISSUE TITLE
git_commit in setup.cfg

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1828]
@Bultako - Can we get rid of the `git_commit` key in `setup.cfg`?

Why not import and use `gammapy.version` to get the version number, like we do in other places of the docs build?

It's hard to remember to change the version number there, in addition to `setup.py` when making a release.

And I'm not sure what's happening here while I'm trying to make the docs build for the stable version:
https://gist.github.com/cdeil/0d504416f43da5df691a5855b42ce325

Did one of these commands change `setup.cfg` and the `git_commit` key back to master on disk?
```
python setup.py build_ext -i
time make docs-all
```

**Comment by cdeil** [comment]
So this isn't used?

https://github.com/gammapy/gammapy/blob/35dd67beebe6acc42828f07d5546a93ba16792c1/setup.cfg#L36-L38

If so, can you please delete it?

**Comment by Bultako** [comment]
umm..
actually, this needs to be there because it is used by `utils.docs.py` script that is called by SphInx.. I could move this key to somewhere else or write a comment there saying that the value is set on-the-fly by `make docs-all`?

**Comment by cdeil** [comment]
I see: it's used to generate the link to binder:

https://github.com/gammapy/gammapy/blob/e017d20e2045212c761cb986a09b10775c37142d/gammapy/utils/docs.py#L128

And the weird issue I saw where `setup.cfg` was modified when running the docs build happens here:

https://github.com/gammapy/gammapy/blob/c1a5f881577dedc74fe2b33fbb5b3b5251d3bc31/gammapy/utils/tutorials_process.py#L41

---

Overall my preference would be to remove that complexity completely, and remove the link to Binder from the generated HTML docs.

Instead I would propose to add a "try it in your browser" button on http://gammapy.org/ similar to how it's at http://jupyter.org/ .

This completely de-couples Binder from the rest of our docs / release process, and it becomes something that we can update at times or our choosing to a stable version of our choosing (usually a day after the release to the next stable version).

@Bultako - What do you think?

If you want to keep the Binder links in the docs, the setup would have to be simplified somehow (not a second version the maintainer needs to set, scripts should never write to `setup.cfg`, that should be something that's just edited manually by the maintainer and read by the build.

**Comment by Bultako** [comment]
It is like this how things happen right now.

* When building dec docs it is just `make docs-all` command.
* If building stable versions it is just `make docs-all release=v0.8`
* The values edited manually in `setup.cfg` are the ones used when doing the building process with `python setup.py build_docs` or with Sphinx commands. We would like not to edit these values manually in the file but pass them to our `make docs-all` command, so in principle we will *never?* edit these values in the file but need them there if we do not want to follow the `make docs-all` process. I could write a comment in the file to explain this.

**Comment by Bultako** [comment]
> Re: Binder links from docs

We can update the dev docs and also the docs for old releases anytime, with links to other binder versions or remove them completely if we want. The docs are not tightly coupled to Gammapy repo or Binder. The point is to decide if we want to keep these links in the docs or not, but that's not a technical issue.

**Comment by cdeil** [comment]
But today to fix the binder links after the release, you had to manually back-port a patch on top of the v0.8 tag. I don't thinks this is exceptional, this is a complex cloud service in beta and things will change from time to time and also we will make mistakes like I did today when making the release.

It's just more pleasant to be able to make commits in https://github.com/gammapy/gammapy-webpage/ to update conda env and binder setup and never having to re-run and go back to the docs build.

**Comment by Bultako** [comment]
I agree that Binder is in beta and things may or will change from time to time. It's easy to completely remove binder links from the dev docs, a few more steps to from old docs, but I don't think they are complex steps. 

It's a tradeoff, should we keep these links knowing they could break at some moment or keep them and provide an straight-forward access from the docs.. I do not have the distance to make an unbiased decision on this, I don't know either if Binder is used or useful..

**Comment by cdeil** [comment]
@Bultako - as you probably noticed from my comments above, I'm -1 to keep the these versioned binder links coupled to the Sphinx docs build. I think it's too complex and hard to maintain, and we should focus only on code developments, not configuring and maintaining a cloud service.

I expect that others in CTA will set up a Jupyter cloud service for CTA and install Gammapy there in the near future. When that appears, we can just link to it from http://gammapy.org/ next to the link we have to the Binder we from the Gammapy team set up and maintain at the moment.

@Bultako - Don't get me wrong. I very much appreciate all the work you have done, and I think having Binder working is a great feature and will be used a lot for tutorials. I just think we should put it more "on the side", not integrated into our docs build to keep things for Gammapy devs and future release managers as simple as possible.

For me, this is the only remaining open point before finalising #1419 and bringing it for an official vote and resolving it with the Gammapy coordination committee.

@registerrier @adonath @Bultako  - Please comment / vote

**Comment by Bultako** [comment]
Solved in #2212
