### ISSUE TITLE
Background computation in MapMaker

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#1830]
I think there is a problem with the background computed in MapMaker.  The number of predicted background events varies with the number of energy bins, and is abnormally large for a single bin. This makes making images with one energy bin very weird. Do you think this is an issue, @registerrier , @cdeil 
For ex: 

`for n in range(2, 15):`

    energy_axis = MapAxis.from_edges(
        np.logspace(-1., 1., n), unit="TeV", name="energy"
    )
    geom = WcsGeom.create(
        skydir=(0, 0),
        binsz=0.02,
        width=(5, 5),
        coordsys="GAL",
        proj="CAR",
        axes=[energy_axis]
    )
    maker = MapMaker(geom, offset_max=4. * u.deg)
    maps = maker.run(obs_list)
    maps=maker.make_images()
    print(maps["background"].data.sum())`

prints `4558460.5
434145.5
203798.08
142040.11
112685.08
105752.22
98714.52
93384.5
88870.47
82596.164
86333.77
85923.91
85119.94`

The number of source counts is constant at `85983.0`

**Comment by cdeil** [comment]
@registerrier - Can you please have a look and try to resolve this with @AtreyeeS ?
Or maybe @JouvinLea could also have a look at this with you next week in Madrid.

(Should we introduce a "Madrid" milestone or label for things we want to work on that week? If yes, please go ahead.)

I don't know if the issue is in the else clause in:
https://github.com/gammapy/gammapy/blob/f6fe37db6aab7969e10c029b29da158bb97b077f/gammapy/cube/background.py#L11
but generally I think maybe we should not have a "double energy grid" in the MapMaker, but only offer the input energy grid as the single option, and then make it convenient to integrate, i.e. sum over groups of bins, on any map. This would avoid duplicaing similar integration code for background and predicted counts.

**Comment by registerrier** [comment]
Without testing I would say that the default option `n_integration_bin=1` in background.py is the likely issue here.

**Comment by cdeil** [comment]
@AtreyeeS - If you have time to work on this, a good course of action would be to replace this test case:

https://github.com/gammapy/gammapy/blob/6370271360cbf02cff6878f6956f8808b8d69d7f/gammapy/cube/tests/test_background.py#L15-L18

with something very simple where we know the expected answer, e.g. a background IRF filled with a step function or power-law, similar to what we do here:

https://github.com/gammapy/gammapy/blob/master/gammapy/irf/tests/test_background.py

The method implemented for the `n_integration_bins=0` case should be value at center times bin width, and for `n_integration_bins>=1` evaluate at new grid points and power-law integral approximation.

Maybe everything is OK, and you're just assuming that background will come out OK with super large energy bins. This is not the case; to get a background image you have to first compute a background cube with reasonably small energy binning (e.g. 5 per decade) and then sum over the energy axis to get the background image.

But the tests should still be improved to have a test case where we know what should come out, to be certain the implementation is OK.

**Comment by AtreyeeS** [comment]
> @AtreyeeS - If you have time to work on this, a good course of action would be to replace this test case:
> 
> [gammapy/gammapy/cube/tests/test_background.py](https://github.com/gammapy/gammapy/blob/6370271360cbf02cff6878f6956f8808b8d69d7f/gammapy/cube/tests/test_background.py#L15-L18)
> Lines 15 to 18 in [6370271](/gammapy/gammapy/commit/6370271360cbf02cff6878f6956f8808b8d69d7f)
>  @pytest.fixture(scope="session") 
>  def bkg_3d(): 
>      filename = "$GAMMAPY_EXTRA/datasets/cta-1dc/caldb/data/cta/1dc/bcf/South_z20_50h/irf_file.fits" 
>      return Background3D.read(filename, hdu="BACKGROUND") 
> with something very simple where we know the expected answer, e.g. a background IRF filled with a step function or power-law, similar to what we do here:
> 
> https://github.com/gammapy/gammapy/blob/master/gammapy/irf/tests/test_background.py
> 
> The method implemented for the `n_integration_bins=0` case should be value at center times bin width, and for `n_integration_bins>=1` evaluate at new grid points and power-law integral approximation.
> 
> Maybe everything is OK, and you're just assuming that background will come out OK with super large energy bins. This is not the case; to get a background image you have to first compute a background cube with reasonably small energy binning (e.g. 5 per decade) and then sum over the energy axis to get the background image.
> 

Yes, I suspect so as well. Trying to understand

> But the tests should still be improved to have a test case where we know what should come out, to be certain the implementation is OK.

**Comment by registerrier** [comment]
There is a misunderstanding on how `MapMaker`is working and how globally one should perform map creation. 
I think the code should do what the user thinks it supposed to do. In this case, the default behavior should be that it produces a background map adapted to the input binning. The choice of the integration step should be made inside `MapMaker` or even in `Background3D` depending on the input reco energy binning (e.g. to ensure a sufficient sampling per decade). 
The option of having only f(E)*dE should possible but not the default one. It is a bit absurd to ask the user to make cubes with 15-20 energy bins in reco energy if he only wants a few.

**Comment by cdeil** [comment]
@AtreyeeS @registerrier - Close?

Alternatively: what's the proposed action item here?

**Comment by AtreyeeS** [comment]
I propose we don't close it now. As discussed in Madrid, I will implement a modified `MapMaker` which will internally decide an optimal binning in such cases, and then do a `group_over_axes()`. I will do this once the HESS meeting is over.
