### ISSUE TITLE
Broken link in tutorials

### ISSUE THREAD

**Issue by Bultako** [gammapy/gammapy#1839]
I have found that the link *Image analysis with Gammapy (individual steps)* in the [tutorials index page](http://docs.gammapy.org/dev/tutorials.html) is broken. It is pointing to a notebook *image_analysis.ipynb* that does not exist.

Should this notebook be recovered somehow or should we remove the link?

**Comment by cdeil** [comment]
That's this notebook: http://docs.gammapy.org/0.7/notebooks/image_analysis.html

Please remove the link.

This was intentionally removed a few months ago, to push the SkyImage removal through.

**Comment by Bultako** [comment]
Ok. 
Fixed in https://github.com/gammapy/gammapy/commit/84dc9a3acb7cbec2af701b5ab160e50ed61ac144, https://github.com/gammapy/gammapy-docs/commit/4fe0416da5cf4bd18ba01eafdf918f74f23f322c and https://github.com/gammapy/gammapy-docs/commit/5753526dd4f233c47b3751570e252a6ec7a02924
