### ISSUE TITLE
Additional parameter for not plotting legend in ReflectedRegionsBackgroundEstimator.plot()

### ISSUE THREAD

**Issue by IAMinaya** [gammapy/gammapy#1847]
Hi! This is just a aesthetic suggestion: when the number of selected events for the analysis is "large" and ReflectedRegionsBackgroundEstimator.plot is used, the legend in the plot becomes extremely large, as shown in this image:

![legend_issue](https://user-images.githubusercontent.com/43816221/46413770-94d69200-c719-11e8-9881-159808e1560d.png)

This could be easily fixed just adding an additional parameter to plot(), something like this (suggested new content written in bold in the comments below the code block):

https://github.com/gammapy/gammapy/blob/5a9027d99f814dafcd8239cb65add438528c803b/gammapy/background/reflected.py#L333-L388

adding in line 333: 
def plot(self, fig=None, ax=None, cmap=None, idx=None, **legend=True**):

adding in line 342:  
**legend: bool, optional
Enable/disable legend in the plot, default: True (legend is plotted).**

adding in line 386:
**if legend:**
ax.legend(handles=handles) 

With this small change the legend could be easily disabled so the plot wouldn't be so "ugly" in cases like mine... 

Thanks!

UPDATE: Just before submitting this issue Catherine told me a trick to avoid this through the `ax.legend().set_visible(False)` command... But even knowing that, it could be (maybe) a good idea to put it directly in the function instead of writing extra lines using matplotlib features, since this is kind of common issue...

**Comment by Bultako** [comment]
It makes sense to me.

@IAMinaya 
Because you know how to deal with this, you could do a PR and close this issue when fixed and PR merged.

**Comment by cdeil** [comment]
Sounds good. Since it's common to have many observations, I'd even suggest `legend=False` as default.

**Comment by registerrier** [comment]
Done by @IAMinaya in PR #1870 . Closing issue.
