### ISSUE TITLE
Add Scipy as core dependency?

### ISSUE THREAD

**Issue by adonath** [gammapy/gammapy#1863]
Currently `scipy.interpolate.interp1d` is used in the `MapAxis.coord_to_pix()` and `MapAxis.pix_to_coord()` methods. Now that we've made `Map` our core data structure, `scipy` has basically become a core dependency, which is not what we planned to have. So I guess we should replace it by `numpy.interp` and add the extrapolation to lower and higher values ourself? Any other ideas how to avoid the `scipy` dependency? Maybe it does not matter as we also depend on scipy in other Map method such as `.convolve()` or `.smooth()`?

**Comment by cdeil** [comment]
@adonath - I think it's fine to have scipy effectively as a core dependency for now. Suggest to not base decisions whether to use numpy or scipy for now on this concern. I don't think we had a single case where a user explicitly had an installation issue with scipy.

Basically our philosophy at the moment (and maybe long-term) is that Gammapy install requires this:
https://github.com/gammapy/gammapy/blob/c9838d4296c6c83a6fddd3dc62f812d3cb060346/setup.py#L106-L111

But then scipy and soon pyyaml are also required to really use Gammapy for analysis.

That's a little annoying for developers, to have to do the delayed imports and `requires_dependency`.
Therefore, I'm 50:50 on putting `scipy` in `install_requires` for now, leaning a little bit to keep as-is.
@adonath @registerrier @woodmd @Bultako or anyone interested in this - Thoughts / votes on this question?

**Comment by Bultako** [comment]
I would add `scipy` to the core dependencies list in `setup.py` in case we cannot really get rid of it. What's the downside of having a bigger list of core dependencies? 

In the last coding sprint I had to explain how to install the whole bunch of dependencies with `pip install gammapy[extra]`. Maybe we should also re-think why and how important is to have different lists of core and extra dependencies, when at the same time we are advocating for conda virtual env installs. I would like to think that once `gammapy` will become stable there will be no difference in the behavior of the soft, if installing following one method or the other.

**Comment by cdeil** [comment]
Discussed with @adonath and @registerrier - decided to add `scipy` as core dependency for now, since we do use it for quite a few things (convolution, interpolation, soon optimisation) and it's needed for most analyses.

@adonath will update `install_requires` and https://docs.gammapy.org/0.8/install/dependencies.html and remove the `requires_dependency` in many tests.

**Comment by adonath** [comment]
Resolved by #1919.
