### ISSUE TITLE
Output errors on developer website notebooks

### ISSUE THREAD

**Issue by IAMinaya** [gammapy/gammapy#1875]
I guess that I know the answer, but just in case I prefer to notify this here... The [simulate_3d](http://docs.gammapy.org/dev/notebooks/simulate_3d.html) and the [Fermi-LAT data with Gammapy](http://docs.gammapy.org/dev/notebooks/fermi_lat.html) notebooks on the developer website (not on the 0.8 one) have some output errors. 

I guess that the /dev/ website notebooks are not up to date and will only be updated with the latest changes when the version is about to be released... but since this is my first week in Gammapy I'd rather to ask just to confirm if this is normal or if it is indeed something to be issued.

Cheers!

**Comment by cdeil** [comment]
@IAMinaya - Thanks for filing the issue!

We're still getting used to the new workflow of having to check and update the notebooks in PRs that change code. About these two broken notebooks, see #1868 and #1869 .
Should be fixed soon and then I'll build and push a new version of the dev docs.

**Comment by IAMinaya** [comment]
Roger that, thanks @cdeil !

**Comment by cdeil** [comment]
This issue is resolved. I pushed new dev docs for version `0.9.dev7620` just now.
(you might have to re-load the page two times, or explicitly clear your browser cache to get the new version)
