### ISSUE TITLE
Improve string capitalisation handling in FITS I/O

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1901]
This issue is triggered by PR #1897 by @AtreyeeS . Probably we should put that in soon and not spend much time on this now, so I'm opening this separate issue and putting it on the 0.12 milestone.

We should improve string capitalisation handling in Gammapy, especially in FITS I/O.

The question is where to use lower or upper case for header keys (and partly values) as well as column names, or where to support both on read.

This is a complex problem because probably already at the FITS reader level there are different cases where lower / upper is distinguished or treated the same - for that see https://github.com/open-gamma-ray-astro/gamma-astro-data-formats/pull/65#issuecomment-257879666 - that discussion should lead to a short entry summarising the situation, probably in the spec, not in the Gammapy docs.
The existing spec contains a mix of capitalisation, e.g. the IRF specs have upper-case column names, but the SED spec has lower-case column names. Maybe this inconsistency was introduced in https://github.com/open-gamma-ray-astro/gamma-astro-data-formats/pull/65 , maybe it was already present before, I'm not sure.

In the Gammapy read / write to FITS we usually only support either lower- or upper-case, following the spec. The exception to this is probably the map axis code, where I think both are supported on read, and I'm not sure exactly what happens on read / write, reviewing that would be also part of this task. Now in #1897 @AtreyeeS is adding support for lower-case in one of the IRF column names, but not the other columns, and not the other IRFs (e.g. AEFF_2D). We can put this in for now to support reading old HAP_FR FITS files, but overall this is not a good state to be in.

So the task here is for someone that also wants to get involved with the data format and spec discussions, and do the corresponding Gammapy coding (which is limited but tricky to figure out the best solution):
- [ ] Review of what we have in Gammapy and in the spec
- [ ] Make a proposal what (if any) changes to make and discuss, as a PR with adding a section in the Gammapy dev docs, describing in detail how it should work.
- [ ] Once we know what we propose from the Gammapy team, make a PR to the open spec proposing it for the standard.
- [ ] Make one or several small PRs with code changes to the IRF or other read / write methods in Gammapy.

Probably the best solution is to develop a strict standard without variants, and always use that on write, but for the read to be lenient at least for a while (a year or two) and keep supporting files that just have the capitalisation wrong (maybe emit a warning).

**Comment by registerrier** [comment]
This issue is part of larger refactoring of IO in gammapy. Closing.
