### ISSUE TITLE
Use model components instead of "amplitude" for TS computation?

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1916]
@adonath - I think we should remove the `Fit.sqrt_ts` method:

https://github.com/gammapy/gammapy/blob/d71e4692462dd17359488bad49a473949b423a5e/gammapy/utils/fitting/fit.py#L99-L115

It's problematic, because it relies on the fact that there's a single hard-coded parameter called "amplitude". That's not the case, e.g. `TableModel` doesn't have such a parameter, and often if there are several sources, there will be several parameters with name "amplitude".

It is used once in the spectral point computation here:

https://github.com/gammapy/gammapy/blob/d71e4692462dd17359488bad49a473949b423a5e/gammapy/spectrum/flux_point.py#L794

Concerning what to put instead: probably TS computations should be done by adding or removing model components instead of setting amplitudes to zero? I think that's how ctools does it, see [here](http://cta.irap.omp.eu/ctools/users/tutorials/howto/howto_ts.html) or [here](http://cta.irap.omp.eu/ctools/users/tutorials/howto/howto_advanced_python_fitting.html). There could also be some declarative scheme for models or parameters so that they can set their amplitude or norm to zero, although since then one usually has to restore I think it'll always be a bit messy and simply making a new model for the second hypothesis seems more general and better. It might not be easy, we will probably need an an API to remove model components, but basically that should be a one-liner removing the model component from the list. Now that we have a model base class, we should probably review other parts of the `gammapy.utils.fitting` API and just take `model` or `models` objects instead of `parameter` objects in some places.

@adonath - Can you take care of this as part of your work on spectral points, or at least remove the call to `Fit.sqrt_ts` and then I can remove that method or refactor it to be more general?

**Comment by adonath** [comment]
@cdeil I almost fully agree. The `Fit.sqrt_ts` method only exists for "historical" reasons, as it was used in the `FluxPointEstimator`. It should definitely be replaced by something more general. Yes, the correct approach is to add and remove model components to compute the TS difference, but right now this is not easily possible and we have to develop first the background model component and a uniform way to handle models with multiple components.

I need the functionality in the `FluxPointEstimator`, but even in the current state it is useful for a 3D analysis as well. I think this is reason enough to keep it as `Fit.sqrt_ts`, until we have something better in place. We could try to go fast and replace it this week, but let us better discuss this in a pair coding session.

**Comment by registerrier** [comment]
I think there is no general way to do delta TS computation, given the wide variety of possible models.  I would not include something public in `Fit` to do it and rather leave to the user the responsibility to do something meaningful.

**Comment by cdeil** [comment]
This is done. @adonath now computes this in the FluxPointEstimator and I removed the method from Fit.
