### ISSUE TITLE
Make tutorial how to use Gammapy with emcee

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1923]
We should add a tutorial notebook showing how to use Gammapy with [emcee](http://dfm.io/emcee). The interface to emcee is just the likelihood function for a given set of parameters, so hooking the likelihood in `SpectrumFit` and `MapFit` up to emcee is possible. The first task here is to "make it work" for one example, e.g. it could be the example from [simulate_3d](https://docs.gammapy.org/0.8/notebooks/simulate_3d.html) or [analysis_3d](https://docs.gammapy.org/0.8/notebooks/analysis_3d.html).

Once that is available, the next step would be to "make it right", i.e. consider the different options how to exactly do the interface, and to create a set of helper functions or classes in `gammapy.utils.fitting` for this. One example could be study what Victor did in [naima](https://naima.readthedocs.io/en/latest/tutorial.html) and consider doing something similar. Another example to look at would be [MCMC in Sherpa](https://sherpa.readthedocs.io/en/latest/mcmc/index.html), I think they couple their MCMC helpers to the Fit class. Another option could be to not put a lot of code in Gammapy, but just to show users with the tutorial how to obtain the fit results e.g. using `numpy.percentile` as in [the emcee tutorial](http://dfm.io/emcee/current/user/line/) or by calling `numpy.cov` to get a covariance matrix from the samples as shown [here](https://multinorm.readthedocs.io/en/v0.2/_modules/multinorm.html#MultiNorm.from_points).

If someone is interested in this task, but doesn't know about MCMC fitting yet, [this](https://docs.pymc.io/notebooks/getting_started) is an excellent tutorial introduction. It uses [pymc](https://docs.pymc.io/), which I think we can't use with Gammapy, because it requires that the full model is written as pymc objects. It gives a framework for priors etc which of course we would like to avoid to re-build in `gammapy.utils.fitting`, but I'm almost certain it's not possible to evaluate our likelihood with it, because all operations in the model and likelihood evaluation have to be coded in the backend in `Theano`, whereas we use `Numpy`. So this is just a good reference to learn about and explain MCMC fitting, and we can link to it from the Gammapy tutorial.

If some is interested in this task, please comment here.
Alternatively, I might take a stab at it in 2019.

**Comment by adonath** [comment]
@facero Is there any chance to get your tutorial notebook you wrote at the coding sprint in for v0.11?

**Comment by facero** [comment]
It is ready.
I was waiting for my other PR to be merged to use the simulate dataset
method.
Any news from Register?


Le ven. 8 mars 2019 à 11:55, Axel Donath <notifications@github.com> a
écrit :

**Comment by adonath** [comment]
@facero I just merged #2064 :-)

**Comment by adonath** [comment]
Addressed by #2077.
