### ISSUE TITLE
Sphinx build not emitting HTML?

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1931]
When I run `python setup.py build_docs`, I don't get any output, no `docs/_build/html` folder is create.

There are warnings, but the command runs through and claims to write the output in `docs/_build/html` at the end, so this is weird. See log [here](https://gist.github.com/cdeil/b8a97f0abf17d6164750e085975401fc).

@Bultako - can you reproduce the issue?

I'm using this env, switched to Python 3.7 a few days ago and haven't tried the docs build since:
https://github.com/gammapy/gammapy/blob/master/environment-dev.yml

I think the warnings in the log relate to what @astrofrog fixed here: https://github.com/astropy/sphinx-automodapi/pull/51
@astrofrog or @bsipocz  - To get the latest version, we have to update the `astropy-helpers` git submodule in Gammapy? Is there still a bot sending PRs for that, or is it a manual procedure?

**Comment by Bultako** [comment]
Yes, I can reproduce the issue with the Python3.7 environment.
On the other hand, works fine with Python3.6.

**Comment by bsipocz** [comment]
> To get the latest version, we have to update the astropy-helpers git submodule in Gammapy? Is there still a bot sending PRs for that, or is it a manual procedure?

I've tagged v3.1rc1 yesterday, but the bot will send an update once the final release is out.
Please note that helpers 3.0+ is python3 only, so please let us know if this is something that needs fixing in the 2.0.x series, too.

**Comment by cdeil** [comment]
Well, in Gammapy we cannot update to helpers 3.0+ then, since we still have to support Python 2.7, right?

Looks like we have astropy-helpers 2.0.6 at the moment, from
https://github.com/gammapy/gammapy/commit/fa2057a3766cad1d23c4a76f151ce39caa89301e

Does that mean we can't build docs with Python 3.7 and should change our dev env back to Python 3.6 until we drop the Python 2 support? Sigh.

**Comment by bsipocz** [comment]
Could you open an issue in the helpers? For this situation I suppose we need to backport a few stuff, but that should be doable.

**Comment by cdeil** [comment]
@bsipocz - I've opened https://github.com/astropy/astropy-helpers/issues/415 .

**Comment by cdeil** [comment]
Some update here, based on infos from @bsipocz.

The backport of the Sphinx-related fixes to the `astropy-helpers` v2.x branch will come in the next weeks. We could just wait for that and postpone v0.9.

But as far as I can tell, we do get good HTML docs, they just land in the `docs/docs/_build/html` folder. @Bultako or @adonath - could you try this please and confirm or deny if those docs are OK?
If OK, I think we could just release v0.9 as planned this week, this is not a real problem.

Also: I tried Python 3.6, and still see the same issue. So I don't think the issue is Python 3.6 vs 3.7 related, rather it has to do mainly with Sphinx version number.

**Comment by astrofrog** [comment]
Just to confirm this is definitely related to Sphinx version, I think 1.8.

**Comment by cdeil** [comment]
Actually, there is an issue. Search doesn't work in the Sphinx docs currently.

@Bultako - There is a JS error pointing to this line.

https://github.com/gammapy/gammapy/blob/c3b1acb2a885e80fef0d43db531ee4eee34f016c/docs/_static/gammapy.js#L6

This is what I see locally:

<img width="1010" alt="screenshot 2018-11-22 at 22 08 37" src="https://user-images.githubusercontent.com/852409/48921920-64061400-eea3-11e8-842c-86304b3295b5.png">

@Bultako - Is this a bug / issue in `gammapy.js` that you can fix? Or is it an issue that requires a change / fit in `astropy-helpers`?

**Comment by Bultako** [comment]
I would say Sphinx v1.8 has changed the way how links are built in the HTML code, so `gammapy.js` has to be modified accordingly to deal with the links in the tutorials.

Sphinx v1.8 also places the built HTML in a new `/docs/docs` folder, and throws tons of warnings that pollute the screen log. I would need some time to clean this new behavior. In the mean time I have pinned Sphinx version dependency to 1.7.9 in `environment-dev.yml` This version works fine with Python3.7 and places the final built in the right folder.

**Comment by cdeil** [comment]
@Bultako - Thanks! If fixing to Sphinx 1.7.9 resolves the issue for now, no need to investigate further. I think fixes will come via astropy-helpers in the next weeks. I'll try with Sphinx 1.7.9 now.

**Comment by cdeil** [comment]
I'm moving this issue to the v0.10 milestone.

Note to future self: the task here is to try and revert 5f2ced1895f51efe687fcdecb6394fad867c6e54 in January 2019, after astropy-helpers has been updates in Gammapy, to make the docs build work with Sphinx 1.8+.

**Comment by cdeil** [comment]
Fixed by @bsipocz in #1965 .
