### ISSUE TITLE
Add option for making images with one energy bin?

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#1935]
While using gammapy for classical 2D analysis, I find it quite necessary to be able to make images from 3D maps. This can be either 2D maps with `x` and `y` co-ordinates (eg: for use with sherpa) or maps with `energy` (single bin) and `x`, `y` (for use in gammapy). Right now, the `make_images()` does only the former, and it is a bit annoying to keep adding an extra dimension everytime.

I think we can add an option `keep_ebin` (`=False` by default?) here : https://github.com/gammapy/gammapy/blob/0ee6c8e1f599d80942d955d3e1d9314847476b05/gammapy/cube/make.py#L134

 and, if `True`, return images with one energy bin.

If this sounds reasonable @cdeil , @adonath I can put in a PR.

**Comment by cdeil** [comment]
Yes, I think that could be useful.

Since `MapMaker.make_images`  calls `Map.sum_over_axes` presumably the same option would appear there?

Maybe call the option `keepdims=False` because that's what it's called in [numpy.sum](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.sum.html)?

**Comment by adonath** [comment]
:+1:  for adding the `keepdims` option to `Map.sum_over_axes` and expose it on the `MapMaker.make_images()`.

**Comment by adonath** [comment]
The remaining action item here is to either extend the existing sherpa notebook or to write a second notebook to demonstrate a 2D image fit with Gammapy.

**Comment by adonath** [comment]
Resolved by #1989.
