### ISSUE TITLE
How to use compound astropy models in Gammapy?

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#195]
It looks like compound models will land in `astropy.modeling` soon and we'll have to figure out how to use them in Gammapy.

I've started to put some questions and use cases here ... at the moment all I have is questions:
http://nbviewer.ipython.org/gist/cdeil/78702a01020ba62d5e96

cc @adonath

**Comment by adonath** [comment]
For now we have our own model classes and we don't consider using astropy models for v1.0.

**Comment by adonath** [comment]
I think the initial question here, with the specific use of compound models for Gammapy is off the table. Will close the issue now, however the question of re-using Astropy model in Gammapy in general might come up again.
