### ISSUE TITLE
Introduce model parameter default min / max values?

### ISSUE THREAD

**Issue by adonath** [gammapy/gammapy#1959]
In the [Simulate 3D Notebook](https://docs.gammapy.org/dev/notebooks/simulate_3d.html) the fit converges to a negative sigma for the Gaussian. Given the parametrization of the model only relying on `sigma ** 2` this is mathematically a correct solution, but clearly not the desired result. To resolves this we could introduce default `min` and `max` values for parameters, where we think it makes sense.

In general I would try to avoid this as much as possible, because in some cases it can restrict the optimizer to find the statistically best result. E.g. when fitting with a fixed background model, a negative flux amplitude is a (statistically) correct result. And it contains the information that the background model is overestimated. The same holds for spectral indices or negative cut off values. In case of the Gaussian it is not controversial.

**Comment by Bultako** [comment]
@adonath 

> To resolves this we could introduce default min and max values for parameters, where we think it makes sense.

You mean the user passing the limits in the **optimize_opts to the `run` method?
If the most general use case is not to make this kind of fine-tuning I would prefer not to add new params in the gammapy code, and let the backend deal with the fine-tuning options.

**Comment by cdeil** [comment]
We could just set a `min` for `sigma`, but no `max` in the default model.

But I find it really surprising that MIGRAD sometimes jumps from sigma +0.3 deg to -0.3 deg for a strong and nice signal. Maybe our initial step sizes aren't good?

Probably once this issue is resolved / understood, this can be removed as well:

https://github.com/gammapy/gammapy/blob/e5dde5826cc296d990a0aed6538d7229d1bee941/gammapy/cube/tests/test_fit.py#L107

**Comment by adonath** [comment]
@Bultako Our current `Parameter` class has `.min` and `.max` attributes which can be set by the user like so:

```
from gammapy.spectrum.models import Powerlaw

pwl = Powerlaw()
pwl.parameters["index"].min = 0
```
These `.min` and `.max` values, if defined, are then passed to the optimizer back-end as additional info for the optimizer. Currently the default value of those `.min` and `.max` attributes are `np.nan`, The question is whether we should introduce more plausible default values, where it makes sense.

**Comment by adonath** [comment]
The action item here was to add a default minimum value of `min=0`for the sigma parameter of `SkyGaussian`. Resolved directly in master in https://github.com/gammapy/gammapy/commit/8ec6c2df21727ee797c2c44f4b1f3e0b3724e917.
