### ISSUE TITLE
Please mark tests that require remote access

### ISSUE THREAD

**Issue by olebole** [gammapy/gammapy#1960]
Hi,

I just wanted to create a Debian package from the 0.9 release. However, I get a failure in the tests, since our build environment is disconnected from the net:
```
gammapy/scripts/tests/test_download.py::test_cli_download_datasets FAILED [ 77%]
gammapy/scripts/tests/test_download.py::test_cli_download_notebooks FAILED [ 77%]
```

The marking could be done by the [pytest.remotedata](https://github.com/astropy/pytest-remotedata) module, as recently done by astropy/specutils#401.

Best

Ole

**Comment by cdeil** [comment]
@olebole - Does #1961 look OK?

Gammapy is still alpha software, so we're not doing bugfix releases so far. So this and any other fixes would land in the next Gammapy v0.10, which is planned for Jan 2019. Does this work for you?

**Comment by olebole** [comment]
I am completely fine with that, since I can add patches to the Debian package.

**Comment by cdeil** [comment]
@olebole - Thanks!

Let us know if you find any other issues during Debian packaging / testing.
