### ISSUE TITLE
Remove Python 2 support

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1963]
This is a reminder issue, that we should remove Python 2 support in Gammapy after the v0.10 release in January 2019. I'm putting this under the 0.11 milestone, but it should be done early in the 0.11 cycle, e.g. a week after the 0.10 release. Rationale and details are at the end of the PIG in #1278 .

**Comment by cdeil** [comment]
Mostly done in #2012 .

@adonath - I would like to change to `concurrent.futures.ProcessPoolExecutor` instead of `multiprocessing.Pool`. It's a little bit simpler / safer. OK?

@bsipocz - Now that Gammapy dropped Python 2 support (once #2012 is merged), should we update `astropy_helpers`? Can you send a PR or instructions in the coming days or weeks?

I think that's actually it. I would discuss / introduce some Python 3 features like using keyword-only arguments, and maybe f-strings if we bump the version requirement to Python 3 only later this year, a lot of our code base has to be cleaned and written still, so IMO going through all our function and method signatures or generally reviewing large parts of the codebase now to polish something isn't time terribly well spent. I wouldn't start using type annotations. PyCharm takes type info from docstrings, so duplicating type annotations in the signature in addition to the docstring doesn't help developers, I expect it would be annoying / distracting to start using type annotations now in Gammapy. This might very well change in the coming years, but for now those are my thoughts.

Of course, @adonath and anyone else - if you have any thoughts or suggestions, please leave them here and we'll discuss them one by one.

**Comment by adonath** [comment]
@cdeil Yes, of course you can change to the `ProcessPoolExecutor`. The `TSMapEstimator` code is tested with parallel processing, so if any issue comes up you will notice...

**Comment by cdeil** [comment]
I simplified the `super()` calls to Python 3 style directly in master in 084aef98 .

**Comment by Bultako** [comment]
We can also remove the pinned dependency in `nbsphinx` 
https://github.com/gammapy/gammapy/blob/888409c6b07ebe7266f890e77591192fb0b3caab/environment-dev.yml#L41

That was the las version supporting Python 2.7

**Comment by cdeil** [comment]
> We can also remove the pinned dependency in nbsphinx

Done in  8e084ca7

**Comment by bsipocz** [comment]
> @bsipocz - Now that Gammapy dropped Python 2 support (once #2012 is merged), should we update astropy_helpers? Can you send a PR or instructions in the coming days or weeks?

I think it may be easier to do it here manually (I'm not sure when the new helpers release will be done). But I'll definitely update the list for the scrupt and move gammapy to the python3 only lot.

**Comment by bsipocz** [comment]
PR is coming for the helpers in minutes, dropping python2 is always so exciting I want to be part of it :)

**Comment by cdeil** [comment]
Just for reference: more Python 3 updates by @hugovk in #2016 and by @bsipocz in #2017.

**Comment by cdeil** [comment]
I'm closing this issue. Pretty much done.
PR #2020 is still open, but not urgent.
