### ISSUE TITLE
Use of node types in Maps

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#1967]
This is a short guideline for the use of node-types in `maps`. I do not know whether it is useful enough to go in the main `gammapy docs`, so initiating as a discussion here for now.

The basic motivation behind having two different `node_types` is to be able to differentiate between differential and integrated maps, ie, whether the values are defined at a specific co-ordinates or by an integral between intervals, respectively. Physically, it does not make sense to interpolate on integrated quantities, so we should be careful to only interpolate when `node_type =center`. For the specific case of the energy axis, a thumb rule which we should follow are:

- True energy axis, `e_true` is usually in `node_type = center`
-  Reco energy axis, `e_reco` is usually in `node_type = edges`

Thus, 
-  `counts` and `background` maps, which are histograms between two energy bins, are always in `e_reco` and are  `node_type = edges`. 
- On the other hand, the IRFs are computed in `e_true`. So, `PSF`, and `exposure` maps should always be node centered.  
- Model computation should be carried out on `e_true` grids, and then, after convolution with the `edisp` give a `npred` map in `e_reco`. [ps: Currently, the `MapEvaluator` returns a `npred` map in `e_true`, which has to be addressed]

In fact, moving from `e_true` to `e_reco` always means a convolution with `edisp` (A diagonal one when none is specified). This also addresses the problem of squashing into an axis with one energy bin (eg: #1935); this can be done by an `edisp` convolution with only one bin in `e_reco`.

Also, but this is just my personal opinion; I think it might be a good idea to have some default choices of `e_true` in the analysis (eg: 10 bins per decade, or the binning in the IRFs, etc). I do not think most users will want to be bothered with `e_true` binnings. `e_reco` bins, of course, should be decided by the user depending on the science case.

@registerrier , @cdeil, @adonath : Does this sound good?

**Comment by adonath** [comment]
@AtreyeeS Thanks for this summary! I'll have to think about it again myself, before commenting in detail, but just one general thought: I think the practical difference between the node types becomes negligible, as soon as the bin size is small enough i.e. if the bin size is well below the instrument's PSF, energy or time resolution. I think we should have this in mind, when we continue with the discussion.

**Comment by adonath** [comment]
We've discussed at the coding sprint in Paris about this and decided the Gammapy code base should be reviewed for the use of `correct` maps types at least once. We should also document somewhere (at least in the developer docs) which node type to use for which quantity.

**Comment by adonath** [comment]
By now we have a very good distinction, between `energy` and `energy_true` (see https://docs.gammapy.org/0.18.2/irf/index.html#irf-axis-naming). However we still differ from the proposed scheme, as energy true axes are used with nod type "edges" as well. The main point for me here is to identify, where the distinction between "center" and "edges" is relevant. And In fact I think it's only relevant for "undersampled" data with large bin sizes. So I think we should provide users with default try energy binnings using the "center" node type, but we should not require it strictly. See also #2482.

**Comment by AtreyeeS** [comment]
>> So I think we should provide users with default true energy binnings using the "center" node type, but we should not require it strictly. See also #2482.

Fully agree

**Comment by adonath** [comment]
AS far as I can see the only remaining action item here is to provide default energy true axis with `node_type="center"`. I'll close this issue now and make a comment in #2482 to consider the corresponding node type.
