### ISSUE TITLE
SpectrumFit crash due to Minuit (0.8)

### ISSUE THREAD

**Issue by tstolarczyk** [gammapy/gammapy#1968]
Hello guys!
Using Gammapy 0.8 on Windows 10

Crash in Minuit when using SpectrumFit.
This is reproduced on a MacBook Pro from a colleague (@jjlk)

test notebook with error messages attached
test files are in Gammapy EXTRA

(Problem found when trying to use FluxPointEstimator)
[GPySpectrumFit-checkpoint-0.8.ipynb.zip](https://github.com/gammapy/gammapy/files/2653517/GPySpectrumFit-checkpoint-0.8.ipynb.zip)

**Comment by adonath** [comment]
@tstolarczyk Thanks for the report! Unfortunately the notebook you attached is empty...

Please note that the `FluxPointEstimator` has been reworked completely for Gammapy v0.9. So before you continue it would be useful if you could update to Gammapy v0.9 and see if the issue remains.

**Comment by tstolarczyk** [comment]
Sorry,  the correct file is attached now, and I also added the observation data.

[test-gammapy-SpectrumFit.zip](https://github.com/gammapy/gammapy/files/2653769/test-gammapy-SpectrumFit.zip)


Yes, thanks, I am aware of the modifications in 0.9 but I have serious problems installing it on my machine right now, and  I cannot make the test (yet)...

**Comment by adonath** [comment]
Just to confirm: the crash remains with Gammapy v0.9. I'll take a closer look now.

**Comment by adonath** [comment]
The issue here is that the `'rmf_obs23523.fits'` file, defining the energy dispersion is missing. Right now this silently passes when `SpectrumObservation.read()` is called (but there is a [TODO comment in the code](https://github.com/gammapy/gammapy/blob/master/gammapy/spectrum/observation.py#L404)). The energy dispersion is set to `None` and not applied, which leads to the broadcasting error later, when the fit is started. 

@tstolarczyk Do you have the  `'rmf_obs23523.fits'` file?

**Comment by adonath** [comment]
@tstolarczyk If you don't have the file and want to fit the excess spectrum you can do so with the `forward_folded=False` option:

```
from gammapy.spectrum import SpectrumObservation, SpectrumFit
from gammapy.spectrum.models import PowerLaw

filename = 'pha_obs23523.fits'
obs = SpectrumObservation.read(filename)

model = PowerLaw(
    index=2,
    amplitude='100 TeV-1',
    reference='1 TeV',
)
fit = SpectrumFit(obs_list=[obs], model=model, forward_folded=False)
fit.run()
print(fit.result[0])
```

**Comment by tstolarczyk** [comment]
Yes I have the file and it solves the problem. Thanks a lot !
