### ISSUE TITLE
Addition of a MapMaker specialized for IRF maps

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#1970]
An `IRFMapMaker` is required to perform IRF map creation. 
At the moment, we have a versatile `MapMaker` that is able to create `counts`, `exposure` and `background` maps. We need to include also the creation of the PSF and edisp maps. These IRFs can be computed only on a coarse grid to limit computing time and storage required and then interpolated before the modeling step on the expected geometries.   
To compute the stacked `PSFMap`and `EdispMap`, it is necessary to compute the `exposure` map simultaneously. We therefore need a specific `IRFMapMaker` to this. We cannot use distinct `PSFMapMaker` and `EdispMapMaker` because this would imply recomputing exposure in each maker. 
This addition will be performed in two PRs:
- Addition of `EdispMap` following a similar structure as `PSFMap`. We need to see how to limit code duplication between the two classes. responsible @registerrier.
- Addition of the `IRFMapMaker` to perform the map creation and stacking. responsible @AtreyeeS

**Comment by cdeil** [comment]
Suggest to develop the building blocks first, and then only to chain it later. Not sure if a separate IRFMaker class is needed, or if it's just very little code (see [here](https://docs.gammapy.org/0.9/api/gammapy.irf.IRFStacker.html) as example), it would be combined into one high-level class that basically scripts the data reduction part.

To be able to have less coupling, I think adding an `exposure` directly on the `PSFMap` and `EdispMap` should be considered. An example of what this looks like is here: https://docs.gammapy.org/0.9/api/gammapy.irf.EnergyDependentTablePSF.html

Yes, it's duplicating exposure information, but that's not really a problem IMO, the gain in flexibility to have more de-coupled objects and PSF / EDISP / background / exposure each can have their own geom is nice. One can just stack two PSF without needing to access other objects.

Usually from the higher-level class one would compute exposure first, and then interpolate from the exposure cube as needed in the IRF reduction. So `PSFMap` would take exposure as needed on init, it certainly shouldn't access AEFF or do I/O.

The alternative to have exposure outside and to pass it in to methods as needed is certainly also possible, it's a design question that's pretty fundamental to the data reduction part.

@adonath @registerrier @AtreyeeS - Thoughts?

**Comment by registerrier** [comment]
This is implemented in PR #2358 . Closing issue.
