### ISSUE TITLE
Make tutorial how to plot spectra and SEDs

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#198]
We should make a page in `docs/tutorials` or a notebook in `gammapy-extra/notebooks` that shows how to plot spectra and SEDs.

This is a starting point:
https://gammapy.readthedocs.org/en/latest/tutorials/crab_mwl_sed/index.html

In addition we should show
- how to compute and plot butterflies
- how to compute and plot residuals

**Comment by cdeil** [comment]
Here's a prototype implementation of how to compute butterflies with the `uncertainties` package:
https://github.com/gammapy/gammapy-extra/blob/master/experiments/butterflies.ipynb

It should be integrated properly into gammapy.spectrum and then also be hooked up to the Fermi catalog source spectra that @JonathanDHarris is working on in #341.

**Comment by cdeil** [comment]
@joleroi - Move to 0.6 milestone? Or do you have time for this in the next day or two? (I don't.)

**Comment by cdeil** [comment]
@adonath wrote this for Fermi spectra which is a great start:
https://gammapy.readthedocs.io/en/latest/spectrum/plotting_fermi_spectra.html

I'll keep this issue open for now, some further things I'd like to see:

- [ ] Plot a TeV spectrum from https://github.com/gammapy/gamma-cat (spectra will be available there in a day or two)
- [ ] Combined GeV, TeV spectrum plot example
- [ ] Use IPython notebook for this instead of Sphinx docs, so that people can more easily play around with this (e.g. on binder) and plot their favourite spectra?

I'm assigning this issue to myself, but any help is welcome!

**Comment by joleroi** [comment]
This is just about plotting, right? no fitting, and flux point computation?

**Comment by cdeil** [comment]
> This is just about plotting, right? no fitting, and flux point computation?

I think probably yes, for now.

Although once you have published GeV or TeV loaded, doing a chi^2 fit with Gammapy or Naima is the next step what lot's of people want, so at some point there should be a tutorial for that as well.

Maybe we should try to have several short notebooks / tutorials, instead of very long tutorials that do many things in sections?

**Comment by cdeil** [comment]
Moving milestone to 0.7 (I'll make the 0.6 release tomorrow)

**Comment by cdeil** [comment]
Closing this now. We already have a few tutorials showing how to plot spectral points and models.
