### ISSUE TITLE
Fix Windows install via environment.yml

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1980]
I noticed  that the install instructions we have don't work on Windows:
https://docs.gammapy.org/0.9/getting-started.html#install
```
curl -O https://gammapy.org/download/install/gammapy-0.9-environment.yml
conda env create -f gammapy-0.9-environment.yml
```

The problem is that the optional dependencies `sherpa` and `healpy` aren't available on Windows.

Probably there is some simple way to declare that those shouldn't be installed on Windows, e.g. as mentioned [here](https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#preprocessing-selectors):
```
sherpa # [not win]
```

I'll try this out and put some fix next week.

**Comment by Bultako** [comment]
Ok.
If the fix does not work, I guess we should add a specific `environment.yml` for Windows.
Do we have an easy way to test the `conda env create` on Windows? 
What about using CI Travis or Appveyor? I do not even know if it's possible..

**Comment by cdeil** [comment]
Selectors as in `meta.yml` from conda build don't work in `environment.yml`.
I've filed a feature request just now here: https://github.com/conda/conda/issues/8089

For now, I'll just add a note to the docs for Windows.

**Comment by cdeil** [comment]
Updated docs for Windows in 46c3a03f .
