### ISSUE TITLE
Update joint Crab dataset

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1981]
I added this a while ago: https://github.com/gammapy/gammapy-extra/tree/master/datasets/joint-crab

It is used a bit in documentation and tests:
https://github.com/gammapy/gammapy/search?q=joint-crab&unscoped_q=joint-crab

The joint-crab datasets are now final and publicly available here:
https://github.com/open-gamma-ray-astro/joint-crab 

The `data` folder has DL3 with 7.8 MB, and the `results/spectra` folder has reduced OGIP spectra with 708 KB.

@Bultako @adonath anyone interested - how should we handle this reference dataset in Gammapy?

Whatever we decide, it's not a lot of work, I can do it next week. But we should discuss a bit and agree first.

- Keep or remove this as a reference dataset?
- Both DL3 and reduced OGIP spectra?
- Put a copy in gammapy-extra, or directly access from https://github.com/open-gamma-ray-astro/joint-crab ?

One concrete suggestion: keep this as a reference dataset, have both DL3 and reduced OGIP spectra, and to remove the copy in `gammapy-extra` and copy directly from https://github.com/open-gamma-ray-astro/joint-crab into GAMMAPY_DATA from `gammapy-download`.

Thoughts?

**Comment by adonath** [comment]
:+1: for your suggestion to keep this as a reference dataset, remove it from gammapy-extra and directly access it from the joint-crab repo.

**Comment by Bultako** [comment]
👍 for @cdeil suggestion.
I assign this to myself, since I will be working in `gammapy-download` next week.

**Comment by Bultako** [comment]
Done in https://github.com/gammapy/gammapy-extra/commit/b5a6cbab76ce1348d2a49e426ccf0debef243cca and https://github.com/gammapy/gammapy-webpage/commit/2579cf5c7b0c15921895c4ab334b31704cc2c7b6

If you agree we can close this one.

**Comment by cdeil** [comment]
@Bultako - Thanks!

These need to be changed from GAMMAPY_EXTRA to GAMMAPY_DATA, no?
```
docs/spectrum/fitting.rst
99:    pha1 = gammapy_extra.filename('datasets/joint-crab/spectra/hess//pha_obs23592.fits')
100:    pha2 = gammapy_extra.filename('datasets/joint-crab/spectra/hess//pha_obs23523.fits')

gammapy/spectrum/tests/test_results.py
16:    filename = "$GAMMAPY_EXTRA/datasets/joint-crab/spectra/hess/pha_obs23592.fits"

gammapy/spectrum/tests/test_observation.py
24:    filename = "$GAMMAPY_EXTRA/datasets/joint-crab/spectra/hess/pha_obs23523.fits"
179:    path = "$GAMMAPY_EXTRA/datasets/joint-crab/spectra/hess/"

gammapy/spectrum/tests/test_fit.py
172:        path = "$GAMMAPY_EXTRA/datasets/joint-crab/spectra/hess/"
```

I was also thinking we ship the DL3 `joint-crab/data` to GAMMAPY_DATA to have some example data from the other IACTs for Gammapy tutorials and people to play around with. It's 8 MB and currently not used, so if you prefer to leave as-is and not ship this for now, that's fine too.

**Comment by Bultako** [comment]
Ok.
I think I've fixed it in https://github.com/gammapy/gammapy/commit/ad02be215f1b5e0a4231d92d799d52442a01fcf3

> I was also thinking we ship the DL3 joint-crab/data to GAMMAPY_DATA to have some example data from the other IACTs for Gammapy tutorials and people to play around with. It's 8 MB and currently not used, so if you prefer to leave as-is and not ship this for now, that's fine too.

Well, all datasets declared in the JSON file are shipped with `gammapy download datesets`, but when doing `gammapy download datesets` only those declared in the YAML `notebooks.yaml` are downloaded. I guess we can ship all the joint-crab datasets as it is now. 

Anyway more concerns of this kind will come up when trying to remove `$GAMMAPY_EXTRA`, and we will have to take some decisions at that time.

**Comment by cdeil** [comment]
@Bultako - Thank you!
