### ISSUE TITLE
Fix spectral model evaluate_error

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1983]
There's a new fail with `evaluate_error` for spectral models with Numpy master and uncertainties:
https://travis-ci.org/gammapy/gammapy/jobs/479299543#L2784

This is a reminder issue for myself to fix this (probably tomorrow).

As discussed previously offline, I'd also like to move the if/else or try/except out of `evaluate` and consistently only have uncertainties error propagation code in the `evaluate_error` methods. I might or might not add it to this PR to fix CI, depending on what the situation is there.

**Comment by cdeil** [comment]
The numpy dev build is gone (see #1997 ), so not sure if this issue was a fluke or is still present.

@adonath - assigning to you and v0.11. If you think it's worth your time to work on this, of course go ahead. If you think it's a blocker for v0.10 move it there and try to resolve it tomorrow. For me it's OK to leave this to v0.11 or even just close and see what happens with the next Numpy pre-release.

**Comment by adonath** [comment]
@cdeil I'm fine to postpone it to v0.11

**Comment by adonath** [comment]
The error is gone, so it was probably fixed upstream in numpy.
