### ISSUE TITLE
Background maps for non-radially-symmetric IRF

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1987]
@watsonjj - this is a description of what we briefly discussed yesterday. The TODO here should be resolved so that for non-radially-symmetric background IRFs (given by a `Background3D` class, the background sky map is filled correctly.

https://github.com/gammapy/gammapy/blob/e70d38e66c246093c3951c7e878a05fc9b92a153/gammapy/cube/background.py#L31

@lmohrmann wrote some code to do this for his work in HESS, and in #1475 already added utility functions that do the FOV to sky coordinate transformation, including test cases that are verified against the HESS software. Ideally those utility functions would be replaced and we'd use `SkyCoord` and `SkyOffsetFrame` from `astropy.coordinates` directly, but the test cases would be preserved. That's one possible PR.

The other task to actually get the feature @lmohrmann needs for the HESS analyses with Gammapy is to hook this up to the background map computation. The two relevant functions are `make_map_background_irf` and `MapMaker._make_background` here:
https://github.com/gammapy/gammapy/blob/d47188fdfcfd1af81aa633380490343690bde290/gammapy/cube/make.py#L236

Like we said yesterday, the final solution for coordinate handling in IRFs isn't clear yet. Concretely here you have for the first time the problem of having to deal with AltAz coordinates, and in `make_map_background_irf` you currently can't compute those because you don't have access to the observatory location and time. In `MapMaker._make_background` these are available from `self.observation` which is a [DataStoreObservation](https://docs.gammapy.org/0.9/api/gammapy.data.DataStoreObservation.html) object with properties `pointing_altaz` and `tstart` that you could use.

My suggestion for now would be that you create a tiny new class `FixedPointingInfo` above the existing but still unused [PointingInfo](https://docs.gammapy.org/0.9/api/gammapy.data.PointingInfo.html), or just create a `PointingInfo` with one or two rows, so that you have an object that contains the observatory location, time (use `tstart` for now) and pointing direction. Then pass this `pointing_info` to `make_map_background_irf` instead of the current `pointing` SkyCoord (see [docs](https://docs.gammapy.org/0.9/api/gammapy.cube.make_map_background_irf.html)), and keep doing the coordinate computations in that function, directly where the TODO is located.

@registerrier @adonath @lmohrmann  or anyone - do you think that's OK, or do you see a better way to get the feature now with limited coding effort?

@watsonjj - Note that there are definitions for FOV coordinates in the spec [here](https://gamma-astro-data-formats.readthedocs.io/en/latest/general/coordinates.html#field-of-view) (assume that Background3D IRF is ALTAZ aligned), and we have agreed on coordinate and axis names to use in Gammapy [here](https://docs.gammapy.org/0.9/development/howto.html#coordinate-and-axis-names). At least new code should use those conventions.

**Comment by lmohrmann** [comment]
No objections here. I can offer to have a look into replacing the current sky coordinate transformations by ones that make use of astropy utilities. Then someone else (@watsonjj, apparently?) could start working on implementing these in the background map computation.

**Comment by lmohrmann** [comment]
I've opened a PR that exchanges the current transformations with ones that use astropy utilities: #2009

**Comment by lmohrmann** [comment]
@watsonjj Have you started to work on implementing 3D background maps? Can you provide an estimate for when these will be available? I can also try to have a look at this if you don't have time now.

**Comment by watsonjj** [comment]
@lmohrmann I do hope to have a PR opened in the next week. I realise it's a fairly straight-forward task, which is why I'd like to use it to introduce me to gammapy. However, if my progress on this is delayed beyond another week, I will be happy for you to take over on it.

**Comment by registerrier** [comment]
Technically this requires that `MapMaker` takes as argument the `PointingInfo`. All IRFs being a priori defined in the FOV system (lon/lat or theta/phi), the conversion to FOV coordinates should be used for the `exposure`, the `PSFMap` and the `EDispMap`. 
Actually, one might introduce minimal change to the `make_map_background_irf`. And simply call it multiple times from the `Map_maker` for each time slice and then sum all maps.

**Comment by registerrier** [comment]
BTW, it terms of API, it might be practical if the `PointingInfo` has a `.to_fov_frame(skycoord, time)` method.

**Comment by adonath** [comment]
The remaining action item here is to implement the time averaging of the background IRF.

**Comment by cdeil** [comment]
> The remaining action item here is to implement the time averaging of the background IRF.

You mean to account for FOV rotation during a run?

Yes, maybe that should be added in Gammapy. But it's also possible that the choice is made that DL3 data is always given for short enough time intervals so that IRFs and also background can just be assumed to be fixed and no time-loop to fill background maps is needed in Gammapy.

I mean: before someone starts hacking on Gammapy to add code to do time stepping, a proposal should be made how exactly to do it and discussed a bit (e.g. in this issue), to avoid that someone spends time to implement something and then in code review or later it turns out it's not what we want.

I think the FOV rotation effects are pretty small, and implementing time stepping isn't really needed for any application at the moment, no?

**Comment by lmohrmann** [comment]
@cdeil 
I think I disagree here. The effect is not so small, I've made this plot that shows the relative difference between the background computed by Gammapy and by my code:
![map_diff](https://user-images.githubusercontent.com/15608734/54182484-e857c380-44a1-11e9-8231-8b081782e4ff.png)
I don't see the point of supporting a 3D background model and not implementing the transformation correctly. If you don't want to do this in Gammapy, then I think there should be an option to provide the background in RADEC (or FOV_RADEC) directly.

I can provide some code that I use to do this, although it's really not much more than dividing the run into time slices, doing the transformation for each slice, and sum up the results (I've discussed this with @adonath already on Slack).

Any other opinions?

**Comment by cdeil** [comment]
@lmohrmann - if you want to put this in Gammapy and @adonath and @registerrier agree - fine, go ahead!

I'm just saying there is the other option to have smaller time intervals at the DL3 level, for all IRFs, and then not to have to do time loops in IRF-related computations. That's e.g. what VERITAS does - they chunk their runs in 5 min intervals at DL3 export, to get better precision for all IRFs.

If that is a better solution then starting to introduce time loops in Gammapy is a bit of a sidetrack / added complexity. But maybe not really - if you make it a feature that can be turned on and off (or number of steps as parameter), then it'll be useful for the coming year to study HESS background models, so yes, if someone is willing to implement it, probably we should put it in.

The plot you show does look extreme, but really background with HESS beyond 2 deg FOV and the non-radial-symmetries aren't understood or stable (look different for different datasets), and because counts there are low showing a relative difference will always blow up noise and systematic effects that are overall small in counts.

**Comment by registerrier** [comment]
@lmohrmann I agree we should support the time integration at some point. We don't know a priori how IRFs/observations will be distributed, so a user should have the possibility to do this properly.

I guess for now we need to understand where the differences you obtain come from. Is it only time rotation of the FoV system or is it a bug somewhere in our projection?

**Comment by lmohrmann** [comment]
@registerrier 
That's not entirely clear to me yet. I'd say we will know once the transformation (it's not only a rotation I think, right?) is correctly implemented and I do another comparison ;-)

@adonath 
You said at some point that you might have time to have a go at this. Is this still the case? As I said, I'm happy to advise/provide code.

**Comment by adonath** [comment]
@lmohrmann What surprises me in the plot you showed is the rectangular shape of the feature in the residuals. It looks like the background model is only defined in the range `fov_lon = +- 2.5 deg`  and `fov_lat= +-2.5 deg`. The rectangular shape is created when the background model is evaluated and somehow extrapolated incorrectly beyond `>2.5 deg`. But this is just a guess...

Yes, I had some time during the coding sprint to work on this, but this week I'm busy with preparing the Gammapy release and PyGamme19. We're a little bit late with other features in Gammapy as well, so it might be an option to delay the v0.11 release and we take sometime during PyGamma19 to look into this...I'll re-discuss with Régis whether it's an option.

**Comment by lmohrmann** [comment]
@adonath 
Indeed, the model that I provide is only 5x5 deg, but this is something that I could fix.

Yes, we can sit together next week and implement this. If delaying 0.11 is not an option and we need a release version before 0.12 (not sure about this yet), maybe a release 0.11.1 would be a possibility?

**Comment by registerrier** [comment]
I have made some tests to quantify the difference between 2 background maps taking into account time rotation of the FoV system. 
I used a Crab observation and assumed a flat box like background to enhance differences. It seems to me the effect is really weak.

see the following note book : https://gist.github.com/registerrier/3f711b002ebfa36dcfdb01da4e27021c

**Comment by lmohrmann** [comment]
Indeed, not doing the transformation in time steps was not the major problem in the plot I pasted above. Nevertheless, I think some functionality to evaluate IRFs in time steps will eventually need to be added.

For now, there is also the option to provide the background in a RA/Dec-aligned system and pass a `SkyCoord` to `make_map_background_irf`, which is a solution that works for me at the moment.

**Comment by adonath** [comment]
I'm closing this issue, for the time averaged IRFs we should just open a new issue.
