### ISSUE TITLE
cli_download_tutorials options

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#2003]
The options (`src`, `out`, `release` and `modetutorials`) on `cli_download_tutorials` currently aren't processed, they are ignored:
https://github.com/gammapy/gammapy/blob/fc4603ec58bdbd25386c5c5eb2a9664cce93769b/gammapy/scripts/download.py#L86

We should either implement those options (probably by storing them on the click context to communicate with the other commands), move them to the `cli_download` group level, or remove them for that command altogether.

Most users will just use the default and it'll be OK, so I'm not considering this a blocker.
I will make the v0.10 release now, so please no edits today.
Let's discuss a bit how `gammapy download` options should be organised and then fix this vor v0.11.

**Comment by cdeil** [comment]
You're right it does work, e.g. here's a test I did locally for the `out` option:
```
(gammapy-dev) hfm-1804a:temp deil$ gammapy download tutorials --out /tmp/spam
INFO:gammapy.scripts.downloadclasses:Looking for notebooks...
INFO:gammapy.scripts.downloadclasses:Reading https://raw.githubusercontent.com/gammapy/gammapy/master/tutorials/notebooks.yaml
INFO:gammapy.scripts.downloadclasses:Content will be downloaded in /tmp/spam/notebooks-0.10.dev8114
Downloading files [==================================================] 100% 

INFO:gammapy.scripts.downloadclasses:Looking for scripts...
INFO:gammapy.scripts.downloadclasses:Reading https://raw.githubusercontent.com/gammapy/gammapy/master/examples/scripts.yaml
INFO:gammapy.scripts.downloadclasses:Content will be downloaded in /tmp/spam/scripts-0.10.dev8114
Downloading files [==================================================] 100% 

INFO:gammapy.scripts.downloadclasses:Looking for datasets...
INFO:gammapy.scripts.downloadclasses:Reading https://raw.githubusercontent.com/gammapy/gammapy/master/tutorials/notebooks.yaml
INFO:gammapy.scripts.downloadclasses:Reading https://raw.githubusercontent.com/gammapy/gammapy-webpage/gh-pages/download/data/gammapy-data-index.json
INFO:gammapy.scripts.downloadclasses:Content will be downloaded in /tmp/spam/datasets
Downloading files [==================================================] 100% 

*** You might want to declare GAMMAPY_DATA env variable
export GAMMAPY_DATA=/tmp/spam/datasets

(gammapy-dev) hfm-1804a:temp deil$ ls -lh /tmp/spam/datasets
total 0
drwxr-xr-x  24 deil  wheel   768B Jan 28 09:52 catalogs
drwxr-xr-x   7 deil  wheel   224B Jan 28 09:52 cta-1dc
drwxr-xr-x   4 deil  wheel   128B Jan 28 09:52 dark_matter_spectra
drwxr-xr-x   7 deil  wheel   224B Jan 28 09:52 ebl
drwxr-xr-x  12 deil  wheel   384B Jan 28 09:52 fermi-3fhl-gc
drwxr-xr-x   7 deil  wheel   224B Jan 28 09:52 fermi_3fhl
drwxr-xr-x   3 deil  wheel    96B Jan 28 09:53 gamma-cat
drwxr-xr-x   8 deil  wheel   256B Jan 28 09:52 hess-dl3-dr1
drwxr-xr-x   7 deil  wheel   224B Jan 28 09:52 images
drwxr-xr-x   3 deil  wheel    96B Jan 28 09:52 joint-crab
(gammapy-dev) hfm-1804a:temp deil$ ls -lh /tmp/spam/
total 0
drwxr-xr-x  12 deil  wheel   384B Jan 28 09:52 datasets
drwxr-xr-x  27 deil  wheel   864B Jan 28 09:52 notebooks-0.10.dev8114
drwxr-xr-x   3 deil  wheel    96B Jan 28 09:52 scripts-0.10.dev8114
```

This issue was based on a "Unused local variable" warning I saw in PyCharm for the `cli_download_tutorials` function. So click is doing some magic here, via the context decorator, right? Probably we can close this, but I would like to look at the `click` docs and see what the recommended pattern is for this. So changing label to "question" and assigning to me for v0.11.

**Comment by Bultako** [comment]
> So click is doing some magic here, via the context decorator, right?

From Click documentation:

<pre>
Sometimes, it might be interesting to invoke one command from another command.
You can use the Context.invoke() or Context.forward() methods.
They work similarly, but the difference is that Context.invoke() merely invokes 
another command with the arguments you provide as a caller, whereas 
Context.forward() fills in the arguments from the current command. 
</pre>

http://click.palletsprojects.com/en/5.x/advanced/#invoking-other-commands

**Comment by cdeil** [comment]
I see, your calling `ctx.forward`:
https://github.com/gammapy/gammapy/blob/fc4603ec58bdbd25386c5c5eb2a9664cce93769b/gammapy/scripts/download.py#L86-L90

If we stick with that implementation, we should probably put an annotation to shut up static code analysers:
```
$ pylint gammapy/scripts/download.py
...
gammapy/scripts/download.py:86:32: W0613: Unused argument 'src' (unused-argument)
gammapy/scripts/download.py:86:37: W0613: Unused argument 'out' (unused-argument)
gammapy/scripts/download.py:86:42: W0613: Unused argument 'release' (unused-argument)
gammapy/scripts/download.py:86:51: W0613: Unused argument 'modetutorials' (unused-argument)
```

I'll do this for v0.11.

**Comment by adonath** [comment]
The download command has been refactored and simplified in #4106.
