### ISSUE TITLE
Maintenance of versioned index files for datasets

### ISSUE THREAD

**Issue by Bultako** [gammapy/gammapy#2005]
We provide *versioned* lists of datasets through JSON index files listing the datasets needed for each version of Gammapy, as well as for the dev version. See [here](https://github.com/gammapy/gammapy-webpage/tree/gh-pages/download/data).

These index files are generated with a script https://github.com/gammapy/gammapy-webpage/blob/gh-pages/make.py placed in the `gammapy-webpage` repository. The datasets index file for the dev version of Gammapy is also placed in that repo, as you may see in the first link above. This is different to what we do with notebooks and example scripts index files, since they are placed as the YAML files in the folders `tutorials` and `examples` of the `gammapy` repository.

This means that the re-generation of old versions of these index files is not supported and what it is worst, it is not version-coupled with the `gammapy` repository. Note that, contrary to what we have with notebooks and example scripts, datasets are spread among different github repositories (most of the datasets in `gammapy-extra`), but not a single dataset lives in the `gammapy` repository. This does not prevent us from moving the index file generator `make.py` and the dev version of the index file to the `gammapy` repo so to have them version-coupled with the code base, and to be consistent with what we already do with versioned notebooks and scripts index files.

If I understand it well, contrary to what happens with notebooks and example scripts, the dataset files themselves are considered not to change, only the lists (index files) of datasets needed for each Gammapy version may change.

Thoughts?

**Comment by cdeil** [comment]
+1 to move this to the `gammapy` repo.

Now sure where it fits best. Maybe `gammapy/scripts/dataset_index.py` ? or on the side / not in the package in `dev/make_dataset_index.py`?

It's not very nice to store the auto-generated data index JSON file in the repo. But given that to make it one needs to have a few datasets / env vars locally to run the script (e.g. `JOINT_CRAB`), and we don't want every developer or dev version user to have to set all that up, I don't hink there's a choice really?

> If I understand it well, contrary to what happens with notebooks and example scripts, the dataset files themselves are considered not to change, only the lists (index files) of datasets needed for each Gammapy version may change.

In principle yes, dataset files should be stable. But in practice probably not in all cases. E.g. we are applying sometimes fixes to data files that we generate, and Fermi sometimes releases versions with fixes to their catalogs, and gamma-cat can change. Of course we could introduce versioning ourselves, e.g. make datasets / folders `joint-crab2` etc and remove `joint-crab`, but that's also not very nice, usually it's simpler and nicer to (rarely) update a given set of dataset files, no?

Luckily I think with the `gammapy download` scheme it doesn't matter. Because it just uses the index file, we can make any changes we like and it'll just work. We probably shouldn't point to Github URLs that contain `master`, only given versions identified by a tag or a commit hash?

**Comment by Bultako** [comment]
> Now sure where it fits best. Maybe gammapy/scripts/dataset_index.py ? or on the side / not in the package in dev/make_dataset_index.py?

I'm +1 to put it on the side.
I would also put the JSON file in the `dev` folder, possibly both files in a `dev/index-datasets` folder with a README?

> We probably shouldn't point to Github URLs that contain master, only given versions identified by a tag or a commit hash?

+1 to replace `master` by a commit hash in the URLs declared in the `make.py` script (and hence generated in the json files)

**Comment by cdeil** [comment]
I would suggest just `dev/datasets` as folder name.

**Comment by adonath** [comment]
@Bultako In this issue @cdeil suggest to point to a commit hash instead of master. Taking a look at #2042, it seem we still point to master. Do you have any plans to change this? Or do you plan to leave it as is?

**Comment by Bultako** [comment]
@adonath 

You're right, I thought of having the different data repositories (gammapy-extra, joint-crab, gamma-cat, fermi-lat-data, etc.) tagged with future gammapy versions (from v0.11 onwards) Hence, for every stable-version index-file in [here](https://github.com/gammapy/gammapy-webpage/tree/gh-pages/download/data) we would have links pointing to one of the tags and not to master. For already-existing old stable versions of these index files, I could replace master by v0.11 for example, but future ones will have the version-coupled tag. For the development version of the index file, I think it is ok having links pointing to master. 

Well, this has some non-automatic work tagging the different repos, and I remember we discussed it but I think we did not really agree on doing it or how to alleviate the task in every release. Moreover, we were not sure that the dataset files themselves would change so often, and we also discussed of adding new ones and/or declare the names in the script, instead of globing the folder content. I think we cannot escape to globing so easily, so I'm +1 to have the data repositories tagged, even if it needs some *manual work*.

If you agree, I could add a param *release* to the script that generates the index file to build the links with the value of this param instead of master.

**Comment by adonath** [comment]
Thanks @Bultako for the explanation. I'm not sure whether tagging all our data repos is really an option. Probably not, because in future there might ones which are not under our control. It is also weird to introduce release tags for repos, which are not really coupled to Gammapy.

I think this requires some more discussion. I'll move the milestone to v0.12 now.

**Comment by cdeil** [comment]
> I'm not sure whether tagging all our data repos is really an option. Probably not, because in future there might ones which are not under our control. It is also weird to introduce release tags for repos, which are not really coupled to Gammapy.

Exactly. This is not a good solution. IMO a goal is to have a solution where Github is only used for file hosting, but the Gammapy data solution isn't coupled to Github or git. Version-coupling between repos needs to be avoided in general.

**Comment by Bultako** [comment]
I'm afraid that as long as the datasets will be distributed in different storage spaces some kind of coupling will be needed among them if we want to group different versions of the datasets into single GAMMAPY_DATA versioned collections (described by the look-up index files). In this case we need a commit hash or a tag for each repo to build the links to the datasets.

We can also decide not to have the datasets versioned, but only the look-up index files which can be fine. We could think of only adding new datasets to new folders, instead of updating or removing the existing ones. The content of the dataset repositories will only grow with time because we do not care about versioning here but in the index files. In this case there's no need to use version-coupled commit hashes or tags for the links, but instead somehow we should avoid using file globing to build the look-up index files.

**Comment by cdeil** [comment]
> We can also decide not to have the datasets versioned, but only the look-up index files which can be fine. We could think of only adding new datasets to new folders, instead of updating or removing the existing ones.

Exactly. In my opinion this is fine, it's the solution we have.

Most datasets (e.g. HESS data release, joint Crab) are stable, no version number needed.

A few datasets (e.g. gamma-cat) are not stable. There we can have the version be contained in the URL that we point to.

So the index file solution that we have allows for both versioned and non-versioned datasets.
Suggest to use it in this way, and not do any further developments on dataset versioning or coupling between repos.

OK?

**Comment by Bultako** [comment]
I think we can close this issue.
We agreed on a solution of not having datasets versioned, but the index look-up files, and there's been no need to do it in a different way for the last six months.

Closing.
