### ISSUE TITLE
Fix name handling in SpectralModel.from_dict

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#2006]
The current `SpectralModel.from_dict` does this:

https://github.com/gammapy/gammapy/blob/f35d8805b0a7a806ffbe01baf99a02ef9a5ed0dc/gammapy/spectrum/models.py#L219-L227

Just now I was bitten by the `val.pop` part - the constructor method removes the name key from the dict that's passed, so trying to create another SpectralModel from that dict fails with a `KeyError`.

A quick fix would be to make a copy of the input dict on the first line.

But also the rest of this method isn't great - the `globals()` part means this is not extensible for user models - probably spectral models should have a "nice name" like "powerlaw" or something that's independent of the class name. That's a much larger question, how `to_dict` and `from_dict` fit into the larger picture of model serialisation.

@adonath - Assigning to you to decide how to process this. Maybe do the quick fix and close, and describe how serialisation and model registry should work in the models PIG (#1971).

**Comment by adonath** [comment]
Resolved by #2057.
