### ISSUE TITLE
Incorrect spectral error band?

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#2007]
We still have a spectral error band that's probably incorrect in sed_fitting_gammacat_fermi for the ECPL fit:

https://docs.gammapy.org/0.10/notebooks/sed_fitting_gammacat_fermi.html#Exponential-Cut-Off-Powerlaw-Fit

This was noticed and discussed a few times before, especially #1838, but also #1718 or #1778 .

😱 

I don't think we ever really understood what was going on. 

At least to me, the spectral error band plotted here looks more reasonable: 

https://docs.gammapy.org/0.8/notebooks/sed_fitting_gammacat_fermi.html#Exponential-Cut-Off-Powerlaw-Fit

---

Some notes:

There are `NaN` values in `dnde_errn`, one from the 3FGL catalog, one from the 3FHL catalog:
```
>>> print(flux_points.table_formatted)
e_ref        dnde         dnde_errn       dnde_errp   
 TeV   1 / (cm2 s TeV) 1 / (cm2 s TeV) 1 / (cm2 s TeV)
------ --------------- --------------- ---------------
 0.861       2.291e-12       8.705e-13       8.955e-13
 1.562       6.982e-13       2.204e-13       2.304e-13
 2.764       1.691e-13       6.759e-14       7.188e-14
 4.892       7.729e-14       2.401e-14       2.607e-14
 9.989       1.033e-14       5.063e-15       5.642e-15
27.040       7.450e-16       5.721e-16       7.260e-16
 0.014       9.288e-09       2.128e-09       2.343e-09
 0.032       2.777e-09       5.818e-10       6.572e-10
 0.087       2.335e-10       8.554e-11       1.055e-10
 0.274       6.411e-11       2.133e-11       2.697e-11
 1.000       9.188e-18             nan       4.034e-12
 0.000       1.798e-04       5.710e-05       5.566e-05
 0.001       2.171e-07             nan       1.689e-06
 0.002       2.528e-07       9.991e-08       1.058e-07
 0.005       2.654e-08       7.932e-09       8.936e-09
 0.032       1.274e-09       3.658e-10       4.237e-10
```
I think those data points are ignored in the stat function. Is that a good idea or should an error be raised for `NaN` error bars?

---

Comparing the v0.8 and v0.10 links above: the best-fit parameters and all covariance matrix entries are basically the same, apart from very small rounding errors.

So the problem is with version-dependent results from `uncertainties`, not with the covar estimation from MINUIT.

For reference, and to help debug, the numbers from `result_ecpl.model.to_dict()` are this:
```
{'parameters': [{'name': 'index',
   'value': 1.8763343736076483,
   'factor': 1.8763343736076483,
   'scale': 1.0,
   'unit': '',
   'min': nan,
   'max': nan,
   'frozen': False},
  {'name': 'amplitude',
   'value': 2.076183759227292e-12,
   'factor': 2.076183759227292,
   'scale': 1e-12,
   'unit': 'cm-2 s-1 TeV-1',
   'min': nan,
   'max': nan,
   'frozen': False},
  {'name': 'reference',
   'value': 1.0,
   'factor': 1.0,
   'scale': 1.0,
   'unit': 'TeV',
   'min': nan,
   'max': nan,
   'frozen': True},
  {'name': 'lambda_',
   'value': 0.08703226432146616,
   'factor': 8.703226432146616,
   'scale': 0.01,
   'unit': 'TeV-1',
   'min': nan,
   'max': nan,
   'frozen': False}],
 'covariance': [[0.002041914982893617,
   -1.507724453135016e-14,
   0.0,
   -0.001834819175490081],
  [-1.507724453135016e-14,
   1.6864740887874626e-25,
   0.0,
   1.8542517891958074e-14],
  [0.0, 0.0, 0.0, 0.0],
  [-0.001834819175490081, 1.8542517891958074e-14, 0.0, 0.0032559101999857817]],
 'name': 'ExponentialCutoffPowerLaw'}
```
One can reproduce the model and error band plot via:
```
m2 = ExponentialCutoffPowerLaw.from_dict(data)
print(m2)
```

Here's what I get for `evaluate_error`, it claims that the relative flux error at either 0.1 TeV or 1 TeV is 122.6, which is way too large, the data should contrain the model to a 10% or 20% relative flux error:
```
>>> m2.evaluate_error(1 * u.TeV) / m2(1 * u.TeV)
[1, 122.64986]
>>> m2.evaluate_error(0.1 * u.TeV) / m2(0.1 * u.TeV)
[1, 122.64982]
```
Probably this would make for a good number to assert on in a unit test?

@adonath - Can you reproduce the incorrect flux error at 1 TeV (do you agree it's impossibly large)?
Is this a bug in `uncertainties` or in how we use `uncertainties`?

**Comment by Bultako** [comment]
In a fresh clean `gammapy-dev` env (the one listed above) I cannot reproduce the issue. 

#-
I think this issue appears when we install others packages (not necessarily related with gammapy) in the environment, so we end up with a somehow *contaminated* env.

In my case I managed to reproduce the issue installing *nbsptripout* (`conda install -c conda-forge nbstripout`) in a fresh clean `gammapy-dev` env, like I said here:
https://github.com/gammapy/gammapy/issues/1838#issuecomment-439191864

It seems that installing this package changes the version of numpy.
```
System:

	python_executable      : /Users/jer/anaconda/envs/gammapy-dev/bin/python 
	python_version         : 3.7.0      
	machine                : x86_64     
	system                 : Darwin     


Gammapy package:

	path                   : /Users/jer/git/gammapy/gammapy/gammapy 
	version                : 0.11.dev8119 
	githash                : c6bfb5371a5a1682cea9aaf56ebedb3c42010a43 


Other packages:

	numpy                  : 1.15.4     
	scipy                  : 1.2.0      
	matplotlib             : 3.0.2      
	cython                 : 0.29.3     
	astropy                : 3.1.1      
	astropy_healpix        : 0.4        
	reproject              : 0.4        
	sherpa                 : 4.10.2     
	pytest                 : 4.1.1      
	sphinx                 : 1.8.3      
	healpy                 : 1.12.8     
	regions                : 0.3        
	iminuit                : 1.3.3      
	naima                  : 0.8.3      
	uncertainties          : 3.0.3 

```

**Comment by cdeil** [comment]
I'll try to extract a minimal testcase and pin this (uncertainties/numpy) version-dependent issue down.

**Comment by adonath** [comment]
Looking at https://docs.gammapy.org/dev/notebooks/sed_fitting_gammacat_fermi.html#Exponential-Cut-Off-Powerlaw-Fit, it seems the issue is (magically?) gone...

**Comment by adonath** [comment]
I saw this issue as well when working on #2023. Once I re-ran the fit, the problem was gone. It seems to me it's rather an issue with the fit convergence. I improved the starting values in #2023, which seemed to help.

**Comment by cdeil** [comment]
> It seems to me it's rather an issue with the fit convergence.

No. See description above how to reproduce an incorrect flux error directly starting with good values / covariance for an ECPL, without a fit or convergence issues being involved.

Of course there can be non-converging fits also, but I think that's a separate issue, the correct best-fit values & covariance matrix for this example is the one printed above.

I'm convinced this is a bug in `ExponentialCutoffPowerLaw.evaluate_error` that is present only for certain `uncertainties` versions.

The way to proceed here is to add a regression test for that part (not involving a fit), and then to pin down why the error occurs in `ExponentialCutoffPowerLaw.evaluate_error` and with which `uncertainties` versions, which will likely be time consuming, and might even become mute if we decide to not use `uncertainties` in Gammapy in the coming months, that's why I didn't work on this further.

**Comment by cdeil** [comment]
Related: #2255

**Comment by cdeil** [comment]
I added the ECPL example from above as a regression test in #2585 .
At the moment I don't see the issue, and most likely it's fixed.
Closing this old issue.
