### ISSUE TITLE
Search does not work in v.10 documentation

### ISSUE THREAD

**Issue by Bultako** [gammapy/gammapy#2010]
With the v.10 release, the documentation website has been updated accordingly.
https://docs.gammapy.org/

The search does not seem to work properly, it remains blocked and no results are provided.
I have rebuilt the docs locally and have no reproduced the issue.

@cdeil 
I would try updating Sphinx for next time when building docs. 

Moreover, I would also update the docs in https://docs.gammapy.org/dev, since they seem to be outdated wrt. fresh new v.10 release.

**Comment by facero** [comment]
So I was teaching a tutorial yesterday and today and since yesterday afternoon the search was not working. I'm pretty sure this was still v0.9 (when was v0.10 uploaded ?)
So I'm not sure whether the problem comes from v0.10 or from the doc website.

**Comment by Bultako** [comment]
Fixed in https://github.com/gammapy/gammapy-docs/commit/bae962b78d647d21c17140db77e8a3faa7955714 and https://github.com/gammapy/gammapy-docs/commit/b6c8cbe51bd6946f7cbdeea45ad2c9cacb05a99f.

**Comment by cdeil** [comment]
@Bultako - Thanks for fixing the issue!

So the problem was probably that I had a "bad" Sphinx version?
I have 1.8.2.
What do you have?

**Comment by Bultako** [comment]
@cdeil 
I've found this was a known issue for Sphinx versions<1.8.3
https://github.com/sphinx-doc/sphinx/issues/5460
