### ISSUE TITLE
Smoothing counts map (integer arrays)

### ISSUE THREAD

**Issue by facero** [gammapy/gammapy#2011]
Running the notebooks during the tutorial I just gave I saw a strange behaviour when plotting a smoothed simulated count map.
I used the notebook `simulate_3d.ipynb`.

When running the following cell and adding a plot: 
```
counts = rng.poisson(npred)
counts_map = WcsNDMap(geom, counts)
counts_map.smooth(width=0.1*u.deg).plot_interactive(add_cbar=True)
```

gives me the following plot:
![image](https://user-images.githubusercontent.com/8652898/51925673-db9a7700-23ef-11e9-8de3-ccd02b47c90c.png)

What happens here is that the `poisson(npred)` returned an integer array. Then when smoothing it all float values are truncated creating this stairs in the point source.

Modifying the cell to :

```
counts_map = WcsNDMap(geom, np.asarray(counts,dtype=np.float64) )
```

fixes the issue. I believed this should be fixed in the smooth function that should transform any input array to float64 before smoothing. 
If you agree I can implement this quick fix. 
Should we add a unit test to check that smooth always returns a float array ?

**Comment by adonath** [comment]
Thanks, @facero for reporting this issue! I noticed exactly the same issue ~1 week ago and already fixed it in https://github.com/gammapy/gammapy/commit/8b84fa3e97a0597caa2873e9291f48efbd8f187c, so it's already in for Gammapy v0.10.

If you'd like to add a unit test for this (maybe just one additional assert in [test_wcsnd.py::test_smooth](https://github.com/gammapy/gammapy/blob/master/gammapy/maps/tests/test_wcsnd.py#L459)), please go ahead!
