### ISSUE TITLE
TypeError from MapAxis.slice

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#2014]
I see this `TypeError`:
```
>>> from gammapy.maps import MapAxis
>>> axis = MapAxis.from_edges([0.25, 0.75, 1.0, 2.0])
>>> axis.slice(slice(1, 3))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/deil/work/code/gammapy/gammapy/maps/geom.py", line 583, in slice
    nodes = self._nodes[(idx,)]
TypeError: list indices must be integers or slices, not tuple
```

I noticed this when I tried to do a bit of cleanup and remove the `np.array` calls here, which I thought were superfluous:
https://github.com/gammapy/gammapy/blob/888409c6b07ebe7266f890e77591192fb0b3caab/gammapy/maps/tests/test_geom.py#L17

Passing a `slice` object to the method and it erring with a TypeError complaining something is not a slice is pretty confusing. Can this be improved (made to work, or better error message) by adjusting `MapAxis.slice` or `MapAxis.__init__` to force required types on creation?

**Comment by adonath** [comment]
Resolved by #2060.
