### ISSUE TITLE
`GAMMAPY_DATA/fermi-3fhl-gc/` not found

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#2025]
I am a bit behind on the latest developments regarding tests and location of test files in gammapy.
After updating to the latest master in `gammapy` and `gammapy-extra` `analysis_3d` fails because "$GAMMAPY_DATA/fermi-3fhl-gc/gll_iem_v06_gc.fits.gz" does not exist. Similarly for many tests in `gammapy.data`. What should I do?

**Comment by adonath** [comment]
@AtreyeeS The test data has now moved to `$GAMMAPY_DATA` as well. To update the datasets just run the `gammapy download datasets` command again it will download all the missing data for the tests.

**Comment by AtreyeeS** [comment]
Thanks for the instant solution @adonath !
