### ISSUE TITLE
Add more checks in `DataStoreChecker`?

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#2041]
I came across this issue while testing the ongoing `HAP-Fr` fits production, but after discussions with @registerrier and @bkhelifi , it seems it is a good idea to add some checks within the science tools as well. It sometimes happen that some observations in the `hdu-index-table` have eventfiles, but not all the associated IRFs. This is exceedingly painful, because this loads the observation into memory, and then fails later during the data reduction/analysis stage. 

Initially I thought we should clean the `hdu-index` and get rid of such runs, but some people might still want such runs from diagnostic purposes or some special types of analysis. In such a case, perhaps we can add some checks within `DataStoreChecker` to only load observations for which all (by default) or some user-specified IRFs are present? If this sounds good, I can do it next week.
comments @adonath @cdeil

**Comment by cdeil** [comment]
What we do in HAP-HD is to have a two-step FITS export.

1. export all data for experts
2. export subset of good data for users

Then experts can do whatever they like, e.g. quality checks, you can have extra columns with quality or availability info in the index tables.
And users get the simple and clean and good-quality data.

Suggest you do the same for HAP-FR, no changes in Gammapy.

In the first HAP-HD FITS production we also distributed runs to users where some didn't have good IRFs. Even though we put a quality column in the obs index file, no-one remembered that and ran into the same problematic runs.

Would that work for you?

**Comment by cdeil** [comment]
@AtreyeeS - Close issue? Or what's the proposed action item in Gammapy?

**Comment by cdeil** [comment]
@AtreyeeS - if you feel an addition is really needed in Gammapy, please re-open.
