### ISSUE TITLE
Add 4FGL Fermi catalog

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#2055]
A first version of 4FGL is out:
https://fermi.gsfc.nasa.gov/ssc/data/access/lat/8yr_catalog/

It would be nice to have a source and catalog class similar to the existing ones in [gammapy.catalog](https://docs.gammapy.org/0.10/catalog/index.html).

I'm labeling this "package-novice", it's a nice task to get started with hacking on Gammapy.
A full implementation of data to Gammapy object mapping (spectral model, spatial model, spectral points, light curves) is quite a bit of work, several 100 lines of code.

A first implementation / PR doesn't have to contain all of that, things can be added in steps.
Probably the most used feature is spectral models.

**Comment by cdeil** [comment]
@kaoriinakashima - Suggest to start minimal and try to get this to work:
```
def test_4fgl():
    cat = SourceCatalog4FGL()
    source = cat["crab"]
    spectral_model = source.spectral_model
    print(spectral_model)
    1/0
```
Add that at the end of `gammapy/catalog/tests/test_fermi.py`, then run test via 
```
pytest gammapy/catalog/tests/test_fermi.py::test_4fgl
```
Then add catalog & source class in `gammapy/catalog/fermipy`, always after corresponding 3FGL class.
First version should have only `SourceCatalog4FGL.__init__`, and for the source you probably only need to write the `spectral_model` property, following the code in 3FGL.

**Comment by cdeil** [comment]
4FGL has been mostly implemented by @QRemy in #2448

I think it's ~ 1 day to finish it up. Let's do that.

@QRemy - you or me?

Here's what we have:
- https://github.com/gammapy/gammapy/blob/master/gammapy/catalog/tests/test_fermi.py
- https://docs.gammapy.org/dev/api/gammapy.catalog.SourceCatalogObject4FGL.html
- https://docs.gammapy.org/dev/api/gammapy.catalog.SourceCatalog4FGL.html

I see a TODO in the `lightcurve` method, that should be resolved.

Most things work:
```
from gammapy.catalog import SOURCE_CATALOGS
cat = SOURCE_CATALOGS["4fgl"]()
for source in cat:
    str(source)
    source.light_curve
    source.flux_points
    source.sky_model()
```
For the model creation, there's some units that we need to handle to avoid the warnings, and some FITS file missing for extended models:
https://gist.github.com/cdeil/5777ef39c3576be36dc3e05ba42ff781

There's https://docs.gammapy.org/dev/api/gammapy.catalog.SourceCatalogObject4FGL.html#gammapy.catalog.SourceCatalogObject4FGL.asso
but then another list of association columns:
https://github.com/gammapy/gammapy/blob/2d8aba04de9fb1c10baea928db891ef9757658e2/gammapy/catalog/fermi.py#L1340
That's present for all Fermi catalogs.
For 3FHL and 3FGL we also have `source_categories` doing some grouping:
https://github.com/gammapy/gammapy/blob/2d8aba04de9fb1c10baea928db891ef9757658e2/gammapy/catalog/fermi.py#L1405-L1411

How about removing most of this assoc-related code and tests (saving a few 100 lines of code) and leaving this to the user? (keep the name lookup also in assoc columns, but not more)

Another thing I would suggest to remove is the translation of int codes to str messages for the analysis issues via `flag_message`: https://github.com/gammapy/gammapy/blob/2d8aba04de9fb1c10baea928db891ef9757658e2/gammapy/catalog/fermi.py#L219-L241
This would save another few 100 lines of code (to print, and test).
At least I don't remember ever checking if those dicts are filled correctly for the various catalogs.
We could just print out the int codes and print a link to the paper where people can look that up.

@adonath @QRemy - Please comment on these questions what to keep or remove.

**Comment by QRemy** [comment]
Also v20 introduce the c suffix in the name for the confuse sources (possible spurious detection due to background) and the 2-month light-curves. I can make a PR to update  the version used, providing also the 2-month light-curves and solving the TODO.

Then I will make another one to cleanup the infos. I guess I can remove the `asso `attribute and use `source_name_alias`, and remove `source_categories` . The `flag_message` message is displayed only for 3FGL and 4FGL, they seem ok to me, that's nicer to have this info and its already implemented.

The file for LMC-Galaxy  seems to be there for me :
https://github.com/gammapy/gammapy-extra/tree/master/datasets/catalogs/fermi/LAT_extended_sources_8years/Templates

**Comment by cdeil** [comment]
I've updated the 4FGL to the latest v20 in 26dabe6949a4ab0091a9b61c25fa8d54e2e9f15d.
And I updated 2FHL to the latest v09 in b6f38f5f4.

**Comment by registerrier** [comment]
Now that we have merged #3241 , can we close this issue @QRemy  ?

**Comment by QRemy** [comment]
Yes, we will have to keep updating the catalog for the next data release(s) with at least the initial version and the last one but we can open a separate reminder issue for that.

**Comment by adonath** [comment]
Will close this now, for the update we can open a different issue.
