### ISSUE TITLE
Should MapAxis be sorted?

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#2061]
We need to decide if `MapAxis` needs to be sorted or if arbitrary values may be allowed. This is because the `coord_to_pix()` uses `scipy.interpolate.interpolate1d` which silently sorts the array before interpolation. 

To always ensure correct results, we can check if the nodes the are sorted. However, this option means that having discrete values for nodes, eg: MC id, will not be acceptable. 

If we want this to be allowed, then we need to make some changes and specify that some axes should not be interpolated.

**Comment by cdeil** [comment]
> coord_to_pix() uses scipy.interpolate.interpolate1d which silently sorts the array before interpolation.

Turn that sorting off, since it's never the right thing to do (data array gets out of sync with axis)?

I think for most axes (energy, time, ...) we can assume nodes are ordered, I wouldn't add a check / warning / error.

In Gammapy (and Python and most codes in general) adding input validation / error handling would be a huge task that adds thousands of lines of boilerplate code. I would suggest to basically assume input data is OK, and only add it  in rare cases where problems actually occur. (Did you have a bad input file?)

> However, this option means that having discrete values for nodes, eg: MC id, will not be acceptable.

Interesting. Would `coord_to_pix` every be called in an analysis with an MC_ID axis?
Maybe we can just leave as-is?
Or can you give a code snippet / test case that shows some behaviour that's wrong or undesirable?

**Comment by AtreyeeS** [comment]
Hello @cdeil ! We noticed this issue during the coding sprint (see: #2059 as well). 

> I think for most axes (energy, time, ...) we can assume nodes are ordered, I wouldn't add a check / warning / error.

Some users were creating a time axis on the fly, eg: taking times from different GRB triggers and concatenating them. This, when not done carefully, was creating a time axis not properly ordered, which pretended to work fine but gave very strange results which were difficult to debug later. So, I thought we should perhaps have some checks for the user.

> > However, this option means that having discrete values for nodes, eg: MC id, will not be acceptable.
> 
> Interesting. Would `coord_to_pix` every be called in an analysis with an MC_ID axis?
> Maybe we can just leave as-is?
> Or can you give a code snippet / test case that shows some behaviour that's wrong or undesirable?

Currently, map values can only be floats. If we are allowing MC_ID as an axis, then why not event classes/types with string names? This will need some changes in the `MapAxis` class, which we were wondering may or may not be worthwhile

**Comment by cdeil** [comment]
For reference: I see [scipy.interpolate.interp1d](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.interp1d.html) has an `assume_sorted` option and is called [here](https://github.com/gammapy/gammapy/blob/046532a483c9927ee44c850d9e5ddf1a57e7a17c/gammapy/maps/geom.py#L281) and [here](https://github.com/gammapy/gammapy/blob/046532a483c9927ee44c850d9e5ddf1a57e7a17c/gammapy/maps/geom.py#L293).

I think supporting "categorical" labels like `MC_ID` is something we want. Don't we have tests for that already, at least when represented as integers? Not sure if we need to support string labels like pandas / xarray.

For non-sorted float nodes I'm not sure what the appropriate Gammapy response should be. @AtreyeeS - Maybe you could create and post a minimal test case that currently fails? And mention what you think a better behaviour would be?

**Comment by AtreyeeS** [comment]
Address in #2126. The question of `labelled_axis` remains open.
