### ISSUE TITLE
ReflectedRegionsBackgroundEstimator.plot() centered on pointing of last obs

### ISSUE THREAD

**Issue by lmohrmann** [gammapy/gammapy#2068]
Since 85025b763d2059ee849ac3a679140c2e51a155d2 and 1a6a85a7474d103face24d63edc421049cab45b3, the plots created by `ReflectedRegionsBackgroundEstimator.plot()` are always centered on the pointing position of the last observation (rather than the position of on region, which I think was the previous behaviour). This is not a big issue, but would be nice if corrected.

As a further suggestion, it might also be helpful to add the option to choose the coordinate system of the `reference_map`. Previously, this was taken from the `exclusion_mask`, but is now always `GAL`.

**Comment by lmohrmann** [comment]
@registerrier 
Any chance to get this fixed for 0.12?

**Comment by bkhelifi** [comment]
Hello @registerrier ,
This is fixed in the PR #2079....

**Comment by lmohrmann** [comment]
@bkhelifi 
Ah, thanks for the information!

@registerrier 
Unless you want this fixed in 0.11, I guess you can just wait for #2079 to be merged. It's not really important to me that this is fixed in 0.11 (#2079 is going into 0.12, I presume), although the current behavior is a bit annoying...

**Comment by cdeil** [comment]
@lmohrmann - could you please check if this issue is resolved in Gammapy master now?

#2267  is still open and related, but this issue should be fixed.

**Comment by cdeil** [comment]
Should be fixed.
