### ISSUE TITLE
Function `log_center` of  BinnedDataAxis is always positive.

### ISSUE THREAD

**Issue by mackaiver** [gammapy/gammapy#2073]
If I have a `BinnedDataAxis` object with bins of negative values like this:

```
In [2]: axes.bins
Out[2]: [-6.  -5.7 -5.4 -5.1 -4.8 -4.5 -4.2 -3.9 -3.6 -3.3 -3.  -2.7 -2.4 -2.1
 -1.8 -1.5 -1.2 -0.9 -0.6 -0.3  0.   0.3  0.6  0.9  1.2  1.5  1.8  2.1
  2.4  2.7  3.   3.3  3.6  3.9  4.2  4.5  4.8  5.1  5.4  5.7  6. ] deg
```
The log centers should also be negative. But in version v0.10.0 they're all positive

```
Out[3]: [ 5.84807661  5.5479726   5.24785671  4.94772675  4.64758002  4.34741302
  4.04722127  3.7469988   3.44673759  3.14642654  2.84604989  2.54558441
  2.24499443  1.94422221  1.64316767  1.34164079  1.03923048  0.73484692
  0.42426407 -0.          0.          0.42426407  0.73484692  1.03923048
  1.34164079  1.64316767  1.94422221  2.24499443  2.54558441  2.84604989
  3.14642654  3.44673759  3.7469988   4.04722127  4.34741302  4.64758002
  4.94772675  5.24785671  5.5479726   5.84807661] deg

```

**Comment by registerrier** [comment]
Thanks @mackaiver . Actually you can even get `nan` since the `BinnedDataAxis` implicitly assumes positive values for bin edges.
```
bins=np.linspace(-3,2.5,11)  
axis=BinnedDataAxis(bins[:-1],bins[1:], interpolation_mode='linear')   
Out[27]: 
<Quantity [2.71108834, 2.1575449 , 1.60156174, 1.03923048, 0.4472136 ,
                  nan, 0.50497525, 1.09087121, 1.65227116, 2.20794022]>
```

**Comment by registerrier** [comment]
The log center of an interval with negative and positive edges being not very clearly defined, I suggest to simply raise a `ValueError` if `log_center` is called with negative edges values.

**Comment by adonath** [comment]
Thanks @mackaiver! I just checked and actually it is an issue for the `MapAxis` as well:

```python3
import numpy as np
from gammapy.maps import MapAxis

nodes = np.linspace(-5, 5, 11)
axis = MapAxis.from_nodes(nodes=nodes, interp="lin")
print(axis.center)

axis = MapAxis.from_nodes(nodes=nodes, interp="log")
print(axis.center)

axis = MapAxis.from_nodes(nodes=nodes, interp="sqrt")
print(axis.center)
```

Which returns:
```
[-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]
[1.17549435e-38 1.17549435e-38 1.17549435e-38 1.17549435e-38
 1.17549435e-38 1.17549435e-38 1.00000000e+00 2.00000000e+00
 3.00000000e+00 4.00000000e+00 5.00000000e+00]
[5. 4. 3. 2. 1. 0. 1. 2. 3. 4. 5.]
```
So for `interp="log"` the values are clipped at zero, for `interp="sqrt"` the values are casted to positive.

The question is what a reasonable behaviour is in those cases. So far `interp="log"` and `interp="sqrt"` have been used for energy and rad axes, where the values are restricted to be positive. For other use-cases (such as FoV coordinates) it's definitely needed to handle negative values as well, but there you probably would not apply any interpolation scaling. 

I guess we have two options here:
1. Just forbid the `log` and `sqrt` scaling if negative values are present and raise a `ValueError`
2. Implement a "mirrored" scaling behaviour for negativ values. I.e. multiply the values with their sign. apply the scaling and multiply again with the cached sign:

```python3
# sqrt
values_scaled = np.where(values > 0, np.sqrt(values), -np.sqrt(-values))

# log
values_scaled = np.where(values > 0, np.log(values), -np.log(-values))
```

@mackaiver Do you think there is a use-case for the second option? Or is it just fine to forbid the scaling if negative values are present?

**Comment by mackaiver** [comment]
> Do you think there is a use-case for the second option? Or is it just fine to forbid the scaling if negative values are present?

I can't think of a use-case. Simply raising an error sounds fine to me. 👍

**Comment by AtreyeeS** [comment]
>  Do you think there is a use-case for the second option? Or is it just fine to forbid the scaling if negative values are present?

Perhaps this can be useful for the time axis? Say the time for a GRB (or whatever) trigger is defined to be 0, and then you can have negative values of time, which may need some interpolation other than linear?

**Comment by adonath** [comment]
@AtreyeeS You, mean e.g. if the burst is fit with an exponential decay curve, it could be useful to have a log scaling in time? But as the zero point of the time axis can be shifted, I think it can be always shifted to positive values...

**Comment by AtreyeeS** [comment]
> @AtreyeeS You, mean e.g. if the burst is fit with an exponential decay curve, it could be useful to have a log scaling in time? 

Yes!

> But as the zero point of the time axis can be shifted, I think it can be always shifted to positive values...

I think so as well, but perhaps it would be better to take opinions of people who have done GRB analysis.
