### ISSUE TITLE
Cython warning about `language_level`

### ISSUE THREAD

**Issue by lmohrmann** [gammapy/gammapy#2087]
When building Gammapy, I currently get the following warning:
```
cythoning gammapy/maps/_sparse.pyx to gammapy/maps/_sparse.c
/home/woody/caph/mpp227/software/anaconda3/lib/python3.7/site-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/hpc/caph/mpp227/software/gammapy/gammapy/maps/_sparse.pyx
```

I investigated a bit, and it seems the solution for this is to put the line `# cython: language_level=3` at the top of all `.pyx`-Files (see e.g. https://github.com/astropy/astropy/search?q=language_level&unscoped_q=language_level). I tested this with `cube/_sparse.pyx`, and indeed, the warning is gone.

**Comment by cdeil** [comment]
There is a way to set cython `language_level` globally via `setup.py`:
See https://stackoverflow.com/a/53992016/498873
But for us `cythonize` is called somewhere else via astropy-helpers, and it's not clear how to pass this option from our `setup.py`.

So I'd suggest we follow the lead of Astropy itself and just add `#cython: language_level=3` at the top of each pyx file.

I'll send a PR shortly.
