### ISSUE TITLE
Bug in tutorials/image_fitting_with_sherpa.ipynb

### ISSUE THREAD

**Issue by holchtim** [gammapy/gammapy#2094]
It looks like there is a `- 1` missing in the calculation of the fitted components' sky positions from pixel coordinates in the last code block of the notebook. It should rather be 
`coord = geom.pix_to_coord((g.xpos.val - 1, g.ypos.val - 1))`
as it appears that sherpa starts numbering pixels from 1 and not from 0.
This can be seen by overlaying the sherpa 2D model with the position of a model component. An adapted notebook with the according code block to visualise the issue can be found [here](https://nbviewer.jupyter.org/gist/holchtim/b7dde9aadc72d32ced474117d17a209f).

**Comment by adonath** [comment]
Thanks @holchtim, looks like a clear bug to me.

@registerrier I don't remember, but I think it's correct that `sherpa` uses 1 based indexing, so I guess we should just fix this?

**Comment by adonath** [comment]
Fixed in https://github.com/gammapy/gammapy/commit/065351a2683e9a25ae597f8a19f9de4c4b8adcaa. Thanks @holchtim!
