### ISSUE TITLE
Jupyter notebook editing via PyCharm

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#2096]
PyCharm 2019.1 was just released - they have completely re-done the Jupyter notebook support, it's much better now than before: https://www.youtube.com/watch?v=TIZH4aPSN2E
(I think only available in the paid pro version for now)

There's two main issues to be able to use it to edit the Gammapy tutorial notebooks:

1. They don't do code analysis of cells with `%%time`, resulting in a ton of incorrect "unresolved reference" errors for us. I've complained about this just now: https://youtrack.jetbrains.com/issue/PY-34933

2. When saving form PyCharm, they add this entry:
```
    "cell_type": "markdown",
-   "metadata": {},
+   "metadata": {
+    "pycharm": {}
+   },
```
and also the JSON they save has a different indentation than the JSON that Jupyter saves.

That second issue probably can be worked around on our side, e.g. the indentation can be fixed via:
```
python -m gammapy jupyter --src=tutorials black
```
@Bultako - what would be the best way to strip the `pycharm` key in `meta`? Add a `Makefile` target and use e.g. `jq`? Or add a sub-command of `gammapy jupyter` to "standardise" the IPYNB files quickly after editing them with PyCharm?

**Comment by cdeil** [comment]
I've complained about the JSON output formatting differences also to Jetbrains: https://youtrack.jetbrains.com/issue/PY-34935

But even if they fix it, it'll probably take a while, so I'm +1 to make some addition / workaround in the `Makefile` or `gammapy jupyter` for now, so that I (and probably others) can use PyCharm to work on the notebooks.

**Comment by Bultako** [comment]
That's great news to have these new features in PyCharm !

I have not found the issue you mention with %%time, see screenshot below.
![Captura de pantalla 2019-03-28 a las 17 15 21](https://user-images.githubusercontent.com/328261/55174104-20872380-517d-11e9-847c-fb0b32197044.png)

I neither have found issues with different indentation (?!)

But I have seen the `pycharm` key in the metadata.
I think this metadata could be easily removed with `gammapy jupyter strip`, it would be an internal transparent step in the process of doc building, which already uses `gammapy jupyter strip`

**Comment by cdeil** [comment]
@Bultako - Thanks for #2099 . There was also a small API change in black recently, fixed in b4e746175702eb2b6531fec625dda3887fdf4f33 . To make notebook `gammapy jupyter --src=tutorials black` work you need to `pip install -U black`.

The PyCharm devs are already fixing the two issues that I reported, should be out in a patch release in the coming weeks. I'll just wait for that and then clean up all notebooks a bit (mainly unused imports). This issue is already assigned to me and v0.12.

**Comment by cdeil** [comment]
PyCharm notebook support not ready yet - at least `cta_1dc_introduction.ipynb` shouldn't be opened in PyCharm: https://youtrack.jetbrains.com/issue/PY-35450

**Comment by cdeil** [comment]
Closing this issue. Nothing to do here really for Gammapy.

Some day Gammapy dev docs should be written, and a mention included that editing notebooks in PyCharm is a very good option.
