### ISSUE TITLE
Single object vs container confusion

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#2102]
I find it confusing if one is allowed to pass single objects or containers.

Several such cases have been introduced recently: see cases below where one can pass a single model or a list, or a background model or a list, or a dataset or list of datasets.

Suggest to simplify those and to only accept lists.

The coding pattern to use is usually:
```
def __init__(self, things):
    self.things = Things(things)
```
and to make it behave like a no-op if `things` is already a `Things` object, and store away the list if a list is passed.

The one small drawback is that sometimes one has to write `Fit(datasets=[my_dataset])`, i.e. an extra `[]` if one only has a single object where the code can handle several. IMO the convenience of being able to write `Fit(datasets=my_dataset)` isn't worth the cost:

- Requires more code (isinstance checks)
- Requires more tests (two cases)
- Requires more complex docstrings
- Two ways to do the same thing - confusion by users and devs where which is accepted and needs to be handled.

---

A bit related is the issue that `SkyModel` is not a base class, but the concrete factorised sky model where spectrum and spatial part are factorised. I think the `gammapy.utils.fitting` code would become clearer if we rename and make `SkyModel` the base class (just how `Map` and `Dataset` are the base classes). Also from just reading around today I found the code with source & background models quite complex - I wonder if a single models list and flags that declare what to do with the model wouldn't be simpler.

@adonath - up to you if you want to finish the datasets and models PIGs first and have everything clear, or just go one pull request / discussion at a time in the coming weeks.

---

Concretely, I saw these places in the current code that I would suggest we simplify:

https://github.com/gammapy/gammapy/blob/b2e78e72521929513a26c59bd1bc343282133b7b/gammapy/cube/fit.py#L24-L25

https://github.com/gammapy/gammapy/blob/e699c3658f6aacff52873508706a962f275021b6/gammapy/cube/fit.py#L36-L37

https://github.com/gammapy/gammapy/blob/b2e78e72521929513a26c59bd1bc343282133b7b/gammapy/cube/fit.py#L80-L98

https://github.com/gammapy/gammapy/blob/b2e78e72521929513a26c59bd1bc343282133b7b/gammapy/utils/fitting/datasets.py#L37-L51

**Comment by adonath** [comment]
I'm completely fine with this suggestion. I think I can take an afternoon before the 0.12 release and implement this pattern everywhere in Gammapy. Alternatively we leave it up to the big API change before the 1.0 release...
