### ISSUE TITLE
SkyEllipse fit convergence problem

### ISSUE THREAD

**Issue by adonath** [gammapy/gammapy#2109]
@lmohrmann reported that he had problems with the fit convergence of the `SkyEllipse` model we introduced for Gammapy v0.11. I have taken a closer look and could reproduce the problems on simulated data. Here are the likelihood profiles I get:

Position longitude:

<img width="404" alt="Screenshot 2019-04-02 at 23 07 24" src="https://user-images.githubusercontent.com/3715928/55436474-bb786700-559c-11e9-853f-330e8c19b528.png">

Position latitude:

<img width="404" alt="Screenshot 2019-04-02 at 23 07 34" src="https://user-images.githubusercontent.com/3715928/55436446-a13e8900-559c-11e9-8896-25e6eba1259a.png">

Semi major:
<img width="404" alt="Screenshot 2019-04-02 at 23 07 43" src="https://user-images.githubusercontent.com/3715928/55436332-4a38b400-559c-11e9-8998-b89b61d29341.png">

Thinking about it twice, I'm not really surprised by the shape. Given our current implementation of the `SkyEllipse` and `SkyDisk`, coordinate pixels will move in and out of the condition defining the area of the ellipse / disk, depending on the center position of the model. This leads to the jumps in the likelihood surface. The issue can technically be resolved by integrating over the area of the pixel, but I wonder how this has been handled in the past without the integration? Maybe softening the edge, e.g. by introducing some slope?

I've never fitted one of these models with "sharp" edges in sherpa nor HAP or M++. Do you know anything about this @registerrier or @luca-giunti?

**Comment by registerrier** [comment]
Note that if this comes from a simulation made with the same model, the data display the same behavior. We can assume that this will increase even more the edgy likelihood profile. I am a bit surprised by the small sizes of the steps. What is the bin size used here?

I am not sure I have a better alternative to propose except integration, I must say.

**Comment by adonath** [comment]
Thanks, @registerrier for the comment. The bin size used for the plots I showed above was 0.05 deg. Here are the same profiles for 0.01 deg for comparison (I did not subtract the fit minimum this time, but for the shape it doesn't matter... ):

Position longitude:

![Screenshot 2019-04-03 at 09 57 57](https://user-images.githubusercontent.com/3715928/55462480-25255f00-55f7-11e9-94fb-e0c0a52af15a.png)

Position latitude:
![Screenshot 2019-04-03 at 09 58 14](https://user-images.githubusercontent.com/3715928/55462466-1ccd2400-55f7-11e9-9796-7aea707b2b3a.png)

Semi major:

![Screenshot 2019-04-03 at 09 58 24](https://user-images.githubusercontent.com/3715928/55462497-2f475d80-55f7-11e9-8393-a0878fda6503.png)

I see a few possibilities to resolve this problem:

- Introduce the `SkyModel.oversample` attribute and set a default of maybe `4` for
the `SkyDisk` and `SkyEllipse` models. This was foreseen in the Dataset PIG anyway and is probably a practical solution. It still might no completely resolve the issue, as it remains just on a different spatial scale. I guess it depends on the step size the optimiser uses...which is not necessarily under our control. 
 
- Maybe use https://github.com/astropy/regions/blob/master/regions/_geometry/elliptical_overlap.pyx to evaluate the `SkyEllipse` and https://github.com/astropy/regions/blob/master/regions/_geometry/circular_overlap.pyx to evaluate the `SkyDisk`?

- Smooth the edge of the `SkyDisk` and `SkyEllipse` somehow...

- Implement something similar as I did for the `SkyPointSource`, based on a local gradients...

- Tell users, that the `SkyDisk` and `SkyEllipse` models are not suitable for fitting positions. And positional parameters should be frozen..?

A different approach here would be to tell the optimiser the minimal step size for `lon_0` and `lat_0` and set it to ~0.5 pixels. I think this should work for `Minuit`, but might not work for other optimisers, that don't accept the step size as a parameter. Side comment: I think by scaling the `lon_0` and `lat_0` for the fitting we actually worsened the problem, so probably we should not do this...

**Comment by registerrier** [comment]
I think we can probably solve part of the issues if `MapEvaluator` computes model and exposure evaluations at bin edges and then apply trapezoidal integration rather than the value at bin center times the bon volume.

If this does not work, then we have to indeed find a way to perform integration, e.g. with astropy models. But then we are back to the question of planar vs spherical models again.

And regarding your side comment, I agree that we should not scale `lon_0` and `lat_0`, and probably all angles no?

**Comment by adonath** [comment]
I just tried the somewhat pragmatic solution to the problem, by introducing a smooth edge using `scripy.special.erf`. Here is a notebook with the resulting likelihood profiles: https://github.com/adonath/notebooks-public/blob/master/smooth-edge-sky-ellipse.ipynb
 The corresponding implementation is [here](https://github.com/adonath/gammapy/blob/smooth_disk_ellipse_edge/gammapy/image/models/core.py#L379). 

The likelihood profiles look very smooth and correct now and the fit converges as well. The question is whether this `edge` parameter is acceptable and how this parameter is handled in practice. I think a reasonable default of maybe 1/10 of the PSF size could be chosen, but still we probably have to add some special handling, depending on the bin size used of the analysis (the edge parameter cannot be smaller than 1/5 of the bins size or similar, e.g. checked within the `MapDataset`).

I think in general it's a useful parameter and could be fitted as well, because a model with a sharp edge is probably not a good (physical) assumption anyway. As long as we don't have a good solution I'm slightly in favour of adding the additional `edge` parameter to the `SkyDisk` and `SkyEllipse` models. The actual definition and name of the parameter is of course open for discussion. Any opinions @lmohrmann, @registerrier or @luca-giunti?

**Comment by lmohrmann** [comment]
Let me try to understand this: we see problems because in the current implementation of the integration of the spatial model, we simply check whether a pixel center falls into the ellipse (and count the pixel if it does and otherwise not). Ultimately, this should be solved by finding a good way to integrate over pixels that are "cut" by the edge of the ellipse. Your proposal is then a temporary fix that should not affect the results much (if the value of `edge` is chosen wisely) but improve the convergence behavior. Is that correct?

If so, that's probably a solution I can live with for now.

**Comment by adonath** [comment]
@lmohrmann Yes, exactly.
