### ISSUE TITLE
test_gaussian_sum_moments fails

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#213]
@adonath The `test_gaussian_sum_moments` from `gammapy/morphology/tests/test_gauss.py` fails:
https://gist.github.com/cdeil/ea674fb7387fc0d27c44

Looks like you pass a numpy array to `measure_image_moments`, which you changed to accept an `ImageHDU` in f310784c95b2f59d89f3d877e7866c8ba046129d .

Can you please fix this?

The reason this didn't fail on travis-ci is that I forgot to `pip install uncertainties` ... can you please in the same PR add this here?
https://github.com/gammapy/gammapy/blob/master/.travis.yml#L90

**Comment by adonath** [comment]
Fixed in #215
