### ISSUE TITLE
Add min / max edges attributes to MapAxis?

### ISSUE THREAD

**Issue by adonath** [gammapy/gammapy#2134]
In the context of #2133, the question came up whether we should implement  `MapAxis.edges_mins` and `MapAxis.edges_maxs` attribute. And correspondingly add the possibility to create a `MapAxis` object from `edges_mins` and `edges_maxs` values. 
It is useful mainly in the context of serialisation of the MapAxis objects to tables. This is currently heavily used in the `gammapy.irf` submodule.

**Comment by AtreyeeS** [comment]
And correspondingly add the possibility to create a `MapAxis` object from `edges_mins` and `edges_maxs` values.
Is this not similar to `MapAxis.from_bounds()`?

**Comment by adonath** [comment]
@AtreyeeS No, that's not what I meant, I guess the names are misleading.

What I had in mind was the following use case:
```python3
from astropy import units as u
from gammapy.maps import MapAxis

# edges as one single array
edges = [1, 2, 3, 4, 5] * u.TeV
axis = MapAxis.from_edges(edges)

# edges as separate mins and maxs arrays
edges_mins = [1, 2, 3, 4] * u.TeV
edges_maxs = [2, 3, 4, 5] * u.TeV 

axis = MapAxis.from_edges(edges_mins, edges_maxs=edges_maxs)

# and
axis.edges_mins  # alias for axis.edges[:-1]
axis.edges_maxs  # alias for axis.edges[1:]
```

Does it make sense now?

**Comment by adonath** [comment]
Choosing a good naming convention is actually another issue. Right now we have in Gammapy a wild mixture between `edges`, `center`, `bins`, `bounds`, `nodes`, `lo`, `hi`, `upper`, `lower`, etc.

I think ideally we could unify this somehow, by a single convention. I don't really strongly care which one it is, as long as it's uniform. I have a slight preference to use what we have for `MapAxis` now, i.e. use `center` and `edges` and `_min` and `_max`, that's why I proposed the those names.

**Comment by AtreyeeS** [comment]
```python
> # edges as separate mins and maxs arrays
> edges_mins = [1, 2, 3, 4] * u.TeV
> edges_maxs = [2, 3, 4, 5] * u.TeV 
> axis = MapAxis.from_edges(edges_mins, edges_maxs=edges_maxs)
```
Ok I see now what you mean. But according to our present implementation, `MapAxis.edges` have to be contiguous, ie, we cannot have "gaps" or "overlaps". So something like
 
```python
# edges as separate mins and maxs arrays
edges_mins = [1, 2, 3, 4] * u.TeV
edges_maxs = [3, 4, 5, 6] * u.TeV 
axis = MapAxis.from_edges(edges_mins, edges_maxs=edges_maxs)
```
is not acceptable. Simply passing one array in `MapAxis.from_nodes()` automatically picks up the only possible high and low edges. Then what do we really gain by passing two arrays?

And yes, I completely agree it would be nice to have a uniform convention. +1 to `center` `edges` and `min` and `max`.

**Comment by adonath** [comment]
@AtreyeeS Yes, this is actually an important point. Right now the only use case we have is the one I described above, e.g. for FITS I/O we split the `edges` into the `mins` and `maxs` values, so it's just a different representation of the same information. The attributes would be just added for convenience and better readability of the code.

I'm not sure whether in general we want to allow "gaps" or "overlaps". If there was a use-case for it, I think it could handle with multiple `Dataset` and a joint-likelihood analysis as well...so maybe no?

**Comment by AtreyeeS** [comment]
I am not sure we can directly allow "gaps" and "overlaps" at present. The `coord_to_pix` interpolation assumes monotonic and "gapless" nodes, so I think it would silently give error prone results. The probable use I can see for such an axis is again `labelled_axis` which will not be interpolated.

For just using in the FITS I/O, I would go with the implementation you have done now...

**Comment by cdeil** [comment]
@adonath - I don't see the advantage of `edges_mins`, suggest to just keep using and documenting the coding pattern to slide of one at the left or right.
```
axis.edges_mins  # alias for axis.edges[:-1]
axis.edges_maxs  # alias for axis.edges[1:]
```

Going the other way is more difficult. For that we still have this helper function in gammapy.maps:
https://github.com/gammapy/gammapy/blob/bddde6ebd446be109be964f64875ba21993aa326/gammapy/maps/utils.py#L155-L161

As discussed previously, we could just centralise all this edges / centers / arange / linspace functionality on `MapAxis`, i.e. I'd suggest to get rid of `edges_from_lo_hi` and if we don't have that functionality already, add it as a static or normal method on MapAxis.

**Comment by adonath** [comment]
+1 to just add `MapAxis.from_edges_lo_hi()` as a little helper function.

**Comment by adonath** [comment]
Remaining ToDo: add `MapAxis.from_edges_lo_hi()`

**Comment by adonath** [comment]
The current use-cases for the `edges_from_lo_hi()` helper methods are all internal, basically for compatibility with IRF classes and the `CountsSpectrum`. At this point it becomes an implementation detail, will re-label now...

**Comment by adonath** [comment]
By now all `MapAxes` actually have the `edges_min` and `edges_max` attributes. The reason is to handle contiguous and non-contiguous axes in an API compatible way.
