### ISSUE TITLE
gammapy.astro.population

### ISSUE THREAD

**Issue by manconi** [gammapy/gammapy#2135]
Recently, I was really interested in this gammapy module:

https://docs.gammapy.org/0.11/astro/population/index.html?highlight=gammapy%20astro%20population#module-gammapy.astro.population

I started with the very basic example that is provided in the documentation, and with the default parameters in the gammapy functions. 
However, I am finding some strange trend for the simulated pulsar  parameters.

For example, the distribution of the spin-down power of the pulsars (L0_psr) in the simulated catalog  contains a significant fraction of sources with this quantity exceeding many orders of magnitude the maximum value in the ATNF catalog of observed pulsars. 
I can share some comparison plots if needed.

Do you have any recommendation on how to avoid these issues?
Thank you!

**Comment by adonath** [comment]
Thanks @manconi for using this code and opening the issue. It would be great if you could share the comparison plots (just drag and drop the images into the Github editing window).

If I remember correctly the pulsar population model basically follows https://arxiv.org/abs/astro-ph/0512585. Including the spatial distributions and underlying assumptions for the magnetic field distribution and birth period distribution. I've never tried to tune the model parameters to match the distributions of the ATNF catalog, but I think it was done in the original Faucher & Kaspi publication, so I just assumed the same default parameters.

Just guessing: equation (22) in the paper suggests that there is a radio emission shut-off. This is not  implemented by default, but can be achieved by a simple selection cut on the simulated pulsar catalog. Have you tried to include this cut in your comparison?

**Comment by manconi** [comment]
Thank you @adonath  for your reply! 
Indeed, applying the radio emission shut-off in eq.22 you suggested the properties of the selected sources are in agreement with my expectation from ATNF, not only for their properties in terms of L0_psr, but also in terms of cosmic ray  electron-positron production. 
Thank you!

**Comment by adonath** [comment]
I'm glad I could help.
