### ISSUE TITLE
Clean up spectral tutorials?

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#2137]
Right now, within gammapy we have 6 tutorials related to spectral analysis, which I find quite confusing. I propose that we clean this up.

1. `spectrum_simulation` can be removed. `spectrum_simulation_cta` explains how to do a simulation, and I do not think "simulating a detector" is something most users would do on the first go. Also, rename `spectrum_simulation_cta` to just `spectrum_simulation`.

2. `spectrum_models` can also be removed and some details about the models (and how to access the errors) provided in the new  `spectrum_simulation`. The one useful thing here is the implementation of User Defined models. Suggest to add it in `spectrum_simulation` as well.

3. `spectrum_fitting_with_sherpa` is a small tutorial, but since it does not even use `Datastore`, can stay untouched.

4. remove `spectrum_pipe` and only keep `spectrum_analysis`? I am not very sure about this, since this implies that `gammapy.scripts.SpectrumAnalysisIACT` will probable not be used by users at all if it is not exposed in the tutorials. However, my experience says it is not very useful (more debug plots are always necessary), fitting using the Datasets API is cleaner... Then perhaps the `SpectrumAnalysisIACT` should be removed as well.

**Comment by adonath** [comment]
Thanks for this proposal, it sounds reasonable to me.

Just to add: `SpectrumAnalysisIACT` is currently used in the `hess.ipynb` tutorial, so I think it's OK to keep it as a class and only use it there. It still saves users writing ~10-20 lines of code...

**Comment by AtreyeeS** [comment]
Done in #2140
