### ISSUE TITLE
Gammapy project code stats

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#2138]
This is a reminder issue for myself to write a script that produces some Gammapy project code stats, such as number of lines of code, comments and blanks, but also number of classes, methods and functions, and how much code we have in Cython and notebooks, and how much docs in RST.

Having all numbers of interest via `make stats` can be useful sometimes, e.g. for presentations, in-kind contributions or a paper about Gammapy.

There are many tools that partly do what I want, e.g. [cloc](https://github.com/AlDanial/cloc), [ohcount](https://github.com/blackducksoftware/ohcount), [radon](https://github.com/rubik/radon), [wily](https://wily.readthedocs.io), ...

But none really do what I want. E.g. they don't count code in notebooks, or they just attribute docstrings either to comments or code, but I think it would be nice to count docstrings separately.

Since this is more generally usable,  I'll make a small separate package `pyprojectstats` and then use it for Gammapy.

**Comment by adonath** [comment]
@registerrier and @bultako would you mind sharing the tool / command that you used to derive the code stats for the CTA ST selection? I think we could maybe add a minimal entry in the developer docs how to do this using an external tool and then close the issue.

**Comment by Bultako** [comment]
I use https://github.com/roskakori/pygount
With a clean install `make clean && pip install -e.` I use the following command 

```
pygount --format summary --folders-to-skip dev,test* --suffix=py,rst,json,yml,pyx,ipynb .
```

which now produces the table below

```
    Language      Files    %     Code     %     Comment    %   
----------------  -----  ------  -----  ------  -------  ------
Python              216   64.48  24882   69.49    20037   99.87
reStructuredText     81   24.18  10624   29.67        4    0.02
YAML                  5    1.49    234    0.65       18    0.09
Cython                1    0.30     68    0.19        5    0.02
__unknown__          32    9.55      0    0.00        0    0.00
----------------  -----  ------  -----  ------  -------  ------
Sum total           335          35808            20064
```

being `__unknown__` Jupyter ipynb files.

**Comment by adonath** [comment]
Thanks @Bultako! Is it possible to count for test files as well?

**Comment by Bultako** [comment]
@adonath 
This code-stats analysis package groups by file types. Since test files are also python files, these will be included in the summary table as Python Language if we do remove `test*` in `--folders-to-skip` parameter of the command, as shown below.

```
$ pygount --format summary --folders-to-skip dev --suffix=py,rst,json,yml,pyx,ipynb .
    Language      Files    %     Code     %     Comment    %   
----------------  -----  ------  -----  ------  -------  ------
Python              335   70.38  41815   79.28    20911   99.87
reStructuredText     81   17.02  10624   20.14        4    0.02
YAML                  5    1.05    234    0.44       18    0.09
Cython                1    0.21     68    0.13        5    0.02
__unknown__          32    6.72      0    0.00        0    0.00
__empty__            22    4.62      0    0.00        0    0.00
----------------  -----  ------  -----  ------  -------  ------
Sum total           476          52741            20938
```

We could subtract the numbers from the previous table to differentiate test files from Python files.
I guess ``__empty__`` files are empty `__init__.py` in test folders.

**Comment by registerrier** [comment]
I have been using `cloc`  which is probably used by `pygount` as well:
```
cloc gammapy
     307 text files.
     307 unique files.                                          
      42 files ignored.

github.com/AlDanial/cloc v 1.80  T=1.29 s (222.9 files/s, 66034.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                         278          14982          17369          43861
C                                1            399           1585           6278
YAML                             7             14             17            400
Cython                           1             14             35             68
-------------------------------------------------------------------------------
SUM:                           287          15409          19006          50607
-------------------------------------------------------------------------------

```
For tests, you would specify tests directories.

**Comment by adonath** [comment]
@registerrier and @Bultako Do you think such info could be interesting for the paper? If yes we could maybe write a little script that executes `cloc` and creates a pie chart and or summary latex table.

**Comment by Bultako** [comment]
I have added a [script](https://github.com/gammapy/gammapy-paper/blob/master/scripts/codestats.py) in the GAMMAPY_PAPER repo that creates a Latex table and piechart plots for code and files used with results coming from `cloc` command.

```
$ python codestats.py --src /Users/jer/git/gammapy/gammapy
INFO:root:LaTeX OUTPUT TABLE BELOW:


\begin{tabular}{ccccccc}
\hline
Language	& files	& blank	& comment & code \\
\hline
Python	& 336	& 15609	& 18097	& 45494 \\
reStructuredText	& 84	& 3486	& 2504	& 8614 \\
C	& 1	& 481	& 2113	& 6617 \\
Notebook	& 32	& 0	& 17442	& 3390 \\
JSON	& 1	& 0	& 0	& 3128 \\
YAML	& 24	& 22	& 35	& 1658 \\
XML	& 10	& 0	& 0	& 398 \\
make	& 2	& 42	& 17	& 226 \\
Batch	& 1	& 21	& 1	& 148 \\
JavaScript	& 2	& 6	& 11	& 78 \\
Cython	& 1	& 14	& 35	& 68 \\
Markdown	& 4	& 18	& 0	& 56 \\
Shell	& 1	& 2	& 3	& 42 \\
CSS	& 1	& 7	& 6	& 35 \\
Dockerfile	& 1	& 13	& 8	& 24 \\
TOML	& 1	& 0	& 0	& 9 \\
\hline
SUM	& 502	& 19721	& 40272	& 69985 \\
\end{tabular}


INFO:root:PIECHART FILE piecode.png CREATED
INFO:root:PIECHART FILE piefiles.png CREATED
```

![image](https://user-images.githubusercontent.com/328261/126164188-8b3a870c-ca69-4687-9511-0719f975274e.png)

![image](https://user-images.githubusercontent.com/328261/126164606-5104ec01-5888-4b14-9325-c2cdf429fd01.png)

**Comment by adonath** [comment]
Nice, thanks a lot @Bultako! Will close the issue for now, anything else can be discussed in the paper repo.
