### ISSUE TITLE
WcsGeom width attribute and repr

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#2148]
I noticed that there's a small bug in the `WcsGeom` repr: it prints "deg deg"

```
In [1]: from gammapy.maps import Map                                                                                                                              

In [2]: Map.create()                                                                                                                                              
Out[2]: 
WcsNDMap

	geom  : WcsGeom 
 	axes  : lon, lat
	shape : (3600, 1800)
	ndim  : 2
	unit  : '' 
	dtype : float32 

In [3]: geom = Map.create().geom                                                                                                                                  

In [4]: geom                                                                                                                                                      
Out[4]: 
WcsGeom

	axes       : lon, lat
	shape      : (3600, 1800)
	ndim       : 2
	coordsys   : CEL
	projection : CAR
	center     : 0.0 deg, 0.0 deg
	width      : 360.0 deg x 180.0 deg deg
```

That's easy to fix, one would just have to edit this line:

https://github.com/gammapy/gammapy/blob/d1b12230eba100de1640a29137d1b4b0f91c2a97/gammapy/maps/wcs.py#L923-L925

But I was also puzzled by this:
```
In [5]: geom.width                                                                                                                                                
Out[5]: 
<Quantity [[360.],
           [180.]] deg>

In [6]: geom.width.shape                                                                                                                                          
Out[6]: (2, 1)
```

Why is the `width` a 2D array.
Couldn't it be simpler, just a 1D array?

By chance I also saw this:
https://github.com/gammapy/gammapy/blob/d1b12230eba100de1640a29137d1b4b0f91c2a97/gammapy/maps/wcs.py#L20
Clearly a named tuple or some other data type could be an option as well for `width` ...

I wasn't sure about this, so @adonath - assigning to you to decide and resolve.

**Comment by adonath** [comment]
If I remember correctly the reason why `geom.width` returns a 2d array are multi resolution maps. If the pixel size varies, the width can also vary (because of rounding...). The question is whether this level of precision is needed, or maybe `geom.width` can just return an approximate width, which is valid for all pixel sizes...

**Comment by adonath** [comment]
I fixed the unit in the `__repr__` in master (https://github.com/gammapy/gammapy/commit/ccfdbbe335ea68ffb70aaef8fac0453d37c80b07). 

Here is the example with the varying bin size:

```python3
from gammapy.maps import Map, MapAxis

axis = MapAxis([1, 2])
image = Map.create(
    width=(10, 10),
    binsz=[0.3, 0.18],
    axes=[axis]
)

print(image.geom.width)
```

Which returns:
```
[[ 9.9  10.08]
 [ 9.9  10.08]] deg
```
So I think we should definitely keep the 2d array here.

**Comment by adonath** [comment]
@cdeil If you think the `.width` argument should still be changed to a 1d array for the case constant pixel size, please re-open.
