### ISSUE TITLE
Introduce a uniform term for -2 * log(likelihood)?

### ISSUE THREAD

**Issue by adonath** [gammapy/gammapy#2149]
In the past the `.likelihood()` method of the `Dataset` object has caused confusion, because it does not return the likelihood, but rather  `- 2 * log(likelihood)`. Apart from improving the documentation, there is probably a good reason to rename the functions and use the convention everywhere in Gammapy. 

What we have now:
- `Dataset.likelihood()` and `Dataset.likelihood_per_bin()`
- `OptimizeResult.total_stat`
- `gammapy.stats.fit_statistic`
- `loglike` and `dloglike` for flux points (see https://gamma-astro-data-formats.readthedocs.io/en/latest/spectra/binned_likelihoods/index.html#required-columns)
-  `total_stat`, `best_fit_stat`, etc. as variable names

What we have now is technically consistent in the sense that we only work with `- 2 * log(L)` and never with the likelihood directly or without the factor of 2. Still it would nice to reflect this in the method and variable names, so it becomes easier for users as well as developers to understand which quantity we refer to. 

My proposal would be to change to `fit_statistic` everywhere in Gammapy but leave the flux-points spec untouched for now. Any other proposals or opinions, @registerrier, @AtreyeeS @facero, @Bultako?

**Comment by cdeil** [comment]
+1 to change `Dataset.likelihood` and `Dataset.likelihood_per_bin`.

This is clearly not the likelihood `L`, it's `stat=-2*log(L)`:

https://github.com/gammapy/gammapy/blob/e4a24d0d777b9254315585aa8de5182f749c8e4b/gammapy/spectrum/dataset.py#L104-L106


> My proposal would be to change to fit_statistic everywhere in Gammapy but leave the flux-points spec untouched for now. 

In principle it doesn't matter mach if we choose `loglike` or `nll` (negative log likelihood) or `stat`.

But +1 to use `stat` as much as possible.

This is also what Sherpa does. See http://cxc.cfa.harvard.edu/sherpa/statistics/ or typical fit result:
```
sherpa> fit()
Dataset               = 1
Method                = levmar
Statistic             = chi2
Initial fit statistic = 2815.14 
Final fit statistic   = 151.827 at function evaluation 6
```

Is it possible / a good idea to try to be super-consistent on `fit_statistic`? I mean `stat` or `statistic` is also nice and short, and it's not always the result of a fit. E.g. we already have `gammapy.stats`. IMO a mix there would be OK, the main thing to do is rename the `Dataset.likelihood`. If you want to change a lot of `stat` -> `fit_stat`, could you please list the functions and methods first for brief discussion before making the change?

There's always going to be parts of the code where `logL` or `-logL` is used. Flux point spec is one, the interface to http://dfm.io/emcee/current/api/#abstract-sampler-object is another. In the end, one cannot completely hide this from users, and just has to explain `stat=-2 x logL` at some point. This could even be done in the results print-out in some places. E.g. [here](http://cta.irap.omp.eu/ctools/users/tutorials/quickstart/fitting.html) you can see that `-logL =` appears in the output to make it clear to users exactly what it is.

**Comment by registerrier** [comment]
I think `fit_statistic` or `stat` is a good choice for `Dataset`, `OptimizeResult`. And the doc must clearly explain we are always considering something of the form `-2 log(L)`.

Maybe those should not be named like the various statistic functions themselves (e.g. Cash, Wstat, Chi2, Cash+prior etc).

**Comment by cdeil** [comment]
@adonath - you wrote:

> My proposal would be to change to fit_statistic everywhere in Gammapy 

@registerrier - you wrote:

> Maybe those should not be named like the various statistic functions themselves (e.g. Cash, Wstat, Chi2, Cash+prior etc).

Can you please list the renames you propose?
E.g. would [gammapy.stats.cash](https://docs.gammapy.org/0.11/api/gammapy.stats.cash.html) change name?

I think a rename for `Dataset.likelihood` is clear and can just be done now. Maybe we can just resolve the issue and agree on other renames you want to do quickly? I would prefer this, as opposed to the alternative, which is to come back to this discussion in a few weeks or months (it's currently labeled v0.14).

**Comment by Bultako** [comment]
> +1 to change Dataset.likelihood and Dataset.likelihood_per_bin.
> This is clearly not the likelihood L, it's stat=-2*log(L):

I agree.
I would choose the same name for all vars that hold exactly the same *concept* = -2*log(L), I don't know if whta we have from the fit depends on the chosen backend used in `gammapy.utils.fitting.Fit` 

> In principle it doesn't matter mach if we choose `loglike` or `nll` (negative log likelihood) or `stat`.

Yes.
I would not choose as name `fit_statistic`, since we already have a very similar name with `gammapy.stats.fit_statistics`

> Maybe those should not be named like the various statistic functions themselves (e.g. Cash, Wstat, Chi2, Cash+prior etc).

Agree.
Moreover (somehow related), there is a chance that we need to add a new likelihood function in `gammapy.stats.fit_statistics` to calculate upper limits for dark matter. In this context I think it would be nice to have a clear interface to chose the stat function to use in the fitting as likelihood (cash, cstat, wstat, etc..), and if we have a var name for -2*log(L) to also have a single name for a method to fetch the name of the stats function L that has been used.

**Comment by adonath** [comment]
@registerrier, @cdeil and myself agreed on the term `stat` and `stat_per_bin`, I will add the proposal to the Datasets PIG #1986 and close this issue.

**Comment by cdeil** [comment]
My final 2 cents: I'd put `stat_array` and `stat_sum`, because if one is called `stat` most people will not know if it's the array or the sum.

**Comment by cdeil** [comment]
Related: #2291 by @tstolarczyk .

In addition to improving names and docstrings, we need to review docs and make sure it's clear.
