### ISSUE TITLE
Change SNRCat to gammapy-data

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#2162]
`test_load_catalog_snrcat` is currently failing because it fetches from http://www.physics.umanitoba.ca/snr/SNRcat/ which is currently down.

https://github.com/gammapy/gammapy/blob/6c1c8f48dde5cc47394e21b2985b9f297689f973/gammapy/catalog/tests/test_snrcat.py#L6-L7

There's a TODO in `SNRCat` already to consider putting a copy in `gammapy-extra`:

https://github.com/gammapy/gammapy/blob/6c1c8f48dde5cc47394e21b2985b9f297689f973/gammapy/catalog/snrcat.py#L43

For the second "live" catalog we have that can change any time, gamma-cat`, we currently have a copy in gammapy-extra and access it via gammapy-data:

https://github.com/gammapy/gammapy/blob/6c1c8f48dde5cc47394e21b2985b9f297689f973/gammapy/catalog/gammacat.py#L456

My suggestion would be to also put a fixed stable version of SNRCat in gammapy-extra, to include that in gammapy-data, and to access that from the test.

We could also add a `SNRCat.from_url` to allow both load from gammapy-data or from URL, and in that case would have to decide whether to leave that method untested, or whether to mark the test as "allowed to fail" to not disturb devs and CI when the web service goes down.

@Bultako @adonath - Thoughts?

**Comment by Bultako** [comment]
> My suggestion would be to also put a fixed stable version of SNRCat in gammapy-extra, to include that in gammapy-data, and to access that from the test.

+1
I guess this catalog will be accessed not only from tests, but also in `SourceCatalogSNRcat()`. According to the code in `catalog/gammacat.py` we would need to different csv files:
 - http://www.physics.umanitoba.ca/snr/SNRcat/SNRdownload.php?table=OBS
 - http://www.physics.umanitoba.ca/snr/SNRcat/SNRdownload.php?table=SNR

Would you prefer to have this catalog versioned?
If you all agree and provide me these two files I could do the modif.

**Comment by cdeil** [comment]
@Bultako - I'd like to do this myself, and for v0.13, because changing datasets while @adonath is preparing and doing the release this week is distracting.

There is already the old https://github.com/gammapy/gammapy-extra/blob/master/datasets/catalogs/snrcat.fits.gz and I'd put a new version there instead.

This is mostly a reminder issue for myself - but I also wanted your feedback on the API and testing to put for these two complex cases (gamma-cat and snrcat) of "live and changing" datasets we have. My suggestion is to dump a stable version in gammapy-extra, expose that as gammapy-data and use that for docs and tests. And to add a second method that lets users fetch the latest version from the web, but to not use that in tests or docs, or if we add a test, to mark it as "allowed to fail" because Gammapy CI shouldn't turn red just because http://www.physics.umanitoba.ca/snr/SNRcat/  is down or they change the format. Of course that comes at the price of us probably not noticing when that happens, but IMO that's OK, it's questionable overall if such code should be in Gammapy at all. A more extreme course of action would be to remove it - let me know if you think that's the right thing to do here.

**Comment by cdeil** [comment]
Here's an example showing that currently our CI fails because of `test_load_catalog_snrcat`:

https://dev.azure.com/gammapy/gammapy/_build/results?buildId=903&view=logs&jobId=54b4a527-ead6-5d78-3f02-5346815e0ca2&taskId=86513c84-57b9-57f7-f171-7d82dc57b7aa&lineStart=152&lineEnd=153&colStart=1&colEnd=1

**Comment by Bultako** [comment]
I would definitely add this catalog to `$GAMMAPY_DATA` so that users do not have to worry about broken external data services, so not only for docs and tests. Note that we can expose different versions of a catalog for each release of Gammapy, since we have different [JSON files](https://github.com/gammapy/gammapy-webpage/tree/gh-pages/download/data) (where the lists of datasets are declared), labeled with numbered releases.

If you want to add an additional method to download the catalog from an external url, it's perfectly fine, but I would set it to fetch it from `$GAMMAPY_DATA` by default.
