### ISSUE TITLE
Sphinx HTML formatting missing colon in parameters

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#2164]
I noticed that there's now an issue with the HTML formatting in our API docs: the colon ":" is missing between parameter names and types. See screenshots below.

My versions should match the latest `gammapy-dev` conda env - see [here](https://gist.github.com/cdeil/e173b63fc793625d888f21d9a12cbf4b) and [here](https://gist.github.com/cdeil/d71faf30b6ecdbbd83bc8e91eea914be) for version numbers.

The Sphinx build shows these warnings:
```
Running Sphinx v2.0.1
/Users/deil/work/code/gammapy/astropy_helpers/astropy_helpers/sphinx/conf.py:5: UserWarning: Note that astropy_helpers.sphinx.conf is deprecated - use sphinx_astropy.conf instead
  warnings.warn("Note that astropy_helpers.sphinx.conf is deprecated - use sphinx_astropy.conf instead")
*** Found GAMMAPY_DATA = /Users/deil/work/gammapy-tutorials/datasets
*** Nice!
/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.7/site-packages/sphinx/util/docutils.py:311: RemovedInSphinx30Warning: function based directive support is now deprecated. Use class based directive instead.
  RemovedInSphinx30Warning)
loading pickled environment... done
```
and later this:
```
writing additional pages... search/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.7/site-packages/sphinx_rtd_theme/search.html:20: RemovedInSphinx30Warning: To modify script_files in the theme is deprecated. Please insert a <script> tag directly in your theme instead.
  {{ super() }}
```

I don't know if those warnings are related or not to this formatting issue.

@Bultako - Can you reproduce? Do you have time to have a look or should I start debugging?

![Screenshot 2019-05-27 at 10 48 13](https://user-images.githubusercontent.com/852409/58407958-1befc600-806d-11e9-9e1d-ada9900375b4.png)

![Screenshot 2019-05-27 at 10 48 30](https://user-images.githubusercontent.com/852409/58407963-201be380-806d-11e9-9a2e-9814942083e3.png)

**Comment by Bultako** [comment]
@cdeil 
I have tested with a downgraded version  of Sphinx 1.8.5, which fixes the colon missing issue and does not throw warnings.

Should we use this Sphinx version? I have not found any differences in the built docs and it also works fine with https://github.com/gammapy/gammapy/pull/2169

**Comment by cdeil** [comment]
We can pin to an old version of Sphinx or nbsphinx for now. But the issue also needs to be fixed upstream in those packages and eventually resolved, pinning to old docs tool versions is a temp fix.

@Bultako - Can you look at their issue trackers and if it's not a known issue, report it there?

I know trying to pinpoint issues or extract test cases for Sphinx is often time consuming and difficult.
It doesn't have to happen now - it can happen any time in the coming weeks.

**Comment by cdeil** [comment]
Let's keep this open, moving to v0.13 milestone for now. Upstream issue is here: https://github.com/rtfd/sphinx_rtd_theme/issues/766

**Comment by Bultako** [comment]
This temporary [fix](https://github.com/readthedocs/sphinx_rtd_theme/issues/766#issuecomment-513852197) seems to solve this issue when building the docs with last version of Sphinx v2.1.2, since it uses the writer used in Sphinx v1.8

I've implemented this temporal fix and remove the pinned version of Sphinx in https://github.com/gammapy/gammapy/commit/6abef174417b598744928db04ba425e163091b69
while we wait for a html5 compliant version of sphinx_rtd_theme

**Comment by Bultako** [comment]
In https://github.com/gammapy/gammapy/commit/1b5461c18e5dbb4e6f537c9b7983e9731170502f I implemented another temporary fix for this.

**Comment by adonath** [comment]
Anything left to do here, @Bultako?

**Comment by Bultako** [comment]
This has been fixed in last version of `sphinx_rtd_theme`
I have removed the temporal fix in the css in this commit https://github.com/gammapy/gammapy/commit/eed5ccf7103ecc03f6dfd695ce55534bafc1952f

Closing now.
