### ISSUE TITLE
Fix test_compute_npred_cube and test_reproject_cube

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#217]
In #216 the following test failures surfaced:
- `test_compute_npred_cube`:  https://travis-ci.org/gammapy/gammapy/jobs/43002008#L2054
- `test_reproject_cube`: https://travis-ci.org/gammapy/gammapy/jobs/43002008#L2229
- `test_gaussian_sum_moments`: https://travis-ci.org/gammapy/gammapy/jobs/43002740#L774 (although this is fixed by @adonath in #215 .

I will `xfail` those tests for now and then look at those tests later and attach a fix here.

Maybe `reproject` changed in `master`?

**Comment by adonath** [comment]
Resolved by #753.

**Comment by cdeil** [comment]
Thanks @adonath for fixing and triaging Gammapy issues!
