### ISSUE TITLE
Continuous testing on Windows with AppVeyor

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#218]
Now that Github has proper support for multiple PR check services (see https://github.com/blog/1935-see-results-from-all-pull-request-status-checks) I've activated Windows testing for Gammapy:
https://ci.appveyor.com/project/cdeil/gammapy

I have no idea if Gammapy work on Windows or how easy it is to configure the tests there ... this is an experiment and I'll disable it if it doesn't work OK.

@adonath You'll start seeing AppVeyor messages on pull requests ... ignore them for now if there's build failures.

**Comment by cdeil** [comment]
I don't know about tests, but at least building conda packages for Gammapy seems to work:
https://anaconda.org/astropy/gammapy/files

@bsipocz - I'll try activating Appveyor for Gammapy now following the instructions in
https://github.com/astropy/ci-helpers#appveyor
but I might need some help.

**Comment by cdeil** [comment]
I've been working on this a bit in #414.
First successful test build of Gammapy on Windows:
https://ci.appveyor.com/project/cdeil/gammapy/build/1.0.5/job/baj28s8bm7hf9v8d

The test coverage can be extended of course, but I'll close this issue for now.
@bsipocz - If you think there should be more builds on Windows (e.g. docs) or more dependencies installed or things set up differently, please file a new issue.

**Comment by bsipocz** [comment]
@cdeil - great to see that this went smoothly :)
