### ISSUE TITLE
Parameter option in likelihood interface

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#2180]
@adonath - the likelihood interface currently sometimes has `parameters=None` and sometimes no default for `parameters`:
```
$ ack "def likelihood\(" gammapy
gammapy/cube/fit.py
162:    def likelihood(self, parameters):

gammapy/utils/fitting/tests/test_fit.py
28:    def likelihood(self, parameters, mask=None):

gammapy/utils/fitting/datasets.py
25:    def likelihood(self, parameters):
86:    def likelihood(self, parameters=None):

gammapy/spectrum/flux_point.py
1235:    def likelihood(self, parameters):

gammapy/spectrum/dataset.py
114:    def likelihood(self, parameters=None):
347:    def likelihood(self, parameters):
```
This inconsistency showed up in static analysis [here](https://lgtm.com/projects/g/gammapy/gammapy/snapshot/4f5cc39dda7fb5359a7c1143d76836a2f58f8c7e/files/gammapy/utils/fitting/datasets.py?sort=name&dir=ASC&mode=heatmap#x2208ea18eb931150:1).

I guess the long-term solution is to remove the `parameters` option completely, and to introduce a separate `parameters_update` method?

Also it look like often the `parameters` input argument to the likelihood methods is often unused, e.g. here:

https://github.com/gammapy/gammapy/blob/aea18a3d2f9ae0e92bf4af51066bdbaf12b96ec3/gammapy/spectrum/dataset.py#L347-L359

I don't understand why this doesn't show up in static analysis e.g. from pylint or on LGTM.

This test case should be updated now that the interface was changed in #2170:
```
gammapy/utils/fitting/tests/test_fit.py
28:    def likelihood(self, parameters, mask=None):
```

@adonath - Thoughts?

**Comment by adonath** [comment]
@cdeil Actually `parameters` is not used at all in the `.likelihood()` methods. The parameter update happens in the `Likelihood` wrapper class. I think we can just remove the `parameters` argument for now. For the parallel evaluation of datasets we'll either re-introduce it or replace by something like `update_parameters()` as you suggested. I can prepare a PR...

**Comment by cdeil** [comment]
Reviewing where / how we currently update parameters, and to decide on a sane caching strategy within datasets, is not something that can be done quickly. 

I think it's non-controversial that parameter update (and resulting cache invalidation logic on some things on Dataset) is an independent action from evaluating the likelihood, so `likelihood` should not have a `parameters` argument. E.g. one might just want to compute model images, or compute likelihoods within different sub-regions of the dataset. So +1 to simplify things now if you can do it quickly.

**Comment by adonath** [comment]
The parameter option was removed in #2184.

**Comment by cdeil** [comment]
🎉 Thanks 🎉
