### ISSUE TITLE
Improve PSF3DChecker

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#2181]
The `PSF3DChecker` should be improved.

* https://github.com/gammapy/gammapy/blob/master/gammapy/irf/psf_check.py
* https://github.com/gammapy/gammapy/blob/master/gammapy/irf/tests/test_psf_check.py

It's currently the slowest automated test in Gammapy, taking 6.4 seconds on my machine (see [here](https://gist.github.com/cdeil/16f259226bf5e35c36d504f187b48a26)).

It looks like the check methods are implemented as Python for loops, where most or all of them could be written with a few lines of Numpy array expressions instead. That should drastically reduce the code size and runtime.

There's also this code which basically re-implements a PSF method to compute an integral in Gammapy in the checker - that should be removed or rewritten:
https://github.com/gammapy/gammapy/blob/2fab5df0ed27491cf8c3eb4836db98da41aeb794/gammapy/irf/psf_check.py#L200-L203

If this is not possible for some check, we could change to a simpler test - the main point of the automated tests is to make it easy to check for obviously bad IRFs for batch processing (i.e. the people producing IRFs in CTA, HESS, .... or as a quick check when consuming or doing data quality for new FITS data).

I have a slight preference for improving the checker code in Gammapy, as opposed to just deleting it again, as we make a push for code quality and v1.0 in Gammapy. But removing is also an option, with the assumption that such checker code would re-appear in ctapipe or Gammapy in future years.

This code was added in #763 and #767 

cc @lmohrmann or @dltiziani

**Comment by cdeil** [comment]
See #2532

**Comment by adonath** [comment]
The code has been deleted in #2532. So there is nothing to improve anymore...closing the issue now.
