### ISSUE TITLE
Refactor tests in gammapy.utils.fitting.tests

### ISSUE THREAD

**Issue by adonath** [gammapy/gammapy#2193]
Currently there is a lot of code and even test duplication in `gammapy.utils.fitting.test`. We have unit test for the individual backends `test_scipy.py`, `test_iminuit.py` and `test_sherpa.py`, where we test on the same test function which is re-defined multiple times. In addition we test again all backends in `test_fit.py` file via the `Fit` API.

I think we should give the tests in `test_fit.py` priority and only implement cases which are not covered in the individual `test_sherpa.py` etc. We should all share yes function for optimisation.

**Comment by adonath** [comment]
Refactoring and simplifying tests will be a big topic for after v1.0. Re-labelling now...

**Comment by registerrier** [comment]
This requires a broad clean-up over the full code base.  Closing this specific issue.
