### ISSUE TITLE
ValueError in AltAz transforms due to astropy cache

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#2194]
It can happen that all AltAz transforms fail in gammapy. This seems to be due to some incorrect behavior in sidereal time calculation. 

This kind of behavior has been discussed in https://github.com/astropy/astropy/issues/6910. But it seems it is still present with newer versions of numpy and astropy. I had the problem with astropy version 3.1.1 and 3.1.2 as well as numpy 1.15.4 and 1.16.3.

Here is a typical error message from a failing test:
```
>                   raise ValueError('Column {} failed to convert: {}'.format(col.name, last_err))
E                   ValueError: Column year failed to convert: invalid literal for int() with base 10: '<!'
```

This issue is connected with time handling. It can be tested using the code snippet proposed in the astropy issue:
```
import astropy.units as u
from astropy.time import Time
from astropy.coordinates import SkyCoord, EarthLocation
keck = EarthLocation.from_geodetic(lat=19.8283*u.deg, lon=-155.4783*u.deg, height=4160*u.m)
sc = SkyCoord(ra=4.88375*u.deg, dec=35.0436389*u.deg)
barycorr = sc.radial_velocity_correction(obstime=Time('2016-6-4'), location=keck)
```

Ultimately the issue is connected to the IERS file handling. To do the time conversions, a file is downloaded periodically from the IERS website. 
 See http://docs.astropy.org/en/stable/utils/iers.html
In the latter page, the right procedure for clearing the cache is explained:
```
from astropy.utils.data import clear_download_cache
clear_download_cache()
```
The time handling in gammapy is explained [here]
(https://docs.gammapy.org/0.11/utils/index.html#time-handling-in-gammapy), see also issue #284 .

This issue is likely to happen randomly and rarely when the IERS file gets corrupted. The correct approach to solve it is likely to apply the `clear_down_cache()` function of astropy. This could be documented in the Time handling doc page, or in a known issues page in the documentation.

**Comment by adonath** [comment]
I think we haven't seen this issue in along time, will close now.
