### ISSUE TITLE
How to write analysis pipelines in / with Gammapy?

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#220]
@pflaumenmus and I discussed how to build powerful and simple analysis pipelines today.

Meaning given a bunch of input data and analysis parameters (possibly different sets), how to best orchestrate running a bunch of (sometimes interdependent) analysis tasks ... basically what `make` does (parallelisation, restart), but possibly using a CPU cluster and with better logging / monitoring / syntax.

Soon we'll want to run analysis pipelines like
- (event selection) -> (event binning) -> (background modeling) -> (likelihood fitting)

for a single target or a source catalog pipeline in Gammapy and we should come up with a good solution (probably Python-oriented for us ...)

Here's some options ... I won't describe them here, this is more of a not to self that I don't forget about these tools:
- Write Python functions and classes to execute steps and sometimes launch other tools (Python or not) using [subprocess](https://docs.python.org/3/library/subprocess.html) or to submit jobs to the cluster batch system .... this is what we currently do in the HGPS pipeline.
- [ctools](https://github.com/ctools/ctools/blob/devel/examples/make_binned_analysis.py) has more well-defined tools and containers that the steps use to communicate (each tool is a GApplication and they always communicate with GObservations).
-  [pytest](http://pytest.org/latest/) and [pytest-xdist](https://pypi.python.org/pypi/pytest-xdist) have powerful test setup, running and parallelisation and we already use it for Gammapy tests and HESS system tests, so there's some know-how present ... but it's not really a general pipeline tool.
- I've looked around for Python packages to do this a bit ... there's a ton, but none really sticks out ... here's a few I want to try out: [luigi](https://github.com/spotify/luigi), [ruffus](http://www.ruffus.org.uk/), [jug](https://pythonhosted.org/Jug/). There's also [joblib](https://pythonhosted.org/joblib/) and [ipython parallel](http://ipython.org/ipython-doc/dev/parallel/) and [celery](http://www.celeryproject.org/).
- And there's Jenkins and plugins like [workflow](http://jenkins-ci.org/content/workflow-plugin-10) that have a very nice production-quality dashboard and are scriptable, so could be options to run things like a CTA survey analysis pipeline, but probably overkill.

@adonath Please comment if you have any thoughts / preferences.
@pflaumenmus Let us know what you choose for scripting of your pipeline prototype.

**Comment by cdeil** [comment]
Just found this: https://github.com/taldcroft/pyyaks

**Comment by adonath** [comment]
By now the package structure of Gammapy reflects the overall analysis workflow like: data -> makers -> datasets -> modelling / estimators. For the high level interface we have the `Analysis` class. Any improvement to this should come after v1.0
