### ISSUE TITLE
Improve gammapy.spectrum.cosmic_ray_flux

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#2213]
We have [gammapy.spectrum.cosmic_ray_flux](https://docs.gammapy.org/0.12/api/gammapy.spectrum.cosmic_ray_flux.html) which needs to be removed or improved.

It's not well-tested, see [coverage report](https://coveralls.io/builds/23806181/source?filename=gammapy%2Fspectrum%2Fcosmic_ray.py).

This is a bit related to the case of crab spectrum and the API question there, see #1788 .

Can [SpectralModel](https://docs.gammapy.org/0.12/api/gammapy.spectrum.models.SpectralModel.html) represent fluxes per solid angle, i.e. CR surface brightness in `m^-2 s^-1 TeV^-1 sr^-1`?

If yes, we could return `SpectralModel` objects here and use the existing classes. If no, then we could keep as-is and evaluate directly and just improve docs and tests.

But the first question is whether to remove completely, or whether to keep and polish.
-> I'm +1 to keep and polish and am volunteering to do this for v0.13 in this case, because I think the CR electron and proton spectrum is quite commonly used by gamma-ray people (e.g. I used the electron spectrum once to do a rough estimate if HESS can see the Fermi bubbles, that's when I added this).

@adonath @registerrier - Thoughts?

**Comment by adonath** [comment]
I agree the `cosmic_ray_flux` method might be useful. But it should be adapted to return an instance of `SpectralModel`. Technically all our spectral models can represent flux per solid angle, so I think this is not a blocker.

**Comment by cdeil** [comment]
Looks like some methods do work, and some don't for spectral models per solid angle:
```
>>> import astropy.units as u
>>> from gammapy.spectrum.models import PowerLaw
>>> model = PowerLaw(amplitude="1 cm-2 s-1 TeV-1 sr-1")
>>> model(1 * u.TeV)
<Quantity 1. 1 / (cm2 s sr TeV)>
>>> model.integral(1*u.TeV, 10*u.TeV)
<Quantity 0.9 1 / (cm2 s sr)>
>>> model.plot(energy_range=[1, 10]*u.TeV)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/deil/work/code/gammapy/gammapy/spectrum/models.py", line 280, in plot
    flux = self(energy).to(flux_unit)
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.7/site-packages/astropy/units/quantity.py", line 671, in to
    return self._new_view(self._to_value(unit, equivalencies), unit)
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.7/site-packages/astropy/units/quantity.py", line 643, in _to_value
    equivalencies=equivalencies)
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.7/site-packages/astropy/units/core.py", line 989, in to
    return self._get_converter(other, equivalencies=equivalencies)(value)
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.7/site-packages/astropy/units/core.py", line 920, in _get_converter
    raise exc
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.7/site-packages/astropy/units/core.py", line 906, in _get_converter
    self, other, self._normalize_equivalencies(equivalencies))
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.7/site-packages/astropy/units/core.py", line 890, in _apply_equivalencies
    unit_str, other_str))
astropy.units.core.UnitConversionError: '1 / (cm2 s sr TeV)' and '1 / (cm2 s TeV)' are not convertible
```
So I'm not sure returning a `SpectralModel` for this is a good idea.

@adonath - Thoughts?

**Comment by adonath** [comment]
@cdeil The `.plot()` method uses default units for SEDs. I don't see a problem when this fails, either users have to set the `flux_unit` argument or we have to change the code to take the default unit from the `amplitude` parameter or similar. I'm still in favour of returning a `SpectralModel` object...

**Comment by registerrier** [comment]
I am also +1 for that solution. 
I am not sure that there is a solid use case for CR spectra as `SpectralModel`, since we would not fold them. But having `SpectralModel` able to deal with intensities seems useful e.g. Diffuse Galactic and Extragalactic backgrounds.

**Comment by cdeil** [comment]
OK, I'll try to change to return a `SpectralModel` for this and open a PR soon.

**Comment by cdeil** [comment]
Actually it's unlikely that I'll get to this before going on vacation tomorrow. So I'm un-assigning myself here and will ask for volunteers for this in the weekly dev call tomorrow.

To summarise the outcome of the discussion above: the task here is to make a PR that updates [gammapy/spectrum/cosmic_ray.py](https://github.com/gammapy/gammapy/blob/master/gammapy/spectrum/cosmic_ray.py) and [gammapy/spectrum/tests/test_cosmic_ray.py](https://github.com/gammapy/gammapy/blob/master/gammapy/spectrum/tests/test_cosmic_ray.py). 

The function `cosmic_ray_flux` should be renamed to `cosmic_ray_spectrum` and rewritten to return a spectral model, using the exising Gammapy spectral model classes (see [here](https://docs.gammapy.org/0.12/spectrum/index.html#module-gammapy.spectrum.models)) and deleting the current `_power_law` and `_log_normal` helper functions.

The tests should execute `cosmic_ray_spectrum` once for each particle type, and then call `evaluate` or `integral` for the returned spectrum for one energy or energy range, and assert on the resulting value, possibly using `pytest.parametrize` as in [gammapy/spectrum/tests/test_crab.py](https://github.com/gammapy/gammapy/blob/master/gammapy/spectrum/tests/test_crab.py)
To execute the tests locally and to check code coverage, the following command can be used:
``` 
pytest -v gammapy/spectrum/tests/test_cosmic_ray.py --cov=gammapy.spectrum.cosmic_ray --cov-report=html
```

If anyone is interested in this task, please leave a comment here any time.

**Comment by cdeil** [comment]
This was done by @JouvinLea in #2282

Following the suggestion in https://github.com/gammapy/gammapy/issues/1788#issuecomment-499470416 we now have [create_crab_spectral_model](https://docs.gammapy.org/dev/api/gammapy.spectrum.create_crab_spectral_model.html)

I will do a follow-up commit in master to change  `cosmic_ray_spectrum` -> `create_cosmic_ray_spectral_model` so that we get a more uniform API.

**Comment by cdeil** [comment]
Done in b09efafa1c4830a16a2e3bed9fe1ca324d182eea
