### ISSUE TITLE
How to test logging in Gammapy

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#2216]
This is a reminder issue for myself to add a dev docs entry how to test logging in Gammapy.

It's triggered by https://github.com/gammapy/gammapy/pull/2214#discussion_r291045047 where @registerrier introduced the `capsys` pytest fixture (see https://docs.pytest.org/en/latest/capture.html#accessing-captured-output-from-a-test-function) in Gammapy, to check that some code generated a given log message.

That's one method we could use, probably there are others (that e.g. work via `logging` and not `stdout` and `stderr`). Should look around a bit and see what other projects use.

**Comment by adonath** [comment]
We now have some recommendation how to test warning from the log output. https://docs.gammapy.org/dev/development/howto.html#caplog-fixture I think any more detailed testing of log output is not required. Will close the issue now.
