### ISSUE TITLE
How to use `integral_error`?

### ISSUE THREAD

**Issue by dagnic** [gammapy/gammapy#2225]
Hello, 

From the quantities (eg. for a `PowerLaw`) `amplitude` and `index` and their uncertainties, how can I use the method `integral_error` to compute the flux and its uncertainty. I tried:

    p = PowerLaw(2, 0.1 /u.keV/u.s/u.cm**2, 1 * u.keV)
    p.integral_error(4*u.keV, 150*u.keV) 

but returns `ValueError: Covariance matrix not set.`. How can I give the input uncertainties (which keywords for kwargs)? 

Thanks

**Comment by adonath** [comment]
We don't have an API yet to define the parameter errors on initialisation of the model, but the covariance matrix can be defined later like so:
```
from gammapy.spectrum.models import PowerLaw
import numpy as np
from astropy import units as u

pwl = PowerLaw()
pwl.parameters.covariance = np.diag([0.1, 0.1e-12, 0]) ** 2
pwl.integral_error(1 * u.TeV, 10 * u.TeV)
```
You can check the order of the parameters with:
```
print(pwl.parameters.names)
```

If you want to define the full covariance (including off-diagonal entries), you can also give a 2D Numpy array:
```
pwl.parameters.covariance = [[...], [...], [...]]
``` 
I hope this answers your question.

**Comment by dagnic** [comment]
Yes it does! Thanks!
