### ISSUE TITLE
Rotation angle of `SkyEllipse` model not conform with IAU convention for position angle

### ISSUE THREAD

**Issue by lmohrmann** [gammapy/gammapy#2228]
There's a convention for measuring angles on the sky by the IAU, see [here](https://en.wikipedia.org/wiki/Position_angle). It specifies that positions angles are measured counter-clockwise from the direction of positive declinations. Currently, the rotation angle `theta` of the `SkyEllipse` model does not follow this convention, it is measured clock-wise from the direction of positive right-ascension. Is there a specific reason for this? If not, should we switch to the IAU convention?

**Comment by luca-giunti** [comment]
Hi! Sure, I will address this shortly. One question first: our default frame for the spatial model is the Galactic one, so should we strictly apply this convention for any frame or would it make more sense to e.g. measure the angle clock-wise from the direction of positive galactic latitudes or longitudes?

**Comment by lmohrmann** [comment]
Good question. As far as I understand, the definition is always with respect to the equatorial system, but it's a bit more complicated to implement this in case the model is used in the galactic system of course...

**Comment by adonath** [comment]
Maybe it could make sense to support both. E.g. in gamma-cat we specify the reference frame for the position angle (see e.g. [Vela X](https://github.com/gammapy/gamma-cat/blob/master/input/data/2012/2012A%2526A...548A..38A/tev-000037.yaml#L17)). I think in literature you find both:
```python3
from gammapy.catalog import SourceCatalogGammaCat
gamma_cat = SourceCatalogGammaCat()
print(set(gamma_cat.table["morph_pa_frame"]))
```

So in some cases the position angle is measured against the north celestial pole in `icrs` sometimes in `galactic` coordinates. So maybe we should just add a `theta_frame` attribute? Or just take the frame the position is measured in? Alternatively we just stick with one convention, which is a bit easier and prevents confusion. Any opinion @registerrier or @cdeil?

**Comment by cdeil** [comment]
How does [this](https://photutils.readthedocs.io/en/stable/api/photutils.SkyEllipticalAperture.html) and [this](https://astropy-regions.readthedocs.io/en/latest/api/regions.EllipseSkyRegion.html) and [this](https://docs.astropy.org/en/stable/api/astropy.coordinates.SkyCoord.html) and [this](http://cta.irap.omp.eu/ctools/users/user_manual/models_spatial_src.html#elliptical-source) compare?

Maybe we're lucky and they are all the same, and we just should change direction?

I'm -1 on adding an extra `theta_frame` -- too complex. I think if you look at the examples I looked at you'll find that they always have one frame that the model is in. And if really a model transform to another frame is needed (very rarely), then one would do it following the small angle approximation at the model center to compute the new coordinate and position angle in that frame.

We can discuss and work this out here, but really my preference would be to finish  [the modeling PIG](https://github.com/gammapy/gammapy/blob/81d6cfc7f2268a35512c58c46e0924c4b04fed5f/docs/development/pigs/pig-007.rst#implement-sky-coordinate-handling) - at least model serialisation has to be considered also when discussing this question how exactly frame and position angle should work for spatial models.

**Comment by cdeil** [comment]
@lmohrmann - Please check if for Galactic coords the IAU convention is to measure wrt. Galactic frame north. I think that behaviour to always use the `model.frame` makes sense for us?
Maybe they don't say clearly? - then still I think it's the only sensible behaviour, that's also how DS9 regions work and display, no?

@lmohrmann or @luca-giunti - Would one of you be willing to implement this change and add 1-2 tests?

**Comment by adonath** [comment]
Adressed in #2300.
