### ISSUE TITLE
Further TS map improvements

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#223]
@adonath implemented TS maps in #215 and #234.
We now have the `gammapy-ts-image` command line script which calls the [ts_image](https://gammapy.readthedocs.org/en/latest/api/gammapy.scripts.ts_image.html) function.
The functionality is implemented in [gammapy.detect](https://gammapy.readthedocs.org/en/latest/detect/index.html#module-gammapy.detect).

Here's a list of further tasks for TS maps:
- [x] Fix TSMapResult.write (see #273)
- [ ] Add unit tests (see [here](https://coveralls.io/builds/1870426/source?filename=gammapy%2Fscripts%2Fts_image.py) and [here](https://coveralls.io/builds/1870426/source?filename=gammapy%2Fdetect%2Ftest_statistics.py))
- [x] Add `nfev` = number of function evaluations to results
- [x] Possible to put `NaN` for pixels with invalid results?
- [x] What about the artefacts for `gammapy-ts-image all.fits.gz --scale 0.1 --model model.fits.gz --residual` ?
- [x] Add possibility to specify the output file name
- [ ] Move kernel pixel size computation from script to library
- [ ] Implement matched filter method (i.e. convolve with PSF-folded model image for Gauss noise ... unclear how to compute and use the matched filter for Poisson noise ... see Stewart paper) and compare to likelihood fitting
- [x] Add a test for the command line tool (see [here](https://github.com/gammapy/gammapy/blob/master/gammapy/scripts/tests/test_bin_image.py#L10) for an example).
- [ ] I think the coverage report for [test_statistics.py](https://coveralls.io/builds/2690491/source?filename=gammapy%2Fdetect%2Ftest_statistics.py) is incorrect, because the functions are wrapped before they are called. This should be fixed somehow, probably the only way is to add a [#pragma: no cover](http://nedbatchelder.com/code/coverage/excluding.html).

**Comment by cdeil** [comment]
@adonath Because I wasn't sure if you've started to improve `scripts/ts_image.py`, I've left it alone and only moved it to `dev/ts_image.py` in #230.

To get it back as a command line tool you need to move it to `gammapy/scripts/ts_image.py`, rewrite it in the style of all the other tools. Then import it in `gammapy/scripts/__init__.py` and add one line to the `entry_points` list in `setup.py`.
You should also clear out the old Gammapy from your `site-packages` and `bin` folder when you update master and `rm -r build docs/api docs/_build` to avoid issues because of old files lying around.

**Comment by cdeil** [comment]
@adonath I think you should have permissions to edit the description and task list above if there's something you think should be added / removed.

**Comment by cdeil** [comment]
Related: #252

**Comment by OlgaVorokh** [comment]
I would like to add unit-tests for TS maps, but I am not sure what can I do -- I can make a regression test that checks that there are no exceptions and output file is non-empty, but I don't know how to check correctness of this 10mb result file by hand

The links to coveralls might be broken

**Comment by adonath** [comment]
See my last comment #456
