### ISSUE TITLE
Fermi-LAT data with Gammapy tutorial

### ISSUE THREAD

**Issue by luca-giunti** [gammapy/gammapy#2232]
Hi, I have a question related to the [Fermi-LAT data with Gammapy](https://github.com/gammapy/gammapy/blob/master/tutorials/fermi_lat.ipynb) tutorial: there,  a binned counts-cube (i.e. a 3D `Map`) is generated from the event file (the product of `gtselect`) within gammapy. Later, the exposure map gets filled in such a way that it matches the counts-cube geometry.

Is there a specific reason why this procedure is more convenient than, more simply, generating the binned counts-cube with `gtbin` (choosing the option `algorithm=CCUBE`) and passing it to `gtexpcube2`, so that the geometry of the exposure naturally matches that of the counts-cube? Those could be then simply read as follows:
```
counts = Map.read("ccube.fits")
exposure = Map.read("expcube.fits")
```
This could possibly simplify a bit the tutorial.
Thanks :)

**Comment by adonath** [comment]
@luca-giunti The idea behind this is, that we have prepared Fermi-LAT all sky data in https://github.com/gammapy/gammapy-fermi-lat-data/tree/master/3fhl/allsky. Starting from this data and following the tutorial, you can do a Fermi-LAT analysis for any source on the sky without running the Fermi science tools at all. 

Of course you can also use the Fermi science tools to do the data reduction, but some users might not be familiar with it or don't want to install it. Does this answer your question?

**Comment by luca-giunti** [comment]
Ok, perfect! Thank you @adonath
