### ISSUE TITLE
Implement __repr__ / __str__ for dataset classes

### ISSUE THREAD

**Issue by adonath** [gammapy/gammapy#2234]
This is a reminder issue to implement `__repr__`,  `__str__` and or `.info()` methods for all our dataset classes. The string should summarise the most important info in the dataset, such as:

- type of the dataset
- type of the model
- type of the background model
- total counts
- total predicated number of counts
- type of the model
- number of model components
- type of spatial / spectral model
- type of the background model
- number of parameters
- number of free parameters
- degrees of freedom
- parameter values?
- type of the likelihood function
- likelihood value
- number of contributing bins from `mask_safe`
- number of contributing bins from `mask_fit`
- min / max energy range derived from `mask_safe`
- min / max energy range derived from `mask_fit`
- ...

Please add your suggestions in a comments below. Should we add "categories" in the string such as "Data", "Model", "Likelihood" to group the info in a meaningful way? Anybody interested in implementing this?

**Comment by registerrier** [comment]
I think one output most users will expect is the livetime of the Dataset. So it might necessary to store it as `meta` in the `MapDataset`.

**Comment by cdeil** [comment]
This would be great to have. Would it be implemented as a two-step "compute" and "format" part? Or would it be long `__str__` methods like what we have in `gammapy.catalog`?

It might be useful to keep `__str__` code and tests not too extensive for now (avoid generating a ton like [here](https://github.com/gammapy/gammapy/blob/master/gammapy/catalog/tests/test_gammacat.py#L368), and to first implement serialisation, and then think whether pretty-format `__str__` should start with the serialisation dict or be separate / parallel to that (i.e. gather info from all kinds of properties and methods, like a dataset serialisation or summary would. Especially for models we already have bad XML serialisation code, and I would prefer we get a nice XML and/or YAML serialisation (which I find quite pretty and human readable, could just be dumped via `__str__` for now) first.

**Comment by adonath** [comment]
@cdeil I don't fully understand your comment. I think the `__str__` representation of the dataset objects will be pretty much independent of the serialisation format we choose. The purpose is just totally different. I think it's clear that `__str__` does not contain all information from the dataset, in the sense that actually data is not included, but only summary numbers such as total counts, means, etc. The main purpose will be interactive use in notebooks and writing summary infos to file. e.g. to keep track of changes in the data of the datasets. 

I still agree a two step procedure could be useful, i.e. add something like a `.info_dict()`, which returns a `dict` with useful summary info (which can than be serialised if needed) and a `__str__` method, that relies on the info dict but formats it nicely.

I think I'll go ahead and make a proposal in a PR. Details can be discussed there.

**Comment by cdeil** [comment]
@adonath - about half of the list above concerns `__str__` for models. You can easily spend a few days and 100s of lines of code and tests to have good model description in a string (like we did in `gammapy.catalog` for the models there). Or you could spend that time on YAML serialisation and just print the YAML for now. My suggestion was to follow this second course of action and prioritise model serialisation, we really need it now if we want to design a high-level interface and storing models and fit results on disk (e.g. for HESS validation or other kinds of batch or really any analysis).

For datasets it's not clear to me how much this `__str__` info overlaps with models, or just things you have to or want to store in YAML when storing a dataset. There it might make sense to write `__str__` first, but my guess is that overall it would be faster to do the hard part, i.e. serialisation first, and then to add a small `__str__`. Trying to implement model and dataset serialisation will shine light on issues in our design and organisation of information and lead to changes.

@adonath - it's just a suggestion - if you want to add `__str__` now, OK, go ahead.

**Comment by adonath** [comment]
Done in #2287.
