### ISSUE TITLE
Implement and unify dataset residual computation

### ISSUE THREAD

**Issue by adonath** [gammapy/gammapy#2236]
Currently we implement a `.residuals()` method for the `SpectrumDatasetOnOff` and `FluxPointsDataset`. In general I think this is very useful and we should also implement it for the `MapDataset`. For the computation of the residuals we should probably offer some option such as:

- `data - model`
- `(data - model) / model`
- `(data - model) / sqrt(model)`
- Maybe some more fancy things like Li&Ma significance or a residual ts map or similar?

Any opinions which options to choose and how to name those?

**Comment by cdeil** [comment]
Fermipy has [this](https://fermipy.readthedocs.io/en/latest/advanced/residmap.html) which is a few 100 lines of code (see [here](https://github.com/fermiPy/fermipy/blob/master/fermipy/residmap.py).

We could add a method, but IMO it should be very simple and just 5 or 10 lines of code, e.g. sum cubes over energy, correlate with user-defined radius (could default to 0.1 deg) and then compute Li&Ma significance.

And then I'd suggest to link from the docstring to a notebook or docs page that explains how to check a 3D analysis. It usually involves residual maps and spectra for certain regions. So a tutorial like
https://enrico.readthedocs.io/en/latest/tutorial.html#check-results
would be appropriate to have in Gammapy IMO.

If you show how to compute 3-5 quantities that people sometimes want (e.g. the ones you mention above), for different spectral weightings and correlation kernels, I think that would be a better approach than to try and pre-script many of them in one or many residual methods.

@adonath @registerrier - What would you suggest to add as methods and as docs?

**Comment by adonath** [comment]
Done in #2293.
