### ISSUE TITLE
Period evolution in gammapy.astro.source.pulsar

### ISSUE THREAD

**Issue by dimauromattia** [gammapy/gammapy#2249]
Dear all,

I and @manconi found a possible error in the function period of https://docs.gammapy.org/dev/_modules/gammapy/astro/source/pulsar.html#Pulsar

In particular this function is defined as 
t = Quantity(t, "yr")
return self.P_0 * (1 + (t / self.tau_0)) ** self.beta

where beta is self.beta = (n + 1.0) / (n - 1.0) while it should be 1./(n-1.0).

**Comment by dimauromattia** [comment]
We also notice that also the function luminosity_spindown(self, t) is not defined correctly since self.beta defined as (n + 1.0) / (n - 1.0) misses a -. The correct definition is: self.beta = - (n + 1.0) / (n - 1.0)

**Comment by cdeil** [comment]
@dimauromattia - do you have time to send a PR with those fixes? Or should we have a look and do it?

I think you're the first to use that part of Gammapy.

Note that we do plan to clean up the PSR code (and all code in Gammapy in preparation for v1.0 in the coming months), see #2211 . But I wasn't aware of any incorrect equations, so thanks for bringing that up!

**Comment by adonath** [comment]
Thanks @dimauromattia, I can confirm this bug.

I just cross-checked against the formulae I gave in my [BSc thesis](https://pure.mpg.de/rest/items/item_912132_1/component/file_912131/content) and there they are stated correctly:

![image](https://user-images.githubusercontent.com/3715928/59912660-c3ff7180-9416-11e9-8d66-915baae6cfa6.png)

and

![Screenshot 2019-06-21 at 11 22 31](https://user-images.githubusercontent.com/3715928/59912701-df6a7c80-9416-11e9-86ad-a737df1826e0.png)
 
So this is definitely a bug in Gammapy...

**Comment by manconi** [comment]
Dear @adonath and @cdeil, 
thank you for checking and confirming the bug. 
I cross-checked  the effects of this bug. This should affect the computation of the following quantities for the class Pulsar:

-luminosity_spindown(self, t)
-period(self, t)
-period_dot(self, t)
-tau(self, t)

We can prepare a PR if needed, let me know!

**Comment by adonath** [comment]
@manconi Yes, please go ahead and prepare a PR to fix this.

This will also need an update of the reference values in the tests [here](https://github.com/gammapy/gammapy/blob/master/gammapy/astro/population/tests/test_simulate.py#L108), let me know if you need help with this. Thanks!

**Comment by adonath** [comment]
Fixed in #2294.
