### ISSUE TITLE
SpectrumDatasetOnOff lack of protection for undefined Livetime

### ISSUE THREAD

**Issue by tstolarczyk** [gammapy/gammapy#2256]
Hello,
Going from gammapy 0.9 to 0.12...

In dataset.py, SpectrumDatasetOnOff accepts to have Livetime undefined (Livetime=None by default) but then , in that case, lead to a crash in  setup_counts_vectors(self) because of a request to convert the livetime in unit "seconds" :

 livetimes = [obs.livetime.to_value("s") for obs in self.obs_list]

Still the case for the dev version.
I guess this should be protected.

**Comment by adonath** [comment]
Thanks @tstolarczyk! I guess there overall behaviour is alright, because you cannot stack the datasets in a meaningful way without the livetime info, but we should probably give a better error message in this case.

**Comment by tstolarczyk** [comment]
Thanks @adonath for considering. 
If conceptually Livetime is a required argument, then it should not have a default value. 

This is the same for all other unavoidable arguments, i.e. all except the masks : 
class gammapy.spectrum.SpectrumDatasetOnOff(model, counts, counts_off, livetime, mask_fit=None, aeff, edisp, mask_safe=None)

**Comment by adonath** [comment]
There might be the use case of e.g. fitting a pure counts spectrum with a spectral model. In this case quantities such as `livetime`, `aeff` and even `background` can be optional, but we don't have a consistent design for this yet. I'll keep the issue open as a reminder...

**Comment by adonath** [comment]
We will likely refactor the `SpectrumDatasetOnOffStacker` soon. I will change the milestone to v0.14 now.

**Comment by adonath** [comment]
In https://github.com/gammapy/gammapy/pull/2360, we added a `SpectrumDatasetOnOff.stack()` method, however I think this issue is still present (see https://github.com/gammapy/gammapy/blob/master/gammapy/spectrum/dataset.py#L841).
