### ISSUE TITLE
Dataset model fitting has a unit issue with PowerLaw2 

### ISSUE THREAD

**Issue by alexiscoutinho** [gammapy/gammapy#2261]
When jointly fitting CTA DC-1 spectrum observations with a PowerLaw2, the interpreter will eventually reach the method **integrate_model** of the class **SpectrumEvaluator** in **gammapy.spectrum.utils**. In the loop of **line 79**, the code iterates over the bases of "amplitude" to get the **ref_unit**:
```
for unit in self.model.parameters["amplitude"].quantity.unit.bases:
	if unit.is_equivalent("eV"):
		ref_unit = unit
```
However, this doesn't work for PowerLaw2 since its energy unit is not inside "amplitude". Shouldn't the code, alternatively, evaluate the model to get its output energy unit when this is not inside the "amplitude"?

**Comment by adonath** [comment]
Thanks @alexiscoutinho, I can confirm this bug. The solution here is just to refactor / simplify the `SpectrumEvaluator` code. The special unit handling in the part of the code that you quoted, seems to be there for no good reasons (not anymore probably...).
