### ISSUE TITLE
Exclusion mask never used in MapMakerObs

### ISSUE THREAD

**Issue by luca-giunti** [gammapy/gammapy#2266]
Hi! 

We noticed, together with @AtreyeeS, that an exclusion mask can be passed to the MapMaker and MapMakerObs, but it doesn't seem to be ever actually used.. Is that a known issue, or maybe we are missing something?

Cheers

**Comment by cdeil** [comment]
It was added because it's needed for the background FOV normalisation method, there you normalise outside the exclusion mask.

@luca-giunti - suggest to close this issue now. There's already 
 https://github.com/gammapy/gammapy/issues/2223 with some discussion concerning FOV normalisation.

**Comment by luca-giunti** [comment]
OK, thanks
