### ISSUE TITLE
Improve reflected regions finder

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#2267]
This issue lists some questions and possible changes and improvements to the reflected regions finder, following up on discussions with @registerrier and @adonath this morning.

This is still one of the most complex pieces of code in Gammapy and I think we should do one more attempt to make it better now, to have it in good shape for v1.0.

[PIG 10](https://docs.gammapy.org/dev/development/pigs/pig-010.html#rotated-regions) and  #2089 are related, and the current code is here:

https://github.com/gammapy/gammapy/blob/fe8ca7d6caac77b8a31efc8bec3b21d09aacf6c1/gammapy/background/reflected.py#L15-L255

The current algorithm is based on a `reference_map` with small pixels that is a local TAN projection centered on the observation pointing position. If the user provides an exclusion mask, that is reprojected onto that `reference_map`, and then for the reflected region finding, the input `exclusion` mask isn't used anymore. I think basically that's fine and all we can achieve, building up spherical sky region contains and overlap functionality and changing to purely spherical computations would require weeks of developments in `astropy-regions`, no-one is working on this, isn't feasible. If we basically stick with this method to have a PixelRegion based algorithm working with  a local TAN reference mask image, I think `ReflectedRegionsFinder` can be improved in several ways.

The current class has conflated `__init__`, `setup` and `run` methods, where part of the setup (making the reference_map) happens in `run`, which is why `run` has to call `setup`. The tests currently make one finder and then use it for multiple jobs, changing out things like which region to use (see [here](https://github.com/gammapy/gammapy/blob/fe8ca7d6caac77b8a31efc8bec3b21d09aacf6c1/gammapy/background/tests/test_reflected.py#L116). I suggest we change the class to do all setup in `__init__` (could call a setup method from `__init__`), and then have `run` be what `find_regions` does now. The only allowed way to use the class would be
```
finder = ReflectedRegionsFinder(...)
reflected_regions = finder.run()
```
or
```
finder = ReflectedRegionsFinder(...)
finder.run()
finder.reflected_regions
finder.other_things_for_debugging
```
which would allow to change `self.reference_map` to `self.exclusion_mask`, and to initialise it by reprojecting the user input exclusion mask onto it and to exclude the pixels in the on region also.

The basic algorithm could then just be a loop incrementing the rotation angle, and for each test position to check if it can be placed, and if yes, to also exclude it's pixels in `self.exclusion_map`, ending after taking one turn of 360 deg. We could delete the complex `_region_angular_size` and `self.excluded_pixcoords`. 
Probably the current algorithm is slow for large offsets (where there are many pixels in the map and regions to be placed), and all the time is spent in `test_reg.contains(self.excluded_pixcoords)` here:
https://github.com/gammapy/gammapy/blob/fe8ca7d6caac77b8a31efc8bec3b21d09aacf6c1/gammapy/background/reflected.py#L222
I think we could change that to `test_reg.to_mask`, which works on bounding boxes and thus should speed up the computation in most cases by an order of magnitude or two, with the same outcome:
https://astropy-regions.readthedocs.io/en/latest/masks.html

One question with this change is whether we need to keep support for the `min_distance_input ` and `min_distance` options (see examples at https://docs.gammapy.org/dev/background/reflected.html)?
It's currently based on an approximation that's only correct for circles - the distance is actually the distance between wedges starting at the pointing position covering a given region via rays that go outward from the pointing position. For other region shapes isn't not really imposing the right distances, they could be too large or too small depending on the regions shape (we could try TETRIS shapes, or a snake represented by a polygon.
If we can just remove those options, good. If people want them, probably the way to implement that feature would be to dilate the exclusion and placed region masks by the distance that was asked for, or to change from an `exclusion_mask` to a `distance_image` based algorithm (where the distance image is a generalisation of the exclusion mask)`, something we already had but that was removed in #2089 (grumble, grumble):
https://github.com/gammapy/gammapy/blob/407068311cbcc06d4359dd6b856c658ffc0688b0/gammapy/background/reflected.py#L204

So to resolve this I think we need to:
1. discuss a bit what min distance feature we need
2. make a notebook with two common cases that are slow (circle and some other shape at large offset, so that ~ 100 off regions result) and do a quick check if `region.to_mask` fully resolves any performance concern we have
3. improve and clean up the code, possibly as outlined above, or in a different way if that is our conclusion

@lmohrmann as probably most heavy user of reflected regions for the HESS validation paper - thoughts?

Also @registerrier @adonath or anyone interested - please leave a comment here.

**Comment by lmohrmann** [comment]
Hi, sorry for not replying earlier.

I did not really have performance issues with this algorithm, but I did not run it on many observations with a large number of Off regions. But if there is an easy way to improve performance, why not?

Concerning `min_distance`, I guess it's a nice feature that we should try to keep. I'd even say it's okay if the distance is fully correct only for circles - circles will be used 95% of the time, and I wouldn't even know how to define this distance in case of arbitrary shapes... It's easy for users to plot the regions and adjust the parameters if they don't like the outcome.

These are my 2 cents...

**Comment by adonath** [comment]
In #3426 I did some cleanup of the code mostly removing the `.setup()` method. I also change to a return pattern like:
```python3
finder = ReflectedRegionsFinder(...)
reflected_regions = finder.run()
```
I did some profiling and for an offset of `5 deg` and a circular region size of `0.07 deg`, which results in ~160 off regions:
```
        645686 function calls (632502 primitive calls) in 1.627 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    1.627    1.627 {built-in method builtins.exec}
        1    0.000    0.000    1.627    1.627 <string>:1(<module>)
        1    0.003    0.003    1.627    1.627 reflected.py:196(run)
8668/8478    0.007    0.000    1.030    0.000 decorators.py:752(__get__)
        1    0.000    0.000    0.999    0.999 reflected.py:178(angle_min)
        1    0.008    0.008    0.998    0.998 reflected.py:135(region_angular_size)
        1    0.000    0.000    0.968    0.968 wcs.py:953(region_mask)
        1    0.009    0.009    0.837    0.837 wcs.py:591(get_idx)
  826/495    0.008    0.000    0.741    0.001 wcs.py:1270(_array_converter)
      495    0.003    0.000    0.732    0.001 wcs.py:1276(_return_list_of_arrays)
        1    0.001    0.001    0.728    0.728 wcs.py:615(get_pix)
        1    0.001    0.001    0.708    0.708 wcs.py:690(pix_to_coord)
        1    0.001    0.001    0.707    0.707 wcs.py:1416(wcs_pix2world)
        1    0.011    0.011    0.658    0.658 wcs.py:1420(<lambda>)
        1    0.647    0.647    0.647    0.647 {method 'p2s' of 'astropy.wcs.Wcsprm' objects}
      163    0.002    0.000    0.532    0.003 circle.py:80(to_sky)
      165    0.008    0.000    0.414    0.003 wcs_helpers.py:13(skycoord_to_pixel_scale_angle)
      331    0.008    0.000    0.319    0.001 utils.py:501(skycoord_to_pixel)
      163    0.004    0.000    0.143    0.001 utils.py:569(pixel_to_skycoord)
        1    0.001    0.001    0.127    0.127 region.py:189(contains_wcs_pix)
```
So the algorithm runs really fast ~1.6s. At this point the actual bottleneck becomes the access to the cached pre-computed properties. In summary I think there is no reason to further improve the performance for now. I think the `min_distance` and `min_distance_input` parameters are correctly documented and could be kept a they are. Will close the issue for now...
