### ISSUE TITLE
Revise version combinations in CI

### ISSUE THREAD

**Issue by bsipocz** [gammapy/gammapy#2270]
[Edit 2021-11-01]: While the particulars below are not necessarily relevant, but the same issue stands for newer versions, e.g py 3.9 and 3.10 at the time of this update, and maybe also for numpy/astropy versions.

Currently I see several errors when running the tests with new numpy (dev or 1.17.0rc1) and new astropy (4.0dev). Looking around in the CI configs it seems that neither there are not tests with numpy dev, as well as there  is abundant python 3.5 testing but less for python 3.7 (e.g astropy dev will switch to be python 3.6+ soon, so no point testing it  with python3.5).

Also, I would suggest to revise the matrix with the aim to reduce a bit the footprint. E.g. at least use stages, e.g. if one generic build fails then don't run the whole matrix as the PR needs further commits anyway.

```
=========================================================================== FAILURES ===========================================================================
_____________________________________________________________________ test_energy_logspace _____________________________________________________________________

i = 2, stacklevel = 3

    def _index_deprecate(i, stacklevel=2):
        try:
>           i = operator.index(i)
E           TypeError: 'numpy.float64' object cannot be interpreted as an integer

/usr/local/lib/python3.7/site-packages/numpy/core/function_base.py:22: TypeError

During handling of the above exception, another exception occurred:

    def test_energy_logspace():
        energy = energy_logspace(emin="0.1 TeV", emax="10 TeV", nbins=3)
        assert energy.unit == "TeV"
        assert_allclose(energy.value, [0.1, 1, 10])
    
        energy = energy_logspace(emin=0.1, emax=10, nbins=3, unit="TeV")
        assert energy.unit == "TeV"
        assert_allclose(energy.value, [0.1, 1, 10])
    
>       energy = energy_logspace(emin="0.1 TeV", emax="10 TeV", nbins=1, per_decade=True)

gammapy/utils/tests/test_energy.py:16: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
gammapy/utils/energy.py:36: in energy_logspace
    energy = np.logspace(x_min, x_max, nbins)
<__array_function__ internals>:6: in logspace
    ???
/usr/local/lib/python3.7/site-packages/numpy/core/function_base.py:277: in logspace
    y = linspace(start, stop, num=num, endpoint=endpoint, axis=axis)
<__array_function__ internals>:6: in linspace
    ???
/usr/local/lib/python3.7/site-packages/numpy/core/function_base.py:128: in linspace
    num = _index_deprecate(num)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

i = 2, stacklevel = 3

    def _index_deprecate(i, stacklevel=2):
        try:
            i = operator.index(i)
        except TypeError:
            msg = ("object of type {} cannot be safely interpreted as "
                   "an integer.".format(type(i)))
            i = int(i)
            stacklevel += 1
>           warnings.warn(msg, DeprecationWarning, stacklevel=stacklevel)
E           DeprecationWarning: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.

/usr/local/lib/python3.7/site-packages/numpy/core/function_base.py:28: DeprecationWarning
====================================================== 1 failed, 858 passed, 463 skipped in 39.26 seconds ======================================================
```

**Comment by cdeil** [comment]
@bsipocz - agreed, our CI setup should be improved. Let's do that in ~ 1 month, after bumping version numbers and deciding on distribution (see #2218) - we probably also want to add builds that build pip and conda packages and then install things from a user perspective.

Adding a build with Numpy dev to CI now would be useful.

I've split out the `test_energy_logspace` issue you saw into a separate issue: #2271
It's another complex discussion and decision what to do, completely independent of this issue on CI.

**Comment by bsipocz** [comment]
>  we probably also want to add builds that build pip and conda packages and then install things from a user perspective

but do you really want to run these on all the commits in pull requests? how often are they breaking (when otherwise everything else is OK?)?

**Comment by cdeil** [comment]
@bsipocz - We should set up better CI and CD for Gammapy. Yes, we'll want to have extended CI that doesn't run all the time, but does packaging and science validation and benchmarking and will take hours. PRs are welcome any time of course, but at least I don't have time for this now, but plan to work on it in the coming months.

**Comment by adonath** [comment]
@Bultako Can you maybe check whether this issue has already beed addressed with the move to GitHub-actions?

**Comment by bsipocz** [comment]
The approach we took since then in e.g. astropy is to define environments at higher than CI levels e.g. in tox. 
The two important point then to have a combination that contains the oldest version of everything that you suppose to support. Keep the version numbers hard wired there, and to match whatever you have in your setup.cfg.

Then the other critical/useful combination is where you test with the development versions of your most important dependencies. E.g. numpy dev, astropy dev, etc, so you will spot any upcoming deprecation, API change, etc the earliest possible time. And then you can have a few intermediate combinations, e.g. the current versions, etc whatever comes up with pip.

I would expect that there will be recommendation documents coming up for the dev testing scenario soonish, in the wider scientific python world, that you can easily adopt then (e.g. first we need to build nightly builds, e.g. it shouldn't be the CIs that build from source of the dependencies, etc.)

On the other hand, I think the issue can be closed, it's a very generic reminder to keep in mind the whole parameter space of the dependency versions.

**Comment by Bultako** [comment]
Hi
we have now the following matrix set in Github actions builds:

```
- Python 3.7 | All deps | Pytest | Linux
- Python 3.7 | All deps | Pytest | Windows
- Python 3.7 | All deps | Pytest | Mac OS 

- Python 3.6.2 | Core deps | Pytest | Linux
- Python 3.8   | Core deps | Pytest | Linux

- Python 3.7 All deps | Notebooks tests | Linux
- Python 3.7 All deps | Build docs + Docstrings + NoDatasets | Linux
```

The versions of the dependencies are not pinned/hard coded in the config file, we build our environments for testing with what conda considers the most suitable versions to create the environment (I guess the latest stable version of each package) **So we do not test with dev versions of dependencies in our CI.** 

There was an attempt to test with dev version of Astropy (see config file below), but I guess we disabled this option because of having our CI blocking the PRs (?)

https://github.com/gammapy/gammapy/blob/dafdedd57dab1ad5b976d8dd2655c1ebfae6aadc/.github/workflows/ci.yml#L133-L138

Yep, I think we should all appreciate having recommendation documents for dev testing.

**Comment by bsipocz** [comment]
Some quick comments: 

- I strongly advise that for one run pin the dependencies to the oldest version you support. There can be hidden issues, and if you say you support numpy x.y and astropy a.b, then users can rightfully expect those to work. Test it, don't just assume that they keep working. Don't assume that conda will pick the right versions.

- Do test with newer python versions. 3.9 is not new anymore, and even 3.10 is almost out.

- right now that pip install is indeed the best I can offer for dev testing. If it's bothersome, you can still let it run as an `allowed_failure`. Ideally, after an initial period of fixes, it won't fail your builds, and the sooner you address issues with astropy dev, or propagate feedback back to astropy core that something is not OK the better.

**Comment by Bultako** [comment]
More comments on this :)

- The [recommended way to install Gammapy](https://docs.gammapy.org/dev/getting-started/quickstart.html) is using conda, and I think this is the main reason why we also use conda in our CI. 
- At this moment [we do not claim to support specific versions in the dependencies](https://docs.gammapy.org/0.18.2/install/dependencies.html#install-dependencies), should we? 
- I agree, we should add tests with Python 3.9 in the CI.

I guess that the important point in this issue is to decide if we add an "informative" build for dev and old versions of dependencies in our CI, and which dependencies to test.

**Comment by adonath** [comment]
A few quick comments form my side:
- I think the specific version of the dependencies just refer to the latest and earliest version supported, typically declared in https://github.com/gammapy/gammapy/blob/master/setup.cfg#L32
- +1 for the Python 3.9 build
- I guess changing to pip could make the CI setup faster, so maybe it's an option to consider...

**Comment by bsipocz** [comment]
I'm not advocating to change from conda to pip. If your only supported way to install with conda then I certainly wouldn't switch, except for dev testing, which is a preventive tool for your developers rather than for users.
But you surely agree that not all users start from a clean environment when they update their gammapy. And to stimulate that scenario you need to pin versions in CI, or use an old prebuild image.

**Comment by Bultako** [comment]
@bsipocz 
That's indeed a good catch, thanks! I think now the only way to update gammapy to newer versions and **guarantee** all the functionalities is installing the new gammapy version in a fresh new conda env. Actually, we do not have any instructions published in the docs on how to update gammapy.

@adonath 
I think we should add a small recipe in the docs on how to update gammapy, in the same spirit of the installation recipe. Maybe something like this:
```
curl -O https://gammapy.org/download/install/gammapy-0.18.2-environment.yml
conda env update -f gammapy-0.18.2-environment.yml
``` 

Re: pinning versions in the CI
I agree we should be consistent with what it is declared in https://github.com/gammapy/gammapy/blob/master/setup.cfg#L32 and declare the same package versions constraints in the [conda env file](https://github.com/gammapy/gammapy/blob/master/environment-dev.yml) we use for the CI.

I would also change the way on how to create the conda env in the CI, it is faster if we do use [mamba](https://github.com/mamba-org/mamba) for this step.

Re: testing dev versions of packages
I would also use pip to add a new "informative/allowed failures" build in the CI to test dev versions of dependencies, which ones? the core deps?

**Comment by bsipocz** [comment]
> I would also use pip to add a new "informative/allowed failures" build in the CI to test dev versions of dependencies, which ones? the core deps?

yes. at minimum numpy and astropy, but I would bring in any dependencies that ever caused you regressions or issues with a new release. And if you don't yet do it, I would raise all deprecation warnings (in fact all warnings) as exceptions, that would force you to fix them as soon as they cause problems.
