### ISSUE TITLE
404 errors on Maps docs pages

### ISSUE THREAD

**Issue by MaxNoe** [gammapy/gammapy#2285]
Clicking on the API reference in the maps section leads to 404 errors:
E.g. clicking any on the classes in the inheritance diagram:
https://docs.gammapy.org/dev/maps/index.html#class-inheritance-diagram

https://docs.gammapy.org/api/gammapy.maps.WcsMap.html#gammapy.maps.WcsMap

**Comment by cdeil** [comment]
I think this has been broken for years, see e.g. https://github.com/astropy/astropy/issues/4935

The question is what to do - either someone contribute a fix "upstream" in Sphinx or the Astropy Sphinx plugin, or maybe there's a way to just turn links off, i.e. just display the graph without linking to anything. Or we could also remove the diagram, it's not super-useful and we only show it in this one place.

Thoughts?

**Comment by Bultako** [comment]
It is indeed the only doc page from all the API docs where there is an inheritance diagram. I would remove this diagram, not only because of this issue, but mainly for consistency with the rest of the docs.

**Comment by cdeil** [comment]
Agree - let's just remove that diagram for now.
