### ISSUE TITLE
Fit stat, FCN and documentation

### ISSUE THREAD

**Issue by tstolarczyk** [gammapy/gammapy#2291]
Hello,
Gpy 0.12
I am doing a fit of a count map using Minuit, based on a IRF and model assumption (3D analysis). The fit converges and gives a FCN value as expected.
Despite my effort, I could no find the answer to that question in the documentation (sorry if I missed it) and the notebooks (that I was inspired by) do notsay anything :

- What is the function that is minimized ? 
or in other terms, what does the FCN value stand for?

I have of course an idea but I need to be sure to interpret the statistics, and compute a p_value.
Thanks.

Here a code extract :

"""

        # IRF for the current observation (depends in particular on livetime)
        expo, bckg, psf, edisp = GetIRFComponents(obs_param.axis,
                                                     pointing,
                                                     obs_param.livetime, 
                                                     perf, 
                                                     obs_param.geom,
                                                     obs_param.fov,
                                                     debug=False)

        ###############
        # INPUT DATA  #
        ###############
        # Create the signal and background theoretical models
        bckg_model    = BackgroundModel(bckg) # Background model
        spatial_model = SkyPointSource(lon_0=grb_ra, lat_0=grb_dec,frame="icrs") 
        grb_model = SkyModel(spatial_model=spatial_model, 
                             spectral_model=spectrum,
                             name="dummy")             
        dataset = MapDataset(model = grb_model,
                             exposure=expo,
                             background_model = bckg_model,
                             psf=psf,
                             edisp=edisp)
        
        #####################
        # GENERATE MC TRIAL #
        #####################
        npred = dataset.npred() # Countmap from the theoretical observation
        rng = np.random.RandomState(seed=51) # fixed random state
        counts = rng.poisson(npred.data) # Compute counts as a Poisson fluctuation
        counts_map = WcsNDMap(obs_param.geom, counts) # maps
        
        ###############################
        # SIGNAL AND BACKGROUND MODEL #
        ###############################
        bckg_fitmodel = BackgroundModel(bckg)
        bckg_fitmodel.parameters["norm"].value = 1.0
        bckg_fitmodel.parameters["norm"].frozen = False
        bckg_fitmodel.parameters["tilt"].frozen = True

        index_fit = 2
        norm_fit  = 1e-11/(u.cm)**2/u.s/u.TeV
        spectral_fitmodel = PowerLaw(index=index_fit, amplitude=norm_fit, reference="1 TeV")
        spatial_fitmodel  = SkyPointSource(lon_0=grb_ra, lat_0=grb_dec,frame="icrs") 
        
        fit_model = SkyModel(spatial_model = spatial_fitmodel,
                             spectral_model= spectral_fitmodel,
                             name="tobefitted") 
        fit_model.parameters["index"].frozen = True
        fit_model.parameters["lon_0"].frozen = True
        fit_model.parameters["lat_0"].frozen = True
        fit_model.parameters["amplitude"].frozen = False
        
        ###########################
        # FIT SIGNAL + BACKGROUND #
        ###########################
        fitdataset = MapDataset(model=fit_model,
                                exposure=expo,
                                counts=counts_map,
                                background_model=bckg_fitmodel,
                                psf=psf,
                                edisp=edisp,)

        # Fit
        fit = Fit(fitdataset)
        result = fit.run(optimize_opts={"print_level": 0})
        # Results
        lik_fit = result.total_stat
        ns_fit  = 0
        nb_fit  = 0
"""

**Comment by registerrier** [comment]
Hello @tstolarczyk , 
the `Fit` object minimizes the `MapDataset.likelihood()` function of the `MapDataset` you are passing to it. In that case, this is the Cash statistic -2*log(like).
I guess this could be made more explicit in the documentation/notebook.

**Comment by cdeil** [comment]
@tstolarczyk - This issue that it's not clear what FCN is was already extensively discussed in #2149 .
I'm closing this issue now as a duplicate.
It's still not cleaned up and fixed in master, but will be soon.

**Comment by cdeil** [comment]
x-ref #2546
