### ISSUE TITLE
Improve MCMC sampling code

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#2304]
As mentioned in #2289, we should improve the MCMC sampling code:

- Add automated tests using a very simple example that runs in 1 second
- Try to use only parameter values, not factors in MCMC code -- establish results with a test that has parameters of roughly `1, 1e-10, 1e10`.

Once that is done, we can try to refactor the code in sampling.py to have a well-defined interface like what we have in the `Fit` class, and to have `emcee` only as one supported backend, as suggested by @QRemy in https://github.com/gammapy/gammapy/pull/2255#issuecomment-509158205 .

**Comment by adonath** [comment]
@facero Do you maybe gave time to work on this in the coming weeks?

**Comment by facero** [comment]
Yes, good idea. This is long time overdue.

**Comment by adonath** [comment]
@facero Any chance the MCMC code will get some attention soon?

**Comment by facero** [comment]
I'm really bad at following up this topic. Sorry. Not sure I'll be able to work on it this week as we're preparing the CTA consortium meeting + I'm attending another collaboration meeting this week. If you find some other volunteers that would probably work faster

**Comment by adonath** [comment]
Preliminary solved with #3429, further discussion are in #3430.
