### ISSUE TITLE
How to implement PSF-convolved model image computation?

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#232]
For Gammapy we need code to compute PSF-convolved model images that works robustly, even if sometimes models are smaller than the data grid. And it should have high precision and be fast (with the user having a few parameter to tune precision vs. speed)

This is something that should probably go into Astropy, but for now I think we should develop one or two prototypes in Gammapy and make it work for the following source models: point, Gauss, Shell, image.

@adonath I've written down a few first thoughts ... but you're the image processing expert ... what do you think how this should be implemented?
http://nbviewer.ipython.org/gist/cdeil/1c7891317e3ab7e115cd

**Comment by cdeil** [comment]
Just to keep some notes ... I've discussed this with @adonath:
- We'll rasterize models and PSF to the data grid and do the convolution there.
- Spatial models should declare a bounding box size that fully contains them (or a radius as a function of containment, with default 99% and if the user needs speed she can choose 90% and if she needs better than 1% photometry, she can choose 99.9%)
- The data grid bin size always has to be chosen so that the PSF is well-sampled and the PSF is smooth and only has to be evaluated once. So for the PSF we can simply oversample with a factor ~ 10 to always get a high-precision PSF on the data grid.
- For model rasterization it's still not fully clear what the best option is ... specifically for points there's a few ideas how to rasterize them [here](http://stackoverflow.com/questions/1513811/getting-smooth-big-points-in-opengl) and [here](https://www.opengl.org/documentation/specs/version1.1/glspec1.1/node44.html).

**Comment by adonath** [comment]
Discussion on this will take place in #1971.
