### ISSUE TITLE
Missing minus sign in Gaussian models

### ISSUE THREAD

**Issue by alexiscoutinho** [gammapy/gammapy#2325]
I noticed that the `evaluate` method of the `SpectralGaussian` class is missing the minus sign of the exponent. Furthermore, the sign is missing in the html documentation of both models (log too).

**Comment by JouvinLea** [comment]
Thanks for pointing this out. Completely my fault.
I just did a PR to fix it

**Comment by cdeil** [comment]
Fixed by @JouvinLea in #2326 .
