### ISSUE TITLE
Add back pytest header

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#2336]
One thing that was lost in #2279 is the pytest header, with version information for dependencies. This is a reminder for myself to add it back in some form.
I'll wait a few days for the discussion in  https://github.com/astropy/astropy-APEs/pull/52#issuecomment-527203047 to settle and then see how to add it via a pytest plugin, or just a few lines of code in our conftest.py.

**Comment by adonath** [comment]
There is now https://github.com/astropy/pytest-astropy-header available, so we should just install and use it to the the pytest header back.

**Comment by adonath** [comment]
Addressed in https://github.com/gammapy/gammapy/commit/b76cb8e03331eae45d16ac5c36763866a691083a.
