### ISSUE TITLE
Clean up model names

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#2353]
This is a reminder issue for myself to clean up the model class names, once #2319 is done.
Moving the models broke all user scripts & notebooks anyways, so now is a good time to do renames of models.

Plan for names is to add "Source", "Spatial", "Spectral" and "Time" in a uniform way: https://github.com/gammapy/gammapy/blob/master/docs/development/pigs/pig-016.rst#introduce-gammapymodeling

**Comment by cdeil** [comment]
@adonath @registerrier and I discussed and agreed on model names yesterday:
https://github.com/gammapy/gammapy/wiki/Model-class-names

I will do the renames today.

**Comment by adonath** [comment]
The remaining action item here is to find a goo scheme and rename the `SkyModel` and `SkyDiffuseCube` models...

**Comment by adonath** [comment]
My proposed solution here is to allow for energy dependent spatial models. This means the functionality of the `SkyDiffuseCube` is taken over by the `TemplateSpatialModel`.

If we stick with the current `SkyModel` then we should probably rename the `BackgroundModel` to `DataModel`. Or the other way around, rename `SkyModel` to `SourceModel`.

**Comment by adonath** [comment]
After #3051 and #3089, the background handling is taken over by the `FoVBackgroundModel` class. The current `BackgroundModel` ca still be used to handle template in reconstructed energy. The Plan here should be to replace this with `TemplateSpatialModel` and `apply_irf={"exposure": False, "psf": Falsse, "edisp": False}` and document it. Then the `BackgroundModel` class could go...

**Comment by adonath** [comment]
Alternatively we could just rename `BackgroundModel` to `NpredTemplateSpatialModel` or `DataTemplateSpatialModel`...

**Comment by QRemy** [comment]
+1 to keep it and rename as`NpredTemplateSpatialModel`

**Comment by registerrier** [comment]
+1 to keep as well.
How about `CountsTemplateSpatialModel`?

**Comment by QRemy** [comment]
Counts would implicitly mean `int` no ? which is not the case

**Comment by registerrier** [comment]
> `Counts` would implicitly mean `int` no ? which is not the case

Right, indeed. If the terminology `npred`/`counts` is clear enough it should be fine to use `NpredTemplateSpatialModel`.
BTW does it really need to be `Spatial`?

**Comment by QRemy** [comment]
maybe `NpredTemplateSkyModel` as it takes a spectral_model as argument

**Comment by adonath** [comment]
Here is my overview:
- I think we should contrast the `Sky` prefix with either `Data` or `NPred'
- It needs  `Template` and `Model` somewhere
- If it remains on the `SkyModel` level, it should not include `Spatial`
- Alternative we have a `DataModel(spatial_model=, spectral_model=)`, but this maybe leads to far...

So I'd propose either `TemplateDataModel` or `TemplateNPredModel`, in contrast to `SkyModel`.

**Comment by adonath** [comment]
In #3337 the `BackgroundModel` has been re-anmed to a more generic `TemplateNPredModel`. So no remaining clean-up her.
