### ISSUE TITLE
Jupyter lab imports wrong gammapy

### ISSUE THREAD

**Issue by luca-giunti** [gammapy/gammapy#2357]
I am working in a gammapy-0.13 environment. However, when I run jupyter notebooks inside the environment for some reason the developement version of gammapy is imported (`gammapy.__version__`  yields '0.14.dev287+g3fd5e2676').

- from command line (inside the env):
```
~$ which python
/home/luca/anaconda3/envs/gammapy-0.13/bin/python
~$ which ipython
/home/luca/anaconda3/envs/gammapy-0.13/bin/ipython
~$ which jupyter
/home/luca/anaconda3/envs/gammapy-0.13/bin/jupyter
~$ which gammapy
/home/luca/anaconda3/envs/gammapy-0.13/bin/gammapy
~$ ipython
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import sys                                                                                       

In [2]: sys.path                                                                                         
Out[2]: 
['/home/luca/anaconda3/envs/gammapy-0.13/bin',
 '/home/luca/anaconda3/envs/gammapy-0.13/lib/python37.zip',
 '/home/luca/anaconda3/envs/gammapy-0.13/lib/python3.7',
 '/home/luca/anaconda3/envs/gammapy-0.13/lib/python3.7/lib-dynload',
 '',
 '/home/luca/anaconda3/envs/gammapy-0.13/lib/python3.7/site-packages',
 '/home/luca/anaconda3/envs/gammapy-0.13/lib/python3.7/site-packages/IPython/extensions',
 '/home/luca/.ipython']

In [3]: sys.executable                                                                                   
Out[3]: '/home/luca/anaconda3/envs/gammapy-0.13/bin/python'

```

- from jupyter lab:
```
import gammapy
gammapy.__version__

'0.14.dev287+g3fd5e2676'

import sys

sys.path

['/home/luca',
 '/home/luca/anaconda3/envs/gammapy-dev/lib/python37.zip',
 '/home/luca/anaconda3/envs/gammapy-dev/lib/python3.7',
 '/home/luca/anaconda3/envs/gammapy-dev/lib/python3.7/lib-dynload',
 '',
 '/home/luca/anaconda3/envs/gammapy-dev/lib/python3.7/site-packages',
 '/home/luca/gammapy',
 '/home/luca/anaconda3/envs/gammapy-dev/lib/python3.7/site-packages/IPython/extensions',
 '/home/luca/.ipython']

sys.executable

'/home/luca/anaconda3/envs/gammapy-dev/bin/python'
```
Help? :)

**Comment by cdeil** [comment]
Current working directory? Which gammapy is imported? Is it on your sys.path?

**Comment by adonath** [comment]
Just for completeness: what's the output of `which jupyter-lab`?

**Comment by luca-giunti** [comment]
@cdeil Current working directory is the home dir. `which gammapy` yields `/home/luca/anaconda3/envs/gammapy-0.13/bin/gammapy`. Above, you can see the sys.path both for plain python and from a jupyter lab notebook.

@adonath 
```
(gammapy-0.13) luca@apcnb1847:~$ which jupyter-lab
/home/luca/anaconda3/envs/gammapy-0.13/bin/jupyter-lab
```

**Comment by cdeil** [comment]
@luca-giunti - Please check which gammapy you import from Jupyter:
```
import gammapy
print(gammapy)
```
Is it the one in `/home/luca/gammapy`?
That's in your `sys.path`, so it's normal that it's picked up?

How did this get on your `sys.path`?
```
import os
print(os.environ["PYTHONPATH"])
```

The way `pip install -e .` works is that it puts an `easy-install.pth` pointing to your source dev into your site-packages. I have this:
```
$ cat /Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.7/site-packages/easy-install.pth 
/Users/deil/work/code/gammapy
```
So you could check your v0.13 site-packages, and if you have an `easy-install.pth` there delete it, if that's the issue.

**Comment by luca-giunti** [comment]
> @luca-giunti - Please check which gammapy you import from Jupyter:
> 
> ```
> import gammapy
> print(gammapy)
> ```
> 
> Is it the one in `/home/luca/gammapy`?

Yes, it gives `<module 'gammapy' from '/home/luca/gammapy/gammapy/__init__.py'>`.





> How did this get on your `sys.path`?
> 
> ```
> import os
> print(os.environ["PYTHONPATH"])
> ```

This raises `KeyError: 'PYTHONPATH'`, both in plain python and jupyter lab. It means it is not set, might be related to the issue?



> So you could check your v0.13 site-packages, and if you have an `easy-install.pth` there delete it, if that's the issue.

I don't seem to have it in the v0.13 site-packages, altough I have it in the dev site-packages (same as you)

**Comment by luca-giunti** [comment]
Solved! I must have installed a kernelspec at some point, which pointed to the dev environment. I run `jupyter kernelspec list` to localize and delete it. 

Thanks, sorry for the waste of time! :)
