### ISSUE TITLE
All-sky map plot bug

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#2369]
I noticed that the all-sky map plot is clipped both for AIT and CAR and the coordinate grid isn't properly aligned. See screenshots below.

@adonath - Maybe this is just a "off by one pixel" bug?

![Screenshot 2019-09-16 at 10 28 04](https://user-images.githubusercontent.com/852409/64944049-a3a44f00-d86d-11e9-913a-99acd5d508d3.png)
![Screenshot 2019-09-16 at 10 28 48](https://user-images.githubusercontent.com/852409/64944055-a7d06c80-d86d-11e9-8400-77239e3f34e7.png)

**Comment by adonath** [comment]
Fixed in master: https://github.com/gammapy/gammapy/commit/dc46f8a1378e4331c8666e07c982ce05d441745c

Result:
<img width="425" alt="image" src="https://user-images.githubusercontent.com/3715928/69919650-961b6000-147f-11ea-945d-4e82c57058a1.png">
