### ISSUE TITLE
Use float32 dtype for maps

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#2374]
Most of the memory and CPU time in Gammapy is related to maps.

Currently we have a mix of 32 and 64 bit float dtype for maps.

I suggest we chant to use 32 bit float as much as possible

I expect that this will significantly reduce memory use of Gammapy, and improve speed, with only ~ 10 lines of code change.

A related question that we could discuss here or elsewhere is whether we should change maps with `int` to `float32` also. My guess is that we use int64 currently for counts data in some places, so float32 would reduce memory use. Probably speed doesn't change, depending on what operations we do for these counts maps. Overflow shouldn't be an issue. Another advantage of using float maps everywhere is that possibly we can remove the complex logic to handle pixels that aren't "on the sky" like for AIT WCS, because then the float `nan` can be used everywhere, not a special int value like -1 and special code is needed for this.

It's non-trivial but not really hard to find the places where we create maps with undesired dtype. E.g. with this one line change
```
diff --git a/gammapy/maps/base.py b/gammapy/maps/base.py
index bec1eec0a..65dd9fcbb 100644
--- a/gammapy/maps/base.py
+++ b/gammapy/maps/base.py
@@ -70,6 +70,8 @@ class Map(abc.ABC):
 
     @data.setter
     def data(self, val):
+        print(f"\nCreating map with dtype {val.dtype} and shape {val.shape}")
+
         if val.shape != self.geom.data_shape:
             raise ValueError(
                 "Shape {val.shape!r} does not match map data shape {self.geom.data_shape!r}"
```
and running the gammapy.cube tests I get this:
https://gist.github.com/cdeil/fa92fd4c35bac6858fbbf687922dd5f2

We could also log the tracebacks showing the callers - probably it's just a few places in the code where we need to edit.

I'm not sure yet if / how it's possible to avoid re-introducing float64 or int dtypes in the future.
Probably we want to have a dtype check in the `map.data` setter, and e.g. log warnings or fail tests when float64 appears (but allow it generally for users of Map outside Gammapy)?

Yesterday, I was thinking something could be done at the Numpy array level, but now I don't think that's the case any more. Related: https://stackoverflow.com/questions/57982230/how-to-avoid-numpy-type-conversions

This is a reminder issue for me at the v0.15 milestone - but comments & feedback or help are welcome any time of course!

**Comment by registerrier** [comment]
Is this issue still relevant? All `Dataset` members are `float32` or `bool`. 
Now why is `counts` not a `int64`?

**Comment by adonath** [comment]
I think there is nothing left to be done here.
