### ISSUE TITLE
Add random_state parameter to functions that generate random numbers

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#238]
We should add a `random_state` parameter to all functions that generate random numbers.

Example how to do it (we should bundle a copy of the utility function)
http://photutils.readthedocs.org/en/latest/api/photutils.datasets.make_random_gaussians.html

List of functions that call `np.random`:
https://github.com/gammapy/gammapy/search?utf8=%E2%9C%93&q=np.random

**Comment by cdeil** [comment]
I've added the `check_random_state` utility function from scikit-learn to `gammapy.utils.random` in fb0e9c15766ef70ab53e7ef8794d5281965de159.
Keeping this issue open because it still has to be used throughout.

**Comment by cdeil** [comment]
@mapazarr - I'm assigning this issue to you.

The [make_test_observation_table](https://dl.dropboxusercontent.com/u/4923986/temp/gammapy-278/html/api/gammapy.datasets.make_test_observation_table.html) function you're adding in #278 should grow a `random_state=None` option as well and while you're at it, please clean up the other functions that generate random data to follow this uniform pattern as well.

An example of how to do it is [make_random_times_poisson_process](https://gammapy.readthedocs.org/en/latest/_modules/gammapy/time/simulate.html#make_random_times_poisson_process), although there I forgot to add `random_state` to the Parameters list in the docstring.

Probably best to leave #278 as is and do it after.

**Comment by cdeil** [comment]
We should probably add an entry to the developer FAQ at https://gammapy.readthedocs.org/en/latest/development/index.html explaining this pattern and linking to http://scikit-learn.org/stable/developers/#random-numbers (we simply do the same what they do).

**Comment by mapazarr** [comment]
Applying this in PR #283.

**Comment by cdeil** [comment]
Closing this issue. Adressed in #283 and #310 .
