### ISSUE TITLE
Model registry pattern

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#2387]
We currently have this coding pattern for spatial, spectral and time models:

https://github.com/gammapy/gammapy/blob/3e6a03386d5280d24ab64cc520cc2eddc023d0a5/gammapy/modeling/models/__init__.py#L10-L40

Now we introduced a model `tag` attribute like this:

https://github.com/gammapy/gammapy/blob/3e6a03386d5280d24ab64cc520cc2eddc023d0a5/gammapy/modeling/models/spectral.py#L437

I'd like to discuss a bit if we should keep as-is or change the model registry a bit.

- In the current approach, it's easy to forget to add something to the registry. E.g. `SkyDiffuseConstant` is currently missing.
- A dict mapping class name string to class object isn't super useful (invites typos), one could just have a list of classes, and then `cls.__name__` gives the name and `cls.tag` the tag.
- Since Python 3.6 it's very simple to auto-generate a list of subclasses, see [here](https://docs.python.org/3/whatsnew/3.6.html#pep-487-simpler-customization-of-class-creation).

I think my suggestion would be that we remove the manual registry dicts, and instead do the auto-registry of subclasses.

That always happens on import, so it does make it a bit harder to control for the unlikely problematic cases where different downstream packages (e.g. CTA GPS pipeline and HESS GPS pipeline or CTA EGAL people or something) define a Gammapy model sub-class with the same class name, and someone imports their packages together - then the later import clobbers the earlier. But overall this problem to have a global shared namespace for models in the registry remains, probably other packages and pipelines would still modify the current registry on init and just clobber.

We could maybe avoid this issue by keeping the dict instead of list, and use tag names as keys and try to make them unique, like here:

https://github.com/astropy/astropy/blob/a1e72dd7b8eca5fc95c9f40557e8ceaae30d4d81/astropy/io/misc/asdf/data/schemas/astropy.org/astropy/coordinates/angle-1.0.0.yaml#L5

But that seems like overkill at the moment - I think I would start by using auto-registry on subclassing, and just have a list like [here](https://docs.python.org/3/whatsnew/3.6.html#pep-487-simpler-customization-of-class-creation), and then only if needed later refactor again to something more general (keeping the auto-registry, just changing the registry data structure and mechanism).

@adonath @registerrier @QRemy or anyone interested - Thoughts?

**Comment by cdeil** [comment]
@watsonjj @kosack - Maybe you could also share your opinion here? I think you do have registries in ctapipe and already some experience with what coding pattern works well and what is problematic?

**Comment by cdeil** [comment]
Hmmm ... I just now found out that we have these spectral models in Gammapy:

- [gammapy.astro.darkmatter.DMAnnihilation](https://github.com/gammapy/gammapy/blob/d4db11d559b210c0e0d03bba75ddcff9c03e0511/gammapy/astro/darkmatter/spectra.py#L123)
- [gammapy.spectrum.tests.test_flux_point.ExpTestModel](https://github.com/gammapy/gammapy/blob/b95cb88682a2bd6fdd02a7ecd40405f88eec79f5/gammapy/spectrum/tests/test_flux_point.py#L50) and a few other spectral models that are only used for testing.

That makes it a bit less attractive to have auto-registry on subclassing, we probably don't want test models in the registry but they could end up there if someone for some reason imports the wrong sub-module.

- Keep the explicit registry and maintain it in `gammapy/gammapy/modeling/models/__init__.py`?
- Change to a list and make `model.tag` required via a base ABC?
- Import and add `gammapy.astro.darkmatter.DMAnnihilation`? Or does that cause circular import issues?

**Comment by kosack** [comment]
> @watsonjj @kosack - Maybe you could also share your opinion here? I think you do have registries in ctapipe and already some experience with what coding pattern works well and what is problematic?

We don't use them in ctapipe: we use instead a plugin-system so far for data readers, and that uses the standard pattern of searching for packages by name (in our case ctapipe_io_X) and then importing all of them.  Since they are subclasses of a base class, we also have a method to collect the names of all non-abstract child classes, after all imports are done.

**Comment by adonath** [comment]
I think the current solution with a hard-coded model registry is not as bad. It's not like model are added and removed on a daily (even monthly) basis. I agree it takes some care by the package maintainers, but as all registries are in a single place now, I would argue that for now we don't need anything better.

**Comment by adonath** [comment]
The current implementation we have is a list based registry, tags are checked on the fly using the `Registry.get_cls(tag)` method. I think this pattern is more then good enough for Gammapy v1.0.

@cdeil Do you propose anything else then the current registry system? If not I'd propose to close this issue...

**Comment by cdeil** [comment]
> Do you propose anything else then the current registry system?

Yes, I think we should polish registries and creation helpers some more:

- [ ] Add documentation
- [ ] Improve [Model.create](https://docs.gammapy.org/dev/api/gammapy.modeling.Model.html#gammapy.modeling.Model.create)
- [ ] Change catalog registry to also have the tag on the catalog classes, for uniformity with the other registries. Fix entry [here](https://docs.gammapy.org/dev/catalog/index.html#variables) in API docs - why does it currently give a 404 and not show the available catalogs?
- [ ] Decide on location of datasets registry, see [here](https://github.com/gammapy/gammapy/blob/3f0cc00c9e5b8d273b2ef4fc2ef0e5aca68c3f3a/gammapy/modeling/serialize.py#L7-L8), Must show up in API docs somewhere.
- [ ] Add background model registry?
- [ ] Add background maker registry?
- [ ] Add `DMAnnihilation` to spectral model registry
- [ ] Improve the `tag` of all the models to something that's simple to remember and type, "power_law" instead of "PowerLawSpectralModel"

Concerning `Model.create` and the registries: it should be very easy for users to interactively use that to make models. Currently it's not clear how to list models, including the tags that one needs to create them. And for a given model how to list the parameters one has to pass. We need a "list models" and a "show info for a given model" function somewhere. Either attached to the `Model` base class, or the `Registry` (thoughts where to put this?). When passing an incorrect thing like `"powerlaw" instead of "power_law" the error message should either say what's available, or explain how to get the list what's available.

This will be used by every Gammapy user daily, so a good user experience is important, and I think it's just ~ 1 more hour to discuss / design, and then ~ 1 day to implement all of the items above - most are very quick.

**Comment by adonath** [comment]
In https://github.com/gammapy/gammapy/pull/2944 we added the proposal for shorter model tags, which there implemented by @QRemy. I think by now the model registry is in a good state (and documented e.g. https://docs.gammapy.org/0.17/notebooks/models.html#Implementing-a-Custom-Model). Will close the issue now.
