### ISSUE TITLE
Add spectral model illustrations to the docs

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#241]
We should add an SED plot to the spectral model class docs like e.g. [BrokenPowerLaw](https://gammapy.readthedocs.org/en/latest/api/gammapy.spectrum.models.BrokenPowerLaw.html).

Also an SED plot showing all available SED models in the [gammapy.spectrum docs](https://gammapy.readthedocs.org/en/latest/spectrum/index.html) would be great!

**Comment by cdeil** [comment]
I noticed that we have examples for some spectral models how to plot them in the class docstring, but not for others. Also, the code examples include `plt.show`, but not the `import matplotlib.pyplot as plt` import, i.e. don't fully work when copy & pasting. I think we should either add the import, or remove the `plt.show` call, which means it still works by default in ipython and Jupyter, just in Python REPL the Figure doesn't pop up.

My suggestion would be to remove those examples from the class docstrings, and instead to add a section in the modeling docs or a notebook where we illustrate the built-in models in one place. We could probably use the model registries or `make_model` as in #2414 to make and plot all models. At least as far as I'm concerned, the idea is to not have to import and type all the model class names, to go that direction also in the docs (and then to improve the API, won't be perfect in v0.14 yet).

Example:

https://github.com/gammapy/gammapy/blob/9015b808c9f69966e7f3c2f5f5735ec034488e05/gammapy/modeling/models/spectral.py#L483-L492

Anyone interested to work on this in the next days (either for v0.14 or after)?
Otherwise I'd take a stab at it ...

**Comment by adonath** [comment]
I agree it would be nice to have a "model gallery". Let's try to implement this for v1.0.

**Comment by cdeil** [comment]
The task here is to improve the spectral model section here: https://github.com/gammapy/gammapy/blob/master/tutorials/models.ipynb

Make one or several nice Figures that illustrate all spectral models that we have:
https://github.com/gammapy/gammapy/blob/ee2535af97986f8df550b1fd9c0f2c0ae2d3c877/gammapy/modeling/models/__init__.py#L33-L52

Anyone interested / available to do this in October?

**Comment by adonath** [comment]
Implemented in #2742 .
