### ISSUE TITLE
Improve catalog source spatial models

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#2423]
To follow up on the discussion in #2420 from earlier today: we should add spatial model methods for 4FGL and HAWC, and review and improve all spatial model methods to fill elongation parameters (there's currently TODO entries for those), and we should also fill spatial model parameter errors. Finally, tests should be improved to add asserts establishing for one example per spatial shape that it's filled correctly. This could be one large PR, although probably a series of small PRs would be better.

@QRemy or anyone - interested to work on this in the coming weeks?

**Comment by QRemy** [comment]
I'll do it.

**Comment by cdeil** [comment]
The main next tasks here are:

- Fill spatial model parameter errors for all catalogs (similar to how it's done for spectral models already) and for each case have an assert on that parameter error value in the tests.
- Add spatial model for 1FHL and 2FHL (currently missing), trying to avoid copy & paste code duplication as much as possible?

For the second point, we could also delete 1FHL and/or 2FHL completely instead of fleshing it out, to remove the amount of code that we have, with the reasoning that very few users will use the older catalogs.

@adonath @QRemy - Thoughts?

@QRemy - Do you want to continue with this task or do other things?

**Comment by cdeil** [comment]
Discussed today in Gammapy dev call. Decided to remove 1FHL, but keep 2FHL.

@QRemy - Can you send two small PRs please, one that removes 1FHL, and a second one that adds at least one printout example reference for 2FHL?
https://github.com/gammapy/gammapy/tree/master/gammapy/catalog/tests/data

Then the other tasks to improve the spatial model code and tests are larger PRs for next week.

**Comment by QRemy** [comment]
Adressed in #2448, #2449, #2476 and #2478
