### ISSUE TITLE
Add Windows CI build for notebooks and docs

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#2430]
In https://docs.gammapy.org/0.14/notebooks/hess.html#Model-fitting I see that we're using `!cat model-best-fit.yaml` to show the file contents. This will not work on Windows, it probably causes a "command not found" error. I'm not sure if there is a good cross-platform solution, I just now asked here: https://discourse.jupyter.org/t/why-does-cat-work-on-unix-but-not-windows/2094/4?u=cdeil

This issue is a reminder for myself to add a Windows CI build that executes and tests the notebooks, or to extend one of the existing Windows CI builds in [azure-pipelines.yml](https://github.com/gammapy/gammapy/blob/master/azure-pipelines.yml). I expect that this will reveal a few small issues like `!cat` not working on Windows -- those should be fixed in the same pull request where the CI build is added.

**Comment by adonath** [comment]
In #2793 I added the notebook build for Azure.
