### ISSUE TITLE
Remove parameter scaling?

### ISSUE THREAD

**Issue by adonath** [gammapy/gammapy#2434]
In preparation of the H.E.S.S. DL3 data tutorial, I found issues with convergence of the model fits both using the `iminuit` and `sherpa` backend. In both cases the optimiser would try positions outside the map already on the first iteration, which currently leads to an error (whether this behaviour is a good one, is a different discussion...). The reason for this weird behaviour is, that we currently scale **all** parameters before the fit and only pass the `factors` to the optimiser.  E.g. if you do a crab analysis in `icrs` coordinates, the optimiser will try a step size in the order of ~10 deg in longitude, which does not make sense. There are now different solutions to fix this behavior:

- Some optimisers can take an initial estimate of the covariance matrix. We could assume plausible default errors for all parameters, but we need a way to build a global covariance matrix form these sub-covariances, e.g. by adding a `Parameters.concatenate()` method.
- We could add a `autoscale` flag to our `Parameter` class, to switch of the scaling for certain parameters (especially position...)
- We could remove the parameter scaling completely. This would actually be my favoured solution. Currently the parameter scaling is only really required (if at all) for the spectral `amplitude` parameter, where the diagonal entries on the covariance matrix can get very small. As we support units for parameters, the scaling can be achieved natively, by moving the scale to the unit of the parameter like `amplitude = u.Quantity("1.34 1e-12 TeV-1 cm-2 s-1")`. This puts a little bit of responsibility on the side of the user, but this can be handled with documentation if needed. Removing the scaling would simplify our `Parameter` class a lot. 

Any opinions @registerrier and @cdeil?

**Comment by registerrier** [comment]
I completely agree that in many cases the scaling is meaningless, in particular for coordinates which are defined only to a closed interval in the real set. 
Technically, it is probably only useful for `amplitude` parameter which can be distributed over several decades. We could alternatively use a log-like representation of the amplitude in the minimizer.  

Often other tools (e.g. sherpa, XSpec) have a `guess` or `norm` function that try to find the good `amplitude` of the model w.r.t. to the data. We could get rid of the amplitude scaling by adding such a functionality, namely `Fit.guess()`. This would require that we have a way to determine 'guessable' parameters, so this is likely not very different from adding an option `autoscale`.

So we might explore your second solution where the only `autoscale=True` parameters would be the amplitudes. If we have all the code there already for scaling, it might be bad to undo everything no?

**Comment by cdeil** [comment]
I removed the "bug" label - it there is still a bug, then @adonath please give an example and re-add the bug label. However, I by now also think we should try to remove the parameter scaling (once we have some validation, a week from now), or significantly change the scaling code, so I'm adding a "high-priority" label here.

**Comment by lmohrmann** [comment]
I've observed this problem in several fits now as well - the minimizer seems to jump outside the FoV already in the first step. To me, this is a clearly a bug!

Previously (e.g. in v0.12) it was possible to set `fit.datasets.parameters.apply_autoscale = False` and provide step sizes for all parameters by setting `fit.datasets.parameters.covariance`. This, unfortunately, does not seem to work any longer (at least the fit crashes with the same error in the cases I've tested). Has the parameter scaling been changed between v0.12 and v0.14?

**Comment by adonath** [comment]
@lmohrmann For v0.15 the behaviour is changed such that if the model component moves outside the image it is just ignored in the likelihood evaluation (instead of throwing an error). This seemed the more stable behaviour.

I just checked and indeed there was a small change in v0.14, that the caching of the fit parameters moved from the `Datasets` object to the `Fit` object, where we hide the parameters. So to restore the old behaviour, you have to use the following work-around:

```
fit = Fit([dataset])
fit._parameters.apply_autoscale = False
fit._parameters.covariance = np.diag([1, 1, 1])

result = fit.optimize()
```
In Gammapy v0.15 the covariance will be build "on the fly" from sub-covariances, which already simplifies the definition for complex models. So for v0.15 the issue will be gone.

In general I'm still in favour of removing the parameter scaling completely, but at the coding sprint we agreed, that we will only removed it once we have a high level benchmark with a complex model fit in place. With this benchmark we can measure, what difference the parameter scaling makes in performance / convergence.

**Comment by cdeil** [comment]
We're mixing discussions / issues here.

Whether to remove the `value = scale * factor` split is really a separate question if / how to set initial step sizes for Minuit.
It's mixed in the current implementation, but even if we remove `scale` and `factor` and just have value, the source-position based failing fits where the optimiser takes a bad first step will remain. I don't know if it was on Github or just in person, but basically the solution is to add a default initial step of roughly ~0.02 deg for lat, and `0.02 deg / cos(lat)` for lon, instead of what we do currently.

Having a minimal currently failing test (e.g. very briefly to the left or right of `lon=0 deg`, possibly going to `lat = 88 deg` or so, would be extremely useful as regression test. @lmohrmann or @adonath - can you create one?

**Comment by lmohrmann** [comment]
@cdeil: I think you're right, the issue that I've been observing is likely connected to badly chosen step sizes for the coordinates, not necessarily the scaling.

@adonath: you can probably create a regression test as @cdeil proposes quicker than I can, but let me know if you don't have time, then I will have a go. Would be really nice to get this fixed for  v0.15 -- I think many testers will encounter this issue. When do you plan to do the release?

**Comment by adonath** [comment]
There is now the possibility to store the fit trace for debugging: #3074. So this test is rather simple to implement. In general I think removing the parameters scaling is still a good idea...these kind of parameter transformation should happened on the optimisers side, because every optimisers handles it differently...

**Comment by lmohrmann** [comment]
Just a side note, maybe helpful: the other day I had the issue that I wanted to fit a `NaimaSpectralModel`, which usually have very large values for the amplitude parameter. It seems that the default behaviour was to apply no scaling to the parameter, which had the result that the fit did not change the parameter value at all, and set the error to 2.0 (exactly), while still reporting a successful fit. Turning the scaling on for the parameter fixed this.

**Comment by adonath** [comment]
Thanks @lmohrmann, my initial proposal for this was to just move the scale to the unit of the parameter. Like `1 * 1e-12 TeV-1 cm-2 s-1` instead of `1e12 TeV-1 cm-2 s-1`. Have you tried this as well? I realise this is less convenient, however we could document e.g. here: https://docs.gammapy.org/0.18.2/tutorials/modeling.html, here https://docs.gammapy.org/0.18.2/howto.html or possibly a "know issues" section.

**Comment by lmohrmann** [comment]
No, have not tried attaching the scale to the unit. So your proposal would be to remove the `scale` attribute altogether?

**Comment by adonath** [comment]
Yes, I think so. This linear scaling can be achieved with the unit handling as well. My main conclusion from the issue here, is that neither "scale all parameters" nor "scale no parameter"  works as a reliable default in all cases. However the case, where the amplitude is super small (like for the `NaimaModel`) is much more rare than e.g. the fitting of `lon` and `lat`, where the scaling is problematic. 

We could only make a significant improvement if we add more meta data on the parameters such as type or more advanced scaling such as log or similar and this I is too much work for now. My guess is that the fit convergence without scaling is just fine in most cases, but we have to check of course...

Remaining action items:
- Fully disable the scaling and check convergence on our validation analyses
- Add documentation on the unit handling
- Add documentation on setting an initial covariance

**Comment by adonath** [comment]
I quickly tested and removing the parameter scaling by default results in a lot of test failures and convergence issue. So let's keep it for now. However in #3394 I'm adding a `scale_parameters` option which makes the configuration easier...

**Comment by QRemy** [comment]
We could introduce a scaling attribute on the parameter object so we can decide what to do with scaling case by case.
