### ISSUE TITLE
Matplotlib axis handling in plot methods

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#2438]
There's possibly a bug, or we have an error-prone API concerning where we accidentally plot on WCS axes where really we want to plot on a new axis in our spectral plot methods. See
https://github.com/gammapy/gammapy/pull/2435#issuecomment-538326363

There's also the question if / when we should return axis objects, or if it would be better to return artist objects from plot methods. See https://github.com/astropy/regions/issues/296

Let's discuss here if we can improve our axis handling in plotting methods, and if yes, do that cleanup for v0.15.

@adonath @Bultako or any other MPL experts - thoughts?

**Comment by adonath** [comment]
I think right now there is now strong motivation to change our coding pattern. I think passing the `Axis` object is just fine and work for most of the use-cases. However we should check all our plotting methods for consistency.

**Comment by adonath** [comment]
I think the current pattern is fine. There is now #3001, which will take care of the uniformity of the pattern. Will close this issue now.
