### ISSUE TITLE
Intersphinx link to pandas not working

### ISSUE THREAD

**Issue by joleroi** [gammapy/gammapy#2439]
https://docs.gammapy.org/0.14/api/gammapy.catalog.GammaCatResourceIndex.html?highlight=pandas#gammapy.catalog.GammaCatResourceIndex.to_pandas

**Comment by cdeil** [comment]
We need to add `pandas` as an extra line here:
https://github.com/gammapy/gammapy/blob/7d7e63e74d9c5e5a5ba1c8e70358cce4bd045794/docs/conf.py#L47

@joleroi - you or me?

**Comment by joleroi** [comment]
If you want me to do small fixes like this, please give me push access to master again 😉

**Comment by cdeil** [comment]
Fixed in ee2535af97986f8df550b1fd9c0f2c0ae2d3c877

**Comment by cdeil** [comment]
@joleroi - You are listed in the `gammapy-maintainers` team. I thought that would give you the permission to commit directly to master. If you go e.g. to https://github.com/gammapy/gammapy/edit/master/CHANGES.rst you don't see the option "Commit directly to the master branch." at the bottom?

**Comment by joleroi** [comment]
![image](https://user-images.githubusercontent.com/11678435/66219948-62fd6000-e6cc-11e9-9122-0cc1f8e283ba.png)
