### ISSUE TITLE
Debian packaging: difficulties with setuptools_scm

### ISSUE THREAD

**Issue by olebole** [gammapy/gammapy#2440]
Hi,
I have a problem with version 0.14 where I am not sure what to do with: In Debian, we have [our own git repository](https://salsa.debian.org/debian-astro-team/gammapy) to track the packing, and use local tags (like `debian/0.14-1`) to organize it.
In version 0.14 however, gammapy uses setuptools_scm, which looks and parses these tags. This results in the error message
```
dh clean --with python3 --buildsystem=pybuild
   dh_auto_clean -O--buildsystem=pybuild
I: pybuild base:217: python3.7 setup.py clean 
/usr/lib/python3/dist-packages/setuptools_scm/version.py:92: UserWarning: tag 'debian/0.13-1' no version found
  warnings.warn("tag %r no version found" % (tag,))
Traceback (most recent call last):
  File "setup.py", line 35, in <module>
    setuptools.setup(use_scm_version=True, ext_modules=ext_modules)
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 446, in __init__
    k: v for k, v in attrs.items()
  File "/usr/lib/python3.7/distutils/dist.py", line 292, in __init__
    self.finalize_options()
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 734, in finalize_options
    ep.load()(self, ep.name, value)
  File "/usr/lib/python3/dist-packages/setuptools_scm/integration.py", line 17, in version_keyword
    dist.metadata.version = get_version(**value)
  File "/usr/lib/python3/dist-packages/setuptools_scm/__init__.py", line 150, in get_version
    parsed_version = _do_parse(config)
  File "/usr/lib/python3/dist-packages/setuptools_scm/__init__.py", line 98, in _do_parse
    version = _version_from_entrypoints(config) or _version_from_entrypoints(
  File "/usr/lib/python3/dist-packages/setuptools_scm/__init__.py", line 58, in _version_from_entrypoints
    version = _call_entrypoint_fn(root, config, ep.load())
  File "/usr/lib/python3/dist-packages/setuptools_scm/__init__.py", line 39, in _call_entrypoint_fn
    return fn(root, config=config)
  File "/usr/lib/python3/dist-packages/setuptools_scm/git.py", line 135, in parse
    branch=branch,
  File "/usr/lib/python3/dist-packages/setuptools_scm/version.py", line 204, in meta
    assert parsed_version is not None, "cant parse version %s" % tag
AssertionError: cant parse version debian/0.13-1
E: pybuild pybuild:341: clean: plugin distutils failed with: exit code=1: python3.7 setup.py clean 
dh_auto_clean: pybuild --clean --test-pytest -i python{version} -p 3.7 returned exit code 13
```
One solution could be to patch out setuptools_scm in the Debian package; however this looks a bit hacky -- and I already observed the use of setuptools_scm in other packages (sunpy, parfive). This seems to slide in with the removal of astropy_helpers. So I am unsure what the best solution is:

 * ask you (and the other packages that use setuptools_scm) to handle the case of non-standard git tags
 * file a Debian bug on the setuptools_scm package (or on setuptools_scm upstream?) to "somehow" handle this centrally
 * keep handling this locally

My feeling in the moment is that the affected packages were the right place to fix this; therefore this issue. I am however unexperienced with setuptools_scm.

Could you help to investigate this?

**Comment by cdeil** [comment]
@astrofrog and @cadair as authors of https://github.com/astropy/astropy-APEs/pull/52 where the use of setuptools_scm is suggested - can you please comment on this packaging issue?

@olebole - My guess is that the right place to discuss this is the `setuptools_scm` issue tracker, because that's where the experts are.

For Debian, do you package starting from the sdist? And that still invokes `setuptools_scm`, and doesn't use the released version number? That sounds like a bug or not a great solution to me.

I thought `setuptools_scm` is relatively widely used, and that pytest and tox use it and one of their authors split `setuptools_scm` out to do the versioning. So shouldn't pytest or tox or other packages in Debian already have figured out a solution for that? @olebole - do you have a way to check?

**Comment by olebole** [comment]
The setuptools_scm maintainer got a hint to resolve this by setting the environment variable `SETUPTOOLS_SCM_PRETEND_VERSION`, which is actually already done when using the Debian python build tools (*pybuild*). I now fail to reproduce the problem and therefore can't tell why this happened in gammapy. Most probably it is a local problem, so I am closing this.
