### ISSUE TITLE
Apply offset cut during data reduction?

### ISSUE THREAD

**Issue by adonath** [gammapy/gammapy#2451]
While working on #2450, I noticed that we always apply the offset-cut during the data reduction already by setting the data outside to zero. In addition we store the mask in `mask_safe`. I could imagine it might be more flexible (not sure it's needed though...) to separate the offset cut from the width of the cutout of the observation we make and not apply the offset-cut on reduction, but just store it in `mask_safe`. For joint analyses this results in almost the same behaviour, as the `mask_safe` is applied during likelihood evaluation anyway. For stacking the datasets, the `mask_safe` is also applied anyway.

 So my proposal would be:
- Add an additional `cutout_width` parameter to `MapDatasetMaker` and choose a default of maybe `5 deg` (something like the largest reasonable offset)
- Don't apply the offset cut on data reduction, but just store it in `mask_safe`

The three advantages I see are:
- users can change the offset cut after data reduction, if needed
- for joint analyses leakage at the edge of the offset-cut is correctly taken into account
- consistent handling of energy and offset cuts with a single `mask_safe`

What do you think @registerrier, @cdeil and @lmohrmann? Is there something I have overseen?

**Comment by registerrier** [comment]
Technically, we could gain computing time if we were to compute the maps in valid pixels only. This is not what we do now. So I imagine this change is not an issue for this.

In the initial design we discussed for the chain of makers, we discussed applying for all obs:
1. Dataset creation 
2. Background estimation
3. Safe range determination. 

The offset cut then becomes a safe offset mask and would not be handled by the `MapDatasetMaker` but by a `SafeMaskMaker`.

We then need to invert step 2 and 3 because e.g. ring background needs the offset mask to run properly.

**Comment by adonath** [comment]
You're right @registerrier, it definitely affects the order in which we're doing the reduction steps. I guess there are also a few other places were we have to apply the `mask_safe` correctly and in order for example when computing images from cubes. I also see the point with the performance, indeed one could reduce the computation effort if the offset cut is defined early in the analysis.

Maybe the actual question is whether we should allow users to change the `mask_safe` **at all** after data reduction. Currently we handle it not really consistently. If we decide that the `mask_safe` can be changed after, then I would vote to not apply it during data reduction to keep full flexibility. If we decide it can't be changed after data reduction, then I would be strict and even make `.mask_safe` a read-only attribute on the dataset.

**Comment by adonath** [comment]
I implemented my proposal in #2551 and #2607. The remaining action item here is to further improve the `gammapy/cube/index.rst` docs page, explain the concept in more detail and emphasise that the mask safe can be set modified between the data reduction and before stacking.

**Comment by adonath** [comment]
I added some more explanations to `docs/cube/index.rst` in https://github.com/gammapy/gammapy/commit/e93e605084e1dffa0e47eeaff64c3be851717238.
