### ISSUE TITLE
Crash after macOS Catalina update in multiprocess call

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#2453]
I updated to macOS Catalina and now I get this crash
```
gammapy/cube/tests/test_ring.py::TestAdaptiveRingBackgroundEstimator::test_run_const_width libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Couldn't close file
Fatal Python error: Aborted
```
```
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Couldn't close file
Fatal Python error: Aborted
```
from here:
https://github.com/gammapy/gammapy/blob/c9ed2c68ed00ae37b14c8092d6096b0f2dbae95a/gammapy/maps/image_utils.py#L51

It occurs every time I run `pytest -s -v gammapy/cube/tests/`, but never when I run `pytest -s -v gammapy/cube/tests/test_ring.py`, i.e. it depends on Python process state and likely previous multiprocessing calls.

Log: https://gist.github.com/cdeil/a75211856a3bcab751ead707df9708c9#file-gistfile1-txt-L88

There is https://www.anaconda.com/how-to-restore-anaconda-after-macos-catalina-update/ but I couldn't find any issue yet concerning multiprocessing issues after Catalina update.

I'll `rm -r` my Anaconda install now and re-install from scratch, let's see ...
I just wanted to put this issue in the tracker to have a record, and as reference if others run into the same issue.

**Comment by cdeil** [comment]
@adonath - I don't have a Python at the moment. :-)
```
hfm-1804a:gammapy deil$ pytest -s -v gammapy/detect/tests
-bash: /usr/local/bin/pytest: /usr/local/bin/python3.9: bad interpreter: No such file or directory
```

I tried to create a minimal test case for 5 minutes, running some multiprocessing code examples like this through python and pytest:
```
import multiprocessing


def f(x):
    return x ** 2

def run():
    pool = multiprocessing.Pool()
    pool.map(f, range(100))
    pool.close()
    pool.join()


def test_pool():
    for _ in range(30):
        run()
```
But that didn't trigger the crash - I wasn't able to create a minimal test case.

I remember this talk: https://youtu.be/UVL4LFy8ch0
Basically his assessment was that `multiprocessing` was broken in some cases on some platforms, and while some important fixes and improvements are in Python 3.7 and 3.8, at the moment, e.g. `scikit-learn` avoids using it, and probably we should as well.

@adonath - Maybe you could watch that talk and comment on whether you think we should make a change (e.g. to `loki` or larger to `numba`) now, or just keep as-is for now and then do this change next year. (My 2 cents: either way is reasonable and doable, maybe learning a bit towards leaving that change to next year.)

**Comment by cdeil** [comment]
Re-installing Anaconda didn't resolve the issue, I still see the same.

If I avoid `multiprocessing` for the scale_cube, I do see the same crash from the TS code, which is the second place where we use `multiprocessing`:
https://gist.github.com/cdeil/4f02d978cf3ed6e7891ffc5bfc7bb976#file-gistfile1-txt-L384
I've tried for an hour, but haven't been able to create a minimal test case yet, the crash comes and goes depending on which tests are run before the one using multiprocessing.

I couldn't find any issues specifically concerning macOS Catalina for multiprocessing in the  conda, python, pytest, numpy trackers. There's multiple issues in the Python tracker concerning bugs with multiprocessing in Python 3.7, see e.g.  https://bugs.python.org/issue36281 or references there.

I'll dig further next week, trying to create a minimal reproducible test case, something I could report to CPython or try on Python 3.8rc.

If this doesn't yield a solution, one option could be to change the defaults to not use multiprocessing for now, to be on the safe side with Gammapy, and then to introduce parallel computing next year. (the code could remain as-is, I'm just suggesting to change the default to `parallel=False`) @adonath - would that be acceptable? Is this used for 3D cube PSF convolution and we'd take a large performance hit for likelihood fitting?

**Comment by cdeil** [comment]
Using `psutils` I found out that this one file is opened several times:
```
/Users/deil/anaconda3/envs/gammapy-dev/lib/python3.7/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSans.ttf
```
Possibly the `std::runtime_error: Couldn't close file` relates to this file.

After
```
conda uninstall matplotlib
```
the issue is gone, all tests (including the ones using multiprocessing) pass for me.

I'll try to debug further next week, see if I can create a minmal test case that only involves matplotlib and multiprocessing.

**Comment by cdeil** [comment]
I didn't manage to create the crash with a simpler test case yet, e.g. this doesn't trigger the crash:
```
$ pytest -s -v gammapy/cube/tests/test_fit.py test_mp_crash.py
```
with [test_mp_crash.py](https://gist.github.com/cdeil/d036e9fc7ec3478c9068f26bf24ed0be)
I think it might depend on non-deterministic closing time of the file descriptor of `DejaVuSans.ttf`, and if it occurs during parallel execution it crashes. (but that's just a guess, I'm not sure this is the issue).

Let's see if someone from MPL can reproduce or has a tip: https://github.com/matplotlib/matplotlib/issues/15410

**Comment by zhul9311** [comment]
I ran into a similar problem. 
So in my software I wrote a few lines of code that use multiprocessing.pool to do some parallel computation work. I all worked fine the first time multiprocessing.pool was triggered. However, if I want to repeat the work in the software, it starts to freeze and keep dumping this error to the screen:
```
......
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Couldn't close file
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Couldn't close file
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Couldn't close file
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Couldn't close file
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Couldn't close file
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Couldn't close file
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Couldn't close file
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Couldn't close file
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Couldn't close file
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Couldn't close file
......
```

Nothing was changed between two operation, and the second one stop working... It seems to me that multiprocessing.pool was using some sort of computer resources and didn't release it when it was finished. But I don't know how to fix it. Hope someone can help with it.

**Comment by cdeil** [comment]
@zhul9311 - Can you create a minimal reproducible test case or a script that triggers the crash? I haven't been able to do that. If yes, maybe you please put it in a https://gist.github.com/ and link to it from this issue? https://github.com/matplotlib/matplotlib/issues/15410
Thanks!

**Comment by cdeil** [comment]
So https://github.com/matplotlib/matplotlib/issues/15410 is still open, and it's not 100% clear why the crash is happening. But it is already clear that this is not a bug in the Gammapy code. Depending on viewpoint, one say it's the fault of Apple, or CPython or matplotlib. matplotlib is keeping a font file open for performance reasons, and then on child process creation tries to close it from the child process. That worked well so far, but apparently now on macOS Catalina it doesn't any more, which is not totally surprising since a major change in that version was process isolation and security changes, moving macOS towards a locked down execution environment like iOS. I note that at the moment these are still guesses from my side, and the issue might or might not be there for other CPython versions and binary builds.

Closing this issue now, resolved by #2472

**Comment by tacaswell** [comment]
Please see https://bugs.python.org/issue33725 for the full explanation of what is broken.

**Comment by lvwarren** [comment]
Please reopen this issue. It is still happening on MacOS Catalina 10.15.5 (19F101) as of June 30, 2020.

**Comment by adonath** [comment]
@lvwarren Fallowing this issue report we removed all of the `multiprocessing` code in Gammapy since `v0.15`. So I guess you run on an older version? If so can you maybe try whether adding (suggested here https://bugs.python.org/issue33725#msg329923):
```
import multiprocessing
multiprocessing.set_start_method('forkserver')
```
to the top of your script fixes the issue?

**Comment by lvwarren** [comment]
Actually I did a pip install to pick up matplotlib 3.3 and this solved the problem at the expense of adding a bunch of deprecation warnings. Condo installer is stuck at v3.2.

All the best,
- Van
________________________________

**Comment by adonath** [comment]
@lvwarren Thanks this is useful information, as we might re-introduce `multiprocessing` at some point...

**Comment by tuzikexin** [comment]
Same issue from my part.
`
from p_tqdm import p_map

forecast = p_map(
                self._get_single_forecast,
                [multiple_ts[k] for k in keys],
                [seasonality_ts[k] for k in keys],
                itertools.repeat(self.n_steps, times=len(keys)),
                [best_models[k] for k in keys],
                num_cpus=cpu_count() - 1,
            )
`
got error as: 
`libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Couldn't close file`

I use python 3.8 with macOS Catalina version 10.15.7

**Comment by zawie** [comment]
Still getting this error on macOS Catalina 10.15.6
`libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Couldn't close file
`
