### ISSUE TITLE
Add position error info for spatial models

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#2460]
In #2449 I noticed that we don't have an API to get and set position error information for spatial models, and left TODO items here specifically for the 2HWC catalog to fill this information:

https://github.com/gammapy/gammapy/blob/6821570a87bb6693394c8a4ebe535e1770b82c38/gammapy/catalog/hawc.py#L143

https://github.com/gammapy/gammapy/blob/6821570a87bb6693394c8a4ebe535e1770b82c38/gammapy/catalog/tests/test_hawc.py#L84-L85

This is something that is very commonly needed, most users want to write this into their papers and plot it, but it's not so easy to compute, and it's not obvious how to add this to Gammapy.

Just as background to what I mean, see here:
http://www.star.bris.ac.uk/~mbt/topcat/sun253/sun253.html#form-skycorr
The assumption is to have a Gaussian PDF (sometimes symmetric, sometimes elongated) on the Sky, and to have the position error represented by an ellipse or circle. So we could use [regions.EllipseSkyRegion](https://astropy-regions.readthedocs.io/en/latest/api/regions.EllipseSkyRegion.html) or [DiskSpatialModel](https://docs.gammapy.org/0.14/api/gammapy.modeling.models.DiskSpatialModel.html) to represent the position error information, or just have a dict with major, minor, angle, frame information.

Probably we should add get and set methods to the spatial model base class, that transform these numbers to / from the model covariance matrix? How about taking `EllipseSkyRegion` in the get and set? For the "get" this would be then consistent with getting a region that represents the source orientation and extent (see #2422).

And then fill position error information via this API when making spatial models from catalog information (instead of doing `lon_err / cos(lat)` manually)?

@adonath @QRemy @registerrier - Thoughts?

Anyone interested to make this addition?

**Comment by QRemy** [comment]
Added in #2491 and #2501
