### ISSUE TITLE
Fix test_wcs_nd_map_data_transpose_issue

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#2465]
I think here we forgot to pass `sparse=True` in `test_wcs_nd_map_data_transpose_issue`?

https://github.com/gammapy/gammapy/pull/1346/files#diff-930fa0f94b49b5d6537396fad7c6512aR137-R140

If I change to `sparse=True` in the write call, I get this fail:
```
E           Arrays are not equal
E           
E           x and y nan location mismatch:
E            x: array([[0., 1., 2.],
E                  [0., 0., 0.]], dtype=float32)
E            y: array([[  0.,   1.,   2.],
E                  [ nan,  inf, -inf]])
```

@adonath - Is there a bug?

Should we spend 1-2 days on maps basics and sort out dtype and missing value issues (#1440, #2374, maybe this issue), e.g. with pair-coding & debugging? Or defer all or some to v1.1?

This is a reminder issue, noticed this accidentally while working on
https://github.com/gammapy/gammapy/pull/2350#issuecomment-542754564

**Comment by adonath** [comment]
I think we should definitely spend a few days (1-2 days might not not sufficient...) on improving `gammapy.maps` before v1.0. However I would prefer to not spend any time on something related to sparse maps. So far I have never worked on sparse maps and I'm not aware of anybody using it. So I think for v1.0 we should just remove sparse maps from the documentation...

**Comment by cdeil** [comment]
> I would prefer to not spend any time on something related to sparse maps. So far I have never worked on sparse maps and I'm not aware of anybody using it. 

Well, no-one's using it because it's not working yet. But yes, moving this issue to v1.1 milestone.

> So I think for v1.0 we should just remove sparse maps from the documentation...

Maybe. The problem is that the whole gammapy.maps design, with the class hierarchy, and also partly how we use maps in data reduction, only makes sense if there are these extra map types. Otherwise things could be simpler and faster. So I'm leaning a bit to leave as-is and say it's foreseen and to be implemented later. But yes, we should discuss whether to remove for now.
