### ISSUE TITLE
Support Python 3.8

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#2466]
Python 3.8 came out a few days ago (Oct 14, 2019):
https://docs.python.org/3/whatsnew/3.8.html

We should support it, either with Gammapy v0.15 or the next release.

There's probably zero code changes needed in Gammapy, but we should add one CI build to make sure it works, and usually it takes a few days or weeks until all dependencies support Python 3.8 and conda binaries become available.

@bsipocz - Is there an issue to watch or ETA when conda Python 3.8 and Astropy conda packages become available?

**Comment by bsipocz** [comment]
> @bsipocz - Is there an issue to watch or ETA when conda Python 3.8 and Astropy conda packages become available?

I really have no idea, but you should seriously consider testing with pip, especially now that it's easy to control what dependency it should install.

**Comment by bsipocz** [comment]
(In the past it took quite a long time for all the deps being rolled out on conda-forge. Now they are less CI limited as before, but I don't think the process would be much quicker).

**Comment by cdeil** [comment]
Moving this to the v1.0 milestone. It'll probably take a few weeks until Python 3.8 becomes widely available and the packaging experts sort out compiler issues in CPython, Numpy, ...
x-ref https://github.com/conda-forge/python-feedstock/pull/274

**Comment by bsipocz** [comment]
well, numpy 1.17.3 got released yesterday, so for the interim you could have a travis job relying on the wheels.

**Comment by cdeil** [comment]
@bsipocz - we could try to make it work now, but really we're not in a rush, we can just wait a week or month, or even a year until Python 3.8 and all our dependencies are available in conda. We realised that with Gammapy, we are not at the base or a package stack, and we don't need to have as broad support for as many old and new versions as possible. We just need to ship one good environment for each release, but when to update from Python 3.7 to 3.8 is whenever we like (see [PIG 13](https://docs.gammapy.org/0.14/development/pigs/pig-013.html)).

Of course, in reality it's a bit different - I'm excited to try out Python 3.8 and see if Gammapy works there, if it's a bit faster. Earlier this year I built a Python 3.8 alpha from source, and numpy and Astropy as well, but then got stuck with scipy, so didn't quite get Gammapy to run. But that's just for fun, at the moment I don't have time and will just wait for conda to build and ship for Python 3.8.

**Comment by cdeil** [comment]
x-ref:  https://github.com/conda-forge/gammapy-feedstock/pull/13

**Comment by cdeil** [comment]
Locally I see one single fail, in `TestEventListFermi.test_plot_image` when using Python 3.8 from conda now. See [here](https://gist.github.com/cdeil/a31c1f90d65f5202772362ad4f0fc12f).

I've asked here if this is something they want to fix in MPL:
https://github.com/matplotlib/matplotlib/issues/15690

I suspect not, and then the fix would be to add
```
xmargin = float(xmargin)
ymarging = float(ymargin)
```
here:
https://github.com/gammapy/gammapy/blob/2d8aba04de9fb1c10baea928db891ef9757658e2/gammapy/maps/wcsnd.py#L482-L486

Or we could improve gammapy.maps coordinates to return scalars in those cases, i.e. to behave more like Numpy, as suggested in #1301 . Probably the reason we get 1-dim arrays for scalar inputs is this:
```
$ ack atleast gammapy/maps
gammapy/maps/geom.py
814:        data = {k: np.atleast_1d(np.asanyarray(v)) for k, v in data.items()}
$ ack ndmin gammapy
gammapy/maps/geom.py
169:    return max([np.array(p, ndmin=1).shape for p in param])
229:        p = np.array(p, ndmin=1)
262:    x = np.array(x, ndmin=1)
562:        return np.array(pix + self._pix_offset, ndmin=1)

gammapy/maps/hpx.py
173:    pixsz = np.array(pixsz, ndmin=1)
400:    nside = np.array(nside, ndmin=1)
453:    ratio = np.array((nside_subpix // nside_superpix) ** 2, ndmin=1)
506:    npix = np.array((nside_subpix // nside_superpix) ** 2, ndmin=1)
575:        self._nside = np.array(nside, ndmin=1)
703:            idx = np.array(idx_global[0], ndmin=1)
759:            idx_global = unravel_hpx_index(np.array(idx_global, ndmin=1), self._maxpix)

gammapy/maps/wcs.py
49:    param = [np.array(p, ndmin=1, dtype=dtype) for p in param]

gammapy/maps/sparse.py
35:            idx += [np.array(s, ndmin=1)[tuple(si)]]
166:        idx_in = tuple([np.array(z, ndmin=1, copy=False) for z in idx_in])
183:        vals = np.array(vals, ndmin=1)

gammapy/maps/wcsnd.py
158:                np.array(x, ndmin=1)
```

**Comment by cdeil** [comment]
https://github.com/conda-forge/gammapy-feedstock/pull/13 was merged. In ~ 1 hour we should have Python 3.8 packages for the last release Gammapy v0.14.

I plan to add a CI build for Python 3.8 for Gammapy ASAP.

**Comment by cdeil** [comment]
Python 3.8 for v0.15 conda-forge build failed, aren't available for now:
https://github.com/conda-forge/gammapy-feedstock/pull/14#issuecomment-561318635

We can try again (probably in the next days) once pydantic is available for Python 3.8 via conda:
https://github.com/conda-forge/pydantic-feedstock/pull/31

**Comment by cdeil** [comment]
pydantic now works fine with Python 3.8 on all platforms
(https://github.com/conda-forge/pydantic-feedstock/pull/32)

The one remaining dependency that needs Python 3.8 binaries is Naima.
Someone needs to merge: https://github.com/conda-forge/naima-feedstock/pull/10
This needs to happen anyways, to have Naima v0.9, the previous Naima v0.8 doesn't support the upcoming Astropy v4.0.
@adonath - it would be good if you add yourself as maintainer for naima on conda-forge. The time investment should be very limited, roughly an hour every few months when a new release comes out. But it's critical to be able to get things like https://github.com/conda-forge/naima-feedstock/pull/10 in, since Naima doesn't have an active maintainer any more, but it's an (optional) dependency for us. Pulling it into Gammapy isn't a good idea for now, focus should be on creating v1.0 and good analysis core, pulling in Naima could happen in 2021 or some other similar package comes along that's active and then we interface with that.

Once this is done, I would suggest to change the Gammapy dev env to Python 3.8, and then use Python 3.8 in the next release. There's no risk really, you can try Python 3.8, and if there are any issues that can't be solved in an hour or two, go back to Python 3.7 for the advertised env.

**Comment by maxnoe** [comment]
I think this can be closed. The test suite is running and passing 3.8 on github actions, right?

**Comment by bsipocz** [comment]
@maxnoe - Yes, but I suppose a similar ones should be opened for python 3.9 and 3.10. Maybe repurpose https://github.com/gammapy/gammapy/issues/2270?
