### ISSUE TITLE
Add background models to HESS DL3 DR1 dataset

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#2495]
Reminder issue for myself, and place to discuss with @lmohrmann and @adonath about details.

Update https://github.com/gammapy/gammapy-extra/tree/master/datasets/hess-dl3-dr1 to include the background models from https://github.com/lmohrmann/hess_ost_paper_material/blob/master/background_model

There's [this script](https://github.com/lmohrmann/hess_ost_paper_material/blob/master/background_model/update_hess_dl3_dr1_hdu_index.py) and [this example](https://docs.gammapy.org/0.14/notebooks/background_model.html) how to make new index files.

There's one background model for each run, in total 36MB. It's stored as float64 data, with a range of 0.1 deg from +- 2.5 deg, and 20 energy bins.

I could change to float32, which is virtually identical, then it should be 18 MB, and combined with the 43 MB of other HESS DL3 DR1 files it would be 61 MB.

Alternativelly I could also downsample from 0.1 to 0.2 deg, which should also be virtually identical, and would result in 4.5 MB of BKG, and in total 48 MB, which is a bit better, but not a huge improvement.

The other change I'd like to make when reformatting the data is to just dump it all into a single `.fits.gz` file. This will then be faster for `gammapy download` and IMO a bit more convenient to copy around. Opening a ~ 50 MB `.fits.gz` file which uncompresses it should be `<~ 1 sec`.

@adonath @lmohrmann @registerrier  - Do you have a preference on these two detail questions?

**Comment by adonath** [comment]
@cdeil I agree we should change to `float32` precision to limit the file size. Whether to use one file or multiple files, I don't really care. Do whatever you prefer...

**Comment by cdeil** [comment]
See https://github.com/gammapy/gammapy-extra/pull/128

I left as one data file per observation for now (just because it was easiest, and because single file wasn't clearly better). Changed to float32, but didn't downsample BKG models. Total file size is 50 MB (compressed as `.fits.gz`), and ~ 115 MB uncompressed when loading the data in memory.

@adonath - OK?

Can you please merge this in, and to update the data index file?
If there's failing notebooks, I can fix those in the next 1-2 days.

**Comment by adonath** [comment]
@cdeil See https://github.com/gammapy/gammapy/pull/2508. It already contains the changes to the notebooks and tests.

**Comment by cdeil** [comment]
@adonath - Thanks!
