### ISSUE TITLE
Gammapy validation: HESS DL3 DR1

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#2509]
As part of the Gammapy validation effort while preparing v1.0, we should script some of the H.E.S.S. data level 3, data release 1 analyses for validation.

Note that large parts of Gammapy were rewritten since Gammapy v0.12 (May 2019) which was used for https://arxiv.org/pdf/1910.08088.pdf requiring the validation exercise to be re-done with the latest version of Gammapy, and from now on moving forward we'll maintain the validation scripts in the Gammapy team to avoid regressions. One concrete case of a regression that we already noticed and fixed in the meantime is https://github.com/gammapy/gammapy/pull/2367 .

A task description and references are here:

- https://github.com/gammapy/gammapy-benchmarks
- https://github.com/gammapy/gammapy-benchmarks/blob/master/validation
- https://github.com/gammapy/gammapy-benchmarks/tree/master/validation/hess-dl3-dr1

We're looking for help! If you can contribute, please leave a comment here, or contact me on Slack.

For this, you don't have to be a Gammapy developer, what's required is some Python & Gammapy & IACT analysis experience, and at least ~ 2 full days to contribute in Nov 2019, although ~ 1 week in Nov & Dec 2019 is more realistic if you're willing to script the analysis for all targets.

**Comment by cdeil** [comment]
First version: https://github.com/gammapy/gammapy-benchmarks/pull/14

**Comment by adonath** [comment]
Here are the current results: https://github.com/gammapy/gammapy-benchmarks/tree/master/validation/hess-dl3-dr1

This will probably require some more work for v1.0, so keeping it open and resetting the milestone.

**Comment by registerrier** [comment]
Closing now. HESS validation might need some clean up/simplifcation. Will open an issue for that in gammapy-benchmark.
