### ISSUE TITLE
Gammapy validation: Fermi-LAT 3FHL

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#2511]
As part of the Gammapy validation effort while preparing v1.0, we should try to reproduce some of the Fermi-LAT 3FHL high-energy catalog analysis results.

A task description and references are here:

- https://github.com/gammapy/gammapy-benchmarks
- https://github.com/gammapy/gammapy-benchmarks/blob/master/validation
- https://github.com/gammapy/gammapy-benchmarks/tree/master/validation/fermi-3fhl

This is on a best-effort basis, ideally we'd have 1-2 sources scripted ASAP, and then a complex region, or an AGN lightcurve also, but that can come later.

For this, you don't have to be a Gammapy developer, what's required is some Python & Gammapy & Fermi-LAT experience, and a few days of free time in Nov 2019.

We're looking for help! If you can contribute, please leave a comment here, or contact me on Slack.

**Comment by adonath** [comment]
Here are the current results: https://github.com/gammapy/gammapy-benchmarks/tree/master/validation/fermi-3fhl#results

Overall the results look mostly good. The obvious things to investigate are probably:
- Systematic shift in the flux points (Gammapy seems to underestimate the flux)
- Check consistency of error and UL estimation (Gammapy seems to systematically underestimate ULs)
- Check consistency in model evaluation regarding log-log integration of spectral models and diffuse models

**Comment by registerrier** [comment]
Closing now. Further issues should be reported in the gammapy-benchmark repo directly.
