### ISSUE TITLE
Gammapy validation: joint Crab analysis

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#2512]
As part of the Gammapy validation effort while preparing v1.0, we should try to reproduce the joint likelihood spectral analysis for the Crab nebula that we did with Gammapy v0.9 a wile ago.

This is a good use case for the high-level joint dataset and fitting API we are currently developing in Gammapy (see e.g. #2505), and to test parameter error and 2D error contour computations. This would also be a good check for the safe energy mask handling and energy dispersion apply for 1D spectral analysis, topics that were checked in detail when doing the joint Crab analysis.

A task description and references are here:

- https://github.com/gammapy/gammapy-benchmarks
- https://github.com/gammapy/gammapy-benchmarks/blob/master/validation
https://github.com/open-gamma-ray-astro/joint-crab

This is on a best-effort basis, the starting point should be to try to load the reduced OGIP data and reproduce the joint log parabola fit. Then one could continue and either reproduce the analysis including the modified likelihood that includes systematics (see if that is possible or even easy with the current dataset API), and / or look at the parameter errors and correlations in detail.

For this, you don't have to be a Gammapy developer, what's required is some Python & Gammapy & gamma-ray experience, and a few days of free time in Nov 2019.

We're looking for help! If you're interested in this task, please leave a comment here, or contact me on Slack.

cc @cosimoNigro @kbruegge @Bultako @TarekHC  @QRemy

**Comment by registerrier** [comment]
joint-crab validation is under way. See:
https://github.com/gammapy/gammapy-benchmarks/blob/master/validation/joint-crab/README.md

For now agreement is good, except for Fermi. The `Dataset` building approach in this case is significantly different from what it used to be. Here we go from a `MapDataset` to a `SpectrumDataset`. The resulting `aeff` seems to be off. I am currently checking for this.

**Comment by registerrier** [comment]
The issue dates from the joint-crab paper. The coordinate used is passed in galactic frame to a `Map` defined in celestial coordinates. This results in an improper exposure estimate at the Crab position.
I changed the `joint-crab` repo code to extract the exposure at the right position and we now get consistent results.

**Comment by adonath** [comment]
@registerrier Anything left to be done here? Is the joint fit already available?

**Comment by registerrier** [comment]
Yes the joint fit is done see: 
https://github.com/gammapy/gammapy-benchmarks/blob/master/validation/joint-crab/results/joint_summary.md

Technically it could be closed. Unless we wait for 1.0 validation to close these issues.

**Comment by registerrier** [comment]
Validation task is running. Closing now.
