### ISSUE TITLE
Accessing observations through the high-level interface

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#2515]
While accessing observations through the high level interface, duplicate observations of the same obs_id is thrown away.
https://github.com/gammapy/gammapy/blob/fe6f23d8b7e3fc1d2f7f00a2dbe368769bea0d0d/gammapy/scripts/analysis.py#L130

Having duplicate observations is usually not a sensible idea, so normally this is not an issue.
However, it may be required in some cases, eg, while doing some benchmark tests or simulations (eg: take one observation, duplicate it `N` times and do a 1 D spectrum - see how many observations are required to get decent spectra etc). 

So if the user intentionally repeats the same obs_id multiple times,  `Analysis.get_observations()` should return the same observation multiple times. This is what `DataStore.get_observations()` does.

What do you think @adonath @Bultako @registerrier @cdeil ?

**Comment by adonath** [comment]
I agree it would be helpful to use the `Analysis` class in the benchmarks as well. I guess the corresponding code in `analysis.py` could be just re-written to not use `set` for the observations ids? The `.difference_update()` can also be achieved by masking into the `selected_obs` observation table instead...

Here is a minimal code example:
```
import numpy as np

exclude = np.array([3, 4, 5])
obs_ids = np.array([1, 2, 3, 4, 5, 6])

selection = np.isin(obs_ids, exclude)
print(obs_ids[~selection])

print(set(obs_ids.tolist()).difference(set(exclude.tolist())))
```

**Comment by cdeil** [comment]
I see a change was made in #2518 .

But this is still not a good solution:
https://github.com/gammapy/gammapy/blob/3da043f5e45fad8e8b20882b148cef4701df9e13/gammapy/scripts/analysis.py#L85-L134

It does contain a TODO comment, but I'd suggest to keep this issue open as a reminder also.
There needs to be a solution where the logic to apply selections is in one place, not spread around three classes (`Analysis`, `DataStore`, `ObservationTable`), or we'll debug and test these selctions multiple times. We can re-expose functionality (e.g. `ObservationTable` selection on `Analysis` or on `DataStore`), but then it has to be done in a way that just does config handling and calls the one implementation of the functionality. The current `Analysis.get_observations` does too much (both conceptually, and also technically, going back and forth between Numpy array and Python list of `OBS_ID` for no good reason multiple times).

**Comment by adonath** [comment]
@registerrier Is this issues addressed after #3424?

**Comment by registerrier** [comment]
I think the initial issue is covered by #2518.
#3424 clarifies the selection by moving all selections that are to be applied to the `ObservationTable`  to an `Analysis._make_obs_table_selection` method. 

The `ObservationTable` is probably the better place to put the selection with multiple criteria. So we could extend `ObservationTable.select_observations` to accept lists of selection `dict`.  So that a single call to `ObservationTable.select_observations` would return the filtered table.

**Comment by adonath** [comment]
Observation selection has been refactored in #3431, this not yet exposed on the `Analysis` class, however the specific issue here is solved, will close now.
