### ISSUE TITLE
Update `simulate.py`

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#2527]
We have a helper function `simulate` to simulate a `MapDataset`. This needs to be updated to work with a different `geom` for the irfs.
https://github.com/gammapy/gammapy/blob/master/gammapy/cube/simulate.py

Is this function being used anywhere? The `simulate_3d` notebook does the simulation by hand. 
Should we adapt `simulate_3d` to use this?
Also, wouldn't it be better to have this as a class method of `MapDataset`?

@cdeil @adonath Please opine

**Comment by cdeil** [comment]
It's currently used in two tests. It's part of the public API: https://docs.gammapy.org/0.14/api/gammapy.cube.simulate_dataset.html
But not used anywhere in the tutorials.

We could keep it, and use it here?
https://docs.gammapy.org/0.14/notebooks/simulate_3d.html

And maybe add an equivalent helper function to quickly make 1D spectral dataset for tests, or simulations?
I think we had a spectrum simulation class that does something similar, but it was removed and now it's done more manually:
https://docs.gammapy.org/0.14/notebooks/spectrum_simulation.html

@adonath - What do we want to have for v0.15 / v1.0?
(Anything is fine with me.)

**Comment by adonath** [comment]
I basically see two options:

Introduce an in memory `Observation` object, which is API compatible with the `DatasStoreObservation`.

It can be minimal for now like:

```python3
obs = Observation(id=, pointing=, livetime=, bkg=, edisp=, aeff=,psf= )
```

Or add helper methods to create `hdu_index` and `obs_index` files for existing IRFs, e.g.:

```python3
obs_table = ObservationTable.from_pointing(pointing=, target=, t_start=, t_stop=)
hdu_table = HDUIndexTable.from_caldb("irf_file.fits", obs_ids=obs_table["OBS_IDS"])
data_store = DataStore(obs_table=obs_table, hdu_table=hdu_table)
```
In both cases the code for simulating a dataset becomes:
```
maker = MapDatasetMaker()

dataset = maker.run(obs, steps=["bkg", "edisp", "exposure", "psf"])

dataset.model = ...
dataset.fake()

# or later once we have event sampling
events = dataset.fake_events()
events.write(obs.location(hdu_type="events", hdu_class="events"))
```
If we start to extend the `simulate_dataset()` functions, we start re-coding the data reduction and this I want to clearly avoid.

**Comment by cdeil** [comment]
Note that we had extensively discussed how to add an observation class that supports setting attributes in #1877, and a class was actually added, but then again removed in #1972.

To be honest, I don't remember why we removed it. Isn't the easiest way to support simulation via a second DL3 Observation object just like we had it? It would have the same API as the existing `DataStoreObservation`, which is the read-only disk-based equivalent used for real data.
Maybe we thought we could come up with one object that support property read and write and can satisfy all use cases?

Suggest to either re-add the second `Observation` and start using it for simulation, or to re-read the discussion we had on the PIG at the time.

**Comment by adonath** [comment]
Thanks @cdeil, I'll read the discussions and proposal in PIG 006 and comment once again.

**Comment by AtreyeeS** [comment]
Closing this to continue discussion in #2626
