### ISSUE TITLE
Naming of OGIP 1D spectrum files

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#2542]
For the serialisation of `SpectrumDataset` we have `SpectrumDatasetOnOff.from_ogip_files()` and `SpectrumDatasetOnOff.to_ogip_files()` .

1. The `to_ogip_files()` automatically chooses the file name as `{pha/bkg/arf/rmf}_obs{dataset.name}.fits`. Firstly, this isn't very nice. The user should be able to specify the naming. Moreover, it is not mentioned in the doc-string how the naming is done. The user really has to look into the code to understand that, which is definitely not nice.
2. The `from_ogip_files()` expects the filename to be `pha_obs{dataset.name}.fits`, which is quite non-intuitive (considering that there are 4 files to be read), and then internally does `phafile.replace("pha", "arf")` to read the other files. Again, the naming convention is not mentioned anywhere in the docstring.

I think it would be nice to have an API like `MapDataset.read()` and `MapDataset.write()` if possible. If not, then give the user some flexibility in the naming. Or at the very least, improve the documentation and include this in the tutorials.

This might be related to #2517 if we decide to remove `name` attribute on the dataset all together.

**Comment by cdeil** [comment]
My 2 cents: I think [convention over configuration](https://en.wikipedia.org/wiki/Convention_over_configuration) is better for a high-level interface like `read` or `write`. If you make everything configurable (filenames, HDU names), the interface becomes very complex and hard to use. There should still be a lower-level API for experts to do whatever they want (e.g. use `astropy.io.fits.open` or `astropy.table.Table.read` or `gammapy.maps.Map.read` to read what they want and pass it to datasets `__init__`, but the dataset read / write API is very high level.

+1 to have read/write.

@adonath - Assigning to you, and unsubscribing from this discussion.

**Comment by AtreyeeS** [comment]
No, I did not mean that the user has to have a lot of flexibility. The problem here is that the user does not understand the names of the files being written

**Comment by registerrier** [comment]
All X-ray analysis pipelines tend to have default names for `arf`, `rmf` and `pha` files. I think we have to do the same here. Especially since most of the times we have to export a large number of such files. 
I propose to update the docstring to better reflect this, see PR #2565 .

**Comment by cdeil** [comment]
Fixed by @registerrier in #2565
