### ISSUE TITLE
test_wcsndmap_reproject_allsky_car fail due to astropy reproject v0.6 change

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#2549]
@astrofrog  released `reproject` v0.6 about 10 days ago, and the conda package was built just now.

It removes `reproject.wcs_utils.convert_world_coordinates` which we called, and now we have this error: https://travis-ci.org/gammapy/gammapy/jobs/612378792#L3210

The code is here:
https://github.com/gammapy/gammapy/blob/a10d7c8434a04c5ddaa526d38c99d162f623700d/gammapy/maps/reproject.py#L11

@adonath - Can you please have a look, and see if we can remove that code, and if we want to keep it, adapt it to newer Astropy or reproject API?

@astrofrog - There's https://github.com/astropy/astropy-APEs/blob/master/APE14.rst, but I'm not sure if the equivalent functionality is already exposed in a released Astropy version?

**Comment by astrofrog** [comment]
As of reproject v0.6, we can reproject a much wider variety of data, so maybe if someone can explain why the custom reprojection code was needed here, I can help migrate to just relying on reproject instead?

**Comment by astrofrog** [comment]
Looking at the code, it seems like you are trying to reproject to HPX - if FITS WCS can't handle this, then the best approach would be to define a WCS class for HPX based on the APE 14 specification (reproject now understands this).

**Comment by adonath** [comment]
We decided to remove the reproject functionality for now. Addressed in #2562.
