### ISSUE TITLE
Simplify LightCurveEstimator

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#2555]
The current `LightCurveEstimator` suffers from heavy code duplication from `FluxPointsEstimator`.  This must be corrected.

The current situation is due to a very similar task with a slightly different logic
Both extract flux by fitting a scaled model of the source on the dataset
But `FluxPointsEstimator` uses the same datasets for all steps (i.e. all energy bins)
while `LightCurveEstimator` uses different datasets for each time bin.
The `Fit` object it contains has to be re-instantiated at each step in the `run` loop.

Therefore, inheritance will not work. 

I propose to simplify `LightCurveEstimator` heavily by making it rely on `FluxPointsEstimator`.

The new logic would be:
- At `__init__`, assign datasets to a time bin. Define a single energy bin from input range.
- For each time bin:
  * create a FluxPointsEstimator for the current list of dataset with one single energy bin
  * run flux point estimation and extract info from the table

**Comment by adonath** [comment]
The code duplication  in `FluxPointEstimator` and `LightCurveEstimator` is not too bad, the core of the algorithm is not the same anymore, since we now have dataset grouping in the light curve estimation. 

The question will rather come up, when we introduce a `PhaseCurveEstimator`, where the algorithm is the same. Will remove the high-priority label now...

**Comment by registerrier** [comment]
There is a general use case for a `FluxEstimator` for instance if you want to compute an upper limit on a source at some position or in some energy range.  
This could be the general object which could be used by the `FluxPointsEstimator`, the `LightCurveEstimator` and future things like `PhaseFluxEstimator` or maybe the sigma_v estimator that is being prepared?

**Comment by registerrier** [comment]
This has now been done with the introduction of the `FluxEstimator` in PR #2791 #2810 #2821 #2848 and mostly #2850
