### ISSUE TITLE
Re-structure gammapy.time documentation

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#2566]
`gammapy.time` documentation must be deeply re-structured. 
- the LightCurve object must be briefly presented with a reference to (gadf)[https://gamma-astro-data-formats.readthedocs.io/en/latest/lightcurves/index.html].
- a long presentation on periodicity using Lomb-Scargle periodograms should probably be removed for now. It should rather be included as a notebook.
- the `LightCurveEstimator` must be presented and its usage described briefly with a reference to the lightcurve.ipynb notebook.

**Comment by cdeil** [comment]
Currently at https://docs.gammapy.org/0.14/time/index.html we have:
- LightCurve
- Variability tests
- Other codes
- Link to [periodicity](https://docs.gammapy.org/0.14/time/period.html)

@registerrier - What's your suggestion?
Start with LightCurve, then LightCurveEstimator?
Or the other way around, only show LightCurve after producing one?
I think maybe what we have isn't so bad, just mainly the link to `lightcurve.ipynb` is missing and must go at the top?

Remove all links to other codes, no? Or do you want to keep some?

Concerning periodicity - I was also thinking earlier this year whether we should remove it. I would suggest to keep it as-is, it's basically v1.0 quality, nothing to do, and it's functionality we basically want, at least at the docs level, so IMO removing it goes in the wrong direction. Moving it to a notebook isn't easy, as it's a long-running analysis. Basically if you try to improve this, you need an expert with a few days of time to really make it better. @registerrier - OK to keep, or are you strongly +1 to remove? (in that case @adonath could be tie-breaker?).

**Comment by registerrier** [comment]
I would start with `LightCurve` since it is easier to explain what you want to extract before explaining how you want to extract it.

I am not sure about the variability tests. There are some currently on the `LightCurve` (fractional variance and chi square). It is not clear to me whether this is where they should be.  It seems to me better to have them either as fully external functions or as general functions in `gammapy.time`.

For periodicity, I agree the documentation is very well done. But it goes completely opposite to what we decided regarding structure (i.e. everything is in a rst page here). Also it is not clear to me how much can be actually redone with the current gammapy version.

I would say we keep it for now, and we'll decide once we have the rest of the documentation in good shape.

**Comment by registerrier** [comment]
A more precise suggestion.
- Present `LightCurve`, the stored columns and refer to https://gamma-astro-data-formats.readthedocs.io/en/latest/lightcurves/index.html
- Present `LightCurveEstimator`, and briefly explain the method. This part is important since most of the time light curves are made without fitting in VHE. Refer to the light curve notebook for an example usage. Explain clearly the required assumptions for the `LightCurveEstimator` to make it behave as expected (fit range definition, time interval definition and datasets GTIs)
- Discuss very briefly methods exposed on variability and periodicity and refer to periodicity page for a more detailed example of timing analysis

**Comment by adonath** [comment]
After #2650 is there anything left to be done here, @registerrier?

**Comment by registerrier** [comment]
Since it probably will require some polishing, I move it to 1.0

**Comment by registerrier** [comment]
The status of `gammapy.time` is not clear after the package restructuring. 

The `LightCurve` and `LightCurveEstimator` objects are now part of `gammapy.estimators` and are no longer described in `time.index.rst`. As long as the package exists and contains some documentation, It is probably important to keep some information on the light curves here too. At the moment, there are links to the two light curve notebooks. This is probably enough.

A minima, on should still mention the `LightCurve` as connected to `gammapy.time` but it is necessary to change the link in the `time/index.rst` page.

**Comment by wegenmat** [comment]
Hi everyone,

I just want to briefly join the conversation, since most of the code for periodicity is written by me.

When restructuring the time documentation and discussing whether to keep periodicity or not, you might consider two more tools for time series analysis written by me.
Link: https://github.com/wegenmat/python
I developed these tools within the framework of the same master thesis as the periodicity code.

My plan was to add everything to gammapy some day, but unfortunately, I won't have time to take care of this anymore.
So, if someone is interested, I could at least assist by answering questions.

Just to let you know ;)

**Comment by registerrier** [comment]
Thanks for the info @wegenmat . 
The periodicity example we have written in the doc does not run any longer. Some of the astropy code has changed.
Note that in the mean time we have introduced `TemporalModel` that can be used for fitting in gammapy. It might be that the code can be restructured at some point to use this.
Any opinion @AtreyeeS ?

**Comment by AtreyeeS** [comment]
Nice scripts @wegenmat ! I think it will be quite user friendly if we can merge this within gammapy at some point (beyond 1.0, I believe)
At present, we simply encourage users to use gammapy to extract light curves and then use their preffered routines to search for periodicities.

**Comment by adonath** [comment]
By now the `gammapy.time` sub-package was removed. So the remaining documentation is part of the `gammapy.estimators` (see https://docs.gammapy.org/0.17/estimators/lightcurve.html).

What could be useful is to show how users can convert the light curve into a `BinnedTimeSeries` object.

**Comment by adonath** [comment]
After the generalisation of the `FluxPoints` class, I think the most useful thing to do here is add `FluxPoints.to_table(format="binned-time-series")`, such that the following works:
```python3
from gammapy.estimators import FluxPoints
from astropy.timeseries import BinnedTimeSeries

fp = FluxPoints.read()
data = fp.to_table(sed_type="flux", format="binned-time-series")
series = BinnedTimeSeries(data=data)

```
