### ISSUE TITLE
Shorten and simplify analysis_3d notebooks

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#2591]
`analysis_3d.ipynb` and `analysis_3d_joint.ipynb` should be simplified. 
- A minima, perform data reduction with high level interface
- See whether they can be merged

**Comment by adonath** [comment]
As you already started working on this, assigning it to you @AtreyeeS...milestone is v1.0 now.

**Comment by registerrier** [comment]
This is resolved by PR #2652. Closing.
