### ISSUE TITLE
Add a general overview for the gamma-ray data analysis

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#2592]
The gammapy documentation starts with an [overview page](https://docs.gammapy.org/dev/overview.html). See code here: https://github.com/gammapy/gammapy/blob/master/docs/overview.rst

It should be written with a section on:
- Gammapy concept
- Gammapy workflow
- DL3 data format
- Data reduction
- Modeling and Fitting

The text should be kept short with many links to general API documentation and notebooks .

Some figures must be prepared:
- gammapy in the scientific python context
- gammapy workflow

**Comment by cdeil** [comment]
I'll spend a few hours and write a first draft of `docs/overview.rst` now.

I'll start with just some text and bullet points, linking to many other pages and tutorials and the API docs of the most important classes. Figures can come later.

@registerrier @adonath - For `overview.ipynb`, what's the plan? (see [here](https://docs.gammapy.org/dev/tutorials/index.html) what we have now)

I can leave that for a second PR, after `docs/overview.rst` is done, but it would help if there is a plan what `docs/overview.ipynb` would contain. Is the idea that we have zero code snippets in `docs/overview.rst`, and then in `docs/overview.ipynb` we import all the major classes and show how to create one of those objects (i.e. `EventList`, `DataStore`, datasets, models, ...)?

**Comment by cdeil** [comment]
First draft written in #2622 . OK for v0.15 (see https://github.com/gammapy/gammapy/pull/2622#issuecomment-560403958), should be improved for v1.0. Keeping this issue open.

**Comment by registerrier** [comment]
A daughter page has been added in PR #2721 that explains DL3 data. Some figures have been produced and stored in gammapy-extra:

-![](https://github.com/gammapy/gammapy-extra/blob/master/figures/general/data_flow_full.png)
- 

![](https://github.com/gammapy/gammapy-extra/blob/master/figures/general/data_flow_gammapy.png)

![](https://github.com/gammapy/gammapy-extra/blob/master/figures/general/data_flow_gammapy.png)

![](https://github.com/gammapy/gammapy-extra/blob/master/figures/general/data_flow_gammapy.png)


![](https://github.com/gammapy/gammapy-extra/blob/master/figures/general/data_flow_gammapy.png)


![](https://github.com/gammapy/gammapy-extra/blob/master/figures/general/data_flow_gammapy.png)

**Comment by Bultako** [comment]
We have now a specific page [Package structure](https://docs.gammapy.org/dev/userguide/package.html) in the docs which addresses this issue.

There's though still most of the content to add to the [Gamma-ray data analysis](https://docs.gammapy.org/dev/userguide/analysis.html), so I reword a bit the label of this issue and keep it open.

**Comment by registerrier** [comment]
Yes this can be closed.
