### ISSUE TITLE
How to: data access and manipulation

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#2611]
Add a number of how-to information for data access and manipulation. Planned entries are : 

- How to open a data store and access observations?
- How to select observations?
- How to filter selected observations?
- How to explore the IRFs of an observation?

How-to entries should be short (ideally less than 10 lines), with links to the relevant tutorial notebooks and only a few example code lines.

**Comment by adonath** [comment]
What is the status here @QRemy and @registerrier ?

**Comment by registerrier** [comment]
We have two howto's on 
- Access IACT data
- Check IRFs
They more or less cover the first and last point above (albeit too briefly to be clear I am afraid). Point 2 and 3 should be added.

Note that all links to tutorials are broken in the howto page. I will change that in a coming PR.
