### ISSUE TITLE
Remove `simulate.py`

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#2626]
In #2597 I tried to adapt the `simulate_dataset()` helper function in `simulate.py` to be useful according to the current API. However, we decide at the coding sprint that simulations should work through the `Analysis` class. 

This function is not being used anywhere at present (it was being used in the tests before, but not since #2587). 

If @adonath @cdeil and @registerrier agree, I can just remove this function, because it does not do what it pretends to do and is unnecessarily confusing.

**Comment by adonath** [comment]
@AtreyeeS I basically agree, but I think we should wait with the removal until the use-case of simulation is supported by the `Analysis` class. As you already commented in https://github.com/gammapy/gammapy/pull/2597#issuecomment-558199921, this requires to expose the `selection` parameter of the `MapDatasetMaker` on the `Analysis` class.

**Comment by cdeil** [comment]
We will merge #2621 tonight, and then we can try to make this work tomorrow. Please bring it up in the dev call, I'm not sure exactly what changes should be done on `Analysis` and who should do it.

**Comment by adonath** [comment]
I'll add it to the agenda...

**Comment by cdeil** [comment]
@AtreyeeS - Is this issue and #2527 about the same question? Can you close one of the two? And comment in the other one what you think should be done once more, and milestone for v1.0 if not something that can be done tonight?

**Comment by AtreyeeS** [comment]
#2657 is using the `Analysis` class to do the simulations. Once we decide upon the PR, this issue will be addressed

**Comment by adonath** [comment]
The `simulate_dataset()` function was removed in #2788.
