### ISSUE TITLE
Write H.E.S.S. with Gammapy notebook

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#2630]
I'd like to add some infos for [tutorials/hess.ipynb](https://github.com/gammapy/gammapy/blob/master/tutorials/hess.ipynb) (see current version at
https://docs.gammapy.org/dev/notebooks/hess.html).

- add a link to Confluence / contact info / mention HESS slack channel?
- some infos about safe energy threshold and max FOV?
- Anything else?

I think overall it's fine if this is very short, only ~ one hour of work to update?
Or should we put a lot of content here?

@registerrier - Thoughts?

**Comment by registerrier** [comment]
I agree it should be short. We will have another repository dedicated to HESS users anyway.

**Comment by adonath** [comment]
I guess except for adding a link to the (private) HESS bitbucket there is nothing else to do here...?

**Comment by adonath** [comment]
@registerrier I think it's still good idea to add the link to the private pages here..
