### ISSUE TITLE
Add Observation base class

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#2638]
I noticed in  https://docs.gammapy.org/dev/api/gammapy.cube.MapDatasetMaker.html that all the docstrings say that they support `DataStoreObservation`.

Really now we have two classes that are (or should be) supported here and in other places where an observation is used:

- https://docs.gammapy.org/dev/api/gammapy.data.Observation.html
- https://docs.gammapy.org/dev/api/gammapy.data.DataStoreObservation.html

I suggest to resolve this issue by introducing a base class, like this:
```
class Observation:
    """Observation base class."""
    # empty, nothing for now
    # will grow methods, might become an abc.ABC

class MemoryObservation(Observation):
    # exactly what we have now

class DataStoreObservation(Observation):
    # exactly what we have now
```
and to adapt docstrings like in `MapDatasetMaker` (and isinstance checks if we have any).

That's something that can be done in ~ 1 hour, and IMO is the right, achievable solution for v1.0.
The `Observation` and `Observations` parallels the design of `Dataset` and `Datasets`, where `Dataset` is a small base class: https://docs.gammapy.org/dev/api/gammapy.modeling.Dataset.html

@AtreyeeS @adonath @registerrier  - Thoughts?

Anyone willing to send a PR? (otherwise I'd be happy to do it, if it's agreed that it's an improvement)

**Comment by adonath** [comment]
Solved in #2753.
