### ISSUE TITLE
Integrate hspec in Gammapy

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#265]
The `hspec` code was added in `gammapy.hspec` In #264 .
There's a lot of work to do to properly integrate this in Sherpa directly or in `gammapy.spectrum`.
Here's an incomplete list:

- [x] Install Sherpa on travis-ci so that it becomes possible to test this
- [x] Make the command line `gammapy-sherpa-hspec` tool work again. -> this was replaced by two `gammapy-spectrum-*` command line tools.
- [ ] Add a basic test that runs an example analysis.
- [ ] Expose the EBL absorption code as separate classes or functions, download the files from [here](https://github.com/gammapy/gammapy-extra/tree/master/datasets/ebl).
- [ ] Make a proposal how to refactor this code, i.e. which functions / classes we want and where they should go (gammapy.spectrum, naima, Sherpa directly)
- [ ] Re-factor piece by piece (this can partly be done just by improving the code in `gammapy.hspec`, e.g. using the Sherpa class-based API instead of the procedural API to avoid side effects via the global session object.

cc @registerrier @ignasi-reichardt @kingj90 @zblz

**Comment by zblz** [comment]
Regarding first point, these lines works fine in the naima travis.yml:

'''
# Add sherpa conda repository for Python 2.7, numpy 1.8
    - if $OPTIONAL_DEPS && [[ $SETUP_CMD != egg_info ]] && [[ $TRAVIS_PYTHON_VERSION == 2.7 ]] && [[ $NUMPY_VERSION == 1.8 ]]; then conda config --add channels https://conda.binstar.org/cxc ; $CONDA_INSTALL sherpa; fi
'''

**Comment by cdeil** [comment]
@zblz – Do you think EBL absorption should go in `gammapy` or `naima`? (see also #133).

**Comment by cdeil** [comment]
I'm adding Sherpa for the tests on travis-ci in #270.

**Comment by cdeil** [comment]
@kingj90 I've assigned this issue to you and moved it to the 1.0 milestone (for fall).

**Comment by joleroi** [comment]
I don't have an overview what functionality we need to "save". As far as I understand the WStat and the stacking part are now (or will be soon) available in gammapy.spectrum. So there is still the EBL functionality. Anything else? @registerrier

**Comment by registerrier** [comment]
EBL absorption is simply using XSPEC style table models stored in fits. They can be loaded as a multiplicative model in sherpa. 
There are two such table files in hspec, one from Finke et al 2010 and the other from Franceschini et al 2008

**Comment by cdeil** [comment]
@joleroi @registerrier - I'm assigning this issue to you and to the `PyGamma1` milestone, i.e. let's try and finish this up this week.

Please also have a look at https://github.com/zblz/naima/pull/119.

At the moment Naima is more advanced for spectra. Probably the EBL absorption code should be contributed there and then we import stuff from `Naima` where useful in Gammapy?

**Comment by registerrier** [comment]
The main issue with the way EBL is used in hspec is that it depends on sherpa XSTableModel which is not in the stand alone version because it depends on XSpec models.
It can not work as is in Gammapy.

I think we should try to have such models as EBL in the form of XSPEC tables since it provides a general system to store table models with varying parameters (i.e. not only the amplitude). 

So we should have a Table model able to read XSPEC fits tables.  

I think the easiest solution for the moment is to fit the spectra with ebl tables with the regular sherpa after extracting the spectra with GammaPy.

**Comment by cdeil** [comment]
@registerrier - Thanks for your comment!

> The main issue with the way EBL is used in hspec is that it depends on sherpa XSTableModel which is not in the stand alone version because it depends on XSpec models.
It can not work as is in Gammapy.

I would like to remove `gammapy/hspec` in the coming days, because it's not tested and usable at the moment. The idea was that we gradually integrate and merge it into `gammapy.spectrum`, but that hasn't happened.
`gammapy/hspec` will be forever available in the repo here:
https://github.com/gammapy/gammapy/tree/v0.4/gammapy/hspec
So whenever someone has time to add back features (like e.g. @jjlk or @registerrier for EBL absorption) with tests and docs, they can use that as a starting point.

@registerrier - Is this OK with you?

> I think we should try to have such models as EBL in the form of XSPEC tables since it provides a general system to store table models with varying parameters (i.e. not only the amplitude).
> So we should have a Table model able to read XSPEC fits tables.
> I think the easiest solution for the moment is to fit the spectra with ebl tables with the regular sherpa after extracting the spectra with GammaPy.

I think I disagree, but let's see.
For now, having working examples is the most important thing.
If someone can produce an IPython notebook that does something with EBL and spectral analysis from Gammapy, that would be great!

Concerning more general `gammapy.spectrum` clean-up and how to move forward, let's use this issue to discuss:
https://github.com/gammapy/gammapy/issues/33#issuecomment-228846297

**Comment by cdeil** [comment]
`gammapy/hspec` was removed in #593.
I'm closing this issue now.

Please open new issues to discuss e.g. EBL absorption or other related topics (and reference the discussion from this issue if you like).
