### ISSUE TITLE
Fill up the Glossary

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#2671]
This is a reminder issue to fill the glossary for the documentation.

The first user test has shown that a glossary is really important to help people understand what the various concepts are, from gamma-ray data analysis techniques to statistics and main code structures.

**Comment by registerrier** [comment]
This is an on-going effort. Some additions were implemented in PR #2721 .

**Comment by adonath** [comment]
@registerrier FYI: in https://github.com/gammapy/gammapy/commit/ac9ce360f43ee7b7b633a36997c97778b9c53136, I changed the implementation to use the `..glossary::` sphinx directive. This allows to use `:term:` to reference entries in the glossary. See https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#glossary

**Comment by registerrier** [comment]
Glossary has been significantly updated. Closing for now
