### ISSUE TITLE
Add `append` and `extend` methods to `data.Observations` (and other container classes)

### ISSUE THREAD

**Issue by lmohrmann** [gammapy/gammapy#2678]
It would be very helpful if the `data.Observations` container class had methods to add additional observations, like `append` and `extend`. It was previously possible to achieve this by accessing the `list` attribute of this class, but that seems to have been removed. It's still possible by accessing the `_observations` attribute, but that is more of a workaround really.

I know the question of how container classes should be implemented in Gammapy has already been discussed in the past, although I didn't manage to find the corresponding issue. It seems the general idea is to use `collections.abc.Sequence`, but that doesn't seem to provide methods to add to the collection (or I simply haven't discovered them?)

**Comment by adonath** [comment]
Thanks for opening a reminder issue again @lmohrmann! I think the old issue was actually the following PR https://github.com/gammapy/gammapy/pull/2021. What I didn't notice was, that the PR was not fully addressed by #2102. 

For Gammapy v0.15 (in https://github.com/gammapy/gammapy/commit/fa03086418a9e74c5c247d8879a2fdcd57b5eeaa) we introduced the inheritance from `collections.abc.Sequence` for the following classes: 
- `Datasets`
- `SkyModels`
- `Observations`
- `Parameters`

All of these container classes are now instantiated with a list of objects and just offer a minimal API to access the data in it. For now all of these containers are not mutable, i.e. cannot be modified in place. I agree that for all of these classes (except the `Parameters`), it would be useful to offer a minimal API to extend, append or delete items in the container. I'd propose the following:

For `Datasets`, `SkyModels` and `Observations` we change the inheritance to a [MutableSequence](https://docs.python.org/3/library/collections.abc.html). This requires implementing an `.insert()`, `__delitem__()` and `__setitem__()` methods and then offers `.append()`, `.extend()`, `.pop()`, `.reverse()`, `.remove()` as mixing methods. What do you think @registerrier?

**Comment by adonath** [comment]
Addressed in #2744.
