### ISSUE TITLE
Implement `PSF` and `EDISP` maps in `MapDataset.to_image()`

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#2680]
**Gammapy version**
The latest dev

**Bug description**
Currently, `MapDataset.to_image()` returns an empty `PSF` and `EDISP` map.

**Expected behavior**
The IRF maps should be summed over the energy axis as mentioned in the TODO here:
https://github.com/gammapy/gammapy/blob/98ca693ca9e752dd3deea53f8944413fee5c1d3e/gammapy/cube/fit.py#L926

@adonath : I think it was left as a TODO because we wanted to discuss an appropriate implementation? 
Maybe an exposure weighted summing over the energy axis would be appropriate for  PSF?
I am not quite sure how a 2D edisp map should behave. Since this only has a `migra` and `etrue`, should it just be one axis in energy (`MapAxis.squash`) and have one `migra` bin filled with `1`? 
@registerrier what do you suggest?

**Comment by registerrier** [comment]
A priori, I see no reason to keep an `edisp` map when going 2D.  One could (should) use the `edisp` to compute the weighted exposure. 

For the PSF indeed an exposure (and spectrum) weighted sum is what we need. 

Maybe there is also the question of what to do with the safe mask.

**Comment by adonath** [comment]
In general I think there is the option to support image analysis by defining one reconstructed energy bin and an array of true energies in a wider energy range, that is used for model evaluation. This gives the possibility to account for spill over by the energy dispersion. To support the later case, I think we don't have to do anything at all. It will just work with our normal data reduction chain.

So `.to_image()` becomes the method to do the approximate handling of image analysis. So I agree with @registerrier and I think in the current scheme we should just compute the exposure and source spectrum weighted sum of the PSF and drop the energy dispersion.

@AtreyeeS It would be great if you could prepare a PR for this.

**Comment by adonath** [comment]
For the record: once we've implemented this we should remove `PSFKernel.make_image()` to avoid to much code duplication...
