### ISSUE TITLE
Change docstring examples using $GAMMAPY_DATA/tests

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#2683]
The directory $GAMMAPY_DATA/ tests contains data used only in tests. It is obtained with the download command `gammapy download datasets --tests`.

Some examples in doctrines are using them but they won't be reproducible by users. These doctrines must be changed.

Note that to see this one needs to build the documentation without the tests files.

It is the case at least for:
- `~gammapy.maps.ImageProfileEstimator`
- `~gammapy.irf.EnergyDependentMultiGaussPSF`
- `~gammapy.spectrum.FluxPoints`
- `~gammapy.data.FixedPointingInfo`
- `~gammapy.modeling.models.PhaseCurveTemplateTemporalModel`

**Comment by Bultako** [comment]
Thanks @registerrier 
Do you agree in adding a note in the docstrings of the like?


Note
In order to reproduce the example you need the *tests* datasets folder.
You may download it with the following command: 
``gammapy download datasets --tests --out $GAMMAPY_DATA``

**Comment by registerrier** [comment]
OK @Bultako . This can solve the issue, indeed. 

Maybe some frequently used classes or methods should have an example docstring working without the test dataset, but this is likely a very limited set of the methods we are discussing.
