### ISSUE TITLE
Make gammapy pip install work without having cython preinstalled

### ISSUE THREAD

**Issue by MaxNoe** [gammapy/gammapy#2686]
**Is your feature request related to a problem? Please describe.**

Currently, gammapy setup.py is hard-importing cython and cython is required to pip install gammapy.
This is unnecessary and inconvenient.

**Describe the solution you'd like**

* Distribute the c-files in the sdist and only require cython if they are not available.
Thus only a working c-compiler is needed and cython is not a direct dependency for people trying to install gammapy. 

**Additional context**
A working example of that can be found here:
https://github.com/cta-observatory/pyeventio/blob/master/setup.py

Cython is only required for local development and  on the ci server that creates the sdist for PyPI upload, the PyPI upload contains the created c files and they are used if available without needing cython.

**Comment by MaxNoe** [comment]
I can contribute the patch myself, but not in the next two months...

**Comment by adonath** [comment]
Thanks @MaxNoe, for now I have assigned you. Maybe I get to it myself earlier...

**Comment by registerrier** [comment]
This should be solved by #2896 
Closing now.
