### ISSUE TITLE
Export model in MapDataset.to_spectrum_dataset()

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#2696]
**The issue**
As reported by @lmohrmann in issue #2693, the model is not exported when doing `MapDataset.to_spectrum_dataset()`. So that the `npred` estimated by the extracted `SpectrumDataset` does contain only the background component.

**Possible solutions?**
Exporting the `MapDataset`model  requires an evaluation of the models on the MapDataset.geom and the creation of new spectral models integrating the spatial part on the on_region properly.  This can be done but this introduces some complexity because:
- spatial and spectral dimensions can get mixed (because of events leaking outside of the on_region). 
- complex multicomponent models have to handled component by component, or a minima one single component should be exported
- what to do with SkyDiffuseCube models?

Note that this can be way to deal with PSF containment for non circular regions and leaking fraction for extended sources.

**Comment by adonath** [comment]
In general there is the same issue with methods like `.stack()`, `.cutout()`, `.to_image()`. For these methods there is the general question of the bookkeeping of the model. This week we will explore the possibility to introduce a "global" model object. In the latter case the answer is always, that the bookkeeping is left up to the user...

**Comment by adonath** [comment]
The current behaviour is that models are never exported in any of the `MapDataset` methods. The model bookkeeping is left to the user...

In general I think we can implement such "model management" on the `Models` class itself. In this example one could use something like:

```python3
spec = dataset.to_spectrum_dataset()
spec.models = dataset.models.to_spatial_template(dataset.exposure.geom, names=["source", "other-source"])
```

Or if we support `TemplateSpatialModel` in reco energy one can work with the npred as well like:

```python3
spec = dataset.to_spectrum_dataset()
npred = dataset.npred_signal(models=[])

template = TemplateSpatialModel(npred, normalize=False)
```

**Comment by adonath** [comment]
The example I put in my previous comment basically works. A automatic setting / model bookkeeping is not foreseen for v1.0. The model / dataset handling is documented in detail in https://docs.gammapy.org/dev/tutorials/api/model_management.html
