### ISSUE TITLE
smoothed broken power law spectral model

### ISSUE THREAD

**Issue by GernotMaier** [gammapy/gammapy#2700]
(low priority)

I am missing a smoothed broken power law among the available spectral models, as described in Equation 4 in the attached screenshot (from https://ui.adsabs.harvard.edu/abs/2009A%26A...503..817A/abstract)

<img width="798" alt="Screenshot 2020-01-03 at 18 09 37" src="https://user-images.githubusercontent.com/14001688/71737539-3a643e00-2e54-11ea-9c8d-3cbf2d136683.png">

**Comment by adonath** [comment]
Thanks @GernotMaier, indeed this would be useful. I'm adding the `package-novice` label, new models can be implemented with very few effort.

**Comment by adonath** [comment]
Done in #2731.

**Comment by GernotMaier** [comment]
Thanks @QRemy and @adonath !
