### ISSUE TITLE
Allow to pass fixed offset to SafeMaskMaker?

### ISSUE THREAD

**Issue by lmohrmann** [gammapy/gammapy#2704]
I often need to compute energy thresholds (say, based on the energy bias) for a given specific offset angle (e.g. 2 degrees). Currently, it is only possible to specify a certain position for the evaluation of the energy bias, but in particular if one is dealing with extended sources I think it's a valid use case to evaluate the bias at a fixed offset.

It's of course possible to do this "by hand", but it would be a lot more convenient if the `SafeMaskMaker` could do this.

I realize that adding this possibility adds quite a bit of complexity, since the user would need to specify by which method the bias should be evaluated (position of fixed offset) in addition to passing the position or offset, respectively. So I'd like to hear other opinions on this matter.

**Comment by adonath** [comment]
I'm fine to add more options to the `SafeMaskMaker` as needed. I think we can just add an additional `fixed_offset` attribute, which is exclusive with the existing `position` attribute. The new position can be computed from the pointing position using `SkyCoord.directional_offset_by()`. I think it doesn't  add to much complexity...PRs are welcome any time!

**Comment by lmohrmann** [comment]
OK, I will assign this one to me and see if I can find the time to propose a PR.

**Comment by adonath** [comment]
I think this is rather simple to implement (~2 hrs including tests). @lmohrmann Are you still interested to give this a try?

**Comment by lmohrmann** [comment]
Interested: yes
Time to do it: no, unfortunately

So please go ahead implement this if you think it's useful (I think it would be). But it's not something that's absolutely necessary I guess.

**Comment by adonath** [comment]
Addressed in #3338.
