### ISSUE TITLE
Support dropping of axes from MapCoord

### ISSUE THREAD

**Issue by lmohrmann** [gammapy/gammapy#2706]
It seems `MapCoord` is currently not capable of dropping one of the extra axes (typically the energy axis). This would be a nice feature, e.g. if one needs a `MapCoord` object with only the spatial coordinates.

**Comment by adonath** [comment]
Just a two more comments:
- Of course one can use `geom.to_image().get_coord()` anytime to get the spatial coordinates only and `geom.get_axis_by_name("axis").center` to get the coordinates from any axis.
- Before we implement any `MapCoord.drop(axis="energy")` method or similar I'd like to change the internal representation a bit. Currently the coordinates are broadcasted in `MapCoord.__init__`. I think we should not do this and instead keep the separated coordinates and only broadcast if it's really needed. Once this change is made one would get the spatial coordinates only directly as `MapCoord.skycoord`. The it also becomes easy to drop any coordinate from the `MapCoord` object.

**Comment by adonath** [comment]
After #3403 is implemented there is now the support for sparse coordinates so one can do:
```python3
coords = geom.get_coord(sparse=True)
coords.skycoord
```
To get the spatial coordinates only. I will close the issue now. @lmohrmann Please reopen if you think we still need a dedicated `.drop()` API.
