### ISSUE TITLE
Bugs in spectrum_analysis.ipynb

### ISSUE THREAD

**Issue by lmohrmann** [gammapy/gammapy#2708]
**Gammapy version**
0.15

**Bug description**
There are, I think, a few bugs in the tutorial notebook `spectrum_analysis.ipynb`.

1. In the first line of cell 30, it should read
`dataset_stacked.models = model`
rather than
`dataset_stacked.model = model`

2. Because of the above bug, `model` has not been changed in the stacked fit at all. That is why the fit parameters of the stacked fit are precisely the same as those for the joint fit (the errors are not, because these are computed from the covariance which is explicitly set on `model_best_stacked`).

3. The stacked fit somehow seems to use one of the models attached to the individual datasets (in cell 20). However, with a bit of testing I found that the stacked fit does not give sensible results if the model is attached to all of the datasets before stacking.

**Proposed solution**
I think two things need to be changed to get a correct behaviour:

1. The first line of cell 30 needs to be changed as described above. Likely, the stacked fit will give strange results after this change.

2. Before stacking, the models attached to the individual datasets should be set to `None`. Now, the stacked fit should work fine again.

I admit that I haven't tested the second step (don't have time to do this right now), but I'm fairly sure this will work.

**Comment by lmohrmann** [comment]
Small addendum: it seems that the second step of my proposed solution is not even necessary, i.e. the fit should already work fine if `stacked_dataset.models` is set correctly.

**Comment by registerrier** [comment]
Normally, this has been solved by @adonath in the following commit:
https://github.com/gammapy/gammapy/commit/8e6acde7faadbe87e68b1bd648da1b1010899877

Close the issue?

**Comment by adonath** [comment]
Thanks @registerrier, I forgot about this.

**Comment by lmohrmann** [comment]
@registerrier To be honest, I don't see how the commit you linked to fixes these bugs. Could you or @adonath elaborate?

**Comment by registerrier** [comment]
I got it wrong. How about this one?
https://github.com/gammapy/gammapy/commit/24e79069163faa95763119d0990ebf8b31937ef7#diff-43dbc35961d3abbcf8d4387d4d0ff5d0

**Comment by lmohrmann** [comment]
That's more convincing ;-) Thanks!
