### ISSUE TITLE
Reoptimize parameters during flux points computation from the HLI

### ISSUE THREAD

**Issue by luca-giunti** [gammapy/gammapy#2714]
This is a reminder issue.

When one computes flux points (especially for 3d analysis), he might want to re-optimize the background norm in each energy bin. For this reaon, the `FluxPointsEstimator` has the flag `reoptimize=True/False`. For now, however, this is not accessible from the HLI.  

This issue has been raised e.g. in the context of [hess-dl3-dr1 validation](https://github.com/gammapy/gammapy-benchmarks/blob/master/validation/hess-dl3-dr1/README.md).

Notice that, most of the times, only the bkg normalization is to be re-fitted (together with the model scaling). Therefore, *all other spatial and spectral parameters should ideally be frozen* (which don't correspond to the default behavior of the `FluxPointsEstimator` when `reoptimize=True`).

**Comment by Bultako** [comment]
Solved in #2756
