### ISSUE TITLE
Error in MapDataset.to_image if no safe_mask is set

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#2717]
**Gammapy version**
v0.15 and dev

**Bug description**
`MapDataset.to_image()` fails if `mask_safe` is not set.
This code cannot work `counts = self.counts * self.mask_safe`

**Expected behavior**
It should yield the image dataset correctly. So either test if `mask_safe` exists or create a property that returns a `mask_safe` with the correct geom.

**To Reproduce**
```
counts = Map.read("$GAMMAPY_DATA/fermi-3fhl-gc/fermi-3fhl-gc-counts-cube.fits.gz")
background = Map.read(
    "$GAMMAPY_DATA/fermi-3fhl-gc/fermi-3fhl-gc-background-cube.fits.gz"
)
background = BackgroundModel(background)

exposure = Map.read(
    "$GAMMAPY_DATA/fermi-3fhl-gc/fermi-3fhl-gc-exposure-cube.fits.gz"
)
exposure = exposure.sum_over_axes(keepdims=True)
dataset = MapDataset(
    counts=counts,
    background_model=background,
    exposure=exposure
)
dataset.to_image()
```

**Comment by adonath** [comment]
Thanks @registerrier, this is somehow related to the recent question of how we handle "undefined" maps in the `MapDataset`, either by setting it to `None` or keeping it as empty maps. I'll put the point on the agenda for tomorrow's developer call.
