### ISSUE TITLE
Offset in time range with DataStoreObservation.select_time

### ISSUE THREAD

**Issue by mdebony** [gammapy/gammapy#2722]
Hello,

I've encountered a problem when I try to select a specific time range in a run (simulation made with ctools). There are a systematic offset of 1 min and 4,184 seconds applied to the boundaries of the time range.

I've made a small code example :
```python
store = DataStore.from_events_files(['simulation.fits'])
obs = store.obs(1)
print(obs.gti)
timeSelect = Time(['2000-01-01T12:00:00.000', '2000-01-01T12:03:00.000'], scale='utc', format='isot')
print(timeSelect, '\n')
nobs = obs.select_time(timeSelect)
print(nobs.gti)
```

The output I obtain is the following :
```
GTI info:
- Number of GTIs: 1
- Duration: 1800.0 s
- Start: 51544.5 MET
- Start: 2000-01-01T12:00:00.000
- Stop: 51544.520833333336 MET
- Stop: 2000-01-01T12:30:00.000

['2000-01-01T12:00:00.000' '2000-01-01T12:03:00.000'] 

GTI info:
- Number of GTIs: 1
- Duration: 179.99999999999937 s
- Start: 51544.50074287037 MET
- Start: 2000-01-01T12:01:04.184
- Stop: 51544.5028262037 MET
- Stop: 2000-01-01T12:04:04.184
```
I've tried with several time interval the offset is always the same.
I use the version 0.15 of gammapy.

**Comment by registerrier** [comment]
Thanks @mdebony , I think the issue is due to the `scale`used to define the times. The `GTI` use by default a scale in terrestrial time `tt` (see https://docs.astropy.org/en/stable/time/#time-scale),
where as your input time is give in `utc`. If you express your time in `tt`, you obtain:
```
timeSelect = Time(['2000-01-01T12:00:00.000', '2000-01-01T12:03:00.000'], scale='utc', format='isot') 
print(timeSelect.tt, '\n')                                                                                                                                           
['2000-01-01T12:01:04.184' '2000-01-01T12:04:04.184'] 
```.

**Comment by mdebony** [comment]
Ok, using tt time scal fix the problem.
Thanks

**Comment by registerrier** [comment]
PR #2723 should improve the readability of the output of `GTI.__repr__`, limiting the confusion.
