### ISSUE TITLE
Add gammapy.catalog.GalacticLatitudeDistribution class

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#274]
We should add a GalacticLatitudeDistribution class that has methods for:
- [ ] quick plot (see [here](http://astropy.readthedocs.org/en/latest/visualization/histogram.html))
- [ ] density estimation and bootstrap error bands
- [ ] simple model fit (e.g. gauss + const) and error propagation to get an error band

Thoughts and ideas for other features welcome!

(I started experimenting with this in a [notebook](http://nbviewer.ipython.org/gist/cdeil/fcf560bb4d906c251459))

**Comment by cdeil** [comment]
So now that we're getting several 10k lines of analysis code in Gammapy, my feeling is that we should go the other way, and not add things that will be used by very few people, and start removing such things. We discussed this today at dinner and all others recommended the same thing.

So now my proposal would be that we close this issue, and instead remove this similar class now:
http://docs.gammapy.org/en/latest/api/gammapy.catalog.FluxDistribution.html

@adonath @joleroi  - Thoughts?

Just on removing `gammapy.catalog.FluxDistribution` for now, and then next week we can go through Gammapy together and just delete a lot of old stuff if we all three think it's OK to remove.

**Comment by adonath** [comment]
:+1: Yes, I'm totally in favour of removing old stuff, that is not used, broken or in very bad shape. We should focus on the important analysis code (1D, 2D, 3D) and rather try to improve the existing code base.

**Comment by cdeil** [comment]
Closing this old issue.
The `gammapy.catalog.FluxDistribution` was already removed.
