### ISSUE TITLE
info_table() fails for MapDatasets

### ISSUE THREAD

**Issue by Bultako** [gammapy/gammapy#2749]
**Gammapy version**

0.16.dev

**Bug description**

When working with MapDatasets calling the `info_table` method fails with the following error.
```
AttributeError: 'MapDataset' object has no attribute 'info_dict'
```

**Expected behavior**

I would expect at least not to expose the `info_table` method for MapDatasets

**Comment by registerrier** [comment]
A possibility here is to create a `SpectrumDataset` from the `MapDataset` and use its `info_dict`.  Possibly passing a `region`.

**Comment by registerrier** [comment]
My suggestion here is to add a `region` argument to `Datasets.info_table` that would be unused for a `SpectrumDataset` but would be used to integrate for maps.

**Comment by AtreyeeS** [comment]
The `Datasets.info_table` calls `dataset.info_dict`, so it is necessary to define a separate `MapDataset.info_dict`.

I think that for maps it might useful to see the total `npred` or the `background`, or see that the effective area is not zero anywhere... For ex, I am looking for large scale diffuse emission now, so do not have a specific region in mind for a quick look.

What I can do is keep an optional `region` argument. If `region` is passed to a `MapDataset`, it is converted to a `SpectrumDataset` and the corresponding `info_dict` is used. If not, general info like the total `counts`, `background` `npred` `excess` `effective_area` (min and max) is printed?

Does that sound ok @registerrier ?
