### ISSUE TITLE
MapDataset.cutout fails with mode=partial option

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#2754]
`MapDataset.cutout` is used in the observation loop to produce a `MapDataset`. By default it is set with option `mode='trim'`. This option simply cut a fraction of the target dataset irrespective of the requested map size. 

This option is an issue if one is to use `FoVBavkground` or `RingBackground`. Especially in the latter case, one needs to have the full field of view to perform proper ring background estimation.
It is therefore necessary to use option `mode='partial'` for the observation loop.

With the current dev version (and former ones as well), the `Map.cutout` does not support this option, because the data of the new `Map` must be created first and only the parent slice should be set to the cutout values. 
Also `WcsNDMap.stack` fails for such maps because the `weight` argument does not use slices (and its geometry is not compared to that of the input `Map`).

**Comment by adonath** [comment]
Solved in #2755.
