### ISSUE TITLE
Consider using pytest-astropy-header or similar

### ISSUE THREAD

**Issue by bsipocz** [gammapy/gammapy#2758]
Currently it's rather difficult to see what actual versions are used in a test run (what's the numpy version e.g. here? Sure one can dig into the thousands of lines above and hope to find the latest one https://travis-ci.org/bsipocz/gammapy/jobs/645270814#L4232)

Recently we've refactored the pytest headers from astropy (https://github.com/astropy/pytest-astropy-header), you may want to consider using it (or any other similar things).

**Comment by adonath** [comment]
Thanks @bsipocz, for digging into this. I noticed just a few days ago, that we had a reminder issue to add back the pytest header https://github.com/gammapy/gammapy/issues/2336. I'll work on it this week...

**Comment by adonath** [comment]
Addressed in https://github.com/gammapy/gammapy/commit/b76cb8e03331eae45d16ac5c36763866a691083a
