### ISSUE TITLE
Naima Self Synchrotron Compton Model

### ISSUE THREAD

**Issue by tunbehaun273** [gammapy/gammapy#2766]
**Is your feature request related to a problem? Please describe.**
When fitting a NaimaSpectralModel of an InverseCompton radiative model with a self synchrotron component like in the naima example: "https://naima.readthedocs.io/en/latest/examples.html#crab-nebula-ssc-model", the synchrotron component is given as raw data and is not updated during the Fit. So the resulting model takes the fitted particle distribution for the InverseCompton model but the initial particle distribution for the Synchrotron model.

**Describe the solution you'd like**
Whenever the InverseCompton model with SSC component is evaluated based on a particle distribution a Synchrotron model based on the same particle distribution should give the photon density of the SSC component. For one special case a work around could look like the attachment NaimaSpectralModel_new.txt. However this is not very general since a lot of values for the synchrotron component (B, Emax, Emin, Rpwn) are fixed and not available for the user. It might also be slow to generate a new Synchrotron model in every evaluation.

[NaimaSpectralModel_new.txt](https://github.com/gammapy/gammapy/files/4165231/NaimaSpectralModel_new.txt)

**Comment by registerrier** [comment]
Thanks @tunbehaun273 . Indeed, to support SSC models it is necessary to create a specific model inheriting from `NaimaSpectralModel` since the target photon field must be dynamically linked to the synchrotron emission of the `ParticleDistribution` being fitted.
Maybe we could introduce a specific `SSCNaimaSpectralModel` or show an example tutorial on how to do it.

**Comment by registerrier** [comment]
This should be addressed by PR #2767 .
Can you test @tunbehaun273 and re-open the issue if this does not work?
