### ISSUE TITLE
Observatory UTC offset

### ISSUE THREAD

**Issue by mapazarr** [gammapy/gammapy#277]
Observers
 https://github.com/gammapy/gammapy/blob/master/gammapy/obs/observers.py
needs a method to get not only the observatory location, but also the time offset w.r.t. UTC for a certain local time.
This is important for celestial <-> terrestrial coordinate transformation, as described in:
 http://astropy.readthedocs.org/en/latest/coordinates/observing-example.html
This is non trivial, since the time shift between UTC and local times changes during the year (summer/winter time), and at different times for different locations in the Earth. This might need some synchronization with a time server.
The high-level API could be:
`from gammapy.obs import observatory_UTC_time_offset`
`observatory_UTC_time_offset[observatory='HESS', localtime]`
with localtime an object of type `~astropy.time.Time`.

**Comment by cdeil** [comment]
@mapazarr UTC / local time is something we're discussing in https://github.com/astroplanners/astroplan/pull/4. Probably there the default will be that everything is done in UTC by default, but then if the user sets a time zone, it's possible to pass times in and get them out in local time.

In Gammapy I don't see the need to support local time. You can do coordinate transformations just using `astropy.time.Time` and `astropy.coordinates`, see e.g. [here](https://hess-confluence.desy.de/confluence/display/~christoph.deil/Crosscheck+of+H.E.S.S.+coordinate+transformations+with+Astropy) or [here](https://github.com/gammapy/gammapy/blob/master/gammapy/data/event_list.py#L697).

Now I know the EventList and EventListChecker and other classes need more work concerning coordinates and time. Specific issues on what needs to be added where, or better pull requests are very welcome. But I think what you're suggesting here is to add time zone info to the gamma-ray observatory EarthLocation objects (see [here](https://github.com/gammapy/gammapy/blob/master/gammapy/obs/observers.py#L46)), and for this I don't see the need !??

**Comment by mapazarr** [comment]
Ok, I see, if everything is done in UTC, there is no need fr such a method.
