### ISSUE TITLE
Dark Matter Primary Flux

### ISSUE THREAD

**Issue by kstre** [gammapy/gammapy#2770]
Gammapy version: 0.16

The Dark Matter Primary Flux is supposed to have a cut off at the Dark Matter particle mass.
When interpolating the data from "$GAMMAPY_DATA/dark_matter_spectra/AtProduction_gammas.dat" the mass of the DM particle is not taken into account.
I avoided the bug by returning a flux of Zero, if the evaluated energy is greater than the DM mass. But maybe there is a better way, to interpolate the datapoints in the beginning.

**Comment by Bultako** [comment]
Thanks @kstre for spotting this !

Yes, we should find a way to set the flux to zero when extrapolating outside the energy range given in the `TableSpectralModel` built with the `AtProduction_gammas.dat` file.

I guess replacing this line https://github.com/gammapy/gammapy/blob/520012064e90aa18d94e52d0cddf0c96ce52a592/gammapy/astro/darkmatter/spectra.py#L120

by the one below
```
return TemplateSpectralModel(energy=energies, values=dN_dE, interp_kwargs={"fill_value":-10e10})
```

could just fix it,  but I'd like to have a more elegant way to do it.

thoughts?
@adonath @registerrier

**Comment by adonath** [comment]
Thanks @Bultako and @kstre for looking into this. I think changing the default interpolation behaviour is fine and a reasonable solution. I would not see any need for a more elegant solution. For the `LogScale` we have defined a "tiny" value, that is used to represent zero. See: https://github.com/gammapy/gammapy/blob/master/gammapy/utils/interpolation.py#L159, this could be used as fill value like so:

```python3
import numpy as np
from astropy import units as u
import matplotlib.pyplot as plt
from gammapy.modeling.models import Models, SkyModel, TemplateSpectralModel
from gammapy.utils.interpolation import LogScale

energy = np.array([1, 3, 10, 30]) * u.TeV
values = np.array([1e-12, 3e-13, 1e-13, 3e-14]) * u.Unit("MeV-1 s-1 cm-2")
model = TemplateSpectralModel(
    energy=energy,
    values=values,
    interp_kwargs={"fill_value": np.log(LogScale.tiny)}
)
```

**Comment by Bultako** [comment]
I have made PR https://github.com/gammapy/gammapy/pull/2771 to fix this.
@kstre, please tell us if this actually solves the issue before merging.

**Comment by kstre** [comment]
Thanks for the fix! 
It works for the Cutoff, but I got the warning Interpolated values reached float32 precision limit.

**Comment by adonath** [comment]
@kstre This warning can be basically ignored, we implement a better handling for the interpolation some time ago. Once you update to a more recent Gammapy version the warning should be gone.
