### ISSUE TITLE
gammapy.analysis.get_flux_points(source="crab") fails  to create flux points.

### ISSUE THREAD

**Issue by 9635065235** [gammapy/gammapy#2774]
With gammapy-0.16  the following command line does not work.

`analysis.get_flux_points(source="crab")`
This redirects to the following error:
`TypeError: get_flux_points() got an unexpected keyword argument 'source'`
With gammapy-0.15 this works fine.

**Comment by adonath** [comment]
@9635065235 In Gammapy v0.16 the parameter has moved to the configuration file. See e.g. here: https://docs.gammapy.org/0.16/analysis/index.html#flux-points

Note that the API of Gammapy is still unstable and expected to change until v1.0. I realise it is currently hard for users to keep track with those little changes, but those are required to arrive at a more stable API for v1.0. For those kind of questions we can also provide quicker help on http://gammapy.slack.com. Let me know if you'd like to join the Gammapy Slack...

**Comment by 9635065235** [comment]
Thanks a lot. I would rather like to ask this kind of questions to Slack.
Therefore, please add me to the Gammapy Slack channel. I could create an account in Slack but it seems that email ids with 'desy.de' is still unavailable for it.

**Comment by adonath** [comment]
@9635065235 You should have received an invitation.
