### ISSUE TITLE
Plotting lightcurves

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#2819]
While using the `LightCurveExtractor`, I see that it does not create a `is_ul` column on the `Lightcurve.table` it produces. This is necessary because the `Lightcurve.plot()` uses `_get_flux_uls` to decide which points to deem as upper limits, which in turn takes it from the column name. The plot it now produces in the absence of upper limits is quite difficult to read. 

We do not have upper limits in our notebooks, so this was not noticed.

**Comment by adonath** [comment]
@AtreyeeS I think we should just go for consistency with `FluxPoints.plot()` here. So if the `is_ul` column is provided upper limits are plotted, if not we just plot the data point and errors. Can you prepare a PR to fix this?

**Comment by registerrier** [comment]
Any news on this @AtreyeeS ?

**Comment by adonath** [comment]
I think this is related to the unification of the estimator result objects...
