### ISSUE TITLE
TableModel (from 0.12 to 0.16)

### ISSUE THREAD

**Issue by tstolarczyk** [gammapy/gammapy#2831]
I am moving a code from 0.12 to 0.16 (https://github.com/tstolarczyk/SoHAPPy)

I have been using TableModel, and other function of that kind, from gammapy.spectrum.models.
I understand that essentially the functionalities were moved to gammapy.modeling.models

I cannot find the equivalent of TableMoel in 0.16 despite my efforts (nothing in the doc, nothing in the log, and nothing in the issues after a quick search).

1. Why is it not possible to track back that change easily (forgot to look somewhere)?
2. Can you indicate if there is a "replacement" for gammapy.spectrum.models.TableModel ?

Thanks !

**Comment by registerrier** [comment]
For clarity we introduced a new naming scheme for models. The `TableModel` became a `TemplateSpectralModel`. Normally, it should work in a nearly identical way. 
A tilt parameter has been added that did not exist on the `TableModel`.

Can you check that it works? And if yes close the issue.

**Comment by tstolarczyk** [comment]
It works, thanks !
