### ISSUE TITLE
Linking parameters of two models

### ISSUE THREAD

**Issue by tunbehaun273** [gammapy/gammapy#2859]
**Gammapy version 0.17**

**Bug description**
When fitting two datasets with two different models, but linking the parameters of the models `(model1.amplitude = model2.amplitude)` and starting a fit I get the following error: 

```
ValueError                                Traceback (most recent call last)
<timed exec> in <module>

/home/woody/caph/mppi086h/software/anaconda3/envs/gammapy-0.17/lib/python3.7/site-packages/gammapy/modeling/fit.py in run(self, backend, optimize_opts, covariance_opts)
    112             return optimize_result
    113 
--> 114         covariance_result = self.covariance(backend, **covariance_opts)
    115         # TODO: not sure how best to report the results
    116         # back or how to form the FitResult object.

/home/woody/caph/mppi086h/software/anaconda3/envs/gammapy-0.17/lib/python3.7/site-packages/gammapy/modeling/fit.py in covariance(self, backend, **kwargs)
    216 
    217             covariance = Covariance.from_factor_matrix(
--> 218                 parameters=self._models.parameters, matrix=factor_matrix
    219             )
    220             self._models.covariance = covariance

/home/woody/caph/mppi086h/software/anaconda3/envs/gammapy-0.17/lib/python3.7/site-packages/gammapy/modeling/covariance.py in from_factor_matrix(cls, parameters, matrix)
     70 
     71         if not matrix.shape == (npars, npars):
---> 72             matrix = cls._expand_factor_matrix(matrix, parameters)
     73 
     74         scales = [par.scale for par in parameters]

/home/woody/caph/mppi086h/software/anaconda3/envs/gammapy-0.17/lib/python3.7/site-packages/gammapy/modeling/covariance.py in _expand_factor_matrix(matrix, parameters)
     58         mask = np.array([par.frozen for par in parameters])
     59         free_parameters = ~(mask | mask[:, np.newaxis])
---> 60         matrix_expanded[free_parameters] = matrix.ravel()
     61         return matrix_expanded
     62 

ValueError: NumPy boolean array indexing assignment cannot assign 49 input values to the 144 output values where the mask is true
```

In my case there are 5 free model parameters and two free background_model parameters (one norm for each dataset), so 7 free parameters are fitted and the covariance matrix is of size 7x7. But the fit counts the 5 free model parameters twice so it expects a 12x12 matrix.

**To Reproduce**
create two datasets
create two models
link the parameters of the model `model1.amplitude=model2.amplitude, model1.index=model2.index, ...`
assign the models to the datasets `dataset1.models.append(model1), dataset2.models.append(model2)`
fit the two datasets `fit = Fit ([dataset1, dataset2]), fit.run()`

**Comment by QRemy** [comment]
Thanks for reporting this, I'll investigate the problem.

**Comment by tunbehaun273** [comment]
So I tried to look into this problem a little bit more and I have now a solution that seems to work fine for my case. The method _expand_factor_matrix() in the gammapy.modeling.covariance class calculates a mask for the frozen parameters (mask) but it does not account for not unique parameters. So the shape of the matrix given by the Fit class is of smaller shape than the mask `free_parameters`. So I calculated a second mask called `not_unique` which is added to the free_parameters mask.
`@staticmethod
    def _expand_factor_matrix(matrix, parameters):
        """Expand covariance matrix with zeros for frozen parameters"""
        npars = len(parameters)
        matrix_expanded = np.zeros((npars, npars))
        mask_frozen = np.array([par.frozen for par in parameters])
        
        mask_not_unique=[]
        for i, x in enumerate(list(parameters)):
            if list(parameters).index(x) == i:
                mask_not_unique.append(False)
            else: mask_not_unique.append(True)
                
        mask = mask_frozen | np.array(mask_not_unique)
        
        free_parameters = ~(mask | mask[:, np.newaxis])
        matrix_expanded[free_parameters] = matrix.ravel()
        return matrix_expanded`
This code prevented the error from occuring but I don't know if it destroys anything else in gammapy.
But at least for my case it works untill now.
What do you think of it?

**Comment by QRemy** [comment]
Thanks, I reached the same conclusion the mask has to take into account duplicate parameters
```python
        mask_frozen = [par.frozen for par in parameters]
        pars_index = [np.where(np.array(parameters)==p)[0][0] for p in parameters]
        mask_duplicate  = [pars_index[idx]!=idx for idx in range(len(parameters))]
        mask =  np.array(mask_frozen) |  np.array(mask_duplicate)
```
Still have to copy the covariance element for the duplicate parameters correctly.

**Comment by tunbehaun273** [comment]
That's true. In my case, where I linked all the parameters of the models, the covariance matrices for both models were exactly the same. I thought this is what I would expect, so I did not question this any further. Neither I checked what would happen if not all parameters of the models are linked. If you figure out a way to do this correctly could you share it here so I can use it until the release of the next stable version?

**Comment by QRemy** [comment]
I tried to link only the index and not the amplitude, and found that the sub-covariance matrices of the two source are correctly build with only the relevant elements repeated.

**Comment by tunbehaun273** [comment]
Perfect, thank you!
