### ISSUE TITLE
Stacking in time observations stacked on several observatories 

### ISSUE THREAD

**Issue by tstolarczyk** [gammapy/gammapy#2860]
Hello,

I have - I think- a conceptual problem with observation stacking that I am not sure can be solved in Gammapy now. This is probablyrelate to issue #1263, but different I guess.

So far this occurs with gammapy 0.12 but my first trials with 0.16 show it would certainly be the same.

I am simulating GRBs in CTA North and South.
A GRB is a set of energy spectrum for a series of times (dates).
From the measurements in time I create time slices in which I evaluate the counting rates in CTA using the given spectra.

From the original GRB slices, after applying a realistic visibility (SWIFT), I have a list of observation slices with an IRF corresponding to a livetime 'obstime' and a GRB position in the sky (assumed fixed during the time slice).

I loop over the time slices [idx] creating each time an observation (here the IRF has been associated to a class instantiation "mc"):
    obs = SpectrumDatasetOnOff(counts     = on_vector,
                                counts_off = off_vector,
                                aeff       = mc.perf[idx].aeff,
                                edisp      = mc.perf[idx].rmf,
                                livetime   = obstime )

Later I stack all these observations to get the evolution of the on and off counts with slices. 
In the end, this allows me finding the time slice where I have a 5 sigma detection.
This works fine in gammapy 0.12 and I have started to modify this to go to 0.16.

Note: so far I only use the total ON and OFF count rates so I could completely bypass the Gammapy Observation but soon I want to extract the energy spectrum of the detected GRB and I want to use the tools for this.

Now my problem is the following :

In some situation, the GRB is seen on both sites.
In these conditions, I have re-organised (re-chopped) the time slices to get common time slices so that I can compute counts at the same moment (same slices) on both sites.
I naively thought I could simply cumulate the on and off counts of both sites, on_vector = on_south + on_north, to create a "cumulated observation" but I realise that it is obviously not possible since each observation is attached to a different IRF (they are different in South and North obviously).

Is there a native solution to this problem ? 
In particular is it possble to stack an observation (in time) that would contained stacked (N+S) observations?
Or should I create separate N and S observations with common slices (i.e. on=off=0 if not visible on one of the sites), stack them slice by slice, and then cumulate the summed observations?

Your advices are welcome !
Thierry S.

**Comment by QRemy** [comment]
Hello sorry for the late response. I don't know much about time analyses but regarding your problem I think you should create `SpectrumDatasetOnOff ` for each site  with the same time bins and apply visibility mask on each dataset using `SpectrumDatasetOnOff.mask_fit`. Then for stacking you can try:
`dataset_stacked = dataset_north.copy()`
`dataset_stacked.stack(dataset_south) `

@registerrier @JouvinLea @AtreyeeS you are more familiar with time analyses, is it really necessary to have one dataset per time bin as described, or could we have only one dataset per site directly in 2D with time and energy axes. in principle it should be possible with v0.17 if counts are given as [RegionNDMap](https://docs.gammapy.org/0.17/api/gammapy.maps.RegionNDMap.html?highlight=gammapy%20maps%20regionndmap#gammapy.maps.RegionNDMap.from_geom) ?

**Comment by adonath** [comment]
Thanks @tstolarczyk for this issue report. 

As far as I understood you want to combine observations from different CTA sites taken at the same time. In general this can be done using `SpectrumDatasetOnOff.stack()`, but for now
we cannot stack observations (aka `SpectrumDatasetOnOff`) which are taken at the same time. In 

Gammapy we require the GTIs defined with the dataset to be unique. But in your case, as you already mentioned, the IRFs are different anyway. To account for this you probably want to do a "joint analysis" anyway. It basically reduces to the following code:
```
spectrum_dataset_south = SpectrumDatasetOnOff()
spectrum_dataset_north = SpectrumDatasetOnOff()

models = SkyModel()
spectrum_dataset_south.models = models
spectrum_dataset_north.models = models

fit = Fit([spectrum_dataset_north, spectrum_dataset_south])
result = fit.run()
```
Does this makes sense to you? Is this what you wanted top achieve? At this point I'll include @registerrier in the discussion, I'm sure he can help as well.

**Comment by registerrier** [comment]
In principle, stacking datasets from different instruments or configurations is possible but I would not recommend it. (At the moment, I notice this would silently return an incorrect result because livetimes and GTIs and separated in `SpectrumDataset`).
The suggestion above seems the good one. 
If you simply want to look at count statistic in each time bin, I would also consider them as two distinct measurement and determine the significance from the sum of the two delta TS  which should be distributed as a chi square with 2 dof.

**Comment by adonath** [comment]
The proposed solution here is to just do a joint analysis. I'll close the issue now.
