### ISSUE TITLE
Adapt MapDataset.to_image() to produce IRFs in reco energy

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#2865]
`MapDataset.to_image()` is used to reduce 3D datasets to 2D ones. The resulting `MapDataset` can then be used for morphological studies.

One difficulty with this approach is that the resulting IRFs are summed over true energies and might not properly reflect the masked energy bins and will not cover the same energy range if the true energy range is different from the reco energy range (which is usually preferable). 

Two behaviors are possible:
- true energy IRFs are left untouched, `to_image` is applied only to counts and background model. `edisp` must be adapted to have only one reco energy bin.
- true energy exposure and PSF are reprojected on reco energy (with the edisp) and then summed over the correct energy range.  e.g:
`expo(x,y,E_i) = \int dE_0 dOmega Aeff(E_0,x_0,y_0) Phi(E_0) PSF(x,y|x_0,y_0,E_0) Edisp(i|E_0)`
`PSF(delta_x,delta_y, E_i) =  \int dE_0 Aeff(E_0,x_0,y_0) Phi(E_0) psf(x,y|x_0,y_0) Edisp(i|E_0)/expo(x,y,E_i)`
`\phi(E_0)` being the spectral model used for averaging over energies.

I suggest we offer the second option. The first one is not very useful in itself. It is probably as simple to perform 3D fits, possibly limiting to a precise energy range.

This could be implemented first by adding methods to compute the average exposure and PSF in the reco geometry. Then `MapDataset.to_image()` can call them.

Opinions @AtreyeeS @adonath ?

**Comment by AtreyeeS** [comment]
Thanks @registerrier for bringing this issue up. Indeed the `to_image` is totally useless in its present form.

I am a bit unsure if the first option is equivalent to performing 3D fits in a given range, say for energy dependent morphologies where I do not want to take such complications into account but fit a GaussianSpatialModel above a threshold.

I am also confused about how to implement the second option. If the method to compute the `reco_exposure` resides on the `MapDataset`, it does not have access to the `aeff`.

As a technicality, the exposure axis must be named `energy_true` for model evaluation. It be confusing to have an exposure in reco energy and can it etrue...

A side note, currently `to_image` discards the models on the imaged dataset. I would prefer that they remain.

**Comment by adonath** [comment]
Thanks @registerrier for bringing up this topic again. 

I think the standard (and only properly supported way) to do an image analysis should be the first option: use a grid of true energies and an energy dispersion matrix with a single reco energy bin. I think we should not support any other case as a standard analysis. I know this is different from what people have done in the past, but that's how it is. It was done in an incorrect approximate way, now we can handle it correctly during fitting, so we should just do it. Spatially varying energy thresholds are only supported for 3D analysis. This option could be supported with e.g. `MapDataset.sum_over_axes()` as well.

Adapting our model evaluation to the case of fitting a spatial model only and supporting IRFs in "reco energy" is a lot of work with not much profit. I think it's even a fair option that the resulting dataset returned by `.to_image()` cannot be used for fitting at all, but only for visualisation and (currently) TS map estimation. If we want to support the second option I think we should stick with our current conventions. I think if true and reconstructed energy are equivalent we should always handle this case with a unity RMF matrix. So in this case it will just be a 1x1 matrix...

**Comment by AtreyeeS** [comment]
> I think it's even a fair option that the resulting dataset returned by `.to_image()` cannot be used for fitting at all, but only for visualisation and (currently) TS map estimation.

A quick point: at present, the TS map estimation does not work after `to_image`, as there is no `npred`.

**Comment by registerrier** [comment]
I suppose that there is an issue regarding the expected usage of `.to_image()`. It is there initially mostly to support `RingBackgroundMaker`. Generally, it is not really possible to export `npred` in downgraded `Dataset`. e.g. properly exporting the model in `MapDataset.to_spectrum_dataset()` is not possible at all. 
In that sense, usage of `.to_image()` to look at residuals in some energy range is probably not the way to go.  Yet TS map estimation can still work, but it will use the model evaluation using image-like IRFs, hence it will most likely find different values for source flux (in particular, because we don't take into account edisp while producing 2D responses).
So we should find good ways to explore residuals in 3D fitting. Possibly by relying internally on the `ExcessMapEstimator`.

**Comment by registerrier** [comment]
Then there is the question of how we support working with `MapDatasetOnOff`. If true OFF measurements can probably be used for 3D fitting, ring background is most of the time only 2D.

So we can follow only option 1 , e.g. simply collapse `edisp` to the remaining bin in reco energy, but leave the true energy as is. Getting the reco energy exposure or reco PSF, is in practice only a npred calculation with these reduced maps (with, respectively, a constant spatial model and a point source model).

Actually, this would also help with the `npred` calculation for TS map that you mention @AtreyeeS  no?

**Comment by AtreyeeS** [comment]
For the specific case of the Ring Background analysis, I guess it is not unreasonable to ask users to start with one bin in `e_reco`? In this case, do we still need any special `to_image` sort of support for the Ring Analysis separately?

I also believe it is fine if the `to_image` does not support any modelling and fitting purpose.

But what would be nice to have is support for the follow science case: What I am doing now is making 3D maps, doing a modelling and fitting etc. And then, I want to look at the correlated significance and excess maps above certain thresholds. At present, this is really painful because for each threshold, I have to make a mask on energies, sum the masked `counts` and `npred`, create the convolution kernel (converting the angular size to pixel size etc) and manually make a call to `CashCountStatistics` (or `WStatCountStatistics`). This is extremely unpleasant, and quite error prone.

Maybe we can rather adapt `to_image` to facilitate this somehow? 
I don't know what is the best way to do it though.

**Comment by registerrier** [comment]
> Maybe we can rather adapt `to_image` to facilitate this somehow?
> So we can do option (1), plus with an optional mask in e_reco as a parameter?

Probably the main issue is the absence of easy methods to set masks on the data. Although a user would not change the `safe_mask` but rather the `fit_mask`. 

Note there is a discussion about this issue here: #2701

**Comment by adonath** [comment]
The implemented behaviour, is that we keep the true energy axis untouched in methods like `.to_image()` and have additional helper methods to compute IRFs and exposure in repo energy. I think there is nothing left to be done here...except clarifying how the mask are taken into account?

**Comment by adonath** [comment]
For the mask handling there is now a dedicated issue #2170. I'll close this one here.
