### ISSUE TITLE
Setting background_model to none on a dataset

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#2873]
I am not sure if this is expected behaviour or it is a bug, but I find this very confusing:
Suppose I have a `dataset`  with a background_model and one sky model.
`dataset.models`  returns both these model, as expected. 
Now, I do `dataset.background_model=None` .

`dataset.models` now gives me:

```
ModelsModels
Component 0: BackgroundModel
  Name                      : stacked-bkg
  Datasets names            : ['stacked']
  Parameters:
    norm                    :   1.300              
    tilt         (frozen)   :   0.000              
    reference    (frozen)   :   1.000  TeV         
Component 1: SkyModel
  Name                      : gc-source
  Datasets names            : None
  Spectral model type       : ExpCutoffPowerLawSpectralModel
  Spatial  model type       : PointSpatialModel
  Temporal model type       : None
  Parameters:
    index                   :   2.300              
    amplitude               :   2.80e-12  1 / (cm2 s TeV)
    reference    (frozen)   :   1.000  TeV         
    lambda_                 :   0.020  1 / TeV     
    alpha        (frozen)   :   1.000              
    lon_0                   :  -0.050  deg         
    lat_0                   :  -0.050  deg         
```
I would expect Component 0 to have vanished now...

comments @registerrier @QRemy @adonath ?

**Comment by QRemy** [comment]
Not sure that should be allowed maybe dataset.background_model should be a property. Why do you want to set it to None ?

**Comment by adonath** [comment]
Thanks @AtreyeeS, these inconsistencies are still a result of the unsolved question of background and global model handling in Gammapy. In this specific case I’m pretty sure the background_model attribute will be removed soon and the only way to interact with the model will be MapDataset.models. The minimal action here could be to make the background_model attribute read only...

**Comment by AtreyeeS** [comment]
@QRemy : Indeed I do not have a reasonable science case for it, but this in done in the tests 
eg:  https://github.com/gammapy/gammapy/blob/5f8eaf2d4c3c89a2705e6897c2ecc9f04b5c38b1/gammapy/datasets/tests/test_map.py#L254
which I realised while implementing #2870 .

Thanks for the clarification @adonath ! I keep this issue open till we sort this out.
