### ISSUE TITLE
Flux point estimation fails with ValueError

### ISSUE THREAD

**Issue by luca-giunti** [gammapy/gammapy#2876]
**Gammapy version**
V0.17

**Bug description**
I am using: 
```
e_edges = np.logspace(...) * u.TeV
fp = FluxPointsEstimator(e_edges=e_edges, source="mysource", reoptimize=False)
flux_points = fp.run(datasets=datasets, steps=["ts", "err"])
```
I get the error message:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-19-55ee89efe84a> in <module>
----> 1 flux_points_A = fpe_A.run(datasets=datasets, steps=["ts", "err"])~/anaconda3/envs/gammapy-0.17/lib/python3.7/site-packages/gammapy/estimators/flux_point.py in run(self, datasets, steps)
    870 
    871         table = table_from_row_data(rows=rows, meta={"SED_TYPE": "likelihood"})
--> 872         return FluxPoints(table).to_sed_type("dnde")
    873 
    874     def _energy_mask(self, e_group, dataset):~/anaconda3/envs/gammapy-0.17/lib/python3.7/site-packages/gammapy/estimators/flux_point.py in __init__(self, table)
    136         # validate that the table is a valid representation
    137         # of the given flux point sed type
--> 138         self._validate_table(self.table, table.meta["SED_TYPE"])
    139 
    140     def __repr__(self):~/anaconda3/envs/gammapy-0.17/lib/python3.7/site-packages/gammapy/estimators/flux_point.py in _validate_table(table, sed_type)
    468             missing = required.difference(table.colnames)
    469             raise ValueError(
--> 470                 "Missing columns for sed type '{}':" " {}".format(sed_type, missing)
    471             )
    472 ValueError: Missing columns for sed type 'likelihood': {'norm_scan', 'stat_scan'}
```

We probably shouldn’t force this :
`table = table_from_row_data(rows=rows, meta={"SED_TYPE": "likelihood"})`, as SED_TYPE  set to likelihood  is not correct here

**Comment by adonath** [comment]
There problem here is that the choice `steps=["ts", "err"]` does not correspond to a valid sed type and cannot (strictly) be represented by a `FluxPoints` object. I think we should check the steps according to the required and optional quantities. See https://github.com/gammapy/gammapy/blob/master/gammapy/estimators/flux_point.py#L19

**Comment by registerrier** [comment]
Yes there is an inconsistency between the different formats. `dnde` expects a `dnde` column whereas the `likelihood` requires a `ref_dnde` and a `norm`.

If we stick to those formats, the table must be reformatted before being converted to a `FluxPoints` object. 
Probably the issue here is more that `FluxPoints` is built according to the various specs, i.e. the `FluxPoints` is the `Table` passed on `__init__` where in reality the conversion to a standard internal format should be made on `__init__`/ `read` etc.

**Comment by adonath** [comment]
I think this issue should be resolved after introducing the `selection_optional` keyword. The idea is now, that we always compute a valid minimal selection of quantities. The  "norm_scan" and "stat_scan" columns are now optional for the "likelihood" SED type as well...
