### ISSUE TITLE
Issue with model setting for joint dataset

### ISSUE THREAD

**Issue by luca-giunti** [gammapy/gammapy#2880]
**Gammapy version**
0.17

**Bug description**
As explained in the [3D analysis tutorial](https://docs.gammapy.org/0.17/notebooks/analysis_3d.html) (see cell [23]), I assign a model to each `MapDataset` inside a joint `Datasets` using:
```
for dataset in datasets:
    dataset.models.append(model_joint)
```
This works fine However, if I store the `Datasets` and later reload to add another model component, it fails with 
```
ValueError: Model names must be unique
```
Here is a working example: https://github.com/luca-giunti/share/blob/master/Bug_report.ipynb

**Comment by QRemy** [comment]
Thanks for pointing this. On read the serialization create a global model that is shared by all datasets, so I guess you dont' have to do the loop.
