### ISSUE TITLE
Transition to EDispKernelMap in MapDataset

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#2887]
In order to handle correctly `safe_mask` stacking for `MapDataset`, we need to use the newly introduced `EDispKernelMap`. It allows to take into account the effective fraction of the reco energy bins to be taken into account across the image (e.g. one data set has a safe threshold at 100 GeV, the other at 200 GeV, and they partly overlap). 

The creation mechanism relies the current `EDispMap.to_edisp_kernel_map(reco_energy_axis)`. The natural solution could therefore be to add this call in the `MapDatasetMaker.make_edisp` in which case it would return the correct `EDispKernelMap` and all `MapDataset` would contain this type of object rather than an `EDispMap`. This implies that `MapDataset.create()` does not take the `migra_axis` as an argument (or at least it should not really need it).

This is simple, but has two drawbacks:
- this is backward incompatible.
- this breaks the event sampling logic which needs a real `EDispMap` to be stored on the `MapDataset`. 
I assume the latter issue is in fact due to the fact that the `MapDataset` is not really the right dataset for event sampling, but that an `EventDataset` would be the right thing to use (i.e. a dataset consisting in an `EventList`, a `PSFMap`, an `EDispMap` (and their exposure map) and a `BackgroundModel`.

Whatever the direction we will take for unbinned datasets, we need to find a solution for now. We have to have the option of having either an `EDispMap` or an `EDispKernelMap` on a `MapDataset`. We might handle this by specifying in `MapDataset.create()` which one to create.  Then the `MapDatasetMaker` would compute the correct one.   
We would still needs numerous tests in `MapDataset.stack()`, `MapDataset.to_image()`, `MapDataset.to_spectrum_dataset()` etc, to handle one or the other. This has likely other implications for the HLI.

Any opinion @adonath , @fabiopintore, @Bultako, @QRemy, @AtreyeeS ?

**Comment by AtreyeeS** [comment]
At present, `MapDataset.edisp` can be either an `EDispMap` or an `EDispKernel`. (I believe we support the `EDispKernel` for Fermi analysis?) 

Adding `EDispKernelMap` to this might make it quite confusing. From what I understand, users will probably never need to make an `EDispMap` during normal data-reduction? 
So the need for having `EDispMap` is only for unbinned simulations, which returns an `EventList`. 
Having a separate dataset for this makes sense to me.

Is it possible now to have `EDispKernel` as an `EDispKernelMap` with only one bin? That might simplify things a lot

**Comment by fabiopintore** [comment]
From what I understand, the `EdispKernelMap` will be used in the vast majority of the user cases but for the event-sampler. Although this may be a bit confusing for the users, for now we might want to keep both options in `MapDataset.create()`. We might add a switch-on or -off argument, which may set by default to `OFF`. If the argument is `OFF` and no `migra_axis` is given, an `EdispKernelMap` object is obtained. If instead the argument is set to `ON`, a migra-axis has to be provided by the user (otherwise the code gives an error). Generally, the latter will be used only for event-sampler.
About the possibility of an `EventDataset`, I don't have a strong idea and I'm not sure if this option can be adopted soon.

**Comment by registerrier** [comment]
> Is it possible now to have EDispKernel as an EDispKernelMap with only one bin? That might simplify things a lot

Yes, it should be possible to have an `IRFMap` with a `RegionGeom` object. It probably need some improvement on the `RegionGeom` to do so. In the end, we won't need the `EDispKernel`.

> Although this may be a bit confusing for the users, for now we might want to keep both options in MapDataset.create(). We might add a switch-on or -off argument, which may set by default to OFF.

Yes, indeed. The most natural solution could be to create a `MapDataset` with full `EDispMap` if the migra_axis is set on `MapDataset.create`. 
In this case,  `MapDatasetMaker.make_edisp` must be adapted to not produce the regular `EDispMap` if the target `MapDataset` does not contain it.

**Comment by registerrier** [comment]
OK. I have followed the discussion and implemented the above solution in PR #2897 

Please comment there.
