### ISSUE TITLE
Add MapDataset.info_dict()

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#2899]
`Datasets.info_table()` fails for `MapDataset` this point because unlike in `SpectrumDataset`, there is no `info_dict()` defined for a MapDataset.

I can add one, but what are the parameters to provide info of? `counts` `npred` `background` `exposure_min` `exposure_max` is what is provided during a `print(MapDataset)`. Anything else @registerrier @luca-giunti ?

**Comment by registerrier** [comment]
Thanks @AtreyeeS .  This issue is already mentioned in #2749 . 

I move the discussion there and close the issue for now.
