### ISSUE TITLE
Improper link to MapDatasetEventSampler in the documentation

### ISSUE THREAD

**Issue by fabiopintore** [gammapy/gammapy#2911]
**Gammapy version**
v0.17 

**Bug description**
The documentation of the `MapDatasetEventSampler` class is incorrectly linked.

**Expected behavior**
The documentation for the `MapDatasetEventSampler` class should be present in the documentation.

**To Reproduce**
https://docs.gammapy.org/0.17/notebooks/event_sampling.html links the `MapDatasetEventSampler` to the `Datasets` page.

**Comment by adonath** [comment]
As the links are created automatically, this might be an issue for @Bultako to investigate...
