### ISSUE TITLE
Add helpers for using 2D maps in gammapy

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#2913]
I recently had some exchange with Emma, who wanted to use HESS images (data reduction not done using gammapy), and do a fitting within gammapy.

In this case, it is required to add an `energy` axis on the counts and background maps, and an `energy_true` axis on the exposure. Converting the psf is a bit tricker, the `energy_true` axis should be added on  `PSFKernel.psf_kernel_map`  and then a new `PSFKernel` created.

Perhaps it is difficult to provide helper functions to do this properly for all cases, but maybe we can add some info about this in the documentation for future users?

**Comment by adonath** [comment]
Indeed this is a use case, that came up many times already. Here are a few ideas from my side:

- We already have `Geom.to_cube()`, we could also introduce `Map.to_cube(axes=[])`, which attaches additional axes to a given 2D map. The same could be done by adding `PSFKernel.to_cube()`
- What could be useful as well and is more general is something like `Map.from_images(images=[], axis=energy_axis)`. This would create a map from a list of 2D images and attach the extra axis.

**Comment by adonath** [comment]
And documentation is a good idea anyway...

**Comment by emmaow** [comment]
Hi! thanks @AtreyeeS AtreyeeS for the help. I can provide the notebook whenever im done, if you like. I am using dataset=MapDatasetOnOff as Atreyee suggested. I am still trying to understand how to implemented (do I need to provide exposure on off? models?). Once I understand this it should be done. I can make the example using some public data

**Comment by registerrier** [comment]
I am about to add a notebook to the HESS bitbucket repo for this specific use case. 

We should also add a specific set of examples, probably within the `Dataset` rst page

**Comment by AtreyeeS** [comment]
> * What could be useful as well and is more general is something like `Map.from_images(images=[], axis=energy_axis)`. This would create a map from a list of 2D images and attach the extra axis.

Hi @adonath : How about a `MapDataset.from_images()`? Then it can automatically attach the extra axis as `energy` or `energy_true`...

**Comment by adonath** [comment]
We now also have `Map.from_images()` (see https://github.com/gammapy/gammapy/blob/master/gammapy/maps/core.py#L1105). So I guess the remaining work is to add documentation?

**Comment by adonath** [comment]
Implementing a `MapDataset.from_images()` could be still useful...

**Comment by adonath** [comment]
Will be resolved with HESS internal documentation.
