### ISSUE TITLE
Add option on ExcessMapEstimator not to correlate OFF data

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#2915]
By default OFF data is correlated with the ON data in the `ExcessMapEstimator`. This allows a standard behavior for real OFF observation and ring-like OFF datasets. 

Yet, as @lmohrmann noted, a number of classical analysis do not correlate OFF deduced from ring background. It might therefore be worth to keep the option available not to convolve the OFF map for a `MapDatasetOnOff`.

**Comment by adonath** [comment]
Hm, I would presume there is only one correct way of doing this?
