### ISSUE TITLE
Fit converges with success=True when parameters are stuck at the borders

### ISSUE THREAD

**Issue by luca-giunti** [gammapy/gammapy#2917]
**Gammapy version**
v0.17

**Bug description**
3D fitting with MINUIT appears to be succesfull (`success=True`) even if the optimizer got stuck at the boundaries of the allowed range for some fitted parameter.

**Expected behavior**
The fit should not report `success=True` if one or more parameters have assumed the max/min value of their allowed range, or at least some error message should be printed.

**To Reproduce**
See this working [example](https://github.com/luca-giunti/share/blob/master/analysis_1.ipynb).
It is a simple adaptation of the `analysis_1.ipynb` notebook. The relevant cells are:
- [19] here, I changed the first-guess value of `lon_0`: instead of starting from nearby the crab position (`lon_0=83.633`), I start from an offset position (`lon_0=83.4`), so that the model will try to shift to `lon_0=83.633`. But I also impose a max value of `83.5` for `lon_0`, so that I know that the optimizer will get stuck at `lon_0=83.5`. To understand why MINUIT gets stuck there, check section 5.3.1 in the [MINUIT manual](https://root.cern.ch/download/minuit.pdf)
- [22] MINUIT wrongly tells us that `success=True`
- [24] I check that indeed the model got stuck at `lon_0=83.5`. Also, we can notice that the error on `lon_0` has a crazy value: `1.643e-07` (which is how I found out this issue in the first place)

**Other information**
This behavior is completely expected in MINUIT fitting, so it's not really a gammapy problem in this sense. However, what should be done by gammapy is printing some error if a fit converges with parameters at the boundaries (and maybe in that case force `success=False`).

**Comment by AtreyeeS** [comment]
Is this something that we want gammapy to do or it is the users responsibility to check that nothing hits the borders?

**Comment by luca-giunti** [comment]
In my experience, it is way too easy to overlook this kind of issue. I really think we should raise a warning. Imagine someone has a large number of models stored in `MapDataset.models`: he should check one by one that there aren't parameters at the edge?

**Comment by adonath** [comment]
I'm not sure this is something we can handle consistently in the Gammapy side, because different optimisers handle this differently. I think for iminuit there are no "hard limits", it uses some internal parameter scaling based on  `arctan` or similar, while sherpa has e.g. "hard" and "soft" limits. However we could maybe check if there is additional status output from the optimisers we could use to determine whether a fit failed for not. It's hard to judge anyway by a single criterion and we should always encourage users to compute likelihood profiles instead...

**Comment by adonath** [comment]
We could maybe emit a warning, if model parameter are set outside a limit? I think by now you could do:

```
a = Parameter("amplitude", value=1e-12, min=0)
a.value = -42
```
Without being notified...

**Comment by luca-giunti** [comment]
@adonath Sure, that's also a place where a warning would be very welcome. But the issue I have described here is somewhat different.. 

Maybe the example on the Crab was a bit trivial, and gave the impression that users just have to pay minimal attention at how they set the min/max values. In a more complex case I have been fighting with this issue many times, and also led me to completely false results: one time it looked like MINUIT successfully converged after the introduction of an additional model component, but much later on (after announcing and discussing the thing as a true scientific result) I realized that actually that component simply got stuck at the minimum `lon_0` allowed value. After removing (or relaxing) the constrain on `lon_0`, the result was completely different (actually, the additional source was not even significant anymore).

This should raise a warning, or at least be very well documented in the docs as a known issue of the MINUIT backend.

**Comment by adonath** [comment]
@luca-giunti As we do an "in place" update of the model parameters, this warning will also be emitted during a fit. The condition for the warning could also include the limit itself like `value >= max` or `value <= min`. Do you think this is sufficient or would you propose something else again?

**Comment by luca-giunti** [comment]
Thanks @adonath , now I see the link between your previous comment and the present issue. It is a good idea! So if I understand correctly, once your solution is implemented a warning will be automatically raised anytime MINUIT explores an edge of the allowed parameter space, right? This indeed can solve the issue, because then the user will know that something might be going wrong. And at the same time, this would discourage users by setting parameters values outside the min/max range, which makes it an elegant solution.

I could take care of that, during the upcoming virtual gammapy meeting.

**Comment by luca-giunti** [comment]
@adonath Related iminuit [issue](https://github.com/scikit-hep/iminuit/issues/449) has tackled in in a [PR](https://github.com/scikit-hep/iminuit/pull/469). In future releases we should update iminuit version..
