### ISSUE TITLE
Minor bug in Datasets.info_table()

### ISSUE THREAD

**Issue by luca-giunti** [gammapy/gammapy#2920]
**Gammapy version**
v0.17

**Bug description**
In the output of [Datasets.info_table(cumulative=bool)](https://docs.gammapy.org/0.17/_modules/gammapy/datasets/core.html#Datasets.info_table) the first row is named 'stacked' even when the method is called with `cumulative=False`.

**Expected behavior**
When `Datasets.info_table(cumulative=False)]` is called, each row should correspond to a separate dataset and its name should correspond to the obs id

**Comment by adonath** [comment]
@luca-giunti I see what you mean. In my opinion even for the cumulative case it could make sense to just use the dataset name and not generate a new one?

**Comment by luca-giunti** [comment]
Maybe, it's a matter of personal taste I guess :) OK so thanks for checking on this, I will close the issue
