### ISSUE TITLE
Fit mask overridden in FoVBackgroundMaker and FluxPointsEstimator

### ISSUE THREAD

**Issue by luca-giunti** [gammapy/gammapy#2921]
**Gammapy version**
dev

**Bug description**
See:
- https://github.com/gammapy/gammapy/blob/9df7a783fc050cf79667deb94d0cc635a2aa5bfb/gammapy/makers/background/fov.py#L49
- https://github.com/gammapy/gammapy/blob/9df7a783fc050cf79667deb94d0cc635a2aa5bfb/gammapy/estimators/flux_point.py#L906

The `dataset.mask_fit` if overridden during the computation of flux points or the field of view background normalization. This is bad, because users might want e.g. to:
- normalize the background in a custom energy range
- compute flux points by masking away some map regions

In those cases, they would set a `dataset.mask_fit` that is silently overridden in the current code. Notice that, for the case of background normalization in a custom energy range, this issue can be overcome by adapting the exclusion mask, instead of touching the `dataset.mask_fit`. But still, it is legitimate to want to do it with the `dataset.mask_fit` so it shouldn't be overridden.

**Other information**
I didn't check if this issue is also present somewhere else in the gammapy code, it might be worth having a look

**Comment by adonath** [comment]
In #2991 the flux points estimation was refactored to use slicing instead of the masks. So this issue should not be present anymore for flux point estimation.

Remaining action item: adapt `FoVBackgroundMaker` to take into account the `mask_fit` information....

**Comment by adonath** [comment]
The main question for me here is: what is the relation between the `exclusion_mask` parameter and the `mask_fit`.

**Comment by adonath** [comment]
@luca-giunti I think the conclusion from the last dev call here was, to handle everything with the `exclusion_mask`. Is this correct?

**Comment by adonath** [comment]
Then the issue is resolved....

**Comment by luca-giunti** [comment]
> @luca-giunti I think the conclusion from the last dev call here was, to handle everything with the `exclusion_mask`. Is this correct?

@adonath @registerrier I don't remember exactly the reasons behind this conclusion, but in any case shouldn't it be better documented? I think it is not an obvious feature. A sentence like `Caveat: This Maker overrides internally the Dataset mask_fit. This means that all spatial and spectral exclusion ranges have to be encoded in the exclusion_mask.` would help

**Comment by adonath** [comment]
@luca-giunti I can't remember the reasoning either. But looking at this again I think overriding the `mask_fit` internally is maybe not the best solution. Probably it would make more sense to to keep the `mask_fit` and combine it internally with the `exclusion_mask`.

**Comment by adonath** [comment]
Solved by #3841.
