### ISSUE TITLE
pip package misses dependencies

### ISSUE THREAD

**Issue by mexanick** [gammapy/gammapy#2954]
**Gammapy version**
0.17

Are you using the latest stable version of Gammapy? (see https://gammapy.org/news.html)
If no, can you upgrade and try with the latest stable version, please?

stable (from Pypi)

**Bug description**
The PyPi-distributed package misses the following dependencies:
- Cython
- numpy

This makes impossible automated installation of other tools which depend on `gammapy`

**Expected behavior**
`python -m pip install gammapy` in a fresh clean environment should happen without the issues related to missing/broken dependencies
**To Reproduce**
run `python -m pip install gammapy` in a fresh clean environment

**Other information**
Any other information you think will be useful for us to fix the issue can go here.

**Comment by adonath** [comment]
Thanks @mexanick, this issue has been resolved by #2896 already. The fix will be delivered with the next version of Gammapy.
