### ISSUE TITLE
Add more info / check plots for events / IRFs

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#297]
Nathan from VERITAS has implemented very nice informative debug plots for their events / IRFs:
![image](https://cloud.githubusercontent.com/assets/852409/8551182/551aec2c-24d5-11e5-8810-938468634cd7.png)

I'd like to have those for Gammapy / HESS.

**Comment by cdeil** [comment]
Some of these plots have been implemented in #352.
Keeping this open because this needs more works and tests / docs.

**Comment by cdeil** [comment]
Moving milestone to 0.7 (I'll make the 0.6 release tomorrow)

**Comment by adonath** [comment]
I think by now this in good shape, see e.g. https://docs.gammapy.org/0.18.2/tutorials/cta.html.
