### ISSUE TITLE
Improve travis-ci setup / build matrix

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#300]
The following aspects of the Gammapy travis-ci setup and build matrix should be improved:

- [x] Migrate to the container-based infrastructure? (see http://docs.travis-ci.com/user/migrating-from-legacy/)
- [x] Add a Sphinx build with Python 3 (see https://github.com/gammapy/gammapy/pull/299#issuecomment-121530634)
- [x] Add a Sphinx build with the latest Astropy master (see https://github.com/gammapy/gammapy/pull/299#issuecomment-121530634)
- [x] Add Mac OS X builds (see Astropy or other affiliated packages for examples
- [ ] Test installing via the gammapy-conda-install.sh script.

For reference, see the current [.travis.yml](https://github.com/gammapy/gammapy/blob/master/.travis.yml) and the latest [build matrix](https://travis-ci.org/gammapy/gammapy)

**Comment by cdeil** [comment]
Migrate to the container-based infrastructure in #340

**Comment by mapazarr** [comment]
May I suggest the following?

1. Test with `--remote-data` option.
2. Add all Fermi datasets to `gammapy-extra` and use them as fall back option in case the tests fail because of Fermi server timeout.

**Comment by cdeil** [comment]
@mapazarr Agreed. But what you suggest will be part of a bigger change to the Gammapy repo / datasets setup (see #288) and I don't have time for that at the moment.

**Comment by cdeil** [comment]
I'm closing this issue and will make a new one for the remaining task
"Test installing via the gammapy-conda-install.sh script."
