### ISSUE TITLE
Model kernel_radius overwrote in TSMapEstimator

### ISSUE THREAD

**Issue by emmaow** [gammapy/gammapy#3004]
**Gammapy version**
0.17
**Bug description**
When producing TSMaps using a model with a Gaussian kernel of x deg, the init value of TSMapEstimator always uses a fixed value (point?). To solve this one has to init the kernel_width directly on the call TSMapEstimator(model,kernel_radius=x*u.deg)

**To Reproduce**
spatial_model = GaussianSpatialModel(sigma="0.5 deg")
spectral_model = PowerLawSpectralModel(index=2)
model = SkyModel(spatial_model=spatial_model, spectral_model=spectral_model)
ts_image_estimator = TSMapEstimator(model)
images_ts = ts_image_estimator.run(dataset_image)

=> images_ts with a 0.1 deg.

ts_image_estimator = TSMapEstimator(model,kernel_width=0.5*u.deg)

=> images_ts with a 0.5 deg

**Other information** 

https://docs.gammapy.org/0.17/notebooks/cta_data_analysis.html?highlight=tsmapestimator%20gaussian%20model

**Comment by adonath** [comment]
Thanks @emmaow, I think we have to clarify what the `kernel_width` parameters does and probably define a better default behaviour.  The `kernel_width` parameter is independent of the actual spatial shape, but just defines the size of map that is used to create the kernel. It's a useful parameter for TS map estimation, as the runtime will scale with `kernel_width ** 2`.

But I agree there is a large potential for mis-use, e.g. the example that you provided, when a `0.5 deg` Gaussian is only evaluated in a `0.2 deg` window. The minimal thing we could do is raise a warning.

**Comment by registerrier** [comment]
I think that an adaptive kernel size taking into account the PSF and the source model would provide a solid implementation for the `TSMapEstimator`.  It should be possible to find a clean solution for this problem as it is also present in other parts of the code. For instance for the choice of the psf kernel dimension.

**Comment by adonath** [comment]
@registerrier Yes, we already have this code in `MapEvaluator.update()`, probably we should move it somewhere else, so that we can re-use it. On the other hand we already use the `MapEvaluator` in `TSMapEstimator.estimate_kernel()`, so maybe we just have to refactor it partly...

**Comment by adonath** [comment]
I think here we should provide a safe default behaviour by inferring the kernel size automatically by default, however we should keep the `kernel_size` parameter to allow users to overwrite it.

**Comment by registerrier** [comment]
A solution for this problem is to set the `kernel_size` default to `None` and internally rely on the `MapEvaluator.cutout_width` which takes into account the spatial model `evaluation_radius`.
If the `kernel_size` is set, a warning is emitted if `kernel_size` is found to be smaller than the `cutout_width`.

Does this sound OK @adonath ?

For more efficiency, at some point, we should introduce a mechanism into `MapEvaluator` to find a better size for the PSF kernel than the IRF `rad_max`, e.g. by setting it to a given containment radius value.

**Comment by adonath** [comment]
Sounds good to me @registerrier!

**Comment by adonath** [comment]
Fixed in #3366.
