### ISSUE TITLE
Spectrum simulation notebook - offset never used -  inconsistency

### ISSUE THREAD

**Issue by tstolarczyk** [gammapy/gammapy#3010]
Hello,

Gammapy 0.17

The 'spectrum simulation' commented notebook https://docs.gammapy.org/0.17/notebooks/spectrum_simulation.html
introduce the analysis with:
"we need to define the observational parameters like the livetime, the **offset**, ...."

In block [3]:
```offset = 0.5 * u.deg```

but this variable ie never used!
And the pointing is at 0,0
```
pointing = SkyCoord(0, 0, unit="deg", frame="galactic")
offset = 0.5 * u.deg
on_region_radius = Angle("0.11 deg")
on_region = CircleSkyRegion(center=pointing, radius=on_region_radius)
```
Thanks!

**Comment by adonath** [comment]
Thanks @tstolarczyk, I can confirm that offset is never used. I guess one should just the shift the center off the on region by the proposed offset with respect to the pointing position. Would you be interested in preparing a PR to fix this yourself?

**Comment by tstolarczyk** [comment]
Well, yes I can do it, but not immediately (I want to finish the implementation of 0.17 in my code)
In that spirit, I have other comments on this notebook.

*** Can you tell me more on this for instance:

In block 7, on have:
- the background is (already) computed, 
 - Total counts                    : nan 
 - Total predicted counts          : nan

In block 8, adding the signal model and before faking
- Background unchanged, 
- Total counts                    : nan 
- Total predicted counts          : computed

Then after the fake, 
- 'background is unchanged', '
- predicted counts is unchanged,' 
- and 'total counts' is estimated.

I think the statement:
" You can see that background counts are now simulated" is a mistake.
The statement should be, if I am not lost: * the total count number is simulated/fluctuated *
and not only the background!
Or, indeed only the background only is fluctuated, would be strange, but this cannot be seen on the output.

*** I  wanted to check if only B has fluctuated and I realised that the available methods do not give access to all information as the one shown in info_dict.  Why not methods, including safe_energy_range as an argument, for all information ? (only npred and npred_sig are available)

*** On top of this, I think that when going to the last on-off part, there should be a word of explanation and/or a link on why to use SpectrumDataSetOnOff when SpectrumDataSet already gives everything -in principle- to do an aperture photometry on-off analysis.   

*** I realise that this issue is diverging a bit, my fault, and maybe that would be better to post this on slack. Please tell me what you think, also on that subject.

**Comment by adonath** [comment]
The not used offset has been fixed in the meantime: https://docs.gammapy.org/dev/tutorials/spectrum_simulation.html#Simulation-of-a-single-spectrum
