### ISSUE TITLE
Clarify Dataset.plot_residuals()

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#3013]
It is a bit confusing what `Dataset.plot_residuals()` does at present.
eg, in `SpectrumDataset.plot_residuals()`, https://github.com/gammapy/gammapy/blob/f038efe436875d8f421d2132ac0b280c5468be8a/gammapy/datasets/spectrum.py#L448-L451

the error bars seem arbitrary.
The `npred()` is not an independent Poissonian measurement, so I am not sure if adding the variances are reasonable. A constant error of `1` is also confusing.

We should discuss a bit and clarify in the doc string what exactly is plotted.

**Comment by adonath** [comment]
What ever we do here, we should definitely make it consistent with `SpectrumDataset.plot_residuals()`

**Comment by adonath** [comment]
@AtreyeeS Any specific proposal what to do here? Maybe not show any errors at all?

**Comment by AtreyeeS** [comment]
My proposal is to use the `CashCountStatistics` for `method=diff` and not show any error bars otherwise.
Tried it here: https://github.com/AtreyeeS/test_notebooks/blob/master/spectrum_simulation.ipynb

Can implement it after the dev call this Friday

**Comment by registerrier** [comment]
I suppose that error bars are smaller using `CountsStatistics` because they take into account only the errors on the data. 
I am not very enthusiastic about plots without errors bars in general.

**Comment by AtreyeeS** [comment]
Implemented in #3208
