### ISSUE TITLE
psf.containment_radius is Nan when containment is 100%

### ISSUE THREAD

**Issue by tstolarczyk** [gammapy/gammapy#3015]
Hello!

Gammpay 0.17

Discovered when using the notebook
https://docs.gammapy.org/0.17/notebooks/cta_sensitivity.html

If ```containment = 1``` in 
```on_radii = obs.psf.containment_radius(
    energy=e_reco.center, theta=0.5 * u.deg, fraction=containment
)[0]
```

returns Nan, leading to problems later.
The doc says the range is up to one, which is mathematically expected :-) but not True here.
According to me : 
A value should be returned (```Inf``` ?), and/or an action should be taken and/or the doc should be corrected and more explicit

Thanks

**Comment by adonath** [comment]
Thanks @tstolarczyk fixed in https://github.com/gammapy/gammapy/commit/6417156acab8f22f2c5aef4769ed0ac94ccc5c3c
