### ISSUE TITLE
SpecrumDataSet : When updating eff. area, the signal count number is not updated

### ISSUE THREAD

**Issue by tstolarczyk** [gammapy/gammapy#3016]
Hello,

gammapy 0.17

I am using the example notebook "Spectrum simulation" (first notebook):
https://docs.gammapy.org/0.17/notebooks/spectrum_simulation.html
I want to evaluate the signal and the background in a 68% containment region, as explained in the second notebook:
https://docs.gammapy.org/0.17/notebooks/cta_sensitivity.html

I create a ```SpectrumDataset```, add a model to the dataset as shown in cell 7 and 8 of the first notebook.
I get background and predicted counts. The signal can be obtained from the difference.

Then I want to compute the same with a given containment (see notebook 2, cell 6):
```
containment = 0.68
dataset.aeff.data.data *= containment
on_radii = obs.psf.containment_radius(
    energy=e_reco.center, theta=0.5 * u.deg, fraction=containment
)[0]
factor = (1 - np.cos(on_radii)) / (1 - np.cos(region.radius))
dataset.background.data *= factor.value.reshape((-1, 1, 1))
``` 
When done:
- the background B count of the dataset is updated
- the predicted count is changed but the difference with B shows that the signal is unchanged.

This is highly disappointing :-)

The problem comes from  ```npred_sig(self)```in the ```SpectrumDataset``` class:

```
if evaluator is None :
                    evaluator = MapEvaluator(
                        model=model,
                        exposure=self.exposure,
                        edisp=self.edisp,
                        gti=self.gti,
                    )
```
The signal is defined once for ever...
Thanks

**Comment by adonath** [comment]
Thanks @tstolarczyk! I cannot confirm this issue: I think the aeff is updated correctly. In the tutorials you have linked there is no source model defined, so the number of predicted counts is not expected to change...

**Comment by tstolarczyk** [comment]
@adonath, please read carefully my issue message : the problem is discovered in the "Spectrum simulation" notebook when I try to modify the effective area as explained in the other notebook. I suggest you try by yourself. 
It is obvious it is due to the intrinsic caching in npred_sig() as I described above.
Thanks

**Comment by adonath** [comment]
Thanks for clarifying @tstolarczyk, I now see what you mean an can confirm the issue.

However I doubt we will implement a general solution to this, because e.g. in the `MapDataset` the caching is crucial to the performance (one could fix it for the `SpectrumDataset`, but then we get inconsistent behaviour...) and tracking changes of all data members is technically very difficult as well. So I guess the solution here is to better document the behaviour. In your case the modification of the `aeff` should be just done prior to setting the model, or you have reset the model in between like `dataset.models = None`. Technically you can also do `dataset._evaluators ={}` to reset the cache. I'll think about it once more maybe we can add a little API to reset the cache...

**Comment by tstolarczyk** [comment]
Thanks @adonath, I indeed made what you say, it came obvious after some time.
What is strongly misleading is that only the spectrum evaluation is "cached", not the rest.

Documenting this feature would be insufficient for normal users.

One could use a aeff_update method or better a **setter** for the effective area (suggestion by Karl) that would call MapEvaluator.
This would fulfil your request for speed and make the process transparent to the user.

**Comment by adonath** [comment]
Yes, indeed a setter could be a reasonable compromise

**Comment by adonath** [comment]
In #3042 I'm refactoring the `SpectrumDataset` and `SpectrumDatasetOnOff` to use `exposure` as well. This unifies the the data model with `MapDataset` and should resolve the specific issue here as well.
