### ISSUE TITLE
MapDataset.to_spectrum_dataset does not take mask_safe into account

### ISSUE THREAD

**Issue by lmohrmann** [gammapy/gammapy#3018]
**Gammapy version**
0.17

**Bug description**
When converting a `MapDataset` to a `SpectrumDataset` via `to_spectrum_dataset`, the `mask_safe` is not taken into account. This leads to unexpected behavior if parts of the `on_region` are excluded by the `mask_safe`.

**Expected behavior**
I would expect that at least the spatial part of the `mask_safe` is taken into account when converting to a `SpectrumDataset`.

**To Reproduce**
Create a `MapDataset`, exclude parts of the map via the `mask_safe` attribute, and create a `SpectrumDataset` using an `on_region` that overlaps with the excluded region. Counts in the excluded region will still be added to the `SpectrumDataset`.

**Comment by adonath** [comment]
Thanks @lmohrmann, I'll close the issue as duplicate of #2953. Let's continue discussion there...

**Comment by lmohrmann** [comment]
Apologies, I wasn't aware of that issue. Thanks!
