### ISSUE TITLE
Unify mask handling in Dataset methods and Estimators

### ISSUE THREAD

**Issue by adonath** [gammapy/gammapy#3031]
We have to unify the handling of `mask_safe` and `mask_fit` in the dataset methods and `Estimator` classes. Here is the current behaviour:

Dataset methods:
- `MapDataset.stack()`, `SpectrumDataset.stack()`: takes into account `mask_safe`
- `MapDataset.to_image()`: takes into account `mask_safe`
- `MapDataset.to_spectrum_dataset()`: no mask handling
- `MapDataset.resample_energy_axis()`: takes into account `mask_safe`

Estimator classes:
- `Fit`: takes into account `mask_safe` as well as `mask_fit`
- `FluxPointsEstimator`: takes into account `mask_safe` as well as `mask_fit`
- `LightCurveEstimator`: takes into account `mask_safe` as well as `mask_fit`
- `TSMapEstimator`: no mask handling
- `ExcessMapEstimator`: takes `mask_safe` into account, optionally the `mask_fit` as well
- `ExcessProfileEstimator`: no mask handling (related to `.to_spectrum_dataset()`)

Maker classes:
- `FoVBackgroundMaker`: just uses the `exclusion_mask` parameter, see #2921.

My current proposal goes into the direction of just applying `mask_fit` and `mask_safe` everywhere, except maybe for `MapDataset.stack()`, but I'll think about once more. Please add your thoughts @registerrier , @AtreyeeS, @luca-giunti .

Related issues:
- #2953 
- #2865 
- #2701 
- #2921

**Comment by AtreyeeS** [comment]
Thanks @adonath for the summary.

I think we might consider keeping the behaviour different for `datasets` and `estimators` 
- `datasets` - apply only the `mask_safe` (always)
- `estimators` - apply the `mask_safe` for sure, and (optionally?) the `mask_fit`

At the `datasets` stage, it is not preferable to mask off good data. I tend to see `mask_fit` as a "loose" mask which does nothing to my dataset, but allows me the flexibility to consider only a part for high level analysis.

For the `FoVBackgroundMaker`, I suppose the behaviour is reasonable - the safe mask is created at the maker stage, and no fit mask is defined yet.

**Comment by registerrier** [comment]
I agree that on `Datasets`, the `mask_safe` should always be applied. 
The case of `to_spectrum_dataset` could require some exclusion regions, e.g. to exclude a pointlike source inside a large ON region. I assume this can be handled well with compound regions.
`Estimators` need the `mask_fit` in general. Are there clear cases where we would want not to use it? It can always be reset by the user I suppose.
For the `FovBackgroundMaker`, the `exclusion_mask` is exactly a `mask_fit` so it does not need to be included I assume.

**Comment by adonath** [comment]
Thanks @registerrier  and @AtreyeeS  for the comments already. So the proposed logic would be:
- In Dataset methods always apply `mask_safe`
- In Estimators always apply `mask_safe` and `mask_fit`, if users don't want to apply the `mask_fit`, they can set it to `None` beforehand

All in all this sounds good to me, the name of the `mask_fit` already suggests it's only used when fitting is involved, which is exactly what happens inside the `Estimator` classes.

**Comment by luca-giunti** [comment]
Sounds good! Just a thought, maybe the default should be that `Datasets` methods don't use the `mask_fit`, but why don't we allow the flexibility of passing it as an optional argument (e.g. `MapDataset.to_image(mask_fit=None)`). Otherwise, to achieve the same result one would have to modify the `mask_safe` or masking things by hand which is painful...

**Comment by adonath** [comment]
@luca-giunti Passing the mask form the "outside" doesn't really make sense to me, as the `mask_fit` is already attached to the `MapDataset`. Then I would rather prefer to always apply the `mask_fit` as well. The default behaviour is that `mask_fit` is `None` anyway, but the it could be at least optionally defined.

**Comment by luca-giunti** [comment]
Sorry I meant `mask_fit=False`, not `None`. I don't know, it's just that I already found myself in both situations of computing a `MapDataset` operation with and without the mask fit applied, so I would like to keep it flexible... but of course, we could always apply the`mask_fit` and then the user has just to set it to `None` beforehand, as for the `Estimator` classes. Then it has to be well documented

**Comment by adonath** [comment]
I'd be open to handle the `mask_fit` as well in dataset methods, it would unify the behaviour 100% and offers a bit more flexibility as @luca-giunti suggested...

**Comment by adonath** [comment]
In the dev call today we agreed on the following:
- In `Dataset` operations only takes into account the `mask_safe`
- In addition we implement a `MapDataset.apply_mask(mask=)`, method we applies a given mask in place
- In addition we move the code from `Datasets.slice_energy()` to the `MapDataset` and `SpectrumDataset` level

**Comment by adonath** [comment]
Does anybody have time to work on what of the things I listed in my comment above?

**Comment by registerrier** [comment]
I will start to adapt the `to_spectrum_dataset` to take into account `mask_safe`.

**Comment by adonath** [comment]
Thanks @registerrier , maybe what for #3042 to be merged. I can implement the `.apply_mask()` then...

**Comment by adonath** [comment]
I think we still have to implement the mask handling for the `TSMapEstimator`...

**Comment by adonath** [comment]
Just for completeness instead of the in place `apply_masked()` I added a method `.to_masked()`...

**Comment by adonath** [comment]
From a quick check this looks all good now in Gammapy, except for one oddity: the `ExcessMapEstimator` exposes an option `apply_mask_fit`, which allows to control the behavior. None of the other estimators does this and one could easily achieve the same behavior using:
```
dataset.mask_fit = None
```
My recommendation would be to remove the `apply_mask_fit` option.
