### ISSUE TITLE
Providing additional output and progress bars in a consistent way

### ISSUE THREAD

**Issue by luca-giunti** [gammapy/gammapy#3040]
This is a reminder issue (related to #3038 ).

We should define a list of places where additional output (in particular the full fit results from `Fit.run()`) and/or a nice `tqdm` progress bars are useful, and add them in a consistent way. 

Obvious places that come to my mind are: estimators, `Fit.stat_profile()`, `Fit.stat_surface()`. I'm sure there will be others, any idea?

**Comment by registerrier** [comment]
I think `Estimators` would need it: `FluxPointsEtimator`, `LightCurveEstimator`, `TSMapEstimator` at least.

**Comment by registerrier** [comment]
Also the general loop over `Observations` in the `Analysis` class would benefit from it.

**Comment by adonath** [comment]
@luca-giunti Close this issue? Implemented in #3343...
