### ISSUE TITLE
Application of mask_safe in MapDataset and SpectrumDataset does not handle nan values well

### ISSUE THREAD

**Issue by lmohrmann** [gammapy/gammapy#3064]
**Gammapy version**
0.17

**Bug description**
The `mask_safe` is applied in the `MapDataset` and `SpectrumDataset` by multiplying the different maps (counts, background, etc.) with the `mask_safe`. This method fails when, for instance, there are `nan` values present in the background model map (which might occur when the background model is interpolated onto the used geometry). This is because `nan * False = nan`, which results in the corresponding pixels not being properly masked.

**Expected behavior**
All pixels outside the `mask_safe` should be properly masked. This could be achieved by using a scheme like `dataset.background_model.map[~dataset.mask_safe.data] = 0` instead of the multiplication.

**Comment by adonath** [comment]
@lmohrmann I checked once again what the status here is and to apply the mask we consistently use `Map.stack( weights=)`. The `weights` argument however is meant to be more generic and not strictly for boolean types. So I think we cannot apply the proposed solution and have to fix replace `NaN` values beforehand instead. A method for this has been added in #3219

**Comment by adonath** [comment]
However once could check the dtype here: https://github.com/gammapy/gammapy/blob/master/gammapy/maps/wcsnd.py#L782

**Comment by QRemy** [comment]
PR #3416 adds a method "bkg-clip" to the SafeMaskMaker in order create a mask from aberrant values in background maps (not finite and eventually very large values). It also offers the possibility to clip the aberrant values to zero in the background map. This should solve the issue.

**Comment by adonath** [comment]
Solved by #3419.
