### ISSUE TITLE
Add list of available catalogs to high-level docs.

### ISSUE THREAD

**Issue by mapazarr** [gammapy/gammapy#308]
It would be useful to have a list of available catalogues in either here:
http://gammapy.readthedocs.org/en/latest/catalog/index.html
or here:
http://gammapy.readthedocs.org/en/latest/datasets/index.html
(or a subpage of either).

**Comment by cdeil** [comment]
This now exists: http://gammapy.readthedocs.io/en/latest/catalog/index.html#available-catalogs
(although the list is manually maintained, auto-generating it would be nicer).

But we have bigger fish to fry ... closing this issue.
