### ISSUE TITLE
Empty edisp in stacked spectral dataset

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#3094]
**Gammapy version**

Latest dev

**Bug description**

When I use the `extended_source_spectral_analysis` notebook and stack the spectral datasets, I end up with an empty edisp. See cell 11 here: https://github.com/AtreyeeS/test_notebooks/blob/master/extended_source_spectral_analysis.ipynb

Stacking of spectral datasets seems to work normally in the standard spectral analysis tutorial, so I do not understand what is going wrong here. The edisp_kernel is behaving normally on the stacked map dataset as well.

**Comment by adonath** [comment]
Thanks again @AtreyeeS, another good catch! Fix in #3096.
