### ISSUE TITLE
Axis mis-aligned in SpectrumDataset.plot_fit()

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#3098]
**Gammapy version**

Present dev

**Bug description**

The x-axis of the counts and residual plots are mis-aligned in `SpectrumDataset.plot_fit()`
This makes it very difficult to read.
See: Cell 16, https://github.com/AtreyeeS/test_notebooks/blob/master/extended_source_spectral_analysis.ipynb

**Comment by adonath** [comment]
The issue is fixed in the latest version https://docs.gammapy.org/dev/tutorials/extended_source_spectral_analysis.html#Cumulative-excess-and-signficance
