### ISSUE TITLE
[0.18]  KeyError: 'metadata' during build time test

### ISSUE THREAD

**Issue by olebole** [gammapy/gammapy#3115]
**Gammapy version**

Gammapy: 0.18 (from PyPI)

platform linux -- Python 3.9.0+, pytest-4.6.11, py-1.9.0, pluggy-0.13.0
rootdir: /build/gammapy-0.18, inifile: setup.cfg
plugins: openfiles-0.5.0, filter-subpackage-0.1.1, remotedata-0.3.2, doctestplus-0.7.0, hypothesis-5.32.1, cov-2.8.1, astropy-header-0.1.2, arraydiff-0.3

(Same for Python 3.8)

**Bug description**

During the build of the Debian package, the CI tests are run. This run creates the following error:

```I: pybuild base:232: cd /build/gammapy-0.18/.pybuild/cpython3_3.9_gammapy/build; python3.9 -m pytest 
============================= test session starts ==============================
platform linux -- Python 3.9.0+, pytest-4.6.11, py-1.9.0, pluggy-0.13.0
rootdir: /build/gammapy-0.18, inifile: setup.cfg
plugins: openfiles-0.5.0, filter-subpackage-0.1.1, remotedata-0.3.2, doctestplus-0.7.0, hypothesis-5.32.1, cov-2.8.1, astropy-header-0.1.2, arraydiff-0.3

Gammapy test data availability:
gammapy-data ... no
Gammapy environment variables:
GAMMAPY_DATA = not set
Setting matplotlib backend to "agg" for the tests.
collected 1644 items / 1 errors / 5 skipped / 1638 selected

==================================== ERRORS ====================================
_ ERROR collecting .pybuild/cpython3_3.9_gammapy/build/gammapy/utils/notebooks_test.py _
/usr/lib/python3.9/configparser.py:846: in items
    d.update(self._sections[section])
E   KeyError: 'metadata'

During handling of the above exception, another exception occurred:
gammapy/utils/notebooks_test.py:19: in <module>
    setup_cfg = dict(conf.items("metadata"))
/usr/lib/python3.9/configparser.py:849: in items
    raise NoSectionError(section)
E   configparser.NoSectionError: No section: 'metadata'
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
====================== 5 skipped, 1 error in 5.99 seconds ======================
E: pybuild pybuild:353: test: plugin distutils failed with: exit code=2: cd /build/gammapy-0.18/.pybuild/cpython3_3.9_gammapy/build; python3.9 -m pytest 
```

**Expected behavior**

The tests are expected to pass.

**To Reproduce**

 * untar the PyPI tarball
 * run `python3 setup.py build`
 * run `cd /build/gammapy-0.18/.pybuild/cpython3_3.9_gammapy/build; python3 -m pytest`

(this is how the build happens in Debian)

**Other information**

This is a regression: version 0.17 passes the tests in the same environment.

**Comment by olebole** [comment]
Is there any progress or workaround here? This problem prevents me from updating gammapy in Debian.

**Comment by adonath** [comment]
We are in the process of preparing the next release v0.19. I'll will check the behavior for the Debian build locally before the tagging and comment here again.

**Comment by adonath** [comment]
I could reproduce the issue with v0.19. Will close now.
