### ISSUE TITLE
Optional key words required for dl3 data 

### ISSUE THREAD

**Issue by SimoneMender** [gammapy/gammapy#3119]
**Gammapy version**
Gammapy version: 0.18

**Bug description**
`DataStore.from_events_files(paths)` fails with `KeyError: "Keyword 'ALT_PNT' not found."` even tough 'ALT_PNT' is an optional column (see https://gamma-astro-data-formats.readthedocs.io/en/latest/events/pointing.html).

**Expected behavior**
`DataStore.from_events_files(paths)` should work without information about 'ALT_PNT'.

**Comment by maxnoe** [comment]
* `DEADC` is optional in the `OBS_INDEX` HDUs, but gammapy assumes it is always there.

Gammapy should read `DEADC` from the `EVENTS` tables themselves, where it is a required keyword.

**Comment by adonath** [comment]
The original issue is resolved by #3613.
