### ISSUE TITLE
Crash of the FluxPointsEstimator using a dataset without a mask

### ISSUE THREAD

**Issue by bkhelifi** [gammapy/gammapy#3132]
**Gammapy version**
V0.18.1

**Bug description**
@Vardan finds out a issue when using a fermi diffuse model: 

```
>>> fluxpointestimator=FluxPointsEstimator(energy_edges=[1, 10] * u.TeV, source=“diffuse_iem”)
>>> fluxpointestimator.run(dataset)
Traceback (most recent call last):
 File “<stdin>“, line 1, in <module>
 File “/Users/vardan19/hawc_software/miniconda3/envs/gammapy-0.18.1/lib/python3.7/site-packages/gammapy/estimators/flux_point.py”, line 866, in run
  datasets, energy_min=energy_min, energy_max=energy_max
 File “/Users/vardan19/hawc_software/miniconda3/envs/gammapy-0.18.1/lib/python3.7/site-packages/gammapy/estimators/flux_point.py”, line 891, in estimate_flux_point
  datasets, energy_min=energy_min, energy_max=energy_max
 File “/Users/vardan19/hawc_software/miniconda3/envs/gammapy-0.18.1/lib/python3.7/site-packages/gammapy/estimators/flux_point.py”, line 921, in estimate_counts
  mask = dataset.mask & energy_mask
TypeError: unsupported operand type(s) for &: ‘NoneType’ and ‘bool’

```
A crash appears because the dataset has no mask and the `apply_mask_safe()` was not called explicitly for this dataset. 

**Expected behavior**
Whatever the dataset, one could work with and without a mask. An user should not care about its non-existance for our internal machinery. If the dataset.mask does not exist, one could create one internally with the good dimension automatically, without a manual call of `apply_mask_safe`.

**Comment by vardan** [comment]
I believe you tagged the wrong Vardan :)

**Comment by adonath** [comment]
This issue has been fixed in the meantime: https://github.com/gammapy/gammapy/blob/master/gammapy/estimators/flux.py#L185
