### ISSUE TITLE
Add Third HAWC catalog to gammapy.catalog

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#3147]
**Is your feature request related to a problem? Please describe.**
The 3rd HAWC catalog has recently been released. It would be nice to add it in the `gammapy.catalog` package.

**Describe the solution you'd like**
A new `SourceCatalog3HWC` should be added that contains informations from the HAWC publication: https://arxiv.org/abs/2007.08582

**Additional context**

**Comment by registerrier** [comment]
The 2HWC and 3HWC catalogs are very similar. 
To avoid code duplication, we should probably rely on inheritance. A generic class `SourceCatalogObjectHWC` could be created and `SourceCatalogObject2HWC` and `SourceCatalogObject3HWC` would only overload the `spectral_model` method. The way the spectral information is stored is the main difference between the 2 catalogs (one contains symmetric error, the other the asymmetric ones).
Opinion @adonath ?

**Comment by adonath** [comment]
@registerrier Yes, for Fermi-LAT we have done the same: https://github.com/gammapy/gammapy/blob/master/gammapy/catalog/fermi.py#L44

**Comment by registerrier** [comment]
This now solved by PR #3173 and PR #3195 .

Closing issue.
