### ISSUE TITLE
Improve observation selection tool

### ISSUE THREAD

**Issue by mapazarr** [gammapy/gammapy#315]
The [find_obs](http://gammapy.readthedocs.org/en/latest/api/gammapy.scripts.find_obs.html) command-line tool is working (see also [find_observations](http://gammapy.readthedocs.org/en/latest/obs/find_observations.html)), but it would be nice to have the following improvements:
- [ ] support for ECSV file format: https://github.com/gammapy/gammapy/pull/295#issuecomment-126890470
- [ ] There is an error on the help string here:
  https://github.com/gammapy/gammapy/blob/master/gammapy/scripts/find_obs.py#L27
  the default value is wrong.
- [ ] Add summary option (e.g. total livetime)
- [ ] Add target lookup by name option
- [ ] Maybe make a few summary tables or plots (e.g. offset distribution, ntel distribution, time distribution, ...)
- [ ] Somehow the examples from the high-level docs should be printed to the screen also when I run `--help`
- [ ] Look at the HESS findruns tool and see if it has any nice features we want.

Feature requests / suggestions welcome ...

This issue is meant to trigger the continuation of the work from PR #295.

**Comment by cdeil** [comment]
@mapazarr and I are having a weird issue where this has no effect (doesn't set the root logger level to debug as expected):
```python
logging.basicConfig(level=logging.DEBUG)
```

The solution at http://stackoverflow.com/a/14335797/498873 seems to work, i.e. changing to solves the issue:
```python
logging.getLogger().setLevel(logging.DEBUG)
```

To reproduce the issue you can run:
```python
import logging
# logging.info('a')
logging.basicConfig(level=logging.INFO)
logging.info('b')
```
For me it works and does print "b".
If I uncomment the `logging.info('a')` statement I get nothing, i.e. "b" is not printed.
Somehow the call to `logging.info` changes the state of the root logger.

So can someone explain what's going on?

And more importantly: what's the best (or a good) way to log out of a command line tool (that uses astropy in case it matters)?
https://github.com/gammapy/gammapy/blob/master/gammapy/scripts/find_obs.py#L117

**Comment by cdeil** [comment]
@eteq Any advice on the issue in the previous comment (forgot to CC you)?

**Comment by eteq** [comment]
@cdeil - I haven't really used this much, so take any of these suggestions with the appropriate grain of salt...

But my understanding is that you're "supposed" to always do `basicConfig` first - if you send something to a logger *before* that, it uses some default config, which apparently doesn't show `INFO` level messages.  So I think that's why `logging.info('a')` makes the following calls do nothing.

So my understanding of how you "should" do it is like so:

e.g. in `gammapy/__init__.py` or something that otherwise imports with gammapy
```
import logging

log = logging.getLogger('gammapy')
#you could also do this 
``` 

and in your script, you do:
```
import logging
from gammapy import log as gammapy_log

logging.basicConfig(level=logging.INFO) # this might get ignored if the user already configured `logging` their favorite way, but if called direct from the command line they probably haven't had the chance to do so
log = gammapy_log.getChild('cmdscript')

...
log.info('whatever')
...
``` 
And then you should see this when you run it straight from the script: ``INFO:gammapy.cmdscript:whatever``

Does that all make sense?

**Comment by eteq** [comment]
Oh, and I guess you should also build gammapy's logger from `astropy` using `astropy.log.getChild('gammapy')`, but I don't know that anyone's tried that (so it might have bugs?)

**Comment by cdeil** [comment]
I'm moving the discussion on how to log to https://github.com/astropy/package-template/issues/134 and will address it in a separate PR (for all of Gammapy).

**Comment by cdeil** [comment]
@mapazarr – I've removed the logging-related TODOs from the comment at the top and added a few others I think should be done.

I'm assigning this issue to myself ... I want to play with the observation selection anyways and this gives you time to focus on background modeling for the last two weeks.

**Comment by cdeil** [comment]
I'm closing this very old issue.
By now we have new classes for observation handling.
Those still need work and discussion, but this old issue isn't useful.
