### ISSUE TITLE
Docs of ObservationTable misses methods.

### ISSUE THREAD

**Issue by mapazarr** [gammapy/gammapy#316]
The doc page for the observation table:
 http://gammapy.readthedocs.org/en/latest/api/gammapy.obs.ObservationTable.html
does not show the newly introduced `select_*` methods from PR #295.

The methods are there in the source code:
  http://gammapy.readthedocs.org/en/latest/_modules/gammapy/obs/observation.html#ObservationTable

And I can see the doc entries in my computer, when building the docs. Is there a reason why they shouldn't appear online?

**Comment by mapazarr** [comment]
There is also an error on the help string here:
 https://github.com/gammapy/gammapy/blob/master/gammapy/scripts/find_obs.py#L27
the default value is wrong.

**Comment by mapazarr** [comment]
I also don't like the output of these lines:
 https://github.com/gammapy/gammapy/blob/master/gammapy/scripts/find_obs.py#L192
 https://github.com/gammapy/gammapy/blob/master/gammapy/scripts/find_obs.py#L193
because the `logger` introduces `INFO - ` at the beginning of them.

**Comment by cdeil** [comment]
It's very weird. I wiped RTD and the new build passed:
https://readthedocs.org/builds/gammapy/3197257/

But as @mapazarr said before, the new methods don't show up in the docs:
https://gammapy.readthedocs.org/en/latest/api/gammapy.obs.ObservationTable.html

The HTML output looks OK to me locally.

Hmm ... I'll just try wiping RTD again tomorrow and we'll see.
Assigning this issue to myself now.

**Comment by cdeil** [comment]
Looks OK to me now ... probably just one more case of RTD taking it's time to update the web server after a build.

@mapazarr – Close this issue?

**Comment by mapazarr** [comment]
Yes, now it looks fine.
