### ISSUE TITLE
Analysis sets a FoVBackgroundModel on OnOff datasets

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#3160]
**Gammapy version**
v0.18.2 and dev

**Bug description**
When creating and fitting a `SpectrumDatasetOnOff`, the `Analysis.set_models` method defines a `FoVBackgroundModel` on each dataset.

**Expected behavior**
No background model should be produced for OnOff datasets.

**Comment by adonath** [comment]
I noticed am fixed this bug already in https://github.com/gammapy/gammapy/pull/3145/files#diff-e4bc10c9ee73fdf72031f8581d094f065a61a1099443ecd606b78c477e7379dbR156.
