### ISSUE TITLE
Dataset stacking does not stack the predicted counts (mu_src)

### ISSUE THREAD

**Issue by tstolarczyk** [gammapy/gammapy#3174]
Gpy 0.17

I have a long list of simulated spectra in time slices that want to stack with time.
For this, I have created datasets(`SpectrumDatasetonOff)`  with common energy binning.
I am stacking the datasets as follows (`dsets` is `Datasets`) :
```
def cumulate(dsets):
    stacked = dsets[0].copy()
    ds_stacked = Datasets([stacked.copy(name=dsets[0].name)])
    for ds in dsets[1:]:
        stacked.stack(ds)
        ds_stacked.append(stacked.copy(name="Stacked-"+ds.name))
    return  ds_stacked
```

I am now creating a plot panel with all the spectra using, for each of the dataset of the collection:
`dset.plot_counts()`

This plots "automatically" both the excess and the expected count number (`mu_src`).
I have used this for the `Datasets `before stacking and it works well.

Doing this for the stacked collection:
- The excess count is the one expected, i.e. the count numbers are stacked (increasing smoothly)
- But the ` mu_src` counts remain the one from the first spectrum.

I am of course expecting that mu_src is stacked also.

Note that I got the same problem when extracting the flux, i.e. the spectrum list s frozen to the first one in the stack, i.e.
`spectrum = dset.models[0].spectral_model`
is the same (1st)  whatever the set in the `Datasets `collection.
 
Any idea?
Thanks?

**Comment by adonath** [comment]
@tstolarczyk I think this problem is related to the caching of the exposure in the model evaluation in Gammapy v0.17. To get it work.correctly you have to reset the model on the stacked dataset like: 

```python3
from gammapy.datasets import SpectrumDatasetOnOff
from gammapy.modeling import Fit
from gammapy.modeling.models import PowerLawSpectralModel, SkyModel
import matplotlib.pyplot as plt

path = "$GAMMAPY_DATA/joint-crab/spectra/hess/"
obs_1 = SpectrumDatasetOnOff.from_ogip_files(path + "pha_obs23523.fits")
obs_2 = SpectrumDatasetOnOff.from_ogip_files(path + "pha_obs23592.fits")

pwl = PowerLawSpectralModel(
    index=2.781,
    amplitude='5.2e-11  cm-2 s-1 TeV-1',
    reference='1 TeV',
)

model = SkyModel(pwl)
obs_1.models = model

obs_1.plot_counts()
plt.xlim(3e8, 3e10)
plt.ylim(1e-1, 1e2)

stacked = obs_1.copy()
stacked.stack(obs_2)

# This line resets the exposure definition
stacked.models = model

stacked.plot_counts()
plt.xlim(3e8, 3e10)
```

**Comment by adonath** [comment]
BTW: this is one of the reasons why in the current version of Gammapy we decided to reset the model definition in `dataset.copy()`...

**Comment by tstolarczyk** [comment]
@adonath, I am not sure this solves my problem...

Each slice has a different model (model1, model2...). 
I understand that `stacked.models=model` reset the `model `to model for each slice.
In my case, If I stack slice 1 and slice 2:
- slice 1 has `model1`
- slice 2 has `(livetime1 * model1 + livetime2 * model2)/(livetime1+livetime2) `
if I am not wrong (and be given that all datasets are defined on the same energy axis).
This is also relevant for the flux extraction.

Second point: I realize that the drawing of the energy masking has no sense in plot_counts for a stacked dataset since the maskings differ from one slice to another (potentially)

What do you suggest?

**Comment by adonath** [comment]
If the model differs, I think the only option is to compute the npred and stack "by hand", like:

```python3
npred_total = datasets[0].npred()

for dataset in datasets[1:]:
    npred = dataset.npred()
    npred_total.stack(npred)
```
But in this case you can not use `.plot_counts()` anymore...

Alternatively you can possibly modify the amplitude of your individual models with the lifetime, but the book-keeping becomes complicated in this case I think.

**Comment by tstolarczyk** [comment]
Hello,
In fact I have reimplement the correct models by hand with the following function (I use template models, I guess it cannot work with models based on functions). It seems ok and I can still use plot_counts...
```
def cumulate(dsets, debug=False):
    """
    Returns a collection of stacked Gammapy datasets (Datasets) from an
    initial colection.
    In the original Gammapy 0.17 code, the models are not stacked.
    Done by hand here.

    Parameters
    ----------
    dsets : Datasets
        A collection of dataset objects

    Returns
    -------
    ds_stacked : Datasets
        A collection of stacked dataset objects

    """
    stacked    = dsets[0].copy() # Copy first unchanged dataset
    ecenter    = dsets[0].aeff.data.axes[0].center # Original E sampling

    ds_stacked = Datasets([stacked.copy(name=dsets[0].name)]) # Init. new Dataset collection

    if debug:
        print("Dt= {:8.2f}    Model: {:6s}"
              .format(stacked.livetime,stacked.models[0].name))

    # Loop over subsequent datasets and stack
    flux = np.zeros(len(ecenter))

    for ds in dsets[1:]:

        dt_stack = stacked.livetime
        dt       = ds.livetime
        stacked.stack(ds) # stack current ds to stacked list

        # Build a stacked model weighted by livetime
        flux_org = ds.models[0].spectral_model(ecenter) # Original flux points
        flux = (dt_stack.value*flux + dt.value*flux_org)/(dt_stack.value+dt.value)

        spec = TemplateSpectralModel(energy = ecenter,
                                     values = flux,
                                     norm= 1.,
                                     interp_kwargs={"values_scale": "linear"})
        stacked.models = SkyModel(spectral_model = spec,
                                  name  = "Stacked"+"-"+ds.name)

        if debug:
            print("Dt= {:8.2f}    Model: {:6s} --- Stacked --> Dt= {:8.2f}    Model: {:6s}"
              .format(ds.livetime,ds.models[0].name,stacked.livetime,stacked.models[0].name))

        ds_stacked.append(stacked.copy(name="Stacked-"+ds.name))

    return  ds_stacked
```
