### ISSUE TITLE
Add option to not include runs with missing IRFs?

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#3184]
Both the HESS fits productions have some runs in the index tables with some missing IRFs.

Currently, `datastore.get_observations()` raises a warning for these observations, but removing these observations is left to the user. The analysis breaks at the Map making stage.
This is quite unpleasant.

Maybe we can add an option `datastore.get_observations(required_IRF=all)  with all = ['bkg', 'psf', 'aeff', 'edisp']`? 

I think we decided at some point that checking the datastore is not the responsibility of Gammapy, but this use case seems to necessary.

Comments @registerrier @adonath ?

**Comment by registerrier** [comment]
This sounds a reasonable feature. After all, many data production are in the making and we should not expect that fully clean and complete databases to be the norm any time soon.

**Comment by adonath** [comment]
Solved in #3205.
