### ISSUE TITLE
Huge memory usage in 'maker'

### ISSUE THREAD

**Issue by mizorafa** [gammapy/gammapy#3192]
Though it may be an elementary question, I have a question about somehow unpredicted error I faced.

I have recently started using Gammapy, and I tried the following tutorial for data reduction:
[https://docs.gammapy.org/0.18.2/makers/index.html]

When the first example program
```
from gammapy.maps import MapAxis, WcsGeom
from gammapy.datasets import MapDataset

energy_axis = MapAxis.from_bounds(
    1, 10, nbin=11, name="energy", unit="TeV", interp="log"
)
geom = WcsGeom.create(axes=[energy_axis])
dataset_empty = MapDataset.create(geom=geom)
print(dataset_empty)
```
was run in jupyter notebook at my local environment with the newest Gammapy(ver.0.18.2) and 16GB memory, the memory usage drastically increased to about 20GB and in the end the kernel died; in short the program was ended up being forcefully closed. 

Apparently there was something wrong with `MapDataset.create(geom=geom)`.

Other member said the memory usage reached 60GB when he tried the same code in a shared server (equipped with about 100GB memory).

It is inconvenient to be unable to use it in a local environment of a general computer. 
I have no idea why it happens. Is there someone to know?

**Comment by adonath** [comment]
Thanks @mizorafa, I can reproduce the issue!

There is one big difference here in your example compared to the tutorials: In the line `geom = WcsGeom.create(axes=[energy_axis])`, you don't define a `binsz` and `width` of the map. This means by default an all-sky map with a bin size of `0.5 deg` is created:
```python3
>>> from gammapy.maps import MapAxis, WcsGeom
>>> geom = WcsGeom.create(axes=[energy_axis])
>>> print(geom)
WcsGeom

	axes       : ['lon', 'lat', 'energy']
	shape      : (720, 360, 11)
	ndim       : 3
	frame      : icrs
	projection : CAR
	center     : 0.0 deg, 0.0 deg
	width      : 360.0 deg x 180.0 deg
```
This is in general not a problem but, the default bin size for the PSF and energy dispersion maps is set to `0.2 deg`. This means in `MapDataset.create()` huge arrays are created see:
```python3
>>> from gammapy.maps import MapAxis, WcsGeom
>>> from gammapy.datasets import create_map_dataset_geoms

>>> energy_axis = MapAxis.from_bounds(
    1, 10, nbin=11, name="energy", unit="TeV", interp="log"
)
>>> geom = WcsGeom.create(axes=[energy_axis])
>>> print(create_map_dataset_geoms(geom)["geom_psf"])
WcsGeom

	axes       : ['lon', 'lat', 'rad', 'energy_true']
	shape      : (1800, 900, 66, 11)
	ndim       : 4
	frame      : icrs
	projection : CAR
	center     : 0.0 deg, 0.0 deg
	width      : 360.0 deg x 180.0 deg
```
The solution here is to specify the bin size of the IRF maps as well, e.g. like:
```python3
from gammapy.maps import MapAxis, WcsGeom
from gammapy.datasets import MapDataset
from astropy import units as u

energy_axis = MapAxis.from_bounds(
    1, 10, nbin=11, name="energy", unit="TeV", interp="log"
)
geom = WcsGeom.create(axes=[energy_axis])
dataset_empty = MapDataset.create(geom=geom, binsz_irf=10 * u.deg)
print(dataset_empty)
```
Or to choose a smaller region of interested like:
```Python3
from gammapy.maps import MapAxis, WcsGeom
from gammapy.datasets import MapDataset
from astropy import units as u

energy_axis = MapAxis.from_bounds(
    1, 10, nbin=11, name="energy", unit="TeV", interp="log"
)
geom = WcsGeom.create(width=10 * u.deg, binsz=0.02 *u.deg,  axes=[energy_axis])
dataset_empty = MapDataset.create(geom=geom)
print(dataset_empty)
```
Hope this helps. In general we could possibly choose a more careful default value of the bin size of the IRF maps...

**Comment by mizorafa** [comment]
Thank you @adonath for your kind and quick response!!
Your clear explanation helped me understand what happens.

Actually, the example code I wrote above is exactly the same as the very first example introduced in the tutorial (copy and paste): `https://docs.gammapy.org/0.18.2/makers/index.html`
So I think it may be better to rewrite the example code in the tutorial so that it can be run at a normal computer in short time.

Anyway, thanks a lot for your helpful explanation!!

**Comment by registerrier** [comment]
Thanks @mizorafa . Indeed, the examples shown there are not adapted. I have a PR underway for the `makers` documentation. I will modify this.
