### ISSUE TITLE
Support reading healpix files in "Hermes" format

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#3220]
**Gammapy version**
v0.18.2 and dev

**Bug description**
It is impossible to read an healpix map that does not have a clear predefined convention. For instance, maps produced by the Hermes software cannot be opened with `HpxNDMap`, because the column name does not belong to one of the pre-existing conventions. 
It should be possible to specify the column name to use.

**Expected behavior**
It should be possible to load a basic flat healpix map into an `HpxNDMap` without complex actions.

**To Reproduce**
```
from astropy.io import fits
from gammapy.maps import HpxNDMap

hdulist = fits.open('https://lambda.gsfc.nasa.gov/data/map/dr5/skymaps/1yr/raw/wmap_qumap_r4_yr1_K1_v5.fits')

# Fails because cannot recognize convention
wmap = HpxNDMap.from_hdulist(hdulist)
# Does not fail but contain an empty map
wmap = HpxNDMap.from_hdulist(hdulist, format="gadf")
print(wmap.data)
```

**Comment by adonath** [comment]
Thanks @registerrier! 

I think if the HPX FITS files does not follow any convention, then it should fail to read! So I think the Gammapy behaviour is completely correct here. The "Hermes" format is not known to Gammapy, so it fails with an acceptable error message.

 From a quick look the example file it does e.g. not specify the coordinate system being used and this is impossible to guess for Gammapy. So the only way this could be supported by Gammapy is to introduce a new "format" for this kind of maps produced by Hermes, which then defines the missing implicit meta information such as the coordinate system. I'll rename and re-label the issue, I don't think it's bug from the Gammapy side...but rather a feature request to support reading HPX Maps in "Hermes"  format.

**Comment by adonath** [comment]
Just for completeness, reading in a flat HPX maps is still simple enough I think:
```python3
from astropy.table import Table
from gammapy.maps import HpxNDMap

filename = 'https://lambda.gsfc.nasa.gov/data/map/dr5/skymaps/1yr/raw/wmap_qumap_r4_yr1_K1_v5.fits'
table = Table.read(filename)

map = HpxNDMap.create(nside=t.meta["NSIDE"], nest=True, frame="galactic")
wmap.quantity = table["Q_POLARISATION"].quantity
```
It requires putting in missing meta information by hand, which I think is reasonable to ask from users...

We could transform this into a docs example as well.

**Comment by registerrier** [comment]
Indeed this WMAP example is not really nice since there is no coordinate specified.

Yet I think the list of healpix conventions that we have now is a bit messy and is only due to internal format handling in the Fermi Science tools. There seem to be no good reason for imposing the column name in the convention, it should be an argument of the read method.

**Comment by adonath** [comment]
@registerrier I think this issue will be resolved by #3320 and follow up PRs. Will relabel but requires confirmation...

**Comment by adonath** [comment]
@vikasj78 I assigned you here: maybe you can check whether the generic healpy format also supports the example map in the initial post...

**Comment by adonath** [comment]
Just to confirm, the following works:
```python3
from astropy.io import fits
from gammapy.maps import HpxNDMap

hdulist = fits.open('https://lambda.gsfc.nasa.gov/data/map/dr5/skymaps/1yr/raw/wmap_qumap_r4_yr1_K1_v5.fits')

wmap = HpxNDMap.from_hdulist(hdulist, format="healpy", colname="Q_POLARISATION")
```

**Comment by adonath** [comment]
The following works, but returns a map with all zeros:
```python3
from astropy.io import fits
from gammapy.maps import HpxNDMap

hdulist = fits.open('https://lambda.gsfc.nasa.gov/data/map/dr5/skymaps/1yr/raw/wmap_qumap_r4_yr1_K1_v5.fits')

wmap = HpxNDMap.from_hdulist(hdulist, format="healpy")
```
Maybe it should raise an error instead...

**Comment by vikasj78** [comment]
I have now changed it to raise an error. This new implementation would require passing a colname, there is no default anymore. As there does not seems to be a general column name scheme, this should be more secure.
