### ISSUE TITLE
ReflectedRegionsBackgroundMaker fails when no OFF are found

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#3259]
**Gammapy version**
v0.18.2 and dev

**Bug description**
When no reflected regions are found `ReflectedRegionsBackgroundMaker.run()` fails with `ZeroDivisionError: division by zero` because of division by 0 in `SpectrumDatasetOnOff.from_spectrum_dataset()`. This is due to the division of floats rather than numpy arrays (when no off regions are found `dataset.acceptance_off` is set to 0.)

Note that this appears only if the `SpectrumDataset` already contains a `background` attribute, e.g. if the option "background" is passed to the `SpectrumDatasetMaker`.

**Expected behavior**
A `SpectrumDatasetOnOff` should be produced with no counts_off and acceptance_off set to 0.

**Comment by registerrier** [comment]
The issue is connected with #3175

**Comment by adonath** [comment]
Thanks @registerrier, I addition we could do the same as proposed in #3247 and also set the `mask_safe` to all false.

For the case where background = None, we already have a unit test: https://github.com/gammapy/gammapy/blob/master/gammapy/makers/background/tests/test_reflected.py#L190
