### ISSUE TITLE
Support for single offset IRF with only 2 bin edges for offset range

### ISSUE THREAD

**Issue by chaimain** [gammapy/gammapy#3269]
I am using gammapy v0.18.2, for analysing DL3 data from LST-1.

The standard offset in LST is 0.4 deg, and although gammapy supports single offset binning by having single THETA_LO and THETA_HI values, it was not possible to use Effective area beyond just reading it.

A workaround that I checked was to have 3 offset bin edges, like [0.3, 0.5, 0.7] deg, but for that, I have to duplicate the effective area into another axis.

@adonath mentioned in an earlier thread in the slack channel (started by @mdebony), that there is a missing support of bin centers in GADF specification, which could be the cause of this need for a workaround.

Is it possible to use only single THETA_LO and THETA_HI values and not having to duplicate the effective area?

I am having this trouble while creating DL3 generating Tools in lstchain [here](https://github.com/cta-observatory/cta-lstchain/pull/593/)

Any other suggestion or solution would be highly appreciated.

**Comment by maxnoe** [comment]
@chaimain I think an example of what exactly is not working is needed here.

Can you provide IRF files with a single offset and code / exception what is not working?

**Comment by chaimain** [comment]
I have an updated astropy v4.2
I attach here the 2 IRFs generated using pyirf functions, with offset bins as [0.3, 0.5, 0.7] and [0.3, 0.5] for files named as per the number of these edges.
I use LST data to produce a DL3 file with these IRFs.

Both can be read by EffectiveAreaTable2D as can be seen by the following example:
```
from gammapy.irf import EffectiveAreaTable2D
from gammapy.maps import MapAxis
import numpy as np
from astropy import units as u

offset_axis = MapAxis.from_edges([0.2, 0.21], unit="deg", name="offset")
offset_axis_3edges = MapAxis.from_edges([0.2, 0.21, 0.22], unit="deg", name="offset")
energy_axis_true = MapAxis.from_energy_bounds("0.3 TeV", "100 TeV", nbin=30, name="energy_true")

aeff = EffectiveAreaTable2D(
    offset_axis=offset_axis,
    energy_axis_true=energy_axis_true,
    data=np.arange(30).reshape((30, 1)) * u.cm ** 2
)
aeff2 = EffectiveAreaTable2D(
    offset_axis=offset_axis_3edges,
    energy_axis_true=energy_axis_true,
    data=np.repeat(np.arange(30), 2).reshape((30, 2))* u.cm ** 2
)

print(aeff.data.evaluate(energy_true=[1, 3, 10] * u.TeV, offset=0.1 * u.deg)) 
print(aeff2.data.evaluate(energy_true=[1, 3, 10] * u.TeV, offset=0.1 * u.deg))
[ 5.71764418 11.39117791 17.60882209] cm2
[ 5.71764418 11.39117791 17.60882209] cm2
```
However, when using SpectrumDatasetMaker for spectral analysis, I get the error that the shape of the effective area (36,) does not match axes shape (36, 1) for the file with the IRF created with 2 offset edges.
Following have some standard variables like e_reco, on_region, obs_id, observation, etc.
```
dataset_empty = SpectrumDataset.create(e_reco=e_reco, e_true=e_true, region=on_region)
dataset_maker = SpectrumDatasetMaker(
    containment_correction=False, selection=["counts", "aeff", "edisp", "background", "exposure"]
)
dataset = dataset_maker.run(dataset_empty.copy(name=str(obs_id)), observation)
------------------------------------------------------------------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/.conda/envs/lst-dev/lib/python3.7/site-packages/gammapy/utils/fits.py in __get__(self, instance, objtype)
    120         try:
--> 121             return instance.__dict__[self.name]
    122         except KeyError:
KeyError: 'aeff'

During handling of the above exception, another exception occurred:
ValueError                                Traceback (most recent call last)
<timed exec> in <module>

~/.conda/envs/lst-dev/lib/python3.7/site-packages/gammapy/makers/spectrum.py in run(self, dataset, observation)
    192         kwargs = {
    193             "gti": observation.gti,
--> 194             "meta_table": self.make_meta_table(observation),
    195         }
    196 

~/.conda/envs/lst-dev/lib/python3.7/site-packages/gammapy/makers/spectrum.py in make_meta_table(observation)
    169         """
    170         meta_table = Table()
--> 171         meta_table["TELESCOP"] = [observation.aeff.meta.get("TELESCOP")]
    172         meta_table["OBS_ID"] = [observation.obs_id]
    173         meta_table["RA_PNT"] = [observation.pointing_radec.icrs.ra.deg] * u.deg

~/.conda/envs/lst-dev/lib/python3.7/site-packages/gammapy/utils/fits.py in __get__(self, instance, objtype)
    123             hdu_loc = instance.__dict__[f"_{self.name}_hdu"]
    124             try:
--> 125                 value = hdu_loc.load()
    126             except KeyError:
    127                 value = None

~/.conda/envs/lst-dev/lib/python3.7/site-packages/gammapy/utils/fits.py in load(self)
     95             cls = IRF_REGISTRY.get_cls(hdu_class)
     96 
---> 97             return cls.read(filename, hdu=hdu)
     98 
     99 

~/.conda/envs/lst-dev/lib/python3.7/site-packages/gammapy/irf/effective_area.py in read(cls, filename, hdu)
    411         """Read from file."""
    412         with fits.open(str(make_path(filename)), memmap=False) as hdulist:
--> 413             return cls.from_hdulist(hdulist, hdu=hdu)
    414 
    415     def to_effective_area_table(self, offset, energy=None):

~/.conda/envs/lst-dev/lib/python3.7/site-packages/gammapy/irf/effective_area.py in from_hdulist(cls, hdulist, hdu)
    405     def from_hdulist(cls, hdulist, hdu="EFFECTIVE AREA"):
    406         """Create from `~astropy.io.fits.HDUList`."""
--> 407         return cls.from_table(Table.read(hdulist[hdu]))
    408 
    409     @classmethod

~/.conda/envs/lst-dev/lib/python3.7/site-packages/gammapy/irf/effective_area.py in from_table(cls, table)
    399             offset_axis=offset_axis,
    400             data=table["EFFAREA"].quantity[0].transpose(),
--> 401             meta=table.meta,
    402         )
    403 

~/.conda/envs/lst-dev/lib/python3.7/site-packages/gammapy/irf/effective_area.py in __init__(self, energy_axis_true, offset_axis, data, meta, interp_kwargs)
    366 
    367         self.data = NDDataArray(
--> 368             axes=[energy_axis_true, offset_axis], data=data, interp_kwargs=interp_kwargs
    369         )
    370         self.meta = meta or {}

~/.conda/envs/lst-dev/lib/python3.7/site-packages/gammapy/utils/nddata.py in __init__(self, axes, data, meta, interp_kwargs)
     37         if np.shape(data) != self._axes.shape:
     38             raise ValueError(
---> 39                 f"data shape {data.shape} does not match"
     40                 f"axes shape {self._axes.shape}"
     41             )

ValueError: data shape (36,) does not matchaxes shape (36, 1)
```
It works fine with IRFs created with 3 offset edges, with the workaround on the effective area as shown in the earlier example.

[test_offset_2edges_irf.fits.gz](https://github.com/gammapy/gammapy/files/6156068/test_offset_2edges_irf.fits.gz)
[test_offset_3edges_irf.fits.gz](https://github.com/gammapy/gammapy/files/6156069/test_offset_3edges_irf.fits.gz)

**Comment by adonath** [comment]
Thanks a lot @chaimain, I presume you use Gammapy v0.18.2?

**Comment by adonath** [comment]
@chaimain I can reproduce the issue. If you consider the following example:

```python3
from astropy.table import Table
from gammapy.utils.scripts import make_path

t = Table.read("test_offset_3edges_irf.fits", hdu="EFFECTIVE AREA")
print("2 edges :", t["EFFAREA"].data.shape)

t = Table.read("test_offset_2edges_irf.fits", hdu="EFFECTIVE AREA")
print("3 edges :", t["EFFAREA"].data.shape)

filename = make_path("$GAMMAPY_DATA/hess-dl3-dr1/data/hess_dl3_dr1_obs_id_020136.fits.gz")
aeff_ref = Table.read(filename, hdu=3)
print("Ref file:", aeff_ref["EFFAREA"].quantity.shape)
```
This prints (I think the files are named incorrectly...):
```
2 edges : (1, 36)
3 edges : (1, 2, 36)
Ref file: (1, 6, 96)
```
So the version with 2 offset bins misses one dimension, that is required. If you use e.g. Gammapy to write your toy example files and read them back again:
```python3
from gammapy.irf import EffectiveAreaTable2D
from gammapy.maps import MapAxis
import numpy as np
from astropy import units as u

offset_axis = MapAxis.from_edges([0.2, 0.21], unit="deg", name="offset")
offset_axis_3edges = MapAxis.from_edges([0.2, 0.21, 0.22], unit="deg", name="offset")
energy_axis_true = MapAxis.from_energy_bounds("0.3 TeV", "100 TeV", nbin=30, name="energy_true")

aeff = EffectiveAreaTable2D(
    offset_axis=offset_axis,
    energy_axis_true=energy_axis_true,
    data=np.arange(30).reshape((30, 1)) * u.cm ** 2
)

aeff.to_table().write("toy_aeff_2_offset_bins.fits", overwrite=True)

aeff2 = EffectiveAreaTable2D(
    offset_axis=offset_axis_3edges,
    energy_axis_true=energy_axis_true,
    data=np.repeat(np.arange(30), 2).reshape((30, 2))* u.cm ** 2
)

aeff2.to_table().write("toy_aeff_3_offset_bins.fits", overwrite=True)

t = Table.read("toy_aeff_2_offset_bins.fits", hdu="EFFECTIVE AREA")
print(t["EFFAREA"].data.shape)

t = Table.read("toy_aeff_3_offset_bins.fits", hdu="EFFECTIVE AREA")
print(t["EFFAREA"].data.shape)
```
It prints:
```
(1, 1, 30)
(1, 2, 30)
```
So even the case with 2 offset bins has stored a 3D data array as expected. So the question is how did you create the `"test_offset_3edges_irf.fits",` file and in this script adding a new dimension to the data like `data[np.newaxis]` or `data.reshape((1, 1, -1))` should make the data 3D and fix the issue.

**Comment by adonath** [comment]
Maybe https://github.com/astropy/astropy/issues/10765 is related?

**Comment by adonath** [comment]
For the record: it seems in `pyirf` this is handled correctly https://github.com/cta-observatory/pyirf/blob/master/pyirf/io/gadf.py#L71

**Comment by maxnoe** [comment]
@adonath you have 2 and 3 edges mixed up in your example

**Comment by adonath** [comment]
@maxnoe I think the files are named incorrectly...

**Comment by chaimain** [comment]
Thank you for checking this @adonath! I did mix up the effective areas while storing them in my intended IRF file.

**Comment by maxnoe** [comment]
So in this case, actually the 3 edges case is broken.

However, neither of these example files are matching the issue description. Having just a single bin (two edges) would mean having only a single entry in the `LO` / `HI` columns.

These files have two / three. In the three edges case, the effective area has the wrong shape

**Comment by maxnoe** [comment]
> @maxnoe I think the files are named incorrectly...

Ah, right! Sorry.

**Comment by chaimain** [comment]
I am rechecking the way I calculate the effective area and will get back soon on it.

**Comment by maxnoe** [comment]
@chaimain The error is that the two edges file has the wrong shape. It has shape `36` instead of `1, 36`.

**Comment by chaimain** [comment]
Yes, it right that the way I was creating the Effective Area IRF was incorrect. I think I did not correct that step when astropy had corrected the issue of reading a single entry column data.
Indeed pyirf does it correctly!
Sorry for this long misunderstanding!
