### ISSUE TITLE
ExcessMapEstimator ignores models with datasets_names attribute set

### ISSUE THREAD

**Issue by luca-giunti** [gammapy/gammapy#3273]
**Gammapy version**
v0.18.2

**Bug description**
Given that in [this line](https://github.com/gammapy/gammapy/blob/1d4bcee496f6884bd99a2476d281fec7f785a23a/gammapy/estimators/excess_map.py#L154) the dataset name is changed (as no `name` parameter is passed to `resample_energy_axis`), the models assignment done three lines later ([here](https://github.com/gammapy/gammapy/blob/1d4bcee496f6884bd99a2476d281fec7f785a23a/gammapy/estimators/excess_map.py#L157)) fails for all models that have a `datasets_names` attribute set. As a result, the `ExcessMapEstimator.run()` ignores those models.

Probably passing the dataset `name` to the `resample_energy_axis` would solve this issue.

**Comment by adonath** [comment]
Thanks @luca-giunti , indeed this looks like a bug. I also agree on your proposed solution. This is exactly how we should handle this in Gammapy internally, whenever we modify a dataset we should keep the name explicitly so that the model is still valid...

**Comment by registerrier** [comment]
Well, the logic should rather be that we resample the background npred and not the background map. I think this was the case initially. 

I don't think having different datasets with identical names is a good design. Also, with a different energy axis, I don't think the npred calculation would be conserved before and after energy axis resampling.

**Comment by adonath** [comment]
> Also, with a different energy axis, I don't think the npred calculation would be conserved before and after energy axis resampling

Naively I think it should. The true energy axis stays untouched and the reco energy axis is just summed up, whether this happens in the application of the RMF matrix or after in `resample_energy_axis()` shouldn't matter. But I have never checked...

**Comment by adonath** [comment]
> I don't think having different datasets with identical names is a good design

I agree in general, however in this case the derived dataset is always internal and never(!) visible to the user. So having this pattern in `Estimator` classes is fine I guess:
```python3
modified_dataset = dataset.resample_energy_axis()
modified_dataset.models = dataset.models.copy()
```

**Comment by registerrier** [comment]
> > Also, with a different energy axis, I don't think the npred calculation would be conserved before and after energy axis resampling
> 
> Naively I think it should. The true energy axis stays untouched and the reco energy axis is just summed up, whether this happens in the application of the RMF matrix or after in `resample_energy_axis()` shouldn't matter. But I have never checked...

Sorry I was unclear. What I meant is that:
applying the `NormSpectralModel` correction to the result of `dataset.background.resample_axis(axis)` will not yield the same result as using `dataset.npred_background().resample_axis(axis)` because the `NormSpectralModel` is applied in the resampled dataset energy bins.

The number of predicted background counts is therefore not a priori identical between the two methods. 

In order to preserve the predicted number of background counts during the energy axis resampling, we have to resample the npred_background.

**Comment by adonath** [comment]
@registerrier Indeed you are right with the background correction. So the internal handling becomes rather:
```python3
modified_dataset = dataset.resample_energy_axis()
modified_dataset.background = dataset.npred().resample_energy_axis()
```
I remember we discussed an option like `apply_bkg_correction` to the dataset methods, but given it is still one line of code, it's probably acceptable...
