### ISSUE TITLE
Correct placement of datastore classes and obs list format converter functions

### ISSUE THREAD

**Issue by mapazarr** [gammapy/gammapy#328]
While working on PR #319 I am encountering the following problem:

I added 2 functions to deal with observation table format conversion and integrated them into the datastore classes, so that the format of obs tables and datastore obs tables imported from the H.E.S.S. runinfo.fits file follow the convention here:
http://gammapy.readthedocs.org/en/latest/dataformats/observation_lists.html
(I also fixed small bugs in the datastore classes).

1. I first attempted to add the functions to the datasets module in an extra file `convert.py`, but then I had problems, when importing then within `obs.datastore.py`. (A circular dependency I think?) Before you ask, I had updated the corresponding `__init.py__` file.

 Please see this commit: mapazarr@675df3e

 And the error log:
```
[MunSys] ~ % python 
Python 3.4.3 |Anaconda 2.3.0 (64-bit)| (default, Jun  4 2015, 15:29:08) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from gammapy.obs import DataStore
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mapaz/astropy/development_code/gammapy/gammapy/obs/__init__.py", line 7, in <module>
    from .datastore import *
  File "/home/mapaz/astropy/development_code/gammapy/gammapy/obs/datastore.py", line 10, in <module>
    from ..datasets import convert_obs_list_format_to_gammapy
  File "/home/mapaz/astropy/development_code/gammapy/gammapy/datasets/__init__.py", line 6, in <module>
    from .make import *
  File "/home/mapaz/astropy/development_code/gammapy/gammapy/datasets/make.py", line 14, in <module>
    from ..background import Cube
  File "/home/mapaz/astropy/development_code/gammapy/gammapy/background/__init__.py", line 14, in <module>
    from .make import *
  File "/home/mapaz/astropy/development_code/gammapy/gammapy/background/make.py", line 10, in <module>
    from ..obs import DataStore
ImportError: cannot import name 'DataStore'
```

2. Moving the `convert.py` file to the `obs` module didn't help.

3. So I moved the functions into `obs.datastore.py` and it worked. (It also works if they are in `obs.observation.py`, but I didn't like them there, since the functions are specific to a particular experiment.)

Other possibilities would be:

4. Add the converter classes as methods of `~ObservationTable`, but I'm not sure they belong there. It seems they are more like utility functions, rather than class members.

5. Move `obs.datastore.py` to `datasets`. Since it deals with the dataset files, maybe it should go there? Then the converters can be placed in `datasets` as well, as I did in my 1st attempt. I think this is their natural location.

For now I'm using optioin 3. (works), but I think option 5. (not tested) would be the most logical.

@cdeil @adonath Please let me know if you like the current location of the functions, otherwise, let me know what is the best location for them.

**Comment by cdeil** [comment]
@mapazarr I've run into circular import issues before when adding things to `gammapy.datasets` (see #171). I need to clean this up and document it, but the solution @adonath  and I discussed is to not put things in `gammapy.datasets`, or even to avoid all imports of Gammapy classes there and have those functions only return filenames.

If you have something that works now, please just leave as is unless @adonath or I suggest other locations during code review of #319. I'm not sure I understand the issues you're describing here, let's discuss in the hangout tomorrow.

**Comment by cdeil** [comment]
The content of the `gammapy.obs` sub-package has been merged into the [gammapy.data](https://gammapy.readthedocs.org/en/latest/data/index.html) sub-package in #384.

I think this basically adresses this issue ... closing it now.

Note that `gammapy.data` is still heavily work in progress and more restructuring will be done over the coming months. We'll have to improve one function and class at a time and clean up.
