### ISSUE TITLE
Introduce YAML in Gammapy

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#329]
I'd like us to use YAML in Gammapy for configuration files.
- [ ] Update [this docs page](https://gammapy.readthedocs.org/en/latest/dataformats/file_formats.html) with some info on JSON and YAML and explain why we prefer YAML.
- [x] Add PyYAML to `.travis.yml` and some simple test to show that it works.

**Comment by cdeil** [comment]
https://github.com/open-gamma-ray-astro/joint-crab/blob/master/2_results.ipynb


OK to close this issue, not a concrete action item. But overall we should

**Comment by cdeil** [comment]
Should also be at least mentioned in the Gammapy docs (maybe even used): http://docs.astropy.org/en/stable/io/misc.html#module-astropy.io.misc.yaml

**Comment by adonath** [comment]
@cdeil OK, if you'd like to add a docs section, but I think I'd even prefer to extend  the corresponding section in #1971 and put a detailed proposal how to implement the YAML format for model serialization there. This way I think it's more likely to result in an actual implementation, that we can use and gain experience with. This can also serve as a reference implementation for config files and fit results etc., that will come later.

Concerning the API I have clear preference for a single `.read()` and `.write()` method, that calls into `from_yaml`, `from_xml` etc., both might use an additional `from_dict()` in the end.

**Comment by cdeil** [comment]
xref #1995

**Comment by cdeil** [comment]
I'm closing this old issue. We now use YAML for config files and model & dataset serialisation.

Overall the docs for those parts need a lot of work, but I think it's better to open a new issue or PR directly for that.

I'd also like to say that I'm not sure the way we handle YAML in Gammapy is good. We always go via hand-written `to_dict` and `from_dict` methods to convert Numpy arrays and sometimes Astropy objects like Angle, SkyCoord, Time. The alternative would be to use the approach from http://docs.astropy.org/en/stable/io/misc.html#module-astropy.io.misc.yaml or ASDF to register those kinds of objects with the YAML machinery, and then we wouldn't need the manual `to_dict` or `from_dict` methods.

But again: I think if someone thinks we should do YAML differently, they should open their own issue or PR in the future.
