### ISSUE TITLE
Improve IRF theory

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#3290]
This is TODO for the documentation. In IRFTheory
- both `PSFKernel` and `PSFMap` are both described simply as "a PSF that can be used to convolve ~gammapy.maps.WcsNDMap objects". A distinction between the two can be specified 
- For the edisp, documentation exists for `EnergyDispersion2D` and `EDispKernel` but nothing for `EDispKernelMap` or `EDispMap`

Creating this as a separate issue and linking from #3143

**Comment by adonath** [comment]
@AtreyeeS is this issue resolved by #3391?

**Comment by AtreyeeS** [comment]
Thanks to @LauraOlivera ! This issue is already resolved by #3391 
Closing this.
