### ISSUE TITLE
Support for energy dependent `RAD_MAX` point-like IRFs

### ISSUE THREAD

**Issue by maxnoe** [gammapy/gammapy#3296]
**Is your feature request related to a problem? Please describe.**

Gammapy currently seems to have no support for energy-depedent `RAD_MAX` for point-like IRFs as described in the DL3 format here:
https://open-gamma-ray-astro.github.io/gamma-astro-data-formats/irfs/point_like/index.html#rad-max-2d

**Describe the solution you'd like**

Add support for using the energy-dependent `RAD_MAX` table and corresponding IRFs.

**Describe alternatives you've considered**

No alternatives. Energy-dependent event selection is a needed feature for most if not all IACTs and point-like IRFs are much easier to handle/calculate when applicable. 

**Additional context**

At least LST, MAGIC and FACT would like to use gammapy with point-like IRFs with energy-dependent `RAD_MAX`

**Comment by chaimain** [comment]
Yes, we from LST would like to have this support as well, as we recently started producing standard DL3 files, with fixed selection cuts (gammaness and theta2) and would soon be moving towards producing IRFs with energy-dependent cuts.

**Comment by maxnoe** [comment]
Reading RAD_MAX_2D works with this now: https://github.com/gammapy/gammapy/pull/3515

**Comment by adonath** [comment]
I had the chance to talk to @registerrier yesterday about this and here are a few general comments / questions:
- Fully integrating this in the Gammapy API is hard: adding full support for energy dependent regions to `RegionGeom` with support for methods such as `RegionGeom.contains()`, `RegionGeom.plot()`, `RegionGeom.solid_angle()` and supporting serialisation is a lot of work. Currently there is no support in `regions` for array valued properties, so one would either need a custom class (such as `ArrayCircleSkyRegion`) or write a lot of `for` loops and declarative way such as `RegionGeom(regions, regions_axis=energy_axis)`. In general this would probably need a design document (PIG) and extensive review. If we decide to go for this, we should keep in mind to not only support the case, where regions are energy dependent but can vary with other axes as well.
- However getting this to work at all is simple.  It seems the only missing functionality is the possibility to bin events into a map with energy dependent region size and then it could just work with setting `RegionGeom(region=None)`. This could be written as a prototype in a single notebook.  My recommendation would be to start like this, use it as a basis for discussion and conclude from the prototype which additions to Gammapy are needed and reasonable.
- In addition to the `IRF.is_point_like` we probably need something like `IRF.has_varying_rad_max` to distinguish the case, where the rad max varies with energy.
- How is the region information translated between true and reconstructed energy? In GADF the rad max is given depending on reconstructed energy however the PSF containment in reconstructed energy depends on the assumed source spectrum. So I guess the effect is just neglected? But where is the information on the assumed source spectrum stored?

**Comment by maxnoe** [comment]
> But where is the information on the assumed source spectrum stored?

I don't understand where an assumed source spectrum enters here.

**Comment by maxnoe** [comment]
> How is the region information translated between true and reconstructed energy? I

Why is this necessary? You select events in reconstructed energy. There is no "region" in true energy since we are talking point-like analysis here.

**Comment by maxnoe** [comment]
I think the best solution here is to explicitly enable the point-like 1D spectral analysis without any regions. Just use positions and select events in radii around this position.

As you stated, forcing this simple approach into the gammapy framework for 3D full enclosure region based analysis will be hard to impossible.

There is a simple solution: don't. 

Point-Like analysis are much simpler. I think with two or three new makers, this can be solved easily. 

We need a background maker that uses reflected off *positions* (not regions!) and a spectrum dataset maker also using an on position.

Everything else is overkill and will not work / will force assumptions only valid for the 3D case on the much simpler, point-like 1D case.

**Comment by registerrier** [comment]
It seems we all agree on this. 

- energy dependent ON region size is meaningful only for pointlike analysis. We won't try to adapt the `RegionGeom` to account for varying region size.
- the current scheme should work well using the `RegionGeom`. My suggestion here would simply to use a `PointSkyRegion` for point-like analysis. This should allow using the `SpectrumDataset` exactly the same way with `RegionGeom` but still carry position information, contrary to using `region=None`.
- a specific reflected position maker is required indeed. Yet the question on how you handle the exclusion regions should be taken into account. I assume that you exclude a position based on the largest possible size of your RADMAX.
- One issue with have `RegionGeom=None` or use a `PointSkyRegion` is the absence of the provenance info on the actual radmax used. Maybe this implies that `SpectrumDataset` should carry the `RADMAX` along.
- We should then see, how the (pseudo)-pointlike analysis with full containment IRFs relates to the full pointlike analysis. 

Finally I think the point Axel wanted to make is also that having a working prototype first will help see the necessary updates/changes beyond the one we mentioned above.

**Comment by adonath** [comment]
> Why is this necessary? You select events in reconstructed energy. There is no "region" in true energy since we are talking point-like analysis here.

Yes, indeed. However what I meant was the following: the rad max is probably optimised for max. significance based on simulations with a certain spectrum. However because of the correlation between the energy and angular resolution I would expect the optimal value of rad max (or PSF containment) to depend on the source spectrum. But I guess this effect is completely negligible and just results in a slightly lower sensitivity. I just thought it might be good to store the info of the spectrum somewhere...

**Comment by adonath** [comment]
@registerrier and @maxnoe Just to clarify: I think having support for energy dependent region sizes, or in general region parameters that vary with extra axis for the `RegionGeom` object would be very nice! I can easily see how this could be useful for e.g. flux profile estimation as well. Also in terms of API consistency, code duplication and meta data handling it would the preferable solution. If we now consider re-implementing reflected region makers, or adding very specific rad max arguments to `SpectrumDataset`, it is not obvious to me that this saves us much work long-term. My point was mostly to just **start** with an independent prototype.

However yesterday I spent an afternoon to sketch some basics of supporting energy dependent region sizes in `RegionGeom`. See https://github.com/adonath/notebooks-public/blob/master/region-geom-array.ipynb When relying on Numpy broadcasting many things (such as `.solid_angle()`, `.bin_volume()` ) already work out of the box. Even this "toy" implementation already allows e.g. to integrate diffuse models with energy dependent region sizes, using `RegioGeom.get_wcs_coords_and_weights()`. Most of the code is introduced to circumvent the checks for scalar values of the `regions` package.

**Comment by maxnoe** [comment]
>  Yes, indeed. However what I meant was the following: the rad max is probably optimised for max. significance based on simulations with a certain spectrum.

Sure, but the same is true for a single rad max (even stronger, since you average all energies)

**Comment by maxnoe** [comment]
I guess the documentation update, @cosimoNigro #3712 ?

**Comment by chaimain** [comment]
Also a small thing #3792, Unless there is some ongoing work that I missed.

**Comment by adonath** [comment]
Anything left to be done here?

**Comment by maxnoe** [comment]
The plotting issue above
