### ISSUE TITLE
Will this Sherpa change cause problems for GammaPy?

### ISSUE THREAD

**Issue by DougBurke** [gammapy/gammapy#3298]
Sorry this is neither a bug report or a feature request...

I don't know how much you still use Sherpa, but I am proposing a change to how XSPEC models are evaluated that *might* impact GammaPy if you still use these models. The PR in question is https://github.com/sherpa/sherpa/pull/1112 if you need any more information.

**Comment by adonath** [comment]
Thanks a lot @DougBurke, right now there is no support for XSPEC models in Gammapy, so I think this change will not affect us...
