### ISSUE TITLE
Improve energy handling – take 2

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#331]
This is a continuation of #290 by @kingj90 ... some further steps to improve / clean up energy handling code in Gammapy.
- [ ] Change API everywhere to use new Energy handling
- [ ] Should `LogEnergyAxis` use `Energy`?

**Comment by kingj90** [comment]
How should I add the changelog entriy? Via a separate PR?

**Comment by cdeil** [comment]
I'll attach a commit here (turning this issue into a PR) and also add a changelog entry.

**Comment by cdeil** [comment]
I'm closing this old issue now. We should unify the axis handling for maps and IRFs and re-use the same axis class everywhere if possible, but I think it's better to have a new issue with a clear description what should be done.
