### ISSUE TITLE
The aeff-max option of the SafeMaskMaker leads to a crash for energy thresholds outside the true energy axis

### ISSUE THREAD

**Issue by luca-giunti** [gammapy/gammapy#3316]
**Gammapy version**
v0.18.2

**Bug description**
If the `aeff-percent` (by default 10%) value of the effective area is below the lower edge of the true energy axis, the `aeff-max` method of the `SafeMaskMaker` results in
```
ValueError                                Traceback (most recent call last)
<timed exec> in <module>

/home/luca/anaconda3/envs/gammapy-0.18.2/lib/python3.7/site-packages/gammapy/makers/safe.py in run(self, dataset, observation)
    219 
    220         if "aeff-max" in self.methods:
--> 221             mask_safe &= self.make_mask_energy_aeff_max(dataset)
    222 
    223         if "edisp-bias" in self.methods:

/home/luca/anaconda3/envs/gammapy-0.18.2/lib/python3.7/site-packages/gammapy/makers/safe.py in make_mask_energy_aeff_max(self, dataset)
    140         )
    141         aeff_thres = (self.aeff_percent / 100) * aeff.max_area
--> 142         energy_min = aeff.find_energy(aeff_thres)
    143         return geom.energy_mask(energy_min=energy_min)
    144 

/home/luca/anaconda3/envs/gammapy-0.18.2/lib/python3.7/site-packages/gammapy/irf/effective_area.py in find_energy(self, aeff, energy_min, energy_max)
    304 
    305         aeff_spectrum = TemplateSpectralModel(energy, self.data.data)
--> 306         return aeff_spectrum.inverse(aeff, energy_min=energy_min, energy_max=energy_max)
    307 
    308 

/home/luca/anaconda3/envs/gammapy-0.18.2/lib/python3.7/site-packages/gammapy/modeling/models/spectral.py in inverse(self, value, energy_min, energy_max)
    468 
    469             energy = scipy.optimize.brentq(
--> 470                 f, energy_min.to_value(eunit), energy_max.to_value(eunit)
    471             )
    472             energies.append(energy)

/home/luca/anaconda3/envs/gammapy-0.18.2/lib/python3.7/site-packages/scipy/optimize/zeros.py in brentq(f, a, b, args, xtol, rtol, maxiter, full_output, disp)
    778     if rtol < _rtol:
    779         raise ValueError("rtol too small (%g < %g)" % (rtol, _rtol))
--> 780     r = _zeros._brentq(f, a, b, xtol, rtol, maxiter, args, full_output, disp)
    781     return results_c(full_output, r)
    782 

ValueError: f(a) and f(b) must have different signs
```
I think in this case the solution would be simply catching the error and ignoring the `aeff-max` method.

A few more thoughts:
- I suspect that a similar issue (and proposed solution) can apply to the `bkg-peak` and `edisp-bias` method, as they would probably crash when the found threshold energy is outside the true energy axis (but I haven't checked). So I imagine that the error catching should be done by the `SafeMaskMaker`, for all selected method.
- Another possible bug (that was introduced in the `dev` version): [here](https://github.com/gammapy/gammapy/blob/ffaa4bc066b35e022d76aeeb378ffd14af5be7d3/gammapy/makers/safe.py#L140) we don't pass any `energy_min`/`energy_max`, therefore the default values of the `inverse` method (energy_min=0.1 * u.TeV, energy_max=100 * u.TeV) are used. This seems arbitrary, I guess we should pass the min and max true energy edges instead. I think this was correctly handled in v0.18.2: https://github.com/gammapy/gammapy/blob/1d4bcee496f6884bd99a2476d281fec7f785a23a/gammapy/irf/effective_area.py#L306

**To Reproduce**
Just add the `aeff-percent` option to the `SafeMaskMaker` in https://docs.gammapy.org/0.18.2/tutorials/analysis_2.html. You will get a crash in cell [11], that can be fixed by lowering the energy true lower edge from 0.5 to e.g. 0.1 deg in cell [7]

**Comment by QRemy** [comment]
This is related to the issues discussed this morning on the dev call, for now the bracketing intervals given to the brentq method are not always valid. This should be addressed by #3300 and follow-up PRs.
