### ISSUE TITLE
Solve FluxPointsEstimator convergence issues

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#3329]
The `FluxPointsEstimator` allows now by default negative values for the `norm` parameter.
This sometimes lead to strange behavior for users, namely:
- non convergence when the `norm` become <<0. This might be due to the fact that the `stat_sum` is 0 when negative counts become negative.
- negative upper limits are often difficult to interpret.

We can by default compute upper limits above 0 and not the minimum.
 
We can also find a solution to let the minimizer get out of the parameter space where the model predicts negative total counts.

**Comment by adonath** [comment]
Solved by #3342.

**Comment by registerrier** [comment]
To summarize the issue for reference. In the absence of a truncation value for the `npred` the fit statistic could become artificially negative when the minimizer reaches a region when `npred` are becoming negative. See the figure below, showing stat values for different norm parameters (from flux points). For readability, all stats minima are set to 0 and maxima at 1:
![Unknown-3](https://user-images.githubusercontent.com/5047091/118098541-51198e00-b3d4-11eb-8076-b6424947c235.png)
 With the truncation value introduced in #3342 , this is changed to the following for the 0.5 TeV point. The minimum is clearly above 0 as expected. 
![Unknown-4](https://user-images.githubusercontent.com/5047091/118098843-b8cfd900-b3d4-11eb-83f1-7201f9dbaded.png)
For a point having a real minimum below 0, like the 15 TeV one above, the profile is unchanged:
![Unknown-6](https://user-images.githubusercontent.com/5047091/118098988-eddc2b80-b3d4-11eb-9bfe-e4cf0d27c56f.png)
