### ISSUE TITLE
Improve cube bg model production

### ISSUE THREAD

**Issue by mapazarr** [gammapy/gammapy#333]
The  cube bg model production is working. Still there is some things to improve:
- [x] investigate the steepening of the bg rate for reconstructed models: https://hess-confluence.desy.de/confluence/display/HESS/HESS+Open+Source+Tools+-+HOWTO+create+cube+background+models+using+Gammapy#HESSOpenSourceTools-HOWTOcreatecubebackgroundmodelsusingGammapy-Comparisontrue/reco
- [ ] add a cube.spectral_index method (example: https://gammapy.readthedocs.org/en/latest/api/gammapy.data.SpectralCube.html#gammapy.data.SpectralCube.spectral_index) and cube.plot_spectral_index, to calculate the spectral index at a given (x, y) position and plot it as a function of the energy
- [ ] add a test producing 1 true bg cube model, 1 reco bg cube model, and testing that they roughly agree (i.e. similar spectral slope), see the following scripts:
  - https://github.com/gammapy/gammapy/blob/master/examples/make_bg_cube_models_true_reco.py
  - https://github.com/gammapy/gammapy/blob/master/examples/plot_bg_cube_model_comparison.py
- [ ] split the inline command into 3 commands: find-obs, define-obs-groups, make-bg-cube-models
- [ ] subdivide the make-bg-cube-models command in 2 parts: make event/livetime cubes, produce bg cube models with/out smoothing
- [ ] rename find_obs -> select_obs (also in the high-level docs)
- [ ] add arguments to the inline tool to customize cube binning and smoothing
- [ ] add arguments to the inline tool to customize group binning
- [ ] make observation list converter functions members of ObservationTable
- [ ] investigate whether the energy threshold is important for the binning/filling of the cubes
- [ ] investigate more sophisticated methods for smoothing the bg cube models
- [ ] add methods to interpolate bg cube models
- [ ] add methods to project bg cube models from detector to celestial coordinates
- [ ] filter out possible sources in the data (leave as TODO/issue for a future PR)
- [ ] better integration of dataset production and true cube bg model production: the model used should be improved and shared between both sets of tools (see #335)
- [ ] Move 2D smooth method: https://github.com/gammapy/gammapy/pull/319#discussion-diff-36718246
- [ ] Error in fits: https://github.com/gammapy/gammapy/pull/319#issuecomment-130241940, https://gist.github.com/cdeil/8665a22897c6ebe71680#file-gistfile1-txt-L1
- [ ] Warning in fits: https://github.com/gammapy/gammapy/pull/319#issuecomment-132888914
- [ ] Move output dir creation to a separate function: https://github.com/gammapy/gammapy/pull/319#discussion-diff-37477370
- [ ] Revise logging: https://github.com/gammapy/gammapy/pull/319#discussion-diff-37547764

This issue lists the open tasks left over from the work in PR #319. Since some of the tasks are quite large (for instance revise smoothing methods), it should trigger the opening of several PRs.

**Comment by mapazarr** [comment]
About the error in fits: https://github.com/gammapy/gammapy/pull/319#issuecomment-130241940, https://gist.github.com/cdeil/8665a22897c6ebe71680#file-gistfile1-txt-L1

This is probably due to the fact that `X, Y` axes are defined via a `WCS` object, but `energy` is not. In any case, this only affects to the `image` format, which should be used for visualization in **DS9**; regular analysis should use the `table` format, which is unaffected, since no axes are defined via `WCS`.

**Comment by mapazarr** [comment]
Steepening of the bg rate studied in PR #338

**Comment by mapazarr** [comment]
Question: would it be useful to have a fits to root exporter for the bg cubes? Maybe this would help to get people working in root-based analysis interested in using the software and not reinvent the wheel?

**Comment by cdeil** [comment]
> would it be useful to have a fits to root exporter for the bg cubes?

I highly doubt anyone would take the time to use that in the HESS software, so it would be a waste of our time. Open-source analysis and open FITS data and CTA is coming ... it'll take a while, but (somewhat surprisingly) no-one in CTA is proposing ROOT.

**Comment by cdeil** [comment]
Moving milestone to 0.7 (I'll make the 0.6 release tomorrow)

**Comment by cdeil** [comment]
I'm closing this old issue from 2015 with a long list of TODOs (many of which were done by @leajouvin in 2016 or 2017).

Note that the old background modeling code was removed for now (#1515), and we have an open issue to bring it back soon (#1516).
