### ISSUE TITLE
Unit consistency when plotting flux points and spectral models together

### ISSUE THREAD

**Issue by LauraOlivera** [gammapy/gammapy#3359]
**Gammapy version**
I am using `0.18.dev584+g3a1807fba`

**Bug description**
When plotting a spectral model on top of a `FluxPointsDataset.plot_fit()` the units in the axis change but not the value being plotted.
Taking a snippet from the `FluxPointsDataset` tests file we define one:
```python3
from gammapy.estimators import FluxPoints
from gammapy.modeling.models import LogParabolaSpectralModel, PowerLawSpectralModel, SkyModel
from astropy.table import Table
import matplotlib.pyplot as plt
from gammapy.datasets import FluxPointsDataset
from astropy import units as u


path = "$GAMMAPY_DATA/tests/spectrum/flux_points/diff_flux_points.fits"
data = FluxPoints.read(path)
data.table["e_ref"] = data.energy_ref.to("TeV")
model = SkyModel(
    spectral_model=PowerLawSpectralModel(
        index=2.3, amplitude="2e-13 cm-2 s-1 TeV-1", reference="1 TeV"
    )
)

obs_table = Table()
obs_table["TELESCOP"] = ["CTA"]
obs_table["OBS_ID"] = ["0001"]
obs_table["INSTRUME"] = ["South_Z20_50h"]

dataset = FluxPointsDataset(model, data, meta_table=obs_table) 
```
we have created a flux points dataset with flux points and a model. Doing `dataset.plot_fit()` results in a plot with flux units of `erg · cm-2 · s-1` by default:
```python3
ax1, ax2 = dataset.plot_fit()
ax1.set_ylim(1e-15,)
ax1.grid(which='both')
plt.show()
```
![image](https://user-images.githubusercontent.com/22521727/118002386-da36b380-b347-11eb-98a7-9cdfe090243b.png)

If I now want to plot **the same model** on the same plot:
```python3
ax_spectrum, ax_residuals = dataset.plot_fit()
model.spectral_model.plot(ax = ax_spectrum, energy_range=(1e-4, 5e-1) * u.TeV, energy_power=2)
ax_spectrum.set_ylim(1e-15,)
ax_spectrum.grid(which='both')

plt.show()
```
![image](https://user-images.githubusercontent.com/22521727/118002247-bc694e80-b347-11eb-9f36-c801804130bc.png)

The default unit of `model.spectral_model.plot` is `TeV · cm-2 · s-1`, and so the axis unit changes (**why? I am passing the ax argument**) but neither the orange line or the flux points change, leading to a mismatch in the green and orange curves, which should be the same.

Since no error is thrown when trying to plot both things in the same plot, I think the units should be treated internally so that the result is consistent. The plot above leads to the conclusion that the two models are incompatible when they are actually the same. Maybe I am doing something the way it isn't intended, but in that case the result should still be a warning of some sort.

**Comment by adonath** [comment]
Thanks @LauraOlivera! I think it is possible to fix this manually by providing the same flux unit as argument:
```python3
ax_spectrum, ax_residuals = dataset.plot_fit(
    kwargs_spectrum={"flux_unit": "TeV-1 cm-2 s-1"}
)
model.spectral_model.plot(
    ax=ax_spectrum,
    energy_range=(1e-4, 5e-1) * u.TeV,
    energy_power=2,
    flux_unit="TeV-1 cm-2 s-1"
)
ax_spectrum.set_ylim(1e-15,)
ax_spectrum.grid(which='both')

plt.show()
```

But I agree it would be way better to handle this in Gammapy internally. However I'm not a 100% whether this is possible at all, because by default `matplotlib` does not know about any units. Maybe Astropy's `quantity_support()` helps:

```python3
import matplotlib.pyplot as plt
from astropy import units as u
from astropy.visualization import quantity_support
import numpy as np

time = np.linspace(0, 100, 10) * u.s

velocity_1 = 5 * u.m / u.s
distance_1 = velocity_1 * time 

velocity_2 = 23 * u.km / u.h
distance_2 = velocity_2 * time 

with quantity_support():
    plt.plot(time, distance_1, label="velocity 1")

with quantity_support():
    plt.plot(time, distance_2, label="velocity 2")

plt.legend()
```

**Comment by LauraOlivera** [comment]
Yes, I know how to fix it, but the issue is that if you don't - for example - expect the two lines to match, you might not notice that this happened at all(you would need to know that the default units for each plot type are different). Maybe unifying the default units would help?

I'l take a look at  `quantity_support()`... thanks!

**Comment by adonath** [comment]
@LauraOlivera Can you please check whether #3438 resolves the issue?

**Comment by adonath** [comment]
Here is the updated code:

```python3
from gammapy.estimators import FluxPoints
from gammapy.modeling.models import LogParabolaSpectralModel, PowerLawSpectralModel, SkyModel
from astropy.table import Table
import matplotlib.pyplot as plt
from gammapy.datasets import FluxPointsDataset
from astropy import units as u


path = "$GAMMAPY_DATA/tests/spectrum/flux_points/diff_flux_points.fits"
data = FluxPoints.read(path)
model = SkyModel(
    spectral_model=PowerLawSpectralModel(
        index=2.3, amplitude="2e-13 cm-2 s-1 TeV-1", reference="1 TeV"
    )
)

obs_table = Table()
obs_table["TELESCOP"] = ["CTA"]
obs_table["OBS_ID"] = ["0001"]
obs_table["INSTRUME"] = ["South_Z20_50h"]

dataset = FluxPointsDataset(model, data, meta_table=obs_table)

ax_spectrum, ax_residuals = dataset.plot_fit()
model.spectral_model.plot(ax=ax_spectrum, energy_bounds=(1e-4, 5e-1) * u.TeV, sed_type="e2dnde")
ax_spectrum.set_ylim(1e-13,)
ax_spectrum.grid(which='both')

plt.show()
```
And resulting plot:
![image](https://user-images.githubusercontent.com/3715928/128362285-5dd02c41-3712-4132-b462-44ccbed48af1.png)

The models are on top of each other as expected. I'll close the issue now, @LauraOlivera please re-open if you find anything else..
