### ISSUE TITLE
Region handling in Gammapy

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#336]
In Gammapy we currently have some region handling code in various places, e.g. see
 [docs search for region](https://gammapy.readthedocs.org/en/latest/search.html?q=region&check_keywords=yes&area=default), [code search for select_sky_box](https://github.com/gammapy/gammapy/search?utf8=%E2%9C%93&q=select_sky_box&type=Code), code for ring and reflected regions in [gammapy.background](https://gammapy.readthedocs.org/en/latest/background/index.html), ...

It's mostly a mess and there's currently no clear concept for regions in Gammapy.

Probably the solution is to use a regions library in Gammapy. Options:
- [CIAO regions python package](http://cxc.harvard.edu/ciao/ahelp/region.html) that ships with and is used by Sherpa.
- These are all work in progress, but might combine into one great Astropy-affiliated regions package, discussions via email ongoing: https://github.com/astropy/pyregion, https://github.com/astropy/regions, https://github.com/ericmandel/regions

This seems clear to me:
- Region-based analysis will remain important and regions are also needed in various places (e.g. for run and catalog selection, ...).
- We probably want to read / write regions to ds9 or CIAO format (the differences are small, I think, for our needs).
- The regions package, especially parsing is not something we want to implement in Gammapy.
- But we do probably want an object-oriented regions package, so that we can programatically create e.g. reflected regions.
- Most likely we do _not_ want to do what's in the HESS software, which is regions on the sphere. The problem with that is that it's a bit complicated to implement, slower, and no-one else does it that way, i.e. ds9 can't even display those regions accurately.
- Instead we do want to do what ds9 / CIAO does: cartesian regions, with the convenience of being able to specify points on the sphere as well as angles and a WCS object to translate to pixel coordinates.

@kingj90 Maybe we can together look at the Sherpa regions package and the to-be Astropy regions package a bit, and think about use cases we have in Gammapy and what it would take to make those work nicely for us / whether it's useful enough to use them?

**Comment by cdeil** [comment]
By now the plan how to do region handling in Gammapy is clear:
* Use https://github.com/astropy/regions, which will become `astropy.regions` at some point.
* For now bundle it in `gammapy.extern.regions`, update from time to time.

So @joleroi - I'm assigning this issue to you (doesn't mean you have to do all the work) and to the `0.5` milestone.

I would suggest keeping this issue open as a high-level overview what needs to be done:

- [ ] Remove `gammapy/region` from the code and docs
- [ ] Write some docs for http://astropy-regions.readthedocs.io/
- [ ] Integrate regions with `EventList` and `SourceCatalog` and `SkyMap` and `SkyCube` (remove the custom cone and rectangle filtering code we have). (needs some thought / discussion)
- [ ] Write some high-level docs in Gammapy (not sure where) with examples how to work with regions and `EventList`, `SourceCatalog`, `SkyMap` and `SkyCube` (maybe other objects also like `ObservationTable`).

**Comment by joleroi** [comment]
I completely agree, thanks!

**Comment by cdeil** [comment]
I'm assigning this issue to myself.

The plan has changed a bit.
I'll make an 0.1 release for `astropy/regions` on Saturday:
https://github.com/astropy/regions/milestone/1
and then we'll add it as a dependency for Gammapy before cutting the Gammapy 0.5 release.

**Comment by cdeil** [comment]
I'm postponing this to the 0.6 milestone.

**Comment by cdeil** [comment]
This is a very old issue. The plan is to fully develop http://astropy-regions.readthedocs.io/ and use that in Gammapy. Keeping open for now with the "cleanup" label, because we still have to change Gammapy methods to use regions in several places (see comments above).

**Comment by cdeil** [comment]
Let's continue this discussion in a PIG: #2129
