### ISSUE TITLE
Parameter type not assigned in PiecewiseNormSpectralModel

### ISSUE THREAD

**Issue by judevin** [gammapy/gammapy#3376]
**Gammapy version**
0.18.2

**Bug description**
When using the PiecewiseNormSpectralModel for the FoVBagroundModel, the parameter type is not assigned (which should be "spectral"). That creates problems for serialization due to the parameters_unique_names which uses the par.type and the error is therefore "expected str instance, NoneType found".

**Expected behavior**
The par.type assigned to "spectral"

**To Reproduce**

Example:
```python3
models_bkg = Models([])
Custom_model = PiecewiseNormSpectralModel(energy = geom.axes["energy"].edges)
bkg_model = FoVBackgroundModel(dataset_name=dataset.name, spectral_model=Custom_model)
dataset.models = bkg_models
dataset = maker_bkg.run(dataset)
model_bkg.append(dataset.background_model)
models_bkg.write("./Models_bkg.yaml")
```
```
Error:
~/opt/anaconda3/envs/gammapy-0.18.2/lib/python3.7/site-packages/gammapy/modeling/models/core.py in write(self, path, overwrite, full_output, write_covariance)
    335                 format="ascii.fixed_width", delimiter="|", overwrite=overwrite
    336             )
--> 337             self.write_covariance(base_path / filecovar, **kwargs)
    338             self._covar_file = filecovar
    339 

~/opt/anaconda3/envs/gammapy-0.18.2/lib/python3.7/site-packages/gammapy/modeling/models/core.py in write_covariance(self, filename, **kwargs)
    404 
    405         """
--> 406         names = self.parameters_unique_names
    407         table = Table()
    408         table["Parameters"] = names

~/opt/anaconda3/envs/gammapy-0.18.2/lib/python3.7/site-packages/gammapy/modeling/models/core.py in parameters_unique_names(self)
    248             for par in model.parameters:
    249                 components = [model.name, par.type, par.name]
--> 250                 name = ".".join(components)
    251                 names.append(name)
    252 

TypeError: sequence item 1: expected str instance, NoneType found
```
**Other information**
For the time being, the problem can be bypassed with:

for par in models_bkg.parameters:
    par._type = 'spectral'

**Comment by adonath** [comment]
Thanks a lot @judevin, I can confirm this bug! On closer inspection this might be an issue that affects all models with dynamically generated parameters, such as `NaimaSpectralModel` as well. The fix is exactly as you proposed to define the parameter type "by hand" for these cases...

**Comment by adonath** [comment]
Let us know if you are interested to work on the issue yourself...
