### ISSUE TITLE
Show reference point in WcsGeom.__repr__

### ISSUE THREAD

**Issue by adonath** [gammapy/gammapy#3384]
Currently when printing a `WcsGeom` the reference point is not shown in the print out, so two `WcsGeom` can look equivalent in the printout, while they are actually not equivalent. Here is an example to reproduce:
```python3
from gammapy.maps import WcsGeom

geom_1 = WcsGeom.create(skydir=(0, 0), width=10)
geom_2 = WcsGeom.create(skydir=(4.75, -4.75), width=10, refpix=(1, 1))

print(geom_1)
print(geom_2)
print(geom_1 == geom_2)
``` 
Which prints:
```
WcsGeom

	axes       : ['lon', 'lat']
	shape      : (20, 20)
	ndim       : 2
	frame      : icrs
	projection : CAR
	center     : 0.0 deg, 0.0 deg
	width      : 10.0 deg x 10.0 deg

WcsGeom

	axes       : ['lon', 'lat']
	shape      : (20, 20)
	ndim       : 2
	frame      : icrs
	projection : CAR
	center     : 0.0 deg, 0.0 deg
	width      : 10.0 deg x 10.0 deg

False
```
A good solution would be to include the reference point of the WCS projection in the printout.

**Comment by AtreyeeS** [comment]
It would also be nice to be able to see pinpoint exactly where exactly the two `geoms` differ. 
Often, the `print(geom)` returns the same info, but is actually different.
eg: if one non-spatial axis is node centered, other one is edge centered
In this case, one has to test explicitly `geom1._node_type == geom2._node_type` or `geom1._interp == geom2._interp`
This is not very nice, it basically duplicates code inside `Geom.__eq__`

But I do not know a good way to provide this. Maybe implementing a `MapAxis.__eq__` can help?

**Comment by adonath** [comment]
@AtreyeeS `MapAxis.__eq__` already exists: https://github.com/gammapy/gammapy/blob/master/gammapy/maps/geom.py#L828
I guess the proposal is to improve the error messages...

**Comment by AtreyeeS** [comment]
Yes indeed - what I meant is that `print(geom)` prints much less info than what is checked in `Geom.__eq__`, so it becomes difficult to know why the equality failed.
