### ISSUE TITLE
`Dataset.npred_signal()` should take model name

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#3386]
`Dataset.npred_signal()` takes a model as argument, whereas in most other places (eg:`FluxPointEstimator` we access models by their names. This create some confusion.

@adonath shall I put in a PR to change this?

**Comment by adonath** [comment]
Thanks @AtreyeeS! I agree the string is the more consistent choice here!

**Comment by adonath** [comment]
@AtreyeeS Can you work this? Shouldn't be much more than half an hour of work...
