### ISSUE TITLE
MapDataset._counts_data  property should be reset when counts are modified

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#3387]
The `MapDataset._counts_data` property is used to convert `counts` to `float` for likelihood calculations. 
It is currently defined as `@lazyproperty`. The direct consequence is that when `counts` is modified (e.g. by `MapDataset.fake`) the counts data actually used for likelihood calculations are silently different from the ones actually defined on the `MapDataset`. 
This could be solved by adding a getter/setter definition for `counts` that would reset the lazy property.

**Comment by adonath** [comment]
The `.counts` property currently uses the `LazyFitsData` descriptor. This requires a little workaround for the setter, e.g. by introducing a hidden `_counts` and `_counts_data` attribute.
