### ISSUE TITLE
to_ud_graded

### ISSUE THREAD

**Issue by rodiram** [gammapy/gammapy#3410]
I may be misunderstanding the command to_ud_graded with the option preserve_counts, I find that when I dowgrade a map, the number of counts is preserved but not when I upgrade it, am I missing something ?
Thank you

energy_axis = MapAxis.from_bounds(10., 100., 3, interp='log', name='energy', unit='MeV')
geom = HpxGeom(2, frame="galactic",axes=[energy_axis]) 
data = numpy.ones([3,12*2*2])
m = HpxNDMap(geom,data)

print(m.data[0].sum())  # 48
m2=m.to_ud_graded(1,preserve_counts=True)  
print(m2.data[0].sum()) # 48
m2=m.to_ud_graded(4,preserve_counts=True)
print(m2.data[0].sum()) # 192 # here , should not it be 48 too ?
m3=healpy.ud_grade(m.data[0],4,power=-2 ) 
print(m3.sum()) # 48

**Comment by adonath** [comment]
Thanks @rodiram! Meanwhile the `.to_ud_graded()` method  has been removed (see https://github.com/gammapy/gammapy/commit/b3559eef5f0bcebfb1ddd2dcefc05ffd5dde4df5). The equivalent functionality is provided by `.downsample()` and `.upsample()`, which both feature the `preserve_counts` keyword. This would be the recommended workaround in your case as well.

**Comment by rodiram** [comment]
Thank you for this precision, it indeed works. However, I suggest you don't remove the function to_ud_graded, most of the time one does not care if the map is downgraded or upgraded, the important point is just the change of NSIDE to match another map for example.

**Comment by adonath** [comment]
@rodiram I agree this is convenient. We already have `HpxGeom.to_nside()` so we could just mirror this and re-introduce `HpxNDMap.to_nside(nside, preserve_counts=)`, which internally calls `.downsample() / upsample()`.

**Comment by rodiram** [comment]
That would be perfect.

**Comment by adonath** [comment]
@rodiram Please check and let me know if you have any comments on #3422.

**Comment by adonath** [comment]
Addressed in #3422.
