### ISSUE TITLE
HpxMap read wrong coord and cannot find the right peak

### ISSUE THREAD

**Issue by jlzhang001** [gammapy/gammapy#3414]
**Gammapy version**
System:

        python_executable      : /public/home/jlzhang/anaconda3/envs/pipthreeML/bin/python 
        python_version         : 3.7.10     
        machine                : x86_64     
        system                 : Linux      

Gammapy package:

        version                : 0.18.2     
        path                   : /public/home/jlzhang/anaconda3/envs/pipthreeML/lib/python3.7/site-packages/gammapy 

Other packages:

        numpy                  : 1.20.3     
        scipy                  : 1.6.3      
        astropy                : 4.2.1      
        regions                : 0.4        
        click                  : 8.0.1      
        yaml                   : 5.4.1      
        IPython                : 7.24.0     
        jupyterlab             : not installed 
        matplotlib             : 3.4.2      
        pandas                 : 1.2.4      
        healpy                 : not installed 
        iminuit                : 2.6.1      
        sherpa                 : not installed 
        naima                  : not installed 
        emcee                  : 3.0.2      
        corner                 : 2.2.1      
        parfive                : 1.3.0      

Gammapy environment variables:

        GAMMAPY_DATA           : /public/home/jlzhang/hawc/gammapy-tutorials/datasets 

**Bug description**
A short description what the bug is (usually 1-2 sentences)
I have a hpx all sky map, HpxMap read wrong coord and cann't find the right peak, only find the pixel around one source

**Expected behavior**

read HpxMap with right coord and find all the peaks in the sky map

**To Reproduce**
Steps to reproduce the behavior.

```python3
import healpy as hp
import numpy as np
from gammapy.maps import HpxGeom, HpxNDMap, HpxMap
from gammapy.estimators.utils import find_peaks
import matplotlib.pyplot as plt
sig = hp.read_map('skymap.fits') #which is a healpix all sky map, NSIDE=1024

m = HpxMap.create(nside=1024, nest=False,frame="icrs")
m.data=sig
m_wcs=m.to_wcs()
m_wcs.plot(cmap='nipy_spectral_r')
plt.show()
sources = find_peaks(m_wcs, threshold=5, min_distance="1.00 deg")
print(sources)
```

output:
```
value   x    y      ra      dec   
                   deg      deg   
------ ---- ---- -------- --------
6.3466 8234 9068 83.67101 22.01225
6.3466 8233 9068 83.68506 22.01175
6.3466 8231 9064 83.68985 21.96360
6.3466 8232 9064 83.67580 21.96410
6.3466 8233 9064 83.66175 21.96460
6.3466 8231 9065 83.69567 21.97539
6.3466 8232 9065 83.68162 21.97589
6.3466 8233 9065 83.66757 21.97639
6.3466 8234 9065 83.65353 21.97689
6.3466 8235 9065 83.63948 21.97739
6.3466 8231 9066 83.70150 21.98717
6.3466 8232 9066 83.68745 21.98768
6.3466 8233 9066 83.67340 21.98818
6.3466 8234 9066 83.65935 21.98868
6.3466 8235 9066 83.64530 21.98918
6.3466 8232 9067 83.69328 21.99946
6.3466 8233 9067 83.67923 21.99996
6.3466 8234 9067 83.66518 22.00047
6.3466 8235 9067 83.65113 22.00097
6.3466 8232 9063 83.66998 21.95231
```
<img width="621" alt="gammapy1" src="https://user-images.githubusercontent.com/17774721/124700968-543a8180-df20-11eb-9a27-4765a77713d3.png">

**Other information**
Any other information you think will be useful for us to fix the issue can go here.

**Comment by adonath** [comment]
Thanks @jlzhang001!

Looking at the output of the `find_peaks()`it seems it's not the exact same pixel. And also looking at the picture you provide I don't see any reasonable structure in the image, are you sure it's the correct picture?

**Comment by jlzhang001** [comment]
> Thanks @jlzhang001!
> 
> Looking at the output of the `find_peaks()`it seems it's not the exact same pixel. And also looking at the picture you provide I don't see any reasonable structure in the image, are you sure it's the correct picture?

Yes, It's not the some pixel.  It's all the pixel of Crab(83.6,22.0). I think find_peaks() should only show 1 peak pixel, not all the pixel of one star. I change the min_distance from "0.25 deg" to "20 deg", it also give the same source several times!


There are stars in the data. If I set the right vmin and vmax in plot, it shows correct picture.

**Comment by adonath** [comment]
@jlzhang001 Not that `.to_wcs()` does a simple oversampling of the healpix map to a was grid, so one healpix pixels is split in to multiple wcs pixels, possibly containing the same value. You could try to interpolate onto a wcs map instead. This is shown e.g. here https://docs.gammapy.org/0.18.2/tutorials/fermi_lat.html#Exposure.

**Comment by QRemy** [comment]
`find_peaks` relies on [scipy.ndimage.maximum_filter](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.maximum_filter.html) that looks for local maxima in a window of a given size. If two nearby pixels have the same value they will both be a local maximum in their respective window so changing min_distance, that control the windows size, won't change anything in that case.

In order to avoid having pixels with the exact same value, you could try to  smooth the data as suggested in the docstring, see `help(find_peaks)`. Alternatively you could add random noise of very small amplitude to the image before running find_peaks.

@adonath `find_peak` no longer appears in the documentation, I could fix this. I also have a de-duplicate function that could go into gammapy for these kind of cases, but I would keep it separated from `find_peaks` that should still follow the behaviour of the maximum_filter.

**Comment by adonath** [comment]
@QRemy `find_peaks` is basically copied over from https://photutils.readthedocs.io/en/stable/api/photutils.detection.find_peaks.html?highlight=find_peaks. We just have this to avoid the additional dependency on `photutils`. So I think we should not extend / fix the functionality in Gammapy...

@jlzhang001 You could try the `photutils` method instead and see if it suffers from the same behaviour.

**Comment by jlzhang001** [comment]
@adonath @QRemy When I use interp_to_geom(), there is only on peak  for one star!  Now the problem is solved! Thanks a lot.
