### ISSUE TITLE
Generalise the use of gammapy.background.Cube

### ISSUE THREAD

**Issue by mapazarr** [gammapy/gammapy#344]
The [gammapy.background.Cube](http://gammapy.readthedocs.org/en/latest/api/gammapy.background.Cube.html) class
is a generic container class for cube data. It should be used for all cubes in Gammapy.

For instance the [gammapy.data.SpectralCube](http://gammapy.readthedocs.org/en/latest/api/gammapy.data.SpectralCube.html) class
could benefit from this container class, which has some of its basic functionality better implemented and tested.

In addition, the background cubes [gammapy.background.CubeBackgroundModel](http://gammapy.readthedocs.org/en/latest/api/gammapy.background.CubeBackgroundModel.html)
could benefit from some of the methods of `gammapy.data.SpectralCube`, like for instance [spectral_index](https://gammapy.readthedocs.org/en/latest/api/gammapy.data.SpectralCube.html#gammapy.data.SpectralCube.spectral_index)
So, some of the functionality could be moved from `gammapy.data.SpectralCube` to `gammapy.background.Cube`.

Maybe the `gammapy.background.Cube` class should be moved to a more generic place than the background module.

Task list:
- [ ] move `gammapy.background.Cube` class to a central place.
- [ ] make `gammapy.data.SpectralCube` a subclass of `gammapy.background.Cube` or contain (a few?) objects of type `gammapy.background.Cube`, similar to `gammapy.background.CubeBackgroundModel`.
- [ ] move some of the functionality from  `gammapy.data.SpectralCube` to `gammapy.background.Cube`

**Comment by cdeil** [comment]
I agree we need to find a way to share code between the cube classes (and also e.g. the IRF classes, i.e. in other parts of Gammapy).

As mentioned in #121, one possibility is to sub-class `NDArray` and then either use a class hierarchy or a  few configurable classes to cover the various use cases.

This needs thought and discussion and making a concrete plan, which is already a significant time investment (a few days). So if someone has time for this, please comment here or on the mailing list and we'll get the ball rolling.

There might also be opportunities for small refactorings, e.g. by splitting out computations like spectral index that Manuel mentioned into functions, that are then called from the various classes where it's needed. For such things, of course, pull requests are welcome any time!

**Comment by cdeil** [comment]
We now have very general map classes in gammapy.maps, and also the gammapy.irf classes have been rewritten in the past years since this issue was filed. Closing.
