### ISSUE TITLE
Add MapDataset.peek()

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#3499]
As pointed out by @registerrier in #3488 , it will be nice to have a `MapDataset.peek()` similar to `SpectrumDataset.peek()`.
We can plot, eg: `dataset.counts.sum_over_axis()`, `dataset.excess.sum_over_axis()` and `dataset.exposure.sum_over_axis()`

Adding this as a reminder issue for now

**Comment by adonath** [comment]
Addressed by #3576. For improvements we can make a new issue.
