### ISSUE TITLE
Add example for tying parameters

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#3509]
It is probably useful to show an example of how to tie parameters together, maybe in the `models` notebook, and add a link from the **HowTo** 
@QRemy did an efficient implementation here
https://github.com/gammapy/gammapy/blob/59dd69e3e00eb04b9e6af2788cac6f48f5d6e650/gammapy/catalog/hess.py#L579

but I do not know if its self-explanatory to external users

**Comment by QRemy** [comment]
The simplest use case is to do `model2.x = model1.x` with `x` a parameter attribute (maybe we should only document this way).

The example above is more complicated as you want to loop over `model.parameters` without writing explicitly the attribute name. 

An other option is to copy  the parameter entry in the .yaml file and the add the link tag  by hand,  but you have to follow the convention `link : {parameter.name}@{some_unique_id}`

**Comment by AtreyeeS** [comment]
Sounds good to me!

**Comment by AtreyeeS** [comment]
Closed by #3513
