### ISSUE TITLE
Rely more on Models.to_parameters_table()

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#3524]
In the current documentation and tutorials, all `Parameters` exploration after a fit is done using `FitResult.parameters.to_table()`. 

I think this hides other functionalities such as `Models.to_parameters_table()` which provides more complete informations to the users. In particular, it provides the name of the parent model for each parameter. When people perform multi-component fitting finding which parameter correspond to which model is often an issue.

I propose to replace most calls to `FitResult.parameters.to_table()` with calls to `Models.to_parameters_table()` in the tutorials.
Opinions @AtreyeeS @QRemy @adonath @luca-giunti and all?

**Comment by AtreyeeS** [comment]
Strongly agree! In fact, with result now being a dictionary, `result["optimize_result"].parameters.to_table()` seems rather unintuitive. I much prefer to show, eg

```
for m in stacked.models:
    print(m.name, "\n")
    m.parameters.to_table().pprint_all()
```
