### ISSUE TITLE
Reintroduce `__init__` methods for IRFs

### ISSUE THREAD

**Issue by maxnoe** [gammapy/gammapy#3539]
With the refactoring of the IRF classes to have a common IRF base class, all `__init__` methods that took keyword arguments were removed, which breaks compatibility with 0.18, I'd argue unnecessarily.

We should add the `__init__` methods back, e.g. for `EffectiveArea2D`:

```
def __init__(self, energy_axis, offset_axis, aeff, **kwargs):
    super()._init_(axes=[energy_axis, offset_axis], data=aeff, **kwargs)
```

**Comment by adonath** [comment]
I would argue for "normal users" it is very rare to instantiate an IRF on its own, for "power users" or developers this change is simple enough to not cause any major refactoring issues. I think the current implementation is cleaner, more flexible and reduces code duplication. There are many other cases, where the next release will be backwards incompatible. Supporting backwards compatibility requires more development resources that we currentlty do not really have. The priority is rather to arrive at a stable API as fast as possible and then tag the v1.0 label. Subsequent version of v1.0 will be backwards compatible then...

**Comment by adonath** [comment]
Just for completeness:

Old init:
```python3
aeff = EffectiveArea2D( 
    energy_axis_true=energy_axis_true,
    offset_axis=offset_axis,
    data=data,
    meta=None,
    interp_kwargs=None,
)
```

New init:
```python3
aeff = EffectiveArea2D( 
    axes=[energy_axis_true, offset_axis],
    data=data,
    meta=None,
    interp_kwargs=None,
)
```
In case the order of the axes is not correct, or the names are not as expected an error message is thrown, like:
```python3
from gammapy.maps import MapAxis
from gammapy.irf import EffectiveAreaTable2D
from astropy import units as u

offset_axis = MapAxis.from_bounds(0 * u.deg, 1 * u.deg, nbin=5, name="offset")
energy_axis = MapAxis.from_energy_bounds("1 TeV", "10 TeV", nbin=10)

aeff = EffectiveAreaTable2D(
    axes=[offset_axis, energy_axis]
)
```
Yields:
```
ValueError: Incorrect axis order or names. Expected axis order: ['energy_true', 'offset'], got: ['offset', 'energy'].
```
I think this is fair behavior from the code...

From the Gammapy side the huge advantage is the generalization of the I/O. E.g. methods such as `.from_table()` can rely on a generic `MapAxes.from_table()`, which just returns the list of axes defined. A class specific init method would require calling and creating the instance all differently and create a lot of unnecessary code. Also the generic `axes` keyword is consistent then with the `Map` API. I think by now there is not much motivation to go back to the old scheme.

We started to collect all relevant API changes in a single document: https://github.com/gammapy/gammapy/wiki/Main-API-changes-from-v0.18.2-to-v0.19 to help users with the refactoring. I will add an entry for the IRF classes and then close the issue. Please reopen if you think it's important to keep the backwards compatibility here.
