### ISSUE TITLE
Fit.run() should not return a dictionary of FitResult objects

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#3542]
Currently `Fit.run()` returns a dictionary with two entries, namely `optimize_result` and `covariance_result`. This is confusing. The two could be merged into a single object.

The main informations shared by all fitting methods are: `
- `success` : a boolean flag
- `message` : a `str` containing the possible message from the fitter
- `backend` : the backend fitter use for this specific task (e.g. minuit, spicy, sherpa)
- `method` : the method used, e.g. `Nelder-Mead` or `L-BFGS-B` for scipy backend

The `Parameters` is also stored but this seems redundant for the results of covariance and confidence since the latter do not determine the best fit parameters. A specific product of `covariance` is the covariance matrix which is also stored on the `Parameters` object.

I would propose to have `Fit.run()` return only a `OptimizeResult` and add `.covariance_result` property containing the `CovarianceResult`. `CovarianceResult` would not contain the `Parameters` table.

We will then need to define more uniform result types for other methods such as `confidence`, `stat_profile`etc.

**Comment by adonath** [comment]
The conclusion from one of the last dev meetings was to introduce a general `FitResult` class, that holds the results from the individual steps such as optimization,  covariance and confidence. For convenience some of the properties can be re-exposed on the `FitResult` object.
