### ISSUE TITLE
test fails in master 

### ISSUE THREAD

**Issue by joleroi** [gammapy/gammapy#355]
When running the test with the --remote-data flag in the master branch, I get 3 failed tests in 
gammapy/datasets/tests/test_catalogs.py

I guess this passed unnoticed since (afaik) the online tests are run without this flag.
@cdeil @mapazarr : Is there an easy way to fix this? It would be nice to be able to run all tests with the remote example data, wouldn't it?

**Comment by cdeil** [comment]
@kingj90 – There should never be failing tests in master.

The solution is to either fix them directly, or to mark them xfail (see example [here](https://github.com/gammapy/gammapy/blob/cd2ae68cac6aea3a1a612d24bb01798a5b7eb702/gammapy/spectrum/tests/test_isrf.py#L8) and deal with this later.

I'm getting 5 fails and will have a look after lunch: https://gist.github.com/cdeil/1ccc2badbb9ce3fac29c

**Comment by cdeil** [comment]
There's no actual bugs, there are all timeout fetching remote files.

E.g. if I run
```
python setup.py test --remote-data -V -t gammapy/background/tests/test_cube.py
```
or
```
python setup.py test --remote-data -V -t gammapy/datasets/tests/test_catalogs.py
```
it will work ~ 50% of the time, and 50% of the time fail with a timeout.

The best fix for this is to fetch all test data, i.e. the whole gammapy-extra repo, before starting the tests.
This is part of #288, for which I unfortunately don't have time.

One quick fix would be to increase the timeout from 3 seconds to ~ 10 seconds in `datasets.get_path` in the `download_file` call.

Another possible interim solution would be to use [pytest-ignore-flaky](https://pypi.python.org/pypi/pytest-ignore-flaky) and mark all remote data tests as flaky.

Or we just ignore this issue for now, and if you work on tests that require remote data, you specifically only run those, not all remote-data tests.

@kingj90 – Does the last option sound acceptable to you for now?
(I'd prefer to spend a little time on #352 now)

**Comment by kingj90** [comment]
@cdeil thanks for the explanation. Yes, the last option is perfectly fine!

**Comment by cdeil** [comment]
@kingj90 – Can you try again with the latest version from `master`?

I think this was fixed in #364 or is there something else that should be fixed / improved?

**Comment by kingj90** [comment]
@cdeil : You are probably aware of that, but at the moment the tests in master fail, if a user does have a datamanager config file that is different from yours, i.e. in my case

KeyError: u"No data store with name hess-hap-hd-prod01-std_zeta_fullEnclosure found. Available datastores: ['hap', 'pa']"

**Comment by cdeil** [comment]
@kingj90 – Yes, I'm aware this is still not set up nicely.

The best solution would be if someone writes a utility function to make a test DataStore instead of using the real one.

A utility function to generate the test data should be added here:
https://github.com/gammapy/gammapy/blob/master/gammapy/utils/testing.py#L97
the easiest would be to replicate these files 3 times:
https://github.com/gammapy/gammapy-extra/tree/master/test_datasets/irf/hess/pa
It could then work like this:
```
export GAMMAPY_TEST_DATA=${HOME}/.gammapy/datasets/test
gammapy-data-manage --make-test-data
```
where the command copies a `data-register-test.yaml` files there.

Overal it's < 100 lines of code, but still some work to get it to run and I don't have the time.
I guess you don't either?

**Comment by kingj90** [comment]
No, unfortunately not. I will run the test on an existing datastore for the moment

**Comment by cdeil** [comment]
These test fails have been resolved.
At the moment there are no tests in Gammapy that query for data other than from gammapy-extra.
Closing this issue.
