### ISSUE TITLE
OnOff datasets npred computation fails in case no counts is present

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#3555]
**Gammapy version**
present dev, 0.18.2

**Bug description**
 As pointed out by @thierrystolarczyk in the slack channel, `SpectrumDatasetOnOff.npred()` fails in case no counts are present, because in on off datasets we try to compute the marginalised background.

https://github.com/gammapy/gammapy/blob/926d3dae2354859b5bfb008e9f8c2e59fee5d9f4/gammapy/datasets/map.py#L1868

This is annoying as for a simulated dataset (before simulating the counts), `print(dataset_onoff)` or `fake` fails. The only way to get around this is to add a dummy counts map.

**To Reproduce**

In the spectrum simulation notebook, add 
```

ds_onoff = SpectrumDatasetOnOff.from_spectrum_dataset(
                                            dataset=dataset,
                                            acceptance=1,
                                            acceptance_off = 1/0.2)
print(ds_onoff)
```

after cell 10.

**Expected behavior**
What should be the correct behaviour @registerrier @QRemy @adonath ?

**Comment by adonath** [comment]
I think this should be fixed before tomorrow...anybody?

**Comment by registerrier** [comment]
I suppose this means that `counts` should never be `None` in counts based  `Dataset` objects. 

I propose to change `MapDatasetMaker.run` to add an empty `counts`  attribute if `"counts"` is not in the selection.
