### ISSUE TITLE
The function maps.wcs.ndmap.to_region_nd_map does not work with Boolean map

### ISSUE THREAD

**Issue by bkhelifi** [gammapy/gammapy#3562]
**Gammapy version**
The dev version

**Bug description**
This function does not conserve the boolean dtype, which is an issue for the mask or fit success maps. 

**Expected behavior**
This might be due to the behaviour of the numpy function that is set as argument. The dtype should be passed:
`data = func(cutout.data[..., idx_y, idx_x], axis=-1)
`
to 
`data = func(cutout.data[..., idx_y, idx_x], dtype=cutout.data.dtype, axis=-1)
`
I ask to the expert to check this point.

**To Reproduce**
```
import numpy as np
import astropy.units as u
from regions import CircleSkyRegion, PointSkyRegion, RectangleSkyRegion
from gammapy.maps import Map, MapAxis, MapCoord, WcsGeom, WcsNDMap
from astropy.coordinates import SkyCoord
axis = MapAxis.from_bounds(1, 10, nbin=3, unit="TeV", name="energy")

geom = WcsGeom.create(
    skydir=(0, 0), width=(2.5, 2.5), binsz=0.5, axes=[axis], frame="galactic"
)

m = Map.from_geom(geom)
m.data += 1
m.data = m.data.astype(bool)
center = SkyCoord(0, 0, frame="galactic", unit="deg")
region = CircleSkyRegion(center=center, radius=1 * u.deg)
rm = m.to_region_nd_map(region=region)
rm.data.dtype
```

**Other information**
As coded, I could expect that maps.hpx.ndmap.to_region_nd_map has exactly the same issue

**Comment by bkhelifi** [comment]
Indeed, I fully agree. Thank you @adonath .
This is indeed not a bug, but rather a well thought feature. I propose to close this 'false' issue

**Comment by adonath** [comment]
Thanks @bkhelifi !
