### ISSUE TITLE
How to sort author list for Zenodo / CITATIONS.cff?

### ISSUE THREAD

**Issue by adonath** [gammapy/gammapy#3608]
In #3344 @Bultako added a first version of the `CITATION.cff` file. In #3604 I added a little helper script to help maintaining the file and keep it in sync with the actual git shortlog. For the actual DOIs we still rely on Zenodo (see e.g. https://zenodo.org/record/4701500#.YZZgTi1h0UE) and I think this will remain.  So the logic is likely that the `zenodo.json` will be created in an automatized way from the `CITATION.cff` file we currently have. Then for the actual citations to Gammapy one citation will go to a main reference paper (currently https://ui.adsabs.harvard.edu/abs/2017ICRC...35..766D/abstract) and a second one to the Zenodo entry pointing to the actual version used in the analysis. We will soon update the webpage (https://gammapy.org/acknowledging.html) to describe this scheme.

The citation to a paper is still the standard academic reference, however there will be only a paper about Gammapy once every few years to describe major version updates (probably similar to Astropy https://www.astropy.org/acknowledging.html). However different versions of Gammapy will be released more often and can be cited via Zenodo. In this context the question arrises how to sort the Author list in `CITATION.cff` and Zenodo. The current scheme proposed in #3604 just sorts by the total number of commits over the lifetime of the project, which is very likely not the best way to do this. It will keep "lifetime" contributors at the top and make it very hard for new contributors to appear more at the top, even if they contributed a lot to a specific version of the Gammapy. 

I think the citations to Zenodo could be used to highlight short term contributions to a software project as well. Ideally we can define a transparent and at least subjectively fair way of doing this. The scheme has to be rather simple as well, otherwise it will not be transparent. Here are a few suggestions:
- Sort by total number of commits over lifetime of the project?
- Sort alphabetically by last name (this is often done in scientific collaborations)?
- Sort by total number of commits since the last minor version and then sort alphabetically for the rest
- "Negotiate" in developer meetings before a release?
- Set a threshold of >2 commits over the lifetime of the project?
- Any other ideas?
- How do other projects do it?

Let's use this issue to collect a few ideas and maybe we can agree on some scheme that we adopt for v1.0 and versions after. The scheme could be adapted any time later. 

Note: the authors lists from the past Zenodo records where compiled by hand (https://zenodo.org/record/4701500, https://zenodo.org/record/4701492, https://zenodo.org/record/4701489).

**Comment by registerrier** [comment]
I definitely agree that we should be able to sort the contributors between specific tags or release and then discuss.
There could be a threshold of  number of commits per year over the lifetime of the project so that historical contributors stay in but individual punctual contributors appear mostly in the time frame when they contributed?

Also we probably should account for contributions in other repositories such as `gammapy-benchmarks` which are essential to the projects but do not appear in the gammapy commits.

**Comment by bkhelifi** [comment]
This is associated to the PR #3970

**Comment by adonath** [comment]
We decided to just sort alphabetical by name. This is written up in [PIG 24](https://docs.gammapy.org/1.0/development/pigs/pig-024.html)
