### ISSUE TITLE
Improper fill_value for integer columns of HDUIndexTable

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#3617]
**Gammapy version**
dev

**Bug description**
The recent change in `HDUIntexTable.read` breaks with some datastores if a column that does not contain strings is masked.

**Expected behavior**
The file should be opened normally

**To Reproduce**
Open hess1 std_Impact datastore with current dev.

**Other information**
Any other information you think will be useful for us to fix the issue can go here.

**Comment by adonath** [comment]
My proposal here would be just to fix the fail, that we see in the validation, otherwise keep the behavior the same...
