### ISSUE TITLE
MD5 for hashes of datasets

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [gammapy/gammapy#3629]
**Gammapy version**

`@master`

**Bug description**

Consider using a different hash than MD5?

While this might not be a security issue involved here, MD5 is obsolete and automated reviewing tools will raise security alerts.

**Expected behavior**

Calls to  `hashlib.md5()` could be replaced by calls to `hashlib.sha256()` or `hashlib.sha512()`:
https://github.com/gammapy/gammapy/blob/ae5621e7ea0857a8b7dd22df2487165f066934fb/dev/datasets/make_dataset_index.py#L19-L24

**Comment by adonath** [comment]
I think by now we can actually remove the datasets handling, can you confirm @Bultako?

**Comment by Bultako** [comment]
Yes, actually we can safely remove the whole `/dev/datasets` folder.

**Comment by adonath** [comment]
Solved by #3652.
