### ISSUE TITLE
Circular imports in gammapy.spectrum and gammapy.data

### ISSUE THREAD

**Issue by joleroi** [gammapy/gammapy#363]
I ran into the following issue:

gammapy.data.SpectralCube uses some functionality from gammapy.spectrum, namely powerlaw, EnergyBounds, LogEnergyAxis.

gammapy.spectrum.spectrum_analysis uses some functionality from gammapy.data namely CountsSpectrum

This lead to a circular import

Possible Solutions

* Move gammapy.data.CountsSpectrum to gammapy.spectrum - for me this would render gammapy.data useless 
* Remove spectrum_analysis from gammapy.specturm toplevel namespace - also weird

I guess the best way would be to find a general solution how to organize data containers in gammapy, but this could take some time

**Comment by cdeil** [comment]
Agreed that some re-structuring in Gammapy is needed.

I've assigned this to me for the 0.5 release milestone.
Related: #171, #288, #328 and probably others.

Of course, if someone wants to make a pull request with a suggestion how to re-structure things in the meantime, it's always welcome!

**Comment by cdeil** [comment]
@joleroi  - I'm closing this issue. (Feel free to re-open if you disagree)

By now we have the `gammapy.cube.SkyCube` in `gammapy.cube`,
and the `gammapy.cube` sub-package is allowed to import from `gammapy.data` and `gammapy.spectrum`.
So I think it's OK for now?

If we later find cases where spectrum and cube analysis is mixed up (e.g. to extract 1-dim spectra from 2-dim cubes for 1-dim analysis), we have to either move that analysis code to a higher-level package (what is now called `gammapy.scripts` or have a delayed import in `gammapy.spectrum`.

I'll make a diagram for the docs how the sub-packages relate soon, but I wanted to start and clean out old issues like this one.
