### ISSUE TITLE
Unexpected keyword argument 'prefix' in method call

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [gammapy/gammapy#3638]
**Gammapy version**

`@master`

**Bug description**

**`Datasets.write()`** is called with keyword argument `prefix`:
https://github.com/gammapy/gammapy/blob/ae5621e7ea0857a8b7dd22df2487165f066934fb/gammapy/modeling/models/tests/data/make.py#L101-L106

The keyword argument `prefix` has been removed by a03d1a7 (#3089).

**Comment by adonath** [comment]
Thanks @DimitriPapadopoulos, this script is not really part of the Gammapy production code, but just used to create test data. However we should probably keep it up to date as well...

**Comment by adonath** [comment]
BTW: this script should probably just go to https://github.com/gammapy/gammapy-data/tree/master/tests/models and could be removed from the Gammapy code base completely. Usually we don't need to update test data that often...
