### ISSUE TITLE
Argument passed both by position and keyword in function call

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [gammapy/gammapy#3639]
**Gammapy version**

`@master`

**Bug description**

`LightCurveTemplateTemporalModel.evaluate()` calls `LightCurveTemplateTemporalModel._interpolator()` with two arguments `time` and `ext`:
https://github.com/gammapy/gammapy/blob/ae5621e7ea0857a8b7dd22df2487165f066934fb/gammapy/modeling/models/temporal.py#L434
https://github.com/gammapy/gammapy/blob/ae5621e7ea0857a8b7dd22df2487165f066934fb/gammapy/modeling/models/temporal.py#L455

Yet `LightCurveTemplateTemporalModel._interpolator()` is defined to accept a single `ext` argument:
https://github.com/gammapy/gammapy/blob/ae5621e7ea0857a8b7dd22df2487165f066934fb/gammapy/modeling/models/temporal.py#L418-L419

**Comment by adonath** [comment]
The code does not exist anymore after #4084.
