### ISSUE TITLE
[0.19] Failure in test_plot_residual_onoff

### ISSUE THREAD

**Issue by olebole** [gammapy/gammapy#3650]
**Gammapy version**

* gammapy 0.19 (from PyPI)
* matplotlib 3.5.0

**Bug description**

When running the unit test on the freshly built package, I get (among others) a failure in test_plot_residual_onoff, which seems to be related to a no-longer-supported usage of 
```
___________________________ test_plot_residual_onoff ___________________________

    @requires_dependency("matplotlib")
    def test_plot_residual_onoff():
        axis = MapAxis.from_energy_bounds(1, 10, 2, unit="TeV")
        geom = WcsGeom.create(npix=(10, 10), binsz=0.05, axes=[axis])
    
        counts = Map.from_geom(geom, data=np.ones((2, 10, 10)))
        counts_off = Map.from_geom(geom, data=np.ones((2, 10, 10)))
        acceptance = Map.from_geom(geom, data=np.ones((2, 10, 10)))
        acceptance_off = Map.from_geom(geom, data=np.ones((2, 10, 10)))
        acceptance_off *= 2
    
        dataset = MapDatasetOnOff(
            counts=counts,
            counts_off=counts_off,
            acceptance=acceptance,
            acceptance_off=acceptance_off,
        )
        with mpl_plot_check():
>           dataset.plot_residuals_spatial()

gammapy/datasets/tests/test_map.py:1527: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
gammapy/datasets/map.py:847: in plot_residuals_spatial
    ax = residuals.plot(ax, **kwargs)
gammapy/maps/wcs/ndmap.py:372: in plot
    im = ax.imshow(data, **kwargs)
/usr/lib/python3/dist-packages/astropy/visualization/wcsaxes/core.py:211: in imshow
    return super().imshow(X, *args, origin=origin, **kwargs)
/usr/lib/python3/dist-packages/matplotlib/_api/deprecation.py:456: in wrapper
    return func(*args, **kwargs)
/usr/lib/python3/dist-packages/matplotlib/__init__.py:1416: in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
/usr/lib/python3/dist-packages/matplotlib/axes/_axes.py:5447: in imshow
    im._scale_norm(norm, vmin, vmax)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <matplotlib.image.AxesImage object at 0x7f70ad8771f0>
norm = <astropy.visualization.mpl_normalize.ImageNormalize object at 0x7f70ad877100>
vmin = None, vmax = 5

    def _scale_norm(self, norm, vmin, vmax):
        """[…]"""
        if vmin is not None or vmax is not None:
            self.set_clim(vmin, vmax)
            if norm is not None:
>               raise ValueError(
                    "Passing parameters norm and vmin/vmax simultaneously is "
                    "not supported. Please pass vmin/vmax directly to the "
                    "norm when creating it.")
E               ValueError: Passing parameters norm and vmin/vmax simultaneously is not supported. Please pass vmin/vmax directly to the norm when creating it.

/usr/lib/python3/dist-packages/matplotlib/cm.py:380: ValueError
```

**Expected behavior**

All tests should pass

**To Reproduce**

Run the tests with matplotlib 3.5.0.

**Other information**

The problem seems that  plot_residuals_spatial() sets both vmin and vmax, which is no longer allowed for matplotlib:
https://github.com/gammapy/gammapy/blob/7e2976713facc0d443ade5279e91c4ae6b38c6c4/gammapy/datasets/map.py#L843-L847

This was [deprecated in matplotlib 3.3](https://matplotlib.org/3.5.0/api/prev_api_changes/api_changes_3.3.0.html#parameters-norm-and-vmin-vmax-should-not-be-used-simultaneously), and removed in 3.5.

**Comment by adonath** [comment]
Same known issue as #3651, Gammapy is not compatible with matplotlib 3.5.

**Comment by adonath** [comment]
The fixate avoid the deprecation us is probably like https://github.com/gammapy/gammapy/blob/v0.19/gammapy/maps/wcs/ndmap.py#L368 So pop the `vmin` and `vmax` attribute beforehand.

**Comment by GajVan** [comment]
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_10427/1737047908.py in <module>
----> 1 tsmap_postfit = gta.tsmap(prefix='TSmap_start',make_plots=True,write_fits=True,write_npy=True)

/anaconda3/envs/fermi/lib/python3.7/site-packages/matplotlib/cm.py in _scale_norm(self, norm, vmin, vmax)
    379             if norm is not None:
    380                 raise ValueError(
--> 381                     "Passing parameters norm and vmin/vmax simultaneously is "
    382                     "not supported. Please pass vmin/vmax directly to the "
    383                     "norm when creating it.")

ValueError: Passing parameters norm and vmin/vmax simultaneously is not supported. Please pass vmin/vmax directly to the norm when creating it.

**Comment by adonath** [comment]
Gammapy should be fully compatible with matplotlib 3.5 by now...see #3908.

**Comment by GajVan** [comment]
Thank you for your response
