### ISSUE TITLE
FoVBackgroundMaker should not support Region based datasets

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#3659]
**Gammapy version**
all versions

**Bug description**
If one uses the `FovBackgroundMaker` in the data reduction loop with a `SpectrumDataset`, it will silently fit the background onto the model. 
The correct approach is of course to start from a `MapDataset`, to compute the FoV background and then to reduce it to a `SpectrumDataset` (or to a RegionNDMap geometry).

**Expected behavior**
I don't really see a good reason why one would use the `FoVBackgroundMaker` on a spectrum unless we completely change its internal behavior to perform background and event projection on a WCS internally. 
It should therefore raise an error.

**To Reproduce**
Take the Spectral analysis notebook and replace Reflected regions maker by a FoVBackgroundMaker.

**Other information**
Any other information you think will be useful for us to fix the issue can go here.

**Comment by adonath** [comment]
I mostly agree @registerrier, however I can imagine one use case: a background model spectrum could be fit to off observations. So one could finally include off observations in a spectral fits to constrain the background model normalization and tilt in the on region. I think it could be a valid use case where there is not much off data available...

**Comment by registerrier** [comment]
> I mostly agree @registerrier, however I can imagine one use case: a background model spectrum could be fit to off observations. So one could finally include off observations in spectral fits to constrain the background model normalization and tilt in the on region. I think it could be a valid use case where there is not much off data available...

I agree @adonath . This is a valid possibility. I suppose it might more naturally work starting from a `MapDataset` since we still need to have a safe mask e.g. with an offset cut. The data reduction approach would be the following:
- create `MapDataset` and `MapMaker` `FovBackgroundMaker` and `SafeMaskMaker`
- Define target region
- loop over observations:
  - run makers
  - `dataset.to_spectrum_dataset`
 
For now, I have simply added an exception if the dataset has a `RegionGeom`
