### ISSUE TITLE
`upsample()` / `downsample()` and other inconsistencies across class hierarchies

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [gammapy/gammapy#3661]
**Gammapy version**

`master` branch

**Bug description**

I just realized that I had mixed up `upsample()` and `downsample()` in #3552. I had modified `downsample()` instead of `upsample()` in at least one location.

**Expected behavior**

Consistent `upsample()` / `downsample()` signature across class hierarchy.

**Other information**

DeepSource.io actually reports lots of inconsistencies in method signatures in class hierarchies, see for example:
https://deepsource.io/gh/DimitriPapadopoulos/gammapy/issue/PYL-W0221/occurrences

I believe it would be worth going through such warnings, and revisiting the API with consistency across class hierarchies in mind.

**Comment by adonath** [comment]
Thanks @DimitriPapadopoulos, I agree this would be good clean-up work to do. I just set the v1.0 milestone...
