### ISSUE TITLE
Document how to compute H-test 

### ISSUE THREAD

**Issue by bkhelifi** [gammapy/gammapy#3665]
**Context**
For the search and analysis of pulsed emission of pulsar, the standard Li&Ma approach is not optimal and the H-test is used commonly now. A detailed description is given here: [https://arxiv.org/abs/1005.4867](https://arxiv.org/abs/1005.4867).

**Proposal**
I propose to include this new test statistics in our `stats` sub-package.

**Comment by registerrier** [comment]
This is indeed an important aspect. We have to see what to include for event-by-event statistics.

The H-test is implemented in pint already.
https://nanograv-pint.readthedocs.io/en/latest/_autosummary/pint.eventstats.hmw.html
Pint provides a broad range of event based stats in its `pints.eventstats` package.

**Comment by adonath** [comment]
@registerrier and @bkhelifi The maybe a Gammapy recipe is the good solution here? Showing how to use `pint` to compute the H test from Gammapy data?

**Comment by registerrier** [comment]
For now, a recipe will show how to use the one from `pint` for pulsar analysis.

**Comment by registerrier** [comment]
This requires solving the issue with gammapy-recipes CI. This should have priority.

**Comment by registerrier** [comment]
This is now solved . The pulsar recipe is online. Closing.
