### ISSUE TITLE
Warning about `is_pointlike` when converting to IRFs to HDU

### ISSUE THREAD

**Issue by maxnoe** [gammapy/gammapy#3668]
**Gammapy version**
0.19.0

**Bug description**

Calling `to_hdu_table` raises a FITS warning that `is_pointlike` is longer than 8 characters and thus not valid for a normal FITS header keyword.

**Expected behavior**

No warning and probably not adding `is_pointlike` to the header at all, since this is covered by the `HDUCLAS` in GADF.

**To Reproduce**

```

In [4]: aeff = EffectiveAreaTable2D.read('joint-crab/data/fact/fact_irf.fits')

In [5]: aeff
Out[5]: <gammapy.irf.effective_area.EffectiveAreaTable2D at 0x7fd1a9d21e90>

In [6]: aeff.to_table_hdu()
/home/maxnoe/.local/anaconda/envs/pyirf/lib/python3.7/site-packages/astropy/io/fits/card.py:268: VerifyWarning: Keyword name 'is_pointlike' is greater than 8 characters or contains characters not allowed by the FITS standard; a HIERARCH card will be created.
  keyword), VerifyWarning)
Out[6]: <astropy.io.fits.hdu.table.BinTableHDU at 0x7fd1aa0e9510>
```

**Comment by adonath** [comment]
Thanks @maxnoe ! Just to confirm: https://github.com/gammapy/gammapy/blob/master/gammapy/irf/core.py#L419 naively copies over the meta data from the Gammapy object. One should translate to valid FITS and GADF keywords instead.
