### ISSUE TITLE
Polish axis labels

### ISSUE THREAD

**Issue by adonath** [gammapy/gammapy#3675]
For v0.19 we moved all the axes formatting for plots we make to the `MapAxis` object. This defines a single place where the formatting of plot axes happens. By default the the axis table is chosen as `axis.name.title()`. While this is nice because it guarantees consistency between the actual axis plotted and the axis label, it leads to less pretty axis labels. To solve this I proposed to introduce a dictionary to translate map axis names to plot axis labels. Like:

```python3
PLOT_AXIS_LABEL = {
    "energy": "Energy",
    "energy_true": "True Energy",
    "migra": ...
}
```

Of course we have to agree in which axes labels to chose...

**Comment by registerrier** [comment]
I suppose this should go with a general definition of reserved axes names in gammapy, otherwise we might duplicate names, no? 
So far, this does not really exist. There is a definition for IRF in `IRF_DL3_AXS_SPECIFICATION`. Where would the plot label registry would go?

**Comment by adonath** [comment]
@registerrier We already have a definition of the reserved axis names here: https://docs.gammapy.org/0.19/irf/index.html#irf-axis-naming 

I think the the plot label registry could either go in `gammapy.visualisation` or `gammapy.maps.axes`. I think both is fine by now.
