### ISSUE TITLE
makers.utils undocumented online

### ISSUE THREAD

**Issue by Tobychev** [gammapy/gammapy#3679]
**Gammapy version**
0.18.2

**Bug description**
`make_theta_squared_table` docstring does not show up in the documentation search, and I can't find it via the menu either. Probably applies for all functions in that subpackage, but I haven't checked.

The function has a proper docstring, it's just not been caught during generation of the html page, and is thus hard to discover.

**To Reproduce**
Go to docs.gammapy.org and search for make_theta_squared_table, the only hit is in an example.

**Comment by registerrier** [comment]
Note that it appears in hess tutorials.

**Comment by bkhelifi** [comment]
I will add it in the PR about the missing links into the documentation
