### ISSUE TITLE
FoVBackgroundMaker with method=fit ignores min_counts and min_npred_background

### ISSUE THREAD

**Issue by luca-giunti** [gammapy/gammapy#3680]
**Gammapy version**
0.19

**Description**
Reminder issue to improve consistency: the options `min_counts` and `min_npred_background` passed to the `FoVBackgroundMaker` are used only if the method is `scale`, not for `fit`. This should be documented if there is a good reason behind, or they should be applied in both cases.

**Comment by registerrier** [comment]
Hello @AtreyeeS . This issue can be closed now that #3688 is merged right?

**Comment by AtreyeeS** [comment]
Addressed in #3688
