### ISSUE TITLE
Add peek methods on IRFMaps

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#3683]
Most IRF methods have `peek` methods implemented. `EDispMap` and `PSFMap` are lacking such methods. Yet they would be useful, in particular to have a rapid view from the `MapDataset`.

The issue is to determine what is the interesting plots to provide. Most likely the average containment radius as a function of energy at the center for the `PSFMap` . Possibly the edisp matrix for `EDispMap`.
Some visualization of the map itself would be good. Possibly the associated exposure map or the containment radius map?

Suggestions @adonath @QRemy @AtreyeeS @LauraOlivera ?

**Comment by adonath** [comment]
Solved by #3894.
