### ISSUE TITLE
Adding utility function to provide rebinned energy axis

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#3685]
A frequent request from users is a tool to determine a good binning for representation of flux point extraction. 

Such a function could determine a `MapAxis` that would provide some requested constraint on energy bins e.g. min number of counts, of off counts, min significance etc.
I suppose this is mostly relevant for `SpectrumDataset` but maybe not only.

**Comment by adonath** [comment]
Solved by #3745.
