### ISSUE TITLE
FluxEstimator._set_norm_parameter crashes

### ISSUE THREAD

**Issue by Tobychev** [gammapy/gammapy#3694]
**Gammapy version**
0.19

**Bug description**
Any code passing trough the "scan" branch of `FluxPointsEstimator._nan_result()` will crash due the invocation of `_set_norm_parameter` without the argument `scaled_parameter`.

**Expected behavior**
Either `_nan_result` passing the correct arguments, or `_set_norm_parameter` properly handling its default arguments.

**Comment by registerrier** [comment]
Thanks @Tobychev.  The test for missing energy intervals currently does not execute scan. This needs to be added.

One issue with `FluxEstimator._set_norm_estimator` is that it shouldn't fail with its default argument `scaled_parameter=None`. A possible default behavior is to force `norm` range to be positive. This could provide a solution to #3690 as well in case no `scale_parameter` is unambiguously found.
