### ISSUE TITLE
Convenience Feldman-Cousins excess limit method

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#370]
As discussed at https://github.com/gammapy/gammapy/pull/367#discussion_r42631482, it would be nice to have a convenience functions to compute excess limits for the common Poisson stats cases from gamma-ray astronomy.

@dlennarz commented at https://github.com/gammapy/gammapy/pull/367#discussion_r42635702 that this would best be implemented as a class.

**Comment by adonath** [comment]
Excess limits are now supported by the `CountsStatistics` classes.
