### ISSUE TITLE
Unexpected dependency of the flux maps on the normalization of the assumed spectra

### ISSUE THREAD

**Issue by luca-giunti** [gammapy/gammapy#3701]
**Gammapy version**
0.19

**Description**
I expected the flux maps obtained with the `ExcessMapEstimator` to be independent on the normalization of the assumed power law spectrum. Or at least that is true if one computes flux maps as explained in the HGPS paper, section 3.4.2. That's because when a simple power law is assumed the normalization cancels out in the conversion of the exposure to reco energy. 

This is instead not the case, and I am not sure whether it is a bug or just a matter of documentation. In the latter case, it would be good to explain this behavior and also possibly provide a HGPS-like method to compute flux maps.

**To Reproduce**
See [this notebook](https://github.com/luca-giunti/share/blob/master/analysis_3d.ipynb), cells >16. Lowering the power law `amplitude` from the default `1 TeV-1 cm-2 s-1` to `1 TeV-1 m-2 s-1` increases the flux by 4 orders of magnitude.

**Comment by adonath** [comment]
Thanks @luca-giunti! Looking at the notebook the values has changed by a factor 1e-4, but note that the unit changed accordingly from `cm-2 s-1` to `m-2 s-1`! So the current behavior is that the unit is adapted from the reference model, which I thunk makes sense. Or is this un-expected?

**Comment by luca-giunti** [comment]
Ah, you're right!!! Sorry, this teaches me to never open an issue at night...
