### ISSUE TITLE
Add information on computing TS of a specific model

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#3702]
Getting the TS of a particular model (from a list of many models) seems to a common question. What we mention in https://docs.gammapy.org/0.19/howto.html#compute-source-significance is probably not sufficient for people starting with multiple models in the initial model definition.

Maybe we can either add some more detailed documentation, or some helper function in our code base.

**Comment by QRemy** [comment]
We could mention in the how-to that the significance of a source assuming that the TS follows a chi2 distribution (see scipy.stats.chi2) can be computed computed as follows:
`Significance = sqrt(chi2.isf(chi2.sf(TS, DoF), 1)`
with
`DoF = len(model.parameters.free_parameters) #could be a model property`
(Note that the survival function sf = 1 - cdf can be more accurate numerically than the cdf.)

We could also add a `TSestimator` to ease the calculation and define some presets for the choice of the frozen parameters.
For the CTA-GPS catalogue I use the following tests:
Test global model with and without each candidate source :
-TSnull : test against global model, all frozen (tested source amplitude frozen or zero)
-TSbkg: test with background norm free (and with tested source amplitude free or zero)
-TSall: test with background norm free + nearby sources amplitude free if d < Robject + Rother + 1 deg (and with tested source amplitude free or zero)

**Comment by registerrier** [comment]
> We could also add a `TSestimator` to ease the calculation and define some presets for the choice of the frozen parameters. For the CTA-GPS catalogue I use the following tests: Test global model with and without each candidate source : -TSnull : test against global model, all frozen (tested source amplitude frozen or zero) -TSbkg: test with background norm free (and with tested source amplitude free or zero) -TSall: test with background norm free + nearby sources amplitude free if d < Robject + Rother + 1 deg (and with tested source amplitude free or zero)

Technically, such a utility would not really be an `Estimator` since it would not estimate a physical parameter but only the statistical significance of a specific model. Of course, this can be extended to be a complete `SkyModelEvaluator` that would take a given component, put its amplitude to 0, then fit it and yield TS as well as all best fit parameters. I suppose that providing detailed error estimates or likelihood scans for each parameter is less obvious. 

This is indeed a feature that is frequently requested.

**Comment by adonath** [comment]
For v1.0 this will remain as a documentation example.

**Comment by registerrier** [comment]
I assume the last missing piece here is an example showing the usage of the function introduced by @QRemy in #4216

**Comment by registerrier** [comment]
This requires to expose `select_nested_models` see issue #4788

**Comment by Astro-Kirsty** [comment]
`select_nested_models` is now exposed (#4944 and #4961)
