### ISSUE TITLE
FitResult print output is confusing

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#3703]
A `print(fit_result)` displays both the `covariance_result` and the `optimize_result` as `OptimizeResult`, eg: see cell 19
https://docs.gammapy.org/dev/tutorials/starting/analysis_2.html#Fit-the-model

Reminder issue to fix it during the sprint week

**Comment by adonath** [comment]
Indeed this line return the incorrect private data member: https://github.com/gammapy/gammapy/blob/master/gammapy/modeling/fit.py#L638
