### ISSUE TITLE
Add mamba as an alternative to conda in installation instructions

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#3710]
We should also advertise mamba (https://mamba.readthedocs.io/en/latest/) as a possible package manager in the installation instructions in the documentation.

**Comment by facero** [comment]
I can do this simple task this week if you want @registerrier.
`mamba` can be used as a replacement for `conda` (like mamba activate gammapy-0.19 for example) but I think its simpler to advertise it only as a replacement for installation (mambda install XXX).
Otherwise it becomes confusing. Do you agree ?

**Comment by AtreyeeS** [comment]
So we can mix `conda` and `mamba` @facero ? `mamba install` and then `condo activate` ?
Resolving the dev environment through `conda` took an abnormal amount of time for me recently, so I guess we should update the dev instructions as well

**Comment by facero** [comment]
Yes you can mix `mamba` and `conda` commands. Also mamba can be used as a full replacement of conda. You can for example do:
`mamba install numpy` or `mamba activate gammapy-dev`.
But as most of the people will have also conda installed and are used to it, I suggest that in the doc we limit the use of mamba to `mamba install XXX`.

I can also update the dev docs to mention `mamba` if everyone agrees.

**Comment by maxnoe** [comment]
@facero mamba cannot do activate, see notes on the doc page: 
https://mamba.readthedocs.io/en/latest/user_guide/mamba.html

Mamba replaces conda for everything but `conda activate <env>` / `conda deactivate`

**Comment by facero** [comment]
Mamba does seem to be able to activate. Here is on my laptop:
```
(base) 09:18-sap123 ~/$  mamba activate gammapy-dev
Run 'mamba init' to be able to run mamba activate/deactivate
and start a new shell session. Or use conda to activate/deactivate.
```
Once I did `mamba init`:
```
(base) 09:19-sap123 ~/$  mamba activate gammapy-dev
(gammapy-dev) 09:19-sapmcn177 ~/$
```

Although it's maybe simpler to stick to conda for everything and just use mamba for installation (but I guess its a question of taste).

**Comment by maxnoe** [comment]
Mmh. That's new. At least in the version I have, there I get the error that mamba cannot do activation. 

After updating, I get the init warning. Nice. Seems the user guide wasn't updated yet.
