### ISSUE TITLE
Read information from `EVENTS` header when not present in `OBS_INDEX`

### ISSUE THREAD

**Issue by maxnoe** [gammapy/gammapy#3724]
**Is your feature request related to a problem? Please describe.**

In the GADF, the `OBS_INDEX` table, mainly for convenience I think, has optional columns for many header keywords that are mandatory for the `EVENTS` HDU header.

However, gammapy only relies on the obs index table in most parts to retrieve this information. 

This is suboptimal, as requiring optional columns and ignoring mandatory keywords somewhere else is not what implementers of the standard expect.
 
**Describe the solution you'd like**

When creating observations, read the info from the event header, not an obs index.
Maybe check for consistency if both `OBS_INDEX` and the `EVENT` header have the same information.

**Additional context**

Mandatory headers in `EVENTS` specification: https://gamma-astro-data-formats.readthedocs.io/en/latest/events/events.html#mandatory-header-keywords

Columns of the `OBS_INDEX`:  https://gamma-astro-data-formats.readthedocs.io/en/latest/data_storage/obs_index/index.html#optional-columns

**Comment by maxnoe** [comment]
This is a follow up to #3352, which was closed after removing the requirement of just one of these optional columns.

**Comment by adonath** [comment]
Thanks @maxnoe, indeed this is still an open issue. My proposed solution here would be:
- Turn the current `Observation.obs_info` into a private `_obs_info`
- Implement a `Observation.obs_info` property, which updates the `_obs_info` with the information from the events header if it is missing.

**Comment by adonath** [comment]
@maxnoe I think by now the behavior is implemented as proposed in this issue?

**Comment by maxnoe** [comment]
Yes
