### ISSUE TITLE
Doubt in tests test_*_temporal_model_integral

### ISSUE THREAD

**Issue by aaguasca** [gammapy/gammapy#3736]
Dear developers, I have a doubt concerning the tests used to check the integration method in temporal models.

For example, in `test_gaussian_temporal_model_integral()`, when we call the method `integral(gti.time_start, gti.time_stop)`, the result `val` is an array of dimension 3. In each position of the array, we have the integral value for each period divided by the sum of the time in the three periods. 

Why is the integral value divided by the sum of time in the three periods? Instead of using only the time in each period?

**Comment by adonath** [comment]
Thanks @aaguasca, this is the convention we use for the temporal models. They don't return the integrated flux, but just a scaling factor <1 that is multiplied with the flux amplitude from the spectral model.
