### ISSUE TITLE
Allow following BiPM recommendations on axis labels

### ISSUE THREAD

**Issue by maxnoe** [gammapy/gammapy#3743]
**Is your feature request related to a problem? Please describe.**

Gammapy plotting functions typeset units as `quantity [unit]`.

 Which, while being common in HEP along with the alternative `quantity (unit)`, is wrong¹ and against the recommendations of the BiPM on how our unit system works:

See section 5.4, Rules and style conventions for expressing values of quantities of the SI Brochure here:

https://www.bipm.org/documents/20126/41483022/SI-Brochure-9-EN.pdf

> Symbols for units are treated as mathematical entities. In expressing the value of a quantity as
the product of a numerical value and a unit, both the numerical value and the unit may be
treated by the ordinary rules of algebra. This procedure is described as the use of quantity
calculus, or the algebra of quantities. For example, the equation p = 48 kPa may equally be
written as p/kPa = 48. It is common practice to write the quotient of a quantity and a unit in
this way for a column heading in a table, so that the entries in the table are simply numbers.
For example, a table of the velocity squared versus pressure may be formatted as shown
below. The axes of a graph may also be labelled in this way, so that the tick marks are labelled
only with numbers, as in the graph below.

¹ According to the people who's job it is to define our unit system

**Describe the solution you'd like**

Allow to use the recommended format for typesetting quantities. If not by default, then at least optionally.

**Comment by adonath** [comment]
Thanks @maxnoe! While I don't have a string opinion here I'd be happy to adopt the recommendation and put the SI brochure as a reference. This mostly concerns #3740...

**Comment by adonath** [comment]
Now one can actually do:

```python3
from gammapy.maps import axes

axes.DEFAULT_LABEL_TEMPLATE = "{quantity} / {unit}"
```
Do you reuest anything else here @maxnoe?

**Comment by maxnoe** [comment]
no, great!

**Comment by maxnoe** [comment]
It seems that this is not fully implemented yet. 

E..g. `Model.plot` seems to ignore this setting, reopening

**Comment by maxnoe** [comment]
Same for most of the IRF plotting methods, e.g. `EffectiveArea2D.plot_energy_depedence`
