### ISSUE TITLE
Feedback / comments on the pydata sphinx theme for Gammapy

### ISSUE THREAD

**Issue by adonath** [gammapy/gammapy#3746]
The new documentation template is online on the dev docs: https://docs.gammapy.org/dev This issue is to collect feedback and comments in a single place. The feedback will be implemented this week.

Please comment @registerrier, @bkhelifim, @AtreyeeS , @luca-giunti, @QRemy, @Bultako, @LauraOlivera, @fabiopintore, @maxnoe, @cosimoNigro

**Comment by adonath** [comment]
Copying over the feedback by @AtreyeeS from the Slack channel:

> I went through on a first glance:
> - A page for upgrade appears in the Getting started on clicking NEXT https://www.iaa.csic.es/~jer/gammapydocs/getting-
> started/upgrade.html. We do not get this in the normal one. I imagine Upgrade does not need to appear
> - I do not know if its useful to have Dependencies in the USER Guide section of the left pane/first page - since the  >recommended installation is through conda, the dependencies should be sorted automatically. it gets more than necessary >prominence probably.
>- The API documentation is very nicely separated now. Some of the pages, eg: datasets , maps , stats etc have a lot of useful >explanatory content. As an user, I would naively not click on the API documenation unless i wanted to see the code. So I would >prefer to move content on what stacking is, or hypothesis testing into the User Guide and leave the API pages clean, eg, like in >analysis . Similarly, the documentation on RingBackground or ReflectedBackground , IFRTheory is a bit lost now.
>- Maybe add a Cite gammapy in the Home page?

**Comment by bkhelifi** [comment]
The HowTo section could be improved a bit:
- the ones pointing towards a tutorial could be visualised as the pandas HowTo (@adonath has mentioned [this nice page](https://pandas.pydata.org/docs/getting_started/index.html#getting-started))
- The HowTo page in panda is in `Getting Started` section, not in the User Guide... Should it be a proposal?
- In the HowTo, we could add more daily tricks (Tab completion to get the list of attributes, How to check my background model?, How to estimate the robutness of my 3D analysis with a 1D spectrum? How to deal with large dataset?[1 nb for the DataReduction and serialise, nb for the fit], How to quickly analyse an AGN?[HLI], How I get the number of hours on a source?)

**Comment by bkhelifi** [comment]
The [Recipes](https://gammapy.github.io/gammapy-recipes/_build/html/index.html) should be referenced. As the aims of their creation are sharing 'common pieces of codes' and also promote the User Contributions, one should put some emphasis on them.
However, their are not part of the official documentation so the `Recipes` should be advertised with some caution...
One possibility could be to replace in the `User Guide` the `glossary and references` by the Recipes, the glossary going to top banner for example.

**Comment by adonath** [comment]
A few first unstructured comment from my side:
- In general the design could be made more similar to our webpage https://gammapy.org (e.g. blue menu bar, same fonts, same red for links...)
- It would be very nice to have the version switching, even it just allows for the dev version now. Then the banner warning about the non stable version could be removed.
- I think we should reduce the text on the main page a bit. Especially the 2nd paragraph (`"This webpage contains the Gammapy documentation. You may also check out..."`) Is a possibly a repetition of links from the top line above...
- I agree with @AtreyeeS that the information on the main page of the API documentation per sub-package seems out of place. Instead the information should be moved over to the "User Guide" section.
- I agree with @bkhelifi, that the HowTo could be improved. Some of the content seems poorly motivated or duplicated with tutorials. So one could indeed add the direct link as for pandas or partly just remove entries. I can make a more detailed proposal later...

**Comment by AtreyeeS** [comment]
- In the **Useful links** section on the home page, maybe we can link to

`Useful links: Installation | Source Repository |  Discussions | Recipes |Contact`

**Comment by maxnoe** [comment]
Can we now also update to a current version of sphinx? We are on a vastly outdated 2.4.4

**Comment by Bultako** [comment]
@maxnoe 
I fully agree.
This has already been done in https://github.com/gammapy/gammapy/commit/5cc47299de7e723ffdaf2d27f4f81245ed340a17

**Comment by maxnoe** [comment]
@Bultako Ah, great, missed that sorry.

**Comment by Bultako** [comment]
I think we can close this issue.
Most of the feedback has been addressed in #3817 and #3819  
There is also one specific issue #3818 opened to discuss details on moving intro texts in API

Still two more specific PRs to come about refactoring content in the HowTo and in the Development sections.
