### ISSUE TITLE
FluxPointDataset serialisation

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#3747]
I am a bit confused about reading `FluxPointsDataset`. 

- We have a `FluxPointsDataset.write()`, but no `read`. Should the reading always happen via `FluxPoints` ?
- The spectral model seems to get changed, for ex:

```
from gammapy.datasets import FluxPointsDataset
from gammapy.modeling.models import PowerLawSpectralModel, SkyModel
filename = "$GAMMAPY_DATA/tests/spectrum/flux_points/diff_flux_points.fits"
from gammapy.estimators import FluxPoints
flux_points = FluxPoints.read(filename)
print(flux_points)
```

The output is (as expected)
```
FluxPoints
----------

  geom                   : RegionGeom
  axes                   : ['lon', 'lat', 'energy']
  shape                  : (1, 1, 24)
  quantities             : ['norm', 'norm_err', 'norm_ul']
  ref. model             : pl
  n_sigma                : 1
  n_sigma_ul             : 2.0
  sqrt_ts_threshold_ul   : 2
  sed type init          : dnde
```

Now, I create a `FluxPointDataset`, write it, read it back

```
model = SkyModel(spectral_model=PowerLawSpectralModel())
dataset = FluxPointsDataset(data=flux_points, models=model)
dataset.write("test.fits")
f1 = FluxPoints.read("test.fits")
print(f1)
```

The output is:
```
FluxPoints
----------

  geom                   : RegionGeom
  axes                   : ['lon', 'lat', 'energy']
  shape                  : (1, 1, 24)
  quantities             : ['norm', 'norm_err', 'norm_ul', 'is_ul']
  ref. model             : template
  n_sigma                : 1
  n_sigma_ul             : 2.0
  sqrt_ts_threshold_ul   : 2
  sed type init          : likelihood
```

namely, the ref model is now a `template`

- In the above example, if `models` is not passed on `init` to `FluxPointDataset`, `print(dataset)` fails with 
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/var/folders/v4/62d6cvbj72qbyw23mq2pwxl00000gn/T/ipykernel_16809/2347221472.py in <module>
----> 1 print(dataset)

~/Gammapy-dev/gammapy/gammapy/datasets/flux_points.py in __str__(self)
    209 
    210         str_ += "\t{:32}: {}\n".format(
--> 211             "Number of parameters", len(self.models.parameters)
    212         )
    213         str_ += "\t{:32}: {}\n\n".format(

AttributeError: 'NoneType' object has no attribute 'parameters'
```

***Expected behaviour***

- the read and write method should both deal with datasets
- the model should be conserved
- if a model is not present (or the default should always be a power law?) print should not fail

**Comment by AtreyeeS** [comment]
If my understanding of the expected behaviour is correct, I can implement the fixes @adonath

**Comment by adonath** [comment]
Thanks @AtreyeeS! 

Here are my comments on the three issues:
- I agree for API consistency the `FluxPointsDataset` should have a `read()` method.
- The change of the reference model is actually expected. This is because `gadf` has no separate specification of a parameterized reference model, but just stores the `ref_dnde` and `ref_flux` etc. in the table. The only way to ready this back in Gammapy is a `TemplateSpectralModel`. So the `gadf` format does not "roundtrip" and I think there is no way to avoid this, except for an extension of the `gadf` specification. 
- Yes, printing of the dataset should work even if not model is present.

**Comment by registerrier** [comment]
How should this behave with the `Datasets` serialization that will export a `Models` object as well? Having possibly two models defined on the `FluxPointsDataset` is a bit weird no?

**Comment by AtreyeeS** [comment]
Addressed except the `models` serialisation, which needs to be addressed with the gaff
