### ISSUE TITLE
Dataset serialisation should preserve names

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#3750]
`MapDataset.read()` should ideally read back the original dataset name by default instead of generating a random string. Is there a specific reason why we can't read the original name?

**Comment by adonath** [comment]
Good point @AtreyeeS, I think there is actually no good reason why the name of the dataset is not serialized.

**Comment by adonath** [comment]
Would be good to have this for v1.0rc

**Comment by AtreyeeS** [comment]
What would be a good way to do it? Add an information in `meta` (but we decided not to use the meta_table internally in gammapy anywhere).
While serialising through `Datasets` we force the filename to be the dataset name. But that is not a good idea for serialising individual dataset.

**Comment by registerrier** [comment]
There is already a specific behavior implemented for `SpectrumDatasetOnOff` in ogip format where the name of the dataset is taken from  the `OBSID` keyword. This default behavior should be kept.

An option for the other cases is to use a specific keyword that could be serialized in most hdus.

**Comment by adonath** [comment]
Solved in #4085.
