### ISSUE TITLE
Use context of Pool directly

### ISSUE THREAD

**Issue by maxnoe** [gammapy/gammapy#3755]
**Gammapy version**

Current master

gammapy uses a `multiprocessing.Pool` in two locations and confusingly for me, it is used like this:

```
            with contextlib.closing(Pool(processes=self.n_jobs)) as pool:
                 do_stuff_with_pool
```

Any reason why the context manager of the pool is not used directly?

```
            with Pool(processes=self.n_jobs) as pool:
                 do_stuff_with_pool
```

From the docs:
> Warning
> multiprocessing.pool objects have internal resources that need to be properly managed (like any other resource) by using the pool > as a context manager or by calling close() and terminate() manually. Failure to do this can lead to the process hanging on finalization.

So it seems this might also be the reason for the stuck CI, as using `closing` is not enough, one has to call both `close` and `terminate`? Or just use the pool as context.

**Comment by adonath** [comment]
Thanks @maxnoe! I think the only reason is that the code in the `TSMapEstimator` Gammapy is older than the feature of using the `Pool` directly in the context manager and just has never been updated. The other usage was probably just copied over from the `TSMapEstimator`. So far we haven't seen any issues related to this in the CI.
