### ISSUE TITLE
Require astropy 5.0 for gammapy 1.0

### ISSUE THREAD

**Issue by maxnoe** [gammapy/gammapy#3763]
**Is your feature request related to a problem? Please describe.**

With the recent release of the new LTS release of astropy, bugfix support for older versions of astropy stopped.

To not get into the situation, where gammapy users run into astropy bugs that are not supported with bugfix releases anymore, we should require astropy 5 and see that this LTS releases stays supported by gammapy for the duration of 1.0.

**Comment by adonath** [comment]
Added in #3906.
