### ISSUE TITLE
Implement MapEvaluator.peek()

### ISSUE THREAD

**Issue by adonath** [gammapy/gammapy#3764]
For debugging and possibly for users as well it would be useful to have a `MapEvaluator.peek()` method. It could plot all of the following quantities:
- PSF kernel
- EDisp kernel
- Exposure map
- Npred map

**Comment by AtreyeeS** [comment]
Currently `MapEvaluator` is not visible in the public API. Maybe making it visible will make the peek more useful.

**Comment by adonath** [comment]
Addressed in #4107.
