### ISSUE TITLE
Automate generation and update of a codemeta.json file

### ISSUE THREAD

**Issue by Bultako** [gammapy/gammapy#3775]
We should have a script that automatically generates and updates a `codemeta.json` file with the contributors present in `CITATION.cff` and the library dependencies described in `setup.cfg`

**Comment by adonath** [comment]
I think the best starting point is https://github.com/citation-file-format/cff-converter-python, maybe it does already all we need..

**Comment by vuillaut** [comment]
https://pypi.org/project/CodeMetaPy/ could also help you regarding the Python package information 👀
