### ISSUE TITLE
Save the center of OFF regions, calculated by WobbleRegionsFinder with PointSkyRegions, properly

### ISSUE THREAD

**Issue by chaimain** [gammapy/gammapy#3792]
**Is your feature request related to a problem? Please describe.**
Following the progress in PR #3733, trying with LST-1 DL3 data with RAD_MAX_2D HDU, and using the modified spectral analysis notebook PR #3712, `plot_spectrum_datasets_off_regions()` cannot plot the correct OFF regions.
As @adonath pointed out that the new implementation of this `RegionsFinder` does not store the OFF regions as `RegionGeom` of the `counts_off` object.

**Describe the solution you'd like**
Make the `RegionGeom` handle energy-dependent regions.

**Describe alternatives you've considered**
Save the correct center of the OFF regions, thus generated, so that the `plot_spectrum_datasets_off_regions` can at least plot those correctly.

**Additional context**
![DL4_off_regions](https://user-images.githubusercontent.com/36500590/153431324-1f2b96e4-2afa-4412-ac4f-19386712c938.png)
The current usage of the function, while using LST-1 standard Crab dataset

**Comment by chaimain** [comment]
I could replicate with Max's script using my LST DL3 files, and updated gammapy master.
With 2 OFF regions (just for different cross-check),
![Crab_off_positions_en_dep](https://user-images.githubusercontent.com/36500590/157700507-593674e3-9b56-4255-960d-e71cbfa88378.png)

**Comment by adonath** [comment]
Thanks @maxnoe! Just to confirm, plotting `PointSkyRegion` does not work correctly in Gammapy:
```python3
from gammapy.maps import RegionGeom
from regions import PointSkyRegion
from astropy import units as u
from astropy.coordinates import SkyCoord

centers = SkyCoord([1, 1, -1, -1] * u.deg, [-1, 1, 1, -1] * u.deg)
regions = [PointSkyRegion(_) for _ in centers]
geom = RegionGeom.from_regions(regions=regions)

ax = geom.plot_region()
```

The reason is a bit weird and possibly a bug in `matplotlib`. So the following works:
```python3
import matplotlib.pyplot as plt
from matplotlib.collections import PatchCollection
from regions import PointPixelRegion, PixCoord

ax = plt.subplot()

point = PointPixelRegion(PixCoord(0.5, 0.5))

artist = point.as_artist()

ax.add_artist(artist)
```

While going through the `PatchCollection` (which is the current implementation in Gammapy) does not:
```python3
import matplotlib.pyplot as plt
from matplotlib.collections import PatchCollection
from regions import PointPixelRegion, PixCoord

ax = plt.subplot()

point = PointPixelRegion(PixCoord(0.5, 0.5))

artist = point.as_artist()
collection = PatchCollection([artist])

ax.add_collection(collection)
```
It does not print anything on the plot. I think if adding a `Line2D` object to the `PatchCollection` does not work it should raise instead of silently not plotting it.

As a quick work-around in Gammapy we could change the implementation of `RegionGeom.plot_region()` to use a loop of `ax.add_artist()` instead of using `add_collection()`.

**Comment by maxnoe** [comment]
@adonath `PointPixelRegion.as_artist()` returns a `Line2D`, which is not a `Patch`, so probably why `PatchCollection` is not working.
