### ISSUE TITLE
`FluxPoints.plot()` fails if no error bars are present

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#3811]
`FluxPoints.plot()` fails if no error bars are present on the data. According to the gaff (https://gamma-astro-data-formats.readthedocs.io/en/v0.2/spectra/flux_points/index.html), error columns are optional, so it should not complain.

**Comment by adonath** [comment]
Could you maybe add minimal example that fails? This can be transformed into unit test later...Thanks!
