### ISSUE TITLE
Moving documentation content from API Reference

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#3818]
We discussed in the last call that we should have a proposal for moving content from API reference doc to somewhere more discoverable by the users. Here I try to make a few suggestions.

The said content should probably reside in the **User Guide** section. 

1. The bullet points and the buttons should not co-exist. 
- Probably remove the *Gamma-ray data analysis* link. Add some comprehensive references (or link to http://tevcat.uchicago.edu/reviews.html) in the *Glossary and References* section. 
- *Package Structure* should be a big button, where the bulk of the content can be moved.
- I do not know if `Dependencies` should stay here. It can maybe move to the page after `Getting Started` and `Installation`

2. `Package Structure`: This page can be broken into sub-pages, one for each sub-package.
- The first figure remains as is.
- The sections become clickable links with one line descriptions.
- Every sub-package has one page. The paragraph on the present page + the API reference page text moves here.

Please opine @registerrier @adonath @Bultako @bkhelifi @luca-giunti @LauraOlivera @QRemy @cosimoNigro

**Comment by Bultako** [comment]
Thanks @AtreyeeS for opening this issue.
I have also filed PR #3819 to address the first part of the suggestions concerning the User Guide.
Let's keep this one only to discuss details about moving the API Reference.

In general I like the idea of moving the content of the API index pages to individual subpages of the Package structure. Let's see what others can say, if nobody is against I could open a new PR with a proposal.
