### ISSUE TITLE
Add Energy dependent TemporalModel

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#3824]
I got a request for a TemplateTemporalModel for simulating agn light curves.
Shall I add one @adonath ?

**Comment by adonath** [comment]
How would it differ from https://docs.gammapy.org/0.19/api/gammapy.modeling.models.LightCurveTemplateTemporalModel.html#gammapy.modeling.models.LightCurveTemplateTemporalModel?

**Comment by AtreyeeS** [comment]
Indeed it will not. Sorry for the noise. 
I missed it somehow. 

But why do we add the LightCurve prefix for this specific model? It makes it a bit hard to find.

**Comment by registerrier** [comment]
Maybe this can be more general than the `LightCurveTemporalModel` though. 
Is the request simply connected to a time dependent flux? Or is it really about time dependent spectral variability?
In the former the `LightCurveTemporalModel` is indeed sufficient. In the latter, we need something quite different.
One could imagine a model in the form of a time+energy `RegionNDMap`. It would be a `TemplateTemporalModel` storing a full spectrum (in flux units) in time various time bins. It would then need a `NormSpectralModel` to define a `SkyModel`.

Or we could also rely on the `TemplateNDSpectralModel` recently introduced:
https://github.com/gammapy/gammapy/blob/1accb3a5e3bfc10c337c49fb59755b5f6aaed94b/gammapy/modeling/models/spectral.py#L1566
Could this be used to have a time evaluation as well @QRemy ?

**Comment by QRemy** [comment]
> Or we could also rely on the `TemplateNDSpectralModel` recently introduced:
> 
> https://github.com/gammapy/gammapy/blob/1accb3a5e3bfc10c337c49fb59755b5f6aaed94b/gammapy/modeling/models/spectral.py#L1566
> 
> 
> Could this be used to have a time evaluation as well @QRemy ?

For the `TemplateNDSpectralModel` if the input `RegionNDMap` has a time axis the evaluate method will accept a time argument but the time will also be added as a parameter so it is not really  what is needed here.

**Comment by AtreyeeS** [comment]
Thank you @registerrier ! The final request is apparently indeed for simulating time dependent spectral variability.

I suppose this might be more general than just for TemplateModels. Maybe we can have a `is_energy_dependent` attribute on TemplateModels as well, analogous to `SpatialModels`?

**Comment by AtreyeeS** [comment]
This was discussed at length today during the co-working week, and the plan forward is:

- [ ] Implement numerical implementation on `TemporalModel` @adonath #3925
- [ ] Adapt temporal models to work with an energy axis, and add an example @AtreyeeS #3838 
- [ ] Enable event sampling to work for energy dependent spectral models for point sources @fabiopintore + others
- [ ] Extend `LightCurveTemplateTemporalModel` to have an energy axis. Internally, we can use `Maps` for such structures, the serialisation format can be discussed.

**Comment by registerrier** [comment]
Hi @AtreyeeS . Where do we stand now? Can we cloase the issue?

**Comment by AtreyeeS** [comment]
Closing this issue. Addressed in #4522,  #4418, #4370, #4459
