### ISSUE TITLE
Gammapy module dependency graph

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#385]
We can try and use tools that compute and visualise Python module dependencies to help us figure out a clean sub-package structure for Gammapy.

This is what I found with a quick Google search:
- http://furius.ca/snakefood/
- https://github.com/stefano-maggiolo/pydepgraph
- http://pythonhosted.org/modulegraph/

I tried `snakefood` and with [makefile-sfood](https://gist.github.com/cdeil/d2ba7d9fbee05def5084) and `make -f makefile-sfood` I get this: [gammapy.pdf](https://github.com/gammapy/gammapy/files/41722/gammapy.pdf)

Probably with some scripting / playing around one could make a few graphs of just the top-level sub-packages (`gammapy.data`, `gammapy.spectrum`, ...) and a few others and get some insight.

It would also be great to get a list of circular dependencies printed or plotted.

I'm putting this on the 1.0 milestone, because for 1.0 we should have a clear documented concept of where sub-packages are located in the Gammapy-internal dependency graph.

**Comment by cdeil** [comment]
This could be useful for #636.

**Comment by adonath** [comment]
The sub-package structure has been resolved in https://docs.gammapy.org/0.18.2/development/pigs/pig-016.html and https://docs.gammapy.org/0.18.2/development/pigs/pig-019.html.
