### ISSUE TITLE
`bkg-peak` option in `SafeMaskMaker` always masks the first bin

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#3851]
**Gammapy version**
dev, 0.19

**Bug description**

Running `SafeMaskMaker` with the `bkg-peak` option *always* masks the first bin, irrespective of the lower energy threshold.

**Expected behavior**
No bins should be masked if the lower threshold is above the peak energy

**To Reproduce**

See https://github.com/AtreyeeS/test_notebooks/blob/master/test-bkg-peak.ipynb

**Comment by adonath** [comment]
Fixed by #3873.
