### ISSUE TITLE
Should `wcs ref` be tested to see if geoms align?

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#3853]
**Gammapy version**
0.19
**Bug description**
Performing a cutout on a map does not change the `wcs ref`.
This is an issue when trying to multiply two maps, because the geoms do not 

**To Reproduce**

Say, I have two maps, `exclusion_mask_hgps` and `significance_map`

```
print(exclusion_mask_hgps.geom)
```
WcsGeom

	axes       : ['lon', 'lat']
	shape      : (9400, 500)
	ndim       : 2
	frame      : galactic
	projection : CAR
	center     : 341.0 deg, 0.0 deg
	width      : 188.0 deg x 10.0 deg
	wcs ref    : 341.0 deg, 0.0 deg

```
print(significance_map.geom)
```
WcsGeom

	axes       : ['lon', 'lat']
	shape      : (250, 250)
	ndim       : 2
	frame      : galactic
	projection : CAR
	center     : 313.0 deg, 0.0 deg
	width      : 5.0 deg x 5.0 deg
	wcs ref    : 313.0 deg, 0.0 deg

Now, I do a cutout:

```
geom = significance_map.geom
exclusion_mask_known = exclusion_mask_hgps.cutout(position=geom.center_skydir,
                           width=geom.width[0])
print(exclusion_mask_known.geom)
```

WcsGeom

	axes       : ['lon', 'lat']
	shape      : (250, 250)
	ndim       : 2
	frame      : galactic
	projection : CAR
	center     : 313.0 deg, 0.0 deg
	width      : 5.0 deg x 5.0 deg
	wcs ref    : 341.0 deg, 0.0 deg

A common use case would be to compute `significance_map * exclusion_mask_known`, but this fails because the geoms are not aligned.

Any suggestions @registerrier @adonath @luca-giunti @QRemy

**Comment by AtreyeeS** [comment]
A solution is, of course, to use `interp_to_geom` instead of a cutout, but then we should probably highlight this in documentation

**Comment by adonath** [comment]
@AtreyeeS I don't understand why this should be a bug. If the reference points are different, the WCS projections are not aligned and the arithmetics should fail. This behavior seems completely correct to me. The correct solution if the WCS geoms are not aligned is indeed to interpolate one map to the other geometry.

**Comment by AtreyeeS** [comment]
No it's not a bug. The question was if the `wcs ref` needs to be checked, or we allow map arithmetic in these cases. I guess not, and this is just an issue that `interp_to_geom` is not well exposed in the documentation. I can add it in one of our analysis notebooks

**Comment by adonath** [comment]
@AtreyeeS I think the initial issue was not confirmed, so I'll close the issue here.
