### ISSUE TITLE
Enable temporal model fitting for flux points

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#3859]
It will be useful to be able to fit temporal models directly on the output of the `LightCurveEstimator`, using `FluxPointsDataset`, similar to the available functionality for spectral models.

**Comment by adonath** [comment]
I agree this would be useful. I think it can be achieved rather simple, however there are two different possibilities:
- Allow for `FluxPoints` with a time axis in `FluxPointsDataset` and use the time info from there
- Introduce `FluxPointsDataset.gti` and split the `FluxPoints` per time bin into multiple `FluxPointsDataset` objects. This would be consistent with what we do for the `MapDataset`, this is the less elegant solution, but maybe preferred for consistency for now.

**Comment by AtreyeeS** [comment]
Implemented in #3876
