### ISSUE TITLE
Safe mask functions should not rely on the projected IRFs

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#3878]
Continuing from the discussions in #3873, maybe safe mask functions should not use the binned IRFs, but rather the DL3 irfs directly when possible. This is a reminder issue for v1.0

**Comment by adonath** [comment]
@AtreyeeS This is a backwards incompatible change and it would be bad to introduce it between v1.0rc and v1.0, because it might change analysis results. I'll label the issue after v1.0.
