### ISSUE TITLE
Ability to label colorbars when doing `Map.plot()`

### ISSUE THREAD

**Issue by LauraOlivera** [gammapy/gammapy#3879]
#3610 made it so `WcsMap.plot()` no longer returns the figure, ax and colorbar object. Which means that adding a label to a colorbar like this is no longer possible.
```
fig, ax, cbar = map.plot(add_cbar=True)
cbar.set_label('Test')
```
Which is very inconvenient. Maybe it is me being dense, but in order to get a labelled colorbar I essentially had to make the whole plot from scratch and ditch the `.plot()` method entirely, which felt non-optimal.

I must say I really appreciated the fact that `WcsMap.plot()` returned all those things, and I would have moved to make other plot methods return figures and colorbars and not the other way around. But I think at least it would be nice if we could pass as an argument to `.plot()` something like `cbar_label` to be able to label the colorbar directly from the plotting method.
Is this reasonable?

**Comment by adonath** [comment]
Just quickly: https://github.com/gammapy/gammapy/wiki/Main-API-changes-from-v0.18.2-to-v0.19#map-api

I‘ll comment on more detail in a few days…

**Comment by LauraOlivera** [comment]
Ah so it seems like indeed I am dense :see_no_evil: sorry! That works really well
