### ISSUE TITLE
Wrong coordinates of events when producing a counts map

### ISSUE THREAD

**Issue by SimoneMender** [gammapy/gammapy#3890]
**Gammapy version**
0.20.dev726+g57be15f25

**Bug description**
When producing a counts map, the coordinates of the events seem to be shifted to the source position (current master branch):
![counts_gammapy_0 20 dev726+g57be15f25](https://user-images.githubusercontent.com/18547482/164730999-e1fe6fce-8e18-4f75-b3d6-136f552dfcb7.png)

**Expected behavior**
Background counts are expected to peak at the pointing positions (which is the case for gammapy 0.19):
![counts_gammapy_0 19](https://user-images.githubusercontent.com/18547482/164730945-fd9daa89-b269-4fad-b427-58f383e303bf.png)

**To Reproduce**
```
from gammapy.data import DataStore
from gammapy import __version__
import numpy as np
from astropy.coordinates.angle_utilities import angular_separation
import astropy.units as u
from astropy.coordinates import SkyCoord
from gammapy.makers import MapDatasetMaker
from gammapy.datasets import MapDataset, Datasets
from gammapy.maps import MapAxis, WcsGeom
import matplotlib.pyplot as plt

data_store = DataStore.from_dir(".")
observations = data_store.get_observations(required_irf=['aeff', 'edisp'])

ra_pnt = [obs.events.table.meta['RA_PNT'] for obs in observations] * u.deg
dec_pnt = [obs.events.table.meta['DEC_PNT'] for obs in observations] * u.deg
ra_obj = [obs.events.table.meta['RA_OBJ'] for obs in observations] * u.deg
dec_obj = [obs.events.table.meta['DEC_OBJ'] for obs in observations] * u.deg

separation = angular_separation(ra_pnt, dec_pnt, ra_obj, dec_obj)
mask = np.abs(separation - 1.8 * u.deg) < 0.05 * u.deg
observations18deg = data_store.get_observations(data_store.obs_table['OBS_ID'][mask], required_irf=["aeff", "edisp"])

source_pos = SkyCoord.from_name("Crab")

e_reco = MapAxis.from_energy_bounds(0.07, 2, 1, unit="TeV", name="energy")
geom = WcsGeom.create(skydir=source_pos, axes=[e_reco], width=4, binsz=0.1)
maker = MapDatasetMaker(selection=["counts"]) 

datasets = []

for obs in observations18deg:
    dataset = MapDataset.create(geom, name=str(obs.obs_id))
    dataset = maker.run(dataset, obs)
    datasets.append(dataset)
    
datasets = Datasets(datasets)
plt.figure()
counts = datasets.stack_reduce().counts.plot(add_cbar=True)
plt.tight_layout()
plt.savefig(f"counts_gammapy_{__version__}.png", dpi=300, bbox_inches='tight')
```

**Comment by SimoneMender** [comment]
@adonath The colorbars are produced with default settings `datasets.stack_reduce().counts.plot(add_cbar=True)`. The scale is different because in case of the master branch most events end up in the same bins. I use exactly the same script and data to produce these two plots.

**Comment by adonath** [comment]
For better comparison can you maybe set the colormap min / max  to the same value in both cases? Like: `counts.plot(add_cbar=True, vmin=0, vmax=200)`?

**Comment by SimoneMender** [comment]
Current master branch (0.20.dev726+g57be15f25):
![counts_gammapy_0 20 dev726+g57be15f25](https://user-images.githubusercontent.com/18547482/164738452-65070a23-ba63-42cb-880b-5efd73274853.png)

0.19:
![counts_gammapy_0 19](https://user-images.githubusercontent.com/18547482/164738493-456e4e83-69d6-49e3-aed2-5fd6214d4e05.png)

**Comment by adonath** [comment]
Thanks @SimoneMender, how do the individual (per observation) counts maps look like?

**Comment by SimoneMender** [comment]
@adonath I just made a test with the "$GAMMAPY_DATA/cta-1dc/index/gps" dataset. In this case, it looks good. So probably there is a problem with my dataset and in the different gammapy branches, and there is a difference from where some information is read.

Current master branch (0.20.dev726+g57be15f25):
![counts_gammapy_hess_0 20 dev726+g57be15f25](https://user-images.githubusercontent.com/18547482/164742183-fbe38c6f-a5e5-42f8-bfcf-3
![counts_gammapy_hess_0 19](https://user-images.githubusercontent.com/18547482/164742371-c94d0f2b-ed03-4156-a283-1b4c8c0f5be4.png)
cf80db5bcfb.png)
0.19:


```
from gammapy.data import DataStore
from gammapy import __version__
import numpy as np
from astropy.coordinates.angle_utilities import angular_separation
import astropy.units as u
from astropy.coordinates import SkyCoord
from gammapy.makers import MapDatasetMaker
from gammapy.datasets import MapDataset, Datasets
from gammapy.maps import MapAxis, WcsGeom
import matplotlib.pyplot as plt

data_store = DataStore.from_dir("$GAMMAPY_DATA/cta-1dc/index/gps")
obs_id = [110380, 111140, 111159]
observations = data_store.get_observations(obs_id)

axis = MapAxis.from_edges(
    np.logspace(-1.0, 1.0, 2), unit="TeV", name="energy", interp="log"
)
e_reco = MapAxis.from_energy_bounds(0.07, 2, 1, unit="TeV", name="energy")
source_pos = SkyCoord.from_name("Galactic Center")
geom = WcsGeom.create(skydir=source_pos, axes=[e_reco], width=4, binsz=0.1)
maker = MapDatasetMaker(selection=["counts"]) 

datasets = []

for obs in observations:
    dataset = MapDataset.create(geom, name=str(obs.obs_id))
    dataset = maker.run(dataset, obs)
    datasets.append(dataset)
    
    
datasets = Datasets(datasets)
plt.figure()
counts = datasets.stack_reduce().counts.plot(add_cbar=True)
plt.tight_layout()
plt.savefig(f"counts_gammapy_hess_{__version__}.png", dpi=300, bbox_inches='tight')
```

**Comment by adonath** [comment]
Could you also show the printout of `datasets`, like `print(datasets)`, after the loop and before the stacking?

**Comment by maxnoe** [comment]
The reason was a wrong assumption about the observation order, leading to the wrong observations being selected. See #3891
