### ISSUE TITLE
Change from bundled to external ci-helpers?

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#391]
@bsipocz split out the Astropy `ci-helpers` into a separate package:
https://groups.google.com/forum/#!topic/astropy-dev/2pn_lEdK-w4
https://github.com/astropy/ci-helpers

In Gammapy we currently have a bundled and modified (and probably slightly outdated) version of the ci-helpers copied over from the Astropy repo in https://github.com/gammapy/gammapy/tree/master/.continuous-integration .

Of course I'd like to switch to the external `ci-helpers` and have less duplicated files / scripts to maintain in Gammapy. But it's not clear to me if / how the external ci-helpers can be extended like we need it for Gammapy (using Sherpa, external test repo):
https://github.com/gammapy/gammapy/blob/master/.continuous-integration/travis/setup_dependencies_common.sh#L65
https://github.com/gammapy/gammapy/blob/master/.continuous-integration/travis/setup_dependencies_common.sh#L90

@bsipocz - Do you think using the external `ci-helpers` is a good idea (i.e. less work for the coming years) for Gammapy vs what we have now? What would your advice be e.g. where to put the setup of GAMMAPY_EXTRA or other custom setup commands?

**Comment by bsipocz** [comment]
@cdeil -  Using several channels is supported by ``ci-helpers``, for the Sherpa channel you can use ``$CONDA_CHANNELS`` variable, just need to list the channels space separated.
As for the ``GAMMAPY_EXTRA``, I would put it in .travis.yml, either in the ``before_install``, or in the ``install`` section, after the ``ci-helpers`` cloning.

Regarding the extra work question: If everything goes well and nothing brakes in the ci system, you won't benefit from switching. But it's more probable that there will be some unforeseen changes (like the change in the conda path) that brakes the testing. With ``ci-helpers`` that can be fixed independently of the affiliated package maintenances, so probably less work for gammapy itself.

**Comment by bsipocz** [comment]
btw - If you prefer I can open a PR here to do the transition .

**Comment by cdeil** [comment]
> If you prefer I can open a PR here to do the transition 

A PR would be very welcome!

Since travis-ci is working now, maybe you changing to the new `ci-helpers` scheme will just work, but I wouldn't be surprised if there are conda install issues.
We had a Gammapy tutorial recently and the biggest conda install issues were the result of Sherpa and Astropy (or other packages) pinning different numpy versions and numpy getting down- or up-graded on various conda install commands, or conda refusing to install something (e.g. Sherpa) if the numpy version didn't match. At the end this set of commands worked for everyone I think:
https://github.com/gammapy/PyGamma15/tree/gh-pages/tutorials/gammapy#how-to-prepare
