### ISSUE TITLE
plotting `ConstantSpatialModel`

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#3920]
`Models.plot_regions()/plot_positions()` fails if it contains any `ConstantSpatialModel` (or `ConstantFluxSpatialModel`), with a rather complicated error message. I suppose this is because there is no `position` defined for these models. 

It would be nice to have this fixed before the 1.0rc release.

A quick solution can be to simply   add an exception for `ValueError ` as well here https://github.com/gammapy/gammapy/blob/a68be851d6523742627ed293aa1122c795680f8e/gammapy/modeling/models/core.py#L918.

**Comment by adonath** [comment]
I cannot reproduce the issue:
```python3
from gammapy.modeling.models import (
    SkyModel,
    PowerLawSpectralModel,
    ConstantSpatialModel,
    PointSpatialModel,
    Models
)

m1 = SkyModel(
    spectral_model=PowerLawSpectralModel(),
    spatial_model=ConstantSpatialModel()
)

m2 = SkyModel(
    spectral_model=PowerLawSpectralModel(),
    spatial_model=PointSpatialModel()
)

models = Models([m1, m2])

models.positions

models.to_regions()
```
Which works fine...

**Comment by adonath** [comment]
However `.plot_positions` fails with:

```python
InvalidTransformError: ERROR 7 in wcsset() at line 2658 of file cextern/wcslib/C/wcs.c:
Ill-conditioned coordinate transformation parameter.
ERROR 4 in celset() at line 441 of file cextern/wcslib/C/cel.c:
Ill-conditioned coordinate transformation parameters
No valid solution for latp for these values of phip, phi0, and theta0.
```

This is because there is no region information, that could be used to infer the `WcsGeom` used for plotting.

**Comment by adonath** [comment]
One could either raise a more explicit message here, or maybe default to an all sky geometry in `models.wcs_geom`

**Comment by AtreyeeS** [comment]
@adonath ! Indeed, `models.to_regions` works, but `models.plot_positions` fails

**Comment by adonath** [comment]
OK, this is sort of expected if there is no extension information in the models (such as constant models and pouting sources). One possible solution would be to use an allsky geom as default?

**Comment by AtreyeeS** [comment]
all sky Geom for the region? I do not understand what region a ConstantModel has - it basically fills the full FoV, so I would be fine to not plot it like we do for the template background model

**Comment by adonath** [comment]
Technically the `ConstantSpatialModel` fills the whole sky! However it is just integrated in the FoV. It could be shown as a shaded  underlying region in `Models.plot_regions()`, but probably it is not worth the effort.

The actual error happens in `Models.wcs_geom`, so then my proposal would be:
- Catch the `InvalidTransformError` here as well https://github.com/gammapy/gammapy/blob/master/gammapy/modeling/models/core.py#L930
- Instead of the logging raise an error, saying that the default `WcsGeom` cannot be created. Users should use a custom one...

**Comment by AtreyeeS** [comment]
I encountered this error during a Fermi-LAT analysis, where the error was happening in the isotropic diffuse model created by `create_fermi_isotropic_diffuse_model`. 

The simplest way people will use this might to take a quick look at the contributing models maybe

```
ax1 = fermi_excess["sqrt_ts"].plot()
dataset_fermi.models.plot_regions(ax=ax1)
```

and having an error raised here is rather unpleasant.
Maybe the `wcs` can then be taken from `ax1` ?

**Comment by adonath** [comment]
But this is the implemented and intended behavior: https://github.com/gammapy/gammapy/blob/master/gammapy/modeling/models/core.py#L959

When passing an `ax`, which is a `WcsAxes`, then it should not call `Models.wcs_geom`. I'm not sure why it fails...
