### ISSUE TITLE
NaimaSpectralModel evaluation fails if called with different energy axes

### ISSUE THREAD

**Issue by QRemy** [gammapy/gammapy#3962]
**Gammapy version**
dev, 0.20, 0.19 (and probably all previous)

**Bug description**
`NaimaSpectralModel` evaluation fails if called with different energy axes because of the internal caching in Naima
(for example in a 3d joint fit of Fermi-LAT+HESS datasets).

**To Reproduce**
Run the example code from 
https://docs.gammapy.org/dev/modeling/gallery/spectral/plot_naima.html#naima-spectral-model
and then
```
skymodel = SkyModel(model)
skymodel.spectral_model.plot(energy_bounds=[10 * u.GeV, 80 * u.TeV], energy_power=2)
```
The last line fails with `ValueError: cannot reshape array of size 1 into shape (100,)`
 
**Solution**
In the previous example we can avoid the error setting : `skymodel.spectral_model.radiative_model._memoize = False`.
The performance does not seem to be significantly affected by this change. I did not find a cleaner way to disable the caching in Naima. It is also odd that the cache is not reset when the model is evaluated at different energies, so it may be a Naima issue.
Anyway for now a minimal solution within gammapy could be to disable the caching of the radiative model on init of the `NaimaSpectralModel` adding `self.radiative_model._memoize = use_cache` with use_cache a new option False by default.

**Comment by adonath** [comment]
Your proposed fix sounds good to me, would you mind open a PR for this?
