### ISSUE TITLE
Observation.peek returns empty subplots

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#3963]
**Gammapy version**
0.20

`Observation.peek` is ugly as the first two subplots are empty (for the hdu corresponding to `events` and `gti`)

**Comment by adonath** [comment]
Thanks @AtreyeeS! I guess the number of axes should be adapted to the actual number of available IRFs here...

**Comment by registerrier** [comment]
Issue solved after #3966. Closing.
