### ISSUE TITLE
Implement WcsNDMap.plot_rgb()

### ISSUE THREAD

**Issue by adonath** [gammapy/gammapy#3967]
For convenience it would nice to have a `WcsNDMap.plot_rgb()` and `HpxNDMap.plot_rgb()` method, which allows users to plot a map with three different energy bins as an RGB image. If it contains more or less bins it will through an error. The logic for more bins would be that users resample the energy axis and plot after...

**Comment by registerrier** [comment]
@adonath Having such a function is definitely a nice to have feature. 
I am not sure it should be a method though. Getting a correct 3 color plot require significant adjustment of the color scales and ranges, the function has to be configurable for that. I think this is a case for a standalone function in `gammapy.visualization`.

**Comment by luca-giunti** [comment]
A draft:
```
from astropy.visualization import make_lupton_rgb
def plot_rgb(map_, energy_edges=None, fig=None, ax=None, **kwargs):
    axis = map_.geom.axes["energy"]
    if not energy_edges:
        if len(axis.center) != 3:
            raise ValueError("Energy edges must be provided for maps with more/less than 3 energy bins")
        else:
            energy_edges = axis.edges
            
    if len(energy_edges) != 4:
        raise ValueError("Energy edges length must be equal to 4")    
    
    axis_rgb = MapAxis.from_energy_edges(
        energy_edges.value, 
        unit=energy_edges.unit,
        name="energy",
        interp=axis.interp
    )
    map_rgb = map_.resample_axis(axis_rgb)
    
    data = make_lupton_rgb(
        map_rgb.data[0] / np.nanmax(map_rgb.data[0]),
        map_rgb.data[1] / np.nanmax(map_rgb.data[1]),
        map_rgb.data[2] / np.nanmax(map_rgb.data[2]),
        **kwargs
    )
    
    if fig is None:
        fig = plt.gcf()

    ax = map_rgb._plot_default_axes(ax=ax)
        
    ax.imshow(data)

    if map_rgb.geom.is_allsky:
        ax = map_rgb._plot_format_allsky(ax)
    else:
        ax = map_rgb._plot_format(ax)
        
    ax.autoscale(enable=False)
    
    return ax
```

- Example with a flux map:
![image](https://user-images.githubusercontent.com/47325742/201727635-99a64eeb-767e-455d-9dae-72e6efddb798.png)


- Example with a counts map:
![image](https://user-images.githubusercontent.com/47325742/201727716-fc551fdb-e375-46f1-97d2-ceea9257569e.png)
