### ISSUE TITLE
Size of the error bar in plot_excess method of SpectrumDatasetOnOff are not correct

### ISSUE THREAD

**Issue by mdebony** [gammapy/gammapy#3971]
**Gammapy version**
0.20

**Bug description**
The error bars displayed by the plot_excess method of SpectrumDatasetOnOff are incorrect and not consistent with the one from the residual plot.
For example, the issue in the bin at ~80 GeV is relatively easy to see in this plot.
![image](https://user-images.githubusercontent.com/49060820/171091156-c15ccd4d-b034-4a18-b703-b4b9de0215f2.png)

**Expected behavior**
The bug comes from the size of the error bars being computed by taking the square root of the excess.
I already have a fix where the error bars are computed using the output of counts uncertainty from CountsStatistic object, and I could open a pull request to propose it.

**To Reproduce**
Create a SpectrumDatasetOnOff a fit the spectra on the source. The lower the Signal/Background, the easier it is to see the issue.

**Comment by registerrier** [comment]
Thanks @mdebony . Indeed the `SpectrumDataset.plot_excess` is incorrectly using the square root of the number of excess. The better solution is to use `CountsStatistics` as you propose. 
The easiest solution is to do it with the private `dataset._counts_statistics` now contained in the `Dataset`. Can you open a PR rapidly that could be included in v0.20.1? Otherwise I can do it as well.

**Comment by registerrier** [comment]
@mdebony I am not sure about asymmetric errors. You could also argue about including U.L in that case as well. And you have to check that the computation worked, and replace with symmetric errors if it did not.
`SpectrumDataset.plot_fit()` should be a simple control plot. 

We should have more complete, more configurable plotting functions to produce paper quality plots. But they would probably be better as part of `gammapy.visualization`.

We should open a discussion to determine the desirable features of a spectral fit plot function?

**Comment by mdebony** [comment]
@registerrier 
Ok so if it's fine with you I make a pull request for both plots with simple symmetric error to fix the current issue and we could then discuss further about making these higher quality plots.

**Comment by registerrier** [comment]
@mdebony . Perfect. Please go ahead!

**Comment by adonath** [comment]
Fixed in #3975.
