### ISSUE TITLE
ExcessMapEstimator fails when dataset has no mask

### ISSUE THREAD

**Issue by LauraOlivera** [gammapy/gammapy#3983]
In the `ExcessMapEstimator`, the object `mask` is a map if the dataset has a mask safe or mask fit, but an array if not.

https://github.com/gammapy/gammapy/blob/7b4dab656795455885d5ab80452001f59877adbf/gammapy/estimators/map/excess.py#L215-L220

This causes an error further down because `.convolve()` is used on mask which doesn't work for an array.

https://github.com/gammapy/gammapy/blob/7b4dab656795455885d5ab80452001f59877adbf/gammapy/estimators/map/excess.py#L238-L240

Small example to reproduce the issue
```
from gammapy.maps import WcsGeom, Map, MapAxis
from gammapy.datasets import MapDataset
from gammapy.estimators import ExcessMapEstimator
import astropy.units as u

# Create geom and axes
geom = WcsGeom.create(skydir=(0,0),
              width=2*u.deg,
                     binsz=0.1)

energy = MapAxis.from_bounds(1,100,3, unit="TeV", interp='log', name='energy')
energy_true = MapAxis.from_bounds(1,100,5, unit="TeV", interp='log', name='energy_true')

geom_reco = geom.to_cube([energy])
geom_true = geom.to_cube([energy_true])

# Dummy maps
counts = Map.from_geom(geom_reco, data = 2)
bg = Map.from_geom(geom_reco, data = 1)
exp = Map.from_geom(geom_true, data=10, unit='cm2 s')


# Dataset with only counts, background and exposure
d = MapDataset(counts=counts,
              background=bg,
              exposure=exp)

# Excess Map estimator
e = ExcessMapEstimator("0.1deg", selection_optional = [], energy_edges =[1,100]*u.TeV)

e.run(d)
```

The solution seems very simple: make the mask always be a `Map`.  But I wanted to be sure I am not missing anything...

**Comment by adonath** [comment]
Thanks @LauraOlivera, indeed this is an obvious bug and fix! This probably comes from when `mask` we still allowed and array and the case you mention is just not tested, so it went unnoticed.
