### ISSUE TITLE
Left pane inconsistent for the tutorials

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#3985]
This is a reminder issue of what we discussed in the dev call today.  In the left pane here https://docs.gammapy.org/0.20/tutorials/analysis/1D/spectral_analysis.html we see the subsections of the user guide, with some in bold. This happens for some tutorials (eg: 3D analysis), but not the others (eg: multi instrument). Any idea why?

**Comment by adonath** [comment]
I'll will try to fix this now...
