### ISSUE TITLE
Missing files/directory from gammapy-extras

### ISSUE THREAD

**Issue by bsipocz** [gammapy/gammapy#399]
I'm at a dead end with fixing #392, as it seems that unrelatedly files got disappeared from ``gammapy-extras``?
This is the test function from ``gammapy/spectrum/tests/test_spectrum_analysis.py``, and the ``hess-crab4_pha`` directory seems to be missing from gammapy-extras.

```
@requires_dependency('sherpa')
@requires_data('gammapy-extra')
def test_spectral_fit(tmpdir):

    pha1 = gammapy_extra.filename("datasets/hess-crab4_pha/pha_run23592.pha")
    pha2 = gammapy_extra.filename("datasets/hess-crab4_pha/pha_run23526.pha")
    pha_list = [pha1, pha2]
    fit = SpectralFit(pha_list)
    fit.model = 'PL'
    fit.energy_threshold_low = '100 GeV'
    fit.energy_threshold_high = '10 TeV'
    fit.run(method='sherpa')
    assert_allclose(fit.model.gamma.val, 2.0, rtol = 1e-1)

```

https://travis-ci.org/gammapy/gammapy/jobs/96446120

**Comment by cdeil** [comment]
@joleroi added that test and can add those missing test files on Monday. I can also look around now if I can find or produce them. But this is an unrelated issue form #392, we can / should merge #392 anyways.

@bsipocz How about adding `pytest.mark.xfail` to this test for now?

**Comment by bsipocz** [comment]
yep, ``xfail`` would work, except that I'm off the internet now, until late tomorrow. Also numpy 1.6 is still problematic with sherpa related stuff, so a bit more experimenting is needed for #392.

**Comment by cdeil** [comment]
@bsipocz - If it helps in any way, feel free to bump the minimum required numpy version for Gammapy to 1.7 or even 1.8 (currently 1.6 is listed in setup.py). We need a recent Astropy, and if someone can install that, they can also install a recent Numpy.

**Comment by cdeil** [comment]
@bsipocz - I think the missing files were added in https://github.com/gammapy/gammapy-extra/commit/737cce99d4b00b323481ab8223079f20f2d61b81 . Can you please confirm (and revert the xfail, if you ended up putting it in)?

**Comment by bsipocz** [comment]
The test is still xfailed because of #408. Closing this issue as the file is not missing any more from ``gammapy-extra``
