### ISSUE TITLE
CI: add python3.10 testing

### ISSUE THREAD

**Issue by bsipocz** [gammapy/gammapy#3999]
While looking into #3998, I've noticed that python3.10 doesn't seem to be used in CI, even though the reminder issue has been closed a few months ago (https://github.com/gammapy/gammapy/issues/3619). I didn't dig deep enough into the logs, so if that's the default for one of the jobs without explicitly stating in the configs, then please close this as an errenous bug report.

(However, I've noticed that `gammapy download datasets` doesn't work for python3.10 locally, while it does for 3.9. I'm investigating a little more about those and will report it separately).

**Comment by adonath** [comment]
Thanks @bsipocz, just to confirm: indeed Python 3.10 was not added to the CI and #3619 was not fully addressed.
