### ISSUE TITLE
CAR projection description

### ISSUE THREAD

**Issue by dima137** [gammapy/gammapy#4009]
I believe that CAR stands for Plate Carrée in WCS:
https://docs.astropy.org/en/stable/wcs/supported_projections.html
rather than Cartesian, as mentioned, e.g., here:
https://docs.gammapy.org/0.20.1/api/gammapy.maps.WcsMap.html?highlight=wcsmap%20create#gammapy.maps.WcsMap.create

**Comment by registerrier** [comment]
Thanks @dima137 . Indeed, the correct terminology is Plate-Carrée projection. This must be corrected.

**Comment by registerrier** [comment]
Fixed by #4011
