### ISSUE TITLE
Update the current codemeta.json

### ISSUE THREAD

**Issue by bkhelifi** [gammapy/gammapy#4012]
The file codemeta.json is used for the ESCAPE tools and for SoftwareHeritage/HAL. It should be then up-to-date with correct information, which is not the case today. Any release should contain correct metadata.

As exemple, the current file contains `"softwareVersion": 0.19`, which is obviously not the case.

**Comment by bkhelifi** [comment]
This issue is associated to #3970

**Comment by adonath** [comment]
Done by hand.
