### ISSUE TITLE
Add the cff-validator in our GitHub Actions

### ISSUE THREAD

**Issue by bkhelifi** [gammapy/gammapy#4021]
**Is your feature request related to a problem? Please describe.**
The file CITATION.cff is an important metadata file to which a special care should be made in order to recognize correctly the work achieved by the contributors. The PIG 24 (PR #3970) precises its importance. Its content should be then systematically checked with the latest official `Citation File Format`.

**Describe the solution you'd like**
As describe [here](https://github.com/marketplace/actions/cff-validator),  there is a simple way to add the `cff-validator` in our GitHub actions

**Comment by adonath** [comment]
For v1.0 the file was validated by hand by @registerrier, long term would be good to have this as part of out CI / release pipeline...
