### ISSUE TITLE
Add code of conduct

### ISSUE THREAD

**Issue by adonath** [gammapy/gammapy#4029]
The Gammapy code project should have a code of conduct. See e.g.:

- https://www.python.org/psf/conduct/
- https://www.astropy.org/code_of_conduct.html
- https://sunpy.org/coc

My proposal would be that we just add it to the Gammapy webpage and links to it from the GitHub repo.

**Comment by bkhelifi** [comment]
Dear all,
We have a CoC within Gammapy that was created for the CTAO selection process. It is hidden but it is here: [https://gammapy.org/contribute.html](https://gammapy.org/contribute.html).
My proposal is :
- at least to change the name of the page,
- in the context of the PIG24, I am preparing a PR, that will include a change of the file README.md. I propose to remind this CoC in a new _Contributing_ section
