### ISSUE TITLE
Confidence contours in minuit v2.13

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#4031]
The recent [v2.13 release of iminuit](https://iminuit.readthedocs.io/en/stable/changelog.html#july-17-2022) introduces a change in the way confidence contours are returned:
- now the last point is equal to the first, which makes current tests fail and require adaptation in `gammapy.visualization.plot_contour`. 
- interpolation can be performed directly inside iminuit now.
For now, iminuit is restricted to <2.13, but this should be changed (see #4028)

**Comment by adonath** [comment]
Thanks @registerrier! I think we can adapt to support v2.13 as well by adding a check whether the contour is closed in `plot_contour()` the test could be adapted to not check the length, but really just individual values or we use something like `len(contour) in [10, 11]` with a comment.

**Comment by registerrier** [comment]
There is no restriction on iminuit version after #4064 . Closing issue.
