### ISSUE TITLE
CI fails on linux with numpy v1.23

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#4032]
CI has been failing during the last weeks on linux, while it ran perfectly on MacOs and Windows. A number of tests see their values different by a non negligible amount on linux. Reverting to numpy 1.22 resolves the issue.
For now, the numpy version has been forced <1.23. See #4028

**Comment by adonath** [comment]
I can adapt https://github.com/gammapy/gammapy/pull/4093 to check the numpy versions accordingly and then we see whether the issue remains...

**Comment by adonath** [comment]
See https://github.com/gammapy/gammapy/pull/4116

And the test fail https://github.com/gammapy/gammapy/actions/runs/3138556585/jobs/5098015416#step:7:177

**Comment by adonath** [comment]
Resolved in #4116.
