### ISSUE TITLE
Joint TS maps with more than one dataset

### ISSUE THREAD

**Issue by LauraOlivera** [gammapy/gammapy#4033]
At the moment the `TSMapEstimator` only accepts a single dataset as input. 

However, for an analysis that makes use of event classes, or for joint analysis between different instruments, it would be nice to be able to input more than one dataset to produce a joint TS map.

**Comment by QRemy** [comment]
If the datasets are independent I guess we can just sum the individual TS maps.

**Comment by registerrier** [comment]
> If the datasets are independent I guess we can just sum the individual TS maps.

Performing independent TS Map estimation will yield a collection of independent
fluxes. The resulting summed TS will then have as many d.o.f. as datasets. This might be the correct way to handle independent datasets in disjoint energy ranges (i.e. to allow for unknown spectral slope), but is likely not relevant for event types.

**Comment by QRemy** [comment]
ok so as the estimators works with arrays internally we can loop over the datasets to get their maps then concatenate them pass that array to the function here :
https://github.com/gammapy/gammapy/blob/6c0fc3ad452cb34e01161de4892714096f2bfcf1/gammapy/estimators/map/ts.py#L401-L411 and unfold them afterward.

**Comment by bkhelifi** [comment]
This can be a nice tutorial to add at the end.... ;)

**Comment by adonath** [comment]
One important comment on the implementation: if we achieve that in our `Dataset` and `IRF` objects and model evaluation we pass on extra dimensions in maps correctly, we basically get this feature "for free". We can require that the datasets have the same geometry and handle the multiple datasets as a `LabelMapAxis`.

**Comment by QRemy** [comment]
Resolved by #5353
