### ISSUE TITLE
Update the documentation of the temporal modelling module

### ISSUE THREAD

**Issue by aaguasca** [gammapy/gammapy#4038]
Dear developers, I would like to help homogenise and correct the mathematical expressions and documentation of the temporal modelling module.

If so, I have two questions about the structure of the documentation. They are the following:

- The mathematical expression should appear in the temporal model class? Or in the module gallery? Or in both?
- Do you want a link to the corresponding temporal model in the module gallery? As in the power law temporal model, it appears: "For more information see [PowerLaw temporal model](https://docs.gammapy.org/0.20.1/user-guide/model-gallery/temporal/plot_powerlaw_temporal.html#powerlaw-temporal-model)."

**Comment by adonath** [comment]
Thanks @aaguasca!

All temporal models are documented in detail in the model gallery here: https://github.com/gammapy/gammapy/tree/master/examples/models/temporal

And in the actual API docs, we just define a reference to the model gallery like: https://github.com/gammapy/gammapy/blob/master/gammapy/modeling/models/temporal.py#L224
