### ISSUE TITLE
Use WStat in region based fit using sherpa

### ISSUE THREAD

**Issue by tibaldo** [gammapy/gammapy#404]
The method _run_sherpa_fit in the class SpetraclFit from gammapy/spectrum/spectrum_analysis at present uses the default statistics, which is chi^2. This should be modified to use WStat as appropriate for IACT analysis and implemented in the latest sherpa version.

**Comment by cdeil** [comment]
Closing this issue now, I think it's fully addressed.

Concerning my last comment: the [SpectrumFit](https://gammapy.readthedocs.org/en/latest/api/gammapy.spectrum.SpectrumFit.html) class now appears in the docs.

@joleroi - Pro tip for class-level variables: you can add a docstring on the line after, and it will be picked up by Sphinx autodoc. In this case something like this:

```python
class SpectrumFit(object):

    FLUX_FACTOR = 1e-20
    """TODO: put description of ``FLUX_FACTOR`` here."""

    DEFAULT_STAT = 'wstat'
    """Default fit statistic."""
```
