### ISSUE TITLE
Documentation about logging

### ISSUE THREAD

**Issue by bkhelifi** [gammapy/gammapy#4046]
**Issue description**
In the [logging documentation](https://docs.gammapy.org/0.20.1/development/dev_howto.html#generating-log-messages), one gives an example that does not exist, `EventListDatasetChecker`. The documentation should be adapted to give a correct example.

**Comment by adonath** [comment]
I'll review and adapt the dev docs before v1.0.

**Comment by adonath** [comment]
This slipped through the tight timeline for v1.0, we will address it for v1.1. Developers should start from the dev docs anyway and not the v1.0 docs...
