### ISSUE TITLE
High-level analysis tests for Gammapy

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#405]
Triggered by #404 reported by @tibaldo, I wanted to make an issue with some thoughts and questions for high-level analysis tests in Gammapy.

Most telescopes and tools have "science verification" or "science validation", e.g. for ctools Jürgen is currently checking pull distributions with simulated data (see [here](https://cta-redmine.irap.omp.eu/issues/1555) and [here](https://github.com/ctools/ctools/blob/devel/test/science_verification.py)).

For Gammapy we currently have one morphology fit [here](https://github.com/gammapy/gammapy/blob/master/gammapy/scripts/tests/test_image_fit.py#L12) and one spectrum fit [here](https://github.com/gammapy/gammapy/blob/master/gammapy/spectrum/tests/test_spectrum_analysis.py#L46). It's great to have this, but I think maybe we should set this up a bit differently so that it can scale.

I'd like to propose this plan (timescale a few months, a major effort for the 0.5 release):
- For IACT data, use [hess-crab4](https://github.com/gammapy/gammapy-extra/tree/master/datasets/hess-crab4) for now, and [hess-dr1](https://hess-confluence.desy.de/confluence/display/HESS/HESS+Open+Source+Tools+-+DR+Proposal) as soon as someone puts it together (preferably via a script, making a tarball from the full datasets on lfs1).
- For Fermi-LAT, use the 2FHL dataset (see #386)
- The whole "science verification" is scripted and run nightly or weekly at [gamma-jenkins](https://www.mpi-hd.mpg.de/gamma-jenkins) (which is maintained by me), i.e. should take at most a day to run, preferably only an hour or even less.
- It's exercising the main functionality of Gammapy (morphology and spectrum likelihood fitting, but also background estimation, source detection, .... everything that's high-level and slow), preferably like a user would (i.e. by running the command line tools and checking the output).

Now some questions:
- Does that sound OK or do you think we need more / different datasets?
- Should we put these high-level tests that take more than a few seconds as normal tests, maybe with a `@pytest.mark.slow` or `@pytest.mark.science` marker so that they can be skipped on travis-ci?
- Or should we make separate files / a separate `make science-tests` target for those?
- Should we stick with the usual scheme where reference results are specified in the test code file?
- Or should we come up with a separate scheme where results files with specified precision (number of output digits) are stored for reference, and then we just check that the current results file from a script is identical to the reference?

I might take a stab at this next Monday for the IACT part, because I want to know where we stand and make progress on the HESS DR proposal. Especially setting up the "slow" test marker and skipping those on travis-ci and running those on Jenkins should be pretty easy.

@joleroi, @adonath, @tibaldo, @peger089, anyone interested -- thoughts?

**Comment by tibaldo** [comment]
@cdeil The plan seems reasonable to me, and worthwhile pursuing. I think it would be easier to make this a separate thing from normal tests (a separate target).

**Comment by joleroi** [comment]
Sounds good, I agree with @tibaldo that a separate target is the better solution.

**Comment by cdeil** [comment]
Proposal for Gammapy validation: https://github.com/gammapy/gammapy-benchmarks/tree/master/validation

@adonath @registerrier - Thoughts?

I suggest we iterate a bit on the descriptions today, and then close this issue and open a new one dedicated to each task, and ask for help.

**Comment by registerrier** [comment]
We should put CTA validation first.
I would not but fermi 3FHL as a high priority thing. It is 'nice to have' but I am not sure it is worth spending too much effort now on a validation scheme based on Fermi data.
In particular, we should rely on high level interface as much as possible. Otherwise it will be necessary to re-code the benchmarks after every release. 

Note that ideally we should use more simulated data because they have a 'true' value to compare to. A fully simulated dataset from CTA would be very useful (gamma-ray showers). Something was started this summer by Tarek. I have to see what the status is.

**Comment by cdeil** [comment]
Problem with CTA is that 1DC isn't public, we're not supposed to use it in public repos.
And the CTA prod3 IRFs have serious known issues, e.g. EDISP is noisy:
https://github.com/gammapy/gammapy/issues/2484#issuecomment-545904310
It has been shown in 1DC validation that when you look in detail, there's many issues and unstable results. So it's not a great for validation at the moment.

3FHL catalog is super-well-tested IRFs and science tools that we can compare against, that's why I would use it first to validate Gammapy if time is limited. The hope is that we find one person for each and get some validation for each of those datasets.

Note that I put "We would like to have..." for the first 4 items, without saying which is more important.

@registerrier - Would you still suggest I list CTA 1DC validation first?

> more simulated data, Tarek

OK. But let's try to get these done now, and do better validation next year, no?

**Comment by cdeil** [comment]
> we should rely on high level interface as much as possible. Otherwise it will be necessary to re-code the benchmarks after every release.

Agree 100%. I've added that info to https://github.com/gammapy/gammapy-benchmarks/blob/master/validation/README.md#howto

> Use the high-level Gammapy analysis interface, the goal is to write as little code as possible to test as much as possible.

**Comment by cdeil** [comment]
I'm closing this old issue now.

We had one occurance of `pytest.mark.slow`, which I've removed in https://github.com/gammapy/gammapy/commit/ef1656223cbed2ec78334e65ffae52f12e700279
Generally I think the coding pattern there is OK, to have checks that are slow and rarely needed not as a pytest, but executable via in that case `python -m gammapy.catalog.tests.test_hess`, or, in most cases, to create sub-folders at https://github.com/gammapy/gammapy-benchmarks/blob/master/validation/ and to have slow and detailed high-level validation tests there. @QRemy - Maybe we should add `catalogs` there now and just have a test which checks all catalogs and sources (see https://github.com/gammapy/gammapy/issues/2055#issuecomment-546242383)?

Otherwise we have a plan now for validation we want scripted at https://github.com/gammapy/gammapy-benchmarks/blob/master/validation/ . I'll open one issue per task, and then we'll try to distribute the work to a few people.

**Comment by cdeil** [comment]
For reference, for now, these are the individual issues describing the high-priority validation tasks: #2507, #2509, #2511, #2512. Of course, that will just be the starting point, other suggestions or PRs welcome any time.
