### ISSUE TITLE
Scaling the colour bar to the plot's height

### ISSUE THREAD

**Issue by bkhelifi** [gammapy/gammapy#4052]
**Is your feature request related to a problem? Please describe.**
The colour bars might randomly be larger or smaller than the plot height. This is a known feature of the matplotlib colour bar (see e.g. [link](https://stackoverflow.com/questions/26034777/matplotlib-same-height-for-colorbar-as-for-plot)). In the worse case, the existence of a colour bar can change the size of the plot itself (see e.g. [link](https://stackoverflow.com/questions/57530042/matplotlib-let-color-bar-not-affect-size-and-proportions-of-the-plot)).

**Describe the solution you'd like**
Once the plot size is set, the colour bar should match exactly its size. An utility function (`add_scaled_cbar`) should be added in `visualization.utils`, and then all the plot functions of Gammapy should be updated to use it.

**Additional context**
A possible solution can be found [here](https://www.geeksforgeeks.org/set-matplotlib-colorbar-size-to-match-graph/).

**Comment by adonath** [comment]
Here is another simple implementatio, that I have used in the past:

```python3
def add_cbar(im, ax, fig):
    """Add cbar to a given axis and figure"""
    bbox = ax.get_position()
    loright = bbox.corners()[-2]
    rect = [loright[0] + 0.02, loright[1], 0.02, bbox.height]
    cax = fig.add_axes(rect)
    return fig.colorbar(im, cax=cax, orientation="vertical")
```

**Comment by adonath** [comment]
I'll try to add this before v1.0...

**Comment by Astro-Kirsty** [comment]
Any update here @adonath? 
Or should I try to implement this?

**Comment by adonath** [comment]
@Astro-Kirsty Right now I don't have time to work on this, but feel free to copy, paste and extend the code I shared above.
