### ISSUE TITLE
HLI: addition of configuration parameters for the FluxPointEstimator and the LightCurveEstimator

### ISSUE THREAD

**Issue by bkhelifi** [gammapy/gammapy#4053]
Currently, some important configuration parameters of the `FluxPointEstimator` and the `LightCurveEstimator` are not yet accessible, e.g. `n_sigma_ul`, `n_sigma`.

This add-on is not an API change. It just provides more functionalities for users

**Comment by registerrier** [comment]
Thanks @bkhelifi .

Indeed, there is no explicit `n_sigma` or `n_sigma_ul` in the current version of the `AnalysisConfig`. There are many other such arguments that are not explicitly defined in the `Estimators` but also in other parts of the workflow, e.g. for `BackgroundMakers`.
But there is a mechanism to pass additional arguments, with the `parameters` dictionary.  See :e.g    
https://github.com/gammapy/gammapy/blob/5b2b01d342621ca4266328b0d41c5a82453a87ab/gammapy/analysis/config/docs.yaml#L61

or 

https://github.com/gammapy/gammapy/blob/5b2b01d342621ca4266328b0d41c5a82453a87ab/gammapy/analysis/config/docs.yaml#L44

So you can pass `n_sigma` to the `FluxPointEstimator` by adding an entry in the parameters dict containing `n_sigma : 2`.

Maybe this deserves a bit of documentation somewhere.

**Comment by bkhelifi** [comment]
Thanks for your feedback.... Maybe I can add this into the nb of the PR #4044 ?

**Comment by adonath** [comment]
Solved in #4044.
