### ISSUE TITLE
Add Franceschini 2018 EBL model

### ISSUE THREAD

**Issue by aleberti** [gammapy/gammapy#4055]
It would be nice to have the updated Franceschini EBL model, which was published a few years ago.

The values of optical depth can be found in table 4 of https://www.aanda.org/articles/aa/pdf/2018/06/aa29684e-16.pdf

**Comment by registerrier** [comment]
Thanks @aleberti . Are there other EBL models that would be required? I see that agnpy also refers to this reference:
https://ui.adsabs.harvard.edu/abs/2021MNRAS.507.5144S/abstract

Internally, Gammapy relies on the parameteric table model of XSpec to represent the model. (I think agnpy is using the same format. Is that correct @cosimoNigro ?)
So in practice one needs to create such a fits file from the existing table.

**Comment by cosimoNigro** [comment]
Hello @registerrier, yes `agnpy` is using the same format! For the old EBL models I just copied the FITS files in `gammapy-data`. And for the Saldana Lopez 2021, @IlariaViale created a file with the same format starting from the model values publicly available at https://www.ucm.es/blazars/ebl.

If the Franceschini 2018 model is available somewhere I (or @IlariaViale?) can produce another file.
I think the Saldana Lopez one can go directly in.

**Comment by cosimoNigro** [comment]
Hello @aleberti I am looking into this,

It is difficult to include Table 4 of the Franceschini 2018 paper as an opacity model readable by Gammapy.
The redshift values at which the opacity is calculated are not evenly spaced (and are very few - just ten).
Evenly spaced values of the redshift parameter are needed to define the first table of the [XSPEC Table Model](https://heasarc.gsfc.nasa.gov/docs/heasarc/caldb/docs/memos/ogip_92_009/ogip_92_009.pdf) adopted by Gammapy to describe the opacity models.

The paper provides the EBL intensity as a function of energy for a denser grid of z but these values are also not evenly spaced in redshift (delta_z = 0.2 in Table 1 and 2 and delta_z = 0.3 in Table 3...). The intensity should be integrated with the gamma-gamma cross section to obtain the opacity and I think this is not a job for us and the people producing these models can do it better.

Would it be possible for you to obtain from the authors a denser and evenly spaced grid of opacity values? [The other (2008) Franceschini EBL absorption file in gammapy-data](https://github.com/cosimoNigro/gammapy-data/blob/master/ebl/ebl_franceschini.fits.gz) has 2002 spectra (so the absorption is provided for 2002 redshift values).

**Comment by aleberti** [comment]
Dear @cosimoNigro , FYI I asked the author of the paper if a new table can be provided. I'll let you know if this is possible. And sorry for not reacting before.

**Comment by QRemy** [comment]
Resolved by #4215.
