### ISSUE TITLE
How can we convert units on the axis?

### ISSUE THREAD

**Issue by SeiyaNozaki** [gammapy/gammapy#4057]
I wanted to plot the spectrum using `TeV` instead of `erg`. But it does not help only to set units on y-axis.

In `spectral_analysis.ipynb`, I added the following codes after tab [27]:
```
flux_points_dataset.plot_spectrum()
plt.gca().yaxis.set_units(u.Unit("TeV cm-2 s-1"))
plt.ylim(1e-12, 1e-10)
```
![image](https://user-images.githubusercontent.com/31307823/185937852-5852e859-d060-495b-a40a-b9349398b2ff.png)

What is the way to change units when plotting the spectrum?

**Comment by adonath** [comment]
Have you checked the entry in the HowTo https://docs.gammapy.org/0.20.1/user-guide/howto.html (Choose units for plotting)...?

**Comment by adonath** [comment]
It is important to create and axes call the `.set_units()` first, before plotting anything else on it....

**Comment by SeiyaNozaki** [comment]
@adonath ah, ok, thank you so much! It works now.
