### ISSUE TITLE
Region info in data exported to OGIP format from SpectrumAnalysis class

### ISSUE THREAD

**Issue by tibaldo** [gammapy/gammapy#406]
The current version of the gammapy.spectrum.SpectrumAnalysis write_ogip_data method creates a fits file with an empty primary HDU. In the standard OGIP format this HDU is used to store information on the original dataset and the region used to extract the spectrum.
Having this type of information would be useful, I believe in general for making the files self-explanatory and understandable by users  in the long term.
In my case I was trying to use the files in 3ML, and I'd need this information to decide which sources from the general likelihood model are within the ON region.
@joleroi : do you think it would be possible to add this feature?

**Comment by joleroi** [comment]
Can you point me to a document where things that go into the OGIP primary header are explained?

**Comment by tibaldo** [comment]
https://heasarc.gsfc.nasa.gov/docs/heasarc/ofwg/docs/spectra/ogip_92_007/node5.html
It's not only the header, for the cases I'm familiar with concerning imaging detectors the primary HDU contains an image of the region itself (either the source region or the background region, depending on the file). Not sure what exactly is needed, but we can think about it ...

**Comment by joleroi** [comment]
As far as I can see,  https://heasarc.gsfc.nasa.gov/docs/heasarc/ofwg/docs/spectra/ogip_92_007/node5.html only contains the specs for the PHA data extension

**Comment by tibaldo** [comment]
You are right, it just says " For imaging detectors the primary array can contain an image of the region from which the spectrum was extracted". We should check with X-ray experts what the specs are, but such image was always present in cases I encountered personally.

**Comment by cdeil** [comment]
If you add an image, it should be optional. PHA is super-small, so even a small mask image would dominate the file size and is rarely needed.

Visualising the regions in per-run plots or combined for all runs is very nice and important. It can also be done with ds9 region files and in HESS there's also sometimes counts images produced, which show the accumulated counts from all the off regions, i.e. where all the off regions fall.
@joleroi - if you have time, that's a nice debug plot to have.

**Comment by joleroi** [comment]
see `~gammapy.spectrum.SpectrumObservation.plot_reflected_regions` :wink:

**Comment by cdeil** [comment]
Example of the stacked on- and off-region counts images that are produced by ParisAnalysis as a debug plot by default:

![screen shot 2015-12-17 at 12 01 56](https://cloud.githubusercontent.com/assets/852409/11868132/03bb83f8-a4b6-11e5-8c2d-b7b20506238c.png)

Probably it's possible to combine them and also add contours for exclusion regions and markers for pointing positions on top of the whole counts image, i.e. make something much prettier.

**Comment by cdeil** [comment]
> see ~gammapy.spectrum.SpectrumObservation.plot_reflected_regions

Thanks for the pointer ... I did manage to build Sherpa yesterday and plan to try out your stuff when I get a chance (probably Monday).

**Comment by joleroi** [comment]
ok, thats not yet easily possible, but can be added

**Comment by joleroi** [comment]
@tibaldo : There will be a spec concerning "our" PHA standard on http://gamma-astro-data-formats.readthedocs.org/en/latest/ soon.
Maybe we can move the discussion there?

**Comment by cdeil** [comment]
We could still keep this issue open as a feature request to write an image or more region info and improve the debug plots as a default output when running a spectral analysis, irrespective of what exactly is added to the output files...

**Comment by tibaldo** [comment]
@joleroi : up to you to handle this in the way that you reckon to be the most effective. @cdeil : you are right that the image should be optional to save disk space if it is not needed.
Probably this boils down to a naive question about OGIP pha format: how do people usually keep track of what went into the source and background region?

**Comment by joleroi** [comment]
We have this now as standard debug plot
![debug](https://cloud.githubusercontent.com/assets/11678435/25479625/db622c6e-2b45-11e7-97e9-c5dc32f0e47f.png)

see https://github.com/gammapy/gammapy-extra/blob/master/notebooks/spectrum_analysis.ipynb

**Comment by joleroi** [comment]
Close?

**Comment by cdeil** [comment]
Closing this now.
Of course: concrete issues or pull requests for more / better diagnostics plots are always welcome!
