### ISSUE TITLE
sample_time() fails for LightCurveTemplateTemporalModel

### ISSUE THREAD

**Issue by fabiopintore** [gammapy/gammapy#4063]
**Gammapy version**
0.20.1

**Bug description**
The time sampling in `TemporalModel.sample_time()` for a `LightCurveTemplateTemporalModel` does not work correctly. The time unit handling is unfortunate and the model evaluation is wrong.

**To Reproduce**
Create a `LightCurveTemplateTemporalModel` and run the `sample_time` function. The output lightcurve will be not correct. 

A possible solution is:
- remove the `if` statement in `TemporalModel.sample_time()` 
- use only `TemporalModel.__call__` for all the temporal models  
- improve the current unit test

**Comment by registerrier** [comment]
Solved by #4067. Closing
