### ISSUE TITLE
Storage of the Gammapy version in DL4+ products, one of the most elementary provenance information?

### ISSUE THREAD

**Issue by bkhelifi** [gammapy/gammapy#4068]
**Is your feature request related to a problem? Please describe.**
For the moment, there is no propagation and storage of the Gammapy version into the fits files of DL4+ products. With the multiplication of releases of Gammapy, this provenance information is important, and so basic.
Also, as there is no clear Data Model and data format versioning of DL4+ products (between HESS, CTA, HAWC, Fermi-LAT), we have of own data format that evolves a bit with time (e.g. in v1.x one might add the fit result map whereas it will not be in v1.0). So, the Gammapy version might 'tag' a version of a data format.
As a conclusion, one might store the Gammapy version as a 'minimal identification' of provenance AND data format version.

**Describe the solution you'd like**
In dataset/map, one could store into the FITS header the Gammapy version.  When reading it, if the stored version is different from the used Gammapy version, a warning should be printed.
The same could/should be done for the models, for which there is no 'universal' data model.

**Comment by registerrier** [comment]
Maybe the `CREATOR` keyword could be used. See:
https://fits.gsfc.nasa.gov/users_guide/users_guide/node80.html

| The same could/should be done for the models, for which there is no 'universal' data model.
We don't serialize models as FITS files for now, so this is not really possible 

Note that DL5 products should also carry this information. It is necessary to check all places where this would be required.

Can we find and agree on a solution for v1.0? Or should this be postponed to v1.1?

**Comment by registerrier** [comment]
This should be dealt with by metadata addition in our code base. See e.g. #4792 #4790 #4789.

**Comment by registerrier** [comment]
This is partly implemented. Postponing to 1.3.

**Comment by registerrier** [comment]
This is implemented. Closing now.
