### ISSUE TITLE
Support Python 3.5

### ISSUE THREAD

**Issue by bsipocz** [gammapy/gammapy#407]
I've tried to upgrade the version numbers of python and numpy as part of #392, but the code is not yet compatible, to it's better to do it separately in a new PR.

Travis buildlog is e.g. here: https://travis-ci.org/gammapy/gammapy/builds/99853649

**Comment by cdeil** [comment]
Why does `astropy.utils.exceptions.AstropyDeprecationWarning` make the Python 3.5 build fail on travis-ci?
https://travis-ci.org/gammapy/gammapy/jobs/99853661#L1598

I don't see a build fail locally with Python 3.5 with Gammapy master now that #392 is merged:
```
python3.5 setup.py test -V -a '-k test_cube_to_image'
```
Was that issue resolved there?

In any case: @bsipocz - Do you have time to add a Python 3.5 build for Gammapy on travis-ci? If no, I could try and do this tomorrow.

**Comment by bsipocz** [comment]
It's tricky. The python 3.5 issue isn't showing locally only because I had to turn off ``enable_deprecations_as_exceptions`` in ``gammapy/conftest.py`` due to https://github.com/astropy/astropy/issues/4430

On the other hand most of the fails in the travis log I linked above came from upgrading numpy to 1.10 (recklessly I did both the py3.5, astropy1.1 and np1.10 in one go), so I guess I have some more time this evening to wrap this up.
