### ISSUE TITLE
Bug in the Xspec reference

### ISSUE THREAD

**Issue by mdpunch** [gammapy/gammapy#4094]
**Gammapy version**
0.20.1

**Bug description**
xspec reference on Heasarc is incorrect (points to non-existent page): https://heasarc.nasa.gov/xanadu/xspec/manual/XSappendixStatistics.html

**Expected behavior**
Should point to: https://heasarc.gsfc.nasa.gov/xanadu/xspec/manual/XSappendixStatistics.html 
(i.e. missing gsfc, Goddard Space Flight Centre)

**Other information**
Maybe check other Heasarc references in the docs?

**Comment by bkhelifi** [comment]
Thank you @mdpunch. This is now fixed and all links are checked.
