### ISSUE TITLE
Turn back enable_deprecations_as_exceptions in conftest

### ISSUE THREAD

**Issue by bsipocz** [gammapy/gammapy#411]
Once either https://github.com/astropy/astropy/issues/4430 or upstream sherpa is fixed `enable_deprecations_as_exceptions` can be turned back on in `conftest.py`. At the moment it causes failing tests due to a numpy 1.10 `DeprecationWarning` triggered by sherpa.

**Comment by cdeil** [comment]
I'm not sure if we want this, but anyways there' still #780 open which is a PR and has more infos. Closing this old issue now.
