### ISSUE TITLE
Fix tutorials printing/plotting

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#4143]
This is a reminder issue to continue the cleanup implemented in #4131 and #4132 .
The relevant changes were implemented in `getting started` and `data exploration`, the other sections should be cleaned up before the final 1.0 release

**Comment by AtreyeeS** [comment]
@adonath I think it will take more time to list them rather than fix them! 
I will put in a PR next week

**Comment by adonath** [comment]
That's even better! Thanks @AtreyeeS!
