### ISSUE TITLE
Use negative powers for the representation of units

### ISSUE THREAD

**Issue by aaguasca** [gammapy/gammapy#4145]
Dear developers,

**Context**
Currently, the astropy units are used directly to represent the units of a given axis.

**Describe the solution you'd like**
I propose to use `to_string('latex_inline')` to represent the units of the y-axis with negative powers instead of fractions. Using `.to_string('latex_inline')` may make the unit representation clearer.

**Comment by registerrier** [comment]
Hello @aaguasca . Have you tried to explore the solution you propose?

**Comment by aaguasca** [comment]
Hello @registerrier. Sorry for the delay. Yes, I tried this solution. Please, find below the SED plot from tutorial "analysis-1d/spectral_analysis.ipynb" using `.to_string('latex_inline')`:
![image](https://user-images.githubusercontent.com/82101094/218340935-37f6be81-f233-4ea2-b1b6-b2df1b775641.png)

For this example, I added `.to_string('latex_inline')` to the following lines:
https://github.com/gammapy/gammapy/blob/74c6a76de09ef7c5189ca6e61804469ab96c3fef/gammapy/estimators/points/core.py#L525
https://github.com/gammapy/gammapy/blob/74c6a76de09ef7c5189ca6e61804469ab96c3fef/gammapy/estimators/points/core.py#L617

Adding `.to_string('latex_inline')` should not raise errors because None "units" are prevented, for example by this:
https://github.com/gammapy/gammapy/blob/74c6a76de09ef7c5189ca6e61804469ab96c3fef/gammapy/estimators/points/core.py#L494

If it is OK, I can take care of the PR. I will add `.to_string('latex_inline')` to all relevant axis with expected negative powers.

**Comment by registerrier** [comment]
Hi @aaguasca I suppose it is more efficient to directly use `quantity_support`  from astropy.visualization: 
https://docs.astropy.org/en/stable/api/astropy.visualization.quantity_support.html

**Comment by aaguasca** [comment]
Hi @registerrier, very interesting feature! I suppose using `quantity_support` is necessary to handle the representation of data with different units (but equivalent), but I think we have to define the axis label as well. As far as I know, `quantity_support` only plots the units (with negative powers), but not the name of the variable that has these units. Thus, I think one must specify set_{x,y}label too. Then, when one uses set_{x,y}label, the axis label shows the units without negative powers again.
