### ISSUE TITLE
Backwards support of OBS_MODE  for GADF v0.2

### ISSUE THREAD

**Issue by luca-giunti** [gammapy/gammapy#4171]
**Gammapy version**
1.0rc1

**Bug description**
`obs.fixed_pointing_info.mode` crashes with `ValueError` if the pointing mode stored in the FITS data file is not equal to "WOBBLE", "POINTING" or "DRIFT". This is coded in [`PointingMode.from_gadf_string`](https://github.com/gammapy/gammapy/blob/2d23261187232ffafaff0b56ebbbe8ac5dc944bf/gammapy/data/pointing.py#L48). This in turn blocks the data reduction.

 This is not a good behavior and not even compatible with GADF, because GADF does not impose any list of acceptable `OBS_MODE` meta data (see [here](https://gamma-astro-data-formats.readthedocs.io/en/v0.2/events/events.html?#obs-mode)). 

Example (using H.E.S.S. data):
![image](https://user-images.githubusercontent.com/47325742/199734428-79516f87-efe4-4dab-bb9a-9fd20ad9d0a8.png)

**Comment by adonath** [comment]
Thanks @luca-giunti! The `OBS_MODE` handling was subject to change in GADF v0.3 (which will be released soon). Here is the latest documentation: https://gamma-astro-data-formats.readthedocs.io/en/latest/events/events.html#obs-mode

As `OBS_MODE` is a mandatory keyword, which is used in the data reduction it should fail for invalid values. I don't see any incorrect behavior in Gammapy here...

**Comment by registerrier** [comment]
> As OBS_MODE is a mandatory keyword, which is used in the data reduction it should fail for invalid values. I don't see any incorrect behavior in Gammapy here...

The question is probably whether Gammapy still supports gadf v0.2 or if it supports only v0.3.
This is probably a strong statement to support only v0.3 only a few weeks after it was released.

**Comment by luca-giunti** [comment]
Thank you @adonath for the reference to the new GADF format. However I still find this problematic, since the current behavior assumes that all FITS DL3 data comply with the latest GADF, which is not necessarily true (yet). The prod I am using, for example, is a standard H.E.S.S. prod with `OBS_MODE=ON`. So it should not crash. At most, raise a warning

**Comment by adonath** [comment]
Yes, I see. I checked and it seems indeed in v0.2 basically arbitrary values are allowed (which is very weird BTW...). This means from the Gammapy side we have to check the GADF version?

**Comment by registerrier** [comment]
Currently, we support only 3 cases: `POINTING`, `DRIFT` and `WOBBLE`. The latter case is there to stay compliant with existing data releases (in particular from the joint Crab dataset) but is not listed among the possible keywords in gadf v0.3.

All in all, if we are to stay consistent with the gadf formats, we could:
- Check the `HDUVERS` and 
   - if v<=0.2, set the `FixedPointingInfo.mode` to the exact `OBS_MODE` 
   - else use the current expression (without the `WOBBLE` option)
- in the `MapDatasetMaker.make_meta_table` remove the explicit test to `PointInfo.POINTING` as imposing one or the other is inconsistent with what is stated in gadf v0.2 that `OBS_MODE` is irrelevant for data reduction

**Comment by registerrier** [comment]
This is solved by #4173 . 
Correct handling of format version will require a cleaner separation between Gammapy's internal data model and the data format. For now, we simply assume `POINTING` unless `OBS_MODE` is set to `DRIFT`.
