### ISSUE TITLE
Issues with 1.0rc2 documentation 

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#4188]
This issue is meant to list all issues encountered with documentation in v1.0rc2.

* Release notes
- [x] Incorrect link to commits in main release notes page (points to master instead of main branch)

*  PIGS
- [x] PIG 24 missing form index
- [x] Weird titles in PIG 24 sections

* Tutorials
- [x] Incorrect link to extended source spectral analysis in 1D spectral analysis tutorial
- [x] Incorrect indentation in the exercices of https://docs.gammapy.org/1.0rc2/tutorials/analysis-time/light_curve_simulation.html
- [x] Bullet list of task not correctly rendered in https://docs.gammapy.org/1.0rc2/tutorials/analysis-1d/spectral_analysis.html and https://docs.gammapy.org/1.0rc2/tutorials/api/fitting.html
- [x] link to analysis 2 incorrect in spectral analysis tutorial
- [x] Serilization section not well rendered in https://docs.gammapy.org/1.0rc2/tutorials/data/fermi_lat.html
- [x] Broken link to modeling/index in fitting API tutorial

* Howtos
- [x] Bad links to tutorials in how to (straight to tutorial button). Solved in #4186

**Comment by luca-giunti** [comment]
- Wrong indent [here](https://docs.gammapy.org/1.0rc2/tutorials/api/fitting.html)
![image](https://user-images.githubusercontent.com/47325742/200359574-43a1c68b-ba20-4c1d-a5e5-dde92b88a7b2.png)

- Wrong contour labels [here](https://docs.gammapy.org/1.0rc2/tutorials/api/fitting.html)
![image](https://user-images.githubusercontent.com/47325742/200359978-44e9ea27-aa06-4f5d-80c4-7edfe23f586f.png)

- Titles not well rendered like this appear in many notebooks
![image](https://user-images.githubusercontent.com/47325742/200360320-91f2a493-16ae-480c-a8c0-42f67a0d127e.png)

**Comment by AtreyeeS** [comment]
Reopening this with minor comments:-

- [ ] broken link in line preceding https://docs.gammapy.org/1.0rc2/tutorials/starting/overview.html#exercises ("take a look a the [maps.ipynb](https://docs.gammapy.org/1.0rc2/tutorials/api/maps.ipynb) notebook.")

- [ ] Figures displayed incorrectly while running as a python script in https://docs.gammapy.org/1.0rc2/tutorials/starting/overview.html 

- [ ] Some axes labels are not visible (eg: butterfly plot in https://docs.gammapy.org/1.0rc2/tutorials/api/fitting.html#covariance-and-parameters-errors)

**Comment by AtreyeeS** [comment]
Some more

- [ ] https://docs.gammapy.org/dev/user-guide/howto.html "Implement a custom model -  straight to tutorial" leads to the beginning of the `Models` tutorial, and not the relevant section
- [ ] Broken links to tutorials in https://docs.gammapy.org/dev/getting-started/index.html#tutorials-overview (Maybe we can remove the `straight to tutorial` link and keep only the links for the specific tutorials in this case? )

**Comment by adonath** [comment]
Addressed
