### ISSUE TITLE
Spectrum analysis docs

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#419]
@joleroi - I read through the [spectral-fitting docs](https://gammapy.readthedocs.org/en/latest/spectrum/index.html#spectral-fitting) you wrote for the first time.

Here's some comments / suggestions for improvement:
- [x] Rename [SpectralFit](https://gammapy.readthedocs.org/en/latest/api/gammapy.spectrum.SpectralFit.html) to `SpectrumFit` to bring it in line with the `gammapy.spectrum`, [SpectrumAnalysis](https://gammapy.readthedocs.org/en/latest/api/gammapy.spectrum.SpectrumAnalysis.html) and [SpectrumObservation](https://gammapy.readthedocs.org/en/latest/api/gammapy.spectrum.SpectrumObservation.html) names.
- [x] Split out the [spectrum fitting docs](https://gammapy.readthedocs.org/en/latest/spectrum/index.html#spectral-fitting) on a sub-page? It will grow (reference output, an image), and I think it would be better to keep the top-level `gammapy.spectrum` page short.
- [x] Link from the [SpectrumObservation](https://gammapy.readthedocs.org/en/latest/api/gammapy.spectrum.SpectrumObservation.html) docstring to that docs section (there's an open TODO) and add some comments on the purpose of this class. The attribute summary list doesn't mention that it has counts and aeff, edisp as data members. Maybe expose those via properties, so that they show up in that list?
- [x] The command line example doesn't work for me ... I get a FileNotFound error for `gammapy-extra/test_datasets/spectrum/dummy_exclusion.fits` (see https://gist.github.com/cdeil/1c4d8907e2595074c805)
- [x] The [creating OGIP data example](https://gammapy.readthedocs.org/en/latest/spectrum/index.html#creating-ogip-data) doesn't work for me, I get this error: https://gist.github.com/cdeil/0a6d957c7977cdc4ffc4
- [x] Add line numbers to the YAML files (even if you don't use them yourself in the docs discussion, it's still useful to be able to refer to a given line in discussion with others / tutorials).

I know everything is work in progress, so this is normal.
Still, since others are starting to use that code / contribute to it, @joleroi, maybe it's useful enough to do the extra work and keep the docs examples working, i.e. address these docs issues now?

cc @JouvinLea

**Comment by joleroi** [comment]
Thanks very much!
