### ISSUE TITLE
Implement template background images

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#42]
There is some old code in [pyfact.py](https://github.com/gammapy/gammapy/blob/master/gammapy/utils/pyfact.py) to do template background estimation as in [Rowell 2003](http://adsabs.harvard.edu/abs/2003A%26A...410..389R).

This should be cleaned up (nice API, add docs, add tests) in `gammapy.background`.

**Comment by adonath** [comment]
As we rely on DL3 input data, this method is not really in scope for Gammapy anymore. The creation of background models falls into the responsibility of the people exporting DL3 data.
