### ISSUE TITLE
plotting theta squared plots in each energy bin and controlling ON/OFF normalization

### ISSUE THREAD

**Issue by katagirihide** [gammapy/gammapy#4211]
**Is your feature request related to a problem? Please describe.**
When obtaining flux points by using FluxPointsEstimator,  SpectrumDatasetOnOff datasets are required.
In my understanding, SpectrumDatasetOnOff is produced by finding OFF source regions with some filters (GTI, exclusion masks, etc.) and calculating counts, excess, acceptance, etc. internally, so we cannot explicitly know how the source data are chosen and check the validity of OFF source data.

**Describe the solution you'd like**
The followings are one of the possible solutions:

1. The validity of OFF source data can be checked by plotting theta squared plots in each energy bin.

2. One of the possible issues of OFF source data which we find from the theta square plots is the difference of acceptance between ON/OFF. It would be useful if there is the option to select whether ON/OFF normalization (like using the data with 0.2 < theta squared < 0.4) is applied when calculating excess, etc. I guess at the moment the normalization is not applied.

**Additional context**
It would be helpful if there were detailed documents about SpectrumDatasetOnOff and FluxPointsEstimator. At present, we have to read source codes to understand the theories of SpectrumDatasetOnOff and FluxPointsEstimator, I think.

**Comment by adonath** [comment]
Thanks @katagirihide! I'm not sure I understand the exact feature requests here. Let me try:

- Add and `energy_edges` keyword to [make_theta_squared_table](https://docs.gammapy.org/1.0/api/gammapy.makers.utils.make_theta_squared_table.html#gammapy.makers.utils.make_theta_squared_table) , such that one can estimate theta squared distributions in energy bins?
- The `SpectrumDatasetOnOff` is hard coded to the so called `wstat` statistics. This has analytically defined max. likelihood solutions for excess, expected backgroundm significance etc. This what is typically  known as the Li&Ma solution. The definitions are shown here: https://docs.gammapy.org/1.0/user-guide/stats/index.html#stats . The ON / OFF normalization happens via the alpha parameter, which is also applied when computing excess...

**Comment by katagirihide** [comment]
Thanks @adonath !

> Thanks @katagirihide! I'm not sure I understand the exact feature requests here. Let me try:
> 
>     * Add and `energy_edges` keyword to [make_theta_squared_table](https://docs.gammapy.org/1.0/api/gammapy.makers.utils.make_theta_squared_table.html#gammapy.makers.utils.make_theta_squared_table) , such that one can estimate theta squared distributions in energy bins?

I tried to use 'energy_edges' keyword with gammapy ver.0.20.1. as follows.
It seems that the keyword 'energy_edges' has not been implemented yet. 
![image](https://user-images.githubusercontent.com/36106436/202827532-ba30a20b-76e2-4c1f-ac0a-d814c362d05d.png)

>     * The `SpectrumDatasetOnOff` is hard coded to the so called `wstat` statistics. This has analytically defined max. likelihood solutions for excess, expected backgroundm significance etc. This what is typically  known as the Li&Ma solution. The definitions are shown here: https://docs.gammapy.org/1.0/user-guide/stats/index.html#stats . The ON / OFF normalization happens via the alpha parameter, which is also applied when computing excess...

In the above definition, alpha is defined as "Background efficiency ratio". Is it defined as t_ON/t_OFF like Li&Ma's convection or estimated by using counts of ON and OFF?

**Comment by adonath** [comment]
> I tried to use 'energy_edges' keyword with gammapy ver.0.20.1. as follows.
It seems that the keyword 'energy_edges' has not been implemented yet.

Oh, yes this does not exist yet. I was just trying to re-phrase you request, to make sure I understood correctly.

> In the above definition, alpha is defined as "Background efficiency ratio". Is it defined as t_ON/t_OFF like Li&Ma's convection or estimated by using counts of ON and OFF?

Yes. it is defined as t_ON/t_OFF as in Li&Ma's convention.

**Comment by katagirihide** [comment]
> > I tried to use 'energy_edges' keyword with gammapy ver.0.20.1. as follows.
> > It seems that the keyword 'energy_edges' has not been implemented yet.
> 
> Oh, yes this does not exist yet. I was just trying to re-phrase you request, to make sure I understood correctly.

I misunderstood. Let me explain the situation more clearly.

When we make flux points, I think we basically use [FluxPointsEstimator](https://docs.gammapy.org/1.0/api/gammapy.estimators.FluxPointsEstimator.html#gammapy.estimators.FluxPointsEstimator) as is done in https://docs.gammapy.org/1.0/tutorials/analysis-1d/spectral_analysis.html.
"""
fpe = FluxPointsEstimator(
    energy_edges=energy_edges, source="crab", selection_optional="all"
)
flux_points = fpe.run(datasets=datasets)
"""

The type of the datasets given to FluxPointsEstimater.run() in this example is SpectrumDatasetOnOFF where its background positions are defined **internally** by ReflectedRegionsBackgroundMaker with exclusion mask and safe mask.
"""
geom = RegionGeom.create(region=on_region, axes=[energy_axis])
dataset_empty = SpectrumDataset.create(geom=geom, energy_axis_true=energy_axis_true)
dataset_maker = SpectrumDatasetMaker(
    containment_correction=True, selection=["counts", "exposure", "edisp"]
)
bkg_maker = ReflectedRegionsBackgroundMaker(exclusion_mask=exclusion_mask)
safe_mask_masker = SafeMaskMaker(methods=["aeff-max"], aeff_percent=10)

datasets = Datasets()

for obs_id, observation in zip(obs_ids, observations):
    dataset = dataset_maker.run(dataset_empty.copy(name=str(obs_id)), observation)
    dataset_on_off = bkg_maker.run(dataset, observation)
    dataset_on_off = safe_mask_masker.run(dataset_on_off, observation)
    datasets.append(dataset_on_off)
"""

On the other hand, theta square plots from make_theta_squared_table seem to require Observation data directly as done in https://docs.gammapy.org/1.0/tutorials/data/hess.html 
"""
observations = data_store.get_observations([23523, 23526])
theta2_table = make_theta_squared_table(
    observations=observations,
    position=position,
    theta_squared_axis=theta2_axis,
)
"""

So I have difficulty in making theta squared plots in each energy. 
Also, make_theta_squared_table requires a OFF source position.
For SpectrumDataSetOnOff, OFF source positions are defined by a background maker in a complicated way with some masks, so it does not seem easy to give these positions to make_theta_squared_table and merge the resulting theta squared plots from each observation somehow. I have quite limited experience with gammapy. If you could suggest a good way to do such things within the current gammapy functions, that would be great.



> > In the above definition, alpha is defined as "Background efficiency ratio". Is it defined as t_ON/t_OFF like Li&Ma's convection or estimated by using counts of ON and OFF?
> 
> Yes. it is defined as t_ON/t_OFF as in Li&Ma's convention.

I found that the latter part of my request was the similar request as 
https://github.com/gammapy/gammapy/issues/3955 ,
which is going to be implemented in ver.1.2.

**Comment by chaimain** [comment]
I have been using a notebook with custom functions to plot theta2 using the DL3 datasets, building upon the Gammapy functions to add the following features -
- having separate energy axes
- evaluating n Wobble OFF regions based on the ON regions and selecting any combination of those OFF regions
- evaluating the Li&Ma significance for a given fixed theta2 cut for each theta2 plot
- producing theta2 plots for each night of observation and adding such tables and saving them to a FITS file
- using the CTA-suggested colour-blind friendly plotting style

However, I have not been able to add more generalizations to it, with respect to 
- Custom ON/OFF normalization (although it should be easy to change it)
- using the WobbleRegionsFinder or other Background regions finder of gammapy to find the OFF regions
- using the RAD_MAX table to get the correct theta2 cut for the given energy edges in the RAD_MAX table
- make "nicer plots"
- fine-tune it by checking for warnings, possible errors, etc, so as to include it in gammapy

I attach theta2 plot of the Crab Nebula using the dataset selected for the LST1 Performance paper (to be submitted soon) from an earlier production and the notebook. Maybe they can be helpful for your use, and perhaps somebody can work on including it or something similar to gammapy. 
Sorry, but I am unable to pursue this work further myself currently.

![Theta2_counts_Crab_117_wob_obs_Run_2914_to_7277_20_en_bins_cut_04_std](https://user-images.githubusercontent.com/36500590/202928307-3b741806-55ca-4e57-b2fc-7a7ff3176bb5.png)
[plot_custom_theta2_from_dl3_en_dep.zip](https://github.com/gammapy/gammapy/files/10050798/plot_custom_theta2_from_dl3_en_dep.zip)

**Comment by katagirihide** [comment]
Thanks a lot! Perhaps it would be useful if such functions were implemented in the next version gammapy.

**Comment by katagirihide** [comment]
> Thanks a lot! Perhaps it would be useful if such functions were implemented in the next version gammapy.
[post_DL3_analysis_with_theta2-Copy1.zip](https://github.com/gammapy/gammapy/files/10097430/post_DL3_analysis_with_theta2-Copy1.zip)

I attached the notebook, where the theta squared plot is created by time normalization and the counts and sqrt_ts are the same as those obtained from FluxPointsEstimater.

**Comment by chaimain** [comment]
@katagirihide could you please recheck/resend your notebook? I am unable to read it. Thanks!

**Comment by katagirihide** [comment]
> @katagirihide could you please recheck/resend your notebook? I am unable to read it. Thanks!

@chaimain How about this one? I changed from Windows zip to linux gzip.

**Comment by chaimain** [comment]
> @chaimain How about this one? I changed from Windows zip to linux gzip.

Ah yes! I forgot about the distinction in compression styles! Sorry about that, and thanks again for the notebook!
