### ISSUE TITLE
plot_spectrum_datasets_off_regions failing with many datasets

### ISSUE THREAD

**Issue by LukasNickel** [gammapy/gammapy#4222]
**Gammapy version**
```
In [3]: gammapy.__version__
Out[3]: '1.0'

In [5]: matplotlib.__version__
Out[5]: '3.6.2'
```

**Bug description**
If you pass too many datasets to `plot_spectrum_datasets_off_regions` it fails with a key_error:

```python
----> 1 plot_spectrum_datasets_off_regions(datasets)

File /scratch/lnickel/conda/envs/M87/lib/python3.9/site-packages/gammapy/visualization/utils.py:90, in plot_spectrum_datasets_off_regions(datasets, ax, legend, legend_kwargs, **kwargs)
     88 plot_kwargs = kwargs.copy()
     89 plot_kwargs["facecolor"] = "None"
---> 90 plot_kwargs.setdefault("edgecolor", props.pop("color"))
     91 plot_kwargs.update(props)
     93 dataset.counts_off.plot_region(ax, **plot_kwargs)

KeyError: 'color'
```
This is due to there being more datasets than colors in the `prop_cycle`

**Expected behavior**
It should reuse colors or default to the first/last one or just black.

**To Reproduce**
This MWE is really only matplotlib, but it shows the problem:
```python
for i, c in zip(range(20), plt.rcParams["axes.prop_cycle"]()):
    print(i, c.pop("color"))
```
Note that if you dont create the itertools object (so just `plt.rcParams["axes.prop_cycle"]`), zip will stop if there are no more colors left,
but this way it will continue and try to start from the beginning again. But it cannot do that, because we popped the elements before.

So if you instead write:
```python
for i, c in zip(range(20), plt.rcParams["axes.prop_cycle"]()):
    print(i, c)
```
it will loop around and if you write

```python
for i, c in zip(range(20), plt.rcParams["axes.prop_cycle"]):
    print(i, c)
```
it stops after all colors have been used once

**Other information**
This is the relevant code:
https://github.com/gammapy/gammapy/blob/647c0001a08fbda055a7aed4bf62747e08ea38e7/gammapy/visualization/utils.py#L85-L93

This did work with the same datasets on an older gammapy-version, but I do not see any changes there. Maybe the behaviour of matplotlib changed at some point regarding the popping of elements.

**Comment by adonath** [comment]
Thanks @LukasNickel for reporting. At first glance it seems indeed the behavior in matplotlib has changed. However the workaround is simple, you can specify the `prop_cycle` from outside:

```python3
import matplotlib.pyplot as plt

prop_cycle = plt.cycler(color=list('rgb'), ls=['--', '-', ':']))
plot_spectrum_datasets_off_regions(..., prop_cycle=prop_cycle)

```

**Comment by LukasNickel** [comment]
That will also only work if the self-defined cycler has enough colors though, right?
Not a huge deal I suppose, but slightly annoying and not trivial to understand from the error message if one is not experienced in python/matplotlib.

**Comment by adonath** [comment]
> That will also only work if the self-defined cycler has enough colors though, right?

Yes

I'll take a few min and try to find out what has changed in matplotlib.

**Comment by adonath** [comment]
@LukasNickel However you can easily increase the length of the default cycler like:

```python3
import matplotlib.pyplot as plt

prop_cycle = 10 * plt.rcParams["axes.prop_cycle"]
plot_spectrum_datasets_off_regions(..., prop_cycle=prop_cycle)
```

**Comment by adonath** [comment]
I have looked at the implementation and found the following:

- https://github.com/matplotlib/cycler/blob/main/cycler.py#L133 relies on `itertools.cycle`, which caches after the first iteration, see https://docs.python.org/3/library/itertools.html#itertools.cycle
- So basically the `.pop()` should have never worked...not sure what is going on...
