### ISSUE TITLE
Can not load gadf files with "wrong" pointing meta data

### ISSUE THREAD

**Issue by LukasNickel** [gammapy/gammapy#4223]
**Gammapy version**
1.0

**Bug description**
I have some old files with a list argument in the `POINTING` meta attribute.
In that case this check:
https://github.com/gammapy/gammapy/blob/647c0001a08fbda055a7aed4bf62747e08ea38e7/gammapy/data/pointing.py#L56
fails as the value is not a string, but a list.

It worked at an earlier point (0.20? 0.19? From a quick look into the code I assume 0.19) and the comments mention, that this keyword is not well defined in gadf < 0.3 so it would argue it should not break.

**Expected behavior**
It should default to `POINTING` mode as it did before.
Protect it with an `is_instance(str)` or make it a string before?

One could also say, that its just not supported anymore. Not a huge deal to edit some metadata.

**Comment by adonath** [comment]
Thanks for the issue @LukasNickel! 

As far as I know the `OBS_MODE` has always been specified by a string. This is documented in GADF v0.1. and v0.2 as well: 

- https://gamma-astro-data-formats.readthedocs.io/en/v0.2/events/events.html#optional-header-keywords
- https://gamma-astro-data-formats.readthedocs.io/en/v0.1/events/index.html#optional-header-keywords

What changed in GADF v0.3 is that the actual allowed values are now defined https://gamma-astro-data-formats.readthedocs.io/en/v0.3/events/events.html#obs-mode, the type has not changed, it still only a string. If a list has worked in the past in Gammapy, then it worked by accident.

**Comment by LukasNickel** [comment]
You are right, it does explicitly mention it being a string.
I guess in that case it is up to the creator of the files to make sure they follow the specs.
