### ISSUE TITLE
GTI definition / API

### ISSUE THREAD

**Issue by maxnoe** [gammapy/gammapy#4240]
**Is your feature request related to a problem? Please describe.**

Part of the ongoing work to support multiple data formats / versions and #3767 

* [ ] Define API / data structure for GTI (e.g. table vs. time attributes)
* [ ] remove reliance on meta dict in properties
* [ ] add methods to convert to / from fits / GADF
* [ ] validate table in `__init__`

**Comment by registerrier** [comment]
A PR implementing all points above is proposed here #4326 . 
The proposed data structure is a `Table` containing start and stop times as `Time` objects. A reference `Time` is kept as well as metadata.
