### ISSUE TITLE
Event Simulation API

### ISSUE THREAD

**Issue by maxnoe** [gammapy/gammapy#4247]
One of the remaining large blocks where the GADF (and some other???) data formats are hard coded at positions where I don't expect them is the `MapDatasetEventsMaker`, specifically the event_list_meta function of that class.

It seems very hard to change this class in a backwards compatible way, so I would propose to deprecate that class entirely and write a new class called `SimulatedObservationMaker` that takes an `observation` (with IRFs but no event list) and source `Models` and returns the observation filled with events.

The resulting observation can then be written using the normal Observation.write method to any format supported by gammapy or just immediately analyzed.

**Comment by QRemy** [comment]
Resolved by #4917 and #3711
