### ISSUE TITLE
Simulations in the absence of a background model

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#4254]
It can be useful to simulate DL4 observations in the absence of a background model, ie, where the off counts are obtained from real off observations (eg, for pulsars or OnOff Spectral datasets). The observed background here is one realisation of the random variable.

The main point here is to handle the statistics correctly. I dont know if it can be done by simply passing the correct `npred_background` to the `fake` method, or it requires some additional code.

opinions @registerrier @bkhelifi @QRemy @facero

**Comment by AtreyeeS** [comment]
I think the simplest thing to here would be

- Update https://docs.gammapy.org/1.0/tutorials/analysis-1d/spectrum_simulation.html#on-off-analysis to show an example with the MAGIC Crab runs. 
- `dataset_on_off.fake` should take `npred_background=dataset_on_off.background`. The `npred_background` gives the marginalised background estimate, so it changes with the source model.

Or, we can also update https://docs.gammapy.org/1.0/tutorials/analysis-1d/spectral_analysis_rad_max.html to include a section on simulations.

**Comment by registerrier** [comment]
In the absence of a background model, the only possible thing would be to bootstrap on the `counts_off` themselves. For instance, by using `np.random.choice`.

**Comment by adonath** [comment]
Just for completeness I wanted to mention the following approach:

- One could work with 2 datasets: one "on" and one "off" dataset.
- One could define a parametric model for the npred of the  background, e.g. some power law with a turn over at low energies
- The background model would be shared between the on and off dataset, while the source model is only fitted to the on dataset
- This gives an estimation for the background npred model.

**Comment by AtreyeeS** [comment]
@adonath This is indeed interesting, but I think there are still some advantages to using on-off stat in certain cases.
I added a line about your proposal in #4427

**Comment by adonath** [comment]
@AtreyeeS One problem of "wstat" that is often ignored, is the lack of a physical prior assumption / model in the background. The energy bins in the background are assumed to be uncorrelated, which is not true. "wstat" always "overfits" to the background, thus the background model does not generalize to other observations. This problem is apparent for cubes (but for spectra too), where one would end up with a different estimate for the background predicted counts in each pixels. However a real or physical background model should typically behave smoothly. Unfortunately I have never seen anybody discuss this problem, so I'm not aware of any references and magnitude of this effect. I think some assumption about smoothness of the background should be required.

**Comment by adonath** [comment]
@AtreyeeS If you introduce a piecewise power-law model for the predicted background counts and you go to the limit, where you have one node per energy bin, the approach that I suggested above and what happens with `wstat` becomes equivalent. Assuming that the background is uncorrelated in the energy bins as in "wstat" is just not a good physical assumption.

**Comment by adonath** [comment]
One way to improve this would be to use "marginalisation" of the background instead of "profile likelihood". @registerrier Are you aware of any references, that do this for "wstat"?

**Comment by registerrier** [comment]
I am not sure I understand here.
- WStat is indeed a profile likelihood method. It makes the minimal assumption you can make that bkg values are independent in all bins.
- Marginalization consists in multiplying the profile likelihood by a prior on the value of the bkg value and integrate over it. It usually yields broader errors. But it does not necessarily mean you take into account a model of the bkg distribution with energy.
- Now I agree that if you have ON and OFF observations, you can try to fit a piecewise bkg model to both ON and OFF. In the limit where you have as many nodes as energy bins, you should recover the wstat (profile likelihood) result. But you loose the analytical formula. Yet, one could numerically profile the likelihood (e.g. by introducing a minimization when computing `npred_background`). Is this what you mean here @adonath ?
- One could even use a penalized ML for the background model to unfold it while imposing some regularity constraint.

**Comment by adonath** [comment]
> WStat is indeed a profile likelihood method. It makes the minimal assumption you can make that bkg values are independent in all bins.

Yes, the assumption is minimal, but I think it is not physical. You would expect the background rate to be correlated between bins in energy. 

> Marginalization consists in multiplying the profile likelihood by a prior on the value of the bkg value and integrate over it. It usually yields broader errors. But it does not necessarily mean you take into account a model of the bkg distribution with energy.

Yes, but in a "true Bayesian" sense you could integrate out the model on the background. You would basically integrate over all possible background models, if the makes sense.

> Now I agree that if you have ON and OFF observations, you can try to fit a piecewise bkg model to both ON and OFF. In the limit where you have as many nodes as energy bins, you should recover the wstat (profile likelihood) result. But you loose the analytical formula. Yet, one could numerically profile the likelihood (e.g. by introducing a minimization when computing npred_background). Is this what you mean here @adonath ?

Yes, exactly that's what I meant!

> One could even use a penalized ML for the background model to unfold it while imposing some regularity constraint.

Yes, except that I think the unfolding is less important. That background is typically expected to be smooth without "sharp" features.
