### ISSUE TITLE
Changing FluxPoints.sqrt_ts_threshold_ul does not update FluxPoints.has_ul property

### ISSUE THREAD

**Issue by cosimoNigro** [gammapy/gammapy#4259]
**Gammapy version**
v1.0

**Bug description**
Setting a different `FluxPoints.sqrt_ts_threshold_ul` updates the `FluxPoints.is_ul` property but not the `has_ul` property.
[This flag is used for plotting](https://github.com/gammapy/gammapy/blob/main/gammapy/estimators/points/core.py#L502), and hence, even if you change the threshold to define your ULs, they will be still plotted as normal flux points.

**To Reproduce**
You can use the same snippet in #4257.
After the `IPython` session opens:

```
In [1]: lc_1.sqrt_ts.data.flatten()
Out[1]: array([98.33583687, 92.0026354 , 77.88428745, 83.78151587])

In [2]: lc_1.is_ul.data.flatten()
Out[2]: array([False, False, False, False])

In [3]: lc_1.sqrt_ts_threshold_ul = 80

In [4]: lc_1.is_ul.data.flatten()
Out[4]: array([False, False,  True, False])

In [5]: lc_1.has_ul
Out[5]: False
```

**Comment by adonath** [comment]
Thanks @cosimoNigro! 

I think there is flaw somewhere in the logic: `.has_ul` checks whether the `norm_ul` quantity is defined. So whether there are upper limits defined at all, not whether they should be used:

```
# this is how it is defined
has_ul = "norm_ul" in fp.data

# this is what you expected?
has_ul = any(fp.is_ul)
```

So in your case it seems `lc_1` does not have the UL information at all. So it is impossible to plot. I guess the way to improve the behavior would be to make users aware when setting e.g. `lc_1.sqrt_ts_threshold_ul = 80`, that there is no UL information at all....

**Comment by cosimoNigro** [comment]
Sorry, this was a misunderstanding from my side.
`has_ul` basically checks if there was `ul` in the `selection_otpional` argument of the estimator, right?

Sorry for the noise.
