### ISSUE TITLE
CI fails with scipy 1.10

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#4265]
The recent release of scipy 1.10 creates CI fails with functions having no signature. See e.g.:
https://github.com/gammapy/gammapy/actions/runs/3845508794/jobs/6549733223

For now, environment-dev.yml (https://github.com/gammapy/gammapy/commit/de8db1f1770a5ece6dd967116895b67a1f28285b) (for gammapy-benchmark) and setup.cfg (https://github.com/gammapy/gammapy/commit/269a64c17d51180fafa8d7c464d9173a04349145) have been modified to enforce scipy<1.10.

**Comment by olebole** [comment]
Is there any progress with this? The next Debian "Bookworm" release will come with scipy 1.10, and if we want to keep Gammapy in Debian, it should be compatible.

**Comment by registerrier** [comment]
The issue here is connected with this issue in scipy 1.10: https://github.com/scipy/scipy/issues/17718
It has been corrected here https://github.com/scipy/scipy/pull/17726 and should probably be released as part of scipy 1.10.1.

**Comment by adonath** [comment]
I think we could do a type cast to `float64` in the `RegularGridInterpolator`, this should be backwards compatible and will support all Scipy versions...
