### ISSUE TITLE
Preserve dataset names during copy?

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#4296]
I think a common issue is arising because we do not properly explain the importance of setting dataset name on the model.
When having a code like
```
models =  Models(bkg_model, model1, model2...)
dataset1.models = models
dataset2  = dataset1.copy()
dataset2.models = models
```
where the `bkg_model` is attached to dataset1, `dataset2` does not have a background model. For the end user, this mistake is rather difficult to notice.

I do not know the best way to solve it. Maybe explicitly mention this in the documentation? Or preserve the name during `copy`?

**Comment by registerrier** [comment]
Hi @AtreyeeS do we have a solution here that we can implement for v1.0.1?

**Comment by adonath** [comment]
@registerrier I think the solution here is to improve docs, e.g. here https://docs.gammapy.org/1.0/tutorials/api/datasets.html#sphx-glr-tutorials-api-datasets-py

**Comment by AtreyeeS** [comment]
And maybe we can convert this to a discussion with the content:

It is important to keep in mind that models are attached to a specific dataset, linked by the dataset name. Every new dataset has a different name. While creating a copy of a dataset, it is necessary to pay attention to the name such that the relevant models, specially the background models, are correctly applied. This can be done, for ex, by `dataset_new = dataset_old.copy(name=dataset_old.name)`

**Comment by bkhelifi** [comment]
The github discussion might a good place. But it is not great to make a reference to a github discussion into our documentation or in tutorials... 
In the main 3D analysis tutorial (https://docs.gammapy.org/dev/tutorials/analysis-3d/analysis_3d.html#sphx-glr-tutorials-analysis-3d-analysis-3d-py), we do not make a focus on the need of copying the bkg model. This is hidden, not explained...
Maybe one should insist on this aspect on tutorials and maybe also on the description of the copy function of the MapDataset

**Comment by registerrier** [comment]
What is the status here @AtreyeeS ?

**Comment by AtreyeeS** [comment]
I think the solution here is to improve the documentation and emphasise during hands on sessions that Dataset operations do not preserve the name, and thus, some models, specially the Background Model, needs to be reapplied. Closing this issue
