### ISSUE TITLE
gammapy-data and the bug release 1.0.1

### ISSUE THREAD

**Issue by bkhelifi** [gammapy/gammapy#4313]
**Is your feature request related to a problem? Please describe.**
Currently, the dev version is using data sets from gammapy-data of the dev version, that are different from the ones of the 1.0 tag (e.g. 2017 Franchescini EBL model) . And some test functions of the dev version are using these new data sets.

**Describe the solution you'd like**
For the bug release, I am wondering if one should not create a tag 1.0.1 of gammapy-data, and take care of the download commands in the documentation

**Comment by adonath** [comment]
@bkhelifi No, we typically do not create bug-fix releases for data, see e.g. https://docs.gammapy.org/1.0/development/release.html

However we can define which data to be used for v1.0.1 here: https://github.com/gammapy/gammapy-webpage/blob/gh-pages/download/index.json

**Comment by adonath** [comment]
So users should keep `GAMMAPY_DATA=$PWD/gammapy-datasets/1.0` for v1.0.1 as well...

**Comment by bkhelifi** [comment]
I do understand my mistake. The registry of  EBL models coded in `modeling/models/spectral.py` contains `franceschini17` only in the branch dev (and so for the future 1.1), but not in the branch v1.0.x.
So, indeed, this is not needed to create a tag for the bug release. This has to be done only for the feature release....
I close then the issue.
Thanks @adonath
