### ISSUE TITLE
4fgl_dr3 equation is still broken in docs + phi_0 in broken power law spectral model

### ISSUE THREAD

**Issue by MRegeard** [gammapy/gammapy#4320]
**Gammapy version**
dev

**Bug description**
Even though equation of 4fgl_dr3 has been fixed in #4315, the rendering is still not good in the documentation. 

Also, phi_0 in broken power law spectral model is rendered as "phi_0" and not the greek character.

**Comment by AtreyeeS** [comment]
It seems okay to me https://docs.gammapy.org/dev/user-guide/model-gallery/spectral/plot_super_exp_cutoff_powerlaw_4fgl.html#sphx-glr-user-guide-model-gallery-spectral-plot-super-exp-cutoff-powerlaw-4fgl-py

Can you elaborate exactly the issue

**Comment by MRegeard** [comment]
Hi @AtreyeeS, It has already been merged from the pull request above (https://github.com/gammapy/gammapy/pull/4321). So that why this is now fine. I'm closing this issue.
