### ISSUE TITLE
Calculate Integral Flux Sensitivities

### ISSUE THREAD

**Issue by STSpencer** [gammapy/gammapy#4329]
**Is your feature request related to a problem? Please describe.**
As far as I can tell in the documentation or source code, the gammapy _SensitivityEstimator_ class lacks the capability to calculate integral flux sensitivities from GADF IRF files, and can only calculate differential sensitivities. This is needed, for example, for CTA source detectability studies. ctools has this functionality built into its cssens tool.

**Describe the solution you'd like**
Could this possibly be implemented?

**Describe alternatives you've considered**
Alternatively, is there a conceivable hack that could be used with the existing gammapy classes? Thanks in advance.

**Comment by adonath** [comment]
Thanks @STSpencer! You can e.g. use our flux points class to convert the sensitivities:

```python3
from gammapy.estimators import FluxPoints

table = energy_axis.to_table(format="gadf-sed")
table["e2dnde"] = sensitivity_table["e2dnde"]

fp = FluxPoints.from_table(
    table=table,
    format="gadf-sed",
    sed_type="e2dnde",
    reference_model=sensitivity_estimator.spectrum
    
)

fp.to_table(sed_type="flux")
```
Given you have an `energy_axis` from e.g. a `SpectrumDatasetOnOff` you passed to the `SensitivityEstimator`. I hop ethos helps...

**Comment by adonath** [comment]
I know realize that you probably refer to the integrated flux above a certain energy threshold. This is not as simple to achieve...

**Comment by bkhelifi** [comment]
Hi @adonath ,
Looking at the details, I see that the function `SensitivityEstimator.estimate_min_excess` could be extended to compute the array of counts integrated over bins instead of the array of counts per bin. And then the function `estimate_min_e2dnde` can be extended accordingly. 
The changes are not so difficult but they are needed. This can be a nice small project for beginners to have an option 'integral' in this estimator.

**Comment by adonath** [comment]
@bkhelifi Yes, I agree it is indeed not too complex. Looking at the table the sensitivity estimator returns I think we should probably make the columns compatible with the `"gadf-sed"` format as well. So use column names `e_ref` and later `e_min` and `e_max`. For the integral sensitivity `e_min` will be set to the energy threshold and `e_max` to a very large value or infinity...

**Comment by AtreyeeS** [comment]
Do we need to adapt the estimator here? Can this not be simply achieved by having one energy bin in the dataset?

**Comment by adonath** [comment]
> Do we need to adapt the estimator here? Can this not be simply achieved by having one energy bin in the dataset?

Yes, for one energy threshold this works. If I understood correctly, there was the request to do this for an array of energies. In this case one would need a loop over energies and modifying the `SensitivityEstimator` is probably more convenient to users.
