### ISSUE TITLE
CI fail for astropy LTS and numpy 1.20 version

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#4331]
The CI currently fails for the `py38-test-alldeps-astropylts-numpy120` environment. This is due to an incompatibility between recent iminuit versions 2.19 and 2.20 with numpy 1.20.

For some reason, iminuit 2.18 is not the version installed albeit the constraint of numpy=1.20.3  

See:
https://github.com/gammapy/gammapy/actions/runs/4172360908/jobs/7223365094#step:7:55

**Comment by maxnoe** [comment]
> For some reason, iminuit 2.18 is not the version installed albeit the constraint of numpy=1.20.3

Iminuit simply requires numpy without version constrained, so pip has no way of knowing it is incompatible with numpy 1.20:

https://github.com/scikit-hep/iminuit/blob/241006fc71672498bf43ade6619c23d25177188f/pyproject.toml#L39

**Comment by maxnoe** [comment]
Probably worth an issue with iminuit
