### ISSUE TITLE
PhaseBackgroundMaker does not support energy-dependent directional cuts

### ISSUE THREAD

**Issue by alvmas** [gammapy/gammapy#4340]
**Gammapy version**
 Gammapy v1.0

**Bug description**
When one tries to do the analysis estimating OFF counts based on the PHASE information and using an energy-dependent rad_max value, the PhaseBackgroundMaker does not work correctly since the geometry is defined as a PointSkyRegion.

**Expected behavior**
It should compute the OFF counts based on the phase information, but using different rad_max for the ON region, in different energy bins. 

**Other information**
We should have an option to compute the OFF counts in the variable ON region, for the case of using a PointSkyRegion geometry. Something similar to what is already implemented in ReflectedRegionsBackgroundMaker.

**Comment by MRegeard** [comment]
Hi @alvmas, 

The rad max cuts should be implemented with the pull request above.

**Comment by alvmas** [comment]
Hi @MRegeard ,
Thanks, I was actually implementing a PR that was exactly the same, so I think this should work!

**Comment by registerrier** [comment]
This is solved in #4352 . Closing now.
