### ISSUE TITLE
DarkMatter docs wrong

### ISSUE THREAD

**Issue by StFroese** [gammapy/gammapy#4351]
**Gammapy version**
1.0

**Bug description**
I'm trying to take a look at the primary fluxes of the dark matter module but using the example in the docs is actually not producing the desired output. 
https://gammapy.github.io/gammapy-recipes/_build/html/notebooks/dark-matter-utilities/astro_dark_matter.html#Gamma-ray-spectra-at-production

**Expected behavior**
Should produce output but fails since the plot function is missing the keyword 'flux_unit'. Has it been removed?
`AttributeError: Line2D.set() got an unexpected keyword argument 'flux_unit'`

**To Reproduce**
```python
fluxes = PrimaryFlux(mDM="1 TeV", channel="eL")
fig, axes = plt.subplots(4, 1, figsize=(6, 16))
mDMs = [0.01, 0.1, 1, 10] * u.TeV

for mDM, ax in zip(mDMs, axes):
    fluxes.mDM = mDM
    ax.set_title(rf"m$_{{\mathrm{{DM}}}}$ = {mDM}")
    ax.set_yscale("log")
    ax.set_ylabel("dN/dE")

    for channel in ["tau", "mu", "b", "Z"]:
        fluxes.channel = channel
        fluxes.table_model.plot(
            energy_range=[mDM / 100, mDM],
            ax=ax,
            label=channel,
            flux_unit="1/GeV",
        )

axes[0].legend()
plt.subplots_adjust(hspace=0.5)
```

**Comment by StFroese** [comment]
Also `energy_range ` is now called `energy_bounds `

**Comment by StFroese** [comment]
I guess this problems comes from the fact that the unit for the yaxis is given by the sed type:
https://github.com/gammapy/gammapy/blob/5bc72905f304536defd4848254b350b582cfb34f/gammapy/modeling/models/spectral.py#L420-L421

Unfortunately none of the DEFAULT seds has the same units as the dNdE spectrum of DM at production

**Comment by registerrier** [comment]
Thanks @StFroese . The issues here are due to old version of gammapy used in this specific recipe (this is not part of the main documentation). Each recipe uses a specific environment.

Technically it would be good to update all recipes to v1.0 if they are to be usable until the next LTS.
I have opened an issue in the gammapy-recipes repo: https://github.com/gammapy/gammapy-recipes/issues/13
