### ISSUE TITLE
Bug in reading Background3D models (fov_alignment)

### ISSUE THREAD

**Issue by SimoneMender** [gammapy/gammapy#4360]
**Gammapy version**
Gammapy 1.0

**Bug description**
When reading a Background3D model, which was created with `fov_alignment=FoVAlignment.ALTAZ`, the `fov_alignment` is "RADEC". 

Also in the docs (https://docs.gammapy.org/1.0/api/gammapy.irf.Background3D.html?highlight=background3d#gammapy.irf.Background3D) `fov_alignment` is described as a parameter of `Background3D`, which is not the case in the docstring of the class: https://github.com/gammapy/gammapy/blob/a11d49073667975af88efdcd8c6d8da2117bc49e/gammapy/irf/background.py#L92

**To Reproduce**
```
from gammapy.irf import Background3D, FoVAlignment
from gammapy.maps import MapAxis
from astropy import units as u
import numpy as np

N_bins = 10
N_bins_e = 6
e_reco = MapAxis.from_energy_bounds(0.1,10,N_bins_e,unit="TeV",name="energy")
lon_axis = MapAxis.from_bounds(-2.3,2.3,N_bins, interp="lin", unit="deg", name="fov_lon")
lat_axis = MapAxis.from_bounds(-2.3,2.3,N_bins, interp="lin", unit="deg", name="fov_lat")
bg_3d = Background3D(
    axes = [e_reco, lon_axis, lat_axis],
    data = np.ones((N_bins_e, N_bins, N_bins)),
    unit = u.Unit("s-1 MeV-1 sr-1"),
    fov_alignment=FoVAlignment.ALTAZ
    )
hduBackground = bg_3d.to_table_hdu()
hduBackground.writeto("background.fits", overwrite=True)
bg = Background3D.read("background.fits", hdu="BACKGROUND")
print(bg.fov_alignment)
```

**Comment by adonath** [comment]
Thanks @SimoneMender! I can reproduce and confirm the bug. Also looking at the code here 
https://github.com/gammapy/gammapy/blob/main/gammapy/irf/core.py#L466

it clearly misses adding the meta information for the FoV alignment.

**Comment by adonath** [comment]
However for some context:

It is unclear whether Gammapy should actually be able to write IRFs. The feature is mostly there for "historical" reasons. So we should also consider to maybe just deprecate this functionality.
