### ISSUE TITLE
Re-check gammapy.utils.time

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#4415]
There are a couple of functions here https://github.com/gammapy/gammapy/blob/d4a6194d8c2b85fbb913d2fd4f7a99a1d3803040/gammapy/utils/time.py#L23 
(time_to_fits_header, time_to_fits) that are untested and probably do not confirm to the guidelines in https://gamma-astro-data-formats.readthedocs.io/en/v0.3/general/time.html?highlight=TIMEREF#formats

Reminder issue to verify and cleanup

**Comment by registerrier** [comment]
Could you have a look there @cgalelli ? Postponing now.
