### ISSUE TITLE
Investigate fail in FluxPointsEstimator

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#4472]
**Gammapy version**
1.0, 1.0.1

While running `FluxPointsEstimator` with multiple models present, and `reoptimize=True`, a confusing error has been sometimes reported

```

File ~/Gammapy-dev/gammapy/gammapy/datasets/evaluator.py:301, in MapEvaluator._compute_flux_spatial(self)
    299     value = (values.quantity * weights).sum(axis=(1, 2), keepdims=True)
    300 else:
--> 301     value = self._compute_flux_spatial_geom(self.geom)
    303 return value

File ~/Gammapy-dev/gammapy/gammapy/datasets/evaluator.py:309, in MapEvaluator._compute_flux_spatial_geom(self, geom)
    307 if not self.model.spatial_model.is_energy_dependent:
    308     geom = geom.to_image()
--> 309 value = self.model.spatial_model.integrate_geom(geom)
    311 if self.psf and self.model.apply_irf["psf"]:
    312     value = self.apply_psf(value)

File ~/Gammapy-dev/gammapy/gammapy/modeling/models/spatial.py:245, in SpatialModel.integrate_geom(self, geom, oversampling_factor)
    243     # Finally stack result
    244     result._unit = integrated.unit
--> 245     result.stack(integrated)
    246 else:
    247     values = self.evaluate_geom(wcs_geom)

File ~/Gammapy-dev/gammapy/gammapy/maps/wcs/ndmap.py:878, in WcsNDMap.stack(self, other, weights, nan_to_num)
    876     cutout_slices = Ellipsis, slices[0], slices[1]
    877 else:
--> 878     raise ValueError(
    879         "Can only stack equivalent maps or cutout of the same map."
    880     )
    882 data = other.quantity[cutout_slices].to_value(self.unit)
    883 if nan_to_num:

ValueError: Can only stack equivalent maps or cutout of the same map.
```

I tried to produce a minimal notebook here where the error shows (on cell 24)
https://github.com/AtreyeeS/test_notebooks/blob/master/fpe_fail.ipynb

from what i understood, the wcs_geom  here (https://github.com/gammapy/gammapy/blob/18c2597f23816f465189f6dde4e6e75fd9e50fe6/gammapy/modeling/models/spatial.py#L227)  ends up with width      : 0.0 deg x 0.0 deg when the spatial model position is very close to the lat/lon allowed range, probably leading to a situation with very little overlap on geom

The error is rather unstable, and sometimes vanishes on re-running the script.

It would be nice to handle this error better, but I dont know how.

**Comment by AtreyeeS** [comment]
@QRemy @adonath do you understand this error?

**Comment by QRemy** [comment]
Does it happen also for 1.01 ? if not it could be related to #4304.

**Comment by AtreyeeS** [comment]
@QRemy : The fail happens in 1.0.1 as well

**Comment by AtreyeeS** [comment]
The spatial parameters should be frozen during the flux estimation, no? Why is the Gaussian width getting affected?

**Comment by AtreyeeS** [comment]
Investigating this, the scaled model works only on the spectral parameters. We only re-set the spectral part of the scale model here

https://github.com/gammapy/gammapy/blob/395930c3c8a9996ef009ac1685d8d945a4c632f6/gammapy/estimators/flux.py#L188


The spatial parameters remain free, and are re-optimised. Is this the correct behaviour @registerrier @bkhelifi ? The spatial position can go completely haywire, and the flux point extracted for a different region?

eg: 
```
from gammapy.modeling.models import *
m1 = SkyModel(spectral_model=PowerLawSpectralModel(),
              spatial_model=PointSpatialModel(),
              name = "m1")
m2 = SkyModel(spectral_model=BrokenPowerLawSpectralModel(),
              spatial_model=GaussianSpatialModel(),
              name = "m2")
models = Models([m1, m2])
scale_m2 = ScaleSpectralModel(m2)
models[m2].spectral_model = scale_m2
models.to_parameters_table()["model", "type", "name", "frozen"]).show_in_browser()
```

clearly shows 
```
model	type	name	frozen
m1	spectral	index	False
m1	spectral	amplitude	False
m1	spectral	reference	True
m1	spatial	lon_0	False
m1	spatial	lat_0	False
m2	spectral	norm	False
m2	spatial	lon_0	False
m2	spatial	lat_0	False
m2	spatial	sigma	False
m2	spatial	e	True
m2	spatial	phi	True
```

**Comment by adonath** [comment]
Thanks @AtreyeeS for investigating. I think the answer here is not obvious, because often there is a strong correlation between e.g. the amplitude and size of a model.  So re-optimizing spatial parameters can make sense. however if the overall fit is unstable, things might break. The advantage of the current solution is that users can explicitly freeze the spatial parameters beforehand. This will set the model in the same state when re-optimizing for the flux point computation. If we always fix spatial parameters it is not possible to unfreeze, except if we introduce  an option for this. 

But I agree the most common method is to just re-optimize the norms of nearby sources. So we could show this more often in the docs:

```python3
models.parameters.freeze_all()
models.parameters.norm_parameters.unfreeze_all()
```

**Comment by bkhelifi** [comment]
And also precise it in the docstring of the estimator! 
Indeed, for each estimator, a user can not scan all tutorials to understand a usage ....

**Comment by registerrier** [comment]
I must say I can't see a good reason why one would re-optimize the source parameters during flux estimation. Yet I can see many bad reasons :) .

I think the default should never be this behavior. It even confuses us.

**Comment by AtreyeeS** [comment]
I think the spectral parameters of other sources are also kept free, no? For fitting in a single bin, that cannot be correct.

**Comment by AtreyeeS** [comment]
If we really want to keep the option open, maybe `reoptimize` can take a string from among `[None, "norms", "all"]`

**Comment by AtreyeeS** [comment]
We already have a sizeable user base now, and I am not sure how many of them will go back and check a fp estimation tutorial unless specifically informed about an issue there. And the current behaviour is rather erroneous (specially for weak sources), and rectifying it seems to solve the problem of "Gammapy gives very low upper limits, inconsistent with previous measurements" (I don't know if it was reported officially..)

I would at least keep a configure approach to `optimize`, AND improve the tutorials to show how to freeze parameters explicitly. Also, detail the behaviour in the forward folding section of the estimator docs (https://docs.gammapy.org/1.1/user-guide/estimators.html#general-method)

**Comment by AtreyeeS** [comment]
Solved through https://github.com/gammapy/gammapy/pull/4567
