### ISSUE TITLE
Add functionality to rebin flux points to have a minimum significance

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#4473]
It is common for users to "rebin the data to have a minimum significance of n sigma for each flux point". This can be done easily by combining the `TS` available on our `FluxPoints`.

It would be convenient to implement  `FluxPoints.rebin(min_sigma=2)`, instead of having people write a variety of code with sometime inconsistent statistics. 

Of course, having other rebinning methods would be required (min counts, min bkg, etc) which would be better implemented at the `EventDataset` level

**Comment by adonath** [comment]
> Of course, having other rebinning methods would be required (min counts, min bkg, etc) which would be better implemented at the EventDataset level 

Just for completeness, we already have: https://docs.gammapy.org/1.0.1/api/gammapy.estimators.utils.resample_energy_edges.html#gammapy.estimators.utils.resample_energy_edges

But I think it is poorly documented. Users can just work with a fine energy binning and get all the functionality they need.

**Comment by AtreyeeS** [comment]
Yes, I understand your concerns, but say, I have a daily binned light curve with mostly upper limits. It can be very convenient to rebin to weekly scales, without having to rerun the estimator. And this is computationally quite light

**Comment by registerrier** [comment]
This is now solved in #5007 . Closing.
