### ISSUE TITLE
Support additional axes in SkyModel.evaluate_geom(geom)

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#4480]
**Is your feature request related to a problem? Please describe.**
Currently, `SkyModel.evaluate_geom(geom)` does not support axes that are not `energy_true`.  Calling it on a `Geom` object with additional axes will return an array with incorrect shape.

**Describe the solution you'd like**
`SkyModel.evaluate_geom(geom)` should return an array of the correct size copying the contents for the additional axes.

Special caution should be taken for `time` axis. For three reasons:
- currently the time is evaluated via the `gti` argument. This is an incorrect approach as `gti` is relevant on the `MapEvaluator`, not on the model. Note that a `TimeMapAxis.from_gti()` factory method exists. 
-  `evaluate_geom` actually integrates over time. Is this still necessary? Does it make sense?
- A `MapAxis` can represent a time-like quantity but does not contain a reference time. This has to be verified. 

Another question, is how to handle `energy` axis (instead of `energy_true`).

**Comment by Astro-Kirsty** [comment]
This should be closed by #4828 ?
