### ISSUE TITLE
datasets.info_table: geom_exposure not in **self.geoms

### ISSUE THREAD

**Issue by mireianievas** [gammapy/gammapy#4490]
**Gammapy version**
1.0.1

**Bug description**

In gammapy/datasets/map.py

```
L718: dataset = self.__class__.from_geoms(**self.geoms, name=name)
```

geoms might not include geom_exposure. 

**Expected behavior**
Not sure

**To Reproduce**
This error popped up while following the tutorial in https://docs.gammapy.org/1.0.1/tutorials/analysis-1d/spectral_analysis.html#sphx-glr-tutorials-analysis-1d-spectral-analysis-py

```
info_table = datasets.info_table(cumulative=True)
display(info_table)
```

**Other information**
Any other information you think will be useful for us to fix the issue can go here.

**Comment by registerrier** [comment]
What is the error you obtain exactly? Isn't there an issue in the tutorial before this?

**Comment by mireianievas** [comment]
This happened when I created SpectrumDatasetMaker(selection=['events']), without adding 'exposure' to the selection. Then the geoms.geom_exposure was not defined.  But probably handling/catching those errors would be good.
