### ISSUE TITLE
Describe more `norm_scan` and `stat_scan` in user-guide docs

### ISSUE THREAD

**Issue by aaguasca** [gammapy/gammapy#4497]
**Is your feature request related to a problem? Please describe.**
The description of the `norm_scan` and `stat_scan` in the section "estimators (DL4 to DL5, and DL6)" from the user guide could be improved. These are the current definitions:

Quantity | Definition
-- | --
norm_scan | Norm scan
stat_scan | Fit statistics scan

**Describe the solution you'd like**
I propose to explain a bit more these quantities. For example,

Quantity | Definition
-- | --
norm_scan | Norm scan used for the fit statistic scan
stat_scan | Fit statistics scan associated with norm_scan

**Comment by registerrier** [comment]
Sorry for the late reaction. This sounds like a good idea.  @aaguasca can you open a PR for this?
