### ISSUE TITLE
Expose NormSpectralModels in Model Gallery

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#4515]
In the present dev, 1.0.1, only the `PiecewiseNormSpectralModel` (https://docs.gammapy.org/dev/user-guide/model-gallery/index.html#spectral-models ) is shown among all norm models.
I understand the motivation, but this gives an incomplete info about the number of supported models.
I think should show all the norm models.

**Comment by Astro-Kirsty** [comment]
I am happy to implement this, however, could you please explain the motivation behind wanting to expose all the `NormSpectralModels`? 
They don't seem to be used a lot, and I wonder if exposing them in this specific manner might confuse the user into wanting to use them in incorrect situations?

**Comment by AtreyeeS** [comment]
We advertise the Models Gallery as a place to know the available models in gammapy, so it would be good to have it complete. A reason why these models are not used is because people don't know that they are there! (kind of like the discussion we had at our last dev call about not advertising our features)


What can be useful is to show how these models affect a Spectral Model, eg, the original model (a power law) and original model*norm model on the same plot..

like... (with better plot labels)

![Unknown](https://github.com/gammapy/gammapy/assets/32677370/93c9afae-fc69-41d2-b10b-1fe602a1c95d)
