### ISSUE TITLE
kwargs definition of Map.plot_grid() is confusing

### ISSUE THREAD

**Issue by MRegeard** [gammapy/gammapy#4518]
**Version : dev**

The documentation of the `**kwargs` of `Map.plot_grid()` method says that `**kwargs` are passed to `Map.plot()` which does not exist. 

I haven't look in details but I don't even know to what `Map.plot()` refers to.

Anyway, I think this is confusing and could be better explained.

**Comment by AtreyeeS** [comment]
In this specific case, the docstring should rather read `passed to WcsNDMap.plot()`

In general, our documentation of `kwargs`, specially for the plotting methods, is not very transparent. We did some cleanup before the 1.0 release, but I think there is a lot of scope for improvement

**Comment by MRegeard** [comment]
But all the `plot_grid()` methods come from `Map` so it is still confusing the if docstring reads `passed to WcsNDMap.plot()` right ? 

And what about `HxpMap.plot_grid()` and `HxpNDMap.plot_grid()` ?
