### ISSUE TITLE
RegionGeom.get_coord sparse argument is never used

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#4542]
**Gammapy version**
v1.0 and dev

**Bug description**
`RegionGeom.get_coord(sparse=False)` always returns a sparse `MapCoord` because `MapAxes.get_coord()` does not support dense coordinates arrays. 

**Expected behavior**
`RegionGeom.get_coord(sparse=False)` should return a `MapCoord` where all coordinates have the same dimension.

**To Reproduce**
```
from gammapy.maps import MapAxis, RegionGeom
time_axis = MapAxis.from_bounds(0 , 3600, nbin=5, name="time", unit="s")
energy_axis = MapAxis.from_energy_bounds(energy_min=0.2, energy_max=100, unit="TeV", nbin=10)
geom = RegionGeom.create(
    region=None, axes=[energy_axis, time_axis]
)
coords = geom.get_coord(sparse=False)
print(coords['energy'].shape)
```
**Other information**
Any other information you think will be useful for us to fix the issue can go here.

**Comment by adonath** [comment]
Note there is https://docs.gammapy.org/1.0.1/api/gammapy.maps.MapCoord.html#gammapy.maps.MapCoord.broadcasted, which allows users to broadcast the sparse coordinate arrays to dense ones.

But yes it should be fixed for consistency.
