### ISSUE TITLE
Use conda to set GAMMAPY_DATA env variable

### ISSUE THREAD

**Issue by HealthyPear** [gammapy/gammapy#4581]
This is just a minor documentation suggestion.

Since the installation requires the use of _conda_, you might as well instruct the user to set any environment variable using _conda_ itself for the environment specific to the _gammapy_ version in use, instead of using the shell which is global,

```
$ curl -O https://gammapy.org/download/install/gammapy-1.1-environment.yml
$ conda env create -f gammapy-1.1-environment.yml
$ conda activate gammapy-1.1
$ gammapy download notebooks
$ gammapy download datasets
$ conda env config vars set GAMMAPY_DATA=$PWD/gammapy-datasets/1.1
$ conda activate gammapy-1.1
```

**Comment by registerrier** [comment]
Thanks @HealthyPear . That's a very good suggestion.
