### ISSUE TITLE
CI fails with numpy 1.25

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#4598]
Currently the CI is failing with the new numpy 1.25. 

Apparently the definition of units in the Table in `gammapy.data.utils.get_irf_features` is causing issues.

I would suggest to rather define the table contents as a `dict` with the item being a `Quantity`. This seems a simpler scheme than the current one. Opinion @QRemy ?

**Comment by QRemy** [comment]
Looking back at the discussion in #4242 it seems that @adonath prefers a `Table`.

**Comment by adonath** [comment]
Yes returning a table as some nice advantages, such as build in grouping and serialisation. If the issue is with table and units it should be fixed upstream in Astropy I guess?

**Comment by registerrier** [comment]
OK. Indeed the `Table` is fine. What I meant is that creating it simply from distinct `Quantity` objects for each feature (e.g. stored in a dict) rather than instantiating units and data separately should work in this case.

**Comment by morcuended** [comment]
Can this issue be closed? Or is there anything else pending after #4634?

**Comment by registerrier** [comment]
I think it can be closed.
