### ISSUE TITLE
Piecewise Norm Spatial Model problems at Galactic Longitude Coordinate 0 deg

### ISSUE THREAD

**Issue by katrinstreil** [gammapy/gammapy#4602]
**Gammapy version**
1.1

**Bug description**

I followed the example plot for the piecewise Norm Spatial Model:
https://docs.gammapy.org/dev/user-guide/model-gallery/spatial/plot_piecewise_norm_spatial.html

If changing the sky coordinate of the geom so that it contains the Galactic Center i.e. (0,0) deg the model evaluation returns NaN. 

**To Reproduce**
Using 
`geom = WcsGeom.create(skydir=(0., 0.), npix=(120, 120), binsz=0.03, frame="galactic")`
in the linked example plot

**Comment by QRemy** [comment]
a simple fix to work at the GC would be to redefine the coords such as:
`coords["lon"][coords["lon"]>180*u.deg]-=360*u.deg`

**Comment by Astro-Kirsty** [comment]
I had a similar idea but using the `wrap_at` function 
`self._coords['lon']=Angle(self._coords.lon).wrap_at(180*u.deg)`
However, then the plot looks like this 
![image](https://github.com/gammapy/gammapy/assets/60767360/b589404c-f76a-4830-bbfb-0804839300e3)

**Comment by Astro-Kirsty** [comment]
I did something similar using `wrap_at` function
`self._coords['lon']=Angle(self._coords.lon).wrap_at(180*u.deg)`

Will make a PR soon
