### ISSUE TITLE
Improve codemeta.py script to include releveant keywords for codemeta.json

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#4617]
This issue is a followup to PR #4594 .

Here we should list the keywords we want to include on the codemeta.json file and include them in the scripts that updates the codemeta file produced by cffconvert.

**Comment by bkhelifi** [comment]
As mentioned in the associated closed PR, the following list of additional keywords was in codemeta.json of the LTS but they are not yet included in `codemeta.py':
- add "Scientific/Engineering" in the section "keywords",
- "softwareVersion": "v1.1" -> "softwareVersion": "1.1" (by memory, to follow the codemeta format)
- "dateCreated"
- "datePublished"
- "applicationCategory": "Astronomy",
- "applicationSubCategory": "Very-high energy gamma rays",
- "programmingLanguage": "Python 3",
- "operatingSystem": "Linux, Mac OS, Windows",
- "audience": {
"@id": "/audience/science-research",
"@type": "Audience",
"audienceType": "Science/Research"
},
- "readme": "If you use this software, please cite it using the metadata from this file.",
- "runtimePlatform": [
"C",
"Cython",
"Python 3",
"Python 3.8",
"Python 3.9",
"Python 3.10",
"Python Implementation CPython"
]
