### ISSUE TITLE
Spectral Model plotting in 3D Fermi dataset, after saving to yaml file and reading back, does not match

### ISSUE THREAD

**Issue by mireianievas** [gammapy/gammapy#4622]
**Gammapy version**
v1.0

**Bug description**
Not using the very last version of gammapy, but probably nothing changed between 1.0 and 1.1 to fix this (correct me if I am wrong). 

This is actually a double-bug. 

At least with Fermi, if you save the model for one source (from a skymodel with many) into a file, then load it back with Models.from_yaml() and plot it, the result is different than the original one. I am suspecting the covariance matrix (not saved for the one-source-writing-case) has to do something with it, but I am not fully sure. If that is the case, I'm not sure if there is an easy way to warn the user of that missing covariance matrix? maybe while saving the model inserting some kind of flag that this is a component from a complex model ? Otherwise it is quite dangerous to be honest. 

In any case, saving the entire skymodel does not seem to work either, as the to_yaml() makes a call to to_dict() which checks for nan values in the skymodel. For Fermi, there are several spatial parameters (lon_0, lat_0, etc) with nans in the min, max for instance. The error while saving the full model in that case is

```
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

**Expected behavior**
I would expect to get the same plot, and to be able to write the model to disk despite the nan values in some parameters.

**To Reproduce**
```
fig, ax = plt.subplots()

plot_kwargs = {
    "energy_bounds": [1*u.GeV,300*u.GeV], 
    "sed_type": "e2dnde",
    "yunits": u.Unit("erg cm-2 s-1"),
    "xunits": u.GeV,
    "ax": ax,
}

LAT_FullDataset.model['mysource'].spectral_model.plot_error(**plot_kwargs,
                                         label='LAT Full Dataset',
                                         ec='C0',facecolor='white',hatch='+++++++',alpha=0.5,zorder=-10)

myloadedmodel = Models.from_yaml(Models(LAT_FullDataset.model['mysource']).to_yaml())
myloadedmodel['mysource'].spectral_model.plot_error(**plot_kwargs,
                                         label='LAT Full Dataset',
                                         ec='C3',facecolor='white',hatch='\\\\\\\\\\',alpha=0.5,zorder=-10)

```

![image](https://github.com/gammapy/gammapy/assets/2607760/41602e2b-5a64-48f0-ad22-3ca0d350d162)

**Comment by AtreyeeS** [comment]
This is indeed by choice, as you said @Astro-Kirsty 
The `to_yaml` simply creates a yaml representation of the model parameters, which does not include the covariance. This is useful, eg, while creating a list of models to be parsed.

Serialisation in gammapy should always proceed through the `read` and `write` methods

**Comment by mireianievas** [comment]
True, I did not notice that by using the write and read methods of Models the covariance matrix was included.
