### ISSUE TITLE
Adding a `concatenate` method to `Observations` 

### ISSUE THREAD

**Issue by MRegeard** [gammapy/gammapy#4637]
I think it would be interesting  to have a proper `concatenate` `classmethod` on `Observations`.  
Sometimes, `DataStore` are split by "epoque".  Therefore, if you want to do an analysis over multiple "epoque" you end up having multiple `Observations` while you want to do a classic analysis with all the `Observation` combined (not a joint-analysis).

**Comment by registerrier** [comment]
This is solved by #4638 . The only remaining thing is to document this somewhere.

**Comment by Astro-Kirsty** [comment]
@MRegeard I think we can close this now? 
I think we do not need further document as it will be present in the API reference documentation?
