### ISSUE TITLE
IRF + FOVBackgroundModel result in negative excess counts when using dataset.fake()

### ISSUE THREAD

**Issue by StFroese** [gammapy/gammapy#4655]
**Gammapy version**
v1.1

**Bug description**
Creating a dataset from IRFs and a FOVBackgroundModel with norm =! 1 will result in `Total excess counts` not being near zero when using `dataset.fake()`

**Expected behavior**
If you decide to build a dataset from IRFs, faking the samples should result in the `Total counts` roughly being the same as `Total background counts` (only close because of poisson sampling of course).
If I decide to use a FOVBackgroundModel together with the IRFs I expect the same behaviour.

**To Reproduce**
```python
from pathlib import Path

import astropy.units as u
from astropy.coordinates import SkyCoord
from gammapy.data import Observation, observatory_locations
from gammapy.datasets import MapDataset
from gammapy.irf import load_irf_dict_from_file
from gammapy.makers import MapDatasetMaker
from gammapy.maps import MapAxis, WcsGeom
from gammapy.modeling.models import FoVBackgroundModel, Models

path = Path("$GAMMAPY_DATA/cta-caldb")
irf_filename = "Prod5-South-20deg-AverageAz-14MSTs37SSTs.180000s-v0.1.fits.gz"

pointing = SkyCoord(0.0, 0.0, frame="galactic", unit="deg")
livetime = 1 * u.hr

irfs = load_irf_dict_from_file(path / irf_filename)
location = observatory_locations["cta_south"]

observation = Observation.create(
    obs_id=1001,
    pointing=pointing,
    livetime=livetime,
    irfs=irfs,
    location=location,
)

energy_axis = MapAxis.from_energy_bounds(
    "0.1 TeV", "100 TeV", nbin=10, per_decade=True
)
energy_axis_true = MapAxis.from_energy_bounds(
    "0.03 TeV", "300 TeV", nbin=20, per_decade=True, name="energy_true"
)
migra_axis = MapAxis.from_bounds(
    0.5, 2, nbin=150, node_type="edges", name="migra"
)

geom = WcsGeom.create(
    skydir=pointing,
    width=(2, 2),
    binsz=0.02,
    frame="galactic",
    axes=[energy_axis],
)

empty = MapDataset.create(
    geom,
    energy_axis_true=energy_axis_true,
    migra_axis=migra_axis,
    name="my-dataset",
)
maker = MapDatasetMaker(selection=["exposure", "background", "psf", "edisp"])
dataset = maker.run(empty, observation)

bkg_model = FoVBackgroundModel(dataset_name='my-dataset')

models = Models([bkg_model])


dataset.models = models

dataset.fake()
print(dataset)

dataset.models[0].parameters['norm'].value = 0.5
dataset.fake()
print(dataset)
```

*Output of second print (norm=0.5):*
```
  Total counts                    : 7579 
  Total background counts         : 15155.71
  Total excess counts             : -7576.71
```

**Other information**
If the FOVBackgroundModel is only for fitting it should be ignored in dataset.fake()

**Comment by AtreyeeS** [comment]
Thanks @StFroese ! I think this is the intended behaviour here.

The `FoVBackgroundModel` is used to correct the background model from the IRF.
When you set `dataset.models[0].parameters['norm'].value = 0.5`, you imply that you expect the actual background to 50% weaker than what is given by the IRF model. This is important information, which correctly goes into the simulations

**Comment by StFroese** [comment]
Thank you @AtreyeeS for explaining. Can we maybe add something like a caveat to the according tutorial in the docs?

**Comment by AtreyeeS** [comment]
I would not call it a caveat, but indeed, we should explain it clearly in the docs
