### ISSUE TITLE
Add metadata class for EventList

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#4673]
Currently, the `EventList` meta data is stored on the `table` meta object. It should have its own `meta` class based on the  `MetaData` base class, following PIG 25 (#4491).

Metadata are partly duplicated from `Observation` attributes (but act here as meta info). They should contain:
- obs_id : Union[str, int]
- telescope : Optional[str] = None   # here optional
- instrument : Optional[str] = None
- observation_mode : Optional[str] = None
- observation_time_start : Optional[Time] = None
- observation_time_stop :  Optional[Time] = None
- observation_time_ref : Optional[Time] = None
- livetime : Time
- deadtime : float
- location : Optional[Union[str, EarthLocation]] = None
- creation : Optional[CreatorMetaData] = None

Are there other things? Should we use names close to current `EventList` properties, e.g. `observatory_earth_location` rather than `location`?

**Comment by bkhelifi** [comment]
Thanks Régis...
What is exactly here observation_mode? For to be sure... 
There are also:
- the array_pointing: parallel, convergent, divergent? if yes, an angle is needed.
- the tracking_mode: pointing, drift-scan (fix alt/az)
- precision pointing boolean
 But should we have a metadata class associated to the HDU pointing? In this case, the 3 later should not be here
- some sky quality
 But should we have a metadata class associated to monitoring data?

A DataRelease name is probably needed: for the current HESS fits prod, we have a prod per analysis config type (ie cuts). But, in other hand, this information is a common metadata to many EventList, like instrument, location, creation... Should we create a `DataReleaseMetaClass`?

Maybe @kosack and @maxnoe can help here...
