### ISSUE TITLE
Add GTI meta data

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#4674]
Following PIG 25, add a `GTIMetaData`. It should be pretty minimal.
- reference_time : Optional[Time] = None

Should it contain anything else? I don't think it needs a creation metadata.

**Comment by bkhelifi** [comment]
GTI is a name of our internal data model (at the DL3, CTAO will call it Stable Time Interval).
Here, however, you are not proposing an interval, but one time... which is not coherent, is not it?

**Comment by registerrier** [comment]
> GTI is a name of our internal data model (at the DL3, CTAO will call it Stable Time Interval). Here, however, you are not proposing an interval, but one time... which is not coherent, is not it?

This does not replace the `GTI` object, but simply provides a container for its metadata. The only one I see is the reference time, as the GTIs are usually stored as seconds since a reference time. But it might probably be skipped completely and no `meta` be carried with the `GTI`.

**Comment by bkhelifi** [comment]
I got it... indeed, the reference time is a meta data for the times.
It is build from the header keywords `MJDREFI`, `MJDREFF`, `TIMESYS`, `TIMEREF` and `TASSIGN`. Is not it?

**Comment by registerrier** [comment]
Solved by #5026
