### ISSUE TITLE
Longer time to load data

### ISSUE THREAD

**Issue by bkhelifi** [gammapy/gammapy#4680]
**Gammapy version**
At least the dev...

**Bug description**
Getting all observations of the HESS data releases takes now about 5min in my laptop. This is probably due to the start of the separation of the internal data model and the GADF format, leading to the fact that we are not reading anymore the obs table (as it is not mandatory for GADF)

**Expected behavior**
An increase of the speed is highly desirable for the users.

**Other information**
They are several possibilities to achieve that:
- convince the community that the obs table should be mandatory (issue to be made on VODF/GADF)
- if an obs table is present, read the needed metadata from it
- activate the caching of the Lazy Loading of astropy

**Comment by registerrier** [comment]
Summary of discussions in the coding sprint day 1:
- identify the observation members that can be cached
- check whether the code actually re-uses efficiently the loaded data
- Objective is to open DL3 files only once or twice at most.

An option is to build an iterator for `Observations` to fully read the observation into memory (caching + garbage collection)

**Comment by morcuended** [comment]
Kind of related to this as a side note: state in the documentation that it is recommended to unzip files before loading them with Gammapy

**Comment by Astro-Kirsty** [comment]
Astropy 6 has now been released, and we are using that version. 
What needs to be done now on this topic?

**Comment by registerrier** [comment]
@morcuended could check the reading times with the latest dev version and astropy 6?

**Comment by registerrier** [comment]
Keeping this open as reminder to check performances.

**Comment by registerrier** [comment]
This can be monitored with LST-1 validation scripts directly. Closing now.
