### ISSUE TITLE
Background2D.to_3d uses cartesian not angular distance

### ISSUE THREAD

**Issue by maxnoe** [gammapy/gammapy#4724]
**Gammapy version**

Current main branch

**Bug description**

```
offset = np.sqrt(coords["fov_lat"] ** 2 + coords["fov_lon"] ** 2)
```

**Expected behavior**

Should use angular separation

**Comment by cgalelli** [comment]
Hi Max, thanks for finding the bug. Tried to fix it in pr #4728
