### ISSUE TITLE
Please revise get_wstat_mu_bkg

### ISSUE THREAD

**Issue by moralejo** [gammapy/gammapy#4742]
https://github.com/gammapy/gammapy/blob/c71cb4707087c5278a15913b46828718562a8b10/gammapy/stats/fit_statistics.py#L211

I think the denominator here should be just 2 (1+alpha) 
If that is the case, the current function will only provide the bext mu_bkg for the case alpha=1

**Comment by moralejo** [comment]
Hi,

the code is correct, but it return the Poisson parameter of the background **in the OFF region**

Whereas the same formula in the documentation: 
https://docs.gammapy.org/1.1/user-guide/stats/wstat_derivation.html

is used to obtain the Poisson parameter of the background **in the ON region** - that is what mu_bkg means in the documentation. So probably only the docs are wrong.

Here: https://github.com/gammapy/gammapy/blob/c71cb4707087c5278a15913b46828718562a8b10/gammapy/datasets/map.py#L2121-L2126

the return of the function (for the whole OFF region) is scaled by alpha, to get the value for the ON region, so it seems correct.
It would anyway be worth that an expert checks it. I also think it would be better to use, for the background Poisson parameters, variable names which make it clear straightaway whether they refer to the ON region or to the OFF region.

**Comment by adonath** [comment]
Thanks @moralejo! Which modifications would you propose to https://docs.gammapy.org/1.1/user-guide/stats/index.html#notations, to make the description more clear?

**Comment by moralejo** [comment]
> Thanks @moralejo! Which modifications would you propose to https://docs.gammapy.org/1.1/user-guide/stats/index.html#notations, to make the description more clear?

Hi,

I would say 

"mu_bkg: predicted background counts in the **ON** region" ( this is what it means here, since below we have mu_off = mu_bkg / alpha) 

Then, for consistency, the function get_wstat_mu_bkg should either be called get_wstat_mu_off , or be modified to return mu_bkg (and the code using the function should be changed as well). 

In the current documentation https://docs.gammapy.org/1.1/user-guide/stats/wstat_derivation.html (not sure if everywhere else) mu_bkg has the same meaning as in the glossary - ok!    
But then the formulae here:
https://docs.gammapy.org/1.1/user-guide/stats/wstat_derivation.html#profile-likelihood 
need fixing (they were taken from a reference in which mu_bkg meant what in gammapy is called mu_noff). These would be the changes (crosscheck is welcome):

$\frac{\alpha\,n_{\mathrm{on}}}{\mu_{\mathrm{sig}}+\alpha\mu_{\mathrm{bkg}}} + \frac{n_{\mathrm{off}}}{\mu_{\mathrm{bkg}}} - (\alpha+ 1) = 0  \longrightarrow  \frac{\alpha \\; n_{\mathrm{on}}}{\mu_{\mathrm{sig}}+\alpha\mu_{\mathrm{bkg}}} + \frac{\alpha \\; n_{\mathrm{off}}}{\mu_{\mathrm{bkg}}} - (\alpha+ 1) = 0$

$\mu_{\mathrm{bkg}} = \frac{C + D}{2\alpha(\alpha + 1)} \longrightarrow \mu_{\mathrm{bkg}} = \frac{C + D}{2(\alpha + 1)}$
One can add $\mu_{bkg} = \alpha \mu_{off}$  for clarity, since in the code we will have: mu_bkg = alpha * get_wstat_mu_off(...)

**Comment by moralejo** [comment]
There are also problems here:
https://docs.gammapy.org/1.1/user-guide/stats/wstat_derivation.html#goodness-of-fit

![image](https://github.com/gammapy/gammapy/assets/14164282/62c9b6c0-4f2a-4a89-ac85-2e6f7fa5ec00)

The Likelihood function is the same as before, with arguments:
![image](https://github.com/gammapy/gammapy/assets/14164282/9026ddc6-402e-4839-a679-75824e796ae0)

So the correct arguments to get the absolute maximum likelihood are:
$L(n_{on},  n_{off},  \alpha,  (n_{on} - \alpha \\; n_{off}),  \alpha \\; n_{off})$

(and the same in the two formulae afterwards)

**Comment by moralejo** [comment]
In https://docs.gammapy.org/1.1/user-guide/stats/wstat_derivation.html#derivation-of-the-wstat-formula
![image](https://github.com/gammapy/gammapy/assets/14164282/5ba042dc-52a3-4c72-8c7b-19de7b5a4cda)

Where it says "mu_src" it should be "mu_sig"

**Comment by moralejo** [comment]
https://docs.gammapy.org/1.1/user-guide/stats/wstat_derivation.html#final-result
![image](https://github.com/gammapy/gammapy/assets/14164282/85f55943-56c9-45e6-8180-087b7c5319c6)



https://docs.gammapy.org/1.1/user-guide/stats/wstat_derivation.html#special-cases
![image](https://github.com/gammapy/gammapy/assets/14164282/11523045-b247-4e86-9a62-cae19b0d9f47)

In **the two formulae above**, mu_bkg should become mu_bkg / alpha   (or, equivalently, mu_off)


![image](https://github.com/gammapy/gammapy/assets/14164282/ccd33679-719f-4d56-9f7b-c52fdac0528a)
Should be:  $L(0,  n_{off},  \alpha,  (0 - \alpha \\; n_{off}),  \alpha \\; n_{off}) = ...$   (maximum absolute L in case n_on=0) The right side is correct.

**Comment by moralejo** [comment]
Last part...
Under https://docs.gammapy.org/1.1/user-guide/stats/wstat_derivation.html#special-cases:

![image](https://github.com/gammapy/gammapy/assets/14164282/c6795e6d-af52-4a7a-8c10-687455b4bc7a)

Again, mu_bkg must be replaced above by mu_bkg / alpha

And
![image](https://github.com/gammapy/gammapy/assets/14164282/390b28d4-8d01-47b1-a014-287729692189)

should become mu_bkg = [alpha / (alpha+1)] * n_off


![image](https://github.com/gammapy/gammapy/assets/14164282/fb4aefea-228e-49a9-8e06-6ca541c67757)
(mu_bkg / alpha should replace mu_bkg above)

And the next one:
![image](https://github.com/gammapy/gammapy/assets/14164282/5a3aecc8-662e-448a-a4a1-de733049c770)

should rather be [alpha / (1+alpha)] n_on - mu_sig

After that, I think the rest is ok (the values of W)

**Comment by registerrier** [comment]
Thanks @moralejo . I remember that this changed at some point to be consistent (see e.g. #1936). 
Let's put this on the list for the next release.
