### ISSUE TITLE
`DarkMatterAnnihilationSpectralModel` not readable from `Models.read` 

### ISSUE THREAD

**Issue by StFroese** [gammapy/gammapy#4748]
**Gammapy version**
v1.1

**Bug description**
`DarkMatterAnnihilationSpectralModel` can't be instantiated when read from .yaml during execution of `Models.read`

If you combine a `DarkMatterAnnihilationSpectralModel` and a `SpatialModel` (i.e. `TemplateSpatialModel`for j-factor) to `SkyModel` and save this as `Models([sky_model]).write('some_file.yaml')`, you can not read in the yaml again with `Models.read('some_file.yaml').`
This is due to the problem that the `DarkMatterAnnihilationSpectralModel` is not found in the `SPECTRAL_MODEL_REGISTRY` since it is only appended inside the gammapy/astro/darkmatter/spectra.py.
The only solution right now is to import the file before de-serialization
```python
import gammapy.astro.darkmatter.spectra

...

Models.read('some_file.yaml')
```

**Solution**
Move the append of the `DarkMatterAnnihilationSpectralModel ` directly to the `SPECTRAL_MODEL_REGISTRY` at definition

**Comment by Astro-Kirsty** [comment]
This is not possible as the `DarkMatterAnnihilationSpectralModel` relies on `modeling` directly, which would lead to a circular import. The only way to get around this would be to adapt the location of the DM spectral models including API change which is not something we want to do. 

Instead I moved the appending to `gammapy.astro.darkmatter` but it means you still need to import it. 
Possibly we need further documentation?
