### ISSUE TITLE
Unkown `Note` section in docstring are not shown in docs. It should be Notes

### ISSUE THREAD

**Issue by morcuended** [gammapy/gammapy#4760]
**Gammapy version**
dev version

**Bug description**
Notes docstring on the progress bar added in #4737 are not included in docs () because the section should be named `Notes` and not `Note`. This actually gives warnings in docs deployment.

**Expected behavior**
Notes section should appear on the webpage.

**To Reproduce**
See e.g. https://docs.gammapy.org/dev/api/gammapy.estimators.LightCurveEstimator.html#gammapy.estimators.LightCurveEstimator.run

**Comment by registerrier** [comment]
This works now. 

I am not sure that all functions using the progress bar are mentioned though.

**Comment by Astro-Kirsty** [comment]
Yes, the correction is missing for:
`gammapy.scripts.download`
`gammapy.utils.parallel`

**Comment by morcuended** [comment]
Oops! missed those. There were no complaints in the docs deployment I think

**Comment by morcuended** [comment]
done in #4767 and #4762
