### ISSUE TITLE
Nearest neighbour interpolation for mass of `PrimaryFlux` produces high fluctuations for ULs

### ISSUE THREAD

**Issue by StFroese** [gammapy/gammapy#4781]
**Problem**
I was trying to compute some upper limits using the `DarkMatterAnnihilationSpectralModel` which uses the PPPC4DM gamma fluxes via the `PrimaryFlux` class. 
The PPPC fluxes are tabular data of flux points for given (mass, energy). 
In the current implementation of `PrimaryFlux` the mass parameter `mDM` is interpolated using nearest neighbour interpolation.

https://github.com/gammapy/gammapy/blob/cecb6f88328e894de1afb374a181f6203e0e9f08/gammapy/astro/darkmatter/spectra.py#L91-L96

This results in high fluctuations when calculating upper limits:

<img width="810" alt="Screenshot 2023-10-04 at 11 45 37" src="https://github.com/gammapy/gammapy/assets/44728015/0be46766-b6d0-48dc-9372-8acc16eb342d">

I took a look a the ratio of the interpolated masses and the masses that are used for this plot and this totally matches.

<img width="650" alt="Screenshot 2023-10-04 at 11 46 53" src="https://github.com/gammapy/gammapy/assets/44728015/6cec6894-8af3-400f-a44c-03088f7e3ff2">

**Suggested Solution**
Find out how to interpolate the values properly

**Comment by StFroese** [comment]
Since `DarkMatterAnnihilationSpectralModel` is `TemplateSpectralModel` this needs to be rewritten as a `SpectralModel` with the interpolation for a specific channel happening at the instantiation of the class and the `evaluate` method method would than wrap the interpolation function.

I think the best way to do this is to make it part of the refactoring of the `darkmatter` subpackage (#4776) and maybe moving away from the `DarkMatterAnnihilationSpectralModel` and let `PrimaryFlux` become the base `SpectralModel` for all spectral fluxes and build the model from there with the new introduced `SpatialModels` from the DM profiles

What do you think @registerrier @bkhelifi @jdjuvsla?

**Comment by StFroese** [comment]
For interpolation: maybe try https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.LinearNDInterpolator.html#scipy.interpolate.LinearNDInterpolator

**Comment by adonath** [comment]
Thanks @StFroese for the issue! I think the best way forward here would be to refactor to use the [`TemplateNDSpectralModel`](https://github.com/gammapy/gammapy/blob/main/gammapy/modeling/models/spectral.py#L1862), which handles nd-interpolation just fine.

Otherwise a simple code fix to use e.g. `np.interp` should also work for now.

**Comment by StFroese** [comment]
@adonath I took a look at it and I'm confused on how to use the `TemplateNDSpectralModel`. I built a `CircleSkyRegion` and took that together with one `MapAxis` for the masses and one `MapAxis` for the `Log[10, x]` energies to create a `RegionNDMap`. I passed that to the `TemplateNDSpectralModel` but I can't figure out how to use the `evaluate` method correctly. It seems that it the energy axis must be named `energy_true` and how do I take the evaluate on the mass axis?

https://github.com/gammapy/gammapy/blob/b038566e9267a5795f825336f177ad783c3932af/gammapy/modeling/models/spectral.py#L1917-L1926

**Comment by StFroese** [comment]
```python
from gammapy.maps import RegionNDMap, RegionGeom, MapAxis
from gammapy.modeling.models import TemplateNDSpectralModel
from regions import CircleSkyRegion
from astropy.coordinates import SkyCoord
import astropy.units as u

from gammapy.astro.darkmatter import PrimaryFlux
import numpy as np

coord = SkyCoord(0, 0, unit='deg', frame='galactic')
region = CircleSkyRegion(coord, radius=1 * u.deg)

table = PrimaryFlux('1 TeV', 'b').table
masses = np.unique(table['mDM'])
energies = np.unique(table['Log[10,x]'])

mass_axis = MapAxis.from_nodes(masses, name='mDM', interp='log')
energie_axis = MapAxis.from_nodes(energies, name='energy_true')

regionMap = RegionNDMap.create(region, axes=[mass_axis, energie_axis], data=table['b'])

model = TemplateNDSpectralModel(regionMap)
```

(small note: ignored units for now)

**Comment by StFroese** [comment]
ah nvm, I totally missend the kwarg unpacking to the coord dict haha
