### ISSUE TITLE
Adding metadata on Models

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#4789]
Metadata must be present for high level products. 

In the case of `~gammapy.modeling.models.Models`, minimal information should be provided. Obviously the creation information is necessary (i.e. gammapy version, date possibly author). 

Would you see anything else @bkhelifi @QRemy @adonath @kosack @fabiopintore ? A priori, I would assume that metadata is not relevant for simple `Model` objects.

Probably adding the `meta` on the in memory object is not necessary, but only to write the creation information in the form of yaml comments in `Models.write`. 

Are there cases where the creation information would be necessary on the in-memory object?

**Comment by bkhelifi** [comment]
This is associated to the PR #4819
