### ISSUE TITLE
Adding metadata on FluxMaps/FluxPoints

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#4790]
We need to create a `Metadata` class to carry the metadata information for `FluxMaps` and `FluxPoints`. Several aspects must be decided:

Do we need specific metadata class for flux point compared to the parent `FluxMaps` class? i.e. is a single metadata class on the parent enough? I would argue that for now we don't need two.

Currently we have information on the creation with the following keywords:
- n_sigma : float
- n_sgima_ul : float
- sqrt_ts_threshold_ul : float
- sed_type_init : str

What type of information do we want to store beyond this? (keeping in mind that this is metadata and not provenance)
- creation information obviously
- obsids used to create the parents datasets? 
- GTI (they are currently stored as a data member) ?
- Other? 

I assume what to propagate will become clearer once the lower level is defined. 

Opinions?

**Comment by bkhelifi** [comment]
The flux points are made for an assumed spectral shape, that one needs to store.
The GTI are needed and also the sky position, obviously...
I am thinking about the basic use case of an SED on an AGN. One needs to know the source and the GTIs!

When you say 'creation information', we are thinking about what? As metadata are not provenance data, then only very high-level info should be inserted... maybe the name of the Dataset(s), such that one can link the DL4 and DL5 products?

**Comment by registerrier** [comment]
> The flux points are made for an assumed spectral shape, that one needs to store. The GTI are needed and also the sky position, obviously... I am thinking about the basic use case of an SED on an AGN. One needs to know the source and the GTIs!

Currently, the `reference_model` is stored as part of the data as it is required to compute reference fluxes. When serializing it is exported as a template spectral model. I think that it should stay in the data but we might improve the serialization. 
We might add some information such e.g. model name as metadata but we should avoid duplicating the info 

The GTI are already stored as data. It might make sense to move them in metadata.

> When you say 'creation information', we are thinking about what? As metadata are not provenance data, then only very high-level info should be inserted... maybe the name of the Dataset(s), such that one can link the DL4 and DL5 products?

I meant creator (software version, date)
Yes indeed. A list of dataset names used is important info
