### ISSUE TITLE
Add a generator on Observations to yield full in memory observation

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#4806]
**Is your feature request related to a problem? Please describe.**
Currently observations do not go out of scope with the for loop. Hence we need to remove the caching of the data read from disk. This causes multiple access to a single file in a regular data reduction process which reduces performance especially for larges zipped files.

**Describe the solution you'd like**
A generator could defined on `Observations` that would yield a single in-memory `Observation` object. Since it would go out of scope at the end of the loop, the memory issues should go away.

**Describe alternatives you've considered**
We could also use an iterator? 
Only calling observation.events once is not really possible as we use the dataset maker and the background makers in a regular loop (esp. in 1D with `ReflectedRegionsBackgroundMaker`)

**Comment by adonath** [comment]
A context manager and a global "switch" might work as well:

```python 

with cache_observation():
    for obs in observations:
       ...
```
But I guess the iterator is simpler and cleaner...
