### ISSUE TITLE
Unify scheme for punctuation of parameters and returned objects in docstrings

### ISSUE THREAD

**Issue by morcuended** [gammapy/gammapy#4811]
Raised in #4805.

We should unify the scheme for punctuation of parameters, returned objects in the doctrings.

Also sometimes the description of a parameter contain several lines which are rendered in the docs as a single line. See for example the `selection` or `use_region_center` parameters in docstring of [SpectrumDatasetMaker](https://docs.gammapy.org/dev/api/gammapy.makers.SpectrumDatasetMaker.html?highlight=spectrumdatasetmaker#gammapy.makers.SpectrumDatasetMaker). I do not know if it's possible to show them as item list in the documentation but at least they should be ended with periods to make them more clear.

More information: https://peps.python.org/pep-0257/

**Comment by MRegeard** [comment]
Thanks @morcuended, 
`PEP8` and `PEP257` clearly states that docstring description should end with a full stop. I have made this task list bellow. If one want to take a module and check that docstring description end with a full stop (also don't forget to check for the Upper case at the beginning), they should add their name after the module name in the list. This way it is easy to keep track of who is going what !

- [ ] gammapy.analysis
- [ ] gammapy.astro
- [ ] gammapy.catalog
- [ ] gammapy.data (@MRegeard)
- [ ] gammapy.datasets
- [ ] gammapy.estimators
- [ ] gammapy.extern
- [ ] gammapy.irf
- [ ] gammapy.makers
- [ ] gammapy.maps
- [ ] gammapy.modeling
- [ ] gammapy.script
- [ ] gammapy.stats
- [ ] gammapy.utils
- [ ] gammapy.visualization

**Comment by registerrier** [comment]
should we use a static docstring checker like [pydocstyle](https://pydocstyle.org/en/stable/)?

**Comment by morcuended** [comment]
Thanks @MRegeard for creating the tasklist

> should we use a static docstring checker like [pydocstyle](https://pydocstyle.org/en/stable/)?

Yes, that is a good idea. Maybe we could even think of moving to Ruff (https://astral.sh/ruff) for the linting and all kind of checks

**Comment by registerrier** [comment]
> Thanks @MRegeard for creating the tasklist
> 
> > should we use a static docstring checker like [pydocstyle](https://pydocstyle.org/en/stable/)?
> 
> Yes, that is a good idea. Maybe we could even think of moving to Ruff (https://astral.sh/ruff) for the linting and all kind of checks

And at the risk of making the discussion diverge a bit more, we should consider pre-commit.ci too.

**Comment by MRegeard** [comment]
I don't really know how these things work, but it might actually be difficult to check that since some of our docstring parameter description are on several lines. 
For one line sentence, I guess it is easy to check if it ends with a full stop. But how would it handle the cases of multiple lines sentences ? And the case of multiple sentences description ?
