### ISSUE TITLE
Consistency with `format` in docstring

### ISSUE THREAD

**Issue by Astro-Kirsty** [gammapy/gammapy#4870]
There are a number of format options available in various functions throughout the code. 
At times, it is not clear which options are available or if there is only currently one option. This can be confusing, especially for a new user. 

For example here:
https://github.com/gammapy/gammapy/blob/b34bbe35b0044ce4c68d2fce67801e600160515a/gammapy/maps/axes.py#L1092-L1120

Versus a well explained docstring:
https://github.com/gammapy/gammapy/blob/b34bbe35b0044ce4c68d2fce67801e600160515a/gammapy/maps/hpx/core.py#L104-L134

**Comment by registerrier** [comment]
I have no strong opinion here. The first pattern is the more common one in docstrings afaik. It can be clear as well if the parameter description explains that the list of possible values is given and that the first one is the default.
