### ISSUE TITLE
Add a licence on the gammapy-data repository

### ISSUE THREAD

**Issue by bkhelifi** [gammapy/gammapy#4871]
**Is your feature request related to a problem? Please describe.**
This issue is a reminder to the issue 38 of the gammapy-data repository (https://github.com/gammapy/gammapy-data/issues/38). One should at least add a permissive licence to the repository, such that the next tag version of gammapy-data has a licence.

**Comment by Astro-Kirsty** [comment]
After looking into the different licenses, I agree with you Bruno that the "CC BY-NC-ND" seems appropriate.

Any other comment on this @adonath, @bkhelifi, @registerrier ?

**Comment by bkhelifi** [comment]
Or maybe this one : [CC BY-NC-ND 4.0 DEED](https://creativecommons.org/licenses/by-nc-nd/4.0/deed.fr)

**Comment by adonath** [comment]
I agree "CC BY-NC-ND" is mostly appropriate. We could however think about allowing derivatives of the data? But that depends on the initial license of the data as well...

**Comment by bkhelifi** [comment]
The issue is that they have not all the same licence, even some has no licence. So, it is hard to think about derivates....
If people wish, the best is that they ask to the data owner. 
This is why I think that this licence is safer. We do not take the responsibility of modification of data that are not produce by us;)

**Comment by adonath** [comment]
@bkhelifi Hm, but does this mean that people can never publish data results from a small study they made using Gammapy data?

**Comment by bkhelifi** [comment]
According to this licence, they can! As the licence forbid only a commercial use

**Comment by adonath** [comment]
The licence forbids "derivatives":

![Screen Shot 2023-12-14 at 8 28 50 AM](https://github.com/gammapy/gammapy/assets/3715928/4b97ed34-9a80-461f-82ae-947de342b932)

Does it mean if somebody computes flux points from the HESS DL3 DR1, they are not allowed to share it? I think this would be not what we want.

In any case I think we should first get the proper licenses for the original material and add it to the sub-folder...

**Comment by bkhelifi** [comment]
What what about [CC BY-NC 4.0 DEED](https://creativecommons.org/licenses/by-nc/4.0/deed.fr) ?
