### ISSUE TITLE
Miswritten if condition in pointing.py

### ISSUE THREAD

**Issue by ArmelleJB** [gammapy/gammapy#4914]
**Gammapy version**
gammapy 1.1

**Bug description**
Miswritten if condition (never enter the elif) in gammapy/data/pointing.py

```
if self.mode is PointingMode.POINTING:
            header["OBS_MODE"] = "POINTING"
            header["RA_PNT"] = self.fixed_icrs.ra.deg, u.deg.to_string("fits")
            header["DEC_PNT"] = self.fixed_icrs.dec.deg, u.deg.to_string("fits")
elif self.mode is PointingMode.POINTING:
            header["OBS_MODE"] = "DRIFT"
            header["AZ_PNT"] = self.fixed_altaz.az.deg, u.deg.to_string("fits")
            header["ALT_PNT"] = self.fixed_altaz.alt.deg, u.deg.to_string("fits")
```

`elif self.mode is PointingMode.POINTING` should likely be `elif self.mode is PointingMode.DRIFT`

**Other information**
Also in the dev version :
https://github.com/gammapy/gammapy/blob/daa25abce5d6ff081ba332d5d24a86f2b7a2aa2c/gammapy/data/pointing.py#L303C1-L311C1

**Comment by MRegeard** [comment]
Thanks @ArmelleJB, see the linked pull request.
