### ISSUE TITLE
Broken links in the documentation

### ISSUE THREAD

**Issue by bkhelifi** [gammapy/gammapy#4922]
**Gammapy version**
The dev version

**Bug description**
I have found two issues:
- [x] The link towards the ReflectedBackgroundMaker in https://docs.gammapy.org/dev/tutorials/api/makers.html#background-estimation seems to point towards the RindgBgMaker
- [x] In the page https://docs.gammapy.org/dev/api/gammapy.modeling.Parameter.html?highlight=priors, a link towards the `Prior` class is proposed. However the class is called `PriorParameter` and it seems to be not yet exposed.
- [x] In https://docs.gammapy.org/dev/user-guide/model-gallery/spectral/plot_absorbed.html, the link towards the EBL models list is broken

**Comment by MRegeard** [comment]
Thanks @bkhelifi, I think that we don't want to expose priors at the moment. 
Is it the case @katrinstreil ? Or is it a mistake ?
