### ISSUE TITLE
MC event lists

### ISSUE THREAD

**Issue by TarekHC** [gammapy/gammapy#494]
Hi @cdeil,

Is there any proposed data format for MC event lists? (adding "MC_" tag to the required additional columns or something like that?)

Thanks!

**Comment by cdeil** [comment]
I'm not aware on status on proposed data format for MC event lists.

@kosack or @gernotmaier - Comments?

Probably this shouldn't be discussed in the Gammapy Github tracker.
Maybe at https://github.com/open-gamma-ray-astro/gamma-astro-data-formats or https://github.com/cta-observatory/ctapipe , or more likely some CTA-internal forum or issue tracker?

**Comment by TarekHC** [comment]
I was not referring to CTA event lists, so I guess the best place would be https://github.com/open-gamma-ray-astro/gamma-astro-data-formats. Thanks!

**Comment by cdeil** [comment]
@TarekHC - I'm closing this issue now.

I agree this will be a topic in the near future, but my suggestion would be new issues or pull requests
- in the `gamma-astro-data-formats` issue tracker or in CTA when it's about the format
- on cta-pipe and / or gammapy if it's about adding support for MC event lists

**Comment by TarekHC** [comment]
Sure, no worries. 

Within ctapipe, probably it is a bit too early to talk about data formats... And MC event lists at DL3 and above has probably a lower priority... But I guess it should be encountered.

**Comment by kosack** [comment]
I agree - if you add some optional MC-related columns to your DL3 format in `gamma-astro-data-formats`, that should be sufficient for us to use it in DL2, etc.
