### ISSUE TITLE
Tutorial for more complex background models

### ISSUE THREAD

**Issue by Astro-Kirsty** [gammapy/gammapy#4947]
Currently we expose how to utilise the `FoVBackgroundMaker` with a `PowerLawNormSpectralModel` that have both tilt and norm unfrozen. 

It could also be useful for users to understand how to correctly implement a more complex background. For example utilising the `PiecewiseNormSpectralModel`.

**Comment by registerrier** [comment]
This has been done in #4821 . Is there anything else to do or can we close the issue @Astro-Kirsty ?

**Comment by Astro-Kirsty** [comment]
There was discussion in the coding sprint to expose further complex background methods. 

#4821 exposes how to utilise the `PowerLawNormSpectralModel`, but that is all. 
There could be other complex methods?
