### ISSUE TITLE
Allow estimators to work with different instruments

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#4988]
Currently, we have a "safety check" which prevents `FluxPoints` computation from different instruments simulataneously

https://github.com/gammapy/gammapy/blob/888905e4d6966b31b564cc3a0e45affa5e45cb14/gammapy/estimators/points/sed.py#L139-L145

As brought up by @jlenain in the HESS slack, this prevents a light curve extraction for CT1-4 + CT5.
There are many other similar use cases, eg: CTA LST + MST...

Removing this security does extract reasonable flux points.

@registerrier @bkhelifi @QRemy @adonath Any obvious issues in allowing estimators to work with different instruments? Any other safety checks we could ensure? Or can we allow this and leave a sanity check to the user?

**Comment by jlenain** [comment]
Thanks a lot, @AtreyeeS , for reporting it here! I can provide more details if needed.

I thought that, perhaps, the current behavior could be kept as is, but with the addition of an optional argument (false by default) to bypass this security in the different flux point/light curve estimators.

**Comment by adonath** [comment]
See https://github.com/gammapy/gammapy/pull/4118#issuecomment-1265473025

**Comment by adonath** [comment]
In general multi instrument flux points can only rely be computed using unfolding. If the energy dispersion is reasonably close between the datasets it should give reasonable results, however we do not have general way of checking this.

**Comment by registerrier** [comment]
This is partly solved in #5331 . Closing now. 
Keeping related issue #4123
