### ISSUE TITLE
Shape of MapCoord for large non-spatial dimension

### ISSUE THREAD

**Issue by katrinstreil** [gammapy/gammapy#5004]
**Gammapy version 1.1**

**Bug description**
When creating a MapCoord with 2 coordinates and 3 energy bins calling the `shape` attribute results in a value error.  

**To Reproduce**
Following the example in `MapCoord.create` but using three energies instead of one.
```
from astropy.coordinates import SkyCoord
from gammapy.maps import MapCoord
lon, lat = [1, 2], [2, 3]
skycoord = SkyCoord(lon, lat, unit='deg')
energy = [1000, 3000, 5000]
c = MapCoord.create(dict(skycoord=skycoord,energy=energy))
c.shape
```
Resulting errormessage:
```
ValueError: shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 0 with shape (2,) and arg 2 with shape (3,).
```

**Comment by adonath** [comment]
Thanks @katrinstreil, I think the behavior is completely correct. The coordinate arrays cannot be broadcasted to a single shape. What was the behavior you expected?

**Comment by katrinstreil** [comment]
In the description of the `MapCoord` it says: `Contains coordinates for 2 spatial dimensions and an arbitrary number of additional non-spatial dimensions.` So I would expect that initialising with an arbitrary number of energies and calling `shape` is possible.

**Comment by adonath** [comment]
> Contains coordinates for 2 spatial dimensions and an arbitrary number of additional non-spatial dimensions.

That's a misunderstanding: the arbitrary number of non-spatial dimensions refers to the dimension of the coordinate system. So "lon, lat" is 2d, "lon, lat, energy" is 3d etc. The number of non-spatial dimensions (energy, time, event class) can be arbitrary. For the actual coordinate arrays, broadcasting rules must apply. Probably we should improve the docs in this regard.

**Comment by AtreyeeS** [comment]
@katrinstreil Note that if you rather have `energy = np.array([1000, 3000, 5000]).reshape(-1,1)` (ie, correctly broadcasted), then your example works.

**Comment by adonath** [comment]
We should probably add some examples in the docstring as well...

**Comment by AtreyeeS** [comment]
@adonath can it be made to break on `init`?  That makes it easier to understand, otherwise, it seems that the `MapCoord` is created but something is funny with its shape
