### ISSUE TITLE
Behaviour of gammapy.utils `interpolate_profile`

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#5005]
**Gammapy version**
Latest dev

**Bug description**
There seems to be small interpolation effects near the minima for the ScaledRegularGridInterpolator.

**To Reproduce**
```
from scipy.interpolate import interp1d
import matplotlib.pyplot as plt
from gammapy.utils.interpolation import interpolate_profile

x = [0.2,   0.27594593, 0.38073079, 0.52530556, 0.72477966, 1., 1.37972966, 1.90365394, 2.6265278,  3.62389832, 5.        ]
y = [ 45.19685382,  26.28875168,  13.47343231,   9.56132843,
        18.27203015,  44.63282147,  95.50949058, 180.32676044,
       312.05478467, 508.56544908, 794.50056902]

f1 = interp1d(x, y, kind="quadratic")
f2 = interpolate_profile(x, y)

x1 = np.linspace(0.2, 3, 100)
plt.plot(x1, f1(x1), label="scipy.interpolate.interp_1d")
plt.plot(x1, f2([x1, x1]), label="gammapy.utils.interpolation.interpolate_profile")
plt.legend()
```

shows
![image](https://github.com/gammapy/gammapy/assets/32677370/e47f3587-c2be-4dd2-bab9-03c0a797438d)

It seems that the gammapy interpolate_profile ensures the minima at zero. Is that the desired behaviour or am I using it wrong?
Help @adonath or @QRemy or anyone else please?

**Comment by adonath** [comment]
@AtreyeeS Yes, the `interpolate_profile` assumes the parabola minimum to be at zero. Which should b the case for likelihood profiles by definition. To make the function a bit more generally useful we could allow the profile to be shifted as well, however in you specific case, it might be worth figuring out, why the profile does not go through zero.

**Comment by AtreyeeS** [comment]
>Yes, the interpolate_profile assumes the parabola minimum to be at zero

Where is the assumption? In the `ScaledRegularGridInterpolator`? 

> Which should b the case for likelihood profiles by definition. 

Presence of a constant additive term should not affect the likelihood minimisation, no?

**Comment by adonath** [comment]
> Where is the assumption? In the ScaledRegularGridInterpolator?

Not only.  The assumption is in the square root scaling and the following line: https://github.com/gammapy/gammapy/blob/main/gammapy/utils/interpolation.py#L262

The sqrt scaling and the sign handling convert a parabola into a line. Then the `ScaledRegularGridInterpolator` does linear interpolation and converts back.

> Presence of a constant additive term should not affect the likelihood minimisation, no?

No, but the `interpolate_profile` does a more specific thing: it does interpolate the ts profile, not the likelihood surface. The TS profile, by definition is with respect to the minimum. If there are good reasons we can loosen that assumption. Right now, I can't think of any.
