### ISSUE TITLE
Use astropy table indexing in ObservationTable

### ISSUE THREAD

**Issue by joleroi** [gammapy/gammapy#501]
https://github.com/gammapy/gammapy/blob/master/gammapy/data/observation.py#L53

**Comment by registerrier** [comment]
This requires adapting `ObservationTable.select_obs_id` to make it work with `Table` indexing, e.g. by introducing an index `obs_table.add_index('OBS_ID')`

**Comment by registerrier** [comment]
This is implemented in #4051 . Closing now.
