### ISSUE TITLE
datasets.info_table() returns inconsistent values.

### ISSUE THREAD

**Issue by LukasNickel** [gammapy/gammapy#5019]
**Gammapy version**
Current master / 1.1
Probably its in all version.

**Bug description**
The code for `datasets.info_table()` returns a table with "wrong" values.
For the first dataset, `to_masked` is called before retrieving the info_dict, for all others it is not.

This produces inconsistent output if any masks are attached to the dataset.
Also seems to matter for an attached FoVBackgroundModel, but I don't see why right now.

https://github.com/gammapy/gammapy/blob/0b099a7c68b702ff6e0b5451abd4e5b155530f6f/gammapy/datasets/core.py#L502-L530

**Expected behavior**
Either use `to_masked` everywhere or never.

**Comment by MRegeard** [comment]
Thanks @LukasNickel, see the link pull request.
