### ISSUE TITLE
Multi-instrument joint fit with MAGIC data

### ISSUE THREAD

**Issue by giulia-brunelli** [gammapy/gammapy#5033]
I am performing a joint fit of Fermi-LAT and LST-1 data following this tutorial: https://docs.gammapy.org/1.1/tutorials/analysis-3d/analysis_mwl.html?highlight=multi%20instrument .
The LST-1 dataset is in the format of `SpectrumDatasetOnOff` (in the tutorial this would be the HESS dataset) and the Fermi-LAT one is a `FluxPointsDataset` (corresponding to the HAWC dataset in the tutorial).

My request is: is there a way to properly include also MAGIC flux points (in the form of `FluxPointsDataset`) without worrying about the correlation matrix between those points and then perform a joint fit of the three datasets (Fermi, MAGIC, LST-1) with the correct statistics?

**Comment by AtreyeeS** [comment]
Discussing this issue with people within the MAGIC collaboration, it seems there is not any simple consistent way to do it. The deconvolution of the MAGIC data to obtain the spectral points have been done in different ways, and the correlation depends on the regularisation method used. Some MAGIC flux points do not provide the associated correlation.

Can you provide some more information on your MAGIC analysis @giulia-brunelli ? How were the spectral points obtained and how the correlation info is available?

**Comment by giulia-brunelli** [comment]
@AtreyeeS I didn't perform the MAGIC analysis, but a collaborator provided me with the flux points and their correlation matrix. The latter is stored in a simple text file including the correlation matrix values between the flux points. 

For now, I included these points in the fit by adding a `FluxPointsDataset` of the MAGIC flux points in the same way as I do with the Fermi-LAT ones and ignoring the correlation matrix, even if I know it's just an approximation.

**Comment by AtreyeeS** [comment]
@giulia-brunelli Can you provide a toy example with some flux points and a correlation matrix and the best fit spectral model obtained through backward folding?

**Comment by registerrier** [comment]
This requires some precise information on what the piecewise model is and the actual covariance matrix. More details are necessary. Closing for now.
