### ISSUE TITLE
Modify EventList serialization

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#5042]
Currently one can serialize an `EventList` in two ways. Namely:
- `EventList.write()` which will call into `EventList.to_table_hdu`.
- `Observation.write()` with `include_irfs` set to `False`. 
This is problematic for various reasons:
1. `EventList.write` relies on the `EventList.table.meta` to export the various metadata and keywords. We cannot guarantee they follow the gadf standard. It should change to `EventList.meta` instead.
2. `EventList.meta` should most likely not contain all meta informations that belong to `ObservationMetaData`. `ObsInfoMetaData` belongs to `Observation`, not `EventList`. Duplicating seems a bad idea. Yet without these informations, it is not possible to serialize the `EventList` to gadf. 
3. Currently `MapDatasetEventSampler` relies on a specific function `event_list_meta` to fill the `EventList.table.meta`. This should not be necessary.

In the long run, we want to have a clean separation of data format and data model. IO should be performed by a specific `GADFWriter` object to avoid spreading format specification and code all over the code.

I propose we deprecate `EventList.write` and instead rely on `Observation.write` to serialize event lists. Most of the metadata export should be performed there. Then we have a cleaner scheme to implement a proper GADF exporter.

Does it sound reasonable @fabiopintore, @adonath, @LauraOlivera @AtreyeeS @Astro-Kirsty @bkhelifi ?

**Comment by AtreyeeS** [comment]
I guess there is indeed no other reasonable solution that going through `Observation.write`, but if I remember correctly, `Event_list.write` was introduced because it was the only gammapy object that could not write itself. Users were still serialising it, but missing some keywords which were creating issues, which is why we thought it would be okay to add this method.

We will have to document this really well to prevent the same in future...

**Comment by fabiopintore** [comment]
Thanks @registerrier . The approach you're suggesting sounds good and clean. I agree to deprecate the `MapDatasetEventSampler.event_list_meta` as it should be often updated, can be in conflict with other metadata and it's a not crucial code duplication. So +1 to just rely on `Observation.write`.
