### ISSUE TITLE
Astropy 6.0 API Change

### ISSUE THREAD

**Issue by ccossou** [gammapy/gammapy#5080]
I installed gammapy (1.1) on python 3.10 today, using 
```
pip install gammapy
```
and I got this error while attempting to use gammapy sensitivity functions
```
ModuleNotFoundError: No module named 'astropy.coordinates.angle_utilities'
```
See this issue in astropy for reference: https://github.com/astropy/astropy/issues/14675
From astropy changelog, they say: 
Removed deprecated angle parsing and formatting utilities from angle_utilities. Use the functions from angle_formats instead. [[#14675](https://github.com/astropy/astropy/issues/14675)]

Either a forced version of astropy in the dependencies, or a change in the import could solve this. 

Hope it helps, 
Christophe

**Comment by adonath** [comment]
Thanks @ccossou, as far as I know this already been resolved in https://github.com/gammapy/gammapy/pull/4937. I will be part of the next releases.

**Comment by ccossou** [comment]
Ah, sorry for the unecessary issue.
