### ISSUE TITLE
Read 2FHL results into SpectrumFitResult

### ISSUE THREAD

**Issue by joleroi** [gammapy/gammapy#509]
I would like to store the PowerLaw spectra from the 2FHL in a gammapy ``SpectrumFitResult``. The spectra are given with the integral flux between two energies as normalization (see http://fermi.gsfc.nasa.gov/ssc/data/analysis/scitools/source_models.html#PowerLaw2).
Gammapy has functionality to evaluate such a model (http://gammapy.readthedocs.org/en/latest/api/gammapy.spectrum.f_with_err.html#gammapy.spectrum.f_with_err).

Should I 

* Introduce a new model "PowerLawIntNorm" (note that neither Sherpa nor astropy.models support such a model)
* Translate the model into a regular PowerLaw,  this would be the nicest solution I guess.

The problem with the latter approach is that I don't know where to set the Reference energy E_0. I think it needs to be set at the decorrelation energy, since I have no idea how to infer the correlation between differential flux norm and index from the Catalog. However, the Catalog also does not state the decorrelation energy. Any ideas?

**Comment by cdeil** [comment]
Either way is OK.

There is a reason the Fermi and HESS software has different parametrisations for the same spectral shapes. Especially the ones with integral fluxes as normalisation are valuable, because they lead to less-correlated fit parameters. So probably we'll add different parametrisations from the HESS software or Fermi ST.

But for now, maybe converting the model to PL with diff flux as norm at the pivot energy is fine also. I think the Fermi catalogs all have a `Pivot_Energy` column (at least that's what I remember and also what's claimed [here](http://fermi.gsfc.nasa.gov/ssc/data/access/lat/2yr_catalog/2FGL_column_descriptions_v6.pdf)).

**Comment by joleroi** [comment]
Thanks for the reply!

Unfortunately the 2FHL does not contain  the ``Pivot_Energy`` as far as I see (that's the core of my problem I guess)

```
In [1]: from gammapy.catalog import source_catalogs

In [2]: cat_2fhl = source_catalogs['2fhl']

In [3]: source = cat_2fhl['2FHL J2323.8+4209']

In [4]: source.data['Pivot_Energy']
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-4-be00011cc225> in <module>()
----> 1 source.data['Pivot_Energy']

KeyError: 'Pivot_Energy'
```

also e.g. http://heasarc.gsfc.nasa.gov/db-perl/W3Browse/w3hdprods.pl?files=P&Target=heasarc_fermifhl|||_unique_id%3D84||&Coordinates=Equatorial&Equinox=2000

I don't even understand if the concept of the decorrelation energy makes sense for the PowerLaw2 parametrization by Fermi (with the Integral as normalization). I could be that the Integral and Index are completely uncorrelated (at least I don't see a strong reason why they should be (which does not mean there isn't one :smile: ))

**Comment by cdeil** [comment]
Looks like the latest version of the 2FHL catalog has a Pivot_Energy column:
```python
from astropy.table import Table
t = Table.read('http://fermi.gsfc.nasa.gov/ssc/data/access/lat/2yr_catalog/gll_psc_v09.fit')
t['Pivot_Energy']
```
Maybe the bundled file in gammapy-extra should be updated?

The change log at http://fermi.gsfc.nasa.gov/ssc/data/access/lat/2yr_catalog/ doesn't mention any changes concerning Pivot_Energy, but maybe they did change something?

**Comment by cdeil** [comment]
Also: if you use integral flux as fit parameter it's **less* correlated with other spectral parameters.
You can assume the correlation is zero if you like.

But it's not exactly zero (why should it given a complex model and dataset), there are some correlations.

**Comment by joleroi** [comment]
The file you downloaded is the 2FGL
```
In [14]: t['Source_Name'][0]
Out[14]: '2FGL J0000.9-0748 '
```
Here the PWLs are parametrized in the 'normal way' 
```
dN/dE = N (E/E_0) ^ gamma
```
Hence the Pivot Energy column

**Comment by cdeil** [comment]
Sorry, I misread the title of the PR as 2FGL the whole time.

So if you want to have something quick for 2FHL and it doesn't have pivot energy, you could just put a fixed value of 100 GeV (a value in the middle) and leave a "TODO: use integral PL model once it's implemented".

(I'm offline now until tonight)

**Comment by joleroi** [comment]
:see_no_evil:

**Comment by cdeil** [comment]
@joleroi - Can you please close this issue or summarise what remains to be done?

(moving this to the 0.5 milestone, not essential for the upcoming 0.4 release)

**Comment by joleroi** [comment]
There seems to be no good short  term solution. 2FHL results cannot simply be expressed as "normal" Powerlaw

**Comment by cdeil** [comment]
As I said, for now you could just use 100 GeV as reference energy and convert the given integral flux to a differential flux at 100 GeV and use the differential PowerLaw to plot a butterfly ... the result will be very close.

**Comment by joleroi** [comment]
Yeah but there's no real point in that is there? I can just plot the integral model directly if I want a working solution.
http://gammapy.readthedocs.org/en/latest/api/gammapy.spectrum.f_with_err.html#gammapy.spectrum.f_with_err
