### ISSUE TITLE
MapDatasetEventSampler fails for very bright sources

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#5112]
**Gammapy version**
1.0 to dev

**Bug description**
The `MapDatasetEventSampler.sample_psf` and `MapDatasetEventSampler.sample_edisp` perform vectorized sampling, internally creating a pdf array of shape `(nevents, rad_axis.nbins)` and `(nevents, migra_axis.nbins)`. This can cause a memory issue when the number of events is larger ~1e6. 

**Expected behavior**
To avoid the issue the sampling should be performed by bunches of events. This could handled by a parameter defined on `MapDatasetEventSampler.__init__()`.

**To Reproduce**
Replacing the flux in the event sampling tutorial by `"1e-7 TeV-1cm-2s-1"` will lead to memory overload

**Comment by adonath** [comment]
I don't agree that this is a bug. Sampling with highest precision requires sufficient memory. But yes we could support multiple modes of precision, with lower requirement on the memory usage. For bright point source the behavior could be simplified further. For bright extended source one would always need a trade off. The modes could be:

- Per event edisp
- Per source edisp
- Per sub-map / tile edisp
- Per whole map edisp

**Comment by registerrier** [comment]
I am not sure I completely follow here. 
To me the point is that `IRFMap.sample_coord` should not compute a pdf/cdf for all values that are passed at once as this will cause problems that might be difficult to understand. It is not obvious that this does broadcasting internally. 
It seems more reasonable to perform it splitting the input coords into smaller chunks.

**Comment by adonath** [comment]
`IRFMap.sample_coord` interpolates the PSF and EDisp for each exact(!) event position, which is the correct thing to do for highest precision, especially for extended source when, the IRF varies across the source. This is were the memory requirement comes from. 

To reduce the memory we need to introduce approximations, either by using single IRF per source component (as we do for fitting) and ignore that the IRF changes across the source, or group events by smaller "tiles" of the IRF map. One could even skip interpolation completely and use the event groups defined by the Binnig of the IRF map.
