### ISSUE TITLE
No reoptimization for `confidence_iminuit`

### ISSUE THREAD

**Issue by StFroese** [gammapy/gammapy#5152]
It seems that the confidence calculation for iminuit takes `reoptimize` as an arg but the logger gives a warning that it's not used if it's False, but the arg is actually not referenced in any of the following lines. I have two questions:
1. Wouldn't it make sense to allow the case where one does not want to reoptimize all other parameters?
2. If we don't use `reoptimize` at all, can't we just remove the arg from the function?

https://github.com/gammapy/gammapy/blob/fdd05df7453c294a8a898e7f790a0da17372f9d2/gammapy/modeling/iminuit.py#L114-L117

**Comment by QRemy** [comment]
For point 1.  it seems not configurable with [minos]( https://scikit-hep.org/iminuit/reference.html#iminuit.Minuit.minos):
"Minos is computationally expensive when there are many fit parameters. Effectively, it scans over one parameter in small steps and runs a full minimisation for all other parameters of the cost function for each scan point."

For point 2.  we probably have to keep the arg anyway for consistency with confidence_scipy

**Comment by QRemy** [comment]
I think no actions are needed here, closing.
