### ISSUE TITLE
Allow `MapAxis` to be passed in `SpectralModel.plot()` ?

### ISSUE THREAD

**Issue by Astro-Kirsty** [gammapy/gammapy#5171]
Currently in the `SpectralModel.plot()` we allow the user to define the `energy_bounds`. (This would also apply to the `plot_error` function)
Should we also allow them to pass a `MapAxis`? 
This relates to discussions here: https://github.com/gammapy/gammapy/issues/5086#issuecomment-1935949104 and https://github.com/gammapy/gammapy/issues/3078#issuecomment-715320223. 

**Describe the solution you'd like**
If we wish to allow this there will be an API change. 
Both `energy_bounds` and `map_axis` would need to be set to `None` inside the function:
` def plot(self, energy_bounds=None, map_axis=None......)`

Then the user would defined either the `energy_bounds` or `map_axis`. I am not sure on this solution however because I do not think it makes sense to have them set to None, this would be confusing to the user and they may think the function can be run without defining either. 

Open to further discussion on whether we wish to allow the functionality to pass a `MapAxis`, and how we could implement that.

**Comment by AtreyeeS** [comment]
> I do not think it makes sense to have them set to None, this would be confusing to the user

I don't think this is a major issue. You can mention in the docstring that either of the 2 need to be specified, and `map_axis` takes preference if both are present.  And then also raise an error if both are None
