### ISSUE TITLE
Geom `_get_pix_all` might use the wrong indexing

### ISSUE THREAD

**Issue by StFroese** [gammapy/gammapy#5182]
**Gammapy version**
main branch and released versions

**Bug description**
I created a small example below which shows that the Lon and lat axes are swapped when one wants to evaluate a bkg model. (and most probable other IRFs too)

```python
from gammapy.irf import Background3D, FoVAlignment
from gammapy.maps import MapAxis, WcsGeom
from gammapy.data import FixedPointingInfo
from gammapy.makers.utils import _get_fov_coords, make_map_background_irf
import astropy.units as u
from astropy.coordinates import SkyCoord, AltAz, EarthLocation
from astropy.time import Time
import numpy as np
import matplotlib.pyplot as plt

fov_lon = MapAxis.from_bounds(-3, 3, nbin=10, unit='deg', name='fov_lon')
fov_lat = MapAxis.from_bounds(-3, 3, nbin=10, unit='deg', name='fov_lat')
energy = MapAxis.from_energy_bounds('1 TeV', '10 TeV', nbin=10, name='energy')

data = np.ones((10,10,10))
data[:,4,:] = 0


plt.imshow(data[0])
```
![bar.pdf](https://github.com/gammapy/gammapy/files/14746266/bar.pdf)

```python
bkg = Background3D([energy, fov_lon, fov_lat], data=data, unit='s^-1 MeV^-1 sr^-1', fov_alignment=FoVAlignment.RADEC)

fixed_icrs = SkyCoord(ra='180 deg', dec='0 deg', frame='icrs')
obstime = Time('2024-01-01T00:00:00')
location = EarthLocation.of_site('Roque de los Muchachos')

pointing = FixedPointingInfo(fixed_icrs=fixed_icrs, location=location)

geom = WcsGeom.create(npix=10, binsz=0.6, skydir=fixed_icrs, axes=[energy])


coords = _get_fov_coords(
        pointing=pointing,
        irf=bkg,
        geom=geom,
        use_region_center=True,
        obstime=obstime,
    )

bkg_map = make_map_background_irf(pointing=pointing, ontime=20*u.min, bkg=bkg, geom=geom, obstime=obstime)

bkg_map.plot_grid(ncols=5)

```
![bar_rotate.pdf](https://github.com/gammapy/gammapy/files/14746275/bar_rotate.pdf)

What's happening is that `make_map_background_irf` creates fov_lon and fov_lat coordinates on order to evaluate the IRF.
These coordinates come from here: https://github.com/gammapy/gammapy/blob/86488ece61f41e92ff3212b9b870f5a9f7d68b79/gammapy/makers/utils.py#L53-L55

As you can see the coords are created by the `get_coord()` method. This method calls:
https://github.com/gammapy/gammapy/blob/86488ece61f41e92ff3212b9b870f5a9f7d68b79/gammapy/maps/wcs/geom.py#L634

which returns:
https://github.com/gammapy/gammapy/blob/86488ece61f41e92ff3212b9b870f5a9f7d68b79/gammapy/maps/wcs/geom.py#L582

The `[::-1]` makes the `indexing='ij'` obsolete here (in this special case with no energy axis?) and therefore the fastest changing axis is no longer the last one but the first one (fov_lon axis).

This is a problem because the IRF `evaluate` method uses the `ScaledRegularGridInterpolator`.
https://github.com/gammapy/gammapy/blob/86488ece61f41e92ff3212b9b870f5a9f7d68b79/gammapy/utils/interpolation.py#L123-L127

As you can see, numpy's `reshape` is called which assumes `order=C` or in other words the last axis should be the fastest changing one. 
This results in the transposed spatial output of the background map.

Is the `[::-1]` here `np.meshgrid(*pix_all[::-1], indexing="ij", sparse=sparse)[::-1]` necessary?
Update: Probably yes, but this still needs a fix somewhere I guess

**Comment by StFroese** [comment]
> This is a problem because the IRF `evaluate` method uses the `ScaledRegularGridInterpolator`.
> 
> https://github.com/gammapy/gammapy/blob/86488ece61f41e92ff3212b9b870f5a9f7d68b79/gammapy/utils/interpolation.py#L123-L127

you can also print the `point_interp` here:
```python
[[ 0.11512925  2.7        -2.7       ]
 [ 0.11512925  2.1        -2.7       ]
 [ 0.11512925  1.5        -2.7       ]
 ...
 [ 2.18745584 -1.5         2.7       ]
 [ 2.18745584 -2.1         2.7       ]
 [ 2.18745584 -2.7         2.7       ]]
```
as you can see, the second value is changing and not the last one
(order here is energy, fov_lon, fov_lat)

**Comment by registerrier** [comment]
Hi @StFroese , if you do `bkg.plot_at_energy([1*u.TeV])` I think you get a consistent picture with what `make_irf_background_map` is creating. I am not sure the issue lies in `get_coord()`. Maybe more likely in the unintuitive way the axes are represented between `Geom` and data.

**Comment by StFroese** [comment]
> Hi @registerrier, this yields to the same plot as imshow
> 

ahh, `fov_lat` is the x axis here

**Comment by StFroese** [comment]
@registerrier So this means when I create a Background3D instance that the first axis of data must be the fov_lat axis, right? 😅

**Comment by StFroese** [comment]
@registerrier is correct, I'll checked again and close this :)
