### ISSUE TITLE
Docs are unreadable in dark mode and there is no button to switch to light

### ISSUE THREAD

**Issue by maxnoe** [gammapy/gammapy#5191]
**Gammapy version**

Current developer documentation

**Bug description**

The current styling of the Gammapy documentation results in unreadable text when using dark mode, which is used by default if the system is configured to be dark:

![docs_theme_dark](https://github.com/gammapy/gammapy/assets/5488440/5e2f5d61-1fee-4fa3-97a4-0f066ad701ad)

**Expected behavior**

Use a styling that results in well-readable text in dark mode or force light mode.

**To Reproduce**

Visit the documentation with system configured to use dark mode.

**Comment by morcuended** [comment]
I think the docs in dark mode are still not readable (at least the current dev version)


![immagine](https://github.com/user-attachments/assets/785f6483-2d50-4013-9959-9ba99714f968)

The text color in the main body should change

**Comment by Astro-Kirsty** [comment]
@morcuended, it is not explained here, but the decision was that we do not 'support' the dark theme. Hence why we decide to force the light theme.

**Comment by morcuended** [comment]
Ah! thanks @Astro-Kirsty but the dev version of the docs still allows setting the dark theme. I think the switch button should then be removed, no?

**Comment by Astro-Kirsty** [comment]
Yes that is probably a good idea. Can you make a PR please? 
This choice was for v1.3, I am not sure what the plan is v2.0. 
So lets just move the milestone here for v2.0 and we can discuss later
