### ISSUE TITLE
Docs requirement specification in `environment-dev.yml` are incompatible

### ISSUE THREAD

**Issue by maxnoe** [gammapy/gammapy#5192]
**Gammapy version**

Current main branch.

**Bug description**

It is currently impossible to setup a gammapy dev environment, because the `environment.yaml` requires `pydata_sphinx_theme==0.15.2`, which requires `sphinx >= 5.0`, which is incompatible with the requirement `sphinx < 5` of `sphinx-panels`.

`sphinx-panels` is unmaintained and will not be updated. A replacement seems to be `sphinx-design`.

**Expected behavior**

Have a working dependency specifications

**To Reproduce**
```
mamba env create -f environment-dev.yaml
```

**Comment by maxnoe** [comment]
The reason this doesn't fail in the CI is that pip happily installs an even older version of `sphinx-panels` (0.4.1) which doesn't yet contain the pin of the sphinx version, but is of course even less compatible to current sphinx versions...

**Comment by registerrier** [comment]
This has been solved in #5193 . Closing now.
