### ISSUE TITLE
Debug plots for spectrum analysis

### ISSUE THREAD

**Issue by joleroi** [gammapy/gammapy#520]
Define a list of debugs plots to be implemented for the gammapy.spectrum module

* [ ] Stacked ON, OFF vectors entire energy range (like BgStats)
* [ ] Stacked ON, OFF vectors in safe energy range (like spectrum stats)
* [ ] SkyMap showing ON OFF counts, pointings, regions (see https://github.com/gammapy/gammapy/pull/491) 

Put all these on a summary html page

**Comment by joleroi** [comment]
@cdeil @JouvinLea 

Please add what you think is needed. I need a plan, otherwise this will never happen

**Comment by cdeil** [comment]
The most important diagnostics are the observed and predicted counts distributions (predicted split into gammas and background) and a vertical line where the safe energy thresholds are.

Once you have those we can debug EDISP, stacking, compare to HESS software, i.e. have plenty of checking to do and document.

So just start with a few numbers and one plot and try to put that in master. Then this can grow over the coming months....

**Comment by joleroi** [comment]
please add a TODO item - I know that we need this plot

**Comment by cdeil** [comment]
It's a bit tricky to define the exact list of counts histograms to show right now.
- I think you don't need a separate plot for outside the safe energy range. This can just be indicated by a vertical line, or by different coloring / shading.
- I think the more info you combine on one plot, the better. I.e. observed and model counts should be on one plot (but maybe implemented in such a way that they can also be plotted as separate panels below each other, with other panels for livetime and alpha, similar to what FitSpectrum produces as debug plot).

Developing good debug plots needs some trial and error and iteration ... I can't give a complete list of 5 plots we'll need now. Just start with one. Then we'll try to understand it and the resulting high-level spectral results. Then we'll probably notice what other diagnostics are needed to fully understand spectral results.

**Comment by cdeil** [comment]
For reference, there *might* be some useful code in #491 which wasn't merged.

**Comment by cdeil** [comment]
@joleroi - Move to 0.6 milestone? Or do you have time to finish this in the next day or two?

**Comment by joleroi** [comment]
No. as you said earlier this issue maybe doesn't make sense at all. We can close it IMO.

**Comment by cdeil** [comment]
OK, I'm closing this issue now. (one more, I'm trying to finish up issues and PRs to get the v0.5 release out the door).
