### ISSUE TITLE
split_dataset fails if no template model is set and split_template_models=True

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#5213]
**Gammapy version**
v1.2

**Bug description**
When running `split_dataset(dataset, 0.3*u.deg)` on a `MapDataset` with no `TemplateSpatialModel` set, an exception is raised.
This is because by default `split_template_models=True`. 

**Expected behavior**
It shouldn't break and proceed as if `split_template_models=False`.

**To Reproduce**

**Comment by Astro-Kirsty** [comment]
I am not able to reproduce this bug. Could you confirm how to reproduce it please?
