### ISSUE TITLE
Returning Alpha Map from 'ExcessMapEstimator' 

### ISSUE THREAD

**Issue by matthew-w-lundy** [gammapy/gammapy#5247]
**Is your feature request related to a problem? Please describe.**
Relating to #5245, identifying problems relating to acceptance in `ExcessMapEstimator` is difficult because only returns a `FluxMap` which contains no alpha information. 

**Describe the solution you'd like**
I would like the ability to produce an alpha map with the output of  `ExcessMapEstimator.run()`. 

**Describe alternatives you've considered**
You can generate an implied alpha map using the TS map and the On, and scaled Off but this is rather clunky and requires a user defined inverse significance function.  

**Additional context**
Alpha is often a critical tool for assessing issues and uncertainties in significance calculations. Returning this information as a diagnostic immediately highlights potential issues when a user has selected parameters that contain issues (i.e. too small a width in their ring background). It feels clunky to add this information to the 'FluxMap' because you should be able to generate maps and significances where alpha isn't a significant factor in the calculation of the background. It could be just an optional return of 'ExcessMapeEstimator' which is what I currently do.

**Comment by registerrier** [comment]
Thanks @matthew-w-lundy . This would useful indeed. Do you have a prototype/example implementation?
