### ISSUE TITLE
Adapt code style and formatting CI to use precommit.ci 

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#5277]
Currently we rely on pre-commit to run black, isort and flake8 when committing changes to the repo.  The CI performs an independent black and codestyle check. This requires running a specific [black action](https://github.com/gammapy/gammapy/blob/6d5dbc66b87564694d327598d9fa647b883ec5e9/.github/workflows/ci.yml#L5-L12)  and having a [codestyle](https://github.com/gammapy/gammapy/blob/6d5dbc66b87564694d327598d9fa647b883ec5e9/tox.ini#L120-L125) `tox` environment called in the [CI matrix](https://github.com/gammapy/gammapy/blob/6d5dbc66b87564694d327598d9fa647b883ec5e9/.github/workflows/ci.yml#L56-L59).
 
It would be simpler to maintain if the CI could rely on the same [pre-commit-config.yaml](https://github.com/gammapy/gammapy/blob/main/.pre-commit-config.yaml) file. 
This could be done using [pre-commit.ci](https://pre-commit.ci/).

**Comment by MRegeard** [comment]
Thanks @registerrier, I think it is a good idea. At some point @adonath also mentioned using [ruff](https://github.com/astral-sh/ruff). This could be done at the same time.

**Comment by registerrier** [comment]
This is done since #5283 . Closing.
