### ISSUE TITLE
Fit.stat_contour and stat_surface yield incorrect parameter names

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#5291]
**Gammapy version**
1.2, dev and probably older versions too

**Bug description**
When using complex models with models shared among several `SkyModel` in `Models`, the schemes of `Models.unique_parameter_names` and `Parameters.unique_parameters` become inconsistent. This becomes problematic when running `Fit.stat_contours` since the parameter names that are extracted do not correspond to the ones actually tested.
 
**Expected behavior**
The unique parameters names used should be the correct ones.

**To Reproduce**
This needs a complex modeling of dataset to reproduce. I don't have a simple example for now.

**Other information**

**Comment by AtreyeeS** [comment]
Does it work correctly if `models.parameters[xx]` is not passed to `fit.stat_contour` but rather `sky_model.parameters[xx]`?

**Comment by AtreyeeS** [comment]
The decision here is to modify the fitting tutorial (https://github.com/gammapy/gammapy/blob/main/examples/tutorials/api/fitting.py) to always use `model.parameters["par_name"]` instead of going through `datasets.parameters` or `models.parameters`

**Comment by AtreyeeS** [comment]
It will also be nice to add the examples in the docstrings for `fit.stat_profile` , `stat_surface`, `stat_contour` showing the same

**Comment by Astro-Kirsty** [comment]
> The decision here is to modify the fitting tutorial (https://github.com/gammapy/gammapy/blob/main/examples/tutorials/api/fitting.py) to always use `model.parameters["par_name"]` instead of going through `datasets.parameters` or `models.parameters`

We need to wait for the unique parameters issue to be solved potentially #5320

**Comment by Astro-Kirsty** [comment]
@QRemy @AtreyeeS, is there anything more that needs to be done here?

**Comment by QRemy** [comment]
Bug is fixed and documentation is adapted so I think we are done.
