### ISSUE TITLE
gammapy.visualization.plot_distribution does not work with non-array representation of axes

### ISSUE THREAD

**Issue by GerritRo** [gammapy/gammapy#5357]
Running

```
fig, ax = plt.subplots(nrows=1, ncols=1)
gammapy.visualization.plot_distribution(ts_map, ax=ax)
```
results in an error, since gammapy.visualization.plot_distribution expects an array of axes in its current form, which does not fit the description, which explicitly allows singular axes objects and lists of axes objects.

A new implementation solving this issue:

#5356

**Comment by QRemy** [comment]
Resolved by https://github.com/gammapy/gammapy/pull/5356
