### ISSUE TITLE
Keyword argument in `FluxPoints.read` shares name with arbitrary keyword argument.

### ISSUE THREAD

**Issue by cbadams2** [gammapy/gammapy#5358]
In the following code, the keyword argument `format` carries the same name as a variable which can be added to the `kwargs`. 
https://github.com/gammapy/gammapy/blob/2829b45f3a8b8c4885cc8a3d9984e919c171bab5/gammapy/estimators/points/core.py#L174-L227
Unfortunately this means that the user has no control over the `kwargs` value for `format`, which is set to `ascii.ecsv`, and passed to the astropy `Table.Read` function a few lines later. In some cases, this leads (I would argue unnecessarily) to the `UnicodeDecodeError`.

**Comment by registerrier** [comment]
Maybe adding a `table_format` argument can solve the issue?

**Comment by lmohrmann** [comment]
I ran into this issue as well.

@registerrier you mean replacing `**kwargs` with a dict called `table_kwargs`, right?

Another option would be to rename `format` to `fp_format` ("fp" for FluxPoints) or similar.
