### ISSUE TITLE
Unify FITS read classmethods

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#539]
We should unify the FITS read classmethods in Gammapy.

You can browse what we currently have here:
https://github.com/gammapy/gammapy/search?utf8=%E2%9C%93&q=%22def+read%28cls%22&type=Code

This PR is triggered by https://github.com/gammapy/gammapy/pull/537#issuecomment-222380381, where for `SkyMap` @adonath so far has been calling [astropy.io.fits.getdata](http://docs.astropy.org/en/latest/io/fits/api/files.html#getdata) (see [here](https://github.com/gammapy/gammapy/search?utf8=%E2%9C%93&q=getdata) for other places where it's called), while in many other places we've been calling [astropy.io.fits.open](http://docs.astropy.org/en/latest/io/fits/api/files.html#astropy.io.fits.open) and in addition accepted a `hdu` argument that was then used to select the HDU. This is also what others have been doing, e.g. `Table.read` in Astropy or [spectral_cube.SpectralCube.read](http://spectral-cube.readthedocs.io/en/latest/api/spectral_cube.SpectralCube.html#spectral_cube.SpectralCube.read) accept the `hdu` keyword and not the `ext` keyword that `getdata` takes. This is confusing for users if `read` methods behave differently for different classes in Gammapy.

I think I like this API and calling `astropy.io.fits.open` followed by HDU selection best

```
    def read(cls, filename, format=None, hdu=None, **kwargs):
        """Read from FITS file.

        Parameters
        ----------
        filename : str
            The file to read the cube from
        hdu : int or str
            For FITS files, the HDU to read in (can be the ID or name of an
            HDU).
        kwargs : dict
            Passed to :func:`~astropy.io.fits.open`.
        """
```

and then an implementation similar to
https://github.com/radio-astro-tools/spectral-cube/blob/master/spectral_cube/io/fits.py
which mostly does the handling of the `hdu=None` case to make it convenient if there is only one good HDU in the FITS file for this kind of object (e.g. one 2-dim image), and if there are several, uses the first and emits a warning. This could be mostly contained in one or a few helper functions in `gammapy.utils.fits`.

For cases where multiple HDUs `aaa` and `bbb` are needed (like [SkyCube.read](https://gammapy.readthedocs.io/en/latest/api/gammapy.cube.SkyCube.html#gammapy.cube.SkyCube.read) I guess we should add `hdu_aaa` and `hdu_bbb` keyword arguments to `read`?

We also have to make a decision on whether we want to accept the HDU as part of the filename in brackets and implement the [gammapy.utils.fits.get_hdu](https://gammapy.readthedocs.io/en/latest/api/gammapy.utils.fits.get_hdu.html) helper function or remove it. I think this could be convenient for command line tools.

@OlgaVorokh @adonath @joleroi - Thoughts?
(If you don't like the basic plan of calling `astropy.io.fits.open` and adding an `hdu` option, please point out why and ideally propose an alternative.)

**Comment by adonath** [comment]
+1 Looks like a good solution to me.

**Comment by joleroi** [comment]
Question, the docstring of ``spectral_cube`` reads
```
def read_data_fits(input, hdu=None, mode='denywrite', **kwargs):
    """
    Read an array and header from an FITS file.
    Parameters
    ----------
    input : str or compatible `astropy.io.fits` HDU object
        If a string, the filename to read the table from. The
        following `astropy.io.fits` HDU objects can be used as input:
        - :class:`~astropy.io.fits.hdu.table.PrimaryHDU`
        - :class:`~astropy.io.fits.hdu.table.ImageHDU`
        - :class:`~astropy.io.fits.hdu.hdulist.HDUList`
    hdu : int or str, optional
        The HDU to read the table from.
    mode : str
        One of the FITS file reading modes; see `~astropy.io.fits.open`.
        ``denywrite`` is used by default since this prevents the system from
        checking that the entire cube will fit into swap, which can prevent the
        file from being opened at all.
    """
```

so ``input`` can be both a file and an Hdu(list). In your example it looks like you only want a filename (plus a hdu keyword) as allowed input. I think the former, i.e. also accepting a HDU object is better.

**Comment by joleroi** [comment]
2nd Question, in the ``nddata`` class so far I have
https://github.com/gammapy/gammapy/blob/master/gammapy/utils/nddata.py#L122
```
  def read(cls, *args, **kwargs):
        """Read from disk
        Calling astropy I/O interface
        see http://docs.astropy.org/en/stable/io/unified.html
        """
        table = Table.read(*args, **kwargs)
        return cls.from_table(table)
```
This would be compatible with you scheme, right?

**Comment by adonath** [comment]
@joleroi Good point, I actually like the option to pass an `ImageHDU` or `BintableHDU` to the `.read()` method as well, instead of having an additional method `from_hdu()`. It makes a smaller and more intuitive (to me...) API. E.g. `Table.read()` takes HDU objects as well.

**Comment by joleroi** [comment]
How should we deal with the ``write`` method? In some cases e.g. for the effective area it is not clear what the extension name is. One option would be to force the user to give one or more extension names when calling ``write`` but this is somehow really inconvenient.

**Comment by cdeil** [comment]
I just now ran into an issue with this file:
```
$ ftlist $GAMMAPY_EXTRA/datasets/exclusion_masks/tevcat_exclusion.fits H

        Name               Type       Dimensions
        ----               ----       ----------
HDU 1   Primary Array      Null Array                               
HDU 2   EXCLUSION          Image      Int8(3600x1800)               
```
Reading via `SkyImage.read` gives this:
```image
>>> from gammapy.image import SkyImage
>>> filename = '$GAMMAPY_EXTRA/datasets/exclusion_masks/tevcat_exclusion.fits'
>>> image = SkyImage.read(filename)
>>> image.data.shape
(1800, 3600)
>>> image.wcs
WCS Keywords

Number of WCS axes: 2
CTYPE : ''  ''  
CRVAL : 0.0  0.0  
CRPIX : 0.0  0.0  
PC1_1 PC1_2  : 1.0  0.0  
PC2_1 PC2_2  : 0.0  1.0  
CDELT : 1.0  1.0  
NAXIS : 3600  1800
```
It looks like the reading went OK, but really what happened was that the data was read from the `EXCLUSION` HDU and the WCS is from the header of the primary HDU, i.e. invalid. Passing e.g. `hdu='EXCLUSION'` doesn't help.

The cause is that `fits.getdata` and `fits.getheader` are called in `SkyImage.read` and behave differently.

The fix is clear and was already mentioned above: always go via `fits.open` in all Gammapy `read` methods. Then this data / header mismatch can't happen and behaviour is uniform.

I'm making this issue high priority (0.6 milestone) and assigning to myself.

**Comment by cdeil** [comment]
Moving milestone to 0.7 (I'll make the 0.6 release tomorrow)

**Comment by cdeil** [comment]
I think now this is working properly both for the old SkyImage and the new Map.

Example from above with SkyImage:
```
>>> from gammapy.image import SkyImage
>>> filename = '$GAMMAPY_EXTRA/datasets/exclusion_masks/tevcat_exclusion.fits'
>>> image = SkyImage.read(filename)
>>> image.data.shape
(1800, 3600)
>>> image.wcs
WCS Keywords

Number of WCS axes: 2
CTYPE : 'GLON-CAR'  'GLAT-CAR'  
CRVAL : 0.0  0.0  
CRPIX : 1800.5  900.5  
PC1_1 PC1_2  : 1.0  0.0  
PC2_1 PC2_2  : 0.0  1.0  
CDELT : -0.1  0.1  
NAXIS : 3600  1800
```

And with Map:
```
>>> from gammapy.maps import Map
>>> filename = '/Users/deil/code/gammapy-extra/datasets/exclusion_masks/tevcat_exclusion.fits'
>>> m = Map.read(filename)
>>> m.data.shape
(1800, 3600)
>>> m.geom.wcs
WCS Keywords

Number of WCS axes: 2
CTYPE : 'GLON-CAR'  'GLAT-CAR'  
CRVAL : 0.0  0.0  
CRPIX : 1800.5  900.5  
PC1_1 PC1_2  : 1.0  0.0  
PC2_1 PC2_2  : 0.0  1.0  
CDELT : -0.1  0.1  
NAXIS : 3600  1800
```

Closing this issue now.

I'll open a PR with improvements to FITS table I/O (that was discussed a bit above) later today.
