### ISSUE TITLE
EBLAbsorptionNormSpectralModel.read_builtin('finke') --> IORegistryError: Format could not be identified

### ISSUE THREAD

**Issue by BrunoArsioli** [gammapy/gammapy#5410]
**Gammapy version**
Gammapy package: version                : 1.2   
Other packages:
        numpy                  : 1.26.3     
        scipy                  : 1.14.0     
        astropy                : 6.0.1      
        regions                : 0.9        
        click                  : 8.1.7      
        yaml                   : 6.0.1      
        IPython                : 8.21.0     
        jupyterlab             : 4.0.12     
        matplotlib             : 3.9.1      
        pandas                 : 2.2.0      
        healpy                 : 1.17.3     
        iminuit                : 2.28.0     
        sherpa                 : not installed 
        naima                  : not installed 
        emcee                  : not installed 
        corner                 : not installed 
        ray                    : not installed 

**Bug description** 

IORegistryError                           Traceback (most recent call last)
absorption_model = EBLAbsorptionNormSpectralModel.read_builtin('saldana-lopez21')

IORegistryError: Format could not be identified based on the file name or contents, please provide a 'format' argument.
The available formats are:
           Format           Read Write Auto-identify Deprecated
--------------------------- ---- ----- ------------- ----------
                      ascii  Yes   Yes            No           
               ascii.aastex  Yes   Yes            No           .... long list of possible formats.

The same error occurs when trying to use other models: "finke" , "franceschini" , etc.  Only "dominguez" model works. 

At $GAMMAPY_DATA/ebl  folder, I have the files (tables) associated to each model:  frd_abs.fits.gz ("finke"),  ebl_franceschini.fits.gz , ebl_saldana-lopez_2021.fits.gz ,  etc...    

**Expected behavior**
Expected to work, just as it works when setting "dominguez" as the EBL model. 

**To Reproduce**
 
``` import pandas as pd
import numpy as np

from astropy.io import fits
from astropy.table import Table
from astropy.coordinates import SkyCoord
import astropy.units as u
from scipy.spatial import cKDTree

import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm

import os
#set data_path for the EBL models
os.environ["GAMMAPY_DATA"] = "/Users/xxx/.myenv/lib/python3.11/site-packages/gammapy/data"

from gammapy.modeling.models import EBLAbsorptionNormSpectralModel

#Initialize EBL absorption models
#models = ['dominguez', 'franceschini', 'finke','saldana-lopez21','franceschini17']

# Initialize the EBL absorption model with Dominguez et al. (2011) model
absorption_model = EBLAbsorptionNormSpectralModel.read_builtin("finke") ```

**Comment by AtreyeeS** [comment]
I can't reproduce the error @bkhelifi ! Can you check your GAMMAPY-DATA once more?

**Comment by BrunoArsioli** [comment]
Dear @AtreyeeS ! I have started a new env following the "gammapy-1.2-environment.yml" and loaded the datasets with gammapy download datasets, as you suggested; All working now. Thank you for your attention!
