### ISSUE TITLE
`SpectrumDatasetOnOff.plot_fit` shows residuals only within `mask_safe`

### ISSUE THREAD

**Issue by lmohrmann** [gammapy/gammapy#5411]
**Gammapy version**
1.2

**Bug description**
`SpectrumDatasetOnOff.plot_fit` shows the residuals (lower panel in the example plot below) only within the range that enters the fit, i.e. where `mask_safe` is `True`.
![image](https://github.com/user-attachments/assets/2b8e03b1-61b0-4532-a70e-8f468af9133f)

**Expected behavior**
I would expect the residuals between model and data also outside the fit range.

**Comment by bkhelifi** [comment]
This behaviour is not a bug, but intended. As the fit is made only for bins within the `mask_safe`, the model is adjusted only for these bins, and not the others. So the residuals are defined only for these bins, and not outside.

**Comment by lmohrmann** [comment]
I understand that the model is adjusted only withing the `mask_safe`, but I don't see why the residuals would be "defined" only within these bins. The model can be evaluated also outside this range, so what would prevent us from calculating the residuals also there? I would definitively see it as beneficial to be able to compare model and data also outside the `mask_safe`. We might want to display a shaded band for the `mask_safe` range also in the lower panel in that case.

**Comment by bkhelifi** [comment]
This other display could be achieved instead, or in addition. Thanks for the proposal. One will discuss about that into a next dev call

**Comment by adonath** [comment]
Here are the lines in question: https://github.com/gammapy/gammapy/blob/main/gammapy/datasets/map.py#L1229
