### ISSUE TITLE
Sorting events by time with `MapDatasetEventSampler`

### ISSUE THREAD

**Issue by fabiopintore** [gammapy/gammapy#5429]
The list of events generated by `MapDatasetEventSampler` are sorted by the `MC_ID` tag of each target in the simulated model. However, this is not a realistic case as events should be sorted by time.

It can be easily fixed it adding a sorting by time of all the events once they are all sampled in `MapDatasetEventSampler.run`.

**Comment by registerrier** [comment]
Solved by #5433. Closing now.
