### ISSUE TITLE
Gammpy.org issues on mobile phone

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#5442]
On android machine with a chrome browser, https://gammapy.org/ does not deploy correctly.
It is not possible to access the different tabs (Team/ Contribute/Documentation etc).

It works correctly with computers, so I really do not know to solve this.
@stahanna do you have any idea?

**Comment by stahanna** [comment]
Hi AtreyeeS, the easiest way is to enable the desktop mode on your mobile browser, but I guess it is not the solution you're looking for. I'm not sure the site is 100% compatible for mobiles, but I will try to find out if it's possible to fix it easily (the firefox on my mobile not working well either)

**Comment by registerrier** [comment]
Since this connected to the gammapy-webpage repository, let's discuss in https://github.com/gammapy/gammapy-webpage/pull/34 and close this issue here.

**Comment by bkhelifi** [comment]
The fix seems to not be sufficiant...

**Comment by registerrier** [comment]
This should not be discussed in this repository. Please open corresponding issue in gammapy-webpage.
