### ISSUE TITLE
Printing the priors of a parameter

### ISSUE THREAD

**Issue by bkhelifi** [gammapy/gammapy#5456]
When printing the parameters, it seems that the priors are not printed, even not mentioned.
It might be great to add this feature/

**Comment by bkhelifi** [comment]
Hi Atreyee,
I did not find in the tutorials an example giving the printing of a parameter with a prior. And I have misinterpreted the current code of `Parameter` relative to that. This is why I put this issue...
So, I should close it. Thank you

**Comment by AtreyeeS** [comment]
> Hi Atreyee, I did not find in the tutorials an example giving the printing of a parameter with a prior. And I have misinterpreted the current code of `Parameter` relative to that. This is why I put this issue... So, I should close it. Thank you

Added an example in #5459
