### ISSUE TITLE
The `get_mean()` function of the EDispKernel might be wrong 

### ISSUE THREAD

**Issue by tunbehaun273** [gammapy/gammapy#5458]
**Gammapy version**
1.2 (and dev)

**Bug description**
The calculation of the mean energy and following also the energy bias uses `pdf = self.data[idx]` which is not a PDF for the EDispKernel, but rather an array of raw probabilities for reconstructing events in the corresponding ereco bins. I think this method only gives the correct result in case of a spectrum which results in the same number of events in each bin. 
In the general case I think the PDF needs to take into account the different bin sizes, i.e., `pdf = self.data[idx]/np.diff(self.axes["energy"].edges)`, resulting in a true PDF giving dP/dE.

I found that the energy bias computed by the EDispKernel generally predicts a larger bias compared to the calculation based on the simulated events directly. This is explained by the wrong PDF giving too much weight to the higher energy bin, as the log bins increase in size.

**Comment by tunbehaun273** [comment]
And as a feature request: I would compute the mean energy and the energy bias at all true energy centers of the kernel and interpolate this function at the requested true energy value (maybe even cache this function if performance matters). Because right now it behaves like a nearest neighbor interpolation and the bias values stay constant within one true energy bin...

**Comment by tunbehaun273** [comment]
I apologize, the factor `1/np.diff(self.axes["energy"].edges)` which I thought was missing enters in the integration as $d\mu$ again. So the function should indeed return the correct result. 
I just got myself confused as I didn't provide the correctly normalized data to my energy dispersion which ultimately lead to the bias different from the expectation. And only if I included the $d\mu$ factor in the bias calculation, the bias would agree with the expected bias. But instead I didn't add this factor correctly when I provided the raw edisp data...

**Comment by adonath** [comment]
@tunbehaun273 Do you think the documentation needs to be improved (with regards to the normalization)?

**Comment by tunbehaun273** [comment]
@adonath No, I think the documentation is clear on which quantity is required ($dP/d\mu$). For the standard case of linear migra bins this is really hard to mess up ;) But I chose log-migra bins (which are no longer constant in size) and managed to produce a numpy broadcasting mistake that did not throw an error but just divided everything by one number. So that's fully on me...
