### ISSUE TITLE
doc web page appearance

### ISSUE THREAD

**Issue by bkhelifi** [gammapy/gammapy#5506]
**Gammapy version**
dev

**Bug description**
When reducing the width of a browser, the documentation page organization is perturbed. The right column is overlapping with the central column in the center. This is not happening for the documentation of the v1.2

**Other information**
The v1.2 is using Sphinx v4.5, and the dev v7.4.7 with PyPanda Sphinx Theme 0.15.

**Comment by bkhelifi** [comment]
I do not find in the Sphinx ecosystem such issue... If someone sees a report of such issues, please add it here.

**Comment by morcuended** [comment]
For example, this does not happen in the PyData docs (https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/layout.html). The right sidebar collapses. Might it be due to a custom CSS configuration in Gammapy?

**Comment by morcuended** [comment]
This is very likely related to #5196

**Comment by bkhelifi** [comment]
> For example, this does not happen in the PyData docs (https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/layout.html). The right sidebar collapses. Might it be due to a custom CSS configuration in Gammapy?

The css does not (yet) contains new entries compared to the 1.2, which does not mean that the previous css is compatible with the new PyData. But I am not an expert on that...

**Comment by maxnoe** [comment]
The way how to customize the css of the pydata sphinx theme has changed in some releases.

I'd say:

* fix the version to something that works with the current CSS
* Then update, also updating the CSS.

Probably updating the CSS is better done starting from the minimum needed. In general, I would recommend to make the least adjustments possible, i.e. limit changes to the colors for the Gammapy design and not touch layout things to much.

**Comment by bkhelifi** [comment]
I have noticed at least 3 issues:
- this left-side menu issue
- the dark theme issue (removed for the moment : one feature less, that is sad)
- the accordeon issue (a temporary fix has been made, by non-using the current css feature)
