### ISSUE TITLE
Precise into the LC/Flux Points tutorial why and how to adjust the scan values limits

### ISSUE THREAD

**Issue by bkhelifi** [gammapy/gammapy#5512]
**Is your feature request related to a problem? Please describe.**
Nan values can appear from the flux points computations (spectrum or light curves).

**Describe the solution you'd like**
- Explain why and show how to change the limits of the scan values.
- Put a link towards the solution within an HowTo

**Comment by AtreyeeS** [comment]
Hi @bkhelifi ! @Astro-Kirsty added some info here https://docs.gammapy.org/dev/tutorials/api/estimators.html#a-fully-configured-flux-points-estimation
Would it suffice to add a link from the HowTo, or would you prefer more explanations?

**Comment by bkhelifi** [comment]
I missed that! perfect... thanks
Maybe an Howto is just enough. Any thought?

**Comment by QRemy** [comment]
Resolved by #5522
