### ISSUE TITLE
HowTo link to tutorials broken

### ISSUE THREAD

**Issue by Astro-Kirsty** [gammapy/gammapy#5523]
In the dev version when you go to the [HowTo](https://docs.gammapy.org/dev/user-guide/howto.html#how-to) you cannot click on the links to the tutorials. It only makes the dropdown initiate!

**Comment by Astro-Kirsty** [comment]
Not sure how to fix that! Maybe to do with this file
https://github.com/gammapy/gammapy/blob/main/gammapy/utils/docs.py

**Comment by morcuended** [comment]
I think the problem is that the link is inside the collapsible header, so wherever you click on the header, even outside the "Straight to the tutorial" text it will simply trigger the drop-down (because of the `data-bs-toggle="collapse"`) overriding going to the actual link. I'll have a look.

**Comment by Astro-Kirsty** [comment]
I have a temporary solution, but it makes the tutorial link go below:
