### ISSUE TITLE
Docstring of `EnergyDispersion2D` lists wrong parameters

### ISSUE THREAD

**Issue by lmohrmann** [gammapy/gammapy#5530]
**Gammapy version**
1.2, dev

**Bug description**
The docstring of `EnergyDispersion2D` lists the following parameters for its constructor:
```
    Parameters
    ----------
    energy_axis_true : `MapAxis`
        True energy axis.
    migra_axis : `MapAxis`
        Energy migration axis.
    offset_axis : `MapAxis`
        Field of view offset axis.
```
However – presumably because of a change to the `IRF` class? – the constructor does not accept a parameter `energy_axis_true`:
```
EnergyDispersion2D(energy_axis_true=0)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[3], line 1
----> 1 EnergyDispersion2D(energy_axis_true=0)

TypeError: IRF.__init__() got an unexpected keyword argument 'energy_axis_true'
```

So I assume that the docstring of this class should be updated, and possible of other classes in `irf` too.

**Comment by bkhelifi** [comment]
Indeed, the constructor of this class is the one of the `IRF` class:
```
Init signature:
EnergyDispersion2D(
    axes,
    data=0,
    unit='',
    is_pointlike=False,
    fov_alignment=<FoVAlignment.RADEC: 'RADEC'>,
    meta=None,
    interp_kwargs=None,

```
And in addition, there are mandatory axes with the values ["energy_true", "migra", "offset"].

**Comment by QRemy** [comment]
Thanks @lmohrmann 

the docsting for the parameters shoud be something like this

```
    Parameters
    ----------
    axes : list of `MapAxis` or `MapAxes`
        Axes with the following names : 
            * energy_axis_true (True energy)
            * migra_axis ( Energy migration)
            * offset_axis (Field of view offset)
```

and the usage example should also be updated.
