### ISSUE TITLE
Caching Background in `MapDataset`

### ISSUE THREAD

**Issue by StFroese** [gammapy/gammapy#5624]
When calling `MapDataset(). npred_background()` we check if the background parameters have changed, this looks like this:

https://github.com/gammapy/gammapy/blob/b9f0cf82d141969073bfcb919edc7f2e0a54bada/gammapy/datasets/map.py#L798

But `_background_parameters_changed` is a method of `MapDataset` which is not called here, so this always will be true right?

Like this
```python
def test():
    return False
if test:
    print(test())
```
```bash
out: False
```

**Comment by adonath** [comment]
Indeed it looks like there is either a missing `@property` decorator or missing parents around the `self._background_parameters_changed` function.
