### ISSUE TITLE
Add keywords to PHA files header

### ISSUE THREAD

**Issue by registerrier** [gammapy/gammapy#567]
It would be nice to have in the header of the PHA file some informations that can be used without the full observation database.
Some suggestions:
- TSTART  =     54059.963310462 / Start time of the run
- TSTOP   =     54059.9828486848 / Stop time of the run
- TELCODE =                   30 / Run TelCode
- NUM_TELS=                 1234 / Participating telescopes numbers
- ZENITH  =     48.3458693430968 / Mean zenith angle
- OFFSET  =    0.700270799991036 / Run offset
- EFFICIEN=     55.8092027902603 / Run efficiency

**Comment by cdeil** [comment]
If someone does add this, please have a look at the [spec](http://gamma-astro-data-formats.readthedocs.io/en/latest/index.html) concerning names, specifically for [EVENTS](http://gamma-astro-data-formats.readthedocs.io/en/latest/events/events.html) and [observation index](http://gamma-astro-data-formats.readthedocs.io/en/latest/data_storage/obs_index/index.html).

Or put whatever names make sense to you in the pull request, and then I'll review and comment which ones should be adapted to get consistency with other formats.

**Comment by joleroi** [comment]
Duplicate https://github.com/gammapy/gammapy/issues/413
