### ISSUE TITLE
Use NDDataArray in gammapy.irf

### ISSUE THREAD

**Issue by joleroi** [gammapy/gammapy#570]
Gammapy has an `NDDataArray`class that is meant to be used as base for classes in `gammapy.irf`

http://docs.gammapy.org/en/latest/api/gammapy.utils.nddata.NDDataArray.html

see http://docs.gammapy.org/en/latest/api/gammapy.irf.EffectiveAreaTable.html for an example how to subclass `NDDataArray`

In short
- Define axes as class attributes
- Define axis order as list (class level)

Optional
- Add plot methods
- Add `to_table` and `from_table` methods for FITS I/O

**Comment by joleroi** [comment]
to be discussed 
https://github.com/gammapy/gammapy/pull/778#issuecomment-261260028

**Comment by joleroi** [comment]
It probably gives a better API if NDData array is not subclassed but used as attribute in the IRF classes. TODO

**Comment by cdeil** [comment]
I think this was partly done in https://github.com/gammapy/gammapy/pull/832 .

**Comment by adonath** [comment]
The `NDDataArray` is removed and replaced by the general `IRF` class by now.
