### ISSUE TITLE
SkyMap unit handling

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#575]
As noticed by @leajouvin at https://github.com/gammapy/gammapy/pull/549/files/0f834b47d09f623762b77288277eec320aa6e16f#r66772852 , FITS I/O currently doesn't work for SkyMap units.

Example:
```python
>>> import numpy as np
>>> from gammapy.image import SkyMap
>>> map = SkyMap(data=np.zeros((3,2)), unit='cm^-2')
>>> map.write('test.fits', clobber=True)
>>> map2 = SkyMap.read('test.fits')
No valid units found for extension None
>>> map.unit
'cm^-2'
>>> map2.unit
```

@adonath - Is this a simple quick fix, or is fixing this part of a larger change where e.g. `data` and `unit` attributes of `SkyMap` are combined into a `Quantity`?

**Comment by adonath** [comment]
Yes, this seems to be bug, the unit is only written if a WCS system is defined (see https://github.com/gammapy/gammapy/blob/master/gammapy/image/maps.py#L490). Should be easy to fix.

The following works:

```
import numpy as np
from gammapy.image import SkyMap
map = SkyMap.empty(unit='cm-2')
map.write('test.fits', clobber=True)
map2 = SkyMap.read('test.fits', ext=1)
map.unit
```

`ext=1` is necessary, because `ImageHDU.write()` adds an empty `PrimaryHDU`. Maybe this should be handled better.

**Comment by cdeil** [comment]
> ext=1 is necessary, because ImageHDU.write() adds an empty PrimaryHDU. Maybe this should be handled better.

It can be handled either way of course (empty primary or not).
But I'm +1 to not put an empty primary HDU.

You can achieve this by just always using `PrimaryHDU` as far as I know.
I.e. in a SkyMapCollection on write you'd create mutliple `PrimaryHDU` and write them.
But I'm not sure this is true and haven't tested myself.

@adonath - OK if this issue is assigned to you? I think it would take longer to describe to others the solution you want to put and tests instead of just implementing it?
