### ISSUE TITLE
WStat implementation

### ISSUE THREAD

**Issue by joleroi** [gammapy/gammapy#601]
@cdeil @registerrier 

Please consider the following output from https://github.com/gammapy/gammapy/blob/master/dev/sherpa/stats/compare_stats.py
```
Test data
n_on: 6
n_off: 2
alpha: [ 0.2]
n_pred: [ 5.50797903]

Sherpa stat: 0.00140672425562
Sherpa fvec: 0.0375063228752

Gammapy stat: -8.27229562872
Gammapy statsvec: [-8.27229563]

XSPEC stat: [ 0.00140672]
```
These value are computed as follows
* XSPEC : formular on https://heasarc.gsfc.nasa.gov/xanadu/xspec/manual/XSappendixStatistics.html
  setting ``t_s =1, t_b = 1/ alpha``
* Sherpa : calling ``sherapa.stats.WStat``
* gammapy : implemented https://tel.archives-ouvertes.fr/tel-00687872/document , page 141

Apparently the Sherpa implementation is equivalent to what is done in XSPEC under the assumption ``t_s = 1, t_b = alpha``.
The likelihood definition that Mathieu chooses gives different results for a few reasons
* No extra terms added to make the stat behave like chi2
* The fundamental definition of the likelihood is different. You can never get from the XSPEC definiton to what Mathieu has written in this habilitation.

I think the definiton that Mathieu has is correct for HESS. Do you agree and if yes, how to we deal with Sherpa?

**Comment by joleroi** [comment]
After discussion this with @cdeil we might have found a solution. I will add examples to the docs. Let's use these for further discussion

**Comment by joleroi** [comment]
UPDATE
```
Test data
n_on: 13
n_off: 6
alpha: [ 0.2]
n_pred: [ 11.01595805]

Sherpa stat: 0.0483014862267
Sherpa fvec: 0.219775991015

Gammapy mu_bkg: [ 6.07638334]
Gammapy stat: -50.1414954385
Gammapy statsvec: [-50.14149544]
---> with extra terms
Gammapy extra terms: 50.1897969247
Gammapy stat: 0.0483014862267
Gammapy statsvec: [ 0.04830149]

XSPEC mu_bkg (f * t_b): [ 6.07638334]
XSPEC stat: [ 0.04830149]
```

Next I will add a table with corner cases to the docs. I guess then we can use the WStat in gammapy to compare against FitSpectrum, START

**Comment by registerrier** [comment]
Hi Johannes,

 actually the wstat formula and the expression in MdN text are the same, except that in one case you marginalize over the expected number of background event in the ON( wstat) or in the OFF (MdN) dataset. 
 What you have is exactly the difference between the simple likelihood and the 'normalized' one (binned likelihood) after subtracting Non log Non + Noff log Noff - (Non + Noff)

**Comment by joleroi** [comment]
I realized that 30 seconds before your post :smile:

**Comment by cdeil** [comment]
@joleroi - Could you please close the issue or comment what still needs to be done?

(I'll go through the 0.5 issues now, release is tomorrow or Sunday latest.)
