### ISSUE TITLE
Merge fermipy.skymap with gammapy.image

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#608]
@woodmd - As discussed via email, it would be nice if we could merge
https://github.com/fermiPy/fermipy/blob/master/fermipy/skymap.py
with Gammapy.

`fermipy.skymap` depends on these other parts of `fermipy`:

```
import fermipy.utils as utils
import fermipy.wcs_utils as wcs_utils
import fermipy.fits_utils as fits_utils
from fermipy.hpx_utils import make_coadd_hpx, HPX
```

One option would be to start moving the utils over to `gammapy.utils`.

Another would be to review the Fermipy code and replace functionality that's in Astropy by now to have fewer private utils first. And to add tests.

I think that would be my preference. @OlgaVorokh  and I could work in Fermipy a little this week and clean some things up, maybe remove some utils where things exist in Astropy, add some tests, convert docstrings to Numpy / Astropy standard, get familiar with the Fermi code base, especially the HEALPIX 
sky map class.
And then we continue the discussion on this move to Gammapy at least for the HEALPIX sky map class in ~ a week.

@woodmd - OK? Or do you already have a clear picture how this "merging" of sky map classes in Fermipy and Gammapy could work?

**Comment by woodmd** [comment]
For the WCS-based maps the gammapy SkyMap/SkyCube classes could already be used in lieu of the fermipy SkyMap class with fairly minimal modifications so that's probably a good place to start.  

I think the easiest way to get started would be for me to migrate fermipy to the gammapy SkyMap/SkyCube classes and monkey-patch the bits of the interface that are currently missing.  Once that's done we can look at replacing the patched methods with astropy/gammapy equivalents and/or moving the requisite code into gammapy.  I can try to get started on this tomorrow but if you wanted to make any additional PRs for cleanup etc. I can also hold off for a few days.

**Comment by cdeil** [comment]
Give me a day or two to make some changes to code and imports so that I can use and test `fermipy.skymap` with Python 3 and without needing the science tools.

What's your preference for using Gammapy from Fermipy?
Is just importing it an option, i.e. having Gammapy as a dependency?
(Gammapy only has Numpy and Astropy as required dependencies)

Or do we have to find a way to organise the image and utils code in Gammapy that makes it easy for you to copy the files over and bundle them in `fermipy/extern`?
It would probably mean that you have to bundle parts of `gammapy.utils`, `gammapy.image` and `gammapy.cube` and it is significant extra work, so not my preference.
But of course I understand if you don't want to introduce the Gammapy dependency for Fermipy.

**Comment by woodmd** [comment]
I think having gammapy as a dependency of fermipy would be fine.  fermipy already has a pretty heavy set of dependencies (e.g. the STs) so adding gammapy to this list more probably isn't going to make a big difference in terms of ease of installation.

With respect to handling the migration I don't think any reorganization in gammapy should really be necessary.  I haven't really given much thought yet to whether copying shared code into an ``extern`` module is the easiest approach.  As I mentioned we could also just use temporary patches that extend or override gammapy functions and classes but maybe you think this will be too fragile.

**Comment by cdeil** [comment]
Closing this old issue.

@woodmd did this work, introduced [gammapy.maps](http://docs.gammapy.org/dev/maps/index.html) in 2017 and it's in use in Fermipy now.
