### ISSUE TITLE
Fix `Maps` container class constructor

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#61]
The `Maps` container class constructor logic is broken at the moment (doesn't show up on travis-ci for some reason):
https://gist.github.com/cdeil/7869324

It should be re-written, probably use `gammapy.stats.Stats` and have FITS I/O in methods `from_fits` and `to_fits` instead of sub-classing `HDUList`.

**Comment by cdeil** [comment]
@adonath attempted to fix the Maps class in  #463, but came to the conclusion that it should be re-written in a way that doesn't sub-class `HDUList`.

**Comment by cdeil** [comment]
@adonath - I'm assigning this issue to you and to the `PyGamma1` milestone.

I don't remember. Is the old `Maps` class gone already? If yes probably this issue can be closed?
(We probably still want to implement something like `BgMaps` in HAP that's filled by different background methods, i.e. restore part of the functionality of the previous `Maps` class. But this issue without a plan how to implement it doesn't help, right?)

**Comment by adonath** [comment]
Yes the `Maps` class is gone, so I'll close this issue. We can open a separate one for `BgMaps`.
