### ISSUE TITLE
Incorrect result from Sphinx full-text search

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#611]
I noticed that this full-text search result in the Gammapy docs is incorrect:
https://gammapy.readthedocs.io/en/latest/search.html?q=spectrumfit

This class doesn't show up:
https://gammapy.readthedocs.io/en/latest/api/gammapy.spectrum.SpectrumFit.html

@joleroi just wiped Gammapy on RTD earlier today and the build log looks OK:
https://readthedocs.org/projects/gammapy/builds/4166984/

I don't see the issue locally, there the search result is OK.

Not sure what the issue is ... probably some versions are different.
The only thing I see for now is that on RTD Sphinx 1.3.5 is used and locally I have Sphinx 1.4.4.

@bsipocz - Have you seen this issue before or any idea how to identify or fix it?

**Comment by bsipocz** [comment]
@cdeil - It looks like that the search is case sensitive as searching for ``SpectrumFit`` indeed finds the classes:
https://gammapy.readthedocs.io/en/latest/search.html?q=SpectrumFit

I'm not yet sure whether this is a version thing or there is config value on RTD to switch it off to be case insensitive.

**Comment by cdeil** [comment]
But this is working:
https://gammapy.readthedocs.io/en/latest/search.html?q=spectrumobservation
It's weird!?

**Comment by bsipocz** [comment]
Hmmm no clue then.
 Have you tried building locally with the older version? If it works fine with it, too, then maybe it's worth opening an issue with RTD.

**Comment by cdeil** [comment]
Both of these work fine not on RTD:

- https://gammapy.readthedocs.io/en/latest/search.html?q=spectrumfit
- https://gammapy.readthedocs.io/en/latest/search.html?q=spectrumobservation

This is with the latest commit 828a7f5d180d6fd5258cff236ff41d9bdd75b7d0 which shows up as version `v0.5.dev3463`.

RTD still runs on Sphinx 1.3.5, but I did change it to run on Python 3.5 and conda recently.
Not sure when / how this bug got fixed, but it's all good now.

Closing this issue now.

**Comment by cdeil** [comment]
This issue is back.

* Works: https://gammapy.readthedocs.io/en/latest/search.html?q=SkyImage
* Doesn't work: https://gammapy.readthedocs.io/en/latest/search.html?q=skyimage

The second query has a different capitalisation, and with that only the `SkyImageList` class is found, but not the `SkyImage` class.

This looks like some weird Sphinx bug.

First thing to do is update the Sphinx version on RTD and see if the issue goes away.

I'm re-opening this issue, putting it under the 0.6 milestone and assigning to myself.

**Comment by cdeil** [comment]
Looking though the Gammapy search results, it seems that it's sometimes case-sensitive, sometimes case-insensitive.

There is an open Sphinx issue to add support for case-insensitive search: https://github.com/sphinx-doc/sphinx/issues/738#issuecomment-272162580

And there are several open Sphinx issues about search giving wrong results, all with complicated details about which text is searched exactly: https://github.com/sphinx-doc/sphinx/issues/2930 , https://github.com/sphinx-doc/sphinx/issues/2989 , https://github.com/sphinx-doc/sphinx/issues/1918

I'm closing this issue now, because I don't see an action item to improve this at the moment on the  Gammapy or Astropy side. Some pages have local Google search, but I don't think that's easy to set up with Sphinx / ReadTheDocs to work well. And overall search works pretty well at the moment already.
