### ISSUE TITLE
Use Fermi-LAT image for gammapy.image docs

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#619]
The current `gammapy.image` docs aren't very friendly ... they start by saying that we use `ImageHDU` objects for the first example:
https://gammapy.readthedocs.io/en/latest/image/index.html

Here's what I think should be done:

- Use the 2FHL dataset as example
https://github.com/gammapy/gammapy-extra/tree/master/datasets/fermi_2fhl

- Write a script in that folder that produces a count and background image (and maybe others like significance) e.g. using code similar to [here](http://nbviewer.jupyter.org/github/gammapy/gammapy-extra/blob/master/notebooks/hess_image_analysis.ipynb). Probably we want two or three regions, e.g. Galactic center similar to [here](http://fermi-hero.readthedocs.io/en/latest/galactic_center/science_tool_images.html), and a smaller one like the vela region we have here: https://github.com/gammapy/gammapy-extra/tree/master/datasets/vela_region

(the https://github.com/gammapy/gammapy-extra/tree/master/datasets/vela_region and https://github.com/gammapy/gammapy-extra/tree/master/datasets/fermi_survey example datasets can then be removed once this 2FHL dataset is complete)

- Replace the Poisson test image with this Fermi image in the docs here:
https://gammapy.readthedocs.io/en/latest/image/skymaps.html
 and here: https://gammapy.readthedocs.io/en/latest/image/index.html#getting-started

I think this is high-priority to have for the 0.5 release and poster that we'll hang on Monday.

@adonath - Do you have time to work on this in the next two days or should I do it?

**Comment by adonath** [comment]
Here is a first version of the script:

https://github.com/gammapy/gammapy-extra/blob/master/datasets/fermi_2fhl/fermi_skyimages.py

I already created a sample dataset for the Galactic Center and the Vela region. From an aesthetical point of view, I think the smoothed counts image looks best so far.

**Comment by adonath** [comment]
Mostly addressed in #658, but could be improved further:

* Put images in  `https://github.com/gammapy/gammapy-extra/tree/master/figures` and link to it from the docs, so that they appear on RTD as well.
* Generally extend the docs with more examples and nice images. 

@cdeil Is this issue resolved with #658, or do you request anything else?

**Comment by cdeil** [comment]
I've moved the pre-generated PNG images we had in `gammapy/docs` to `gammapy-extra/figures`: https://github.com/gammapy/gammapy-extra/tree/master/figures

I'll make a PR shortly removing the PNG images from the `gammapy` repo and pointing to `gammapy-extra`.

Closing this issue now.
