### ISSUE TITLE
Create example dataset to be used for docs/poster

### ISSUE THREAD

**Issue by joleroi** [gammapy/gammapy#621]
So far we're using [this](https://github.com/gammapy/gammapy-extra/tree/master/datasets/hess-crab4-hd-hap-prod2) simulated crab dataset. It has known issues and gives wrong results.

Instead we would like to simulate a hess/fermi crab dataset. Let's start with H.E.S.S.

* Use the [Abramowski](https://github.com/gammapy/gammapy/blob/9c566e4935b5e600f795afe8079094a9fba7666a/gammapy/irf/effective_area.py#L345) effective area parametrization
* Assume gaussian energy dispersion (20 % resolution)
* Simulate counts spectrum
* Simulate background spectrum
* Fit

TODO
* [x] Fix [from_gauss](https://github.com/gammapy/gammapy/blob/9c566e4935b5e600f795afe8079094a9fba7666a/gammapy/irf/energy_dispersion.py#L108)
* [x] Enable fitting ``~gammapy.spectrum.models``, i.e. to sherpa method
* [x] Implement ``ECPL``, and ``BrokenPL``
* [x] Refactor simulation tools

cc @cdeil @registerrier

**Comment by joleroi** [comment]
That's all I can think off at the moment. If someone want to help he/she could start by implementing the ``ECPL`` and ``BrokenPL``.

https://github.com/gammapy/gammapy/blob/9c566e4935b5e600f795afe8079094a9fba7666a/gammapy/spectrum/models.py#L67

We also need some numeric integration method, to get ``npred`` (for the PL it's done analytically)

**Comment by cdeil** [comment]
@joleroi - I can do the `ECPL` and `BPL` today (unless someone else volunteers).

Maybe you start the script to simulate the ARF and RMF, and put a README, the script and generated files in a `simulated_spectrum` sub-folder here?
https://github.com/gammapy/gammapy-extra/tree/master/datasets

**Comment by joleroi** [comment]
That's the status
https://github.com/gammapy/gammapy-extra/tree/master/datasets/hess_simulated_pha
![observation](https://cloud.githubusercontent.com/assets/11678435/16710699/702b5e0e-4638-11e6-983c-00b3b8a81b5f.png)

![fit](https://cloud.githubusercontent.com/assets/11678435/16710700/7c86e1d2-4638-11e6-99c1-691f8fd20791.png)

@cdeil  What should be improved to put this as an example on the gammapy poster (or is it too late anyway?)

**Comment by cdeil** [comment]
@joleroi - Thank you!

I didn't have time yesterday and don't have time today to make the poster.
I'll do it Monday morning.

If you have time to add something, a plot of the fitted global model (with butterfly?) would be the most important plot at the end of the spectral example.

**Comment by cdeil** [comment]
Also, this is the first example we have of how to simulate a spectrum.
It should be linked to or include in the docs.
Maybe from here?
https://gammapy.readthedocs.io/en/latest/spectrum/index.html

**Comment by joleroi** [comment]
> If you have time to add something, a plot of the fitted global model (with butterfly?) would be the most important plot at the end of the spectral example.

Done

> Also, this is the first example we have of how to simulate a spectrum.
It should be linked to or include in the docs.

I would like to wait until this code is properly added to a gammapy ``SimulateObs`` class or so. Also the model handling must be improved before I would show this to anyone. (InputModel is plotted as ``SpectrumFitResult`` at the moment). The plots at the end won't change though.

I won't have much time today to improve this. But you can definitely use the plots. In case you want to change something - you need to merge https://github.com/gammapy/gammapy/pull/625 before the ``simulate.py`` script works for you.

![model_fit](https://cloud.githubusercontent.com/assets/11678435/16712911/6b646f92-4696-11e6-84f8-41b321ffdc41.png)

**Comment by joleroi** [comment]
There is a tutorial how to simulate spectra
http://docs.gammapy.org/en/latest/spectrum/simulation.html
Which explains what was discussed in this issue.
