### ISSUE TITLE
ObservationGroupAxis array or quantity

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#626]
Bug report by @registerrier on Slack.
Posting it here as a Github issue so that it doesn't get forgotten.

```
from astropy.coordinates import Angle
from gammapy.data import ObservationGroups, ObservationGroupAxis
# ObservationGroupAxis seems to implicitly require Quantity arrays. e.g.:
# define binning in cos zenith angle
zen = Angle(np.arccos(np.arange(1.0,0.2,-0.1)),'rad')
print(zen.deg)

# define binning in efficiency
eff = np.arange(0.4,1.3,0.1)    # muon efficieny bins

# Create observation group
obs_group = ObservationGroups([ObservationGroupAxis('ZEN_PNT',zen.deg,fmt='edges'), 
                              ObservationGroupAxis('MUONEFF',eff,fmt='edges')])

# Apply the grouping scheme to the current observation table
tab_group = obs_group.apply(datastore.obs_table)

obs_group.info_group(4)

fails with the error message:
AttributeError: 'numpy.ndarray' object has no attribute ‘unit'

(line 302 in obsgroup.py)

the doc says: The axis parameters should be either dimensionless or castable
   into `~astropy.units.Quantity` objects. 

A numpy array does not qualify?
```

**Comment by joleroi** [comment]
I usually solve this by passing input in ``__init__`` though the Quantity constructor
```
In [4]: test = np.arange(10)

In [5]: import astropy.units as u

In [6]: u.Quantity(test)
Out[6]: <Quantity [ 0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]>
```

Then calling ``Quantity.value`` always works

**Comment by cdeil** [comment]
@leajouvin @registerrier @adonath @dcfidalgo  - I'd like to discuss the obs group code in Gammapy tomorrow.

We currently have a lot of code for this:
- https://github.com/gammapy/gammapy/blob/master/gammapy/data/obs_group.py
- https://github.com/gammapy/gammapy/blob/master/gammapy/data/tests/test_obs_group.py
- http://docs.gammapy.org/dev/data/obs_group.html

I think very few people (maybe @leajouvin or @registerrier ?) are using this, and this bug has been open since 2016.  The only caller within Gammapy was the code to group off runs and make a background model for each. So https://github.com/gammapy/gammapy/issues/1516 is very much related. We haven't started to use observation `GROUP_ID` in other code, like e.g. the 1D or 3D analysis yet.

My proposal would be to delete the `ObservationGroupAxis` and `ObservationGroups` classes, and to replace the docs page with an example how to do this with ~ 10 lines of Numpy:
https://gist.github.com/cdeil/eb1659c724e518eb68c653b53814fa1a

My thinking is that we should move as quickly as possible towards a "clean core" and v1.0 for Gammapy by ~ October 2018, and that means that only things should remain that we want to teach users and maintain for the next years. For me, `ObservationGroupAxis` and `ObservationGroups` don't quite make the cut here, I think we should teach users Numpy and Astropy Table instead and avoid code in Gammapy where we can.

Let's discuss tomorrow ...

**Comment by cdeil** [comment]
Fixed by removing this code. See #1575 .
