### ISSUE TITLE
Gammapy code organisation

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#636]
This is a first attempt at a diagram to illustrate Gammapy code organisation.

![gammapy-organisation](https://cloud.githubusercontent.com/assets/852409/16940539/f53243d4-4d8a-11e6-8da0-0b1b1ecd61b2.png)

After some discussion / improvements / code re-organisation I plan to add it to the Gammapy docs and the paper.

At the moment it only shows which sub-packages are lower or higher level. The idea is that a given package is only allowed to import from lower-level packages to avoid circular imports. There are some exceptions, like e.g. gammapy.data does import higher-level classes in factory functions using delayed imports. I'm not sure if it's desirable / possible to try to avoid this completely.
One more aspect: e.g. for spectral analysis we probably want to sometimes extract a spectrum out of a diffuse spectral model cube (e.g. for Fermi-LAT), i.e. functions from lower-level modules can take objects from higher-level package as inputs.

Some ideas to make the diagram better:
- Add public sub-sub packages, like `gammapy.spectrum.models` or all packages in `gammapy.utils` to the diagram.
- We could try and add a one-line description for each sub-package, although I don't think this would work well (too much text).
- We could try to draw connecting lines for all dependencies that are actually there (e.g. `astro` doesn't depend on most of the lower-level sub-packages. I don't think this will work well ... too many lines.

There's a lot of work / cleanup to do. I'll continue with this in a few weeks.

I have one concrete question: OK to dissolve [gammapy.morphology](https://gammapy.readthedocs.io/en/latest/morphology/index.html), and introducing `gammapy.image.models`?

**Comment by adonath** [comment]
:+1: to dissolve `gammapy.morphology` and introduce `gammapy.image.models`. I think this makes the structure of gammapy more consistent.

**Comment by joleroi** [comment]
> We could try and add a one-line description for each sub-package

:-1:

**Comment by cdeil** [comment]
This needs a PIG, and probably this should be a priority for v0.9. This could go in steps (e.g. add or remove one sub-package at a time) or if someone has the time, a complete (1 page) proposal for what code organisation in v0.9 or 1.0 could be that would be good to have.

cc @registerrier @adonath

**Comment by cdeil** [comment]
I think we should close this old issue, and start a PIG on this topic of Gammapy code organisation for v1.0.

We could start with a diagram like the one above that documents the sub-packages we have, and roughly their interrelation. And then we discuss a bit opportunities to re-organise in a better way, or also ask for help and feedback by experienced people that have written gamma-ray or other science analysis packages before.

Nothing might come of it, or maybe we do merge the content of `gammapy.detect`, `gammapy.image`, or dissolve `gammapy.background` and move that code in the other sub-packages, or ... ? And there might be some modules in `gammapy.utils` that we can get rid of, or hide from the API docs because we consider them internal helpers that no-one should import outside Gammapy? I think we should give it a try and would be happy to start a PIG PR like I did for a few other topics recently.

@adonath @registerrier - Thoughts?

**Comment by adonath** [comment]
@cdeil Fine by me...I agree this is better discussed in a PIG.

**Comment by registerrier** [comment]
+1

**Comment by cdeil** [comment]
@adonath @registerrier - Is this what we have as of now?

Probably the PIG should contain two Figures: what we have now, and then the proposal what to put?

![IMG_4929](https://user-images.githubusercontent.com/852409/60668721-ec528b80-9e6c-11e9-8913-0174a53676b4.jpg)

**Comment by cdeil** [comment]
I made a diagram: https://drive.google.com/file/d/1OrptsiCpM4CjlG7cGruEeHtdZ3Kj_dXO/view
Now starting PIG 15, then will close this issue.

**Comment by cdeil** [comment]
Discussion will continue in #2274
