### ISSUE TITLE
Adapt Fermi ST / ctools spectral model names / parameters?

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#669]
There's been an effort in ctools to clean up the spectral model and parameter names.
As far as I know there's a plan to adapt the Fermi ST to have the exact same models.
(see https://github.com/open-gamma-ray-astro/gamma-astro-data-formats/issues/41)

My suggestion would be that we simply adapt the exact same model / parameter names (even if we think for some a better name could be chosen)?

I can give arguments why I think that is useful, but maybe this isn't even controversial and just needs doing, not discussing?

Here's what they have:
http://cta.irap.omp.eu/ctools-devel/users/user_manual/getting_started/models.html#spectral-model-components
http://cta.irap.omp.eu/gammalib-devel/doxygen/classGModelSpectral.html

Here's what we currently have:
https://gammapy.readthedocs.io/en/latest/spectrum/index.html#module-gammapy.spectrum.models

@joleroi @adonath - Thoughts?

**Comment by cdeil** [comment]
Moving milestone to 0.7 (I'll make the 0.6 release tomorrow)

**Comment by adonath** [comment]
By now we implement a uniform naming scheme for our models, so I think we should not re-consider any re-naming for the next time...
