### ISSUE TITLE
Support energy-dependent alpha in SpectrumFit

### ISSUE THREAD

**Issue by joleroi** [gammapy/gammapy#682]
We need this now, because exported HESS spectrum objects are stacked and thus have an energy dependent alpha. This should use the BACKSCAL column in the FITS data extension. It can always be used even in the case of constant alpha.

https://heasarc.gsfc.nasa.gov/docs/heasarc/ofwg/docs/spectra/ogip_92_007/node7.html

**Comment by cdeil** [comment]
This was (partly?) implemented in #683 and might be related to https://github.com/sherpa/sherpa/pull/249, right?

@joleroi - Should this remain in the 0.5 milestone (due in a "few days") or move to 0.6?

**Comment by joleroi** [comment]
Sorry, I forgot about this issue.

It's solved by #683 but relies on sherpa HEAD version at the moment. This will change with the next sherpa release.
