### ISSUE TITLE
Save containment correction in SpectrumObservation as AREASCAL column

### ISSUE THREAD

**Issue by joleroi** [gammapy/gammapy#684]
At the moment the containment correction is directly applied to the effective area
https://github.com/gammapy/gammapy/blob/master/gammapy/spectrum/extract.py#L222

I think it would be nicer to save this as AREASCAL column on the FITS file, so it's more transparent which correction was applied.

see https://heasarc.gsfc.nasa.gov/docs/heasarc/ofwg/docs/spectra/ogip_92_007/node7.html

**Comment by cdeil** [comment]
@joleroi - Assigning to you. If you don't have time, please move to the 0.7 milestone, and unassign yourself if you don't want to do this at all.

**Comment by joleroi** [comment]
Done in https://github.com/gammapy/gammapy/pull/972. Please leave open, the AREASCAL is not taken into account in the fit yet.

**Comment by cdeil** [comment]
Moving milestone to 0.7 (I'll make the 0.6 release tomorrow)

**Comment by joleroi** [comment]
This must go in otherwise no containment correction is possible
