### ISSUE TITLE
Spectrum extraction tests write to gammapy-extra

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#688]
After I run the Gammapy tests locally the following files in gammapy-extra are modified:

```
$ cd $GAMMAPY_EXTRA
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

    modified:   datasets/hess-crab4_pha/arf_obs23523.fits
    modified:   datasets/hess-crab4_pha/arf_obs23592.fits
    modified:   datasets/hess-crab4_pha/bkg_obs23523.fits
    modified:   datasets/hess-crab4_pha/bkg_obs23592.fits
    modified:   datasets/hess-crab4_pha/pha_obs23523.fits
    modified:   datasets/hess-crab4_pha/pha_obs23592.fits
    modified:   datasets/hess-crab4_pha/rmf_obs23523.fits
    modified:   datasets/hess-crab4_pha/rmf_obs23592.fits
...
```

This is annoying and should be changed.
Running the tests should only read files from gammapy-extra, never write files there.

The culprit is this test:

```
python setup.py test -t gammapy/spectrum/tests/test_extract.py
```

and this code:
https://github.com/gammapy/gammapy/blob/master/gammapy/spectrum/tests/test_extract.py#L74

@joleroi - Can you please fix this?

Any idea how to change the test code structure so that producing the test dataset is easily possible independently of running the test?
Maybe a utility function or class in that test file that can be imported and run with an option or method to generate the reference test data, and also call it from the test?
I'm not sure ... if you want, come by and we can discuss and try to find a good solution.

**Comment by joleroi** [comment]
> This is annoying and should be changed.

I don't understand - please elaborate. For me it's more annoying to update the test data every time something changes in the spectrum extraction code.

**Comment by cdeil** [comment]
Everytime I (or other Gammapy devs) work on `gammapy-extra`, I see these changes when I type `git status` and wonder what changed, i.e. waste time.

Also, having the test data generation mixed up with test running is confusing / hard to maintain.

I know it's difficult to structure the test dataset generation and test running code well without code duplication and so that it's "obvious" how to find the code that updates the dataset for a given test. Let's discuss offline later today how to improve here.

**Comment by joleroi** [comment]
@cdeil 

I updated the files in ``gammapy-extra`` manually and all fit results changed. It is now impossible to trace this back because the person who changed the code writing the OGIP files did not update the file in ``gammapy-extra`` and didn't notice the change.

Any idea how to avoid this in the future?

**Comment by cdeil** [comment]
@joleroi - Can you please come by my office tomorrow to discuss and find a good solution here?

**Comment by cdeil** [comment]
Thanks for finishing this up!

> Any idea how to avoid this in the future?

I don't think I fully understand why this went unnoticed. Basically that test wasn't set up in a good way an it is possible to change it so that it fails when a bug is introduced in the code, or the reference files change, no? And linking versions of code and test data is key.
This and more stable reference test datasets should make things better in the future, but a lot of work is needed to get there.
