### ISSUE TITLE
Add SkyImage.smooth method

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#694]
I think we should add a [SkyImage](https://gammapy.readthedocs.io/en/latest/api/gammapy.image.SkyImage.html) convenience method that's identical to [DS9 smooth](http://ds9.si.edu/doc/ref/how.html#Smoothing).

```
SkyImage.smooth(type={gauss,tophat,boxcar}, radius={1 pix by default}):
   # Apply the smoothing to self.data and return new smoothed SkyImage
```

These standalone functions should also be changed into SkyImage methods:
- https://gammapy.readthedocs.io/en/latest/api/gammapy.image.disk_correlate.html
- https://gammapy.readthedocs.io/en/latest/api/gammapy.image.disk_correlate.html
  and we should probably add a general `SkyImage.convolve` method that takes a kernel numpy array.

But for interactive work having the `ds9` smooth available would be worthwhile also (because people know and like it), and also gauss can be implemented as a special fast case by calling [scipy.ndimage.gaussian_filter](http://docs.scipy.org/doc/scipy-0.16.1/reference/generated/scipy.ndimage.filters.gaussian_filter.html) and "boxcar" by calling [scipy.ndimage.uniform_filter](http://docs.scipy.org/doc/scipy-0.16.1/reference/generated/scipy.ndimage.filters.uniform_filter.html).
So as far as I'm concerned, any of these methods / changes be be done independency (and separate small pull requests are better anyways).

Anyone interested in implementing this?

**Comment by adonath** [comment]
`SkyImage.convolve()` has been added in #713. But still it might be nice to add the `SkyImage.smooth()` method to provide more convenience to the user with, e.g. allow specifying the smoothing radius in world coordinates as well with `radius = 0.2 * u.deg` etc.
