### ISSUE TITLE
Add code quality to Gammapy CI

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#696]
There's several nice and free code quality tools with Github integration:
https://github.com/integrations/feature/code-quality

We currently have https://landscape.io/ running:
https://landscape.io/github/gammapy/gammapy

Looks like I set this up in 2014 (see #125 and 1dcdb4f8d35f8b75916d4371d49b4888285559e9),
but by now the `landscape.yml` file is no longer in the Gammapy repo, and anyways, it should be called `.landscape.yml` (see https://landscape.io/github/gammapy/gammapy/565/config)

It should be added back and configured a bit, at a minimum the `ignore-paths` should be set to include `astropy-helpers` and `gammapy/extern`.

These also might be worth checking out:
- https://github.com/integrations/code-climate
- https://github.com/integrations/quantifiedcode

But I'm not sure if they are any better than `landscape`.
The nice thing about `landscape` is that it runs [prospector](https://docs.landscape.io/prospector.html), a tool one can pip-install and also run locally while working on code quality issues.

**Comment by cdeil** [comment]
I noticed that landscape isn't working:
https://landscape.io/github/gammapy/gammapy/1682
I've sent an email just now.

I guess we could also try out these that are free for open source:
- https://lgtm.com/
- https://www.codacy.com/

From a brief look https://codeclimate.com/ isn't free and https://www.quantifiedcode.com/ is dead.

**Comment by cdeil** [comment]
@adonath or @Bultako or anyone - Can you see this page?
https://app.codacy.com/app/cdeil/gammapy

I only looked for 1 min so far, there seem to be a few useful things and a lot of irrelevant stuff.
So this will need some configuration.

**Comment by cdeil** [comment]
Just to point out one example of a somewhat useful find:
https://app.codacy.com/app/cdeil/gammapy/file/22113171284/issues/source#l470
We should do string processing instead of `eval` - otherwise if people use Gammapy in a web app that allows FITS file upload some day this `eval` will give hackers arbitrary code execution.

Like I said, I only looked very briefly at this so far, haven't used codacy before.

**Comment by cdeil** [comment]
I've also activated LGTM to try it out.

@adonath or @Bultako - Can you see this?
https://lgtm.com/projects/g/gammapy/gammapy/
Code analysis still seems to be in progress...

For codacy I've added a badge to the README, so that it's easy to find for devs already, and it seems to be integrated with pull requests alreday, giving a status message on each. ctapipe uses it, so maybe it's a good option.

@kosack or anyone - if you know how to configure codacy to give better results, please let me know or just to ahead and do it.

**Comment by Bultako** [comment]
👍 
I find the `codacy` checks in PRs quite useful.  Do they block merging? I'll try to fix all issues thrown by `codacy` for open and future PRs. As for the ones reported in https://app.codacy.com/app/cdeil/gammapy we could slowly solve the most prominent, there's lot of stuff..  LGTM and Scrutinizer may help as a complement, but I wonder if we risk to spend too much effort on this. Surely, code quality is better achieved with a CI.

**Comment by cdeil** [comment]
I would suggest we try those for a week or two, maybe even up to the coding sprint, and then discuss a bit and decide which ones to activate and how to configure them from then on. E.g. it's not clear to me if automatic PR review is something we want (since many Gammapy contributors are not professional coders, just astronomers that make their first open source commit and never heard of static code analysis and PEP8 and such things), or if those code quality services / tools are just what one or a few core devs use, to scan and clean up a bit when they have time.
E.g. in https://lgtm.com/projects/g/gammapy/gammapy/alerts/?mode=list there's current some good "alerts" how they call it, like a few missing "raise" or "assert" statements.

**Comment by cdeil** [comment]
Our coverage report on coveralls.io is still working, but that site seems to be unmaintained or not well maintained, e.g. sorting and searching is broken at the moment:

- https://github.com/lemurheavy/coveralls-public/issues/1355
- https://github.com/lemurheavy/coveralls-public/issues/1365

I'm considering switching somewhere else, but not sure where.
https://codecov.io/ is an option used by Astropy and ctapipe, although it looks like they don't have it configured properly, at least I can't see the line coverage actually. https://github.com/astropy/astropy/issues/9540

**Comment by cdeil** [comment]
I've added codecov.io for Gammapy in https://twitter.com/codecov/status/1191779759706918912 and  https://twitter.com/codecov/status/1191779759706918912
It should work, but will likely take another 30 min or so to upload a first coverage report.

I already removed coveralls.io in https://twitter.com/codecov/status/1191779759706918912

And also landscape.io doesn't seem to exist any more, removed in https://twitter.com/codecov/status/1191779759706918912

**Comment by cdeil** [comment]
codecov seems to run: https://travis-ci.org/gammapy/gammapy/jobs/608239285#L3186
Small config update: ad583962c
At https://codecov.io/gh/gammapy/gammapy I'm still getting errors, no report yet.
I'll just check back tomorrow, I think it should come.

**Comment by cdeil** [comment]
The current "Unable to find report content in the storage archive." error is a known issue on the codecov.io side that they are working on fixing: https://community.codecov.io/t/open-issue-investigation-report-stuck-in-processing-unable-to-find-report-content-in-storage-archive/670

**Comment by cdeil** [comment]
Everything looks good now concerning code coverage: https://codecov.io/gh/gammapy/gammapy
I love the sunburst, it allows very quick browsing and drilling down to find the badly covered files.

We now get a report on every pull request, summarising how code coverage changed: https://github.com/gammapy/gammapy/pull/2519#issuecomment-550412571
I could turn that off, but IMO it's very useful, so I'll keep it on for now.

I'm closing this old issue now.

We have code coverage reports at codecov, and we have static code analysis and quality reports at LGTM and Codacy. They are easy to find via the README: https://github.com/gammapy/gammapy#status-shields

If someone has suggestions to improve something concerning tooling, please re-open or open a new issue. Of course, improving code coverage and quality will be a continued task, it's not "done", this issue was just about setting up good tooling.
