### ISSUE TITLE
Add flux point upper limit method

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#698]
Thanks to @joleroi Gammapy has recently grown some code to compute flux points for 1-dim spectra, using a method that is common in TeV astronomy (see example [here](http://nbviewer.jupyter.org/github/gammapy/gammapy-extra/blob/master/notebooks/hess_spectrum_analysis.ipynb#Compute-Flux-Points)).

Now how should we compute upper limits?

This issue is to discuss which method(s) we should add and how to proceed:
- Fermipy has confidence limit methods in [fermipy/castro.py](https://github.com/fermiPy/fermipy/blob/master/fermipy/castro.py) and likelihood profiles in [this format](http://gamma-astro-data-formats.readthedocs.io/en/latest/results/binned_likelihoods/index.html#likelihood-sed).
  I'm not sure what method that is?
- In the HESS software the ROLKE method is the default. I think I managed to implement it [here](https://gist.github.com/cdeil/6db65c2705cab30833ea86b81906ba91) or in some other notebook many years ago, but it's not well-written, debugged and probably slow.
- I think I also have an IPython notebook somewhere from years ago where I use MINOS to compute the limits for the on-off stats likelihood and get the same results as ROLKE. But I can't find that now and I'm not sure.
- Anyways, I think maybe we can just call [iminuit.Minuit.minos](http://iminuit.readthedocs.io/en/latest/api.html#iminuit.Minuit.minos) or Sherpa conf on the likelihood?

@joleroi and I want to take some time next week and implement this, because we need it.

@woodmd - Do you think it might make sense to move Castro to Gammapy long-term? Or is there something specific to Fermi / ST? Can you comment on the method implemented there? Is there a standard in Fermi how ULs are computed e.g. in the catalogs or do we need different methods?

@dlennarz - You've implemented [Feldman Cousins limits](https://gammapy.readthedocs.io/en/latest/stats/feldman_cousins.html) in Gammapy and might have a Python Rolke implementation at hand?

@registerrier, @jjlk  - Thoughts or help with this?

**Comment by dlennarz** [comment]
Sorry, I never implemented Rolke in python.

**Comment by woodmd** [comment]
The method used in fermipy is the "delta-loglikelihood" method which is also the commonly accepted practice for most LAT analyses (although some people also use Bayesian methods).  This method involves evaluating a profile likelihood Lp(x) = max_y L(x;y) for the parameter of interest x and nuisance parameters y.  The UL is defined to be the point at which the profile likelihood changes by some value relative to the maximum (2.71/2 for 95% UL).  When there is a physical boundary on a parameter (such as a normalization) the profile likelihood is always restricted to the physical region such that for a negative MLE the maximum is evaluated at zero.  I think the Rolke method is basically just a special case of the delta-loglikelihood method for ON/OFF analysis.  I believe the delta-loglikelihood method is also the method used internally by MINOS.

Regarding the Castro classes, there is nothing Fermi specific about them so it probably would make sense to migrate them to gammapy long-term.  Before doing this we should probably work on the skymap migration first.

**Comment by cdeil** [comment]
@woodmd - Thanks for the infos.

> Regarding the Castro classes, there is nothing Fermi specific about them so it probably would make sense to migrate them to gammapy long-term. Before doing this we should probably work on the skymap migration first.

Agreed.

Just FYI: sorry I dropped the ball on integrating the HEALPIX classes from Fermipy into Gammapy so far. I just didn't have the time yet, and I want to get the HEALPIX we need into Astropy core first so that it's available in the next stable release (see http://healpix.readthedocs.io/en/latest/about.html).
Once that's done we could even see discuss if the `HPX` class that's the equivalent of `WCS` should go there, too.

And now the flux points and likelihood profiles are higher priority for the work @joleroi and I are doing in HESS, we need it working for us ASAP.

**Comment by adonath** [comment]
I added the flux point upper limit computation some time ago to Gammapy. The `FluxPointEstimator` class now has two methods, [compute_flux_point_ul](http://docs.gammapy.org/en/latest/api/gammapy.spectrum.FluxPointEstimator.html#gammapy.spectrum.FluxPointEstimator.compute_flux_point_ul) and [compute_flux_point_sqrt_ts](http://docs.gammapy.org/en/latest/api/gammapy.spectrum.FluxPointEstimator.html#gammapy.spectrum.FluxPointEstimator.compute_flux_point_sqrt_ts), which basically implement the method described by @woodmd. But I guess at some point we should discuss and document the details of the method, such as:

* How to compute the delta TS for a given CL. @woodmd Suggested 2.71/2 for 95% UL, while I used 4/2 for 95% UL. 
* What to use as the null likelihood. While @woodmd suggested to clip at physical parameter boundaries, I think one should always take the value at the minimum (i.e. even allow negative amplitudes). 

I think those points listed above do not really make an important difference, but we should probably still decide and document what we implemented for transparency. So I keep the issue open as a reminder.

I do not think there is a real need for other methods such as TRolke or Feldman-Cousins.

**Comment by cdeil** [comment]
@adonath - Just FYI: next week Thursday afternoon would be a good chance to discuss / decide Gammapy analysis issues. So if you have time and there's anything you'd like to discuss, then please add a bullet with the topic or link to the issue if it exists to the agenda at https://github.com/gammapy/gammapy-meetings/blob/master/2017-09_Heidelberg.md#remote-connection

**Comment by adonath** [comment]
@cdeil Thanks for the hint, but I think for the issues I mentioned above, it probably does not help to discuss those in a larger group (except if we have statistics expert...). Everyone has half an opinion (me included) on those statistical questions, but no one really knows it for sure.  I remember @joleroi send me a link to the following book:

http://www.sherrytowers.com/cowan_statistical_data_analysis.pdf

The relevant section are 9.7 and 9.8. Maybe I (or anyone else who is interested...) can find some time to read those sections in detail and make a suggestion here what to actually implement . We then just give a reference to the book...

**Comment by cdeil** [comment]
> Everyone has half an opinion (me included) on those statistical questions, but no one really knows it for sure.

🤣 

Well, yes and no.

Years ago I was an expert on this and read several papers on Poisson stats upper limits. Yes, no one really knows, there's a ton of methods / approaches to deal with the hard physical limit. I agree with your statement earlier that we don't need more methods from Rolke and Cousins or others (although if someone is motivated, they can add).

But there's the simple / unambiguous high-stats, Gaussian error case, where one can validate by checking coverage. I think that's the main / only concrete action item here? To make a Jupyter notebook with a small simulation for a single flux point that shows that UL coverage is OK in one or a few cases with Gammapy?

**Comment by cdeil** [comment]
In HESS an effort is starting to improve code / methods for various upper limit computations (see [HESS Confluence page](https://hess-confluence.desy.de/confluence/pages/viewpage.action?pageId=34382354). Looks like one of the methods they want to look at is this one:
http://adsabs.harvard.edu/abs/2017ApJ...836..196A
https://github.com/mahnen/gamma_limits_sensitivity

I haven't read it yet, not actually sure if that is a new method, or just a description how to compute a flux UL in the usual way. But there seem to be well-established test cases, so those could be useful for Gammapy at least (and it's MIT licensed, i.e. we can use for Gammapy as long as we include a reference where it comes). So I wanted to leave this now here for whoever continues with ULs in Gammapy.

**Comment by cdeil** [comment]
@adonath - Assigning this issue to you, since you already started to work on likelihood profiles for spectra.

**Comment by adonath** [comment]
Addressed by #1929, #1933 and #1934.

**Comment by cdeil** [comment]
I'm re-opening this issue, putting it on the v0.13 milestone.

Fermi-LAT added a new tutorial how to compute upper limits: https://fermi.gsfc.nasa.gov/ssc/data/analysis/scitools/upper_limits.html

In high-energy physics http://adsabs.harvard.edu/abs/2011EPJC...71.1554C is very popular and it's implemented here: https://github.com/marinang/statnight

At the very least, we need to add end-user documentation how parameter limits can be computed with Gammapy. We very likely also need more methods, and validation against results from papers or other codes. Flux point limits aren't the only limits of interest, Gammapy also needs to be able to compute e.g. source extension limits assuming some parametrised shape.

@adonath - If you don't like this issue, feel free to close and open a new one. But I think the general reminder issue that this needs work in 2019, and specifically to these methods / papers should be open.

**Comment by cdeil** [comment]
Could be useful (to use directly, or copy & paste from, or learn from): https://github.com/scikit-hep/pyhf

**Comment by adonath** [comment]
I think right now there is no strong motivation to add further methods for UL computation . By now we use the same method as Fermipy consistently everywhere. We also have a `ParameterEstimator` class, which allow to compute likelihood profile based UL for any paramater. Closing the issue now....
