### ISSUE TITLE
Merge DifferentialFluxPoints and IntegralFluxPoints classes

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#699]
In Gammapy we currently have separate [DifferentialFluxPoints](http://docs.gammapy.org/en/latest/api/gammapy.spectrum.DifferentialFluxPoints.html) and [IntegralFluxPoints](http://docs.gammapy.org/en/latest/api/gammapy.spectrum.IntegralFluxPoints.html) classes.

I think we should merge them or outright replace them with an existing class from Fermipy.

Something that represents this format developed by @woodmd and can either have differential or integral values filled:
http://gamma-astro-data-formats.readthedocs.io/en/latest/results/flux_points/index.html

Another suggestion I have is that we shouldn't sub-class `astropy.table.Table`, but instead store `table` as a data member. As they say: "Prefer composition over inheritance".

Good example that has a table data member: https://gammapy.readthedocs.io/en/latest/api/gammapy.data.PointingInfo.html

Another bad example that sub-classes table that I plan to change when I get a chance:
https://gammapy.readthedocs.io/en/latest/api/gammapy.data.EventList.html

@joleroi @woodmd - Thoughts?

Related: https://github.com/fermiPy/fermipy/issues/82, #698 .

**Comment by joleroi** [comment]
https://github.com/open-gamma-ray-astro/gamma-astro-data-formats/issues/45

**Comment by joleroi** [comment]
I would suggest to decide on a spec ASAP. And then just implement it in gammapy. The astropy ``Table`` as data member is a good idea, I think. When I added the flux point classes I used ``EventList`` as inspiration .. so we should change both.

**Comment by cdeil** [comment]
We can wait for a day or two. But if there's disagreement on the spec discussion we should just move ahead and implement what we like in Gammapy, and then change again when the discussion is through (could take a day or months).

**Comment by joleroi** [comment]
For me the current status of the ``DifferentialFluxPoints`` class is satisfying, if you need it to be more flexible for your use case, feel free to add what you like

**Comment by adonath** [comment]
Resolved by #810? Close this issue?

**Comment by joleroi** [comment]
:+1:

**Comment by cdeil** [comment]
The new class is here:
http://docs.gammapy.org/en/latest/api/gammapy.spectrum.FluxPoints.html

Of course, further feedback and improvements are welcome!
But I don't think keeping this issue open helps ... closing it now.
