### ISSUE TITLE
Adaptive ring background estimation

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#7]
Implement an adaptive ring background method in `gammapy/background/ring.py`.

The ring background method is described in [Berge 2007](http://adsabs.harvard.edu/abs/2007A%26A...466.1219B), the adaptive ring background method in [Carrigan 2013](http://adsabs.harvard.edu/abs/2013arXiv1307.4868C).

**Comment by adonath** [comment]
A prototype implementation has been added in #719. Close issue?

**Comment by cdeil** [comment]
@adonath - I would prefer to keep the issue open as a reminder until the adaptive ring background estimation is of Gammapy 1.0 quality.

Of course, an issue without concrete action items if of limited value. So I had a quick look at [gammapy.background.AdaptiveRingBackgroundEstimator](http://docs.gammapy.org/en/latest/api/gammapy.background.AdaptiveRingBackgroundEstimator.html) in the docs and the implementation / tests. Here's some suggestions:

- [ ] The example in the docstring is broken. You have to replace `RingBackgroundEstimator` with `AdaptiveRingBackgroundEstimator`. Then it runs, but gives a few warnings that should really be handled in Gammapy, not exposed to the user:
```
WARNING: The kernel normalization factor is exceptionally large, > 100. [astropy.convolution.core]

/Users/deil/Library/Python/3.5/lib/python/site-packages/gammapy/background/ring.py:128: RuntimeWarning: divide by zero encountered in true_divide
  alpha_approx = np.where(exposure_off > 0, exposure_on / exposure_off, np.inf)
/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/image.py:676: UserWarning: The backend (<class 'matplotlib.backends.backend_macosx.RendererMac'>) does not support interpolation='none'. The image will be interpolated with 'nearest` mode.
  "mode." % renderer.__class__)
/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/image.py:676: UserWarning: The backend (<class 'matplotlib.backends.backend_macosx.RendererMac'>) does not support interpolation='none'. The image will be interpolated with 'nearest` mode.
  "mode." % renderer.__class__)
```
- [ ] The output image looks a bit weird. Is it correct? Showing an alpha or some other map that let's one see how the adaptive algorithm kicks in would be nice. Also choosing some more interesting example image for the docs, e.g. 2FHL for the Galactic center or Vela region would be better. Maybe move the example to an IPython notebook and link to it from the docstring?
- [ ] I would suggest to rename parameters `width` -> `r_width` and `stepsize` -> `r_stepsize`, to make it clearer that they concern the radius.
- [ ] At least a short description of the algorithm would be good, especially mention how `threshold_alpha` is used. Probably this would be best to do when showing the alpha map in the docs example.
- [ ] In the code I see that you're storing the parameters in a `parameters` dict. This is not visible from the docstring at the moment. You could either call the attribute `_parameters` and expose it as a property `parameters`, then the docstring will show up in the docs and you can describe this. Or there's also a syntax to document such attributes in an `Attributes` section in the class-level docstring.
- [ ] The [AdaptiveRingBackgroundEstimator.run](http://docs.gammapy.org/en/latest/api/gammapy.background.AdaptiveRingBackgroundEstimator.html#gammapy.background.AdaptiveRingBackgroundEstimator.run) method has parameters of type `SkyImageList`, the link to those is broken in the Sphinx docs.
- [ ] It's hard for me to see from the tests if the method works. Is it possible to pick a case where the "correct" response is clearer? Or maybe just add a comment or two, explaining why numbers are as they are (number of pixels in the ring, etc.)?
- [ ] For adaptive algorithms that can "go wrong" it can be useful to have a "report" or "summary" method that looks at some common diagnostics and prints them. Here it could be to give info about which alphas were used by how many pixels, and especially if there's pixels where no background estimate is available at all, which is what happens inside large exclusion regions. It's really useful to have such a "summary report printout" and "summary plots" that let users quickly see if the algorithm worked for their dataset and play with parameters (e.g. change ring parameters or alpha threshold).

I think it's worth spending the extra time (2 days or work here?), and make image background estimation a section in the Gammapy paper, or punt it to a future "gamma-ray image analysis" method paper next year.

**Comment by adonath** [comment]
@cdeil I agree with most of your points, so lets keep this issue open.

**Comment by cdeil** [comment]
I'm not sure what the status is here. Moving to v0.8 milestone.

**Comment by registerrier** [comment]
Migration is done in PR #1582

Docstrings and example have been updated and corrected.
A parameter property has been added.

I don't know what diagnostics to add for the AdaptiveRingBackground for the moment.
