### ISSUE TITLE
gammapy-extra files cleanup

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#700]
As we're producing better example datasets in gammapy-extra, we should clean up some old stuff.

Let's use this issue to discuss where needed.

Just one thing I noticed:
https://github.com/gammapy/gammapy-extra/blob/master/datasets/exclusion_masks/tevcat_exclusion.fits
is 49 MB and compressed 78K when you run gzip.
@joleroi - can you please change the file / script /tests to the zipped version, and in the future only commit small zipped FITS files?

We'll have to loose git history for gammapy-extra if we want to get rid of such large files in the git repo so that clone remains fast. For now my suggestion would be to just keep going, and then maybe at some future point I'll purge large files from the git history.

**Comment by cdeil** [comment]
I've removed some very old datasets that we haven't used in years:
https://github.com/gammapy/gammapy-extra/commits/master/datasets

I think that's OK, even if those are used in tests or tutorials of very old Gammapy versions. We just don't support those any more, and most likely no-one will notice.

@adonath - I noticed that `make dataset-index` uses `glob` and picks up all kinds of files that we don't need to ship to users. That's bad. I'll see if I can work on that a bit and make it better.

**Comment by cdeil** [comment]
What's this?

https://github.com/gammapy/gammapy-extra/tree/master/test_datasets

It's not accessed from Gammapy tests any more.

@adonath - OK to remove?

Test datasets that are used are here:
https://github.com/gammapy/gammapy-extra/tree/master/datasets/tests

Would like to have one folder to clean up, not two.

**Comment by cdeil** [comment]
@registerrier - I've removed `gammapy-extra/valhalla` in https://github.com/gammapy/gammapy-extra/commit/a54ca164757c574aabd4868e768798cfbb58f633

It's still in version history of course, you can see what it is here: https://github.com/gammapy/gammapy-extra/tree/e0d5bb1bb4ad48bf9689af57c7fc4efcd578c0fe/valhalla/cta_simulation
and it'll forever be in Gammapy v0.7.

There was a big discussion in #1551, where the compromise was to introduce `gammapy-extra/valhalla/cta_simulation` and put a copy of the code there. I think it's obvious by now that we do not want to maintain and evolve code there. No-one touched it since we put it there, so it's the same code as in Gammapy v0.7, and we don't want people to spend time on updating and evolving the code in `gammapy-extra/valhalla/cta_simulation`, instead we want them to contribute to `gammapy.irf`.

**Comment by adonath** [comment]
@cdeil I have no idea, where this duplication the test data comes from. So please go ahead and remove `test_datasets`.

**Comment by cdeil** [comment]
Removed `gammapy-extra/test_datasets` in https://github.com/gammapy/gammapy-extra/commit/744b0c5ef64a31d0629d613cbe8a6797248b1a7f

I have a theory how this happened: first came `test_datsets`. Then later we introduced `datasets/tests` and just globbed there when introducing `gammapy download` and the index files.

So I think removing `test_datsets` and cleaning up `datasets/tests` is the right thing to do.

**Comment by cdeil** [comment]
I removed a lot of old stuff, and updated old tests to use more recent files (especially HESS DR1)

Current status:

- https://github.com/gammapy/gammapy-extra/commit/e1a36df10688e397ff91cf546f013210a06f5b83
- https://github.com/gammapy/gammapy/commit/1ee0cd8e0b95485b403dd1344e48a77eacc4eb9f

`gammapy download` should be significantly faster now, downloading fewer files.

There's still many things we could clean up further, in [gammapy-extra/datasets](https://github.com/gammapy/gammapy-extra/tree/master/datasets) and especially in [gammapy-extra/datasets/tests](https://github.com/gammapy/gammapy-extra/tree/master/datasets/tests)

But this is as far as I want to go for now, so I'm closing this old issue.
