### ISSUE TITLE
TestFluxEstimator.test_with_power_law fail in master

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#724]
@joleroi - I think after your changes yesterday `TestFluxEstimator.test_with_power_law` fails in master. Looks like the energy grouping isn't applied to `backscale_ratio`?

```
E       TypeError: statistic input array sizes do not match
```

https://travis-ci.org/gammapy/gammapy/jobs/162223291#L938

I will mark that test as `xfail` for now.

Putting this under the 0.5 milestone.
Let me know if you don't have time, and I'll try to do it on Monday.

**Comment by cdeil** [comment]
It might fail like this by now:
https://travis-ci.org/gammapy/gammapy/jobs/162411311#L1057

**Comment by cdeil** [comment]
There's also this fail in the spectrum notebook:
https://travis-ci.org/gammapy/gammapy/jobs/162411333#L3070

@joleroi - I'll disable the test for that one now to do other things,
and then you or I can go back to `gammapy.spectrum` Monday.
I'm moving the 0.5 milestone to Tuesday.

**Comment by cdeil** [comment]
`test_wstat` on `gammapy/stats/tests/test_fit_statistics.py:83` also fails:
https://travis-ci.org/gammapy/gammapy/jobs/162414691#L940

I'm adding `xfail` to this test now as a temp solution to fix the builds in `master`

**Comment by joleroi** [comment]
General comment. Fails like this 
```
TypeError: statistic input array sizes do not match
```
are due to https://github.com/sherpa/sherpa/issues/248

I'll have a look at the other fails ASAP

**Comment by joleroi** [comment]
The notebook is fixed in https://github.com/gammapy/gammapy/pull/728
