### ISSUE TITLE
array cdf random sampling

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#74]
The current [`GeneralRandom`](https://gammapy.readthedocs.org/en/latest/api/gammapy.utils.distributions.general_random.GeneralRandom.html) class should be improved (work with n-dim arrays, rename, document, unit tests).

I think this can be implemented better with [`np.choice`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.random.choice.html) when passing `a=pdf` and `p=pdf`.

It would also be nice to add functions that consider the array a discretised version of a continuous function and then sample that continuous function, similar to what is available in ROOT:
http://root.cern.ch/root/html/src/TF2.cxx.html#QsZi6C

I've made a feature request for this in scipy: https://github.com/scipy/scipy/issues/3747

**Comment by cdeil** [comment]
Some more notes to self or @joleroi :

I think this might be a better implementation that what we have in `gammapy/utils` at the moment:
https://stackoverflow.com/a/21101584/498873
Could add tests and replace the current implementation with that.

There's a getting started blog post with a nice plot explaining the method here:
http://www.nehalemlabs.net/prototype/blog/2013/12/16/how-to-do-inverse-transformation-sampling-in-scipy-and-numpy/

I remember there were discussions / threads / code on the scipy mailing list concerning a possible general class to interpolate a discrete PDF / CDF or inverse CDF in a good stable way.
If anyone is willing to work on this I could look it up.

**Comment by adonath** [comment]
This is probably useful for event sampling. As we haven't set a time-line for the event sampler yet, I'll put it under v1.0 milestone.

**Comment by cdeil** [comment]
@fabiopintore and @adonath - Is there anything left to do for this issue?
I think we can close it now?

**Comment by fabiopintore** [comment]
I think we can close it.
