### ISSUE TITLE
Improve spectrum observation notebook

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#742]
To have a Gammapy CTA application example for the presentation at the CTA meeting next week Tuesday, @jjlk and I started a "Spectrum simulation for CTA" notebook just now:
http://nbviewer.jupyter.org/github/gammapy/gammapy-extra/blob/master/notebooks/spectrum_simulation.ipynb

@joleroi and / or @jjlk - If you have time in the coming days to investigate / fix some of the issues that came up there, or to extend the notebook to make it more interesting, please do.

We can use this issue to discuss.

TODO:
- [ ] Running this script creates a `notebooks/fit_result_PowerLaw.yaml` file. That shouldn't happen, Gammapy should only create files when the user explicitly calls a method that has a name indicating that files will be written.
- [ ] The simulation seems to give too low counts for CTA (see TODO for AEFF below).
- [ ] Printing `obs` doesn't work, because no `off_vector` is present.
- [ ] `SpectrumObservation.peek()` still plots the image twice in the notebook. Fix!
- [ ] Simulation should work without having to se `lo_threshold` and `hi_threshold`, but doesn't. Possibly in CTA there will not be such thresholds, one can just use all counts.
- [ ] Simulate some real spectrum to make it more interesting. Ideally some source where published CTA simulations with prod 2 exist.
- [ ] Add background and theta cut to SpectrumSimulation (quite a bit of work)
- [ ] Compute flux points
- [ ] Compute significance of source detection.
- [ ] Show CTA IRFs in some more detail and make some comments on the shapes?
- [ ] Show how to scan some parameter in observation time (e.g. significance of cutoff energy) as an example how to find out how much observation time to request for a given science question.

**Comment by joleroi** [comment]
> Running this script creates a notebooks/fit_result_PowerLaw.yaml file. That shouldn't happen, Gammapy should only create files when the user explicitly calls a method that has a name indicating that files will be written.

In general ``run`` methods in (at least the spectral analysis part of) gammapy run all steps of an analysis and write the results to disk. If you do not want that you have to call the individual analysis methods, in the case of ``SpectrumFit`` it's only one called ``fit``

**Comment by joleroi** [comment]
https://github.com/gammapy/gammapy/issues/720

**Comment by joleroi** [comment]
> Simulation should work without having to se lo_threshold and hi_threshold, but doesn't.

@cdeil Can you point out an example where I can see the error message, in principle the simulation does not know anything about thresholds

**Comment by cdeil** [comment]
I noticed this while writing
[spectrum_simulation.ipynb](http://nbviewer.jupyter.org/github/gammapy/gammapy-extra/blob/master/notebooks/spectrum_simulation.ipynb) with @jjlk .
If you uncomment
```
aeff.lo_threshold = lo_threshold
aeff.hi_threshold = hi_threshold
```
in cell 6 you should get the error.

**Comment by cdeil** [comment]
@joleroi @jjlk - Contrary to what I said last week, I've decided to keep this notebook for now:
https://github.com/gammapy/gammapy-extra/blob/master/notebooks/spectrum_simulation_cta.ipynb

At least until we have new / better notebooks with CTA examples.
It's not linked to from the index page at the moment though.

I've updated it a bit and cleaned it up.

It's pretty slow, I think because there's such a fine energy binning.
@joleroi - if it's quick for you, maybe you could change this?
It would be good if first simple example runs in ~ 1 sec.

If this is just duplicating stuff from other 1-d spectrum notebooks, eventually it should be removed.
So @joleroi @jjlk - feel free to improve or reorganise content in the 1-d spectrum notebooks any time or improve them.

**Comment by cdeil** [comment]
One issue I noticed just now with `spectrum_simulation.ipynb` is that I get incorrect spectral indices, but no error:
```
[5.1817803417293984, 1.6298144633011236, 9.9999972809821962, 1.992107739333786, 1.9649879009564355, 9.9999978952966, 4.4894243812384325, 6.1772455807957076, 2.3976418829555244, 9.9999938499917604]
```
@joleroi - Can you please have a look?

---

More generally, we should discuss / clean up the 1D spectrum analysis related notebooks, so that there's good organisation of content and not too much overlap.

Currently we have this:

* [spectrum_analysis](https://github.com/gammapy/gammapy-extra/blob/master/notebooks/spectrum_analysis.ipynb)
* [spectrum_simulation](https://github.com/gammapy/gammapy-extra/blob/master/notebooks/spectrum_simulation.ipynb)
* [spectrum_simulation_cta](https://github.com/gammapy/gammapy-extra/blob/master/notebooks/spectrum_simulation_cta.ipynb)

One thought I had was to maybe split out the user-defined model into a separate notebook. It's a bit hidden at the moment, in the spectrum_simulation notebook. So this new notebook would explain how spectral models work, how to write a new one, and in the future how to read / write models and how to make a physical model with Naima that can be fit with Gammapy. Then this notebook wouldn't do any simulation or fitting, but point to the other notebooks and say: simulation and fitting works with any spectral model defined in this way.

**Comment by joleroi** [comment]
> One thought I had was to maybe split out the user-defined model into a separate notebook. It's a bit hidden at the moment, in the spectrum_simulation notebook

:+1: 

I am currently working on a ``SpectrumAnalysisIACT`` class (because I got tired of writing it again and again for my analyses). Maybe we should wait for that before we reorganize the notebooks.

**Comment by joleroi** [comment]
> One issue I noticed just now with spectrum_simulation.ipynb is that I get incorrect spectral indices, but no error is raised:

What is the line you posted? Can you point me to the cell where the incorrect index is computed?

**Comment by cdeil** [comment]
The output I posted was from
```
print(best_fit_index)
```
which is currently in cell 26.

**Comment by joleroi** [comment]
After https://github.com/gammapy/gammapy-extra/commit/20a677acbac453b97f233b789543a74caf496d6c the output is

```
[2.8875690152357274, 1.8675012564154847, 2.615113294915091, 2.1381933091530518, 2.1958706604565603, 2.3658522601045102, 2.9585649812793648, 2.9228716957787881, 1.9987105503591069, 3.2220035301460714]
```

**Comment by cdeil** [comment]
Moving to 0.7 milestone.

**Comment by joleroi** [comment]
It's not clear what this issue is about. There are two notebooks
* http://nbviewer.jupyter.org/github/gammapy/gammapy-extra/blob/master/notebooks/spectrum_simulation.ipynb
* http://nbviewer.jupyter.org/github/gammapy/gammapy-extra/blob/master/notebooks/spectrum_simulation_cta.ipynb
And they are both party discussed above. I suggest to close this and open new issues for each notebook

**Comment by cdeil** [comment]
@joleroi - OK to close this old issue.

Maybe check if this bug is still present (one of the things listed above)?
```
Printing obs doesn't work, because no off_vector is present.
```

**Comment by joleroi** [comment]
> Maybe check if this bug is still present (one of the things listed above)?

Ensured by this test 
https://github.com/gammapy/gammapy/blob/master/gammapy/spectrum/tests/test_observation.py#L41
