### ISSUE TITLE
Refactor SpectrumExtraction

### ISSUE THREAD

**Issue by joleroi** [gammapy/gammapy#747]
The ``extract_spectrum`` method on ``SpectrumExtraction`` is very messy.

* [x]  The loop should be separated from a method processing one observation
* [x] The handling of meta keywords should be separated out 
* [x] The containment correction should be separated out (see also https://github.com/gammapy/gammapy/issues/684)

**Comment by cdeil** [comment]
Moving milestone to 0.7 (I'll make the 0.6 release tomorrow)

**Comment by joleroi** [comment]
Done in https://github.com/gammapy/gammapy/pull/995
