### ISSUE TITLE
Update EffectiveAreaTable2d to read effective area as function of reconstructed energy

### ISSUE THREAD

**Issue by joleroi** [gammapy/gammapy#757]
The ``EffectiveAreaTable2d.read`` method at the moment takes the first HDU it find. As of https://github.com/gammasky/hess-host-analyses/issues/48 there is a second HDU containing the effective area as a function of reconstructed energy. It should be possible to read this HDU.

**Comment by cdeil** [comment]
Related:
- https://github.com/gammapy/gammapy/issues/539#issuecomment-222464452
- http://docs.gammapy.org/en/latest/_modules/gammapy/utils/nddata.html#NDDataArray.read

Agreed this should be changed so that a `hdu` option works for `EffectiveAreaTable2d.read`.

**Comment by joleroi** [comment]
Actually I think nothing has to be done, since ``Table.read`` takes ``hdu`` as keyword argument.
see

**Comment by joleroi** [comment]
This should be fixed by https://github.com/gammapy/gammapy/pull/755

**Comment by joleroi** [comment]
This was fixed in https://github.com/gammapy/gammapy/pull/832
