### ISSUE TITLE
Implement basic event list sampler

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#761]
For the planned CTA data challenge, but also generally for tests, we should implement an event sampler, i.e. a tool to simulate event lists given:
- source spectral model (arbitrary shape)
- source morphology model (point-like or arbitrary radial shape)
- given AEFF, EDISP, PSF (radially symmetric)
- given obs time.

We realised that it's actually not very hard to do, basically a series of sampling from 1-dimensional distributions, which can be done by computing the CDF and using "inverse CDF sampling" from the [0, 1] interval.

Concretely these are the steps (to be done for each GTI) for a radially symmetric source if the exposure doesn't vary across the source:
- Compute `npred = aeff * obs_time * flux` distribution
- Compute total npred and sample total number of events to simulate from that as `np.poisson(npred_total)`
- Sample true energies from npred distribution
- Sample for each e_trues the 1-dim EDISP to get e_reco
- Sample 1-dim radially symmetric morphology model to get offset -> true RA / DEC
- Sample 1-dim radially symmetric PSF to get RA_reco, DEC_reco
- Sample uniform time from t_start to t_end
- done

If you have very extended sources, instead of the 1-dim samplings, you can do this:
- Compute 3-dim (lon-lat-logE) exposure cubes (AEFF * obs_time)
- Compute 3-dim flux cube
- Compute 3-dim npred cube
- poisson-fluctuate npred cube and scatter events within bin OR
- for each fine energy bin, create spline 2-dim model that has sampling implemented (I can add a link later)
- apply EDISP and PSF as above

For background, it's similar, except that you don't multiply with AEFF.

If anyone has some time to work on this in the coming weeks / months, please mention it here.

Related #760 
cc @bkhelifi @cboisson @jjlk

**Comment by adonath** [comment]
Just wanted to mention Scipy's  [rv_discrete](https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.stats.rv_discrete.html) class, which might be useful for this usecase. Here's a toy example, where I used it to generate the gammapy poisson logo: https://github.com/gammapy/gammapy-extra/blob/master/experiments/gammapy_poisson_logo/gammapy_poisson_logo.py

**Comment by cdeil** [comment]
I'm closing this old issue with ideas on event sampling. @fabiopintore wrote a PIG, discussion should go there: #2136
