### ISSUE TITLE
Further EventList improvements

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#782]
In #754 I improved EventList a bit. This is a reminder issue on further tasks that should be done:

- [x] Merge `EventListDataset` class into `EventList` class
- [x] Add events region selection
- [x] Add tests for stacking event lists
- [x] Change from `$GAMMAPY_EXTRA/datasets/hess-crab4-hd-hap-prod2` to a better dataset where event lists have units, and remove the temp fix in `EventList.__init__`.

**Comment by cdeil** [comment]
Related: #1185

**Comment by adonath** [comment]
Nothing left to be done here...
