### ISSUE TITLE
Is the spectrum.SpectrumSimulation.simulate_obs function broken ?

### ISSUE THREAD

**Issue by jjlk** [gammapy/gammapy#801]
Hi @joleroi and @cdeil ,
I was playing with the gammapy.spectrum.SpectrumSimulation class and everything was fine until I did an update of gammapy (I was 227 commits late...).

The problem is that I get a None value when I call the SpectrumSimulation.simulate_obs function. I looked at the code but I didn't find where the None value could come from.

Here is a minimal script showing the bug:

```
import numpy as np
import astropy.units as u
from gammapy.irf import EnergyDispersion, EffectiveAreaTable
from gammapy.spectrum import SpectrumSimulation, SpectrumFit
from gammapy.spectrum.models import PowerLaw
from gammapy.scripts import CTAIrf

filename = '$GAMMAPY_EXTRA/datasets/cta/perf_prod2/South_5h/irf_file.fits.gz'
cta_irf = CTAIrf.read(filename)

aeff = cta_irf.aeff.to_effective_area_table(offset=3 * u.deg)
edisp = cta_irf.edisp.to_energy_dispersion(offset=3 * u.deg)

index = 2.3 * u.Unit('')
amplitude = 2.5 * 1e-11 * u.Unit('cm-2 s-1 TeV-1')
reference = 1 * u.TeV
model = PowerLaw(index=index, amplitude=amplitude, reference=reference)

livetime = 1 * u.h

sim = SpectrumSimulation(aeff=aeff, edisp=edisp,
                         source_model=model,
                         livetime=livetime)
obs = sim.simulate_obs(seed=42)

```
Results is: 
```
In [3]: type(obs)
Out[3]: NoneType
```
Do you have any idea where the problem is?

Thanks!

**Comment by joleroi** [comment]
Thanks for your report!

The problem is that ``sim.simulate_obs`` does not return anything, see

http://docs.gammapy.org/en/latest/_modules/gammapy/spectrum/simulation.html#SpectrumSimulation.simulate_obs

The result is stored in ``sim.obs`` (perhaps this was different in the past)

For an up to date example how to use ``SpectrumSimulation`` see

https://github.com/gammapy/gammapy-extra/blob/master/notebooks/spectrum_simulation.ipynb

**Comment by cdeil** [comment]
@joleroi - I think we made this change of not returning something from the `simulate_obs` method after watching one of the clean code episodes by [uncle Bob](https://en.wikipedia.org/wiki/Robert_Cecil_Martin). One of his recommendations was that methods should
- either change the state of an object and return nothing
- or not change the state of an object and return something

and not both at the same time. His argument was that this leads to simpler, easier to reason about code overall.

I don't really have an opinion on this matter yet, except that maybe I tend to agree with uncle Bob, and to move the Gammapy codebase more in that direction.

So @jjlk - if it's OK with you, we can leave things as-are and close the issue?
(docs can / should always be improved of course, pointing to existing examples or adding new ones in-place, or explaining how a given class works in the docstring better, PRs for that are always welcome)

**Comment by jjlk** [comment]
Thanks for your explanations @joleroi ! I'm getting old and my eyes are not what they where. And yes @cdeil , we can close the issue.

**Comment by joleroi** [comment]
https://github.com/gammapy/gammapy/issues/749

This would have probably avoided the issue ...
