### ISSUE TITLE
Add generic to_sherpa method in SpectralModel

### ISSUE THREAD

**Issue by joleroi** [gammapy/gammapy#805]
* Define Sherpa model (something not built in in Gammapy) - should work
* Simulate data - won't work at the moment, only GP models supported
* Fit - should work

**Comment by cdeil** [comment]
I think keeping our `SpectralModel` in the Gammapy interface, and having a generic way to create and fit Sherpa models from that might be nicer. I.e. Sherpa as a fitting engine only. More convenience and control in Gammapy. Of course, this will not give the expressive modeling language from Sherpa.

So bottom line -- add whatever you like for now, if it works it's progress.

**Comment by joleroi** [comment]
> I think keeping our SpectralModel in the Gammapy interface, and having a generic way to create and fit Sherpa models from that might be nicer. I.e. Sherpa as a fitting engine only

I agree

**Comment by joleroi** [comment]
This will also solve the problem raised [here](https://github.com/gammapy/gammapy/issues/808) namely the fitting of a absorbed spectral model. 

Therefore

* [ ] add to_sherpa method to ``SpectralModel``, subclasses should not have to implement this
* [ ] add notebook showing how to define a user model, simulate data and fit it

**Comment by joleroi** [comment]
Done, see https://github.com/gammapy/gammapy-extra/blob/master/notebooks/spectrum_simulation.ipynb
