### ISSUE TITLE
SkyImage paste error with Numpy 1.12

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#843]
I just now updated to Numpy 1.12, and what was before a warning is now an error:
```
$ time python setup.py test -V -t gammapy/image/tests/test_core.py

____________________________________________ TestSkyImagePoisson.test_cutout_paste _____________________________________________

self = <gammapy.image.tests.test_core.TestSkyImagePoisson object at 0x10e1080b8>

    def test_cutout_paste(self):
        positions = SkyCoord([0, 0, 0, 0.4, -0.4], [0, 0.4, -0.4, 0, 0],
                             unit='deg', frame='galactic')
        BINSZ = 0.02
    
        # setup coordinate images
        lon = SkyImage.empty(nxpix=41, nypix=41, binsz=BINSZ)
        lat = SkyImage.empty(nxpix=41, nypix=41, binsz=BINSZ)
    
        c = lon.coordinates()
        lon.data = c.galactic.l.deg
        lat.data = c.galactic.b.deg
    
        size = Quantity([0.3, 0.3], 'deg')
        for pos in positions:
            cutout = lon.cutout(pos, size=size)
    
            # recompute coordinates and paste into coordinate images
            c = cutout.coordinates()
            cutout.data = c.galactic.l.deg
>           lon.paste(cutout, method='replace')

gammapy/image/tests/test_core.py:236: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <gammapy.image.core.SkyImage object at 0x10e113fd0>, image = <gammapy.image.core.SkyImage object at 0x107f50ba8>
method = 'replace', wcs_check = True

    def paste(self, image, method='sum', wcs_check=True):
        """
            Paste smaller image into image.
    
            WCS specifications of both images must be aligned. If not call
            `SkyImage.reproject()` on one of the images first. See :ref:`image-cutpaste`
            more for information how to cut and paste sky images.
    
            Parameters
            ----------
            image : `~gammapy.image.SkyImage`
                Smaller image to paste.
            method : {'sum', 'replace'}, optional
                Sum or replace total values with cutout values.
            wcs_check : bool
                Check if both WCS are aligned. Raises `~astropy.wcs.WcsError` if not.
                Disable for performance critical computations.
            """
        xlo, xhi, ylo, yhi = self._get_boundaries(self, image, wcs_check)
        xlo_c, xhi_c, ylo_c, yhi_c = self._get_boundaries(image, self, wcs_check)
    
        if method == 'sum':
            self.data[ylo:yhi, xlo:xhi] += image.data[ylo_c:yhi_c, xlo_c:xhi_c]
        elif method == 'replace':
>           self.data[ylo:yhi, xlo:xhi] = image.data[ylo_c:yhi_c, xlo_c:xhi_c]
E           TypeError: slice indices must be integers or None or have an __index__ method

gammapy/image/core.py:438: TypeError
==================================== 1 failed, 41 passed, 1 pytest-warnings in 3.50 seconds ====================================
```

@bsipocz - Why didn't this show up on travis-ci so far? I thought we had a build for latest stable Numpy, maybe even latest dev version?

@adonath - Do you have time to make a fix? If no, let me know and I'll have a look tomorrow.

I know that getting this right is tricky. It took a few pull request to arrive at this code for a similar problem with regions bounding boxes:
https://github.com/astropy/regions/blob/85b1a28bd7c86e7207a8b354a40eedd653b7e667/regions/core/bounding_box.py#L77
Maybe that could be copied over as a utility function to do float -> int correctly in all cases, with a TODO comment to use BoundingBox to compute slices here later (once regions 0.2 is out)?

**Comment by adonath** [comment]
The issue was just a missing `.astype('int')` in `SkyImage._get_boundaries()`, because `np.rint()` still returns an array of float values. I fixed in directly in master. Let's keep the issue open until @bsipocz commented, why this didn't show up on Travis-CI.

**Comment by cdeil** [comment]
@adonath - Thanks!
I can confirm that the test fail is resolved.

Running the docs build, the only error is this one:
```
/Users/deil/code/gammapy/docs/astro/population/index.rst:41: WARNING: Exception occurred in plotting plot_spiral_arms
 from /Users/deil/code/gammapy/docs/astro/population/plot_spiral_arms.py:
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/sphinxext/plot_directive.py", line 520, in run_code
    six.exec_(code, ns)
  File "<string>", line 10, in <module>
  File "/Users/deil/code/gammapy/build/lib.macosx-10.12-x86_64-3.5/gammapy/astro/population/simulate.py", line 254, in make_base_catalog_galactic
    r = Quantity(draw(RMIN.value, RMAX.value, n_sources, pdf(rad_dis())), 'kpc')
  File "/Users/deil/code/gammapy/build/lib.macosx-10.12-x86_64-3.5/gammapy/utils/distributions/utils.py", line 44, in draw
    array = d.draw(size)
  File "/Users/deil/code/gammapy/build/lib.macosx-10.12-x86_64-3.5/gammapy/utils/distributions/general_random.py", line 103, in draw
    idx_f = random_state.uniform(size=N, high=self.ninversecdf - 1)
  File "mtrand.pyx", line 1291, in mtrand.RandomState.uniform (numpy/random/mtrand/mtrand.c:19304)
  File "mtrand.pyx", line 242, in mtrand.cont2_array_sc (numpy/random/mtrand/mtrand.c:7401)
TypeError: 'float' object cannot be interpreted as an integer
```
Again, looks like something where Numpy got stricter and doesn't accept a float where an integer is needed.

@adonath - It's again code that (I think) you wrote. Do you have time to fix or should I have a look?

**Comment by bsipocz** [comment]
@cdeil - latest numpy is defined by ci-helpers, and it's still 1.11 as last time I checked (yesterday), 1.12 was not yet available on the default conda channel.

**Comment by bsipocz** [comment]
Also it seems that both numpy dev and prerelease are allowed to fail so no wonder there that it wasn't spotted.

**Comment by cdeil** [comment]
This is the only fail we have with numpy dev on travis-ci:
https://travis-ci.org/gammapy/gammapy/jobs/193710741#L1837

@adonath - Is this one of the new functions you wrote or old stuff from Ellis or me? Can you fix or remove?

**Comment by cdeil** [comment]
I will look at and try to fix the `plot_spiral_arms.py` and `test_image_lat_profile` fail now.

**Comment by cdeil** [comment]
I've fixed `plot_spiral_arms.py` in master in 50208e64 .

@adonath - If you could have a look and try to improve the script a little further that would be great. See TODO comment at
https://github.com/gammapy/gammapy/commit/50208e649e83da1245d40c12eb724dcc338882c9#diff-2f5a20c6838f9424c68dfdb0deee6bc1R44

I hope the current output is still correct, and I didn't introduce an issue in the calculations that select the indices into the arrays:
![figure_1](https://cloud.githubusercontent.com/assets/852409/22284128/09300114-e2e6-11e6-8324-489f1bc6155b.png)

**Comment by cdeil** [comment]
With #849 merged, the issues discussed above are resolved.

@adonath confirmed offline that the spiral arms and labels are still correct (nothing changed).

Closing this issue now.
