### ISSUE TITLE
Check data types written to OGIP files

### ISSUE THREAD

**Issue by joleroi** [gammapy/gammapy#850]
In https://github.com/gammapy/gammapy/pull/848  and https://github.com/gammapy/gammapy/pull/847 @registerrier  noted that some of the OGIP files that are written by gammapy contain incorrect data types. This seem not to cause problems when opening them in an IPython sessions using sherpa but makes the sherpa command line interface and also XSPEC crash.

The correct data types are given [here](https://heasarc.gsfc.nasa.gov/docs/heasarc/ofwg/docs/spectra/ogip_92_007/node7.html)

We should define data types as explained by @cdeil 
```
>>> import numpy as np
>>> np.dtype('i2')
dtype('int16')
>>> np.dtype('int16')
dtype('int16')
>>> np.dtype(np.int16)
dtype('int16')
```
> See https://docs.scipy.org/doc/numpy/user/basics.types.html
> My preference is to use the long strings ('int16' in this case),

**Comment by cdeil** [comment]
I think the Sherpa devs always consider a crash as a bug, even if passed bad input data, there should be a nice normal Python error traceback, not a crash.

So @joleroi or @registerrier - If you have a minimal test case, I'd encourage you to file an issue in the Sherpa Github tracker in addition to this one.

**Comment by cdeil** [comment]
@joleroi - Assigning to you.
If you don't have time, feel free to assign to me or defer to the 0.7 milestone.
(I want to make the Gammapy 0.6 release this Wednesday)

**Comment by cdeil** [comment]
Moving milestone to 0.7 (I'll make the 0.6 release tomorrow)

**Comment by joleroi** [comment]
I am not aware of an issue that is currently present with our OGIP files. Let's keep this open in order to report such issues when we encounter them.

**Comment by cdeil** [comment]
I'm closing this issue.

@joleroi @registerrier or anyone -- if there's still a problem with OGIP files written by Gammapy, please comment here or re-open!
