### ISSUE TITLE
CTA IRF interpolation nodes issue

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#861]
As mentioned in  https://github.com/gammasky/cta-dc/blob/master/irf/prod3/irf_check.ipynb and discussed with @jjlk , there's an issue with IRF interpolation.

The offset-dependent IRFs have bins:
```
THETA_LO = [0, ..., 5]
THETA_HI = [1, ..., 6]
```

In Gammapy, this is read in like this:
```
>>> print(irf.aeff.offset.data)
[ 1.  2.  3.  4.  5.  6.] deg
```
i.e. interpolation nodes are placed at `THETA_HI` instead of the bin center.

And there's the additional issue that `evaluate` fails for low-offset values (offset < 1 deg).

My suggestions are:
* Change the IRF reader to keep LO / HI on reading (to have the info available, e.g. it can be useful in print output, to show what was really in the file
* Put interpolation nodes at bin center (log bin center in energy)
* Change our interpolation default to allow extrapolation. All our users keep running into this issue at the edges, and while the goal to error when there might be a problem is noble, it keeps people from getting their job done and is very annoying.

The code changes for this are probably minor, but with test and docs updates it's a significant task.
@joleroi - Assigning to you for now.
Let @jjlk  and me know if you don't have time to do or finish it this week and we'll help.

In the past days there were emails on CTA mailing lists, and people want to start using CTA IRFs for science simulations and present first results in the Milano meeting in a month. They explicitly pointed people to http://nbviewer.jupyter.org/github/gammapy/gammapy-extra/blob/master/notebooks/spectrum_simulation_cta.ipynb , so improving this (is it working / tested at the moment?) is important.

**Comment by joleroi** [comment]
> so improving this (is it working / tested at the moment?) is important.

It was not tested and completely broken, maybe we should add a disclaimer to all notebooks that are not tested.
This one I fixed in https://github.com/gammapy/gammapy-extra/commit/63a13c19fc911aa419b97f59277a378c4fbcae2f
but it still does not show much. It should be improved.

**Comment by cdeil** [comment]
>  maybe we should add a disclaimer to all notebooks that are not tested.

My hope is that we can make a concerted effort to improve documentation over the next 10 days until the Gammapy 0.6 release and the workshops. I.e. all try to spend ~ a day to take a broken notebook and make it great ... (wait, this is not funny any more).

If that doesn't work out, yes, I'll delete or hide broken notebooks.

Current status can roughly be seen on this overview page: http://nbviewer.jupyter.org/github/gammapy/gammapy-extra/blob/master/index.ipynb#Notebooks
