### ISSUE TITLE
EnergyDispersion2D peek is very slow

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#862]
@joleroi - As discussed right now, for unknown reasons EnergyDispersion2D peek is super-slow at the moment.
It should take < 1 sec and do simple linear interpolation, but takes ~ 1 minute for this example:
https://github.com/gammasky/cta-dc/blob/master/irf/prod3/irf_check.ipynb
and I think it takes ~ 10 seconds for this example:
http://nbviewer.jupyter.org/github/gammapy/gammapy-extra/blob/master/notebooks/data_iact.ipynb

Could you please have a look. Maybe it's the RMF computation with the integration implemented by Lea via a Python loop? Identifying if that's the case, and posting a few commands that one can run with `%%timeit` would be the first step. Fixing the implementation might take longer / not be high priority, but please have a quick look so that we know what's going on.

**Comment by joleroi** [comment]
The same problem occurs in the CTA spectrum simulation notebook. It's impossible to run it because all operation including energy dispersion take O(1min)

**Comment by joleroi** [comment]
Fixed in https://github.com/gammapy/gammapy/pull/911
