### ISSUE TITLE
Fix SpectrumEnergyGroupMaker.compute_range_safe

### ISSUE THREAD

**Issue by joleroi** [gammapy/gammapy#867]
The [compute_range_safe](https://github.com/gammapy/gammapy/blob/master/gammapy/spectrum/energy_group.py#L111) method is broken, and the corresponding test xfailed.

This method applies the energy range, based on the ``lo_threshold`` and ``hi_threshold`` properties of the ``SpectrumObservation``. This does not work if these are not set (i.e. all bins within the safe range, can happen in simulations). The reason are binning issues.

Anyways, how this method should works is take the safe bins from ``SpectrumObservation.bins_in_safe_range`` and then define the overflow and underflow bin accordingly.

**Comment by cdeil** [comment]
I see that there's several fails in `master`:
https://gist.github.com/cdeil/16bb76351da9669f7018861976884200
and don't have time to look into this at the moment.

@joleroi - Can you fix those in the coming days or should I xfail those tests for now?

**Comment by joleroi** [comment]
https://github.com/gammapy/gammapy/pull/863 fixes master by marking the FluxPoints test xfail.

**Comment by joleroi** [comment]
Fixed in #912
