### ISSUE TITLE
Matplotlib notebook double plot issue

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#873]
I was reading
http://nbviewer.jupyter.org/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/04.00-Introduction-To-Matplotlib.ipynb#show()-or-No-show()?-How-to-Display-Your-Plots
and remembered the "double-plotting" issue we sometimes had / have in IPython notebooks.

> One thing to be aware of: the plt.show() command should be used only once per Python session, and is most often seen at the very end of the script. Multiple show() commands can lead to unpredictable backend-dependent behavior, and should mostly be avoided.

It sounds like we in Gammapy should never call "plt.show" and leave that up to the user (to control the plotting event loop and when to show figures), no?

So the first thing to try would be to just remove all `plt.show` calls from our `plot` and `peek` methods, no?
https://github.com/gammapy/gammapy/search?utf8=%E2%9C%93&q=plt.show+path%3Agammapy&type=Code

@adonath - Thoughts? Would you be willing to fix this issue within the next ~ week for the upcoming 0.6 release or should I do it?

**Comment by cdeil** [comment]
@facero is fixing this. The main issue is that we're returning a `Figure`. We discussed just now and decided that not calling `plt.show` and not return a `Figure`.

This means that our plot / peek functions behave like Matplotlib functions like `plt.scatter`, `plt.plot`, and users will have to learn to call `plt.show` if they aren't in pyplot mode (which is rare when doing interactive work with plotting anyways).

**Comment by adonath** [comment]
:+1: For this change.

**Comment by cdeil** [comment]
This issue was fixed a few weeks ago by @facero in #919.
Closing it now.
