### ISSUE TITLE
Add docs examples how to create FluxPoints

### ISSUE THREAD

**Issue by joleroi** [gammapy/gammapy#874]
The old ``DifferentialFluxPoints`` class I added a while ago, had a method ``from_arrays`` (I don't care about the name though). 

http://docs.gammapy.org/en/v0.4/api/gammapy.spectrum.DifferentialFluxPoints.html#gammapy.spectrum.DifferentialFluxPoints.from_arrays

I found it very useful, because you give flux points and errors etc. without caring about the column names in the SED spec. I don't think a user will be happy to have to create an astropy table with the correct column names to use our flux points class. This method seems to have disappeared in the refactoring of the flux points classes. I think we should add it back.

**Comment by cdeil** [comment]
I'm -1 on adding this. It's just re-exposing a small subset of functionality of `Table` before creating the `FluxPoints` object. Suggest to instead improve the docs with examples how to manipulate `Table` into the expected format. 

What we have now is this:
http://docs.gammapy.org/en/latest/api/gammapy.spectrum.FluxPoints.html

So if you have a Table in a non-standard format you have to do something like:
```python
table = Table.read('bad-point.txt')
table.rename_column('Fluss', 'dnde')
# More fix-ups
flux_points = FluxPoints(table)
```

And if you just have some data as lists or arrays, you have one or two more lines to pass via `Table`:
```python
data = <some format Table understands, there are many conveniences>
fluxPpoints = FluxPoints(Table(data))
```

Adding a second way to create `FluxPoints` doesn't bring any advantages, but makes it more complex for users and us.

@joleroi - OK to "solve" this point via docs examples?

Anyone volunteering to improve the docs?

**Comment by adonath** [comment]
Thinking about this again, I agree with @cdeil. Astropy tables are a standard data structure we use everywhere in Gammapy (`EventList`, `SourceCatalog`, etc.) and we should just teach users how to work with it.

**Comment by cdeil** [comment]
@adonath - Yes, from the past few weeks I've learnt that most users don't know the basics of `Table`, and teaching them those is really essential to using Gammapy.

So basically we should refer to the Astropy tutorials and docs, but I think a 10 min read on tutorial introduction to Numpy & Astropy, and for sure including Table, would be in scope for the Gammapy docs. This could be made interesting by using gamma-ray data.

@adonath - Could you take over this issue as well as
https://github.com/gammapy/gammapy/issues/618#issuecomment-272133922
and do them within the next ~ week, i.e. before the workshops?

**Comment by joleroi** [comment]
:+1: to make all gammapy users astropy experts!

**Comment by cdeil** [comment]
I'm re-opening to have this as a reminder. The action item here is to improve the docs along the lines of what is discussed above.

**Comment by cdeil** [comment]
Moving milestone to 0.7 (I'll make the 0.6 release tomorrow)

**Comment by cdeil** [comment]
Done by @adonath in #1125 and other docs improvements in the past months, e.g. @joleroi added
https://github.com/gammapy/gammapy-extra/blob/master/notebooks/spectrum_models.ipynb

Closing this old issue.
