### ISSUE TITLE
Add Fermi-LAT 3FHL extended sources templates

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#877]
The 3FHL extended sources spatial template archive (v17) was released:

https://fermi.gsfc.nasa.gov/ssc/data/access/lat/3FHL/
https://fermi.gsfc.nasa.gov/ssc/data/access/lat/3FHL/LAT_extended_sources_v17.tgz

If I remember correctly, we have access to the spatial templates for one of the previous Fermi-LAT catalogs, and generating model images used to work at some point. Not sure if it's still working or if it needs a re-write for that other catalog also.

Info by Elizabeth Ferrera via email:

> This archive file contains all the spatial templates that were used in the 3FHL analysis. As a note, there are several extended sources that use analytic extended forms rather than map templates. These are G150.3.3+4.5, G292.2-0.5, HESS J1356-645, HESS J1420-607, and G24.7+0.6.

> There is a description of the method used for these templates in the Extended Sources paper recently submitted to ApJ. You can find a preliminary version of that paper at:
https://arxiv.org/abs/1702.00476

> The analytic forms for these sources are not yet available in the public versions of the Fermi Science Tools. We are working to prepare a new release of the tools, but do not anticipate it will be available until March at the earliest. If you have an analysis that requires the inclusion of one of these sources, we encourage you to create a spatial template to include in your analysis.

@jjlk added 3FHL, but I don't think he has time to add the spatial templates, given that he's an extra-galactic guy and doesn't have a use for them.

cc @adonath

**Comment by cdeil** [comment]
@adonath - Didn't you add this already? Is it finished / visible via the docs? Close issue?

**Comment by adonath** [comment]
Addressed in https://github.com/gammapy/gammapy/pull/1013.
