### ISSUE TITLE
Spectrum test fails in master

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#878]
@joleroi - Could you please fix this docs build error leading to travis-ci test fail in master?
https://travis-ci.org/gammapy/gammapy/jobs/199604312#L1626
```
/home/travis/build/gammapy/gammapy/build/lib.linux-x86_64-2.7/gammapy/irf/energy_dispersion.py:docstring of gammapy.irf.EnergyDispersion2D.peek:9: SEVERE: Unexpected section title or transition.
```
(I wasn't sure if you're working on that code and didn't want to create a merge conflict for you.)

---

Locally I currently get the following fails from ` gammapy/spectrum/tests/test_fit.py` in master, which as far as I can see aren't seen on travis-ci:
https://gist.github.com/cdeil/30143c8d28b264a91ebc7e4133aa8ac8

This one is probably due to a recent change by you?
https://gist.github.com/cdeil/30143c8d28b264a91ebc7e4133aa8ac8#file-gistfile1-txt-L84

This one looks like you just need to reduce assert precision?
https://gist.github.com/cdeil/30143c8d28b264a91ebc7e4133aa8ac8#file-gistfile1-txt-L413

**Comment by joleroi** [comment]
> Locally I currently get the following fails from gammapy/spectrum/tests/test_fit.py in master, which as far as I can see aren't seen on travis-ci:

Did you update ``gammapy-extra`` ?

**Comment by joleroi** [comment]
travis build should be fixed by https://github.com/gammapy/gammapy/commit/29f45c186cafec0f6550a5af6da5b7d897dd9085

**Comment by cdeil** [comment]
I am up to date with gammapy-extra, at this latest commit: https://github.com/gammapy/gammapy-extra/commit/19f60bbc90ee01cfd649d07305fdab56bd5fa3ad

The fail is about a test example that slices a `SpectrumObservationList` object, and then apparently the result isn't a `SpectrumObservationList` object any more, i.e. this fails:
```
if not isinstance(obs_list, SpectrumObservationList)
```
This is how it's currently implemented:
http://docs.gammapy.org/en/latest/_modules/gammapy/spectrum/observation.html#SpectrumObservationList

Probably non-trivial to understand why this happens for me (Python 3.5, Astropy dev).
@joleroi - If you don't understand it from the info here, or can't reproduce, maybe assign back to me and I'll have a look as soon as I can?

**Comment by joleroi** [comment]
What's the status here? Do you still get the issue? Assigning back to you @cdeil

**Comment by cdeil** [comment]
I think this is old stuff that was resolved months ago. Closing issue.
