### ISSUE TITLE
Merge spectral model classes in gammapy.utils.modeling with gammapy.spectrum.models

### ISSUE THREAD

**Issue by joleroi** [gammapy/gammapy#879]
[This](https://github.com/gammapy/gammapy/blob/master/gammapy/utils/modeling.py#L171) has to go [here](https://github.com/gammapy/gammapy/blob/master/gammapy/spectrum/models.py#L35)

see also https://github.com/gammapy/gammapy/pull/871

**Comment by cdeil** [comment]
Closing this old issue.
This was done by @joleroi recently in a0c231cf01475d0a2d60655d3a59a8aed6999002 and more cleanup in that directly is coming via #1403 .
