### ISSUE TITLE
Spectrum model test fail

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#880]
The following issue was reported on the Gammapy mailing list just now:
https://groups.google.com/forum/#!topic/gammapy/HBCTHRfh6Hs

```
ERROR collecting lib.macosx-10.10-intel-2.7/gammapy/spectrum/tests/test_models.py 
gammapy/spectrum/tests/test_models.py:111: in <module>
    model=table_model(),
gammapy/spectrum/tests/test_models.py:22: in table_model
    return TableModel(energy, flux, 1 * u.Unit(''))
gammapy/spectrum/models.py:624: in __init__
    kind='cubic')
/Library/Python/2.7/site-packages/scipy/interpolate/interpolate.py:478: in __init__
    self._spline = splmake(self.x, self._y, order=order)
/Library/Python/2.7/site-packages/scipy/interpolate/interpolate.py:2927: in splmake
    coefs = func(xk, yk, order, conds, B)
/Library/Python/2.7/site-packages/scipy/interpolate/interpolate.py:2624: in _find_smoothest
    p = scipy.linalg.solve(Q, tmp)
/Library/Python/2.7/site-packages/scipy/linalg/basic.py:79: in solve
    a1 = _asarray_validated(a, check_finite=check_finite)
/Library/Python/2.7/site-packages/scipy/_lib/_util.py:228: in _asarray_validated
    a = toarray(a)
/Library/Python/2.7/site-packages/numpy/lib/function_base.py:1215: in asarray_chkfinite
    "array must not contain infs or NaNs")
E   ValueError: array must not contain infs or NaNs
```

I see a similar issue for gamma-cat when using the Gammapy master since a few hours ago:
https://travis-ci.org/gammapy/gamma-cat#L582

@adonath @joleroi - Is this due to changes you did recently?
I'm assigning this to myself and plan to look at this tomorrow, but if you know what it is, please comment here.

**Comment by joleroi** [comment]
I have never seen this error and cannot reproduce it locally, sorry.

**Comment by cdeil** [comment]
I'm not sure if this issue is still present or have a testcase for it.
Moving this issue to 0.7
Action item: implement well-structured unit tests for spectral models (including table model) in `gammapy/spectrum/tests/test_models.py`

**Comment by cdeil** [comment]
I'm closing this old issue. I think the error is resolved; there is a test case for a TableModel in `gammapy/spectrum/tests/test_models.py`. Of course, most of the Gammapy code and tests can be improved, but I don't think this specific reminder issue is useful.
