### ISSUE TITLE
ForwardFolding in SpectrumFit is very slow

### ISSUE THREAD

**Issue by joleroi** [gammapy/gammapy#882]
After having changed the stats calculation from sherpa to gammapy, the fit became significantly slower. A wstat fit now takes ~ 3 seconds. This makes it inconvenient to simulate & fit even O(10) spectra for example in a tutorial notebook.

The problem is that the response matrix is interpolated before the multiplication with the flux vector in each fit iteration. This should be cached. Best way: Refactor ``calculate_predicted_counts`` as class. 

No need to comment at the moment, this is just a reminder for myself.

**Comment by cdeil** [comment]
The EDSIP matrix computation (involving interpolation and integration) must happen completely in the "extract" step, and the "fit" step just calls `np.dot`.

Is this what you meant already?

Your description sounds like you plan to compute the matrix and cache it at the start of the "fit" step, but that's not clean code and a good separation of computing steps, no?

**Comment by joleroi** [comment]
This has nothing to do with EDISP matrix computation. The (precalculated) EDISP matrix is reprojected on the reco energy axis of the counts vectors for each fit iteration. This was a [feature request](https://github.com/gammapy/gammapy/issues/638) by @jjlk. The reprojection even happens if the binning of the EDISP matrix and the counts is already the same (due to poor implementation). 

So what I want to cache is the EDISP matrix reprojected on the correct reconstructed energy axis.
