### ISSUE TITLE
Add 2HWC HAWC source catalog

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#887]
The 2HWC HAWC source catalog is out:
https://arxiv.org/abs/1702.02992

We should add it to [gammapy.catalog](http://docs.gammapy.org/en/latest/catalog/index.html) and http://gamma-sky.net/

@rlopezcoto - Is it available in electronic format somewhere? If no, can you please forward that request to release it, or should I write to someone asking for it?

**Comment by rlopezcoto** [comment]
@cdeil the idea was to release the electronic format of the catalog when it was accepted by ApJ. I'll get in touch with the main author and let you know if things can be speeded up.

**Comment by cdeil** [comment]
@rlopezcoto - Thanks!

Is there a 1HWC catalog? Is it published? Available in electronic format? We could start with that one.

(The results are given in tables in the PDF, so there's really no point in not releasing an electronic version when posting to ArXiv IMO. This is what Fermi-LAT does with their catalog, and then they post updated files in the coming months or even years of their catalog as they find little issues or users report them.)

**Comment by rlopezcoto** [comment]
Yes, the 1HWC was done with data from the partial array:
http://adsabs.harvard.edu/abs/2016ApJ...817....3A
I do not think there was any electronic material released with it, but I'll ask either way.

I agree with you that the electronic material could be released now, the only issue is that it was thought that the host for all this information could be the journal, therefore we need it accepted before.

**Comment by cdeil** [comment]
> Yes, the 1HWC was done with data from the partial array:
http://adsabs.harvard.edu/abs/2016ApJ...817....3A
I do not think there was any electronic material released with it, but I'll ask either way.

I see that they have their measurements in Table 4. That should be released by HAWC in electronic format, so that people interested in the data don't have to scrub the PDF, no?

There's also the option to  send the tables to http://vizier.u-strasbg.fr/ via their listed contacts, and then they become available via CDS. That might be a good option for 1HWC if HAWC doesn't want to release the data via their website for some reason.

**Comment by rlopezcoto** [comment]
I talked to Colas Riviere (riviere@umdgrb.umd.edu, @ColasRi) and he said he would produce an electronic version of the tables. I gave him your contact details, so if he does not come back to you, please let me know. 
I can try to upload the table, so I can practice the pull requests, if you want.

**Comment by cdeil** [comment]
We usually add catalog files here: https://github.com/gammapy/gammapy-extra/tree/master/datasets/catalogs

Just to not give the wrong impression: this is not urgent at all, I don't want to rush HAWC into releasing anything. I just file reminder issues such as this one whenever I hear of something that I think could be a nice addition to Gammapy.

**Comment by cdeil** [comment]
Update: 2HWC is published (http://adsabs.harvard.edu/abs/2017ApJ...843...40A) and I just now asked Colas & Ruben via email if it can be made available in machine-readable format.

**Comment by cdeil** [comment]
@ColasRi - Thanks for providing the 2HWC catalog via email!

I've put it here: https://github.com/gammapy/gammapy-extra/commit/dfa063494b13da9486abb114e81928ce9eff3e2e
and converted to ECSV because I prefer it (see `2HWC.ecsv` there and `make_2hwc.py`.

Anyone interested in adding it to Gammapy?
It's a good contribution to get started: you implement two classes as described at http://docs.gammapy.org/en/latest/catalog/index.html#how-it-works and looking e.g. at the `gamma-cat` classes as examples.

Or anyone interested to add it to http://gamma-sky.net ?
Again, it's a good contribution to get started; you write a Python function to dump it to JSON (see https://github.com/gammapy/gamma-sky/blob/master/gammasky/catalogs.py) and then write some HTML and TypeScript (which is almost like Python) again using gamma-cat as an example: https://github.com/gammapy/gamma-sky/tree/master/src/app/widgets/cat-source/cat-source-tev
(adding 2HWC will be much shorter, because there's much less info per source).

**Comment by cdeil** [comment]
Just FYI: I've tried to sell the task of adding `gammapy/catalog/hawc.py` to @pdeiml just now, he might have time in the coming days.

In any case, as with any other task in gammapy described in an issue: if someone starts working on it, leave a comment saying so and ask questions in the issue or your pull request (PR), as you prefer.

**Comment by cdeil** [comment]
@pdeiml is writing a PR adding 2HWC to gammapy: #887

**Comment by cdeil** [comment]
The 2HWC catalog was added by @pdeiml in #1108 :
http://docs.gammapy.org/en/latest/api/gammapy.catalog.SourceCatalog2HWC.html

I'm closing this issue, because the task for gamma-cat is complete.

There's https://github.com/gammapy/gamma-cat/issues/150 open discussing whether we should add 2HWC to gamma-cat.
And I've made a reminder https://github.com/gammapy/gamma-sky/issues/89 in the gamma-sky.net issue tracker that we should add it there. If someone is interested to do that, please get in touch with me or leave a comment in those issues.
