### ISSUE TITLE
SkyMask write method

### ISSUE THREAD

**Issue by JouvinLea** [gammapy/gammapy#891]
@cdeil @adonath 
Hi, I have a problem with the write method of SKyMask. When you write a SkyMask you only write the first hdu and sou see it when you try to load the fits file when io.fits
```
In [1]: from gammapy.image import SkyMask

In [2]: mask = SkyMask.read('$GAMMAPY_EXTRA/datasets/exclusion_masks/tevcat_exclusion.fits')

In [3]: mask.write("test.fits",clobber=True)

In [4]: from astropy.io import fits

In [5]: fits.open("test.fits")
Out[5]: [<astropy.io.fits.hdu.image.PrimaryHDU at 0x1087c5f50>]
```

**Comment by JouvinLea** [comment]
When you load directly the mask from gammapy extra with io.fits:
```
fits.open("/Users/jouvin/Desktop/these/test_Gammapy/gammapy-extra/datasets/exclusion_masks/tevcat_exclusion.fits")
```
, you have the 2 hdu so there is something happening in the write method...:

**Comment by cdeil** [comment]
So this file has an empty primary HDU, and the mask is stored in the second HDU:
```
$ ftlist datasets/exclusion_masks/tevcat_exclusion.fits H

        Name               Type       Dimensions
        ----               ----       ----------
HDU 1   Primary Array      Null Array                               
HDU 2   EXCLUSION          Image      Int8(3600x1800)               
```

@JouvinLea - Do you care in which HDU the mask is stored? What exactly are you trying to achieve?

---

There's also #539 which might be related and my suggestion anyways would be to get rid of `SkyMask` completely, and put it's functionality on `SkyImage`. Would SkyImage read and write solve your use case here?

I'll discuss with @adonath later today and we'll see if it's possible to improve something quickly.

**Comment by JouvinLea** [comment]
The problem is that I am creating a SkyMask with the method ```make_tevcat_exclusion_mask()```changinf the redius of the source to exclude... And when I write it I only get the primary hdu in the fits file but it womes from the write function....
