### ISSUE TITLE
Broken nddata_demo.ipynb notebook

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#901]
@joleroi - The `nddata_demo.ipynb` notebook is currently broken after the changed you did last week:
https://travis-ci.org/gammapy/gammapy/jobs/203344546#L2693

Can you please fix it?

**Comment by joleroi** [comment]
Fixed by https://github.com/gammapy/gammapy-extra/commit/67e9fa69650a6c41f7ba0f4523aadc72c2c4b626
