### ISSUE TITLE
Add notebook on Fermi-LAT data

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#902]
I've re-organised the Gammapy tutorials overview page:
http://nbviewer.jupyter.org/github/gammapy/gammapy-extra/blob/master/index.ipynb#Notebooks

One thing that was clearly missing is an example how to load Fermi-LAT data with Gammapy.
@adonath - Could you please start a small notebook so that people have a chance to find this via the Gammapy docs.

It doesn't have to do any analysis, but if it's working already, maybe move the example from
https://github.com/gammapy/gammapy-fermi-lat-data#work-with-the-data
to the notebook and plot the output?
(remove the docs example there, so that docs remain easier to maintain)

**Comment by joleroi** [comment]
Typo: If you're new to Astro **-> Astropy** (haven't used Table, SkyCoord and Time much), start here:

Other than that I like the re-orgaization, probably I would have put the data analysis examples at the top, but I don't really care

**Comment by adonath** [comment]
See https://github.com/gammapy/gammapy-extra/pull/71

**Comment by cdeil** [comment]
This is implemented. Closing this issue now.

@adonath - Thanks!
