### ISSUE TITLE
Improve setup instructions for tutorials

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#903]
So yesterday and today we gave the Gammapy tutorials for the first time to a crowd of ~ 15 people, many new to Python / Jupyter notebooks / Gammapy.

What we currently have is here:
https://nbviewer.jupyter.org/github/gammapy/gammapy-extra/blob/master/index.ipynb

The most common issues people had was setup problems:
* Running the wrong Python / Jupyter version
* Missing dependencies, such as Sherpa, reproject, uncertainties, ...
* Too old versions of dependencies, or just generally versions of dependencies where we have issues (such as the matplotlib 2.0 plotting issues, or with regions 0.2 we removed `sky_region.plot()`, but some notebook was still using it.
* Environment variables (such as GAMMAPY_EXTRA, GAMMA_CAT, GAMMAPY_FERMI_LAT_DATA) not set, or only set after they had started `jupyter-notebook` already and it wasn't visible from the notebook.

So for the tutorials next week at MPIK, and the CTA PHYS meeting in Milano, we need to make it better!

---

One thing I started was to add a separate notebook with instructions how to get set up and trouble-shoot an installation: https://nbviewer.jupyter.org/github/gammapy/gammapy-extra/blob/master/notebooks/tutorial_setup.ipynb

I think we need this, but it needs some thought and work to avoid duplicating this page:
http://docs.gammapy.org/en/latest/getting-started.html#getting-started
Maybe the two can merged or we keep them both but avoid duplication somehow?

---

Another suggestion that came up today was that there could be a "recommended" set of packages / versions defined via a `requirements.txt` or `environment.yml` file, and users are instructed how to make an environment with that for the Gammapy tutorials, but also generally for science analysis.
So this would be the "best tested" and "recommenced" set of dependencies, even if we test and analyses work for more versions.

---

Finally, I think it might be good to add something to the start of each notebook, in the "Setup" section. We do have something already sporadically, e.g. [here](https://nbviewer.jupyter.org/github/gammapy/gammapy-extra/blob/master/notebooks/astropy_introduction.ipynb#Setup) or [here](https://nbviewer.jupyter.org/github/gammapy/gammapy-extra/blob/master/notebooks/cwt.ipynb#Setup), we do already print the Astropy & Gammapy version number.

I think we need more of that:
* Import (or at least try to import) many (all?) packages that will be used and print their version numbers.
* Check via `os.environ` if the environment variables that will be used to access data are set

Basically, we should avoid users following along with a tutorial and then in the middle or towards the end notice that they have a package or environment variable missing and need to re-start. (sometimes one can install or set via `os.environ` in the notebook and keep the running one, but most users get confused when this works / doesn't work and this is not a good solution)

We already have a command line tool `gammapy-info` ... maybe that could be re-written so that it just calls a utility function, and we call the same (or extra) utility functions at the start of notebooks to check and print versions (to avoid a lot of boilerplate similar code with separate imports at the start of notebooks, distracting from the contents)

---

So making this getting started / setup part better is a large job, probably a day or two of full-time work. But it's high priority, we need to do this ASAP.

Does anyone have time to do it all?
Or in part (if yes, which)?
(Basically, pull requests welcome to make things better any time!)

Any thoughts on how exactly this should be done?
I mean short term, within the next ~ week, not an ideal system that we might implement in the coming months?

@adonath @joleroi @jjlk @registerrier @JouvinLea - Thoughts? Volunteers?

**Comment by adonath** [comment]
For the notebooks one possible improvement could be to add the required dependencies (incl. versions) and required environment variables to https://github.com/gammapy/gammapy-extra/blob/master/notebooks/notebooks.yaml (I just noticed there's already an empty section for this in the file). Every notebook would then call `check_notebook_setup('image_analysis')` in the first line and give well understandable error messages, if something is missing. 

Apart from my suggestion above, I'm :+1: to add a `enviroment.yml` and `requirement.txt` file, with our recommended set of dependencies.

**Comment by cdeil** [comment]
@adonath - I think a utility function `check_notebook_setup` would be very nice.

I've written a utility function to gather version numbers and other info in a dict a while ago:
https://gist.github.com/cdeil/5b17b031d649879761a5a44e75c94407

So `check_notebook_setup` could call into a helper function or class in Gammapy to gather that info, and then print what's missing (or "all good"). Then it would be re-usable from other parts (e.g. dumping a `provenance.json` in analysis output folders for Gammapy analyses.

Anyone have time to do something here? (It doesn't need to be comprehensive, we're not going to make it perfect on the first try anyway and will have to iterate on this in the coming months.)

**Comment by cdeil** [comment]
This was done in #1808 .

See http://docs.gammapy.org/dev/getting-started.html

Closing this old issue now.
