### ISSUE TITLE
Problem with flux points

### ISSUE THREAD

**Issue by jjlk** [gammapy/gammapy#908]
Hi @cdeil and @joleroi , 
I've got an issue when I try to compute flux points for a simulation with CTA performance file. Something is going wrong with the index of the energy bins:
```
/Users/julien/Documents/WorkingDir/Tools/python/gammapy/gammapy/spectrum/energy_group.pyc in find_list_idx(self, energy)
    308                 return idx
    309 
--> 310         raise IndexError('No group found with energy: {}'.format(energy))
    311 
    312     def find_list_idx_range(self, energy_range):

IndexError: No group found with energy: 0.0125892544165 TeV
```
Here a short example that reproduce the BUG:
```
from gammapy.spectrum.models import LogParabola, PowerLaw
from gammapy.scripts import CTAPerf
from gammapy.scripts.cta_utils import CTAObservationSimulation, Target, ObservationParameters

import astropy.units as u
import time

from gammapy.spectrum import SpectrumFit, SpectrumResult
from gammapy.spectrum import FluxPoints, FluxPointEstimator, SpectrumEnergyGroupMaker

import matplotlib.pyplot as plt

# Observation parameters
alpha = 0.2 * u.Unit('')
livetime = 5. * u.h
emin = 0.03 * u.TeV
emax = 5 * u.TeV
obs_param = ObservationParameters(alpha=alpha,
                                  livetime=livetime,
                                  emin=emin,
                                  emax=emax)

# Target, PKS 2155-304 from 3FHL
name = "2155"
# model parameters
alpha = 1.88 * u.Unit('')
beta = 0.15 * u.Unit('')
reference = 18.3 * u.GeV
amplitude = 7.7e-11 * u.Unit('cm-2 s-1 GeV-1')
model = LogParabola(alpha=alpha, beta=beta, reference=reference, amplitude=amplitude)
# redshift
redshift = 0.116
# EBL model
ebl_model_name = 'dominguez'
target = Target(name=name, model=model,
                redshift=redshift,
                ebl_model_name=ebl_model_name)

# Performance
filename = '$GAMMAPY_EXTRA/datasets/cta/perf_prod2/point_like_non_smoothed/South_5h.fits.gz'
cta_perf = CTAPerf.read(filename)

# Simulation
simu = CTAObservationSimulation.simulate_obs(perf=cta_perf,
                                             target=target,
                                             obs_param=obs_param)
# Spectrum
fit_model = PowerLaw(index = 2 * u.Unit(''),
                     amplitude = 2e-11 * u.Unit('cm-2 s-1 TeV-1'),
                     reference = 1 * u.TeV)

fit = SpectrumFit(obs_list=simu, model=fit_model)
fit.run(outdir='./out/')
result = fit.result[0]

# needed, if not it bugs
# fit.model.parameters['index'].parmin = None 

seg = SpectrumEnergyGroupMaker(obs=simu)
#seg.compute_range_safe()
seg.set_energy_range(emin=emin, emax=emax)

ebounds = simu.e_reco.value.tolist() * u.TeV
# ebounds = [7.94328228e-02, 1.25892550e-01] * u.TeV
seg.compute_groups_fixed(ebounds=ebounds)

fpe = FluxPointEstimator(
    obs=simu,
    groups=seg.groups,
    model=fit.model,
)
fpe.compute_points()

spectrum_result = SpectrumResult(
    points=fpe.flux_points,
    fit=fit.result[0],                   
)   
```

If you put: 
```
ebounds = [7.94328228e-02, 1.25892550e-01] * u.TeV
```
there is no error anymore but it takes the first bin energy low edge for the computation. 
![figure_1](https://cloud.githubusercontent.com/assets/15717586/23224219/b8e30be4-f92d-11e6-8aae-c419a40a8577.png)

Strange, right?

Thanks ++

**Comment by joleroi** [comment]
I have seen this bug before. It is related to [this function](https://github.com/gammapy/gammapy/blob/master/gammapy/spectrum/energy_group.py#L114). The bins for a given energy are searched using the bin edge, this is unstable due to float noise. Adding the ``0.999`` factor fixes this, but leads to a crash if the lowest flux points bin is equivalent to the lower bin in the energy axis (i.e. not thresholds are applied to the observation).

**Comment by jjlk** [comment]
Hi @joleroi , 
I'm not sure I understand. My `simu` object which comes from `SpectrumObservation`, has an energy threshold greater than the first energy bin (0.0125892544 GeV): 
```
In [2]: simu.lo_threshold
Out[2]: <Quantity 0.03162277862429619 TeV>
```
There must be something else, no?

**Comment by joleroi** [comment]
You are right, the method I mentioned is never called in your script. The problem however is like I described (just one layer deeper). The error is raised in ``compute_groups_fixed``
```
 File "flux_point.py", line 66, in <module>
    seg.compute_groups_fixed(ebounds=ebounds)
  File "/home/kingj/Software/gammapy/gammapy/spectrum/energy_group.py", line 131, in compute_groups_fixed
    self.groups.apply_energy_min(energy=ebounds[0])
  File "/home/kingj/Software/gammapy/gammapy/spectrum/energy_group.py", line 327, in apply_energy_min
    idx_max = self.find_list_idx(energy)
  File "/home/kingj/Software/gammapy/gammapy/spectrum/energy_group.py", line 310, in find_list_idx
    raise IndexError('No group found with energy: {}'.format(energy))
IndexError: No group found with energy: 0.0125892544165 TeV
```

There you give the reco binning of the ``SpectrumObservation``
```
ebounds = simu.e_reco.value.tolist() * u.TeV
# ebounds = [7.94328228e-02, 1.25892550e-01] * u.TeV
seg.compute_groups_fixed(ebounds=ebounds)
```

This checks which bins the energies you give fall into using [this method](https://github.com/gammapy/gammapy/blob/master/gammapy/spectrum/energy_group.py#L446) on ``EnergyRange`` (which is a temp class that @cdeil introduced, it should be merged with ``EnergyBounds``). With the current implementation the bin edges fall into no bin

```
if (self.min < energy) and (energy < self.max):
    return True
```
However, replacing e.g. the first of the ``<`` with ``<=`` does not fix the problem since then the highest bin edges falls into no bin 

```
  File "flux_point.py", line 68, in <module>
    seg.compute_groups_fixed(ebounds=ebounds)
  File "/home/kingj/Software/gammapy/gammapy/spectrum/energy_group.py", line 132, in compute_groups_fixed
    self.groups.apply_energy_max(energy=ebounds[-1])
  File "/home/kingj/Software/gammapy/gammapy/spectrum/energy_group.py", line 333, in apply_energy_max
    idx_min = self.find_list_idx(energy)
  File "/home/kingj/Software/gammapy/gammapy/spectrum/energy_group.py", line 310, in find_list_idx
    raise IndexError('No group found with energy: {}'.format(energy))
IndexError: No group found with energy: 199.5262146 TeV
```

What we can do now is change the ``__contains__`` method now to have a closed lower interval boundary and you then must use an energy binning that does not include the highest energy bounds (it would make sense anyway to only compute flux points in the safe range, no?). Which this 

```
from gammapy.utils.energy import EnergyBounds
ebounds = EnergyBounds.equal_log_spacing(simu.lo_threshold, simu.hi_threshold, 10)
seg.compute_groups_fixed(ebounds=ebounds)
```

I don't get the error anymore.


**But** there is a new error 

```
/home/kingj/Software/gammapy/gammapy/spectrum/fit.py in fit(self)
    342         self._check_valid_fit()
    343         if self.method == 'sherpa':
--> 344             self._fit_sherpa()
    345         else:
    346             raise NotImplementedError('{}'.format(self.method))

/home/kingj/Software/gammapy/gammapy/spectrum/fit.py in _fit_sherpa(self)
    379         fitresult = self._sherpa_fit.fit()
    380         log.debug(fitresult)
--> 381         self._make_fit_result()
    382
    383     def _make_fit_result(self):

/home/kingj/Software/gammapy/gammapy/spectrum/fit.py in _make_fit_result(self)
    400
    401         for idx, obs in enumerate(self.obs_list):
--> 402             fit_range = self.true_fit_range[idx]
    403             statval = np.sum(self.statval[idx])
    404             npred_src = copy.deepcopy(self.predicted_counts[idx][0])

/home/kingj/Software/gammapy/gammapy/spectrum/fit.py in true_fit_range(self)
    154             idx = np.where(binrange)[0]
    155             import IPython; IPython.embed()
--> 156             e_min = obs.e_reco[idx[0]]
    157             e_max = obs.e_reco[idx[-1] + 1]
    158             fit_range = u.Quantity((e_min, e_max))

IndexError: index 0 is out of bounds for axis 0 with size 0

```

The real issue here is that the flux point computation methods are all half-finished and completely untested. So I'm afraid there will be no satisfying solution until someone finished this up :disappointed:

**Comment by joleroi** [comment]
With https://github.com/gammapy/gammapy/pull/912 it works for the following definition of ``ebounds``

```
from gammapy.utils.energy import EnergyBounds
ebounds = EnergyBounds.equal_log_spacing(simu.lo_threshold, simu.hi_threshold, 5)
```

Is that ok for your use case?

**Comment by jjlk** [comment]
Ola @joleroi , 
Thanks! Yes it is oké, no bug anymore. Except that errors look pretty wrong (both for the spectra and the residuals).
Ideas?
![figure_2](https://cloud.githubusercontent.com/assets/15717586/23270881/a85e2aec-f9f5-11e6-878a-9868ee91435b.png)
Do you know where I could look for the problem in the code?

**Comment by joleroi** [comment]
After https://github.com/gammapy/gammapy/pull/927

Your plot looks like this

![figure_1-2](https://cloud.githubusercontent.com/assets/11678435/23408572/cc8232de-fdc8-11e6-98ad-5f7154ee8474.png)

Does this fix the issue?

**Comment by jjlk** [comment]
Hi @joleroi , 
It looks better. Could you merge #927 to make the fix available to everyone?

@cdeil and @joleroi : Question, is there a way to use dedicated methods such as Rolke or Feldman & Cousin to compute error on flux points and on residuals. And how upper limit are dealt within GammaPy? Thanks

**Comment by joleroi** [comment]
> It looks better. Could you merge #927 to make the fix available to everyone?

done

> Question, is there a way to use dedicated methods such as Rolke or Feldman & Cousin to compute error on flux points and on residuals

Answer, no(t yet)

> And how upper limit are dealt with in GammaPy? 

Not at all (yet)


Are you interested in working on this? If yes we could make a call to discuss what need to be implemented and how. Personally I don't plan to spend much time on this in the near future.

**Comment by cdeil** [comment]
@jjlk @joleroi - I think this bug has been fixed. Closing the issue now.

If there's still an action item here, please re-open.
Concerning future work / feature requests, like upper limits, please open a new issue (if one doesn't exist already).
