### ISSUE TITLE
Simplify cube exclusion example

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#916]
@adonath - Could you please have a look at this example, and see if the example code can be simplified, or if we need to add a convenience method for something like this?

http://nbviewer.jupyter.org/github/gammapy/gammapy-extra/blob/master/notebooks/cube_analysis_part2.ipynb#Define-the-mask

This is how it's currently written:
```python
exclusion_region = CircleSkyRegion(
    center=SkyCoord(83.60, 21.88, unit='deg'),
    radius=Angle(0.1, "deg"),
)

# TODO: simplify this code or introduce a utility function
# It should be a one-liner or two-liner to apply the mask to the cube
# sky_mask = counts_3d.sky_image_ref.region_mask(exclusion_region)

sky_mask_cube = SkyCube.empty_like(counts_3d)
energies = sky_mask_cube.energies(mode='edges').to("TeV")
coord_center_pix = sky_mask_cube.sky_image_ref.coordinates(mode="center").icrs
lon = np.tile(coord_center_pix.data.lon.degree, (len(energies) - 1, 1, 1))
lat = np.tile(coord_center_pix.data.lat.degree, (len(energies) - 1, 1, 1))
coord_3d_center_pix = SkyCoord(lon, lat, unit="deg")
index_excluded_region = np.where(
        (exclusion_region.center).separation(coord_3d_center_pix) < exclusion_region.radius)
#0 in the region you want to exclude and 1 outside
sky_mask_cube.data.value[:] = 1
sky_mask_cube.data.value[index_excluded_region] = 0
index_region_selected_3d = np.where(sky_mask_cube.data.value == 1)
```

**Comment by adonath** [comment]
My first suggestion would be to add `.region_mask` to the `SkyCube` class. For convenience it can take a `SkyMask` object as well or a region object. For now it will return just another `SkyCube` object.

**Comment by cdeil** [comment]
👍

**Comment by cdeil** [comment]
Moving to 0.7 milestone.

**Comment by adonath** [comment]
Just for the record:

The `SkyCube.region_mask` already exists ([see here](http://docs.gammapy.org/en/latest/api/gammapy.cube.SkyCube.html#gammapy.cube.SkyCube.region_mask)). So it's just a matter of adapting the notebook to use that method.

**Comment by adonath** [comment]
Addressed in https://github.com/gammapy/gammapy-extra/commit/02749eceb3bf57a329c463549d0301f452d20338
