### ISSUE TITLE
Simplify cube analysis tutorial notebook

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#917]
@JouvinLea  or @registerrier - Could you please simplify this notebook a bit?

http://nbviewer.jupyter.org/github/gammapy/gammapy-extra/blob/master/notebooks/cube_analysis_part1.ipynb

People are starting to copy & paste notebooks to adapt it to their analysis, so IMO notebooks should be as short and sweet as possible.

Concretely, here I think the following two helper functions should note be in the notebook:
* `make_mean_psf_cube`
* `make_mean_rmf`
* For `make_empty_cube` there's already a separate issue (#905), not to be discussed here.

To be honest, I've lost track of what functions / methods / classes we have already in Gammapy to compute mean IRFs. I think something is already available.
Can you make the existing methods in Gammapy more convenient to use?
Or add convenience wrappers similar to the functions you have here, but in Gammapy?

**Comment by adonath** [comment]
Partly adressed in https://github.com/gammapy/gammapy-extra/commit/de312f08e82191b01d5adf48692f555eb6a091ab and https://github.com/gammapy/gammapy/commit/8bd8a16212960cb4f01c139e45de160da6a3ebc7. 

Remaining ToDo's:

- [ ] Use observation selection by `OBS_ID`
- [ ] Cut long lines

**Comment by cdeil** [comment]
This old notebook was removed (see https://github.com/gammapy/gammapy/issues/925#issuecomment-386992338)

New code is work in progress, the equivalent example for a 3D analysis and mean PSF / EDISP will appear here: http://docs.gammapy.org/dev/notebooks/analysis_3d.html
