### ISSUE TITLE
Change 3FHL source catalog flux points implementation?

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#918]
@jjlk added in #868 the [SourceCatalog3FHL](http://docs.gammapy.org/en/latest/_modules/gammapy/catalog/fermi.html#SourceCatalog3FHL) and [SourceCatalogObject3FHL](http://docs.gammapy.org/en/latest/api/gammapy.catalog.SourceCatalogObject3FHL.html#gammapy.catalog.SourceCatalogObject3FHL) classes.

On Tuesday Arache asked me how exactly the flux points are filled, and we looked at `source.data` and saw that the `nuFnu` columns were accessed from the `flux_points` method. Then we looked at the 3FHL paper description of the catalog columns, and were confused when the `nuFnu` columns weren't described there.

What's going on is that the 3FHL spectral point format is different from previous catalogs, and  @jjlk added the `nuFnu` columns on table read, I think so that the code is more similar to the other catalog classes?

@jjlk - Do you think a change in implementation where no extra columns are added on table read (so that `source.data` reflects the columns described in the paper), and then computing extra things via methods and properties on the `SourceCatalogObject3FHL` object is possible? Do you agree it's better to do it that way, or do you prefer the current implementation?

**Comment by cdeil** [comment]
This was partly cleaned up in 07cb7444855186b384a48f1898247c2e0785a9d6 as part of #978 .

Remaining task:
- [ ] Remove https://github.com/cdeil/gammapy/blob/07cb7444855186b384a48f1898247c2e0785a9d6/gammapy/catalog/fermi.py#L660
- [ ] Remove `eflux`? Or keep it, but document which is to be used? Or maybe a second property `flux_points_eflux` would be best?

Assigning to myself and moving to the 0.7 milestone.

**Comment by cdeil** [comment]
@adonath - Could you please have a look at this issue and see if everything is OK or some change should be done? If this doesn't affect your work using 3FHL, or you don't want to deal with it now, please defer to v0.10 and unassign yourself.

**Comment by adonath** [comment]
Resolved by #1903.
