### ISSUE TITLE
No explanatory error if cython is missing

### ISSUE THREAD

**Issue by tibaldo** [gammapy/gammapy#930]
I was trying to run the image_pipe notebook from the latest gammapy dev version. When doing
from gammapy.scripts import StackedObsImageMaker
I was getting an error
```
ImportError                               Traceback (most recent call last)
<ipython-input-2-3a69714fe844> in <module>()
      5 from gammapy.data import DataStore
      6 from gammapy.image import SkyImage, SkyMask
----> 7 from gammapy.scripts import StackedObsImageMaker
      8 from gammapy.utils.energy import Energy

/Users/ltibaldo/anaconda/envs/gammapy-tutorial/lib/python2.7/site-packages/gammapy-0.6.dev4261-py2.7-macosx-10.7-x86_64.egg/gammapy/scripts/__init__.py in <module>()
     20 from .image_model_sherpa import *
     21 from .image_pipe import *
---> 22 from .image_ts import *
     23 
     24 from .cube_background import *

/Users/ltibaldo/anaconda/envs/gammapy-tutorial/lib/python2.7/site-packages/gammapy-0.6.dev4261-py2.7-macosx-10.7-x86_64.egg/gammapy/scripts/image_ts.py in <module>()
      6 from ..utils.scripts import get_parser, set_up_logging_from_args, make_path
      7 from ..image import SkyImage, SkyImageList
----> 8 from ..detect import compute_ts_image_multiscale
      9 
     10 __all__ = ['image_ts']

/Users/ltibaldo/anaconda/envs/gammapy-tutorial/lib/python2.7/site-packages/gammapy-0.6.dev4261-py2.7-macosx-10.7-x86_64.egg/gammapy/detect/__init__.py in <module>()
      7 from .iterfind import *
      8 from .matched_filter import *
----> 9 from .test_statistics import *
     10 from .lima import *

/Users/ltibaldo/anaconda/envs/gammapy-tutorial/lib/python2.7/site-packages/gammapy-0.6.dev4261-py2.7-macosx-10.7-x86_64.egg/gammapy/detect/test_statistics.py in <module>()
     19 from ..image import measure_containment_radius, SkyImageList, SkyImage
     20 from ..image.models import Shell2D
---> 21 from ._test_statistics_cython import (_cash_cython, _amplitude_bounds_cython,
     22                                       _cash_sum_cython, _f_cash_root_cython,
     23                                       _x_best_leastsq)

ImportError: cannot import name _x_best_leastsq
```
It turns out in the end I did not have cython installed, but the error from the import was not easy to interpret for me, and there was no error/warning thrown when installing gammapy without cython.

Could we have a clearer error/warning or add cython as requirement to setup.py

**Comment by cdeil** [comment]
I'm not sure what happened here, how you ended up with this broken install of Gammapy in site-packages.

Cython is used to generate C code files when you build / install the dev version.
If you don't have Cython, then usually there's an error ending with a statement about missing Cython.

Then when you have Gammapy installed, there's a compiled C extension, and Cython is never used at import / run time.

So I'm not sure what exactly happened here or how to make it better.

If you have the time, you could start fresh:
* open a new terminal
* activate some Python environment where you don't have Cython installed
* git clone gammapy in a new folder (e.g. `/tmp`)
* `pip install .` or `python setup.py install`
* Does it really install a broken Gammapy (i.e. without the C extension for TS maps)?
* It should error out with an error message (that might be a bit cryptic, but should mention Cython)
* Copy full console output into a log, e.g. here: https://gist.github.com/
* Put the link to that log in this issue, and I'll have a look.

**Comment by joleroi** [comment]
FYI:

I encounter this error quite frenquently. I usually goes away with

```
make clean
python setup.py build
python setup.py develop
```

**Comment by cdeil** [comment]
@tibaldo - you could also try
```
pip uninstall gammapy
```
a few times , or if that doesn't solve the broken install issue you can use this to get rid of the broken install in your site-packages:
```
rm -r /Users/ltibaldo/anaconda/envs/gammapy-tutorial/lib/python2.7/site-packages/gammapy*
```
Let us know how it goes ...

**Comment by cdeil** [comment]
Closing this old issue now.

@tibaldo or anyone else - if you still see this issue, see the info in the comments above and if that doesn't help, please leave a comment here and we'll re-open, or open a new issue.
