### ISSUE TITLE
Broken conda install for docs build on Readthedocs

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#934]
The conda install for the docs build on Readthedocs has been broken for over a week.

* Last build that passed: http://readthedocs.org/projects/gammapy/builds/5044590/
* Last build as of now, failing: http://readthedocs.org/projects/gammapy/builds/5101299/

There's a `CondaRuntimeError` when trying to install the `yaml` conda package.

I will try to reproduce this locally now, and fix by making commits to our config files:
* https://github.com/gammapy/gammapy/blob/master/readthedocs.yml
* https://github.com/gammapy/gammapy/blob/master/docs/environment.yml
or by doing the "wipe" for Gammapy on RTD.

We need our docs to reflect all the work that has been done in the past two weeks or users will be super confused, so I'm giving this priority.

@bsipocz - Have you seen this error before? I think it's peculiar to our conda setup on RTD, no?

**Comment by cdeil** [comment]
This is a known issue on RTD since a week or two, see e.g.:
https://github.com/rtfd/readthedocs.org/issues/2651

As far as I can see, there's no simple workaround available.
Changing the docs build on RTD to not use conda (but just pip like in the good old days) would probably work.
I might attempt this tonight, but only if I have other things ready for tomorrow.

@adonath - The other thing that would be nice to have for tomorrow is Binder.
Similarly, we could go back to Python 2 and try to get it to work.
But I'm not sure if that would take 30 min or 3 hours and if it's the best way to spend our time.

I would say both of those things would be nice and important to have, but not a must, we shouldn't stress out just because of the presentation on Monday.

**Comment by adonath** [comment]
@cdeil FYI: I'll take 30 min. now and try to fix the Binder build.

**Comment by cdeil** [comment]
Fixed.

* https://readthedocs.org/projects/gammapy/builds/5335869/
* http://docs.gammapy.org/en/latest/

So now it's worth working on the Gammapy docs again -- your changes will show up!

I'll check a few more things and then close this issue tomorrow morning.

**Comment by cdeil** [comment]
Closing this now, seems to be all OK.

I changed several things, so I'm not sure what fixed the build in the end.
But I think it was disabling "use virtualenv" and "use global site-packages" in the RTD settings page.

And the conda issues on RTD (see https://github.com/rtfd/readthedocs.org/issues/2651) had been resolved in the meantime.
