### ISSUE TITLE
Use uncertainties nominal_value and std_dev attributes

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#938]
@adonath - A while ago I was puzzled by the gamma-cat code when I saw the `.n` and `.s` properties being accesses. I didn't know what they were, and whether that was something new in our parameter class or uncertainties.

It's from uncertainties:
```python
>>> import uncertainties
>>> a = uncertainties.ufloat(nominal_value=1, std_dev=2)
>>> a.n
1.0
>>> a.s
2.0
>>> a.nominal_value
1.0
>>> a.std_dev
2.0
```

Can we please everywhere in Gammapy change to the more explicit `.nominal_value` instead of `.n` and to `.std_dev` instead of `.s`. Especially since we only use it very rarely, it'll be hard for devs to remember what it is with the one-letter abbreviation. I just now again saw `.n` in a test.

@adonath - You wrote the code, so I wanted to check with you first if you're OK with the change. Thoughts?

**Comment by adonath** [comment]
I used `.n` and `.s` just for convenience and for me as a frequent user of `uncertainties` I didn't make a large difference. But I totally see the advantage if you're not familiar with the code, so I think it's a good idea to change it.

**Comment by cdeil** [comment]
I reviewed the code, this has been fixed.
