### ISSUE TITLE
Reflected regions errors

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#939]
I managed to make an example analysis for CTA:
https://github.com/gammapy/gammapy-extra/blob/ed2c653df95580f001db1173c67a8bf28e1efa8e/notebooks/cta_data_analysis.ipynb

We now have a nice example of three CTA runs that we can use for other notebooks as well.
One major thing to fix would be the background model.

However, short-term, I've noticed two issues with the reflected regions analysis:
- Sometimes an `UnboundLocalError` appears when plotting the regions (see notebook). I think that happens when there is a run where no off regions are found? Can't you skip those runs for plotting?
- If the mask is too small, an IndexError appears. This should be changed, so that it works, no? I think assuming that pixels outside the mask are valid reflected regions is fine.

@joleroi - Could you please look at those two issues and try to make it better?

**Comment by joleroi** [comment]
> Sometimes an UnboundLocalError appears when plotting the regions (see notebook). I think that happens when there is a run where no off regions are found? Can't you skip those runs for plotting?

I've never seen this error. Can you provide an example, please?

**Comment by cdeil** [comment]
Did you know about this?
http://docs.gammapy.org/en/latest/detect/index.html#computation-of-li-ma-significance-images

Maybe we should call this?
Or did you do the significance image computation with kernels by hand intentionally to teach people something lower-level?

**Comment by cdeil** [comment]
I think the reflected regions issues are resolved?
@joleroi - Thanks!

Current status: https://github.com/gammapy/gammapy-extra/blob/master/notebooks/cta_data_analysis.ipynb

One more thing that would be nice would be to put the cell that computes a significance image into it's own section, and to make a TS image instead (if it's fast enough), and to run findpeaks from photutils on it, and to plot markers on the two brightest sources.
I don't have time today. @adonath - if you are interested, please do it.
Otherwise I'll add this in the coming days.

**Comment by joleroi** [comment]
> I think the reflected regions issues are resolved?
@joleroi - Thanks!

I wouldn't call it resolved. I put a workaround for the plotting issue. And the maps are still very large. So please leave this open as a reminder to properly fix this.

**Comment by joleroi** [comment]
Fixed in https://github.com/gammapy/gammapy/pull/972
