### ISSUE TITLE
Incorrect image plot with Matplotlib < 2

### ISSUE THREAD

**Issue by TarekHC** [gammapy/gammapy#944]
As reported in Issue #823, I see weird features when plotting images.

Currently using matplotlib 1.5.1:

If I execute:
```python
import matplotlib.pyplot as plt

import astropy.units as u
from astropy.coordinates import SkyCoord
from astropy.convolution import Ring2DKernel, Tophat2DKernel

from gammapy.data import DataStore
from gammapy.image import SkyImage, SkyImageList
from gammapy.detect import KernelBackgroundEstimator as KBE


data_store = DataStore.from_dir('$GAMMAPY_EXTRA/datasets/hess-crab4-hd-hap-prod2/')
source_pos = SkyCoord(83.633083, 22.0145, unit='deg')
ref_image = SkyImage.empty(
    nxpix=400, nypix=400, binsz=0.02,
    xref=source_pos.ra.deg, yref=source_pos.dec.deg,
    coordsys='CEL', proj='TAN',
)
# Make a counts image for a single observation
events = data_store.obs(obs_id=23523).events
counts_image = SkyImage.empty_like(ref_image)
counts_image.fill_events(events)

# If you have internet access, you could also use this to define the `source_pos`:
from astropy.coordinates import SkyCoord
source_pos = SkyCoord.from_name('crab')
norm = counts_image.plot_norm(stretch='sqrt', min_cut=0, max_cut=0.3)
fig, axes, cbar = counts_image.smooth(radius=0.1 * u.deg).plot(norm=norm, add_cbar=True)
```

It plots a beautiful counts map. But if you add a cross in the position of the Crab Nebula:

```python
axes.plot(source_pos.ra.deg, source_pos.dec.deg, marker='+', color='white', mew=1, ms=30,  transform=axes.get_transform('fk5'))
```

The plot is distorted, but ONLY if you are using an old Matplotlib version (not working for Matplotlib: 1.5.1, and working properly for @mackaiver in 2.0.0).

**Comment by adonath** [comment]
@TarekHC Thanks for reporting this issue.

Could you re-run the following script with the latest gammapy version and post the output (including image) here?

```python
import matplotlib
import wcsaxes
import gammapy
import astropy

print('matplotlib version: ', matplotlib.__version__)
print('wcsaxes version: ', wcsaxes.__version__)
print('gammapy version: ', gammapy.__version__)
print('astropy version: ', astropy.__version__)

import astropy.units as u
from astropy.coordinates import SkyCoord
from astropy.convolution import Ring2DKernel, Tophat2DKernel

from gammapy.data import DataStore
from gammapy.image import SkyImage, SkyImageList

data_store = DataStore.from_dir('$GAMMAPY_EXTRA/datasets/hess-crab4-hd-hap-prod2/')

source_pos = SkyCoord(83.633083, 22.0145, unit='deg', frame='fk5')

ref_image = SkyImage.empty(
    nxpix=400, nypix=400, binsz=0.02,
    xref=source_pos.ra.deg, yref=source_pos.dec.deg,
    coordsys='CEL', proj='TAN',
)
# Make a counts image for a single observation
events = data_store.obs(obs_id=23523).events
counts_image = SkyImage.empty_like(ref_image)
counts_image.fill_events(events)

norm = counts_image.plot_norm(stretch='sqrt', min_cut=0, max_cut=0.3)
fig, axes, cbar = counts_image.smooth(radius=0.1 * u.deg).plot(norm=norm, add_cbar=True)
axes.plot(source_pos.ra.deg, source_pos.dec.deg, marker='+', color='lime', mew=3, ms=30,
          transform=axes.get_transform('fk5'))
plt.savefig('crab.png')
```

For me this gives the following output:
```bash
matplotlib version:  1.5.3
wcsaxes version:  0.9
gammapy version:  0.6.dev4313
astropy version:  1.3
```

And a correct image:
![crab](https://cloud.githubusercontent.com/assets/3715928/23657849/5af7142c-0340-11e7-897a-9b9951e164d8.png)

**Comment by TarekHC** [comment]
@adonath, if I execute your code, I do get the correct png image.

But if I execute the code in a jupyter notebook, the image gets distorted.

![image](https://cloud.githubusercontent.com/assets/7864276/23669353/1bf18734-0364-11e7-9e56-e487b80dc4da.png)

Any idea why?

**Comment by cdeil** [comment]
@TarekHC @adonath - What's the status or conclusion here?

@TarekHC - Maybe you have to call `set_xlim` and `set_ylim` as shown here?
http://docs.astropy.org/en/latest/visualization/wcsaxes/initializing_axes.html

@adonath - Is there anything we could / should do in the Gammapy plotting methods to make this better?

I want to release Gammapy 0.7 next week, and if possible, clean out as many open issues and fix bugs / make little improvements as possible.

**Comment by adonath** [comment]
From the back of my head: I think what happened here was that the image was rescaled whit the call to `ax.plot()` or `ax.scatter()` to add the marker. By default there is now a call to `ax.autoscale(enable=False)` in  [SkyImage.plot()](https://github.com/gammapy/gammapy/blob/master/gammapy/image/core.py#L935), which should fix this issue. But it would be great to have this confirmed by @TarekHC, otherwise I think we can close this issue...

**Comment by cdeil** [comment]
I'm closing this old issue.

@TarekHC - Please comment or re-open if you still see this issue and the last comment by @adonath  doesn't help to resolve it.

**Comment by TarekHC** [comment]
Sorry for the delay. I updated gammapy and indeed the glitch is solved. 
Cheers!
