### ISSUE TITLE
Rewrite 3D background class

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#947]
For CTA we urgently need support for 3D background IRFs in this format:
http://gamma-astro-data-formats.readthedocs.io/en/latest/irfs/background/index.html#bkg-3d-format
Example file for testing is here:
https://gist.github.com/cdeil/2b4561935f2a65d988d7f8e28aeaee8b

We have these old classes:
http://docs.gammapy.org/en/latest/api/gammapy.background.FOVCube.html
http://docs.gammapy.org/en/latest/api/gammapy.background.FOVCubeBackgroundModel.html
https://github.com/gammapy/gammapy/blob/master/gammapy/background/fov_cube.py

I think the quickest would be to throw those away (or hide them via `_` for now) and to write a new class that uses NDDataArray.
There's also some overlap with `SkyCube` and `EnergyOffsetArray`.

A first milestone could be to have working code to fill a SkyCube with this background, for a given pointing position.

If there is a volunteer to work on this, great!
Otherwise I'll do this next week.

**Comment by adonath** [comment]
@cdeil When I understood correctly there a two separate tasks in this issue:

* Read the precomputed CTA background IRFs and create background model cube and images from it.
There I think it would be nice to introduce a `FOVBackgroundEstimator` class, that just takes a list of observations and computes background cubes/images given a reference cube/image.

* Create background models from the scratch using a list of off runs. Which is a bigger task and probably makes it necessary that we introduce further classes such as `AcceptanceProfile` or similar.

**Comment by cdeil** [comment]
This is partly done: see [gammapy.irf.Background3D](http://docs.gammapy.org/en/latest/api/gammapy.irf.Background3D.html) and [gammapy.cube.make_background_cube](http://docs.gammapy.org/en/latest/api/gammapy.cube.make_background_cube.html)

There's more to add for this new class, and the old classes in `gammapy.background` need to be removed, so keeping this issue open for now and moving milestone to v0.8.

**Comment by cdeil** [comment]
Just to close out the discussion in https://github.com/gammapy/gammapy/issues/987#issuecomment-342015048 and put a reminder: Another action item here is to add a `gammapy.irf.Background2D` class, that is very similar to the existing `gammapy.irf.Background3D`, except that it has a `THETA` axis instead of `DETX` and `DETY`. I.e. there should be two classes corresponding to the two formats defined here:
http://gamma-astro-data-formats.readthedocs.io/en/latest/irfs/full_enclosure/bkg/index.html

There should be a method to evaluate the 2D also on detx,  dety (compute `theta = np.sqrt(detx * detx + dety * dety` and call the normal evaluate for 2D, or some other way to have a uniform API that high-level code like `make_background_cube` can call into without having to care what type of background object it is.

**Comment by cdeil** [comment]
This issue is mostly done. Closing. Lea added a Background2D class.

Proper transform to FOV coordinates in analysis still needs to be done, for that I'll open a new issue with a description.
