### ISSUE TITLE
Bug in calculate_predicted_counts if e_reco different from e_true

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#953]
While working on light curve computation in #950, @jjlk found an issue today, which I think is a serious bug in `gammapy.spectrum.calculate_predicted_counts`.

It seems that it gives incorrect results if `e_reco` is different from `e_true`.

To reproduce, you can use the example from the current docstring (slightly modified):
```python
import numpy as np
import astropy.units as u
from gammapy.irf import EnergyDispersion, EffectiveAreaTable
from gammapy.spectrum import models, calculate_predicted_counts

e_true = np.logspace(-2, 2.5, 109) * u.TeV
e_reco = np.logspace(-2, 2, 73) * u.TeV
aeff = EffectiveAreaTable.from_parametrization(energy=e_true)
edisp = EnergyDispersion.from_gauss(e_true=e_true, e_reco=e_reco, sigma=0.3)
model = models.PowerLaw(index=2.0,
                        amplitude=1e-12 * u.Unit('cm-2 s-1 TeV-1'),
                        reference=1 * u.TeV)
livetime = 1 * u.h
n_reco_energy_bins = 100
e_reco_desired = np.logspace(-1, 2, n_reco_energy_bins) * u.TeV
npred = calculate_predicted_counts(
    model=model,
    aeff=aeff,
    edisp=edisp,
    livetime=livetime,
    e_reco=e_reco_desired,
)
print(npred.data.data.sum())
# print(npred.data)
# print(e_reco_desired)
# print(npred.data.data)
```
Currently for `n_reco_energy_bins = 100` this gives:
```
25.493127959641352 ct
```
and then when putting `n_reco_energy_bins = 1000` (i.e. 10 times more reco energy bins) I get roughly 10 times more npred:
```
257.2500294448974 ct
```
where really it should be roughly the same `npred`.

When putting `edisp=None`, the correct behaviour occurs, so looking at the implementation of `calculate_predicted_counts` this shows that this is a problem with `EnergyDispersion.apply`.

@joleroi - You implemented the current version of `EnergyDispersion.apply` in #864 (but unfortunately didn't add a test that shows if it's working or not).

@joleroi or @registerrier - Does one of you have time to fix this bug and add a regression test (using simple constant AEFF where the true answer is known for npred)?

Really, looking at `EnergyDispersion.apply`, it's not clear to me what the concept is. At the moment `EnergyDispersion` is a mix between being a PDF (probability density function) that is interpolated, and a PMF (probability mass function) with integral probabilities per bin, no? The interpolation / integration should at the very least be split out from the matrix multiplication in `apply`, no? Can you please review the docstring and code and tests for this class to make sure it's well-done? (this is a core piece in Gammapy that needs to be correct or many users will get incorrect results for different cases when e_true and e_reco binning is not the same.

**Comment by jjlk** [comment]
Hi @cdeil, @registerrier , @joleroi ,
Just a comment. It seems that I get, consistant results when I compute the expected excess with the default binning of the reconstructed energy (from the rmf) and, as Christoph said, strange results when i use a different binning for the reconstructed energy. For example, if use the same energy range as the rmf but with a number bins X times greater, I get ~X times the expected excess.

**Comment by joleroi** [comment]
Related https://github.com/gammapy/gammapy/issues/882

**Comment by joleroi** [comment]
I am :+1: to separate the interpolation / integration of the energy dispersion and then do all later operation on pure np.arrays (or wrapper classes holding such) for both speed and consistency. The reco energy of the predicted counts vector would then always be the same as in the energy dispersion matrix. There was, however, this features request by @jjlk a while ago https://github.com/gammapy/gammapy/issues/638. Do you agree to remove this convenience? You can still create an energy dispersion matrix using the interpolation methods on the PDF class, but it's one more step.

**Comment by cdeil** [comment]
I'm +1 to make a class to hold the EDISP matrix. It has energy axes and FITS serialisation and plotting, so a class makes sense, no?

For me, an extra step and requiring that people explicitly prepare a new EDISP matrix every time they want to change energy binnings is fine. If really needed, conveniences can be added back later, or maybe just docs examples are needed showing how to do this.

**Comment by joleroi** [comment]
TODO
* [ ] Add ``EnergyDispersionMatrix`` class holdig a numpy array (no NDData with interpolation). This should have all plotting methods attached to it
* [ ] To the same separation also for the effective area (even though there it's mostly cosmetics)

**Comment by joleroi** [comment]
We decided to not do the second TODO because it's trivial.
