### ISSUE TITLE
Update LightCurveEstimator

### ISSUE THREAD

**Issue by joleroi** [gammapy/gammapy#982]
https://github.com/gammapy/gammapy/pull/972 breaks the light curve estimator. I list the steps that are necessary to fix it here

* [ ] Remove hard coupling from ``SpectrumExtraction``: At the moment the ``LightCurveEstimator`` takes a ``SpectrumExtraction`` instance as only argument. This coupling is very strong, e.g. the data (i.e. the ``DataStoreObservation`` is accessed via the ``SpectrumExtraction``).
* [ ] From what I understand all that's needed for the lightcurve estimation  is a ``BackgroundEstimate`` containing the on and off events (at the moment only off events, but if it leads to better reusable code we can also attach the on event list to this) and some information about time intervals. Possibly also energy thresholds, but these should be taken as plain  ``astropy.Quantities`` (if someone want to use some safe energy thresholds there could be a convenience wrapper)
* [ ] Remove methods like [_get_on_event_list](https://github.com/gammapy/gammapy/blob/master/gammapy/time/lightcurve.py#L140) this is now provided as input

As far as I can see these are the only steps necessary to bring back the current functionality. There is of course more refactoring that could be done

* [ ] The algorithm is coded in one huge function [compute_flux_point](https://github.com/gammapy/gammapy/blob/master/gammapy/time/lightcurve.py#L213), this could be split up to smaller function to make it better readable.

**Comment by joleroi** [comment]
I won't have time to do this in the near future

**Comment by joleroi** [comment]
UPDATE: #972 was not merged so the Lightcurve stuff continues to work. So whether or not we implement the changes suggested here is a mere question of API design.

**Comment by cdeil** [comment]
@joleroi @dcfidalgo - Close this issue and discuss in #1451 ?

**Comment by dcfidalgo** [comment]
> Close this issue and discuss in #1451 ?

:+1:

**Comment by cdeil** [comment]
@joleroi - Please review and comment on #1451.
