### ISSUE TITLE
Reimplemement analytical solutions for `.energy_flux_error()` and `.integral_error()`

### ISSUE THREAD

**Issue by adonath** [gammapy/gammapy#984]
I think we should reimplement analytical solution for `.energy_flux_error()` and `.integral_error()` for all spectral models, where these are known. Currently the default is, that these quantities are computed numerically, which gives raise to few issues e.g. https://github.com/gammapy/gamma-cat/issues/107

**Comment by cdeil** [comment]
Moving to milestone: 0.7

**Comment by cdeil** [comment]
@adonath - In light of the recent discussions on model evaluation and uncertainties (see #2255) - do you still think we should put effort into analytical solutions for the 2-3 models where this exists?

I would suggest to just close this old issue and we focus our efforts on the generic numerical implementations in the base class in the coming weeks. (Or at least to un-assign yourself if you don't plan to work on it in the near future.)

**Comment by adonath** [comment]
The original issue (https://github.com/gammapy/gamma-cat/issues/107) that triggered this issue should be fixed using the approach in #2255 as well, because we always go through `.evaluate()`.
