### ISSUE TITLE
Implement ASMOOTH

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#99]
Reference:
- http://adsabs.harvard.edu/abs/2006MNRAS.368...65E
- http://hesperia.gsfc.nasa.gov/ssw/gen/idl/util/asmooth.pro (IDL, license unclear)
- http://cxc.harvard.edu/ciao/ahelp/csmooth.html (same algorithm in C, license unclear)

Probably shouldn't go in Gammapy ... either Astropy or photutils or scikit-image or here:
https://github.com/weaverba137/pydl/blob/master/pydl/smooth.py

The ASMOOTH algorithm was used for the [2FHL](http://adsabs.harvard.edu/abs/2015arXiv150804449T) publication (Figures 1 & 5). It's not written in the paper, but stated by Marco Ajello via email.

**Comment by cdeil** [comment]
@adonath - I'm assigning this issue to implement ASMOOTH you and to the 0.5 milestone.

**Comment by adonath** [comment]
I'm closing this one the initial implementation has been addressed in #746. Remaining work for ASmooth is documented in  #751 and #752
